### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by JavaJens** [WhisperSystems/Signal-Android#1000]
As #127 is a little overloaded and goes beyond the technical, I thought to open up this issue to gather implementation details and coordinate efforts for this.

Support for WebSockets is already present on the server, so the idea is to use WebSockets on Android as well (for now instead of a possible more suited protocol like MQTT)

@geileszeuch mentioned a guide on how to use websockets in native apps: http://www.elabs.se/blog/66-using-websockets-in-native-ios-and-android-apps

However I don't think this would be a good guide as it doesn't talk about Wake/Sleep and connection loss.
This article list several issues one has to deal with in a mobile enviroment: http://dalelane.co.uk/blog/?p=1599
I believe the approach mentioned here http://stackoverflow.com/a/16602970 to be reasonable, if I find the time I will give it a try.

I guess for developing this one has to run an own server, as WS is disabled per default.

So please, if you have a question, concern or are already working on this: comment!

**Comment by jensMF** [comment]
Is there any progress in websocket implementation since last post (28 days ago)?
Is it possible to build TextSecure with websocket and communicate with people that have the official gcm build?
If not, is it possible to unregister from TextSecure push with websocket? I tried to unregister, but my friends with official gcm build autocratically send me push messages and I can't receive thus...

**Comment by JavaJens** [comment]
Sorry, there has been so much silence. I didn't have the time to further work on this.
@Selaron and @marciomr Please open up an issue on my fork, if possible with logcat.

@jensMF As far as I know, it is possible to communicate with the official GCM client, but you are not supposed to run this code against the production server, staging only. At least that is what I read from moxies comment some while back.
Regarding unregistering...make sure that you are running on the same server (production vs. staging) and if that still not works, try to get a debug log and open up an issue on my fork.
To me it wasn't exactly clear how unregistering works, as the Wiki Page only specifies unregistering of GCM or APN codes.

**Comment by patcon** [comment]
@jensMF I'd say just install the official app, re-register, and then unregister for push notifications using the standard advice:
https://github.com/WhisperSystems/TextSecure/issues/845#issuecomment-36313124

**Comment by jensMF** [comment]
@JavaJens Thanks for your answer, but how can I check the server where I'm running textsecure on? And how can I change it? (I tried to unregister with websocket version 2.2.0 because I registered with that one, that should run on the same server cause I used the same apk) For the last try i used the latest version of your fork (I checked out the repository, installed everything needed via android-studio and did ./gradlew build). I can send masseges, but don't receive messages…

@patcon I don't have gapps and I don't want to install them…

**Comment by ddast** [comment]
@jensMF You can unregister from TextSecure on this website: https://whispersystems.org/textsecure/unregister/

**Comment by JavaJens** [comment]
@jensMF If you haven't changed anything then you are using the Staging (aka correct) server.
However I never touched the version number, hence I would look at the commit checksums for verification.

You can check the server in the Release.java file. If you need more help, open a ticket on my fork or send me a mail.

**Comment by jensMF** [comment]
Thanks @ddast, that worked well.

@javajens is it possible communicate whith playstore-version when being on the staging server?

**Comment by JavaJens** [comment]
@jensMF As fas as I know, the two servers are not federated. That is if you
register against the staging server, people on the other server don't know
that you use TS and can't send you messages.

In order to communicate with them, you would need to change the
Release.java file, but shouldn't be using development code against a
production system.

**Comment by ThomasWaldmann** [comment]
+1 for textsecure without google services. can't use it currently due to that.

**Comment by jensMF** [comment]
Thanks for all the information, it helped me out very well. Are there any news about websocket or plans getting away from gcm? Maybe @moxie0 could say something about it? Or does @JavaJens knows something?
Thanks in advance.

**Comment by h-2** [comment]
I recently tried the last version in @grote 's repository. It still drains a lot of battery. If there is any testing and reporting that I could do to help, please let me know. All Jabber-Clients I know, Kontalk, Telegram ... all have some mechanism that has only a slight influence on the battery life...

**Comment by JavaJens** [comment]
I don't know which version you were using, but I do know that the server has a connection timeout of 15s. This, in my opinion, is the only reason why there is such an enormous battery drain. Compare it to GCM which is said to have a timeout of 15m [1] (however I don't know if this is outdated info). The server side of things will most likely not be updated, due to limited server resources: https://github.com/WhisperSystems/TextSecure-Server/issues/27.

About the progress of integrating WebSocket in TextSecure; I know that my initial PR was not very good and required lots of refactoring, furthermore there were some changes planned that would break the communication again. Now I've lost most interest in it as I don't know if/when it will break again and if it would ever be accepted. I don't know how the crew at Signal deals with battery issues, maybe they have a completely different way (like only establish the connection on APN or if the app is focus), but it might be worth to check that out.

So again, feel free to pick up my work, I'd be more that happy to assist :)

[1] https://productforums.google.com/forum/#!msg/nexus/fslYqYrULto/lU2D3Qe1mugJ

**Comment by JavaJens** [comment]
If I see it right there is support for WebSocket on the roadmap for milestone 2.6 https://github.com/WhisperSystems/TextSecure/milestones/v2.6.0

See PR https://github.com/WhisperSystems/TextSecure/pull/2423

**Comment by schiesbn** [comment]
This sounds awesome! Is there any estimation when 2.6 will be released?

**Comment by jeremymasters** [comment]
Sometime after 2.5.3, sometime before 2.6.1. :)

**Comment by moxie0** [comment]
That is not "websocket support" in the sense you want, which is still a ways off.

**Comment by devurandom** [comment]
@moxie: What is the purpose of #2423? I am unable to make it out from the diffs.

**Comment by JavaJens** [comment]
I believe it is to receive messages but triggered by gcm. This would prevent messages from being lost. 

Haven't checked thoroughly though.

**Comment by h-2** [comment]
> So again, feel free to pick up my work, I'd be more that happy to assist :)

Thanks for your work thus far, JavaJens. But to be honest, judging from this thread and other conversations, I feel like the overall climate here is not very friendy towards suggestions or even pull requests, so for now I will spend what free time I have on other Free Software projects like Kontalk [no offence to anyone here, its of course their choice where to put priorities].

**Comment by jensschulz** [comment]
Would it be a possible alternative to implement polling (e.g. every 15 minutes) until websocket support is available? I use this on Threema and it's almost as good as push and there is no heavy battery drainage. The load on the server shouldn't be too heavy as only few people are not using GCM. I really would like to switch to TextSecure, but as many others won't install Google Services for it.

**Comment by ThomasWaldmann** [comment]
@jensschulz maybe open a separate ticket for that and link to it from here? would also like such a feature!

**Comment by JavaJens** [comment]
I've started a new branch that uses the WebSocket mechanism as it is currently implemented.
Therefore the changes are very small.
Feel free to check it out: https://github.com/JavaJens/TextSecure/tree/feature/websocket-reborn
(note that it requires a local build of libtextsecure, see README)

**Comment by moxie0** [comment]
in 3.30.0
