### ISSUE TITLE
After restore: Groups are completely broken! - Getting messages, can't leave, can't write!

### ISSUE THREAD

**Issue by Waboru** [WhisperSystems/Signal-Android#1048]
The bug:
I deleted all my data from Textsecure while I was in a group and registered again with the same number. After that, I get the messages of the old group which is just unknown since then and I can't leave or write to this group. It's showing that there aren't any members in the group.
My mates can't kick me from the group either.

This is how the bug was caused:
I joined a group, made an encrypted backup, deleted all data of the app, restarted it and restored the backup. The restore failed, all messages were broken.
I still get messages of the group, the group is unknown, I can't leave or join the group, but receive all messages they send.

Suggestion:
Let me see which groups I joined with my number and let me leave them (even if I restored!)

**Comment by vanitasvitae** [comment]
I can confirm this. Renaming the group solved my problem though.

**Comment by Asara** [comment]
I actually had the people in the group reset secure connection in our individual conversations, and then rename the group

**Comment by hasdf** [comment]
Does anybody know what could cause this problem?

I have a group-caht with 8 contacts (all android) and we have to update the group title ~ every 2 weeks, because somebody can't write anymore.

Receiving messeges always works. But one can simply not *write* text.

**Comment by 2-4601** [comment]
@hasdf what did the person who has this issue do before this behaviour started to occur? Can you ask your contact to send a debug log immediately after it happens next time?

**Comment by gartenriese2** [comment]
Is there any news about this? It's slightly annoying that every time someone reinstalls Signal all groups he is a member of need to be updated manually.

**Comment by moxie0** [comment]
@gartenriese2 Please do not bump issues: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues

Sadly, it doesn't suddenly make us have more time.

**Comment by 2-4601** [comment]
Fix in 3.24.0 (cf01959e16acc1ff31cd007d68b3ba43810b6c3a)
