### ISSUE TITLE
unencrypted export crahes App

### ISSUE THREAD

**Issue by JayPiEs** [WhisperSystems/Signal-Android#1054]
trying to export the Massagen unencrypted to SD crahes TextSecure every time. 
Encrypted export works finde.

**Comment by riyapenn** [comment]
Is this still an issue? Will re-open if an updated debug log is provided with steps to reproduce.

**Comment by birdbrain5381** [comment]
I have not encountered this issue for over 6 months, and have successfully transferred the backup between 3 xperia z3's in that time. Thanks!
