### ISSUE TITLE
Ask for desired behaviour on first start

### ISSUE THREAD

**Issue by BrokenPhysics** [WhisperSystems/Signal-Android#1065]
Would it be possible to ask the user during the first start of the app (right before/after setting the passphrase), to specify the desired behaviour:
- only use push
- use SMS fallback
- use as default SMS/MMS-App

Probably even add a "what does that mean?" button which opens a pop-up that explains (in simple words) what every mode does.

This would go a long way in making the app more friendly for the less tech-enthusiastic users and those, who don't want to crawl through the settings-menu.

edit: corrected formatting.

**Comment by riyapenn** [comment]
Closed. No longer a feature.
