### ISSUE TITLE
International data groups. Unidentified problem.

### ISSUE THREAD

**Issue by frictionlessmeme** [WhisperSystems/Signal-Android#1152]
Alice is in Ireland. Bob is in Colombia. Carol is in the UK.

They resolve to use Text Secure because SMS is too expensive.

They all appear to register their numbers successfully, and all of them successfully begin to use push messages.

Alice (or Carol) start a new group and add the others.

Alice can see both Bob's and Carol's messages, and can send messages to the group, which appear to be sent.

Bob can see both Alice's and Carol's messages, and can send messages to the group, which appear to be sent.

Carol can see Alice's messages, but cannot see Bob's messages, and whenever she sends messages to the group, they appear to be sent.

They try to message each other individually.

Alice can message both Bob and Carol.

Carol can message both Bob and Alice.

Bob can message Alice, but cannot message Carol. His messages don't arrive, even though they appear to have sent.

None of them really understand what could be going wrong at the protocol level.

**Comment by riyapenn** [comment]
Closed for no useful information and no updates in over a year.
