### ISSUE TITLE
Add a way to restore group information

### ISSUE THREAD

**Issue by tinloaf** [WhisperSystems/Signal-Android#1254]
If a user (like me) has to re-install TS, restore some (old) backup or loses (part of) his data for some other reason, groups are messed up. The groups that he joined do not show up, and as far as I can see, there is currently no way to restore them. If someone tries to re-add me to the group, that does nothing. If someone writes something into the group, I see a message in an "unknown group", but cannot reply since my TS does not know the recipients.

I think there should be some way to send the group data from one TS that still knows this information to the one that lost it. This is what I think could be done (let my buddy be called 'Bob'):
1. I restore a backup, my group is gone.
2. Bob sends something in that group.
3. My TS sees that it's missing a group, and that Bob is most probably part of it. It sends a "please give me the group data" message to Bob.
4. Bob's TS receives the message and checks that I am actually part of that group (so we don't leak group data to potential outsiders). It then sends a message with the whole group information to me.

Also, there should be a way to do this manually from Bob's client.

@moxie0 Since you're thinking about adding message types anyway (talking about delivery receipts), could this be done?

**Comment by dkasak** [comment]
Any progress on this? The solution outlined by @tinloaf in the beginning of this thread and [here](https://github.com/WhisperSystems/TextSecure/issues/2581#issuecomment-77352186) seems like it should work. @moxie0, you mentioned it sounded un-asynchronous; do you still see problems with it after elaboration?

**Comment by peterpanondrugs** [comment]
Here a log if you whish. Since I often try different ROMs...its annoying that iI can't join a group myself..
The so far for your support. Great app!
https://gist.github.com/e7ecc798446f801f7afe

**Comment by t-animal** [comment]
Still no progress on this?!

Here's a workaround, though: 1) The person who reinstalled signal has to close all instances of the group chat (i.e. on all devices, mobile and desktop) that might have come up due to messages in that group still being delivered to him/her. 2) Someone else has to re-add the person, ignoring that he/she is already in the group and accept the change in the "edit group" window via the tick mark in the top right corner. This solved it for me and the user could reply to the group thereafter.

**Comment by haffenloher** [comment]
@t-animal no need for closing, re-adding etc., doing a group update without any change should be enough. Regarding progress: check out #5876

**Comment by t-animal** [comment]
@haffenloher i already thought so, but i could not verify it without re-reinstalling the app, which i did not want to do l ;) Cool, that there's finally a fix for this :)

**Comment by 2-4601** [comment]
Fix in 3.24.0 (cf01959e16acc1ff31cd007d68b3ba43810b6c3a)
