### ISSUE TITLE
Option to disable trailing whitespaces

### ISSUE THREAD

**Issue by gaveen** [WhisperSystems/Signal-Android#1294]
##### Problem: #####
TextSecure apparently uses trailing whitespaces in text messages. This makes it impossible to use with certain telco-services which rely on exact SMS-based short codes/activation codes.

##### Requested solution: #####
Please provide a way to disable trailing spaces (even at the expense of secure data messaging). In addition to that you could perhaps consider disabling it (as a sane default) for numbers with up to a few (e.g., 4) digits.

##### Related to: #####
Issue #304

**Comment by haffenloher** [comment]
If I'm not mistaken, TextSecure / Signal hasn't been using whitespace tagging for many versions now as the encrypted SMS transport has been removed, so this issue can be closed.

**Comment by moxie0** [comment]
truth
