### ISSUE TITLE
New group showed other threads messages

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#1335]
![screenshot_2014-04-10-23-23-38](https://cloud.githubusercontent.com/assets/5326916/2676539/ff558cce-c13a-11e3-9da5-60d298b812f1.png)
*this shows the newly created group - the messages are those of another existing single contact thread*

Have to admit, that I merged some pull requests - but I could not imagine what changes could have caused this.

What I did:
- I created a group with one contact
- named it (with emoji) 
- added a push contact by selecting it
- added a *my* number by typing it in
- finished creating

I remember there was an issue describing this behavior - can't find it anymore.
Still trying to reproduce this...

**Comment by lazlolazlolazlo** [comment]
Can't reproduce on 2.7.0

**Comment by McLoo** [comment]
Very likely some derivation of #2354 or maybe #2262
That scenario was built during my heavy testing/deleting/importing/whatever phase.

Don't know if this should be closed...
But in any case there is some change needed in safe thread id usage IMHO

**Comment by McLoo** [comment]
Never seen this again
