### ISSUE TITLE
[bug] Forwarding media messages only forwards text

### ISSUE THREAD

**Issue by generalmanager** [WhisperSystems/Signal-Android#1362]
Sharing pictures from the gallery or anywhere else works great in 2.0.7., but whenever I want to forward a message with an image, only the text gets transferred into the new message.

Observed behaviour: Forwarding messages with pictures only forwards the text.
Expected behaviour: Forwarding messages with pictures forwards the whole message.

@McLoo identified the problem in ConversationFragment.java (https://github.com/WhisperSystems/TextSecure/issues/316#issuecomment-40311690):

```java
  private void handleForwardMessage(MessageRecord message) {
    Intent composeIntent = new Intent(getActivity(), ShareActivity.class);
    composeIntent.putExtra(ConversationActivity.DRAFT_TEXT_EXTRA, message.getDisplayBody().toString());
    composeIntent.putExtra(ShareActivity.MASTER_SECRET_EXTRA, masterSecret);
    startActivity(composeIntent);
  }
```

**Comment by jeremymasters** [comment]
Looks like all the PR's for this have been closed.  Is there a chance this feature could rise from the crypt? :)  I have a few users that I have given work-arounds but just curious.

**Comment by McLoo** [comment]
@jeremymasters just waiting till the whole attachment refactoring block is done, to see what's possible :)

**Comment by generalmanager** [comment]
@McLoo Thanks for at least giving it a try! Did I understand it correctly from your last comments in #3311 that everything works apart from gifs?

In that case: would you consider releasing the patch for the other media types regardless? This would fix the problem for a huge majority of messages (and users) until GIFs can also be supported.

Or will you have to do it all over again, when the attachement refactoring is done?

**Comment by generalmanager** [comment]
Yay, thanks a lot @mcginty :D :dancers:
