### ISSUE TITLE
Indicating in the conservation overview whether the last message is yours or from your conversation partner

### ISSUE THREAD

**Issue by bvorak** [WhisperSystems/Signal-Android#1363]
Description given.

**Comment by franciscod** [comment]
this has been solved here https://github.com/WhisperSystems/Signal-Android/commit/7c95adc7e61e8157a686caa19ac8b6c8cf593eae right?

**Comment by 2-4601** [comment]
Closed too hastily. I'm not sure if it's planned to add "You" or contact names in the conversation list? Or is the current situation good enough?

**Comment by moxie0** [comment]
I think it's good as is
