### ISSUE TITLE
Creation of group leaks name and included numbers to participants before any message is sent

### ISSUE THREAD

**Issue by kannes** [WhisperSystems/Signal-Android#1725]
I created a group just to test how creating a group works. I added some random contacts that showed as TextSecure users. Then I decided, ok, creating groups works and went on with my day.

Later I received a message from one of the users, inside the group, asking about the purpose of this group.

At no point did TextSecure indicate or warn that the mere creation of a group was a "transferred" action. This lead me to leak the numbers of completely unrelated strangers to each others.

Please add a warning or dialog that a group is immediately communicated to all participants, even with no message(s) sent.

**Comment by pguth** [comment]
@riyapenn Could you add a few words what close means here?

**Comment by riyapenn** [comment]
After creating group, a conversation is created and it states that you 'Updated the group.' (iOS users see 'Group updated.') All users see this new group. 

So this feature now exists.

**Comment by kannes** [comment]
I don't understand how that answers the issue. If all users see the group, surely they see each other?
