### ISSUE TITLE
Custom label value not showing up at top of conversation

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#1733]
Setup:
1. Have a contact  with two Custom labels for their two phone numbers.

Steps to reproduce:
1. open any conversation with a user like above.

Note: at the top of the conversation, it doesn't show that custom label next to the phone #.  This affects me because I have contacts that have two cell #'s to which I can text.  It also might be good to consider showing the custom label in the list of conversations.

**Comment by rhodey** [comment]
non-custom labels such as 'HOME', 'CELL', 'WORK', etc are also not supported, TextSecure shows the contact name + phone number instead of contact name + label. seems more like UX or feature than a bug to me.

**Comment by jeremymasters** [comment]
Makes sense.  I think somewhere there is an issue relating to people having more than one TS number per contact besides the one I created here.

**Comment by jeremymasters** [comment]
I think I was looking at how Red Phone handles the labels in the list of contacts when I wrote this for TextSecure.  If they will be merged this probably proves even more relevant.

**Comment by p4nci** [comment]
@jeremymasters is this still an issue or is fixed by https://github.com/WhisperSystems/Signal-Android/commit/165fae5734e7a6d0ea3252ee2a325d4c771e25b7 ?

**Comment by jeremymasters** [comment]
Fixed.  Thanks for the reminder.
