### ISSUE TITLE
Automatic SMS forwarding

### ISSUE THREAD

**Issue by swperman** [WhisperSystems/Signal-Android#1761]
It would be awesome to be able to automatically forward all incoming SMS from a certain contact to another contact.

**Comment by riyapenn** [comment]
Closed for no further description.

**Comment by martondob** [comment]
This would be practical for cases when you can only set one phone number for receiving notifications from services, but you would like to share notifications with business partner, wife/husband.
Like transfer notifications from banks in my case.

**Comment by alan-signal** [comment]
Please use the community forum for feature requests https://community.signalusers.org/

**Comment by martondob** [comment]
@alan-signal OK, thanks for the info.
