### ISSUE TITLE
Confusing session setup

### ISSUE THREAD

**Issue by thoughtbox** [WhisperSystems/Signal-Android#1871]
Hey,

Just a comment regarding the session setup. I sent a key exchange request after TS detected the sending party was using TS. Nice.

However, even though I have "Complete Key Exchanges" ticked, the received key was not processed (and since I got about 10-12 messages in one burst, the topmost (the remote key material), was out of sight, while all the others were still encrypted, with the "encrypted with an existing session" (or something like that :-) message).

Of course, as soon as I scrolled up and found the key exchange response message ("key" icon) and clicked on it, everything was fine. I do believe this will be confusing to new users, though.

Just two cents, keep up the good work!

/TB

**Comment by agrajaghh** [comment]
encryped sms
