### ISSUE TITLE
Option to set a default output Directory for Backups/Backup into subfolder instead of root

### ISSUE THREAD

**Issue by TWfromSWD** [WhisperSystems/Signal-Android#1901]
Just a little Feature request. My Problem is, that i want to synchronize the Message Backups to my Home Computer. When I was using normal SMS and SMSBackup, all the output files were written into a subdirectory which was easy to synchronize but TextSecure writes the Backup File directly into the root of the sd card which I cant synchronize automatically because the sync software only supports folders and not single files.
My question is: Is it possible to place the Backups per default in a subdirectory or to add an option where the backup directory can be set?

**Comment by 2-4601** [comment]
Closing in favour of #2791.
