### ISSUE TITLE
Import/export of public keys with sharing interface

### ISSUE THREAD

**Issue by effigies** [WhisperSystems/Signal-Android#1911]
This is similar to but not quite the same as #802, which seems to be aimed at importing/exporting key files. And it may be violating rule 3, so apologies in advance if this is deemed too power-usery.

Importing/exporting public keys via the sharing interface would be useful for allowing people to easily construct alternative out-of-band verifications.

For example, for people who have verified PGP keys in the past, but are not now close enough to verify TextSecure keys:

1) Share public key -> Sign/Encrypt with APG -> Share via Email/whatever
2) Receive -> Verify/decrypt with APG -> Share to TextSecure, importing the key

Right now, you can export your fingerprint QR code, sign, send and have them verify and scan it, but it's not quite smooth, and the QR seems like a complicating step.

Another possibility is making a URI protocol that TextSecure is assigned to, like `tsfpr:<PHONENUMBER>:<FINGERPRINT>`. This would resolve the import problem altogether, and could resolve something like #1016 in passing.

**Comment by FeuRenard** [comment]
I assume that the equivalent of 2014's "public keys" are "safety numbers" (2016). The sharing interface is now implemented in several ways

- https://github.com/WhisperSystems/Signal-Android/commit/b55a7ff5c05adc0b2e5c5c0b2b54f116f964cec3: Add copy and compare safety numbers from clipboard actions
- https://github.com/WhisperSystems/Signal-Android/commit/92aeafc26172fbbce036cdf99b82f8313acb204b: Add share button for safety numbers

So if I understand this issue correctly, it will be resolved.
