### ISSUE TITLE
Give option for user to suppress warning on opening attachments

### ISSUE THREAD

**Issue by fuzzyroddis** [WhisperSystems/Signal-Android#1915]
Friends who are using TextSecure have found it frustrating that it alerts them every time they want to view an image.

![alert](https://cloud.githubusercontent.com/assets/2271265/4263833/ff31b85a-3c03-11e4-9457-3b796d9826d4.png)

Even if they have the passphrase option disabled it still prompts them.

My "I'm totally an artist" mockup:
![yibfmub](https://cloud.githubusercontent.com/assets/2271265/4263838/a3b182fc-3c04-11e4-8556-b9d9e2837d90.png)

But I'd recommend the box being **unchecked** by default and an option in settings to reenable the alert.

**Comment by FeuRenard** [comment]
Now that images and videos are displayed in-app this issue can be closed, I think.
