### ISSUE TITLE
SMS from non-numeric sender showing push availability

### ISSUE THREAD

**Issue by Joesen1** [WhisperSystems/Signal-Android#1932]
Hi,

i received a SMS from a anonymous/non-numeric sender (like "sender") and TextSecure is showing me the blue send button for secure messaging in the conversation.
The two options on long press are push and insecure sms.

How can a non-numeric sender id be registered with the push service? Or is it a bug?

**Comment by gordon-morehouse** [comment]
@Joesen1 Is this still a problem?

**Comment by Joesen1** [comment]
@gordon-morehouse Yes, it's still a problem. Nothing changed since last update (2.3.3).
I have two non-numeric sms conversations showing push availability!

**Comment by rhodey** [comment]
@Joesen1 lots of relevant changes in 2.6.4, if you have time for another update it'd be really helpful, thanks! :)

**Comment by Joesen1** [comment]
@rhodey Problem still exists in 2.6.4. Maybe it's because the sender's name contains a single digit between other character and thats why TextSecure is thinking it's a regular number!?

**Comment by riyapenn** [comment]
Is this still an issue?

**Comment by Joesen1** [comment]
Hi! @riyapenn Just updated to Signal 3.3.2, nothing changed regarding this issue...

**Comment by Joesen1** [comment]
Bug seems to be fixed in one of the last versions (at least since 4.10). Thank you
