### ISSUE TITLE
Show image hint instead of (no subject) for media/mms

### ISSUE THREAD

**Issue by mcginty** [WhisperSystems/Signal-Android#1934]

**Comment by rhodey** [comment]
to clarify, the idea is that if the last message in a conversation thread contains an image (sent or received) the conversation item in the conversation list view should contain a preview of the image which when clicked opens a view intent list so.

![issue-1934](http://i.imgur.com/UYA743e.png)

*opens to*

![bike](http://i.imgur.com/2kmFM4o.jpg)

**Comment by McLoo** [comment]
I always thought it should be sth like it's for drafts now. Show
- *(Image)*
- *(Audio)*
- *(Video)*

if it's a media only message. cause right now it's just *(No subject)*

**Comment by rhodey** [comment]
@McLoo my first impression from the name of this issue also, I think a combination of that and this image preview thing would be nice. Maybe video preview could be a preview of the first frame in the video, though I'm not sure if audio preview could be nicely pulled out into conversation list view also. The UX that Messenger has with this image preview setup is really nice, especially with material design.

**Comment by heyimgay** [comment]
This issue can be closed as the feature has been implemented
