### ISSUE TITLE
Add support for other QR-code scanner

### ISSUE THREAD

**Issue by oholika** [WhisperSystems/Signal-Android#2074]
The QR-code scanner which needs to be installed requires a lot of rights (like reading my contacts or bookmarks), this does IMO not match to the security standards of TextSecure.

**Comment by volcano99** [comment]
Can't it be integrated and become part of textsecure? Especially now that the browser extension is coming, I think most users won't expect to need another app to scan the code...

**Comment by franzmueller** [comment]
>Especially now that the browser extension is coming, I think most users won't expect to need another app to scan the code...

I could actually scan the QR to connect the browser extension without installing any additional app. Generating/Scanning QR codes to validate a contact still doesn't work without it though.

**Comment by FeuRenard** [comment]
Barcode Scanner for safety number verification is built in since 3.20.0.
So this can be closed.
