### ISSUE TITLE
Detailed receive receipts in group message details

### ISSUE THREAD

**Issue by generalmanager** [WhisperSystems/Signal-Android#2115]
I believe that group messages are currently only marked with the receive receipt indicator if every participant's phone has sent one.

The usability could be much improved if the detailed message information which is shown after a long-click on the message followed by clicking the "i" icon contained the receive receipt status of all participants.

eg:

**Receive statuses:**

> Alice:   [✓]
> Bob:    [✓]
> Marry: [   ]

What do you think?

**Comment by moxie0** [comment]
285947e
