### ISSUE TITLE
sending sms possible when sms disabled in existing conversation

### ISSUE THREAD

**Issue by jagz6262** [WhisperSystems/Signal-Android#2161]
In the version 2.3.2, When we choose the settings to allow outgoing SMS to check the options:
Text Secure users or Non-Text Secure Users. I choose only the text secure users and sends message to other party without having the text secure application and the other party was able to receive the message.
Device: Nexus 5 Android Version 5.0 lollipop

**Comment by agrajaghh** [comment]
> Ah yeah. If you have an existing conversation open with a non-TS user, you can currently continue to send SMS with them.

Thats still possible, but intended, right? Closing?

**Comment by FeuRenard** [comment]
This issue refers options that are no more present in Signal. It should be closed, I think.
