### ISSUE TITLE
[Feature Request] Swipe images

### ISSUE THREAD

**Issue by JavaJens** [WhisperSystems/Signal-Android#2355]
I noticed that in a conversation with several images (or media files in general) I have to click each one to view and then return to the conversation list to view the next.

I think it would be more comfortable for the user to be able to swipe (left/right) between all media items sent in this conversation, similar to the Gallery app.

**Comment by mcginty** [comment]
it's a great idea, would go wonderfully with a media view for conversations

**Comment by bungabunga** [comment]
Threema has a dedicated menu entry in every conversation called Media Gallery. While JavaJens's idea's plus is you don't have to leave the conversation view to see pictures, Threema's is that it keeps received pictures handy. Imagine you raceived a photo or video frome someone 100 entries in the past; you need quite a loot of swiping up to find it.
Maybe a combination of both ideas?

**Comment by Mihahn** [comment]
@bungabunga @JavaJens what about a solution similar to WhatsApp then? In WhatsApp there is a "gallery" in every conversation with all pictures sorted by date. If you select an image you can still swipe left/right to the previous/next image.

I'd like to see something like that in the future too! It would be a handy function :+1:

**Comment by JavaJens** [comment]
I don't know how WhatsApp does it, but this sounds like what  @mcginty said with the media view I assume

**Comment by Mihahn** [comment]
This is what it looks like: 

![screenshot_2015-01-17-15-17-46](https://cloud.githubusercontent.com/assets/3447340/5789083/423538b0-9e5c-11e4-8672-35511551c337.png)
![screenshot_2015-01-17-15-17-53](https://cloud.githubusercontent.com/assets/3447340/5789086/4682c27a-9e5c-11e4-92de-28bcb7912394.png)

**Comment by JavaJens** [comment]
@mcginty was very quick and implemented the media view in #2367 
It shows all images within a conversation in one view. Swipe is not implemented yet, but I am sure this will be fairly easy now...

**Comment by bbinoy** [comment]
+1 would be great if implemented!

**Comment by moxie0** [comment]
@bbinoy Please don't post in issues unless you have new information to add, thanks

**Comment by FeuRenard** [comment]
I am working on this.

**Comment by FeuRenard** [comment]
The feature is implemented, but I have to test it extensively before opening a PR. You can help by trying out [this branch](https://github.com/FeuRenard/Signal-Android/tree/image-slide).

Currently there seems to be a memory leak. This causes images after 20+ swipes to one side not to load because of `java.lang.OutOfMemory`.

**Comment by MartinX3** [comment]
@FeuRenard 
What is the actual status of this issue?
And if there is any pull request, i don't find it.

**Comment by FeuRenard** [comment]
PR: #5801

Status: #5941 should be implemented before or at the same time. The PR itself needs some adaptation. I may have time for that in roughly a month, but I can't promise anything.

**Comment by MartinX3** [comment]
Thank you for the fast response :)
And thank you very much for your hard work!

**Comment by FeuRenard** [comment]
Current status of my work: https://github.com/FeuRenard/Signal-Android/commits/media-swipe_draft
I'll have to crack this feature up to some easy to review commits or PRs. Other than that there isn't that much work remaining.
