### ISSUE TITLE
Send button should send immediately on changing transport

### ISSUE THREAD

**Issue by merkste** [WhisperSystems/Signal-Android#2356]
I've just noticed that the send button remembers the selected transport (sms, sec. sms, push) but does not send immediately anymore. I find this pretty cumbersome, since one expects a send button to send a message. Also I am used to the previous behavior, namely sending on select of transport.

**Comment by 2-4601** [comment]
@merkste Is this still an issue?

**Comment by merkste** [comment]
It is. I think a comment from the developers would help a lot.

Am 23. Dezember 2015 23:15:57 MEZ, schrieb 2-4601 <notifications@github.com>:

**Comment by moxie0** [comment]
thanks but we're going to keep it as-is
