### ISSUE TITLE
[Feature Request] Improve group message delivery confirmation

### ISSUE THREAD

**Issue by janvlug** [WhisperSystems/Signal-Android#2373]
Only confirm the delivery of a message to a group when it has been delivered to _all_ group members.
Currently, a message sent to a group is marked as delivered when at least _one_ group member confirmed the reception (see #2260). This is not intuitive in my opinion, because it can now happen that a group message is labeled as delivered while some group members did not receive it.
Reliable and intuitive group message delivery notifications are important, because it seems that GCM is not too reliable (see #2238, #2098).

**Comment by janvlug** [comment]
Related to #2115.

**Comment by jeremymasters** [comment]
Maybe have a number in the bottom that shows x of y members delivered to and then when you click on the info for that message it would show to whom it's been delivered.

**Comment by derNarr** [comment]
Additionally, it would be good if you can check in the message details who has received the message. A check-mark next to the name would be perfect.

**Comment by i7u** [comment]
Yesterday I sent a message to a group of 3 other people. None of them received it for ~4 hours (probably due to network issues). For those 4 hours I was staring at the double tick mark, wondering why they were ignoring me - as it was an urgent work-related request.

**Comment by moxie0** [comment]
285947e

**Comment by matthias-g** [comment]
Thanks for implementing the per-member delivery status info.
The original post talked about showing the double tick mark only when the message has been delivered to _all_ members of the group instead of already when it has been delivered to the _first_ member. I agree that this behavior is more intuitive. Did you consider changing it?

**Comment by UserX404** [comment]
I would propose an other option. If anyone read the message colors one check mark blue and if everyone has read them both could be colored blue.
That could be a gain of information.
