### ISSUE TITLE
no place to enter sms verify code if app fails to notice it, must wait for voice verification

### ISSUE THREAD

**Issue by kaihen** [WhisperSystems/Signal-Android#2410]
TextSecure is unable to read / check the received activation SMS. It would be cool if there would be a box to copy / type the code from the SMS into it (manual activation). Because the call activation / verification is also broken on my smartphone (Xiaocai X9 with LeWaOS / Android 4.2.1).

By the way TextSecure is able to import all my old SMS. Maybe it's just a bug in the activation part.

**Comment by ximex** [comment]
"By the way TextSecure is able to import all my old SMS."
Shouldn't this be so? Or do you mean "isn't able to"?

**Comment by git12a** [comment]
@kaihen When you posted, voice call activiation service was also down. I had the same problem, but it was fixed some hours ago. Try voice call activation now?

**Comment by kaihen** [comment]
@ximex Just wanted to say with that that TextSecure is able to access on the SMS but doesn't check the received activation SMS. I think it's because the LeWaOS notify and popup the received SMS.

@git12a Ah! The error message wasn't clear. I though it would be a problem with my smartphone, provider, internet conneciton and after the 3. call request I was getting the message to wait 30 mins for a new try. Long time ago I was able to use the call activation (and TextSecure) so the broken service is arise from the downtime of the service.

Yesterday I just used my new smartphone and had no problem with the activation SMS.

**Comment by rhodey** [comment]
thanks for proving us with the update @kaihen :)

**Comment by invapid** [comment]
can you re-open this. this IS still a problem.

On textsecure start: it tries to text you and forces you to wait (even if you get the sms, and textsecure isn't aware the phone received the SMS).

Fix:
* you should be able to type the code in, instead of having to wait.
* would be nice to have the option to call you as well (instead of having to wait until the sms attempt fails)

Interestingly whatsapp's implementation for activiating over SMS works properly.

**Comment by alexandrujuncu** [comment]
+1 on this issue. I think it's reasonable to let the users have the option of manually inputting the code.

**Comment by agrajaghh** [comment]
@alexandrujuncu Please only post comments in issues if you have new information to add. This isn't helpful and is just time consuming for the devs...

**Comment by moxie0** [comment]
thanks but we're not going to do this
