### ISSUE TITLE
notifications for group messages

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [WhisperSystems/Signal-Android#2558]
when multiple people post new messages in a group chat, the notification on android assigns them all to the first person that posted. Only when I open the app, I learn that they are from multiple people.

Maybe it would be more straightforward to show the group name in notifications instead?

**Comment by olbrew** [comment]
Possibly related to this: when I get a notification from a group chat and press it, it redirects me to the personal message thread I have with that person, not the group thread where he/she posted from.

**Comment by rhodey** [comment]
related #1033

**Comment by KommX** [comment]
@rhodey
Are you still working on this issue?
