### ISSUE TITLE
3 different padlock icons

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#2622]
Minor, but disturbing 
There are 2 different pad locks In the notification (keyhole, color) :
![screenshot_2015-03-07-23-01-29 01](https://cloud.githubusercontent.com/assets/5326916/6543511/bbea8aaa-c51e-11e4-9e3e-e99b9fdb7a94.png)
And a third one in the action bar: 
![screenshot_2015-03-07-23-04-07 01](https://cloud.githubusercontent.com/assets/5326916/6543515/dc27bffe-c51e-11e4-8ab1-59eb7ea3324a.png)

**Comment by agrajaghh** [comment]
Just for reference: the little one used in the encrypted message bubbles is the one from "Lock with passphrase"

**Comment by agrajaghh** [comment]
@mcginty should I make a PR to harmonize all of them and just use the one with the little hole in it (from the material icon repo)?

And this one for the unlocked notification? (but white and filled)

![ic_lock_open_black_24dp](https://cloud.githubusercontent.com/assets/5296073/6543601/244b6cb0-c522-11e4-8d60-2af183f66638.png)

**Comment by McLoo** [comment]
Seems were going the way where the keyhole is on the bottom, and therefore invisible.
from 3.0 Branch:
![unbenannt](https://cloud.githubusercontent.com/assets/5326916/10184987/6a009794-6743-11e5-9c78-61471be67e08.png)

If I'm not completely wrong this new icon is placed next to the holey-padlock in the actionbar

**Comment by McLoo** [comment]
fixed with #5325
