### ISSUE TITLE
Video needs to be saved on disc to be playbacked

### ISSUE THREAD

**Issue by oholika** [WhisperSystems/Signal-Android#2706]
I received a MP4 file from an iOS user (don't know if that has an impact); by trying to playback out of the conversation with vlc i received an error message: can not connect to file, please try to update media db. After saving the file playback was possible on my Nexus 4 running LRX22C version 2.6.4.

**Comment by rhodey** [comment]
kinda a feature (related to in app media playback) but the error message is misleading enough to be a UX bug.

**Comment by mcginty** [comment]
Yeah, it looks like VLC is expecting the video to be indexed in Android's media database which sounds undesirable.

**Comment by agrajaghh** [comment]
its not just VLC, I can't play videos with QuickPic and MX Player until I saved them to storage...

**Comment by McLoo** [comment]
this is definitely new. Was always able to play videos. 
Crash log part from quick pick. Yes screenshot, no copy option here... 
![screenshot_2015-04-05-08-40-58](https://cloud.githubusercontent.com/assets/5326916/6996042/cd7b7542-db6f-11e4-8633-aa1817b2c9b3.png)

**Comment by agrajaghh** [comment]
log from Quickpic:
https://gist.github.com/agrajaghh/cc43fda2038bb59cecc1

**Comment by mcginty** [comment]
Found the issue, PR out soon.

**Comment by bungabunga** [comment]
I still cant play audio/video normaly - have to save them to disk first to be playbacked on the latest version of TextSecure (2.11.1). Please reopen.

log (TextSecure):
https://gist.github.com/bungabunga/78a11a036237fcc32506
log (VLC):
https://gist.github.com/bungabunga/52a8d22432492de2cfbb

**Comment by jeremymasters** [comment]
This is currently marked as 2.10.2.  Might want to change the milestone to make sure it doesn't get lost.

**Comment by bungabunga** [comment]
@moxie0 Video/audio playback now works for me on 2.16.4, Android 4.4. You might want to close the issue.

PS - The only difference is, it used to work with Music+ app (link at the end) and now it doesen't. But it works with VLC.

https://play.google.com/store/apps/details?id=net.rymate.music

**Comment by 2-4601** [comment]
> You might want to close this issue.
