### ISSUE TITLE
Messages sent to group delivered to private chat after the sender uses a new PreKey

### ISSUE THREAD

**Issue by TheStash** [WhisperSystems/Signal-Android#2739]
Sender's Device: LG G3 running Lolipop, TextSecure 2.6.4 / 2.7.1 (not sure)
Receiver's Device: Nexus 5 running Lolipop, TextSecure 2.7.1

Issue details:

1. An existing TextSecure user switched to a new phone and installed TextSecure on it
2. The user sent a message to an existing group member which accepted his new identity then added him to the group.
3. Other group members did not yet approve his new identity.
4. Whenever the user with a new identity sends a message to the group, users who didn't yet accept his new identity receive a "private chat notification" asking them to confirm his unknown identity or cancel.
5. after confirming each "confirm identity" notification, the message which was supposed to be delivered to the group is delivered to the private chat instead of group chat.
6. no idea about future messages, but i believe they would be delivered normally to the group after confirming the identity.

**Comment by shaaati** [comment]
I experienced this today as well. I can confirm that in step 6 further messages really go to the group chat after confirmation.

**Comment by real-or-random** [comment]
I can confirm this as well.

Additionally, the group was shown as "Unnamed Group" for some (not all)  group members when this happened. Renaming the group fixed that.

**Comment by riyapenn** [comment]
Related: #3537 and #3581
