### ISSUE TITLE
Highlight thread with new messages on Light theme.

### ISSUE THREAD

**Issue by Geblaat** [WhisperSystems/Signal-Android#2770]
When one is using the dark theme, a thread with new messages is highlighted in addition to the bolded font.
However when the light theme is being used, there is no highlight to indicate there are new messages, only bolded font. 
I read/heard some users complaining the bolded font is not distinct enough, especially in situations with bad readability(sunny weather etc.)
Making both themes have the same properties would be desirable anyway and helps visibility as well.

**Comment by 2-4601** [comment]
Currently (3.8.1) a thread with new messages is highlighted with white background in the light theme.
