### ISSUE TITLE
better highlight conversations with failed messages

### ISSUE THREAD

**Issue by ghost** [WhisperSystems/Signal-Android#2900]
When sending a message fails, the current behaviour is that you get a notification about the failure. I think it would be better to also display something like a red triangle in the conversations list, mostly because:
-you may swipe the notification without taking care of resending the message right away
-several messages may fail to send if you temporarily lose your connection, and clicking every notification seems cumbersome to me
-it would just make sense for the sake of clarity

And maybe move the failed messages to the top of the conversations list (?)
Thank you

**Comment by volcano99** [comment]
It would also be cool if the notification had a "resend messages" button, similar to the "lock with passphrase" button currently displayed when textsecure is unlocked

**Comment by mcginty** [comment]
@volcano99 good idea!
