### ISSUE TITLE
crash bug - OOM bitmap related

### ISSUE THREAD

**Issue by turion** [WhisperSystems/Signal-Android#2944]
TextSecure currently crashes on my phone every time I start it. I don't know how to fix it, it stays the same after restarting the phone. I haven't made any backups of the data so far, and I can't do that now since I can't start the app. Can I reinstall TextSecure, or will I lose all the data? Will it delete the private key and/or the database?

**Comment by agrajaghh** [comment]
unfortunately all the data will be lost if you uninstall and reinstal. Could you get a debug log of the crash (with adb) please? would be helpful to fix this bug...

**Comment by turion** [comment]
No, I don't have the phone in my hands (I'm just talking to my girlfriend who is experiencing the bug), so adb can't be used. Will alogcat be useful?

**Comment by moxie0** [comment]
@turion Try putting your device into airplane mode, then opening TS.  If that works without crashing, you can capture a debug log from the TS settings ->advanced menu.

**Comment by agrajaghh** [comment]
@turion yes, alogcat would be useful if airplane mode doesn't work

**Comment by turion** [comment]
@moxie0, good idea, but as soon as I want to submit it, I need network again. (Would be good to have an option "save debug log to file") I'm trying to get her to copy & paste, but the phone seems to be slow...
@agrajaghh, I'll try that next.

**Comment by moxie0** [comment]
alogcat doesn't work on modern devices

**Comment by agrajaghh** [comment]
oh sry, didn't know that...

**Comment by turion** [comment]
For some reason the copy & paste on her device doesn't work... she presses the copy button, but the log is not copied to the clipboard.

**Comment by moxie0** [comment]
It's going to be a problem with either a recent incoming or outgoing message, most likely an MMS message.  Once the phone is in airplane mode, if she deletes the offending message she can safely switch the device out of airplane mode.

**Comment by turion** [comment]
Yep, she can launch TextSecure, but as soon as she opens the thread with me, it crashes directly, it doesn't even load the messages before crashes (only shows empty speech bubbles).

**Comment by turion** [comment]
Can I delete the sent images on her phone somehow? By manually editing the SQLite file? Or by deleting them in my thread?

**Comment by moxie0** [comment]
Well that's pretty weird. Unfortunately we can't help more until we get a debug log.  Sounds like you'll have to do that with adb if the built in debug log capture isn't working for some reason.

**Comment by agrajaghh** [comment]
really ugly alternative if copy and paste isn't working: screenshots :grin:

**Comment by turion** [comment]
Hm yes, I'm going to ask her tomorrow for screenshots (she went to bed (Europe)).

I got this log from her through alogcat, but it doesn't seem to helpful: http://dpaste.com/3XH62ZQ

The builtin debug log capture is working great, it's just that it needs the internet to submit. So if you want to implement a "save to file" feature and release it, I can get her to do that ;)

**Comment by turion** [comment]
So I looked at the thread I sent her, and I found an image that might have been the cause of trouble. But is there a manual way for me to delete it from her database? (I don't mind a bit of SQL hackery)

**Comment by turion** [comment]
Also, when I try to resend the offending image, I get "Failed to send" again. I can send you my debug log for that: https://gist.github.com/f6f608d0a5a2b9d1f9b7 (So that's the phone that sent the image probably causing her phone to crash)

**Comment by moxie0** [comment]
Looks like an out of memory error on the send side for you.  Could be that's what's going on for the receive side as well.

You can delete the message manually out of the sql database, but you'd need an adb shell on the device.

**Comment by turion** [comment]
That's surprising, why would there be such an error? You mean around line 1213 in my log? It's not that my device is out of memory, right? There is some >100MB left, they couldn't be exhausted by processing one image..?

**Comment by McLoo** [comment]
@moxie0 filling up the thread with messages to move the image out of view, should prevent loading the image? 

@turion it's a single conversation, not a two man group, right? 
(sorry, couldn't resist: sent something big, that Edward Snowden mentioned recently? 😁)

**Comment by turion** [comment]
Haha, no, just an image. The NSA hasn't cracked TextSecure and makes it crash whenever we send some leaks around. I think.

 Right, filling up might work, at least I could circumvent similar bugs that were abundant in earlier versions (and unfortunately still seem to be)

**Comment by turion** [comment]
Is there a size restriction on images to be sent via Push? Maybe it complains about every image bigger than 4MB or so? (It would be really good if there were more verbose error messages when messages fail to send)

**Comment by rhodey** [comment]
hey @turion, just checking in. have you experienced anything like this again since first reporting?

I suspect that this issue may now be resolved because we started using "Glide" for all our bitmap stuff and the bitmap stuff (the image being sent) seems to have been what caused this crash in the first place.

**Comment by turion** [comment]
@rhodey, if it's resolved in 2.17, I still have to wait for the update.

**Comment by mcginty** [comment]
closing since this is old and Glide helped resolve most of these
