### ISSUE TITLE
Long-pressing emoji backspace deletes only one character

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/Signal-Android#2945]
**Another lovely emoji keyboard related issue:**
If you want to remove ten characters with the emoji drawer's backspace you have to tap it ten times. Long press does not work.
Compare to the regular keyboards' backspace which you can tap and hold to remove everything at once.

Tested with: TS 2.11.0, Android 5.0.1, Android 4.0.4

**Comment by wp9015362** [comment]
Yes, same here.

I actually was about to submit that issue myself.

In Telegram for Android the backspace button of the built-in Emoji drawer currently also does not support continuous deletion by long pressing, so I'm kinda used to it.

But if the TextSecure Emoji drawer could be made to support it, then that would be nice.

Regards

**Comment by raptortalons** [comment]
Damn - I still see this issue in Android 5.1.1

**Comment by mcginty** [comment]
works fine for me. more details? are you sure you're using *our* emoji keyboard and not the one in your software keyboard?

**Comment by 2-4601** [comment]
Works fine here too.
I would guess @raptortalons is using the system emoji keyboard. The backspace there can delete only one character at a time.

**Comment by raptortalons** [comment]
YES - didn't mean to confuse. It's the SYSTEM keyboard. I didn't realize this was a special keyboard.

**Comment by mcginty** [comment]
All good. It's kind of confusing, be we don't have any better options for integrating.
