### ISSUE TITLE
CrashBrowser: ConversationActivity NPE - onNewIntent before onCreate 0.o

### ISSUE THREAD

**Issue by moxie0** [WhisperSystems/Signal-Android#2971]
`````
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.thoughtcrime.securesms.mms.AttachmentManager.isAttachmentPresent()' on a null object reference
at org.thoughtcrime.securesms.ConversationActivity.onNewIntent(Unknown Source)
at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1211)
at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1223)
at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2456)
at android.app.ActivityThread.performNewIntents(ActivityThread.java:2468)
at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2477)
at android.app.ActivityThread.access$1600(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
`````

**Comment by mcginty** [comment]
did not know onNewIntent could be called before onCreate.

**Comment by mcginty** [comment]
In fact I still can't say I understand this one. `onNewIntent` should only be called after an Activity has been created, paused, then is relaunched with a new intent. AttachmentManager is set in onCreate and never unset.

**Comment by mcginty** [comment]
If it works like this, then pretty much all the logic in `onNewIntent` is incorrect, but Android's documentation contradicts what's actually happening here.

**Comment by rhodey** [comment]
the only occurrence I'm aware of in which we mess around with Android's lifecycle ideas is [here, in DynamicLanguage](https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/util/DynamicLanguage.java#L25)

it's a stretch, but only guess I have at this time.

**Comment by moxie0** [comment]
@mcginty Looks like there are scenarios where you never call onCreate() from PassphraseRequiredActionbarActivity, so there's a race condition where onNewIntent can be called before onCreate ever is.

**Comment by jeremymasters** [comment]
Is this going into 2.11.2 instead?

**Comment by moxie0** [comment]
@jeremymasters It's not entirely clear how to deal with it at the moment.

**Comment by McLoo** [comment]
Another log in that
https://gist.github.com/97d46a13aab739abaff7

**Comment by mcginty** [comment]
I have a new guess. I'm guessing your passphrase expired, you clicked the notification, and Android still calls onNewIntent even if you call finish() from within the onCreate().

**Comment by McLoo** [comment]
Could be, as I do have a passphrase set and a timeout of some 10 minutes. So it's very likely that it timed out in all of the cases.

**Comment by McLoo** [comment]
I guess there is no more info, but here is another log. 
Openend SMS from notification. Signal should have been locked for quite some time... 
https://gist.github.com/43277f3e7e0e3aadba78

**Comment by McLoo** [comment]
Happens always *only with the same SMS only* contact. 
This time:
- Turned phone back on 
- received new sms 
- tapped that Notification 
- bang again 

https://gist.github.com/cfe509c68ce56ea0fd4e

**Comment by McLoo** [comment]
Now foot another SMS only contact 
Signal was locked while I received the SMS and notification 

Some few minutes passed before I realized the notificaron and unlocked. 

Guess there is nothing new, but here we go :+1: 
https://gist.github.com/ecc0b3c898b88d75fd7d

**Comment by moxie0** [comment]
Looks like @mcginty was correct, android seems to call onNewIntent even if you call finish() from within onCreate()...
