### ISSUE TITLE
[Security Risk] Login Screen and last character of password visible in app switcher

### ISSUE THREAD

**Issue by bl4ckeve** [WhisperSystems/Signal-Android#3017]
The last state of the login screen is visible in the app switcher, making it possible to see the length and the last character of the password. Screen protection is enabled.
PW was typed in followed by quickly pressing enter on the keyboard.
![app-switcher-textsecure-login](https://cloud.githubusercontent.com/assets/1664268/7219062/d4fb76c6-e68e-11e4-875a-a9da683a317c.png)
Is this a problem that you can fix or is it not possible because of "Sense"?
HTC One X running Android 4.2.2 with HTC Sense 5.0

**Comment by 2-4601** [comment]
I can reproduce this with the following steps:
0. Screen security on, passphrase enabled
1. Get TS locked and open the _Enter passphrase_ screen
2. Tap your device's _Overview/Recent apps_ button
3. Go back to the _Enter passphrase_ screen.
4. Enter your passphrase to open TS
5. From now on the Android's Overview/Recent apps view shows a screenshot from the last time you pressed _Overview_ in the _Enter passphrase_ screen (i.e. step 2)
![screenshot_2015-04-19-16-48-07](https://cloud.githubusercontent.com/assets/174176/7219680/21771878-e6b4-11e4-95ad-a7f6b9dfa167.png)


Stock Android 5.0.1
Android 4.0.4
TS 2.12.0

**Comment by agrajaghh** [comment]
how about moving `initializeScreenshotSecurity()` from `PassphraseRequiredActionBarActivity` to `BaseActionBarActivity`?

**Comment by mcginty** [comment]
the PassphrasePromptActivity now respects screen security preferences
