### ISSUE TITLE
Thumbnail orientation is different from gallery view

### ISSUE THREAD

**Issue by yzrmn** [WhisperSystems/Signal-Android#3076]
I am building master and thumbnail orientation is different if I click on it (might be introduced with Glide).

Steps to reproduce:
1. Take a picture with Camera
2. Go to Gallery and rotate the image (left or right) in the menu
3. Send image with TextSecure (thumbnail orientation is wrong, like before rotation)
4. Click on the image (image orientation is right in gallery/fullscreen view, like you rotated it)

It looks like it has something to do with Exif rotation?!
Steps cannot be reproduced with 2.12.0 tag, only with master!

**Comment by agrajaghh** [comment]
Could you please upload a picture which TS is displaying wrong?

**Comment by mcginty** [comment]
i'll assign myself and check it out - could be that Glide needs some help handling EXIF rotation info

**Comment by riyapenn** [comment]
Is this still an issue?

**Comment by yzrmn** [comment]
I will check against 3.1.0

**Comment by yzrmn** [comment]
Ok, tested in 3.1.1: Should be fixed but there is yet one case where the attachment preview is wrong (it is fine once sent)

1. Take a picture with Camera
2. Go to Gallery and rotate the image (left) in the menu
3. Send image with Signal (everything is fine)
4. Go to Gallery and rotate the same image (2 times right) in the menu
5. The attachment preview orientation is like the first time rotated (which is wrong, but once sent it is displayed just the way it was meant to be)

So I guess this is just a minor bug...

**Comment by jj0b** [comment]
This is a problem again in 4.17.5. Any photos, no matter how they are attached, whether I send them or receive them from a contact, show correctly in the thumbnail view, but when tapped on to view the full photo they get rotated 90 degrees to the right. This is happening for everyone I know using Signal on Android and just started in the past week or so.

**Comment by greysonp** [comment]
@jj0b Can you let us know what device and Android version you're running? Also, if you could attach an example of a photo that doesn't render properly, that'd also be super useful. Thanks!

**Comment by greyson-signal** [comment]
@jj0b So I found one issue with EXIF data, but I think it may be separate from what your describing. First, to address your bug: I tried sending and receiving this image from my Pixel 2 (Android 8.1), Moto X (Android 7), and Moto E (Android 5), and none of them had problems displaying this image correctly in either the thumbnail or the preview. When you say the issue stopped happening -- did you upgrade your app version maybe?

For the issue I found: it seems that when sharing an image via the share action from an external app (like clicking the share button in a photo gallery app, then choosing to share it to Signal), the EXIF data is not read able to be read properly by Android's ExifInterface, and therefore it'll display in the correct orientation, but with the wrong dimensions. Leaving the conversation and then coming back will fix this. That's puzzling and I'll have to open a separate issue for it, but that doesn't appear to be what you're describing.

If this continues to happen (images displaying with the wrong orientation), please update this ticket.

P.S. Yeah, Github struggles to render EXIF-rotated images properly as well :)

**Comment by jj0b** [comment]
Thanks @greysonp . I didn't upgrade the app, still on 4.17.5, but three photos I shared on Tuesday did not get rotated. Those were the first images to not get rotated for me in a few weeks but everything since is back to rotating if I tap on it (thumbnail is still correct orientation). I'll attach one of those in case it reveals anything interesting.

Also FYI, I've been sharing the images by tapping the attachment button in Signal and then tapping on the photo.

Lol on Github having render issues too. ;)

![img_20180411_155544](https://user-images.githubusercontent.com/146588/38744553-eefb7968-3ef6-11e8-8b8f-9bffe27ed82e.jpg)
