### ISSUE TITLE
You can still send messages when you are left alone in a group

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/Signal-Android#3090]
If **you leave a group** the thread is not deleted but you lose the ability to type in the input box and send messages. _[1]_ I assume this is the expected behavior as you might still want to view past messages after leaving.

However if **everyone else leaves the group** you can still do everything: type text, add attachments and send messages. This makes no sense since there are no recipients anymore. The thread should be "locked" as in the case above where you are the one who leaves. Adding more people (updating group) should "unlock" the conversation again.
![kalevi helvetti optimized](https://cloud.githubusercontent.com/assets/174176/7405414/d241db2c-eefa-11e4-88d2-24fd763a2a1a.gif)

There are many issues about groups but could not find anything about this case.

TS 2.12.0, stock Android 5.1

Edit: Here's [a debug log](https://gist.github.com/anonymous/66c9f855d51f58fbf9b9) after the following steps:
- Open TS first time after boot
- Go to a group
- All the other people leave the group (in this debug log all the other people = one person)
- I send a message to the empty group

_([1] You can still type using the TS emoji drawer. Also you can add attachments. But it might be best to add this as a separate issue.)_

**Comment by moxie0** [comment]
We let people send messages to themselves, is this that different? I'm worried that if we made this change, people would suddenly start complaining that they don't understand why they can't send stuff to their group.

**Comment by 2-4601** [comment]
Sure, if self sending is allowed then no change needed.
However some issues remain:
- self sent messages never get (or display?) second delivery receipt (check mark)
- in message details all sent messages list only the current members of the group (#2642)
- should the user be allowed to create empty groups? (currently not allowed)
