### ISSUE TITLE
OOM - Crash while sending picture

### ISSUE THREAD

**Issue by ghost** [WhisperSystems/Signal-Android#3094]
I was sending a picture when textsecure crashed. The sending also failed by the way.
Log https://gist.github.com/anonymous/74de533cc8d30b66e7d4

**Comment by moxie0** [comment]
This looks like a duplicate of #3092

**Comment by peterpanondrugs** [comment]
still the same ... 
https://gist.githubusercontent.com/anonymous/6723cd79ded93c219999/raw/cat.log

**Comment by mcginty** [comment]
closing since this is old and Glide helped resolve most of these
