### ISSUE TITLE
initials not working for self-send media only message

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#3138]
![screenshot_2015-05-08-20-03-36 01](https://cloud.githubusercontent.com/assets/5326916/7542556/00896ce2-f5be-11e4-9aa2-723a346d9570.png)

**Comment by McLoo** [comment]
Hm, very selective bug 
All the same single convo 

![screenshot_2015-05-08-20-19-46 01](https://cloud.githubusercontent.com/assets/5326916/7542803/26b4649c-f5c0-11e4-8974-1362b913dd29.png)

**Comment by McLoo** [comment]
sorry, forgot:
Sony Z1 compact on 4.4.4 stock

**Comment by McLoo** [comment]
hm hm hm,  just in the convo with myself as it seems...

**Comment by moxie0** [comment]
@McLoo What do you mean by conversation with "yourself?"

**Comment by McLoo** [comment]
Sorry. Self texting my TS registered number. Same number in and out)

**Comment by McLoo** [comment]
checked another device, also just the self sends. 
*Debugging isn't really working. No variable contents. proguard?*

**Comment by rhodey** [comment]
huh, cool I can reproduce this when self-sending media only TextSecure messages. I am unable to reproduce this when sending to other people though, @McLoo is this still the case for you too? I'm gonna update the issue title if you don't mind.

**Comment by rhodey** [comment]
note: I have my own number in my contacts so when self-sending there is the potential to use the initials instead of the `#`.

**Comment by McLoo** [comment]
@rhodey yipp, persists in 2.16.2 also on my CM 12.1 HTC One S
I'm in my contact list too, else it would lack the M :wink:

**Comment by McLoo** [comment]
Don't have this anymore (3.4)
