### ISSUE TITLE
[Feature request] Indicate a new day [ux]

### ISSUE THREAD

**Issue by Mihahn** [WhisperSystems/Signal-Android#3147]
I'd like to request a new "feature", which would be some kind of indicator when a new day begins (like it's implemented in other messengers like WhatsApp).
I think this would make searching messages that were sent on a certain day easier and it just structures the conversations...

Below you can see how WhatsApp handles it and I think a similar solution would be great!

![screenshot_2015-05-10-12-09-39](https://cloud.githubusercontent.com/assets/3447340/7553885/c742aeec-f70e-11e4-89fc-29a0c7692549.png)

**Comment by 2-4601** [comment]
4c815db076bdad365c785857e690982bfdb63aa3
