### ISSUE TITLE
Multiple/repeating notification sounds/vibrations/alerts are annoying

### ISSUE THREAD

**Issue by robertfw** [WhisperSystems/Signal-Android#3165]
I've been using the group functionality recently, and I've found that if, when I sync (I use battery stamina mode, apps will not sync while phone is locked), I get a stream of notifications. My vibration motor gets a real workout. If there are 30 notifications, I get 30 vibrate/sound events in very rapid succession. 

Running android 4.4.2. Please let me know what other information would be useful :)

**Comment by mcginty** [comment]
Yep, definitely a good idea.

**Comment by 5boro** [comment]
Great idea, a good number of my friends are complaining about this and #801
