### ISSUE TITLE
Low resoluted "missing image" icon

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#3238]
[HTC One S](http://en.wikipedia.org/wiki/HTC_One_S)  CM 12.1
2.16.0
Testing forwarding changes. And what I get if forwarding does not work is soooo blury  👓

![_20150522_202231](https://cloud.githubusercontent.com/assets/5326916/7777166/ee172db6-00c0-11e5-94f5-e5ee1bff4518.JPG)

**Comment by Limeth** [comment]
How can I reproduce it?

**Comment by McLoo** [comment]
never managed again to reproduce.

**Comment by McLoo** [comment]
never ever seen again
