### ISSUE TITLE
Duplicate message in group

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#3419]
https://gist.github.com/anonymous/84ce697b6cb0257ced5e

Like the subject says, received duplicate  message. Had exact same send/receive time.  Have not had this happen before that I know of.

**Comment by 5boro** [comment]
Could be #2639

**Comment by riyapenn** [comment]
More likely related to an iOS issue wrt key changes https://github.com/WhisperSystems/Signal-iOS/issues/951

**Comment by jeremymasters** [comment]
Haven't seen for quite awhile

**Comment by obifur** [comment]
I still have this problem. One in our group uses ios but he isn't the problem. All get frequently double or triple messages from one guy on Android. He said he had weak signal..

Here is my log:
https://gist.github.com/97edce6e1a5cb8ce52bf

**Comment by jeremymasters** [comment]
It's possible that he got a message failed warning and hit resend a few times.  I've done that.

**Comment by obifur** [comment]
true - I asked him and he did it for each person. what else should he do? nothing? how can he know?

**Comment by jeremymasters** [comment]
tell him next time just hit it once :)  but this is something the devs may want to tidy up a bit.

**Comment by 2-4601** [comment]
Seems like @obifur is experiencing #2639 which is different from @jeremymasters's original issue?

**Comment by jeremymasters** [comment]
@2-4601 is right.  I humbly re-close this issue and refer @obifur to the other one.

**Comment by ab0032** [comment]
I got a message first seven times, then some other messages from others, then again five times. Others in the group got the message multiple times too, but not 12 tumes.

**Comment by icco** [comment]
I was sending an image on Android 7.1 on a pretty shitty signal and my message got delivered around six times according to other members of my group.

**Comment by codeofcarson** [comment]
I am also having this issue on a google pixel 2 with android 8.1.0. My signal is fine and the re-sends happen often usually a day or two later. I'll try to get a debug log next time it happens.
