### ISSUE TITLE
bumping gradle build tools version broke all the tests

### ISSUE THREAD

**Issue by rhodey** [WhisperSystems/Signal-Android#3474]
bumping from `com.android.tools.build:gradle:1.0.1` to `com.android.tools.build:gradle:1.2.3` in this commit b4634f30e675476890e3a273ba04ed1ffb0de040 broke all the tests. the `build.gradle` needs to be refactored to do whatever it is 1.2.3 wants, this will take some time, seems like none of the proguard rules are being applied to the automation test build type.

**Comment by moxie0** [comment]
This doesn't seem like a sustainable testing strategy, ultimately can't the harness be external to the apk?

**Comment by rhodey** [comment]
I think we could have checked that the commit didn't break all tests before merging it into master. when we update the gradle build plugin there will always be a chance that we will need to change the syntax of our build.gradle, this time it affected the syntax we use for our test build types, next time it will be something different.

I don't agree that this has anything to do with our testing strategy.

**Comment by rhodey** [comment]
all android test frameworks (official and 3rd party) are built off the idea that a test suite is comprised of two APKs:

1) the apk of the application under test
2) the instrumentation apk, used to manipulate the application under test, basically a test harness

my understanding is that the instrumentation apk must be built against the application apk, always, everything I've read states this as a given and every `build.gradle` also, some reasons I can extrapolate are:

1) for basic unit tests the instrumentation apk definitely needs access to application classes else there would be nothing to unit test.
2) for UI tests such as UIAutomator, Espresso, and some Robolectric stuff the instrumentation apk needs access to the generated application `R.*` for matching UI elements.

if we separated the code under test and the testing code into two repos, the instrumentation apk would still have to be built against the application apk, so one would need to be merged into the other at test time. the repo that builds the instrumentation apk would need to simultaneously merge into master, RC branches, and every PR without merge conflicts. also to build the instrumentation apk we must know what build type (and potentially flavor) of the application apk to build against, and to run the tests we must know the filename of the resulting application apk, both of these things can be changed explicitly in `build.gradle` (as was done in the above referenced commit) or unintentionally by updating gradle build tools (as was done in the above referenced commit).

I think that what we have is as good as it gets for now, the limitations of our current setup being that:

1) when we update gradle build tools we may need to update our build.gradle syntax on master.
2) when build.gradle on master changes the name of the test build types, PRs will fail until they rebase.
3) when build.gradle on master changes the filename of the resulting test apks, PRs will fail until they rebase.

notice that all the limitations of our current setup would exist if we moved our test code to another repo, and then some.

**Comment by nikwen** [comment]
I started getting the tests up and running again. Not finished yet but I fixed the gradle thing. :smile:

**Comment by nikwen** [comment]
Okay, I've got everything up and running now in my [`bring_back_automated_tests`](https://github.com/nikwen/Signal-Android/tree/bring_back_automated_tests) branch. Before I can create the pull request, I still have to read and sign the CLA though.
