### ISSUE TITLE
conversation sort order not updated on message send

### ISSUE THREAD

**Issue by rhodey** [WhisperSystems/Signal-Android#3478]
tested on my GB device with a25bedff2888399bde6b880a32d64a7cd794fe92

1) send message to person A (new conversation)
2) receive message from person B
3) send another message to person A
4) notice that the conversation with person B is still sorted top

**Comment by rhodey** [comment]
I'm actually seeing some strange message sort behavior on 2.19.1 from the play store on my Nexus 5 also.

**Comment by riyapenn** [comment]
Is this still an issue?

**Comment by Richtiggenial** [comment]
Can't reproduce it.
I think it isn't an open issue anymore.
