### ISSUE TITLE
Handle early-arriving delivery receipts

### ISSUE THREAD

**Issue by liliakai** [WhisperSystems/Signal-Android#3479]
In a multi-device world, it's quite common for one device to receive a delivery receipt for a message sent from another paired device before the message content itself is synced between them. In this case, the android client never marks that message as delivered.

**Comment by mammuth** [comment]
Probably implemented in https://github.com/WhisperSystems/Signal-Android/commit/a23efe7e58dcbe75e24fcb41f2b7f865b1cdf41d

**Comment by 2-4601** [comment]
Thanks @mammuth
