### ISSUE TITLE
Colorize "add attachment"-button

### ISSUE THREAD

**Issue by Mihahn** [WhisperSystems/Signal-Android#3521]
I think you should colorize the "add attachment" button, too, to have a consistent UI... :smiley:

**Comment by generalmanager** [comment]
+1

**Comment by wp9015362** [comment]
+1

I agree.

But to be precise, the attachment button / send button is not the only thing that would need to be changed.

There are some more elements which currently remain blue (default theme color), even if the contact color is set to another color:

**Blinking cursor:**

The blinking cursor inside the message input box remains blue. The easiest fix for this IMHO would be to give the blinking cursor a neutral color like gray or black all the time, regardless of the contact color.

**Overscroll animation:**

When you scroll all the way down to the bottom of a conversation or all the way up to the beginning of a conversation and then scroll even further, there is a visible overscroll animation.

I am referring to the overscroll animation which is being discussed over there (not sure if it is really called "overscroll animation"):

http://stackoverflow.com/questions/27423239/scrolling-edge-effect-on-a-recyclerview-on-lollipop-doesnt-follow-the-finger

This overscroll animation also remains blue, even if the contact color is set to another color. IMHO this overscroll animation should change it's color according to the contact color.

That overscroll animation is also in the Emoji drawer, not just in the conversation.

Regards

**Comment by Mihahn** [comment]
In my opinion the cursor should be black/grey and this animation should be grey, too. 
Take a look at Google's Messenger app: The animation is grey and the cursor black/grey in all conversations with different colors  :smile:

**Comment by moxie0** [comment]
thanks but I think we want the add attachment button to represent the "type" of the conversation, since it morphs into the send button which does the same
