### ISSUE TITLE
TS Media Messages Received Timestamps Report Different Times

### ISSUE THREAD

**Issue by purpleplatypus** [WhisperSystems/Signal-Android#3525]
Sometimes I receive an MMS (over push) when I am offline; when I finally come back online, I get the MMS message with two different received timestamps. My guess is that one timestamp corresponds to the time sent, and the other time stamp corresponds to the time received.

This seems to be confusing and unnecessary information for the user, who probably only cares about when the message is sent, and doesn't understand why the time stamps are different.

Device info: Sony Xperia Z3 Tablet Compact, stock android 4.4.4, TextSecure 2.21.0? (I compiled from b7492ebdfa580687b44f1aa31410931f0b92dcdd)

App state: Push registered, incoming SMS disabled, outgoing SMS fully disabled

Debug logs: https://gist.github.com/anonymous/98fe3fb59609cd429909

Example here where the last picture received has a timestamp difference of about 4 minutes, because that's how long I was offline. Both of these screenshots were taken within a minute of each other.

![device-2015-07-03-144642-clean](https://cloud.githubusercontent.com/assets/3969963/8504601/f3576508-2199-11e5-85ca-13fd2488052e.png)
![device-2015-07-03-144656-clean](https://cloud.githubusercontent.com/assets/3969963/8504602/f35c1ed6-2199-11e5-96f3-f7fde4dc2475.png)

**Comment by rhodey** [comment]
steps to reproduce:

1) disable TS password or unlock TS
2) put your device in airplane mode
3) ask friend with TS installed to send you a picture
4) wait a few minutes
5) disable airplane mode
6) notice that the timestamp of the received message in the conversation view is different than the timestamp in the image preview view.

**Comment by MaxXor** [comment]
Thanks for changing this. It was indeed annoying.
