### ISSUE TITLE
Duplicate messages sent to non TS user when two conversations exist (group and single)

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#3537]
I had a strange issue this weekend using version 2.20 of TS.  I had a conversation with a non-ts user on iPhone (non-signal) and I also had a group conversation with that same user + a TS user on android.  When I would send messages to the single-user conversation, said user would get duplicates of every message.  I tried rebooting my phone, etc, to no avail.  Once I deleted the mixed-group (TS/non-TS) the problem stopped.  I accidentally submitted the log w/o grabbing the link for the log to post here.  If this isn't enough info, feel free to nuke this, just thought we should have a record of it.

**Comment by riyapenn** [comment]
Able to recreate?

**Comment by jeremymasters** [comment]
I think it's solved now.
