### ISSUE TITLE
Emoji categories and ordering is incorrect/outdated in 2.22.0

### ISSUE THREAD

**Issue by wp9015362** [WhisperSystems/Signal-Android#3555]
Hello,

so, apparently you finally made the switch for 2.22.0:

https://github.com/WhisperSystems/TextSecure/commit/9a18be0a6194d4dd8ef420e9b567b1d7ce69c613

But the categories and the ordering of the Emojis is outdated (the ordering is actually not just outdated but also incorrect, it would even have been incorrect earlier).

Over there you can read how the categories and ordering should be like:

> http://blog.emojipedia.org/apple-2015-emoji-changelog-ios-os-x
> 
> **Emoji Categories**
> 
> Prepare to re-learn the position of your favorite emojis,
> as they have all changed. New categories have been introduced,
> and emojis have been re-arranged within the existing categories as well.
> 
> The new categories are:
> 
> 😃 People
> 🌸 Nature
> 🍔 Food & Drink
> 🎉 Celebration
> 🏃 Activity
> 🌇 Travel & Places
> 🔣 Objects & Symbols
> 
> Essentially, many emojis that were previously in the People or Objects categories
> may now be in one of the new, more-specific categories. Objects & Symbols is now
> a catch-all for the more obscure remaining characters.

The categories and ordering can also be seen on:

http://emojipedia.org/

So, could you please fix the Emoji categories and ordering?

Ideally before releasing 2.22.0?

Regards

**Comment by mcginty** [comment]
Will have to look at the repurcussions of having 9 categories (including recents and ASCII) in the emoji pane for small screens instead of the current 7. It's already a relatively tight fit.

**Comment by wp9015362** [comment]
I see where you're coming from.

But if the Emoji categoriy icons get smaller because you have to cram 9 (or 8, see below) in the same place where there have been only 7 before, then it's actually not that much of an issue, because you still can switch between the categories by swiping from left to right and from right to left on the Emoji drawer, so you don't actually have to press the category icons.

And if you ask me, the ASCII category does not need to be on the Emoji drawer.

At the end of the day it's an Emoji drawer, not an ASCII drawer.

ASCII emoticons can be done with any regular keyboard, so they don't have to be on the Emoji drawer wasting space with one more category.

Of course it's more convenient being able to insert ASCII emoticons via templates. But why would you even use them if you can use color Emojis instead. All TextSecure and Signal users are able to use color Emojis, and beginning with TextSecure 2.22.0 they will now all even see the same Emojis.

So, IMHO there is no reason to use ASCII emoticons. Or at least not as big of a reason to justify a category for it on the Emoji drawer.

The ASCII category in the Emoji drawer does not have all possible ASCII emoticons anyway.

It might have been a nice to have feature. But if the ASCII category steals space from the Emoji drawer and the space could be used for an actual Emoji category instead, then I'd say the ASCII category should be removed.

By the way, the reference drawer also name's the categories in actual words, see the "PEOPLE" label in the upper left on the following screenshot:

http://img.svbtle.com/0v70lxzkamb36w.png ([Source](http://blog.emojipedia.org/apple-2015-emoji-changelog-ios-os-x))

![Image](http://img.svbtle.com/0v70lxzkamb36w.png)

It would be kinda nice if the TextSecure Emoji drawer would have that as well.

Regards

**Comment by unrulygnu** [comment]
I think it makes better sense if how the user finds their emoji (categories) is consistent with the user's platform, rather than the source platform of the glyphs themselves.  This consistency helps reduce confusion when using emoji in multiple apps on the same device.

Here is Google Keyboard's emoji UI, available via long-press on the Enter key:
![google-keyboard-emoji](https://cloud.githubusercontent.com/assets/11031903/8616885/b0878316-2739-11e5-83b9-fc3c6d462f1f.png)

TextSecure's emoji categories are currently consistent with Google Keyboard's categories, which should be consistent with Android user expectations.  Is there a more important reason that they shouldn't remain this way, at least until they change in the platform?

**Comment by wp9015362** [comment]
@unrulygnu :

I disagree.

Because TextSecure is already using it's own Emoji drawer and is using it's own built-in Emoji set and overwrites native Emojis.

So, as you can see, TextSecure already differs from the native Android Emoji experience (which is very good and necessary IMHO, since the native Android Emoji experience is bad IMHO).

So why shouldn't TextSecure be allowed to have it's own Emoji drawer design?

And, by the way, not all Android smartphones are using the Google (AOSP) keyboard by default.

A lot of smartphones use manufacturer specific keyboards by default.

So even if TextSecure's built-in Emoji drawer would resemble the Google (AOSP) keyboard Emoji drawer, it would still look different on a LG smartphone for example (LG has it's own keyboard and is not using the AOSP keyboard, it's not even installed by default) unless the user would install and use the Google (AOSP) keyboard.

Regards

**Comment by unrulygnu** [comment]
@wp9015362 : Good points. :)

**Comment by mcginty** [comment]
I imagine Google will also move to the new categories and diversity-selectors in a future release. It'll be a bit of effort but seems like the way to go given it's a set unicode standard.

**Comment by jellium** [comment]
@wp9015362

1) how was TextSecure "Emoji experience" so different from Android's "Emoji experience"?

2) why is TextSecure's "Emoji experience" good and native Android's "Emoji experience" bad, IYHO?

**Comment by wp9015362** [comment]
Emoji One has now updated their family tree page with the new sorting/categorization scheme, see:

http://emoji.codes/family

You can switch through the seven categories via the category icons in the upprt right corner of the page.

Regards

**Comment by moxie0** [comment]
f7474362ff8bc75fff70ed75a1caad31fd55374e
