### ISSUE TITLE
"Raised Hand With Part Between Middle And Ring Fingers" Emoji (A.K.A. "Vulcan Salute" Emoji) is missing from 2.22.0

### ISSUE THREAD

**Issue by wp9015362** [WhisperSystems/Signal-Android#3557]
Hello,

so, apparently you finally made the switch for 2.22.0:

https://github.com/WhisperSystems/TextSecure/commit/9a18be0a6194d4dd8ef420e9b567b1d7ce69c613

And you even seem to use [the updated set](http://blog.emojipedia.org/apple-2015-emoji-changelog-ios-os-x).

But the "Raised Hand With Part Between Middle And Ring Fingers" Emoji (A.K.A. "Vulcan Salute" Emoji"), see:

http://emojipedia.org/raised-hand-with-part-between-middle-and-ring-fingers/

apparently is missing from 2.22.0, even though it would be available from the set.

So, could you please add it?

Regards

**Comment by siddhartharao17** [comment]
If this issue is still open, can I be assigned to this?
