### ISSUE TITLE
Colorize Message Details

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/Signal-Android#3560]
2.21.0

Dark theme, private conversation:
![dirty harry](https://cloud.githubusercontent.com/assets/174176/8582952/ac392656-25d2-11e5-92d2-ec2609ad9aaf.png)

----------
Light theme, private conversation:
![dirty harry](https://cloud.githubusercontent.com/assets/174176/8583539/01dcbf88-25d7-11e5-8b1b-617250f24f75.png)

**Comment by 2-4601** [comment]
![dirty harry](https://cloud.githubusercontent.com/assets/174176/8583539/01dcbf88-25d7-11e5-8b1b-617250f24f75.png)

**Comment by McLoo** [comment]
According to the arrows, you want the bubble and the action bar to be black/white like the background?

Sorry, couldn't resist :stuck_out_tongue:

**Comment by 2-4601** [comment]
@McLoo :)

**Comment by riyapenn** [comment]
See also point 2 in #3281
