### ISSUE TITLE
Direct audio capture

### ISSUE THREAD

**Issue by mcginty** [WhisperSystems/Signal-Android#3563]
Push-to-talk style.

spawned from https://github.com/WhisperSystems/TextSecure/issues/520

**Comment by turtlekiosk** [comment]
Do you see this being part of the same drawer as the direct image capture or a separate component (sort of like WhatsApp?)

**Comment by derfasthirnlosenick** [comment]
Judging from how I've observed a 12 y.o. Teenager using this feature if whatsapp, the sheer number if messages sent hints to a need for quite direct access. I.e. not a drawer.

How about as an alternative mode of selecting, we get a press-and-hold circular "menu" like paranoid android has/had, just with Material style floating buttons. Due to the location of the attach button, we'd probably need two levels as the first one can only accommodate three icons. I guess Camera, Microphone and File/other might be a good choice. And behind File/other you hide File (in the same level so that it's one swiping motion), Location and the others. Whether it would be good to put Picture and Video behindert the camera one, I do not know.

**Comment by Thunderpig72** [comment]
Telegram has this as a little button, not hidden away in a drawer. I think that should be the case here too. Especially once you combine RedPhone and TextSecure.

**Comment by mawed** [comment]
Sorry for the offtopic question (I do not know where to ask elsewhere, in #520 I can't write anything):
Was there some commit and update, when closing #520 with milestone 2.22.0?
Or was the toDo List just seperated in Audio and video issue?
I thought (hoped) this may would include the new media branch.

**Comment by McLoo** [comment]
@mawed Direct capture is in beta right now
and:
# 520 was 
> Closed in favor of # 3563 and # 3564 since all these different types of media captures will be separate PRs, making it easier to track progress.

**Comment by Dyras** [comment]
Is direct capture in the latest beta? If so, I don't see it.

**Comment by mawed** [comment]
Thank you for the information
so it was just divided not finished with milestone 2.22.0.

That's what I thought after the update with no (visible) changes.

**Comment by heyimgay** [comment]
It would be cool if the audio was encoded in [opus](https://www.opus-codec.org/) so we can have awesome quality at a small size:

> Opus is a totally open, royalty-free, highly versatile audio codec. Opus is unmatched for interactive speech and music transmission over the Internet, but is also intended for storage and streaming applications. It is standardized by the Internet Engineering Task Force (IETF) as RFC 6716 which incorporated technology from Skype's SILK codec and Xiph.Org's CELT codec. 

ffmpeg has a codec for it so we can use https://github.com/guardianproject/android-ffmpeg for example

**Comment by amenk** [comment]
:thumbsup:

**Comment by mawed** [comment]
I'm on 3.5.2 (beta) and I had this feature last version (or the one before). Was it taken back because of problems?

**Comment by mcginty** [comment]
@mawed yep

**Comment by mawed** [comment]
@mcginty Ok thanks for reopening.
I liked the look and feel of it (just to mention ;-)).

**Comment by heyimgay** [comment]
@mcginty any chance we'll get opus audio messages next time around?

**Comment by smichel17** [comment]
If there's a better place to give feedback on this or other issues, let me know.

When I used the direct audio capture feature for the time it was enabled, I liked hold to record, but found it jarring that it would immediately send upon letting go. I expected it to act like direct image capture: when I let go, it attaches the audio clip, which I now have a chance to review before sending.

**Comment by cxarmonato** [comment]
implemented here: https://play.google.com/store/apps/details?id=org.privatechats.securesms

**Comment by smichel17** [comment]
Signal Android Beta had direct audio capture as well. It was removed because it crashed Signal iOS. I imagine when OWS finds a full time iOS dev they will quickly reinstate the feature.

________________________________

**Comment by Tormen** [comment]
Hi, Is this feature still to come anytime soon ?
In development ?
Can I help by testing it ?

Thanks a lot in advance!

**Comment by agrajaghh** [comment]
Please don't bump issues (they just create extra email notifications for the devs). Thanks

https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues

**Comment by Tormen** [comment]
"Thus bumping issues with :+1:s, me toos or asking for updates "
OK I get it.

But :
I also asked if I can help! This is not listed in the link you posted.
... or how can I offer my help in another way ?

Tormen.

**Comment by Tormen** [comment]
Is there anything I can do to help ?

According to the link you sent me this question should be fine, no ? --- I really don't want to be stuborn here, but just transmit my sincere wish to help!!

If you don't like people to offer their help, could you please update your dont-bump-issues to also list "offer your help" in the list of unwanted annoyances:

> Thus bumping issues with :+1:s, me toos or asking for updates just generate unnecessary email

**Comment by agrajaghh** [comment]
> Is there anything I can do to help ?
 
https://github.com/WhisperSystems/Signal-Android/issues/3563#issuecomment-179980289:

> It was removed because it crashed Signal iOS. I imagine when OWS finds a full time iOS dev they will quickly reinstate the feature.

afaik this is still true, so I don't think there is anything to do at the moment until there is full time iOS dev again...
