### ISSUE TITLE
I'm having problems sending unsecured SMS. I've included the debug log. Thanks.

### ISSUE THREAD

**Issue by aggonzo326** [WhisperSystems/Signal-Android#3571]
https://gist.github.com/anonymous/23e869b7ba2767202d8d

**Comment by mcginty** [comment]
I only see the ConversationActivity being paused in your main debug log.

**Comment by merkste** [comment]
Perhaps the issue's author faces this problem:
Switching between sms and encrypted message after entering a certain amount of text quite often crashes TS for me.
https://gist.github.com/8026ffad438c9abd2dae

**Comment by moxie0** [comment]
@merkste Could you open a new issue for that?

**Comment by 2-4601** [comment]
I was just writing a reply to @merkste's issue with reproducible steps. I will add it to a new issue.

**Comment by agrajaghh** [comment]
closing since old/inactive/not usefull log

please reopen if you encounter it again
