### ISSUE TITLE
new group conversation creates additional conversations with members

### ISSUE THREAD

**Issue by agrajaghh** [WhisperSystems/Signal-Android#3581]
If you create a new group with people you don't have a conversation with already, the new group gets created plus "normal" conversations for every member. If you open this conversations and go back, the conversation is gone. Tested with a new install of current master (https://github.com/WhisperSystems/TextSecure/commit/d6d881b0cac20ecb5915cf094386aa44662e4ec6)

**Comment by ehartsuyker** [comment]
I started looking into this, and it looks like what is happening is that when a group is created, a new thread entry is added to the SQLite DB for all the users in the group. From a design perspective, would it make more sense to prevent these entries from going into the DB or woudl it make more sense to prevent the empty threads from being visible?

**Comment by jeremymasters** [comment]
@ehartsuyker Could that be related to this? #3537

**Comment by ehartsuyker** [comment]
@jeremymasters I can't say. When I was poking around and testing it, I was only testing with other TS users. But, I'm pretty sure the point I found where it's creating the multiple threads is the same for all group creations (don't quote me, I just started leaning Android on Wednesday). Anyway. That answers the question and I'm going to say don't let the empty threads get created.

**Comment by moxie0** [comment]
I'm not able to reproduce this, is it still a thing?

**Comment by agrajaghh** [comment]
can't reproduce it anymore :blush:
