### ISSUE TITLE
Multi-row messages jumping to the left when opening a thread

### ISSUE THREAD

**Issue by ComeGitSome** [WhisperSystems/Signal-Android#3588]
Send a message with at least two rows, like
XXXXXXX
XXXXXXX

The new row has to be made with the enter key, not by writing a long message.
Open the thread and press back a few times. The text inside the message will jump to the left

**Comment by 2-4601** [comment]
Tried to reproduce this:

1) I send a message:
```
XXXXXXX
XXXXXXX
```
2) I close the thread???
3) I open the thread
4) I press back a few times
5) Now I'm in Android's home screen
6) wut?

Nexus 4, Android 5.1.1, TS 2.21.0

**Comment by ComeGitSome** [comment]
Sorry, I meant keep opening the thread. It doesn't happen every time (but almost) and it also makes it easier to spot if you do it over and over again.

**Comment by 2-4601** [comment]
What is your device? And which Android and TextSecure versions are you running?
Could you post a video of the glitch?

**Comment by ComeGitSome** [comment]
Samsung Galaxy S4 GT-I9509
Android 5.0.1
Textsecure 2.21.0 (beta)

I recorded a short video but haven't figured out how to remove all personal info using OpenShot.

**Comment by 2-4601** [comment]
Thanks for taking the time to record a video.

Covering personal data in a video might be a little bit tedious. Another way would be to create so many new groups that they cover the whole conversation list thus hiding all your personal conversations below. And then reproduce the glitch in one of those group conversations. This requires at least one other person to test with. You can create as many groups with the same person as you wish.

**Comment by 2-4601** [comment]
It seems you can also create a group with yourself so you don't need to bug your friends for this.

**Comment by ComeGitSome** [comment]
![screen-recording](https://cloud.githubusercontent.com/assets/1025490/8604677/5c5b4412-2680-11e5-8926-141480828a78.gif)

**Comment by 2-4601** [comment]
:+1: very nice, thanks!

It might help to also submit a debug log.
Immediately after the glitch go to
_Settings --> Advanced --> Submit debug log_
and then paste the url here.

I'm not sure if the glitch will be caught in the log but then you have at least done pretty much everything you can to help fix this.

**Comment by agrajaghh** [comment]
I can't see the jumping but sometimes the whitespace on the right is bigger than normal:

**normal:**
![normal](https://cloud.githubusercontent.com/assets/5296073/8605378/2b462496-2685-11e5-9ca2-95ee64a65f90.png)
**bigger:**
![bigger](https://cloud.githubusercontent.com/assets/5296073/8605382/2d391150-2685-11e5-819a-16d0c4af1412.png)

**Comment by 2-4601** [comment]
I experience this like @agrajaghh 
Didn't notice before.
Nexus 4, Android 5.1.1, TS 2.21.0

**Comment by 2-4601** [comment]
I'm not experiencing this anymore with TS 2.23.2

**Comment by ComeGitSome** [comment]
Still happens for me on version 2.23.2. Did you try a couple of times?

**Comment by 2-4601** [comment]
Not just a couple of times but 10 times for each contact :)
I will try tomorrow again even more thoroughly.
But as I've said before I cannot reproduce this exactly as @ComeGitSome. Only @agrajaghh​-style
So I think @ComeGitSome should have the final say when this is fully solved.

**Comment by 2-4601** [comment]
Sorry, it's still there for me too. Just requires a lot of tries.

Here are three pictures to demonstrate. The pictures are composed of two images: top is no issue; bottom has the padding issue.

**multiple lines, but no newline characters: no bug**
![wrappednonewlines](https://cloud.githubusercontent.com/assets/174176/8889214/a128507a-32d9-11e5-988e-718aaa7c3c42.png)

----------

**one line (no newline characters): no bug**
![nonewlines](https://cloud.githubusercontent.com/assets/174176/8889216/aa34dea4-32d9-11e5-956e-6ef4cd040e0b.png)

----------

**multiple lines, two newline characters: bug**
![newlines](https://cloud.githubusercontent.com/assets/174176/8889218/b08e811a-32d9-11e5-9eab-e3560ad91c17.png)

**Comment by ComeGitSome** [comment]
I don't see it every time either. I'm guessing either it happens too fast or more likely due to lag that hides the effect, because the same is true when watching the gif I posted.

**Comment by 2-4601** [comment]
I can see the jump if I open "conversation settings" and then press back. Works only the first time though.

**Comment by mcginty** [comment]
just tried to repro this and can't - assuming fixed

**Comment by 2-4601** [comment]
@mcginty Try harder :stuck_out_tongue_winking_eye: 
![jump](https://cloud.githubusercontent.com/assets/174176/11196827/0eeda8c0-8cc2-11e5-9ba0-cc00facab49a.gif)

3.4.2, Nexus 4, 5.1.1

**Comment by mcginty** [comment]
Still no repro on the two devices I tried on, but will keep it open I guess!

**Comment by 2-4601** [comment]
Yeah, this is a cockroach issue. When you think it's gone, it comes back. This was closed July when I thought I couldn't reproduce it any more but I just hadn't tried hard enough :)
I can only reproduce this on Nexus 4, not with my other device (Huawei U8800)

**Comment by ComeGitSome** [comment]
Can't reproduce the issue.
