### ISSUE TITLE
Showing contact info is choppy when Swiftkey is up

### ISSUE THREAD

**Issue by ComeGitSome** [WhisperSystems/Signal-Android#3599]
Open a message thread
Bring up the keyboard (Swiftkey, stock Samsung keyboard doesn't have the same problem)
Press contact picture to show contact info

The keyboard moves up with a white bar at the bottom and then goes back down. 

Samsung Galaxy S4 GT-I9509
Android 5.0.1
Textsecure 2.21.0 (beta)

**Comment by claenn** [comment]
Can't confirm.

SwiftKey-Beta-5.3.0.77
Device  : LGE Nexus 5 (hammerhead)
Android : 4.4.4 (8166, slim_hammerhead-userdebug 4.4.4 KTU84Q 8166 test-keys)
OS Host : slimgerrit
App     : TextSecure 2.21.0

**Comment by McLoo** [comment]
Can't reproduce on Sony stock 5.0.2 and CM 12.1 with SwiftKey. Contact info smoothly rolls in from screen bottom.

**Comment by ComeGitSome** [comment]
Also happens when pressing the Home button to show recent apps when in Textsecure with the keyboard up. The keyboard bounce also happens when doing this from Firefox but not in Youtube.

**Comment by ComeGitSome** [comment]
Can't reproduce the issue.
