### ISSUE TITLE
Emoji aren't rendered in generated avatar

### ISSUE THREAD

**Issue by mcginty** [WhisperSystems/Signal-Android#3604]
![img_20150710_130357](https://cloud.githubusercontent.com/assets/373823/8628041/42f92a64-2704-11e5-9360-0fac4040109c.JPG)

**Comment by agrajaghh** [comment]
fixed with https://github.com/WhisperSystems/Signal-Android/commit/67415a8dcbeff4ab3b52757400fe09fb015cca5c
