### ISSUE TITLE
"Verify identity" doesn't use contact color

### ISSUE THREAD

**Issue by ComeGitSome** [WhisperSystems/Signal-Android#3630]
Opening "verify identity" switches back to blue instead of using the contact color like "conversation settings". Would also be nice to have a smooth animation like when showing "conversation settings".

**Comment by wp9015362** [comment]
More or less a duplicate of:

https://github.com/WhisperSystems/TextSecure/issues/3521

Regards

**Comment by agrajaghh** [comment]
doesn't look like #3521 

but I got a PR open to fix it: #3580
