### ISSUE TITLE
Message Length Limits Are Not Enforced

### ISSUE THREAD

**Issue by purpleplatypus** [WhisperSystems/Signal-Android#3658]
On Android 4.4.4, TextSecure version 2.21.0 (Sony Xperia Tablet Compact Z3) I found that pasting an extremely long draft message (I was inspired by #3388) into the new message box will bring up the max message length indicator without actually enforcing it. Hence we can get negative characters remaining as shown below.

I was still able to send this message without issue to a Signal app; interestingly it causes Signal to crash while trying to load the message.

I'm assuming that the desired behavior is to actually enforce message length restrictions, so I will look into this.

Steps to Reproduce:
1. Write a really long draft message until you get past 2000 characters.
2. Profit.

![device-2015-07-13-220630](https://cloud.githubusercontent.com/assets/3969963/8665697/8572e574-29ac-11e5-920e-c0d37a00a535.gif)

**Comment by oaim** [comment]
Have a look at https://github.com/WhisperSystems/TextSecure/issues/3362

**Comment by junitas** [comment]
I noticed this as well when playing with a fix for #3388. 2000 chars seems to be like the speed of light, you can approach it, and can exceed it, you just can't ever match it.

**Comment by ehartsuyker** [comment]
Hey. I've mostly solved this here (or so I think):
https://github.com/ehartsuyker/TextSecure/commit/2e3907940457591d3312ad60c1344d2b8efd81c2

I have two smaller things I can't figure out and could use some assitance.

First, is there an image that signifies that a message can't be sent? Right now I'm reusing the `ic_menu_remove_holo_light` which isn't a great idea.

Second, I can't seem to figure out where the icon for the standalone paperclip for tha attachment is controlled. I can get sending being disabled and the `X` from `ic_menu_remove_holo_light` to be displayed, but behind (in front of) the `X` the paperclip is still visible.

**Comment by agrajaghh** [comment]
closing in favor of #5146
