### ISSUE TITLE
Cyanogen contact and messaging

### ISSUE THREAD

**Issue by liamgoode** [WhisperSystems/Signal-Android#3695]
I am having a similar problem to some of the other guys but mine seems to go a little further. My contacts don't seem to link with my messages, but also when I send an SMS with some of my contacts the phone will automatically send the message to other contacts too. 

I will then get replies from other people not knowing why I am texting them but very rarely will the intended recipient get the actual message. With one if my contacts I have given up texting him now and I have resorted to using whatsapp. 

This is very very confusing for me and I must admit I have no idea why its happening. Furthermore I feel very unable to fix it. Can anyone help me??

**Comment by Dyras** [comment]
I think this is something you have to take up with Cyanogen.

**Comment by riyapenn** [comment]
Closed unless there's more information and logs that suggest this is a bug in Signal.
