### ISSUE TITLE
Quick capture temporarily shows previous preview texture before re-initializing

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#3699]
Switch orientation while QC is open 
See former orientation preview flipped and stretched  then the new orientation preview shows up

**Comment by McLoo** [comment]
Also if camera was open and closed and reopened in Other orientation.

**Comment by mcginty** [comment]
Is this just what you see temporarily until the preview becomes live, or do you mean the live preview is skewed?

**Comment by McLoo** [comment]
Again not being precise enough. 😰
Is just temporarily.   Below 1 sec I'd say. Then the expected  preview shows up correctly.

**Comment by mcginty** [comment]
Ok, that's expected. I'm going to change this issue to just say we should find a way to not display old textures while the camera is initializing.

**Comment by mcginty** [comment]
in 3.6.0
