### ISSUE TITLE
Prevent switch camera button rapid tapping 

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#3700]
A accidentally performed double tap gives a short freeze and than your still on the same camera. 

Same if that manic squirrel goes wild on the button. Freeze until all camera switches where performed (changes not visible) ...

**Comment by McLoo** [comment]
Just crashed WA with squirrel tapping
So this might not only be a UX thing...

**Comment by mcginty** [comment]
in 3.6.0
