### ISSUE TITLE
Crash after Switching to Emoji Pane

### ISSUE THREAD

**Issue by merkste** [WhisperSystems/Signal-Android#3721]
I hope this is no duplicate. I've just typed a message and wanted to insert an emoji. But the plane remained blank and TS crashed.
https://gist.github.com/6a3ccd06e5635c02fb62

**Comment by merkste** [comment]
This crash has happened several times now. But this debug log is different:
https://gist.github.com/faa01ac8845e48d43b70

**Comment by agrajaghh** [comment]
Android must be joking:
`E/AndroidRuntime(21291): java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack available`

**Comment by mcginty** [comment]
There have been enough changes since this issue that we'll need new debug logs if it can still be reproduced. Closing unless anyone still experiences this.
