### ISSUE TITLE
Pressing back in Conversation doesn't return to conversation list, but just back to the previews app/launcher

### ISSUE THREAD

**Issue by mammuth** [WhisperSystems/Signal-Android#3739]
#### Reproduce:
- Remove all apps from Androids *"Recent Apps"*
- TS message arrives, notification appears
- Open the conversation by clicking on the notification
- read/answer/whatever and return with the back key

#### Result: 
- Instead of returning to the main view of TS, as expected, the conversation activity closes without opening the main activity
- When wanting to switch to TS using *"Recent Apps"* at any later time the conversion gets opened, also with no ability to come back to the main view

#### Expected:
- Always show the conversation list when pressing back in a conversation

Or is this behavior intentional, because *"well...thats how Android works"*?
[It's not, how Android works](https://developer.android.com/training/implementing-navigation/temporal.html#SynthesizeBackStack) ;-)

**Comment by sedrubal** [comment]
:+1:

**Comment by 2-4601** [comment]
Settled by 694e6064bdc2a6e7c0e74c13b67c9a448b90b7e1
