### ISSUE TITLE
Visual self send issues for media attachements

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#3779]
2.23.2

1. "received" image download indicator runs forever (reduction of forever was too less)
2. the media message bubble is dark gray not convo-colored  (gray in light theme)
3. **Edit**: just noticed from the screenshot, the avatar is also incorrect
4. **Edit 2**: if you go to message detail, the sender name above the meesage bubble is "Anonymous"

**Comment by McLoo** [comment]
![screenshot_2015-07-23-21-31-44 01](https://cloud.githubusercontent.com/assets/5326916/8860283/10a2618c-3183-11e5-866b-9ef785426b4c.png)

**Comment by 2-4601** [comment]
Sending pics to yourself?

**Comment by McLoo** [comment]
not only :pig2:s but also :cat2:s

My first sentence for the report was "I'm not going to argue about why one self sends media", maybe i dropped that line too hasty :wink: 

Let it only be for having secured direct captures

**Comment by 2-4601** [comment]
Yeah, I guess it makes even more sense when multi-device support is fully released 😰

**Comment by McLoo** [comment]
Good point, self send isn't synchronized yet @moxie0

**Comment by McLoo** [comment]
This is an ex issue now. Can't tell since when though.
