### ISSUE TITLE
MasterCipher constructor is sloooooow

### ISSUE THREAD

**Issue by mcginty** [WhisperSystems/Signal-Android#3857]
https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/crypto/MasterCipher.java#L65

As it turns out, over the course of loading the items in the conversation list view, Cipher.getInstance is called 32 times from its various initializations and takes ~100ms of main thread time *per dataset change*, which means ~300-500ms of main thread time per message sent since the cursor is reloaded up to 5 times when a message is sent.

Seems like we should either have one MasterCipher instance that we pass along to the various Mms/SmsDatabase readers or at least have the Cipher instances be static singletons.

**Comment by moxie0** [comment]
The choice is between incurring the hit of construction or serializing access.  The former is generally faster.  Last resort is object pooling, but we should only do that if it's the bottleneck, and I doubt we're there yet.
