### ISSUE TITLE
Switchcompat sliders in dark theme to match the ones in light theme

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#3881]
In different preferences sliders (switchcompat?) are used.  In the light theme, they are the TS blue which looks great, while in the dark theme they are aqua.  While this is certainly not a show-stopper, it would look nicer if they matched the same blue or a more muted blue than having them be aqua.  For someone who knows Android dev, unlike myself, this is probably pretty easy.

**Comment by heyimgay** [comment]
I think i have a fix for this in my branch, i haven't tested it yet but it is a simple change

https://github.com/heyimgay/TextSecure/tree/patch-1

**Comment by jeremymasters** [comment]
Does this change affect the color of the typing cursor in dark theme as well?  These two things would be awesome.
