### ISSUE TITLE
Direct capture shows up shortly

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#3887]
play release 2.24.1 (log is 2.24.0)
if of any use: https://gist.github.com/b493615acf56dff114ac

- open convo
- lock screen
- open lock screen camera
- lock screen (don't press 'back')
- unlock (with pattern in my case) 
- have TS convo in half screen direct capture mode for a few moments - without a preview (black screen) 
- then the DC preview closes

**Comment by McLoo** [comment]
hm, same in WhazzAppp
Can we to this better?!

**Comment by samlanning** [comment]
Doesn't seem to be present on Android 5.1.1 Nexus 5

**Comment by mcginty** [comment]
this sounds like a bug with the lock screen camera not releasing the camera properly
