### ISSUE TITLE
Change string 'Neither' to sth. more descriptive

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#3903]
It works well in the chooser, but might rise some questions when seen in the notifications preferences overview

**Display in notifications**
*Neither*

sth. like
**No/Hide Details**
or
**No/Hide Information**
would fit better imo

**Comment by 2-4601** [comment]
For comparison Signal uses a very explicit string:
_No name or message_

**Comment by RiseT** [comment]
Another possibility, derived from the existing strings 'Name and message' and 'Neither':

**Neither name nor message**
