### ISSUE TITLE
default Group avatar no more circle cropped in GroupCreateActivity

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#3908]

**Comment by 2bard** [comment]
@McLoo what device are you using?

**Comment by brumsoel** [comment]
This has been fixed by #3915 (according to the PR description).

**Comment by McLoo** [comment]
@moxie0 please reopen, as I encountered this in 3.4.2

**Comment by mcginty** [comment]
already closed in #4639
