### ISSUE TITLE
Wording: 'SD Card' vs. 'Storage'

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/Signal-Android#3920]
The wording of several strings is inconsistent regarding the use of 'SD Card' and 'Storage', although all of these strings refer to the very same thing (as seen in the source code).

I'd like to do a small PR correcting that, but want to gather information first what term is prefered.

**Some things to consider:**
- As far as I know, TextSecure is not able to access a 'real' SD card when using KitKat or Lollipop.
- The term 'SD card' could be confusing to users with no SD card slot on their phone. The concept of a 'emulated SD card' could be even more confusing to those users ('There are no power users').

**Possible terms:**
- SD card
- storage
- device storage
- external storage (thx, @2-4601)
- anything else?

I'd appreciate your input!

**Comment by 2-4601** [comment]
I've been meaning to open an issue about this myself but never got around to it.

According to the Android docs **external storage** is a term that both applies to SD cards and non-removable storage (such as in the Nexus devices).
https://developer.android.com/guide/topics/data/data-storage.html#filesExternal
> Every Android-compatible device supports a shared "external storage" that you can use to save files. This can be a removable storage media (such as an SD card) or an internal (non-removable) storage. Files saved to the external storage are world-readable and can be modified by the user when they enable USB mass storage to transfer files on a computer.

But **external storage** might be confusing as it's an Android (developer) term not known to most users. (_What's internal storage then?_) Thus it might be best to just use the term **storage**.
In any case the term **SD card** is definitely something that should be gotten rid of.

**Comment by BrokenPhysics** [comment]
I am definitely in favor of *storage*. I agree with @2-4601 that *external storage* is confusing: I didn't know what it meant until now, although I started doing android development recently.
