### ISSUE TITLE
Unread Message in a groupchat (startpoint)

### ISSUE THREAD

**Issue by Schweineschwarte** [WhisperSystems/Signal-Android#3955]
Hello,
if I receive a lot of messages in a groupchat, TextSecure begins with the newest/last message and don't show the point of the first unread message. It's very inconvenient, if I receive a lot of unread messages, in a groupchat!
(The messages are chronological right, but TextSecure scrolls to the last message.)

**Comment by 1337sup3rh4x0r** [comment]
I'd also love Textsecure to help me continue from where I last left the conversation. Maybe add an arrow on the side that scrolls down to the newest message on a click.

**Comment by riyapenn** [comment]
Related discussion #1211

**Comment by sedrubal** [comment]
Related pull request: #5422

**Comment by FeuRenard** [comment]
Fixed by d9b42c436907fbf5d0c34b1b5b25baac65c1d628
