### ISSUE TITLE
Allow disable ringtone per conversation

### ISSUE THREAD

**Issue by RalfJung** [WhisperSystems/Signal-Android#3957]
Currently, it is possible to choose a different ringtone per conversation. However, it does not seem to be possible to have _no_ ringtone for a specific conversation, while having some ringtone (the system one, in my case) for all the others: The per-conversation ringtone selection lacks the "None" option.

**Comment by johanw666** [comment]
You can easily work around that by creating a ringtone with no sound and selecting that one.

**Comment by agrajaghh** [comment]
"silent" is disabled here:
https://github.com/WhisperSystems/TextSecure/blob/master/res/xml/recipient_preferences.xml#L17

I think it would make sense to allow "silent" since muting the conversation is different (no vibration). 
Should I open a PR, do you change it yourself or would you like to leave it like this?

**Comment by McLoo** [comment]
@agrajaghh now that's a good find! Was really annoyed not being able to have vibrate only. 
PR this ASAP plz :grin:

**Comment by jeremymasters** [comment]
Having not really used the mute conversation yet, does it mute ALL notification as in even not showing a notification popup, or is it just no sound/vibration?

**Comment by McLoo** [comment]
@jeremymasters mute = you won't get any info 
No sound, no vibration, no notification

**Comment by agrajaghh** [comment]
@McLoo noticed #3962, will try to fix it before opening a PR for this one...

**Comment by agrajaghh** [comment]
@mcginty @moxie0 is it inteded that it's not possible to set per-recipient ringtone to silent? If not, I'll try to implement it...

**Comment by dingens** [comment]
Please pull this. The default "mute" mode is often too much, as it even disables notifications. I usually do want to see these.

**Comment by agrajaghh** [comment]
@dingens Please don't bump issues. Unfortunately bumping or +1's don't help fixing this issue (they just create extra email notifications for the devs). Thanks

https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues

**Comment by jeremymasters** [comment]
@dingens Going [here](https://whispersystems.discoursehosting.net/) is a great place to discuss though.

**Comment by 2-4601** [comment]
Fixed by #4957
