### ISSUE TITLE
Disorted photo

### ISSUE THREAD

**Issue by merkste** [WhisperSystems/Signal-Android#3977]
Taking a photo in app gives a distorted picture, see screenshot below. TS 2.25.3, Samsung GT-I9300, Archidroid, Android 5.1.1.
https://www.dropbox.com/s/tt7akm4hfnzwdo2/Screenshot_2015-08-24-17-33-50~2.png?dl=0

**Comment by mcginty** [comment]
which samsung phone?

**Comment by merkste** [comment]
Sorry, I must have deleted that info accidentally. It is a Samsung GT-I9300.

**Comment by f41c0r** [comment]
I have multiple GT-i9300s running non-stock Replicant (basically Cyanogenmod with binary blobs stripped out) have never seen anything like this. Maybe related to #3752? The images look similar...

**Comment by Dyras** [comment]
This happened to me once with Paranoid Android. Except it didn't happen in TS, it happened in Chrome. Does it happen every time, or just really really often? Are you sure it's not Archidroid screwing you?

**Comment by merkste** [comment]
It happened almost every time. However, the update to 3.5.2 appears to solve the issue, fingers crossed.
