### ISSUE TITLE
delivery indicator in conversation list item

### ISSUE THREAD

**Issue by mcginty** [WhisperSystems/Signal-Android#4049]
the conversation summary should show the most recent message's delivery status if it's outgoing

**Comment by McLoo** [comment]
Sound like #1363

**Comment by mcginty** [comment]
similar but different

**Comment by McLoo** [comment]
uh, wanted to post #3012 as reference not  1363
as @agrajaghh mocked sth. up there

**Comment by 2-4601** [comment]
7c95adc7e61e8157a686caa19ac8b6c8cf593eae annihilated this
