### ISSUE TITLE
Notifications menu shows "Default" instead of "None"

### ISSUE THREAD

**Issue by rg3** [WhisperSystems/Signal-Android#4109]
Minor UI bug: when choosing no sound for notifications in the notification settings menu, the program displays "Default" instead of "None" under the word "Sound".

**Comment by agrajaghh** [comment]
fixed with https://github.com/WhisperSystems/Signal-Android/commit/6a99c6c4ac5aa7c0d1e0024bf2800b2ed7f50a10
