### ISSUE TITLE
Old notification icon on xxxhdpi devices

### ISSUE THREAD

**Issue by blblee3lee** [WhisperSystems/Signal-Android#4110]
Just a minor issue. I guess it's the old icon_notification.png in res/drawable-xxxhdpi-v11.

Keep up the absolutely fantastic work! Ignore the haters! ;-)

**Comment by tjom** [comment]
The notification icon on pixelapse is only 82 x 82 and I couldn't find any svgs, so that is the maximum resolution I could export.

**Comment by cascheberg** [comment]
Fixed in #5250
