### ISSUE TITLE
Everything is messed up after phone number change

### ISSUE THREAD

**Issue by fumazu** [WhisperSystems/Signal-Android#4113]
I recently had to change my phone number and used the recommended protocol from the support pages to do so: http://support.whispersystems.org/customer/portal/articles/1468975

After reenabling push messages everything worked fine on my side, but most of my contacts only received an error instead of my messages (*Message encrypted for non-existant session*). After they sent a message to me this problem was resolved. I guess a new session was opened by that?

Furthermore my old number did still show up in all of my group conversations and broke them for everybody (*Error sending message*). As I can't reactivate my old number, our only option was to create new groups. My first attempt to do so was also unsuccessful because of the session errors mentioned above. Half of the members still had their old session with me and only received notification about an "unknown group" in which they could not read or write.

I'm not familiar with the specifics of how Textsecure handles sessions or group conversations, so all I can do is report this strange behaviour and hope for some smart people to figure out what went wrong here.

**Comment by moxie0** [comment]
Hmm yeah there's not great support for changing phone numbers.  Definitely something we should consider.

**Comment by riyapenn** [comment]
Closing, use https://github.com/WhisperSystems/Signal-Android/issues/3558
