### ISSUE TITLE
Group conversation bugs.

### ISSUE THREAD

**Issue by GilCol** [WhisperSystems/Signal-Android#4123]
There are some bugs in group conversations when following these steps.

Two parties, ＃1 and ＃2 
1. ＃1 disables Textsecure-messages in settings
2. ＃2 creates a group conversation and invites ＃1
3. ＃1 enables Textsecure-messages in settings
4. ＃2 sends a message in the group conversation

This scenario resulted in four found bugs

- The first message that is sent by ＃2 in step 4 is not received by ＃1.
- When a message is successfully transmitted, the group thread appears in ＃1 chat list.  But it doesn't have the selected thread name. It uses Unnamed group.
- Pressing the "show members" icon will not display any members.
- (Major problem) ＃1 can't open the keyboard. Pressing the emoji icon will open the  emoji drawer but it is not possible to press send. Attaching a file is also possible, but it is not possible to press end.

Device info: 
- Samsung Galaxy S5. Android 5.0. Textsecure 2.26.2.
- Sony Z3 Compact. Android 5.1.1. Textsecure 2.25.3.

App state: 
- Push registered. 
- Enable/Disable Textsecure-messages.

Log: https://gist.github.com/anonymous/f47acfb7b705db94e712

Related issues: https://github.com/WhisperSystems/TextSecure-Browser/issues/274

I am investigating what causes this problem. Would appreciate any comments/advice, specially on the 4th bug.

**Comment by jeremymasters** [comment]
I would suggest updating TS to the latest version (27.2) to make sure these are still present.

**Comment by riyapenn** [comment]
Is this still an issue in Signal?  
Are your messages going through as MMS (this would happen if your contact list updated after user 1 un-registered and before he/she re-registered)?

**Comment by sebrojas14** [comment]
I'm having varius bus on groups conversatiosn with current version from Play Sotre.
1) Almost all messages I send to the group shos error in delivery, but are arriving to other members
2) I'm getting other members messages duplicated (5 times in some cases)

**Comment by 2-4601** [comment]
@sebrojas14 The errors you describe are known issues and they are tracked in other tickets.

**Comment by 2-4601** [comment]
Reproduced with:
＃1: Huawei U8800, Android 4.0.4, Signal 13.5.2
＃2: Nexus 4, Android 5.1.1, Signal 13.5.2

> Two parties, ＃1 and ＃2 
> 1. ＃1 disables Textsecure-messages in settings
> 2. ＃2 creates a group conversation and invites ＃1
> 3. ＃1 enables Textsecure-messages in settings
> 4. ＃2 sends a message in the group conversation
>
> - The first message that is sent by ＃2 in step 4 is not received by ＃1.

I did not experience this (perhaps because I waited for the re-registration to complete)

> - When a message is successfully transmitted, the group thread appears in ＃1 chat list. But it doesn't have the selected thread name. It uses Unnamed group.

Confirmed.

> - Pressing the "show members" icon will not display any members.

Confirmed.

> - (Major problem) ＃1 can't open the keyboard. Pressing the emoji icon will open the  emojidrawer but it is not possible to press send. Attaching a file is also possible, but it is not possible to press send.

Confirmed.

A workaround is to ask ＃2 to update the group. However an empty update still keeps the name _"Unnamed group"_ on ＃1's device. But if you also update the name, it does change.

**Debug log:** https://gist.github.com/anonymous/3a3fd2e0a3764fa5f9ea68f1af4d1f77

**Comment by 2-4601** [comment]
Come to think of it, this is essentially the same as #1048, #2581.
