### ISSUE TITLE
Upgrade material-dialogs

### ISSUE THREAD

**Issue by char32** [WhisperSystems/Signal-Android#4138]
The current master fails to compile because material-dialogs cannot be fetched from maven (they removed that version)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'TextSecure'.
> Failed to notify project evaluation listener.
   > Could not find material-dialogs.aar (com.afollestad:material-dialogs:0.7.3.1).
     Searched in the following locations:
         https://jcenter.bintray.com/com/afollestad/material-dialogs/0.7.3.1/material-dialogs-0.7.3.1.aar
   > Could not find material-dialogs.aar (com.afollestad:material-dialogs:0.7.3.1).
     Searched in the following locations:
         https://jcenter.bintray.com/com/afollestad/material-dialogs/0.7.3.1/material-dialogs-0.7.3.1.aar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by johanw666** [comment]
Building with Android Studio is still possible for me. However,you can apply https://github.com/SMSSecure/SMSSecure/commit/30032918a94e7def54fa46c574a94830a2747a1e and upgrade to 0.7.9.1.

**Comment by agrajaghh** [comment]
#3222 would remove the material-dialogs dependency

**Comment by mcginty** [comment]
Yeah, we're hoping to remove that dependency entirely (sorry for taking so long @agrajaghh :speak_no_evil:)

**Comment by Tea23** [comment]
As an interim solution, I found adding http://repo.jenkins-ci.org/public/com/ (there is a https but it has an invalid cert) works; that repo still has the old version in.

**Comment by jensMF** [comment]
I still get this error:
Gradle sync failed: Could not find com.afollestad:material-dialogs:0.7.3.1.
         Required by:
         :Signal_origin:unspecified

**Comment by RyanRiddle** [comment]
If you follow the latest instructions for adding material dialogs as a dependency: https://github.com/afollestad/material-dialogs/blob/master/README.md

That is add this repositiory

    repositories {
        maven { url "https://jitpack.io" }
    }

and replace these lines

    compile('com.github.afollestad.material-dialogs:0.7.3.1') {
        exclude module: 'appcompat-v7'
        exclude module: 'recyclerview-v7'
        exclude module: 'support-annotations'
    }

with these

    compile('com.github.afollestad.material-dialogs:core:0.8.5.0@aar') {
        exclude module: 'appcompat-v7'
        exclude module: 'recyclerview-v7'
        exclude module: 'support-annotations'
    }

and finally remove the v0.7.3.1 checksum (see "dependencyVerification" in build.gradle)

you should be able to compile.

**Comment by KyraJ** [comment]
I've got the same problem and tried your solution. But now I get:
```
:proguardDebug
Warning: com.afollestad.materialdialogs.DialogInit: can't find referenced class me.zhanghai.android.materialprogressbar.IndeterminateHorizontalProgressDrawable
Warning: com.afollestad.materialdialogs.DialogInit: can't find referenced class me.zhanghai.android.materialprogressbar.IndeterminateProgressDrawable
Warning: com.afollestad.materialdialogs.DialogInit: can't find referenced class me.zhanghai.android.materialprogressbar.HorizontalProgressDrawable
Warning: com.afollestad.materialdialogs.util.DialogUtils: can't find referenced method 'android.content.res.ColorStateList getColorStateList(int)' in library class android.content.Context
Warning: com.afollestad.materialdialogs.util.DialogUtils: can't find referenced method 'int getColor(int)' in library class android.content.Context
Warning: there were 12 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
Warning: there were 2 unresolved references to library class members.
         You probably need to update the library versions.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedlibraryclassmember)
:proguardDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':proguardDebug'.
> java.io.IOException: Please correct the above warnings first.
```
Is it easier to compile TextSecure with Android Studio?

**Comment by johanw666** [comment]
I don't understand why I have no problems building and others have issues with this library (admitedly, I'm not that much experienced with Java/Android buld systems). AFAIK the old version is hosted at a Whispersystems repository. Does your setup ignore the other repositories mentioned in build.gradle?

**Comment by KyraJ** [comment]
I'm new to Android development, too. I've just setup a vm with Ubuntu and installed gradle, git, openjdk using apt and android sdk (stand alone, without android studio) and looked at the BUILDING.md for some basic hints.
According to the error message multiple sources have been checked. I'm pretty confident that no repositories have been ignored.

**Comment by RyanRiddle** [comment]
I spoke too soon.  I have the same issue as you, @KyraJ.  I tried building with 0..7.9.1 but I get this error.

    Error:Could not find com.github.afollestad.material-dialogs:0.7.9.1:.

**Comment by KyraJ** [comment]
Just like johanw666 suggested above, I applied the solution SMSSecure apparently used: https://github.com/SMSSecure/SMSSecure/commit/30032918a94e7def54fa46c574a94830a2747a1e
It seems like there's a typo. It's supposed to be: com.afollestad:material-dialogs:0.7.9.1

**Comment by RyanRiddle** [comment]
Yep, that works.  Thanks!

**Comment by jensMF** [comment]
Yes that works, but the original build.gradle does not work.

**Comment by ldematte** [comment]
@johanw666 maybe you had it cached in your local repository? Anyway, just adding the jitpack.io repo and removing the library checksum worked for me

**Comment by dcherian** [comment]
Can be closed
