### ISSUE TITLE
Allow call handling from notifiaction

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#4160]
Right now you get the full screen incoming call activity.

If you then (accidentally) switch the app or go to home screen, it's still ringing and you have to tap the notification "Signal call in progress", that brings you back to the call activity. There should be the buttons "Dismiss" and "Answer" on the notification.

**Comment by jeremymasters** [comment]
It might also be good to have a "Dismiss/Reject with message" option here if it could fit into the notification.
