### ISSUE TITLE
Can not delete call log entries

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/Signal-Android#4190]
I can delete individual messages in Signal, but call log entries can not be deleted. This was also the case in RedPhone, I don't know if it is related.

**Comment by Norbert80** [comment]
#4229 is a closed duplicate of this.

Signal 3.0.2 android.

**Comment by Norbert80** [comment]
@moxie0 is it possible to assign a target milestone please? This is an annoying issue.

**Comment by moxie0** [comment]
I agree that this is something we should change, but posting in issues without new information to add will only make us less interested in helping.

**Comment by TheNain38** [comment]
Yes, this is something really annoying

**Comment by Norbert80** [comment]
@moxie0:
Sorry for my request.


Additional information:
Group join and leave message look like they are of the same type of information messages. A solution should also allow to delete these messages.

**Comment by gh88** [comment]
To help us remove old entries form the list you can implement simple, yet very flexible UI. Long tap on an item does 2 things: marks the item (by putting a different background color or a check box on the right) and shows "Delete" action (trash bin, 'X' mark, etc). The user has a choice now - to remove that item or tap on other items to set a bunch and to remove that bunch at once. It's simple, intuitive and convenient way to handle this process. Example - [CSipSimple](https://github.com/r3gis3r/CSipSimple) open source project, hosted in GitHub. They offer even inversion of that choice, which is quite convenient in some cases...

**Comment by gh88** [comment]
BTW, you may use the same UI to offer selective export functionality too. User chooses (marks) messages to export, taps the Export action link and all selected items go into a local text file... In this case, next to Delete, there should be Export action (and additional Invert action would be a nice touch though :).

**Comment by nrizzio** [comment]
This issue was fixed in d7e4928f22e0a0e123eadd7442c32296b6eb6fad.
