### ISSUE TITLE
TS crashes as soon as I enter my passphrase, every single time

### ISSUE THREAD

**Issue by fallennudechampion** [WhisperSystems/Signal-Android#4209]
I was conversing with a friend who uses Signal. We typically use regular SMS, as my friend is accustomed to using iMessage by default. On occasion, we converse via encrypted messaging. So on my end, my conversation thread is a mix of SMS and encrypted messages. This is the case with a few other friends as well

Today we were conversing via SMS, and my friend sent an MMS, which was likely just a picture of what we were talking about. I tapped on the MMS to download it, and TS immediately crashed

I opened TS again and entered my passphrase, and it immediately crashed. This continued to happen, over and over. The app has become unusable

I still receive SMS and encrypted messages, and notifications. If I enter my passphrase, TS will crash, but I can then see message previews in the pull down notification window. I can even use the "Mark All As Read" option

Rebooting my phone hasn't helped. I asked a few other friends to message me via TS, and to send TS messages and MMS' with picture attachments, in hopes that some state of the app would change. Nothing has worked

I'm on the latest version of Android and TS

My debug log: https://gist.github.com/anonymous/98234d272af3935fe776

Thank you

**Comment by ChaoticMind** [comment]
I think that's #4061

**Comment by ChaoticMind** [comment]
I think that might be #4061

**Comment by McLoo** [comment]
sounds like #4061 somehow
and **maybe** could be fixed by upgrading to 3.0.1 beta
though the exception is a different one, but it seems *to me* that a TS/push send job is failing and causing this.

**Comment by fallennudechampion** [comment]
I enabled aeroplane mode: success! I was able to access TS. 

I could then reply to messages, disable aeroplane mode to send them and then receive new ones, and then enable aeroplane mode to compose replies. With TS crashing every time, of course. I disabled my passphrase to make this process less tedious

I then deleted the MMS that started this all: TS is fully functional again. I enabled my passphrase and set "Media auto-download" to "none" under wifi. It was already set to "none" under "mobile data" and "roaming"

The strange thing is that I've received MMS' without any problems in the past. In this instance, when the MMS arrived, I had wifi enabled and mobile data disabled, to save on my mobile data consumption. Perhaps this was the cause?

**Comment by fallennudechampion** [comment]
See my current comment. Once I deleted the offending MMS that couldn't
download, all was fine

Thanks!


Hef

**Comment by mcginty** [comment]
https://github.com/WhisperSystems/TextSecure/pull/4246 would fix this send job NPE.

**Comment by McLoo** [comment]
can be closed as fixed #4246
