### ISSUE TITLE
Update emojis

### ISSUE THREAD

**Issue by 5boro** [WhisperSystems/Signal-Android#4279]
Apple has added [a bunch of new emojis with IOS 9.1](http://emojipedia.org/new-ios-9-1/), and users of signal for IOS are able to send them.
![1445607827279](https://cloud.githubusercontent.com/assets/3460479/10694907/b11ae118-7998-11e5-977a-559ff404af6e.jpg)
The intended emoji here was [taco](http://emojipedia.org/taco/)

**Comment by jeremymasters** [comment]
I think we should hold off on signal until emojis are all added...;)
http://www.droid-life.com/2015/10/23/new-emoji-are-coming-to-android-new-emoji-are-coming-to-android/#more-176429

**Comment by therealmarv** [comment]
Next week will be new emojis for Android Nexus phones: https://twitter.com/lockheimer/status/672206241003937792

![image](https://cloud.githubusercontent.com/assets/1050582/11556947/2c88039a-99aa-11e5-8cf1-f839184701a0.png)

**Comment by JuLx64** [comment]
I see an option related to system emojis. It Signal can use its own emojis, why doesn't it support the new ones ?
