### ISSUE TITLE
Signal 3.0.3 Suddently password required in the middle of conversation

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#4313]
I was texting with another TS friend and a few messages (5+ back and forth) suddenly was required to enter my password for TS even though I do not have it timing out.
https://gist.github.com/anonymous/bdd5248ad9ebe1207bf4

**Comment by Norbert80** [comment]
Did you put Signal to background during the conversation?

**Comment by jeremymasters** [comment]
I just set it on my desk between texts.  Nothing too complicated as far as my interaction.

**Comment by Norbert80** [comment]
?

**Comment by Norbert80** [comment]
This may be caused by Androids automated life cycle management that closes background apps if Memory is allocated.

**Comment by jeremymasters** [comment]
It has the textsecure unlocked notification in the notification area.  I didn't stop to look if that was gone or not.

**Comment by jeremymasters** [comment]
I haven't seen this since moving to 3.1.1.  I'll close it and if it happens again I can re-open.  Sound good?

**Comment by mcginty** [comment]
:+1:
