### ISSUE TITLE
No place to enter verification code after call with app closed

### ISSUE THREAD

**Issue by lukestanley** [WhisperSystems/Signal-Android#4351]
I have had 2 verification calls, much later than I pressed the button requesting them.
Each time I got the call I was already using a different app, and had no place to put the code.
So now I have to leave the app open and wait.
A manual place to enter the code would be super.

**Comment by riyapenn** [comment]
Users were receiving delayed verification calls earlier this morning.  This is not common, and if you go to Advanced > Settings > Signal you typically do not have to wait and can enter the code manually.
