### ISSUE TITLE
Audio preview controls difficult to see in dark theme

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/Signal-Android#4353]
The play button and seek bar controls are difficult to see with some colors when using the dark theme.
Example (dark theme top, light theme bottom for comparison):
![play](https://cloud.githubusercontent.com/assets/174176/10914371/c554818c-825a-11e5-8271-62e346c7a862.png)

Making them white on the dark theme would solve this.

Signal 3.1.1, Nexus 4, stock 5.1.1

**Comment by moxie0** [comment]
in 3.4.0
