### ISSUE TITLE
  Opus Codec Support

### ISSUE THREAD

**Issue by kxra** [WhisperSystems/Signal-Android#4359]
This has already been reported against RedPhone and Signal for iOS: 

https://github.com/WhisperSystems/RedPhone/issues/69
https://github.com/WhisperSystems/Signal-iOS/issues/50

**Comment by JasonLocklin** [comment]
+1 Opus provides much better audio quality at the same bitrate and other features (like forward error correction).

**Comment by mcginty** [comment]
Hey @JasonLocklin, just as a heads-up we prefer not to have the "+1" comments as it muddles up our notifications.

Opus support is certainly on the roadmap, since as the Speex page succinctly puts it: "Opus is better than Speex in all aspects."

**Comment by heyimgay** [comment]
I was looking into this, we could use https://github.com/actorapp/droidkit-opus

**Comment by Safari77** [comment]
Remember that if not using hard CBR, bitrate changes leak information about when caller is active etc.
Maybe add option to use VBR or hard CBR, default to hard CBR?

**Comment by heyimgay** [comment]
I suppose the data could be padded to seem constant.

**Comment by Dyras** [comment]
Would this fix the delay while speaking to someone? Even on WiFi with someone in the same apartment the messages are arriving like 1,5 seconds later than in a regular call.

**Comment by snaggen** [comment]
I got the impression that Android 5.0 and higher supports opus
https://developer.android.com/reference/android/media/MediaFormat.html#MIMETYPE_AUDIO_OPUS

So maybe add opus to the list of supported codecs for Android 5.0, and use that if both sides support it.

**Comment by 2-4601** [comment]
https://github.com/WhisperSystems/Signal-iOS/issues/50 has now been closed, closing this as well.
(v. 3.29 introduced webrtc)
