### ISSUE TITLE
Can't initiate secure call w/ some contacts in new Signal

### ISSUE THREAD

**Issue by hollis2001** [WhisperSystems/Signal-Android#4370]
Unable to initiate secure call with known signal/redphone contacts. Was previously able to initiate call through Redphone with same contacts. Messages report secured but the phone icon is missing the lock and directs to standard dialer when clicked. Contacts appear as signal/redphone users in contact picker. Signal has been uninstalled/reinstalled and reactivated. Debug log attached. 

https://gist.github.com/176814acb998dd088bc7

**Comment by wksantiago** [comment]
Same problem here with some of my contact other contacts show the lock
