### ISSUE TITLE
Sharing Picture with Text does not work

### ISSUE THREAD

**Issue by JavaJens** [WhisperSystems/Signal-Android#4374]
I have tried to share Image and Text from an App, the draft looks just fine with a preview of the image.
However when I hit send it just disappears. 

It sounds like #3989 but I don't use the Google Photos App.

Log is at: https://gist.github.com/anonymous/d6b9ed58ed72ebe1a3ed

**Comment by mcginty** [comment]
I'll keep this open but it's very likely that https://github.com/WhisperSystems/Signal-Android/pull/4339 fixes this as well, since the bug wasn't limited to Google Photos. Our sharing handling was generally broken.
