### ISSUE TITLE
Panoramas are displayed black if you try to open in conversation window

### ISSUE THREAD

**Issue by oholika** [WhisperSystems/Signal-Android#4380]
Signal 3.1.1.
Nexus 4
Amdroid 5.1.1

Received a panorama from an iOS user, the thumbnail showed parts of the panorama, opening in conversation showed just a black image; after saving I could see the image in my galery in full size.

**Comment by FeuRenard** [comment]
### Link to debug log (receiving Android device)
https://gist.github.com/anonymous/2f4d4d9a01f3b0ed9f2a58c764a2ae18

tl;dr `W/OpenGLRenderer(32103): Bitmap too large to be uploaded into a texture (4434x1024, max=4096x4096)`

**Comment by haffenloher** [comment]
Related: https://github.com/WhisperSystems/Signal-Android/pull/5765#issuecomment-266396839 - to fix this, we'd need something like the [subsampling-scale-image-view](https://github.com/davemorrissey/subsampling-scale-image-view) mcginty proposed

**Comment by FeuRenard** [comment]
Or Signal-iOS adopts the image size/resolution restrictions of Signal-Android. I wouldn't say that I prefer this solution but it could be better for low-end devices if that is our priority.

When I forward the 4434x1024 panorama from Android to Android it is resized to 2048x270. This can be displayed successfully in Signal.
