### ISSUE TITLE
Signal 3.1.1: When sending picture, image in thread is clipped

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#4384]
This has been around awhile. If I attach an image to a message in 3.1.1, the preview shows the correct HxW ratio (say 16:9) but after I send it, it only shows a clipped square (1:1 HxW ratio) and actually doesn't let me see the whole picture in the thread.  If I open the picture it does show the whole picture correctly.

**Comment by moxie0** [comment]
Yep, I think this is the intended behavior. We want all the thumbnails to be the same size.
