### ISSUE TITLE
(some) users in Mexico cannot register / can register only temporarily

### ISSUE THREAD

**Issue by mfb** [WhisperSystems/Signal-Android#4386]
At least some users in Mexico are having difficulty registering with Signal.  As far as I've heard, this is an ongoing problem that also affected TextSecure.

The symptoms I've seen are that 1) SMS registration does not work - the registration times out unsuccessfully.  2) The user can successfully register using voice verification, and an encrypted session can be initialized, and messages sent back and forth. 3) However, the Mexican phone then decides that it is no longer registered, and encrypted messages cannot be sent or received.

I suspect this issue may be related to #3360 - there are multiple valid formats for a Mexican phone number.

I've posted a debug log.

**Comment by moxie0** [comment]
@mfb You need to put the link to the debug log in the issue.

**Comment by mfb** [comment]
https://gist.github.com/d51e83570aeaa61ed2d2

**Comment by moxie0** [comment]
We've deployed some server changes that should help with registration at least.
