### ISSUE TITLE
Can't properly translate some strings in Signal on Transifex

### ISSUE THREAD

**Issue by bungabunga** [WhisperSystems/Signal-Android#4388]
With the latest strings added to the Signal-Android project on Transifex there is no way for me to correctly translate some of them to my language (Slovenian):

SEND TO %1$s FRIEND(S)
Send %1$s SMS invite(s)?

Due to differencies between languages I can't use () keys in the cases above and if I don't use them Transifex doesn't let me save my translations.

I suggest you solve these issues the same way as you did with #2421, without using () keys.

**Comment by pejakm** [comment]
It looks ugly for Serbian, too. I translated it as `POŠALJI %1$s PRIJATELJU(A)`, but I could also save it without "(A)" part. I'm not sure why you can't.

**Comment by bungabunga** [comment]
@pajakm I can but it's REALLY ugly.

**Comment by 5boro** [comment]
Would having dedicated strings for the singular and plural form fix it ?

**Comment by bungabunga** [comment]
yes, that would solve the issue.

**Comment by 2-4601** [comment]
@bungabunga 
> and if I don't use them Transifex doesn't let me save my translations.

You can force save it by selecting the tick box of the said translation from the left side list and then clicking review.

**Comment by RiseT** [comment]
@bungabunga Although this issue is solved now - you *can* save without the parentheses (at least I've never seen a case where you cannot). It's just a warning that Transifex displays - which you can ignore.

**Comment by bungabunga** [comment]
thanks. will wait until strings get updated on Transifex.
