### ISSUE TITLE
Signal call not an option in contact details

### ISSUE THREAD

**Issue by dcherian** [WhisperSystems/Signal-Android#4392]
Tap a contact's avatar, click the Signal icon. There is only an option to message the person using Signal, not call them even though I've made Signal calls with this contact before.

**Comment by moxie0** [comment]
@dcherian the best place for support is support@whispersystems.org thanks!

**Comment by dcherian** [comment]
No, you misunderstood me. In this screen (image below), it should be possible to make Signal calls too. Skype and WhatsApp let me call/video-call/message any contact. Seems like Signal isn't telling Android that it can make calls too.

![screenshot_2015-11-05-11-03-21](https://cloud.githubusercontent.com/assets/2448579/10974300/71faa0d8-83af-11e5-9ee9-ae55d48c8e97.png)

**Comment by moxie0** [comment]
Got it, I see what you mean.

**Comment by TheNain38** [comment]
Yeah, it would be cool if you could call someone that way too, I was going to open an issue for it

**Comment by moxie0** [comment]
in 3.4.0
