### ISSUE TITLE
New attachment drawer is cut off at the bottom.

### ISSUE THREAD

**Issue by dcherian** [WhisperSystems/Signal-Android#4405]
This occurs when a keyboard is not open and you try to open the drawer (both with attachment button and from the menu). The text saying "Camera" is cut off. I'll attach a screenshot soon.

3.3.0, Android 4.4.4, Moto G.

**Comment by dcherian** [comment]
![screenshot_2015-11-05-17-49-19](https://cloud.githubusercontent.com/assets/2448579/10984549/24e4cbf0-83e8-11e5-80ae-74e785ed87d4.png)

**Comment by moxie0** [comment]
@dcherian stock android?

**Comment by dcherian** [comment]
Rooted with xposed but stock otherwise. Moto G 2013.

**Comment by moxie0** [comment]
It looks like getSize() is returning the value of getRealSize(), which I'm very willing to blame xposed for.

**Comment by dcherian** [comment]
Still have the problem with xposed disabled

On 6 November 2015 5:50:40 pm EST, Moxie Marlinspike <notifications@github.com> wrote:
>It looks like getSize() is returning the value of getRealSize(), which
>I'm very willing to blame xposed for.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/WhisperSystems/Signal-Android/issues/4405#issuecomment-154567747

-- 
Deepak Cherian

**Comment by dcherian** [comment]
Also, Issue does not occur when I have a keyboard open, regardless if whether xposed is enabled or not.

**Comment by skulumani** [comment]
I am also experiencing this issue on a Moto X 2013, Signal 3.3.2 , with stock Android 4.4.4 and no xposed stuff or anything else. Maybe this is an issue with Motorola phones or this version of Android?


This first image was generated by first selecting the attach button with the keyboard closed.
![screenshot_2015-11-12-14-26-15](https://cloud.githubusercontent.com/assets/5266022/11128807/2065ab78-894a-11e5-9c92-33f4b1470ecb.png)

This image is after opening the keyboard then clicking the attach button.
![screenshot_2015-11-12-14-26-25](https://cloud.githubusercontent.com/assets/5266022/11128808/2068a68e-894a-11e5-943d-04b3c0560f2f.png)

**Comment by johanw666** [comment]
This is not a Motorola only issue, it happens too on a Sony XPeria Z1 Compact, Android 4.4.4 with a 4.3" screen with a resolution of 1280x720. Signal 3.8.1 and 3.9.0.

**Comment by dcherian** [comment]
So, it's a 4.4.4 issue.

**Comment by johanw666** [comment]
Maybe. I just tested it on a tablet with Android 4.0.4, and that didn't have the issue.

**Comment by johanw666** [comment]
Odd, when I installed 3.17.0 on my Xperia Z1 compact with 4.4.4 the issue is gone. But I use a self built version an several libraries and the JDK have been upgraded since I built 3.16.0 so I have no idea what exactly solved it.

**Comment by FeuRenard** [comment]
There was this https://github.com/WhisperSystems/Signal-Android/commit/716ed251bca520c678052e3e0eed5089512a7f97 .
So maybe this issue can be closed?

**Comment by johanw666** [comment]
I must have overlooked that one. If there are no reports from other devices with this issue I think it can be closed but that decision is not mine.

**Comment by dcherian** [comment]
Closing since it is probably solved (I can't check because I'm on CM now) or because it affects 4.4.4 and android is now on  version 7.

**Comment by johanw666** [comment]
@dcherian it is solved on both my 4.4.4 devices since 3.17 so I guess it can be closed.
