### ISSUE TITLE
Notification about a new Signal user appears every few seconds

### ISSUE THREAD

**Issue by 0nse** [WhisperSystems/Signal-Android#4406]
- A friend is an iPhone user and installed Signal a longer time ago
- I am being told "[said friend] is on Signal, say hey!" every ~20s
- In his chat, I can only send "unsecured SMS". Signal messages or Signal calls are not available
- SMS transmission fails
- Force closing the app does not change anything. I will still receive a notification every few seconds.
- If I try to start a new conversation with him, it has the header "Take your conversation with [said friend] to the next level. Invite to Signal".
- Deleting the last active Signal chat with him did not have any effect. I am still getting a notification every few seconds.

![screenshot_20151106-002432](https://cloud.githubusercontent.com/assets/7449611/10984920/5d10f21c-841d-11e5-8e0a-de47e8dec070.png)

**My device:** Stock Nexus 5 Android 6.0, Signal 3.3.0, all permissions are allowed. The screenshot shows that I have a screen filter active (rootless CF.Lumen) and a custom set DPI. Both should not provoke this behaviour.

**App state:** Push registered, set as SMS application

[debug log](https://gist.github.com/8215e174709f3aa5bafe)

**Comment by moxie0** [comment]
Thanks for the report, sounds hella annoying. The two questions are, why is Android running the sync adapter every 20 seconds, and why does Signal think it's a unique match.

Can you email me at moxie.github@moxie.org? I have a signed APK with some more debug output for you to try if you're willing.
