### ISSUE TITLE
German Google Play page still says "TextSecure"

### ISSUE THREAD

**Issue by devurandom** [WhisperSystems/Signal-Android#4408]
On the German Google Play page it still says "TextSecure" instead of "Signal".

**Comment by Wikinaut** [comment]
I will fix this asap, just noticed it too. Thanks!

**Comment by RiseT** [comment]
@Wikinaut Where exactly is the translation for the Google Play Store located?

**Comment by Wikinaut** [comment]
@RiseT I am just looking for it @moxie0 I supplied the original translation to German for (then) TextSecure, but cannot remember how this was done (pls. can you post some infos here ?)

**Comment by Wikinaut** [comment]
@RiseT as far as I can see, apparently, not in https://www.transifex.com/moxie/textsecure-official/

**Comment by RiseT** [comment]
@Wikinaut I have a hint. Don't know if it is useful, though.

https://textsecure.piratenpad.de/PlaystoreBeschreibung

Wondering how this is pushed to the Play Store...

**Comment by Wikinaut** [comment]
@RiseT @devurandom Hi, I found the details ( https://github.com/WhisperSystems/Signal-Android/issues/1124#issuecomment-37335881 ) . 

Please make your changes in this pad https://textsecure.piratenpad.de/PlaystoreBeschreibung? and when you are ready, then inform Moxie that the text is ready . I remember that he then put the texts to Google Play, as there is not formal community-translateion tool for it (AFAIK).

**Comment by Wikinaut** [comment]
uh, crossed posting! good

**Comment by Wikinaut** [comment]
@RiseT yes, you are right, see, what i prepared when you posted. Go on and change the strings there. perhaps an additional text that TextSecure and RedPhone have been finally merged into Signal.

**Comment by RiseT** [comment]
@Wikinaut Sounds sort of inefficient. Wondering if this couldn't somehow get located at Transifex (separate from the app's translation).

**Comment by RiseT** [comment]
But will do...

**Comment by RiseT** [comment]
@Wikinaut Is there a place where I can find an updated version of the original (English) text?

**Comment by Wikinaut** [comment]
@RiseT The Google Play page with "en": https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms&hl=en

**Comment by RiseT** [comment]
@Wikinaut Ok - dumb question... :smile:

**Comment by Wikinaut** [comment]
@RiseT you wrote
> @Wikinaut Sounds sort of inefficient. Wondering if this couldn't somehow get located at Transifex (separate from the app's translation)

Yes, may be, but this was how I submitted the first German translation to Moxie, it was the then-approved way to do so. Pls. contact him, if you think the procedure should and could be improved. As far as i understand, it's not possible to automate, but ask Moxie, as he is the boss here.

**Comment by agrajaghh** [comment]
maybe it would be possible to add these (currently outdated) strings to the strings.xml so they could be translated with transifex?
https://github.com/WhisperSystems/Signal-Android/blob/master/res/values/google-playstore-strings.xml

**Comment by RiseT** [comment]
In case someone is wondering that nothing happens, I'm currently editing this in an external editor... :smile:

**Comment by RiseT** [comment]
I'm done. Feel free to check it out.

@moxie0 Updated German translation for the Play Store is ready:
https://textsecure.piratenpad.de/PlaystoreBeschreibung

Any chances to integrate the Play Store text into Transifex in the future?

**Comment by Wikinaut** [comment]
@agrajaghh https://github.com/WhisperSystems/Signal-Android/blob/master/res/values/google-playstore-strings.xml  look here https://github.com/WhisperSystems/Signal-Android/pull/1051 where this was discussed.

**Comment by moxie0** [comment]
ok thanks updated, will take a sec to propagate

**Comment by mawed** [comment]
shouldn't there be an information that it can be used as SMS-standard app with the possibility to store the SMS encrypted?

**Comment by Wikinaut** [comment]
@moxie0 @RiseT Google Play updated now https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms&hl=de .

Still to do: new screenshot(s). The first screenshot still shows "TextSecure"

@RiseT The text (Programmname) "Signal Vertraulicher Messenger", personally I don't like that. It's de facto a new name, and the writing in uppercase is not so nice. Shouldn't this be better: "Signal - ein sicherer Messenger" or simply "Signal" and then the explanation below that line ?

**Comment by agrajaghh** [comment]
I agree, "Signal Vertraulicher Messenger" sounds totally weird. Please put the "-" inbetween:
"Signal - Vertraulicher Messenger"

**Comment by Wikinaut** [comment]
@agrajaghh @moxie0 D'accord, I also suggest to add a long dash in the title between "Signal" and "Vertraulicher Messenger"

**Comment by RiseT** [comment]
That's what I did in the first place. Has it changed?

**Comment by RiseT** [comment]
Been outdoors for 45 minutes...

**Comment by RiseT** [comment]
It's "Signal – Vertraulicher Messenger", no?

**Comment by moxie0** [comment]
the max length is 30 chars

**Comment by RiseT** [comment]
In this case I would just use "Signal". Or "Signal – Sicherer Messenger". That would amount to 28 chars.

**Comment by Wikinaut** [comment]
+1

**Comment by moxie0** [comment]
Done. The short description is also untranslated: "Signal makes privacy simple. Send text, photos, and group messages for free!" Max length 80 chars.

**Comment by RiseT** [comment]
80 chars is sort of hard. German is just too lengthy... Compressing... :smile:

**Comment by Wikinaut** [comment]
@RiseT yes, let's do this on the pad, pleeeassse

**Comment by RiseT** [comment]
Btw - "calls" are missing in the original short description. Just saying (doesn't really help with a German translation that is already too long...)

**Comment by Wikinaut** [comment]
proposal:
"Signal macht vertrauliche Kommunikation einfach und sicher: Text, Fotos, Videos."

**Comment by Wikinaut** [comment]
@moxie0 
"Vertrauliche und sichere Kommunikation für Ihre Telefonate, Text, Audio, Video."

agreed by @RiseT & @Wikinaut. It includes the phone functionality "Telefonate" !

**Comment by RiseT** [comment]
Just as an alternative: "Signal - vertrauliche Kommunikation für Telefonate, Nachrichten, Multimedia." Don't know which one is better.

**Comment by Wikinaut** [comment]
Multimedia: ok for me, but not everyone knows, what this mean (my Oma/Grandmother, ok, a joke)

**Comment by RiseT** [comment]
My girlfriend though about newspapers when reading "Medien" elsewhere in TS...

**Comment by moxie0** [comment]
Neither of those seem to include the word "free," which is really the most important thing? Also I'm not exactly sure how these things translate, but if we were to write a brand guideline it would be to never use the word "secure" and instead favor the word "private."

**Comment by Wikinaut** [comment]
@moxie0 @RiseT take "Signal - vertrauliche Kommunikation für Telefonate, Nachrichten, Multimedia." I like it

**Comment by Wikinaut** [comment]
vertrauliche = private (avoid "secure") (=ok)

**Comment by RiseT** [comment]
"Privat" in German exists, but it has a somewhat different meaning. "Vertraulich" would be the most appropriate term.

**Comment by Wikinaut** [comment]
@RiseT : i meant w.r.t. Moxie's post.

@Moxie0 Do we need "Signal" in the subtilte" ?

**Comment by moxie0** [comment]
So can I change the title to "Signal – Vertraulich Messenger" then?

**Comment by mawed** [comment]
Signal - Vertraulicher Messenger

**Comment by RiseT** [comment]
I've had ""Signal – Vertraulicher Messenger" from the start, but it's too long (that's what you said).

**Comment by Wikinaut** [comment]
Kostenlose vertrauliche Kommunikation für Telefonate, Nachrichten, Medien.

**Comment by Wikinaut** [comment]
Then: (subtitle)
Kostenlose vertrauliche Kommunikation für Telefonate, Nachrichten, Medien.

**Comment by RiseT** [comment]
Kostenlose vertrauliche Kommunikation für Telefonate, Nachrichten, Multimedia.

**Comment by Wikinaut** [comment]
ah, bingo!

**Comment by RiseT** [comment]
Ok. Let's take that for the subtitle.

**Comment by moxie0** [comment]
ok done and done, thanks everyone!

**Comment by Wikinaut** [comment]
@moxie0 
Title = "Signal – Vertraulicher Messenger"
Subtitle = Kostenlose vertrauliche Kommunikation für Telefonate, Nachrichten, Multimedia.

**Comment by mawed** [comment]
"Signal - diskreter Messenger"?

**Comment by moxie0** [comment]
"Signal – Vertraulicher Messenger" is still too long, I forgot it was conjugated that way.

**Comment by Wikinaut** [comment]
@mawed : I think, that "diskret" is not suited.

**Comment by RiseT** [comment]
I think "Signal – Sicherer Messenger" is the best we can get within 30 chars.

**Comment by mawed** [comment]
@Wikinaut I searched for synonyms, this was the best suited inseat of "sicher"

**Comment by moxie0** [comment]
ok good by me, thanks everyone!

**Comment by RiseT** [comment]
You're welcome.

**Comment by Wikinaut** [comment]
I like most "Signal – Sicherer Messenger" as proposed above. Much better than this weird word "Vertraulich"

**Comment by RiseT** [comment]
@Wikinaut Have you noticed that the "NEU: [...]" has been removed?

**Comment by RiseT** [comment]
@Wikinaut I perceive "vertraulich" as the most appropriate translation for "private". But as it's too long, it doesn't matter.

**Comment by Wikinaut** [comment]
@RiseT 
> "NEU: [...]"
yes, pls. can you discuss this with Moxie0 ?

**Comment by RiseT** [comment]
@moxie0 Have you removed the (first) paragraph that explains that Signal is the combined app for the previous apps TextSecure and RedPhone on purpose?

"NEU: Die bisherigen Apps TextSecure (Messaging) und RedPhone (Telefonie) wurden zu einer einzigen App zusammengeführt: Signal"

**Comment by Wikinaut** [comment]
@moxie0 on https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms&hl=de , the (I call it) service links in the area

```
Bei Wünschen, Problemen und Fehlern:
http://support.whispersystems.org/
https://github.com/WhisperSystems/Signal-Android/issues

Weitere Informationen:
http://www.whispersystems.org/
```

have **several** unusual redirects.

Please can you check the urls (links) in your submitted "page source" and perhaps correct what needs to be corrected?

**Comment by 2-4601** [comment]
Gods below, this really needs a proper translation tool!
