### ISSUE TITLE
english playstore desciption still uses "TextSecure"

### ISSUE THREAD

**Issue by agrajaghh** [WhisperSystems/Signal-Android#4410]
> * Open Source. Signal is Free and Open Source, enabling anyone to verify its security by auditing the code. **TextSecure** is the only private messenger that uses open source peer-reviewed cryptographic protocols to keep your messages safe.

and

> Please file any bugs, issues, or feature requests at:
**https://github.com/whispersystems/textsecure/issues**

**Comment by moxie0** [comment]
thanks got it
