### ISSUE TITLE
Contact's phone number doesn't update when changing sim

### ISSUE THREAD

**Issue by funkydude** [WhisperSystems/Signal-Android#4412]
So a friend of mine recently changed their sim card and thus got a new phone number. In the normal Signal chat session pane it will show the person's name with their phone number below it. However, this number has stayed the same when I view my chat with this person.

I actually had no idea this person had changed their sim/number until a few weeks later, even though I was frequently messaging them via Signal. After they told me I then added their number to my contacts list (so now both the new and old numbers are listed under their name in my phone's contacts list).

However, the Signal chat pane still shows the old number. I should point out that this in no way affects functionality of the app, it's purely the aesthetical display of the phone number under their name.

If this is due to the fact I still have the old number saved, I cannot remove that as that friend still swaps between the 2 sims on rare occasions.

**Comment by moxie0** [comment]
Yep, your friend would have to reregister with the new number. There's a lot we should do around making the change number flow easier though, which I believe is represented in other open issues.
