### ISSUE TITLE
receiving a group message from changed identity appears in normal coversation

### ISSUE THREAD

**Issue by agrajaghh** [WhisperSystems/Signal-Android#4413]
Reproducible like that:
* A and B are having a normal Signal conversation
* A gets a new phone and registers for Signal again -> new key
* A is creating a new group with B
* A is writing a message in that group
* B is receiving 2 key exchange messages in the existing/normal conversation with A (group creation +  message)
* B is accepting the new key in one of them: the message appears in the existing conversation and the group is created without this message

**Comment by moxie0** [comment]
Unfortunately this is just the way it is for now.  We don't know it's a group message until we decrypt it, but we can't decrypt it because of the updated identity.  So the way it's supposed to work is that the message shows up in an individual thread, requires your approval, and then moves over to the group thread once we decrypt it.

We'll be making some changes in the future that should make this less painful in the common case.

**Comment by agrajaghh** [comment]
@moxie0 are you saying the message should move over to the group thread once decrypted? Because that is currently not the case, it stayed in the normal conversation.
Or should it just move over to the group after the future changes?

**Comment by moxie0** [comment]
Yeah once a group message is decrypted, it should move over to the group thread.

**Comment by agrajaghh** [comment]
okay, thats all I wanted to point out. Maybe a Toast or something similar could say that the message is in the group conversation?
Or just directly open the group conversation or conversation list (if several messages are affected).

**Comment by fumazu** [comment]
Same issue here.
* A is in a group conversation with B
* B generates a new key and writes a message in said group
* A receives key a exchange warning in normal conversation and after accepting that the decrypted message stays in the normal conversation

Bonus:
* A also uses the Signal-Desktop app where no key exchange warning was displayed and the message appeared in the group conversation instantly

**Comment by agrajaghh** [comment]
fixed with https://github.com/WhisperSystems/Signal-Android/commit/edbbb15a41f98a7e57f8eef68e569cf060e22289?

I will test it later (weekend)...

**Comment by agrajaghh** [comment]
yep, fixed in 3.8.0 :blush:
