### ISSUE TITLE
Support for permanent disabling of notifications for group/person

### ISSUE THREAD

**Issue by jutoft** [WhisperSystems/Signal-Android#4414]
Currently it is possible to disable notifications for a group for up to a week, but it would be nice if it could be done permanently.

Seems like earlier work on this was done in: #757

**Comment by 2-4601** [comment]
Duplicate of #3407 (but don't know if the position has changed)

**Comment by 2-4601** [comment]
Can be closed now (https://github.com/WhisperSystems/Signal-Android/commit/3cb2257ffdca81d2f2ac04994225014c20a08b08)
