### ISSUE TITLE
Quick capture regression

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/Signal-Android#4415]
Hi, every time I try to take a picture directly in the app, the app crashes. Hotfix please!

Crash log coming real soon now. Waiting for Firefox to sync the bookmark.

**Comment by mcginty** [comment]
Closing until Firefox syncs ;)

**Comment by Dyras** [comment]
@mcginty Here we go, just five hours late all thanks to Firefox.
https://gist.github.com/anonymous/78ed0be50ca0afd45cc5

**Comment by moxie0** [comment]
Hey @Dyras did you ever try using direct capture on 3.1 or 2.x? Did it work back then?

**Comment by Dyras** [comment]
@moxie0 Yes sir, it worked up until this morning when I installed 3.3.

**Comment by mcginty** [comment]
Thanks @Dyras! The refactor in 3.3.0 seems like it is choosing the wrong preview size for some subset of devices. I haven't gotten a device to crash to reproduce this yet, but I see some "poor choices" that lead to bad resolutions on other devices that I'm working out now.

**Comment by Dyras** [comment]
@mcginty Tell me if there is anything I can do to help you out. You should have my email from before.

**Comment by mcginty** [comment]
@Dyras for sure, will have a debug build for you if I don't work it out from the devices sitting on my table :P.

**Comment by Dyras** [comment]
@mcginty I saw your email, I don't build my own versions so feel free sending a signed version. Thanks.

**Comment by Dyras** [comment]
@mcginty Is the version you sent me 3.3.1 or just a debug 3.3.0? Because my phone just updated to 3.3.1 automatically tonight.

**Comment by Dyras** [comment]
With 3.3.1 it's no longer crashing when I try to take a picture, but front camera AKA selfie camera is 100% black.

https://gist.github.com/anonymous/152bfb9182f27d896f04

**Comment by mcginty** [comment]
To clarify: Back camera works, though? Also, before 3.3 did you ever use the front camera and did it work then?

**Comment by Dyras** [comment]
It has always worked, up until now. I've also noticed that the back camera, while it works, sometimes "freezes" when I open it.

**Comment by moxie0** [comment]
@Dyras When you get a chance can you confirm that the new beta (3.3.2) fixes this for you?  Thanks!

**Comment by Dyras** [comment]
@moxie0 Seems to be working just fine now, thanks! Completely unrelated, the server seems to be having problems.
