### ISSUE TITLE
microg GmsCore as free alternative for proprietary Gms

### ISSUE THREAD

**Issue by vuyibiran** [WhisperSystems/Signal-Android#4417]
Hello

As @moxie0 stated here: https://news.ycombinator.com/item?id=10498671 he would be pleased to see a 'API-compatible open source implementation of play services'
to make it possible to use signal with GMS without the need to install GAPPS.

Well, there is now good progress in this direction with the project microG GmsCore. This aims to be a 'framework to allow applications designed for Google Play Services to run on systems, where Play Services is not available'.

Would it be possible to accept this as an alternative? At the moment this project can be used to run Signal without GAPPS. The disadvantage is that microg GmsCore needs to fake app signatures at the moment to get Signal running. This is a huge security risk.

If Signal would accept microg GmsCore as an alternative to the proprietary implementation, there would be no need anymore to tamper with the android security system.

What do you Signal developers think about this and would you consider this as an alternative?

Kind regards.

PS: I am not affiliated with this project.

More can be found here: 
http://forum.xda-developers.com/android/apps-games/app-microg-gmscore-floss-play-services-t3217616
https://github.com/microg

**Comment by pejakm** [comment]
My Signal (official version) works just fine with GmsCore.

**Comment by vuyibiran** [comment]
Ok. Do you use omnirom or xposed or some special patch to enable fake app signatures?
If not, then Signal complains about the signature of the playstore not being valid.
And like I said enabling this is a security risk. Cyanogenmod for example has rejected that option for its rom.

So the option to hassle-free use microg GmsCore would have to be implemented into Signal ideally.

**Comment by pejakm** [comment]
Euphoria OS (unofficial build for LG p880) is patched.

> So the option to hassle-free use microg GmsCore would have to be implemented into Signal ideally.

I don't think Moxie will do this. :)

**Comment by moxie0** [comment]
Please post questions/discussion to the mailing list rather than the issue tracker.
