### ISSUE TITLE
Halloween easter egg: Muting notifications in group chat messes up avatars & names

### ISSUE THREAD

**Issue by TheNain38** [WhisperSystems/Signal-Android#4420]

**Comment by jeremymasters** [comment]
screenshot?

**Comment by 2-4601** [comment]
Steps to reproduce:
- open group chat
- tap top right ... menu
- tap _Mute notifications_
- tap _Mute for 1 hour_ (or any other, does't matter-9
- contact names have changed to group names, contact avatars have changed to group avatar

3.3.0, Nexus 4, stock 5.1.1

**Comment by agrajaghh** [comment]
haha this is a weird but...
I can reproduce it. It's fixed btw when you reopen the conversation...

**Comment by TheNain38** [comment]
Yeah, me too I find this very weird... When I found it, I was thinking myself, maybe someone else already reported that one, I looked and see no issue speaking of this bug...

**Comment by moxie0** [comment]
You found the Halloween easter egg! Actually I have no idea how this could be happening, but very reproducible.

**Comment by TheNain38** [comment]
Actually It seems every contact name is change by the group name, instead of their actual name, and it also get the Group chat icon

**Comment by jarteaga** [comment]
As far as I can tell, this bug was introduced in 7838e8fbe0ad992407529be81d48cf9f686dc61d. It makes `ConversationItem` add itself as a listener of group updates, but then implements `onModified` as:

```Java
  @Override
  public void onModified(Recipients recipient) {
    onModified(recipient.getPrimaryRecipient());
  }
```
Since the primary recipient for a `Recipients` group is a `Recipient` representing the group itself, this logic just updates the bubble and avatar from group data, which doesn't really make sense:

```Java
  @Override
  public void onModified(final Recipient recipient) {
    Util.runOnMain(new Runnable() {
      @Override
      public void run() {
        setBubbleState(messageRecord, recipient);
        setContactPhoto(recipient);
        setGroupMessageStatus(messageRecord, recipient);
      }
    });
  }
```

I think we could just delete that code instead of doing #4528, but I still don't fully understand the original intent.

**Comment by jarteaga** [comment]
(Fun fact: the color is actually generated from the group name, so you can turn this into an easter egg for your favorite holiday instead.)

**Comment by Hainish** [comment]
I just reproduced this in Signal 3.16.0, Android 6.0.1
![screenshot_20160801-175421](https://cloud.githubusercontent.com/assets/156137/17313671/87191cbe-5812-11e6-885f-eea39cb1ea96.png)

**Comment by Hainish** [comment]
Also reproducible upon unmute

**Comment by Hainish** [comment]
If I update the group, the bug is no longer reproducible.
