### ISSUE TITLE
Quick capture always uses front cam as default 

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#4421]
V 3.3
Sony Z1 compact 5.1.1

Whenever I enter a convo a try to quick capture I get scared a little bit of what I see. 
The happy me. 😊

So the front cam is the default for me. In-convo the change to back is stored though between closing and opening the quick capture. Until reentering. 
Stock and 3rd party cam behave well and default to back. 

Log after entering convo and opening quick capture (front mode of course)
https://gist.github.com/4a9f0c1fd53547db82ca

You dropped some  log outputs, did you?

**Comment by agrajaghh** [comment]
it looks like this is intentional: https://github.com/WhisperSystems/Signal-Android/commit/8fd0ea39aabed7494abd3929803f355cfad83003

I personally don't like it, but perhaps its good for the selfie generation :wink:

**Comment by McLoo** [comment]
Courses. Ok. Hm,  need  to visit some Barber then. Soon 💇

**Comment by McLoo** [comment]
Really? OK.

**Comment by mcginty** [comment]
apparently most people take photos of themselves, so this appeases the selfie gen

**Comment by McLoo** [comment]
Just got to get used to it...
(you sure you didn't mixed up your letters? Looks like you wanted to write "selfie disease gen app")

**Comment by 2-4601** [comment]
Could you _add a preference that's exposed to the user_ that would disable this behavior? Think of the people who are too ugly for selfies!
