### ISSUE TITLE
camera becomes unavailable with quick capture

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#4422]
yesss, twichty fingers is around again

- open convo
- open quick capture
- rapidly change between compose field and quick capture
- bang!

log after cam crash: ( https://gist.github.com/008f8f0b57c9236cff0a ) 

Wanted to reproduce the case where cam and keyboard are on screen the same time which I encountered a few minutes ago in 3.3 (sounds familiar...)
In case I got the mentioned behavior, which somehow is new ;) 

Edit: to few log outputs, it feels to me.
Edit 2: maybe it crashes cause of what the camera sees on the front cam :joy:

**Comment by mcginty** [comment]
I missed you, twitchy!

This is what happens when the camera code gets touched, eh.

**Comment by mcginty** [comment]
That log doesn't have any crashes in it, and I've been twitching pretty hard without crashes. Hmm.

**Comment by McLoo** [comment]
It's the camera that crashes. System wide. Even with soft twitching.

**Comment by McLoo** [comment]
Two changes between your friend SwiftKey and quick capture only were enough

**Comment by mcginty** [comment]
Can you try to get a log that has the crash in it? I'm doing exactly that and no crash.

**Comment by McLoo** [comment]
No crash in the log. But the changes between cam  and keyboard. And the: conditions not met. 
TS just closed the drawer and removes the cam icon. And a toast: camera not available. 
Sry
https://gist.github.com/3240317494f8e3905cde

**Comment by McLoo** [comment]
Fixed indeed.  For now 😁
Reproduced or analyzed it?

**Comment by mcginty** [comment]
Reproduced on an older phone :)
