### ISSUE TITLE
New attachment selector close arrow shows in wrong direction

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#4423]
In case the selector is overlaying the keyboard.
Arrows shows down.
Animation goes up in direction of the paperclip.
Just doesn't feel right - maybe it's the urge to nitpick...

**Comment by McLoo** [comment]
![screenshot_2015-11-06-21-32-08](https://cloud.githubusercontent.com/assets/5326916/11008040/40b7f92e-84ce-11e5-89c5-a8c4c161b43f.png)

**Comment by moxie0** [comment]
Yeah I thought about it, but I'm cool with it for now
