### ISSUE TITLE
attachment drawer not big enough when keyboard is open

### ISSUE THREAD

**Issue by agrajaghh** [WhisperSystems/Signal-Android#4425]
When the keyboard is open and you open the new (and really nice) attachment drawer, you can still see the keyboard peeking through. I think it would look much better if the attachment drawer had the size of the keyboard, or the keyboard gets closed before. 

I don't have this problem with the emoji drawer, the behaviour there is perfect!

Nexus 4, 5.1.1
![screenshot_21-53-29](https://cloud.githubusercontent.com/assets/5296073/11008528/67e08040-84d1-11e5-89f3-d92cce27028a.png)

HTC Desire, 2.3.7
![screenshot-20151106-215421](https://cloud.githubusercontent.com/assets/5296073/11008524/66ac8b92-84d1-11e5-942b-c4374673f9ce.png)

**Comment by moxie0** [comment]
I think I'm cool with that, wasn't really intending it to be a keyboard replacement
