### ISSUE TITLE
can't "sned textsecure message"

### ISSUE THREAD

**Issue by stonehat** [WhisperSystems/Signal-Android#4432]
I don't know why I can't send textsecure message . The tip in edit line is always "Send unsecured SMS".
How can I solve it?

**Comment by TheNain38** [comment]
You need to have contacts who also have Signal, and you need to sync the contacts, if you don't have automatic synchronisation, it is in your tel settings, then in Signal, you tap the right bottom button and here you drag down

**Comment by stonehat** [comment]
Thank you. It worked!
