### ISSUE TITLE
Switch display off during phone call

### ISSUE THREAD

**Issue by prinz-z** [WhisperSystems/Signal-Android#4434]
I noticed that the display remains on when I try to call someone, even if I put the phone close to my ear. With normal calls, the proximity sensor is used to switch the display off until I remove the phone from my ear.

**Comment by 2-4601** [comment]
It's supposed to switch off automatically using the proximity sensor.
Call someone, place your phone next to your ear, end call and go to **Settings -> Advanced -> Submit debug log** and paste the link here.

**Comment by pejakm** [comment]
It works properly here.

**Comment by prinz-z** [comment]
Okay, here it is: https://gist.github.com/317ff304c82d8ff92413

**Comment by jensMF** [comment]
Doesn't work for me as well.

**Comment by ljantzen** [comment]
I also have this issue

**Comment by swltr** [comment]
With me (Signal 3.5.2), the screen also remains on during calls.

**Comment by 2-4601** [comment]
Is this still an issue in 3.8.x?

**Comment by swltr** [comment]
I just checked with 3.8.1. The display was still on during a call. (Note that I was called, i.e. it wasn't me who called. I don't know if that makes a difference here.)

**Comment by prinz-z** [comment]
It works with the latest update on my device (version 3.9.0), thanks for fixing!

**Comment by swltr** [comment]
In the meantime, I checked this with 3.9.1. My display was still on during a call I received. (HTC Incredible S, Android 4.0.4)

**Comment by riyapenn** [comment]
Same issue for 
Device  : HTC One M7 
Android : 5.0.2
Signal 3.13.1
https://gist.github.com/8daca983ff2087e01ab0

Other ways to adjust setting: Settings > Display & gestures or Display, gestures & buttons > Screen timeout > adjust time before the screen turns off

**Comment by riyapenn** [comment]
Surfacing for one device on webrtc calls 
Device: HTC HTC Desire EYE
Android 6.0.1
Signal 4.6.1
https://gist.github.com/e3fc7c8f4e2eb06d6822cb583998cb1c where the proximity sensor triggers the call screen to turn off for non-Signal calls.
