### ISSUE TITLE
Wishlist: please let the quick camera remember the last used mode (front/rear)

### ISSUE THREAD

**Issue by legovini** [WhisperSystems/Signal-Android#4438]
I see that with 8fd0ea3 the quick picture mode uses the front facing camera by default. I personally don't like it, but if you think that for most people it's more "useful" like this, then fine.

I suggest to make Signal remember the last used camera (either per-conversation or application-wide). This would make most people happy and I think it fits within your development guidelines (don't add settings, ...).

**Comment by agrajaghh** [comment]
looks like a good trade-off to me, I could try to implement it if you guys are good with it?

**Comment by moxie0** [comment]
i agree

**Comment by McLoo** [comment]
@moxie0 you agree on
- per convo 
- or app wide?

**Comment by agrajaghh** [comment]
I did it now application wide, I think per-conversation might be confusing...

**Comment by mcginty** [comment]
Per-conversation would likely be more confusing than application-wide, agreed.
