### ISSUE TITLE
Feature Request: Support fingerprint reader as an alternative to PIN for encryption

### ISSUE THREAD

**Issue by maurizi** [WhisperSystems/Signal-Android#4439]

**Comment by moxie0** [comment]
thanks but we're not going to do this

**Comment by kurtisnelson** [comment]
I understand the security ramifications of using a fingerprint over a passphrase, BUT wouldn't it still be better than running with no passphrase? I'm thinking of less savvy users who don't understand encryption basics and the fact that their private key is just sitting on their phone.

At a minimum if fingerprint is not ever going to be added as a good sane default, I think the app should encourage a passphrase on first use.
