### ISSUE TITLE
Is this screen flow intended?

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/Signal-Android#4442]
Signal 3.3.0, other side the latest iOS version. Yesterday I received a Signal call. While calling (on speaker) I received a (little bit) delayed Signal message from the same person. I pulled down the notification drawer to see tghe message and got in the standard Signal messages screen. When I pushed the back button I more or less expected to re-enter the call screen but I got in the list of conversations. Is that intended? When I re-opened the conversation with the person who was calling (we could continue to talk during this) and pushed the call button I re-entered the Redphone call screen.

**Comment by moxie0** [comment]
It is intended. It's designed to be similar to how the normal in-call screen works, where once you switch tasks you need to select a persistent "in call" notification from the notification bar to re-enter the screen.
