### ISSUE TITLE
Group update always lists all group parameters (regression)

### ISSUE THREAD

**Issue by Norbert80** [WhisperSystems/Signal-Android#4444]
If I only add one person or confirm the group configuration without any changes all participants are listed as joined and the unchanged group name is listed as new group name.

Found in build 3.3.1. For me it looks like a regression that has possibly been introduced with the fix that replaces numbers with names for joined participants.

**Comment by 2-4601** [comment]
Hmm... I think this was just discussed recently in https://github.com/WhisperSystems/Signal-Android/issues/1347#issuecomment-156255806

**Comment by Norbert80** [comment]
If it is technically required to re-send all group parameters (including unchanged ones) each time updating a group a solution could be to fix it so that the clients only list things that really have changed by comparing old and new group parameters.

**Comment by riyapenn** [comment]
String Changes for parity with iOs (Desktop has details of who updated group):
1. if self-device updated group then "Updated the group" 
2. if someone else updated then "Group updated" or "Title is now '...' "

**Comment by moxie0** [comment]
thanks in 3.5.0
