### ISSUE TITLE
update documentation

### ISSUE THREAD

**Issue by heyimgay** [WhisperSystems/Signal-Android#4446]
I've noticed that many wiki pages need an update and/or are missing. For examle the 'redphone protocol' page is not reachable since the github repo was taken down. 

Another thing i noticed is the protocol is still called textsecure protocol v2. Since this is the only protocol signal has ever supported i suggest we just call it the signal protocol.

(this is kind of off topic but is why I was looking for the wiki page: how much is shared between the messaging and calling protocols? Is the calling protocol zrtp as claimed [here](http://www.wired.com/2014/07/free-encrypted-calling-finally-comes-to-the-iphone)? If this is true it means it does not have the self healing properties of the axolotl ratchet, right?)

**Comment by heyimgay** [comment]
I'll add this here because i don't want to open a new issue for it. [this Google play screenshot](https://lh3.googleusercontent.com/qy8c0VNYnrvWlEtti4AnNJgp08Ff0SUkn_ncBqy6w2dszEXFSmm2jKqNOH1o6W5W5xQ=h310) shows a phone icon without a padlock but with one next to it implying the other contact is using an old textsecure version.

**Comment by JasperWeiss** [comment]
I'd like to now whether signal uses local encryption by default or does it require you to set a passphrase for that under privacy settings. Or is it not locally encrypted either way?
