### ISSUE TITLE
Conversation list: Time & date, delivery status, lock symbol

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/Signal-Android#4450]
I suggest that the items within the conversation list - which at the moment just display time/date of the last message - are adjusted to exactly the same format used within the actual conversations/messages, i. e. time/date, delivery status (checkmarks) and lock symbol (if last message is encrypted).

This has a more coherent look and it's more convenient being able to check if last messages have been delivered (or *read* should you decide to implement an - *optional*, ideally even optional *per contact* - read status, which in my opinion wouldn't hurt) just from the conversation list.

On a sidenote, time & date of message records like "%s called you" or "Called %s" should be right-aligned like they are within the messages, and not centered like they are now. This has an incoherent look to it.

Sorry in advance if this is a duplicate - couldn't find a related issue.

**Comment by 2-4601** [comment]
Related #3012

**Comment by jeremymasters** [comment]
Also, the message that notes the incoming or outgoing call is probably a little bit too tall which only is an issue because it reduces the amount of conversation that is visible on the screen.  It also might be good to have a way to see only typed conversation, for instance, if I don't want to worry about when I made or received a signal call.

**Comment by 2-4601** [comment]
7c95adc7e61e8157a686caa19ac8b6c8cf593eae solved the main idea of this issue?

**Comment by RiseT** [comment]
@2-4601 That's right. Wondering about this as well. I've put too many small additional issues (some of them still unresolved).

Nevertheless - closing.
