### ISSUE TITLE
Contact selection not reseted after sending invitations

### ISSUE THREAD

**Issue by mangei** [WhisperSystems/Signal-Android#4452]
When I send invitations via SMS, the contact selection is not reseted if I want to sent invitations again. I would expect, that no contacts are selected, if I continue sending invitations.

```
Device  : LGE Nexus 4 (occam)
Android : 5.1.1 (2237560, LMY48T)
Memory  : 43M (0.03% used, 192M max)
Memclass: 192
OS Host : kpfj15.cbf.corp.google.com
App     : Signal 3.3.1
```

How to reproduce:

 - In Main Screen Menu
 - "Invite friends"
 - Click "Send SMS"
 - Select a contact
 - Click "Send to 1 friend(s)"
 - Confirm "Send 1 SMS invite(s)?" Dialog with "Yes"
 - Back at invitation screen with "Invitations sent!" Notification 
 - Click "Send SMS" again
 - Previous contact selection is still active
  - _Expected_: No contacts are selected

**Comment by mcginty** [comment]
Thanks for the report!

**Comment by moxie0** [comment]
in 3.4.0
