### ISSUE TITLE
Show who has Signal and who hasn't in the list of text messages

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/Signal-Android#4456]
Hello. I wish there was a way of telling who has Signal and who hasn't immediately by looking at the contact's name on the "front page" of Signal. It would only take a tiny lock next to their name. As it is right now, there is no way of teling if a user has Signal or not, unless you click their name. It's not a big deal, I know. But if the long term goal of Signal is to compete with WhatsApp I would say this feature is a necessity.

Sorry for a dizzy post, I've had the flu for quite some time now.

**Comment by Mihahn** [comment]
I guess #4431 adds a little icon next to Signal users in your contact list...

**Comment by Dyras** [comment]
Ah shit, late like always. Lame!
