### ISSUE TITLE
registering with the same phone number breaks original registration

### ISSUE THREAD

**Issue by jtracey** [WhisperSystems/Signal-Android#4457]
Since commit 5757962f95ae8e64330a75940a46b18e2becfcec was added, you can now install Signal on WiFi-only devices like tablets. However, if you do this, and register using the same phone number as your phone with a Signal install, your phone will no longer be able to receive or send Signal messages (and vice versa). The obvious solution is better multi-device support, which is already on the roadmap. But until then, there should be some warning that you can only have one device per number right now.

**Comment by jeremymasters** [comment]
I don't think it's advertised as advisable anywhere though either.  On the Signal chrome plugin it also says not to install yet.

**Comment by jtracey** [comment]
Not advertised as advisable, no, but I could easily imagine a new user attempting to install Signal on all their android devices, not realizing that it won't work, or someone getting a shiny new tablet and trying to install it.

**Comment by moxie0** [comment]
@jtracey Yeah this is the entire reason we don't let you type in the SMS verification code in the registration flow.  I'll put the telephony feature requirement back in, didn't realize that was the thing that has been blocking installs on tablets.
