### ISSUE TITLE
Some conversation colours are horrible to read

### ISSUE THREAD

**Issue by tehabe** [WhisperSystems/Signal-Android#4459]
One contact got yellow as colour and it not very good for reading their messages.

**Comment by moxie0** [comment]
We're cool with the colors, if you'd like to change your contact's color you can do it by tapping their name in the action bar at the top of the conversation.

**Comment by lvdstam** [comment]
I must agree with ghost. For me the contrast between the bubble and the text is to low to be able to read the messages comfortably. I would like an option to choose a white (or almost white) bubble with black text, with the possible addition of a black (or very dark grey) with white text option.

**Comment by Lokesh-Krishna** [comment]
Could it be possible to change the colour of the text depending upon the the color chosen? Text turns dark if the color is very light and vice versa?
