### ISSUE TITLE
Don't turn display on during calls

### ISSUE THREAD

**Issue by ComeGitSome** [WhisperSystems/Signal-Android#4464]
Signal 3.3.1

Call someone using headphones
Turn the display off with power button on phone
After a few seconds the display is switched on again. There's no way to keep the screen off during the call. Proximity sensor turning it off doesn't help when you're not holdint the phone to your ear and it shouldn't turn the display on unless pressing the power button again.

**Comment by moxie0** [comment]
Sounds like it's probably a device-specific issue, but at the end of the day the choice is going to come down to proximity sensor or this.

**Comment by ComeGitSome** [comment]
This is on Samsung Galaxy S4 by the way.

Why not do this when headphones are plugged in and use the proximity sensor otherwise?
