### ISSUE TITLE
Sudden switch to unencrypted conversation

### ISSUE THREAD

**Issue by merkste** [WhisperSystems/Signal-Android#4468]
White in the middle of an ongoing conversation encryption stopped working. The other one can send me encrypted messages but I have to fall back to SMS. He also not listed as Signal contact any longer. Log: https://gist.github.com/e34eb0695e27a303f2b0

**Comment by moxie0** [comment]
according to the server, this user is no longer registered. strange that they can send you encrypted messages, though.  Does the number you receive from match the number you're trying to send to, and are you sure what you're receiving is encrypted (little padlock)?

Has the person you're communicating with switched phones, or done anything else strange lately?

**Comment by merkste** [comment]
Yes, the messages I received were encrypted and mad TS attempt to send an encrypted message back until it failed again. He just de- and reregistered which solved the issue for now. The only unusual thing he did was moving some apps to the SD card. Maybe I can get a log.

**Comment by merkste** [comment]
Here we go:
https://gist.github.com/anonymous/e8910f265225cd2c30e3

**Comment by moxie0** [comment]
I would have to debug this server-side, but it sounds like the registration has already been reset.  If this ever happens again, please reopen and I'll take a quick look before the reregister.  Thanks!

**Comment by merkste** [comment]
I'll do. Thanks!

Am .11.2015, 22:13 Uhr, schrieb Moxie Marlinspike  
<notifications@github.com>:

**Comment by zouroboros** [comment]
Im having this problem in two conversations one disabled conversation a few days the other one today. In both cases I can still receive encrypted messages but are unable to send them messages. Signal just shows the gray sms message button. 

[Debug log](https://gist.github.com/anonymous/04a09207a731073d593a96b0e3c019ee)

**Comment by moxie0** [comment]
@zouroboros if you're comfortable, send me an email with the phone number of the contact you can't message: moxie+github@whispersystems.org

**Comment by zouroboros** [comment]
Sorry I can't send you the number.

**Comment by zouroboros** [comment]
With one of my contacts the problem seems to be resolved. But with the other one it persists. The person uses a pretty old version of android (I think Gingerbread).

**Comment by Sweater-Baron** [comment]
This also happened to me. @moxie0 , I will email you with the phone number.
