### ISSUE TITLE
Ability to disable "Invite to Signal" suggestion

### ISSUE THREAD

**Issue by mach-o** [WhisperSystems/Signal-Android#4471]
I'm happy with "Invite to Signal" pop-ups appearing by default, but it would be great if there were a setting you could use to disable this (or possibly also fine tune the situations in which they appear).

**Comment by moxie0** [comment]
thanks but we're not going to add another preference and there's another open issue for the fine tuning

**Comment by mach-o** [comment]
Thanks for the response. Can you link to the open issue you mention, so I can follow it? Thanks.

**Comment by heyimgay** [comment]
#4436 is the issue i believe

**Comment by SamHH** [comment]
I really think this deserves a preference - it's one of those annoying app behaviours that everyone hates and it's very frustrating that it keeps on popping up again after I've dismissed it. If there won't be a preference option then at least have it only pop up once - I don't need it popping up for every one of my contacts - if I want to share it then I will sans nag.
