### ISSUE TITLE
failed to send sms to short number

### ISSUE THREAD

**Issue by calin2k** [WhisperSystems/Signal-Android#4478]
signal 3.3.1 android 5.1.1 fails to send sms to short 4 digits number after aotomaticaly adding + country code to short number.
can't find where to deactivate automatic countrycode prefix in signal.

**Comment by hpmueller1971** [comment]
I can confirm this; it did *not* happen with previous versions (not sure when it started, but ~10 days ago, with the last beta it worked)...

**Comment by hpmueller1971** [comment]
After browsing through the source, i'd assume [this commit](https://github.com/WhisperSystems/Signal-Android/commit/b5b564cfe132ed28c008e6a320bf5d66290a7f58) caused the problem...?

**Comment by riyapenn** [comment]
Related: https://github.com/WhisperSystems/Signal-Android/issues/4453

**Comment by iosian** [comment]
Thanks for the fix but it (3.3.3) doesn't really solve the issue. While trying to send a SMS to a shortcode number like 6701, it still becomes  +16701.

**Comment by moxie0** [comment]
@iosian If you have an existing thread that got converted to +16701, you have to create a new one with just 6701.  Alternately, if you receive a new message from 6701 it will create a new thread for you.

**Comment by iosian** [comment]
@moxie0 I cleaned all of the threads in the Signal, deleted the contact associates to 6701, and rebooted the handset. It still adds +1 to 6701. Thanks.

**Comment by moxie0** [comment]
What country is your Signal number in, and how are you creating the thread?

**Comment by mcginty** [comment]
@iosian can you also put a debug log up when opening the conversation and trying to send?

**Comment by iosian** [comment]
@moxie0 It's in US. First hit the pen at the right bottom corner. Enter a number like 6701 (a fake number) using on screen keypad. Select "# New message to... 6701". On the left up corner it shows +16701. Send text through "Send unsecured SMS". Then check the SMS details using the "!". It shows "Via SMS To: #+16701".

@mcginty The log is at https://gist.github.com/anonymous/ba92b15118b4dfa8dd23

**Comment by McLoo** [comment]
Country code is added for me too. +49 in my case

**Comment by moxie0** [comment]
Hmm, ok according to libphonenumber 5 and 6 digit numbers are valid shortcodes in +1.  I know some carriers do shit with like 3 digit codes, though, so we should probably special case 4 digit or less numbers as shortcodes, except in countries where numbers can be 4 digits (I think that's less than 10 countries?).

**Comment by moxie0** [comment]
I think this is why 40404 works, but 6701 doesn't.

**Comment by iosian** [comment]
@moxie0 For 5 digit numbers, they are working correctly. For 6 digit numbers like 266278, on the top left corner it shows exactly 6 digits, 266278, but in the message details it shows "To: # +1266278" instead.

**Comment by moxie0** [comment]
@McLoo libphonenumber thinks that Germany only has 3 digit shortcodes (https://github.com/googlei18n/libphonenumber/blob/master/resources/ShortNumberMetadata.xml#L2623), but wikipedia says that they are 5 or 6 digits.  Do you have any sample shortcodes that could confirm one or the other?  I noticed Twitter doesn't even have a shortcode for germany.

**Comment by McLoo** [comment]
@moxie0 can't remember that I've ever seen a 3 digit shortcode. 
Checked two carrier's list (youth protection because of sms prices)  and there are 4, 5 and 6 digit shortcodes listed.

**Comment by McLoo** [comment]
Tried 5 digit two numbers. Country code, **was** added, but the SMS were properly sent and I got a deliver receipt on 3.4.0 :open_mouth:

**Comment by McLoo** [comment]
@moxie0 you have might expected it, but just for completeness: With 3.4.2 shortcodes work well for me (even the fancy 3 or less digit ones)

**Comment by moxie0** [comment]
thanks!

On 11/16/2015 10:17 PM, McLoo wrote:
> @moxie0 <https://github.com/moxie0> you have might expected it, but just
> for completeness: With 3.4.2 shortcodes work well for me (even the fancy
> 3 or less digit ones)
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-Android/issues/4478#issuecomment-157282080>.
> 

-- 
http://www.thoughtcrime.org

**Comment by edgarmtoro** [comment]
Same issue. Ottawa, Canada, SMS to 560560 for retrieving bus schedule. Signal appends +1 and message is undeliverable. Tried with Google messenger and it works.
Signal 3.6.1 on Nexus 6.0

**Comment by dominee** [comment]
Hello. Same problem in Slovakia, O2 operator uses 99222 for managing all services via SMS. Signal 3.9.1 is prepending +421 to the number. The message is undelivered.

**Comment by Nazta** [comment]
So I'm guessing this is still a problem, and no one ever added norway to that list?

Since after the last update, signal started refusing sending messages to a number with 5 digits

**Comment by macemmek** [comment]
A 5-digit code in Poland is being prefixed (+48)

**Comment by atenrok** [comment]
Totally still a problem. Nothing has changed since I first reported it.  

74121, 39858
in MA USA

Signal never sends a text. I always need to switch to default text app.

**Comment by anoteng** [comment]
Signal is still unable to send messages to Norwegian 5-digit numbers

**Comment by jonathancross** [comment]
Short codes were not working here in Switzerland for `414` (buying stamps).  Signal interpreted with country code as `+41 414` and returned "Failed to send".

I found that (astoundingly) -- turning off all internet in the phone suddenly worked and the SMS could then be sent.

There is a bug here somewhere.

**Comment by Iru** [comment]
> Totally still a problem. Nothing has changed since I first reported it. Can't understand why this is closed... :/
> 
> 74121, 39858 in MA USA
> 
> Signal never sends a text. I always need to switch to default text app.

Still broken today. Cannot reply to fraud mess as ges from Chase etc (72166)
