### ISSUE TITLE
No dialer integration since move from Redphone to Signal

### ISSUE THREAD

**Issue by jwittlincohen** [WhisperSystems/Signal-Android#4486]
Previous behavior (with Redphone):  If I initiated a call from the system dialer for a user that was registered with Redphone, I received a pop-up asking if I wanted to upgrade the call to a Redphone call.  In addition, calls showed up in the list of sent, received, and missed calls in the system dialer even if placed via Redphone.  

Current Behavior: With the introduction of Signal, there is no longer any dialer integration.  

Why the change matters: I think this was a nice feature as it means a user could simply initiate calls through the system dialer as opposed to opening Signal to initiate a call. This make it more likely that unsophisticated users, like my mother, would actually make secure calls since they don't have to do anything differently.

A Google search revealed another user brought up this issue, but attempting to access that page results in a 404.  I didn't see any existing issues in Github.

Tested with Signal 3.1.1 and 3.3.1 on Cyanogenmod 11 (Milestone 11), Android 4.4.4, on a One Plus One (A0001).

**Comment by moxie0** [comment]
Thanks but we've decided not to do this for now.

**Comment by wrapper** [comment]
@moxie0 would be keen to find out why this can't be offered as an option? I keep making clear calls to signal users by mistake

**Comment by lrq3000** [comment]
There's no dialer integration, but there's a contact card integration as I detailed in #4857. It's not as nice as what you propose, but maybe that would be too hard to maintain for all phones on the market (lots of phone brands customize the call app, sometimes very heavily, so that may be why Signal's devs don't want to try).
