### ISSUE TITLE
Response 401 Login failed on encrypted call

### ISSUE THREAD

**Issue by thrillfall** [WhisperSystems/Signal-Android#4489]
When i try to call another signal user over signal i get "Login Failed!" Error Message and the call aborts.
Text messages do work without a problem. I have already tried resolve this issue by unregistering my mobile number via the webinterface and reregistering inside signal. I still get the error.

[Debug log](https://gist.github.com/anonymous/fb00343e0098cef4de89). You'll find this Exception in line 881:
```
W/InitiatingCallManager(21045): org.thoughtcrime.redphone.signaling.LoginFailedException: Initiate threw 401
W/InitiatingCallManager(21045): 	at org.thoughtcrime.redphone.signaling.SignalingSocket.initiateConnection(SignalingSocket.java:185)
W/InitiatingCallManager(21045): 	at org.thoughtcrime.redphone.call.InitiatingCallManager.run(InitiatingCallManager.java:77)
```
When i try to call my number from another signal instance (from Google Playstore) then an error message is displayed saying that the called party (me) is not capable of encrypted calls.
But when i use the librephone app [(xmikos)](https://eutopia.cz/experimental/fdroid/repo) on my mobile to call the other way around it works very well.
Please note that i do use the websocket version from [xmikos](https://eutopia.cz/experimental/fdroid/repo). My understanding is that this build doesn't change the redphone part of signal so i come here for help.

**Comment by JasperWeiss** [comment]
I think this is exactly why moxie doesn't want forks. I suggest you submit problems to their github page.
That said I think there should be a self updating apk available for people not using Google's play store. But a few issues prevent this from happening and the people who want this have shown little effort to adress these.

**Comment by thrillfall** [comment]
Ok, my mistake. Thanks for your reply.
