### ISSUE TITLE
Message delivery failed

### ISSUE THREAD

**Issue by samson212** [WhisperSystems/Signal-Android#4493]
When sending a Signal message to a friend, I get this error notification. In the app, there's a red exclamation mark next to the message, it says 'Not delivered' and 'Tap for details'. When I tap, I get 'Some issues need your attention' and 'Failed to send' with the option to 'RESEND'. Resending just reproduces the same problem again. Here's the debug log: https://gist.github.com/anonymous/5053bfb633d8b87091d7

I suspect this is related to a couple of other issues listed in the last three days (specifically [this one](https://github.com/WhisperSystems/Signal-Android/issues/4476) and [this one](https://github.com/WhisperSystems/Signal-Android/issues/4460)), but since it's not _exactly_ the same (i.e. it works when I send to non-Signal users) I opened a new one.

--sam

**Comment by peterpanondrugs** [comment]
Same here: after update from 3.3.1 to 3.3.2. the messages stuck while sending or didnt send. 
And when the "server mark" was shown, i didnt get the "receive mark"
https://gist.github.com/7de29a87b66c73da39a8

**Comment by kennyballou** [comment]
I am also having this issue on 3.1.1.

I've tried deleting the data and reinstalling the application to no avail.

**Comment by kanytu** [comment]
Having the same issue on 3.3.2 on a group chat. 

log:
https://gist.github.com/kanytu/55b3044999fbc4e8799e

**Comment by generalmanager** [comment]
@kanytu You seem to experience the same or a similar bug as I do:
https://github.com/WhisperSystems/Signal-Android/issues/4550

**Comment by athensy** [comment]
Similar problem, but it is only happen when I send message from a group, but have no problem for individual message. i.e. peer-to-peer messaging. Although the red exclamation mark is shown and the message is marked "Not delivered", it actually be sent out (at least part of group members received my message).

**Comment by generalmanager** [comment]
@athensy Maybe I should have clarified, that is the same behaviour I and my friends encountered in https://github.com/WhisperSystems/Signal-Android/issues/4550.

**Comment by athensy** [comment]
Yes, @generalmanger, it is the same you reported previously. Could you tell me how to register Signal? I just can't find a glue.

**Comment by generalmanager** [comment]
Uhm usually it tells you to register after you installed the app. Have you tried uninstalling, reinstalling and registering on the first time you opened the app?

**Comment by athensy** [comment]
One of group member has reinstalled. She didn't quit group before she reinstalled, but she joins the group again afterward. Do you think it is the source of problem?

**Comment by generalmanager** [comment]
Maybe. She could just try to remove herself and someone else can readd her to check that possibility. I think the problem only occurs when someone unregisters via the web tool or the first option in the advanced settings. But please ask those group-related problems over in https://github.com/WhisperSystems/Signal-Android/issues/4550 tough, so we don't unecceccarily spam this issue.

**Comment by athensy** [comment]
You are right, we should stop here, and thanks for you opinion.

**Comment by 2-4601** [comment]
When @samson212 posted this issue there were some server problems and message deliveries failed for (nearly?) everybody. The following comments are either related to that or if posted days later about something completely different.

I think this issue can be closed.

**Comment by samson212** [comment]
Yes, sorry I didn't come back and mention it, but this issue is totally resolved on my side.

**Comment by wdavidhj** [comment]
I’m seeing this problem when sending to any individual recipient in my Signal contacts (I don’t use Signal groups).

**Comment by Trolldemorted** [comment]
@wdavidhj could you upload a debug log?

**Comment by Accusedbold** [comment]
I can't send a message to ANYONE with signal, here's my debug log:
https://gist.github.com/anonymous/024ddc11b0b88782d3ae67b21c802b5b

**Comment by kennyballou** [comment]
I'm going to go out on a limb here and suggest this is an entirely different issue. I've been noticing this behaviour for the last hour or two, but haven't yet been given the chance to research (much) of the issue. Is there a new issue for this yet? Or...

**Comment by wdavidhj** [comment]
> @wdavidhj could you upload a debug log?

How do I send a debug log from Signal?

**Comment by PiCob** [comment]
See here: https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports#android_debug
You can paste the link here, if you want to.

However, if you are still facing these problems, I'm sure there will be a more active/recent [open issue](https://github.com/signalapp/Signal-Android/issues?q=is%3Aissue+is%3Aopen) covering this.
