### ISSUE TITLE
Wishlist: Video calls

### ISSUE THREAD

**Issue by sicofante** [WhisperSystems/Signal-Android#4497]
It would be nice if we could make video calls, not just voice calls. Can we expect this to happen in the future?

Thanks!

**Comment by xzipyx** [comment]
Yes I agree that would be a really nice feature but also transfers of any file type. Keep up the good work! My favourite Messenger!

**Comment by zero77** [comment]
Yes I also agree video calling would be a great feature to have most apps have it.

**Comment by agrajaghh** [comment]
@zero77 Please don't bump issues (they just create extra email notifications for the devs). Thanks

https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues

**Comment by malkhamis** [comment]
I am desperately waiting for this feature!

**Comment by riyapenn** [comment]
@malkhamis Please refrain from adding comments similar to "+1" "me too" "I am desperately waiting for this feature!" without adding any NEW or ACTIONABLE information as this only creates noise for everyone.  If you _really_ want, there is an emoji icon in the comment header that allows you to "Add your reaction".

**Comment by nrizzio** [comment]
The most recent version of Signal in the Play Store is 3.29.6, which includes video calls. This issue can be closed :fireworks:!
