### ISSUE TITLE
Is ProtocolV2 Going to Stick?

### ISSUE THREAD

**Issue by paragonie-scott** [WhisperSystems/Signal-Android#4500]
I'm currently looking to write a Signal-compatible library that lets people send 2FA codes if supported, and fallback to SMS if not.

Before I dive too deep, is [ProtocolV2](https://github.com/WhisperSystems/Signal-Android/wiki/ProtocolV2) going to be changed drastically any time soon? Or can I rely on that as a solid reference material with a reasonable level of confidence that there won't be a ProtocolV3 in the next month or so?

(In case anyone is wondering, I will be using libsodium for Curve25519, etc. I will not be writing my own primitives!)

**Comment by moxie0** [comment]
Hey @paragonie-scott we use this as an issue tracker, not a discussion forum.  You can post questions to the mailing list or contact support at support@whispersystems.org.  Thanks! 

(But the short answer is no)
