### ISSUE TITLE
Can't get connected secure calls

### ISSUE THREAD

**Issue by milanjungic** [WhisperSystems/Signal-Android#4515]
Hello. With friends we installed Signal (2 Android users and 1 iPhone) and can't get connected secure calls between us. We verified our keys using barcode scanner and also sending SMS works. When I call a friend (he has same version of Signal, as we all installed it at same time), he gets the call ringing, but when he answers, on my (caller) side Signal still states "Calling" for a while and then drops the call. When he calls me, the situation is same, I get the call but when I answer it just states "establishing connection" or similar and then after a while it drops the connection. We have the same issue when we try to make calls on local Wifi or 3G/4G networks.

I use Android 5.1.1. (non-roted, original ROM), Samsung S6 Edge
Friend uses Android 5.0.2. (non-roted, original ROM), Samsung Note 3
Friend uses iPhone 5.

Here is the full debug log from my phone: https://gist.github.com/anonymous/3b39245965aeafc299de

**Comment by moxie0** [comment]
From the log it looks like you have no network connectivity to the relay. My guess is that whatever network you're on is blocking udp.
