### ISSUE TITLE
Member joined group message should use Plurals

### ISSUE THREAD

**Issue by cascheberg** [WhisperSystems/Signal-Android#4521]
The string [GroupUtil_joined_the_group](https://github.com/WhisperSystems/Signal-Android/blob/master/src/org/thoughtcrime/securesms/util/GroupUtil.java#L77) "%1$s joined the group" cannot be translated properly. It can mean that one or more people joined the group. But for example in German you must specify "has joined" for singular, or "have joined" for plural. So it should use Android Plurals.

**Comment by RiseT** [comment]
As far as I know, the placeholder in this string represents a contact name rather than a number, no?

**Comment by cascheberg** [comment]
Yes, but it can be more than one contact name. So the problem is that in German you need to be able to differentiate:
* "UserA **has** joined the group."
* "UserA, UserB **have** joined the group."

**Comment by RiseT** [comment]
Ah - ok. Wasn't aware the multiple contacts can join at the same time.

**Comment by McLoo** [comment]
Could swear I did the translation or original string change for that one. 
Worked around the pluralistic  singularity  with that:
"Joined the group: %1$s"

**Comment by RiseT** [comment]
@McLoo Just checked - the string's history consists of just one translation (which doesn't take plurals into account). Modified it accordingly to your suggestion.

**Comment by cascheberg** [comment]
@RiseT @McLoo Yes that works for German, but I am not sure about other languages.

(I signed up for Transifex. It seems that during the signup process I automatically requested to add the new language "German" to the project. I did not realize it would do that, oops, sorry!)
