### ISSUE TITLE
text box focus after contact selection

### ISSUE THREAD

**Issue by dcherian** [WhisperSystems/Signal-Android#4527]
This is a terrible title but here are the steps:

1. Click FAB to get contact selection screen.
2. Use keyboard to type letters and narrow down selection.
3. Choose a contact
4. Conversation window opens with keyboard open.
5. Text box doesn't have focus. So, you can type on the keyboard without the letters actually going anywhere.

Not sure if this is Signal's fault, or just Android.
Signal 3.4.0, Moto G. Android 4.4.4

EDIT: *last* word typed appears after tapping on the "text input" box. This is after following above steps.

**Comment by mcginty** [comment]
Oh yeah, great point. Thanks for the good repro steps!

**Comment by dcherian** [comment]
Same issue if tapping on a notification when Signal is locked.
