### ISSUE TITLE
My contact can hear me, but I can't hear him.

### ISSUE THREAD

**Issue by kyanha** [WhisperSystems/Signal-Android#4532]
Making calls through Signal... I'm having trouble with talking with a contact.  He can hear me, whether I call him or he calls me... but I can't hear him.

We're both on wifi, not mobile data.  I don't know precisely which ports need to be unblocked there, but I do have other contacts I can speak with and we can all hear each other (though with those other contacts, I tend not to be able to receive their call signalling, where I can receive call signalling from this one.).

I'm on a Samsung Galaxy Prevail LTE via Boost Mobile.  He's on a Samsung Galaxy S4 via T-Mobile.  We both rebooted our phones, and the situation remained the same.

**Comment by kyanha** [comment]
Also: my device (Galaxy Prevail LTE) is running Android 4.4.4.  My contact's device is running Android 5.0.1.  Both of us have the latest Signal from the App Store.

**Comment by mammuth** [comment]
You might provide a debug log when you experience this another time. 
It can be fetched by going to the app settings > advanced > submit debug log

**Comment by Dyras** [comment]
I have this exact same problem, but only sometimes. I thought it was my mic! Will totes post a log if it happens again.

**Comment by pejakm** [comment]
Exact same problem here: a friend can hear me, but I don't hear him. Just this one particular contact. Both of us using v3.4.1. Here's a log from his phone:
https://gist.github.com/anonymous/ea1ff3f89a91fee69d7d

**Comment by AnteBucan** [comment]
When you can't hear someone, press the speakerphone icon and then you can hear them. Then turn off the speakerphone, and now you can talk normally. I don't know why that works, but it works.

**Comment by pejakm** [comment]
@AnteBucan I did try that, but it didn't help, I still couldn't hear my friend.

**Comment by eternaltyro** [comment]
My problem is the reverse. I can hear my friend. But my friend can't hear me. It's as if I'd muted. My debug log has a line that says this:

W/RecipientPreferenceDatabase(12676): Muted until: 0

Not sure if that's relevant though. For those claiming you can't hear your friends' voices, kindly ask them if things work normally with their other contacts. If not, I suspect the problem could be with their phones/signal.

my debug log:: https://gist.github.com/7483d9cb32b4dfae2330

**Comment by pejakm** [comment]
@eternaltyro You are using version 3.3.2. Could you please update to 3.4.2 (you need to be beta tester or you can get original-signed version from [apkmirror](http://www.apkmirror.com/apk/open-whisper-systems/signal-private-messenger/signal-private-messenger-3-4-2-android-apk-download/)) and then post some logs?

**Comment by eternaltyro** [comment]
Here we go: https://gist.github.com/anonymous/ba96475a5a02275f37f2

**Comment by eternaltyro** [comment]
Also recent upgrade from 3.3.3 to 3.4.2 introduces issue #4548 on Motorola Moto E 2nd Generation.

**Comment by eternaltyro** [comment]
Another attempt: https://gist.github.com/anonymous/17a929569719bfcd7e47

**Comment by pejakm** [comment]
This line looks suspicious to me:
`AUDIO_INPUT_FLAG_FAST denied by client`

**Comment by eternaltyro** [comment]
W/AudioRecord(21684): AUDIO_INPUT_FLAG_FAST denied by client
    W/CallAudioManager(21684): Starting AudioPlayer...
    W/libOpenSLES(21684): class OutputMix interface 0 requested but unavailable MPH=43
    W/AudioTrack(21684): AUDIO_OUTPUT_FLAG_FAST denied by client

I  can't make sense of the log. Does this mean there's an audio recording software trying to capture the mic? Is there a clash between my audio player and signal?

**Comment by eternaltyro** [comment]
Issue persists in 3.5.2

**Comment by eternaltyro** [comment]
I don't know if this line could be a problem

    W/ResourcesManager( 6736): Asset path '/system/framework/com.google.android.media.effects.jar' does not exist or contains no resources.

I don't see it in the other phone .

**Comment by eternaltyro** [comment]
Issue persisted in 3.7.2 and persists in 3.8.1. Logs for 3.8.1 : https://gist.github.com/anonymous/e31c228270dd22f8f5b6

**Comment by tokariu** [comment]
I still have this issue on LG G3 with Cyanogenmod 12.1.
I call my friend with signal (latest version as of date) and he doesn't hear me until i klick on the speaker icon for free speech. normal mic is not working.
signal phone calls only working with free speech are kinda useless in public...

this problem definitely needs some more love.

**Comment by velteyn** [comment]
https://gist.github.com/anonymous/19591fba7787b67dc9c2cb9777454752

**Comment by e8quarl** [comment]
I have the opposite problem, i.e. my contact can't hear me, but I can hear him. I have tried this with two different contacts. Here's my log from one of my attempts:

https://gist.github.com/anonymous/cc536cebf2227df2feefbe06cd9c82a3

I believe this issue might be related to the following:

- [I hear no audio during video calls with a contract #6271](https://github.com/WhisperSystems/Signal-Android/issues/6271) and possibly also
- [One phone is silent in WebRTC call #6140](https://github.com/WhisperSystems/Signal-Android/issues/6140)

**Comment by e8quarl** [comment]
An update: The audio problem was kind of solved by enabling the new beta audio/video alternative on all the phones involved. However, moving back to the old method (i.e. disabling the beta alternative) breaks it again.

**Comment by 2-4601** [comment]
Closing as mainly RedPhone related issue. For WebRTC see the issues mentioned above.
