### ISSUE TITLE
testRelease, testDebug, testDev tasks have 2 failed tests each

### ISSUE THREAD

**Issue by kyanha** [WhisperSystems/Signal-Android#4534]
org.thoughtcrime.securesms.jobs.AttachmentDownloadJobTest > testCreateAttachmentPointerInvalidId
 FAILED
    java.lang.Exception: Unexpected exception, expected<org.thoughtcrime.securesms.jobs.AttachmentDownloadJob$InvalidPartException> but was<java.lang.RuntimeException>

        Caused by:
        java.lang.RuntimeException: Method isEmpty in android.text.TextUtils not mocked. See https://sites.google.com/a/android.com/tools/tech-docs/unit-testing-support for details.
            at android.text.TextUtils.isEmpty(TextUtils.java)
            at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.createAttachmentPointer(AttachmentDownloadJob.java:134)
            at org.thoughtcrime.securesms.jobs.AttachmentDownloadJobTest.testCreateAttachmentPointerInvalidId(AttachmentDownloadJobTest.java:31)

org.thoughtcrime.securesms.jobs.AttachmentDownloadJobTest > testCreateAttachmentPointerInvalidKey FAILED
    java.lang.Exception: Unexpected exception, expected<org.thoughtcrime.securesms.jobs.AttachmentDownloadJob$InvalidPartException> but was<java.lang.RuntimeException>

        Caused by:
        java.lang.RuntimeException: Method isEmpty in android.text.TextUtils not mocked. See https://sites.google.com/a/android.com/tools/tech-docs/unit-testing-support for details.
            at android.text.TextUtils.isEmpty(TextUtils.java)
            at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.createAttachmentPointer(AttachmentDownloadJob.java:134)
            at org.thoughtcrime.securesms.jobs.AttachmentDownloadJobTest.testCreateAttachmentPointerInvalidKey(AttachmentDownloadJobTest.java:40)
Gradle Test Executor 1 finished executing tests.

16 tests completed, 2 failed

---

I am using JDK 1.8.0 with the Android Studio bundle 141.2343393.  I have gone to the page referenced in the errors and added the snippet to build.gradle in the android {} section, but I get the same error with NullPointerException instead of RuntimeException.

This occurs on the v3.4.0 tag.

From what I can tell, TextUtils.isEmpty has never been mocked, and these tests should have never been able to succeed.  Are the tests being run on build, before release?

**Comment by mammuth** [comment]
Hi kyanha, the developers prefer to keep this issue tracker for bug reports for the app.

Discussions or questions like yours should probably go to the mailing list (https://lists.riseup.net/www/info/whispersystems), where you will get better answers.

**Comment by mcginty** [comment]
yeah I think this test broke.

**Comment by kyanha** [comment]
Ummm... @mcginty, I know you committed #4559 to fix these, but I'm still getting the same test failures.  I don't understand the test harness to be able to address them myself, I'm sorry.

**Comment by mcginty** [comment]
works for me, make sure you're on HEAD of master?

**Comment by kyanha** [comment]
I was on HEAD of master, and they failed.  I switched to branch 3.5.0 and I couldn't get it to compile (due to bad checksum on the build.gradle update to textsecure-android:1.8.3, see #4605).  After applying ba4ebed (@moxie0's fix for #4605), I was able to get it to compile; now, there are no failures on that branch.

Am testing on HEAD of master to be certain that it's fixed there as well.

**Comment by kyanha** [comment]
testDebug verified no test failures on HEAD of master.
testRelease verified no test failures on HEAD of master.
testDev verified no test failures on HEAD of master.
