### ISSUE TITLE
Donate button image not loading

### ISSUE THREAD

**Issue by bbodenmiller** [WhisperSystems/Signal-Android#4542]
In README.md appears donate button is broken.

**Comment by heyimgay** [comment]
Apparently the tipping system has been shut down and they suggest moving over to https://www.changetip.com/

**Comment by bbodenmiller** [comment]
The link, https://www.coinbase.com/checkouts/51dac699e660a4d773216b5ad94d6a0b appears to load fine so I think whoever set the coinbase account just needs to go to https://developers.coinbase.com/docs/wallet/tutorials/donations and follow the details to create the button.

**Comment by odeke-em** [comment]
@bbodenmiller potential PR https://github.com/WhisperSystems/Signal-Android/pull/4575
