### ISSUE TITLE
Signal messages delayed and unable to initiate secure calls until recipient restarts Signal app

### ISSUE THREAD

**Issue by jwittlincohen** [WhisperSystems/Signal-Android#4545]
Over the last several days, I've noticed that messages are occasionally not being delivered (one checkmark) and I am unable to initiate a secure call to said contact.  I confirmed that the user's phone was on at the time, he had a data connection (Wifi), and in fact the Signal app was opened in the background.  The user was able to receive emails and regular phone calls without issue.  Restarting the Signal app fixed the problem.  In addition, after restarting the app, he recevied all my previous messages.  This user was running Android 4.4.4 on a One Plus One with Signal 3.1.1.

I had a similar issue with a Signal iOS user (Signal 2.2, iOS 8.4.1, iPhone 5S).  Messages to that user went through nearly instantly but I was unable to initiate a secure call.  However, the user could  call me via Signal, and my phone rang nearly instantly.  When the user closed the Signal app, I was able to initiate a call, and it rang on her phone within a second.

I understand that Google Cloud Messaging is believed it be causing delayed message delivery intermittently.  However, the behavior I'm seeing appears to impact both iOS and Android clients, the messages are not merely delayed but do not arrive at all until the app is restarted, and when the recipient restarts his/her Signal applicaiton, new messages sent to that user are delivered within seconds.  As noted above, calls are also impacted.  I can't see why restarting Signal would suddenly make GCM more reliable, so it seems there may be a bug in Signal causing the delays and inability to initiate secure calls.  Would logs useful? If so, do you want them for me (sender) or the recipient that isn't receiving the messages?

**Comment by heyimgay** [comment]
Lets start with logs on your end to determine if the messages are sent correctly

**Comment by jwittlincohen** [comment]
I saw this behavior on Signal 3.11, 3.3.2, 3.3.3, and 3.4.0.  Just installed 3.4.1 this morning but I haven't seen this behavior yet.

**Comment by moxie0** [comment]
@jwittlincohen I think you'll have better luck contacting support@whispersystems.org. We can walk you through the scenarios where this is likely to occur.
