### ISSUE TITLE
New contact selection & dark theme: Gray Signal icon has white keyhole

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/Signal-Android#4546]
The gray Signal icon (the one in line with the alphabet letters) has a white keyhole when using the dark theme. I guess - like with the light theme - this should have the color of the background, i. e. black.

Two more observations on this:

- The gray tone of the Signal icon & letters seems a bit dark to me, i. e. the contrast to the black background is pretty low and thus a bit hard to read
- A Signal-blue Signal icon would look nicer and more obvious than a gray one (while leaving the alphabetical letters gray)

Signal v3.4.1

**Comment by RiseT** [comment]
@mcginty I guess this can be closed now because of https://github.com/WhisperSystems/Signal-Android/pull/4619, right (don't know if you still want to lighten the gray tone slightly)?

Btw - I really like the latest changes you've done with that PR.

**Comment by mcginty** [comment]
Yeah, the gray tone should probably be lightened just a hair more.

Glad you like it!
