### ISSUE TITLE
[Feature Request] Default message options

### ISSUE THREAD

**Issue by peanuttery** [WhisperSystems/Signal-Android#4547]
Would it be possible to implement a default messaging option (e.g. SMS by default) per conversation open?

Currently, I have to constantly change the Encrypted text option to SMS everytime I want to send an SMS instead. I would like there to be an option available to change the default type of message sent.

**Comment by moxie0** [comment]
thanks but we're not going to do this

**Comment by 2-4601** [comment]
For future reference marking as duplicate of #2329 (took some time to find that).

**Comment by peanuttery** [comment]
Could you provide a reason as to why this won't be done?
