### ISSUE TITLE
After a call the audio of the recipient's phone is stuck to earpiece speaker

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/Signal-Android#4548]
Steps to reproduce:
* Jerry calls George with Signal
* George answers
* They end the call
* Now the audio of George's phone is stuck to the handset earpiece speaker
 * everything (music, videos, notifications) play through the earpiece
 * every time George tries to adjust the volume of his phone he sees a bluetooth volume control overlay instead of the normal volume control overlay

This does not seem to happen to Jerry's phone (i.e. the initiator of the call).

To fix this George can call someone with Signal or system dialer and end the call immediately. Now audio will play through the loud speaker again and normal volume controls become available.

This has been an issue for me since Signal 3.3.x (currently using 3.4.1)

Affects both of my devices:
 * Nexus 4, stock 5.1.1
 * Huawei U8800, 4.0.4

**Comment by 2-4601** [comment]
@agrajaghh: Could you help me to test this by trying to reproduce this with your Nexus 4?

Initial state of Nexus 4: stock 5.1.1, Signal 3.4.1, All sounds mode (i.e. the normal state :bell:) and all volumes are non-zero.

Test:
* use another device to make a Signal call to your Nexus 4
* answer the call with your Nexus 4
* end the call from your another device

After the call has ended:
* try to adjust the volume of your Nexus 4 using the physical volume slider at the side of the phone
 * do you see a bluetooth volume control or the regular Lollipop volume controls?
* try to play some audio (e.g. YouTube video)
 * does the sound come from the speaker behind the phone or from the earpiece speaker at the top front?

**Comment by agrajaghh** [comment]
Sure! I'm running master with latest commit: https://github.com/WhisperSystems/Signal-Android/commit/69f5aacd2514ba3ea90d1b3cfba3908e229bc40b Is this 3.4.1?

>try to adjust the volume of your Nexus 4 by using the physical volume slider at the side of the phone> 
> * do you see a bluetooth volume control or the regular Lollipop volume controls?

bluethooth volume control

> try to play some audio (e.g. YouTube video)
> 
> * does the sound come from the speaker behind the phone or from the earpiece speaker at the top front?

earpiece speaker :flushed: 

> To fix this George can call someone with Signal or system dialer and end the call immediately. Now audio will play through the loud speaker again and normal volume controls become available.

confirmed

wow thats fucked up.... :laughing:

**Comment by haffenloher** [comment]
Funny, can reproduce on Android 4.2, but only after I re-read @2-4601's post and changed my phone's profile from vibration to normal mode.

**Comment by 2-4601** [comment]
@agrajaghh, @haffenloher thanks!

I have this with my other device too but I don't trust it's audio hardware enough to base bug reports on it any more and wanted to confirm with at least one proper device (Nexus 4).

**Comment by haffenloher** [comment]
@2-4601 could you test #4567 and see if it works for you?

**Comment by 2-4601** [comment]
Tested on my Huawei device. Yes, it fixes the issue for me. :+1:

**Comment by eternaltyro** [comment]
Recent update from 3.3.3 to 3.4.2 introduced this issue for me in Motorola Moto E  2nd Gen. Logs: https://gist.github.com/anonymous/ba96475a5a02275f37f2

**Comment by motatuc** [comment]
I have to add that the problem still exists for me with cm12.1 from 20.11.2015 and signal from today. I still have the bluetooth symbol after placing a call with signal. I then cannot adjust volume anymore.

Phone is S4 Mini.
