### ISSUE TITLE
unable to call from opo

### ISSUE THREAD

**Issue by wrd83** [WhisperSystems/Signal-Android#4558]
I just installed signal, whenever I try to call somebody I get the overlay to choose the app to call with and get the following options:

 - skype
 - viber
 - phone

I don't get the option to just call over signal (wiithout costs). iterestingly the connection setup works as I can receive calls successfully.

(Also installed apps: skype, whatsapp and viber)
operating system: cm 12.1-20151007-SNAPSHOT-YOG4PPO33I-bacon
android version 5.1.1
I'm connected via wifi.
Signal version 3.3.3
log: https://gist.github.com/34c3b44b2e3b7332c470

**Comment by moxie0** [comment]
should be fixed in 3.4
