### ISSUE TITLE
RedPhone message from service: LOGIN_FAILED

### ISSUE THREAD

**Issue by unimelbIR** [WhisperSystems/Signal-Android#4563]
After upgrading to signal I can't use the secure call functionality. Looking at the debug log ([here](https://gist.github.com/anonymous/1fdc1beac5ba10e039b6)) I can see the following problem:

```
W/RedPhone( 4073): Got message from service: LOGIN_FAILED
```

which is also displayed in the UI when trying to make a call. Interestingly yesterday the "secure call" functionality didn't appear in the UI at all (it showed the regular call button instead)

**Comment by mammuth** [comment]
Is the person you try calling also using Signal for Android >=3.0 or the iOS app? 

Is the encrypted call icon shown after you press on the floating action button on the bottom right, then pull to refresh the contact list?

**Comment by mpetri** [comment]
I created this issue with the wrong github user. 

Both users are using the current signal for android version. The encrypted call icon is shown in the top right corner. When I click it the call begins, it switches from the "chat view" to the "call view" it shows "dailing" followed by the "login failed" message and returns to the "chat view" where an entry "Called XYZ" was added to the chat log.

After pressing the floating action button I see the Image, Audio, Video, Contact and Camera button.

**Comment by justin-** [comment]
I'm also encountering this issue. Here's [a debug log](https://gist.github.com/5950050c3c8d637287fa). The UI says "DIALING", one ping noise plays, and then "LOGIN FAILED" is displayed and the call ends.

As you can see in the log the WhisperSystems server is returning HTTP 401 during initiation.

This is happening when calling both Android and iOS users. Refreshing the contacts list did not resolve the issue, nor does rebooting the phone.

**Comment by xris** [comment]
I am also having this exact problem.

**Comment by p1st4ch0** [comment]
Me too. Both last Signal for Android.

**Comment by simdol** [comment]
I am on Jolla phone with Sailfish OS 2.0.1.7 under Android support layer . This issue persists with this phone as well. I doubt that I could get support for this specific case but I will leave this here just in case while crossing my fingers.

https://gist.github.com/9f512dfe186f91421ddf

**Comment by vandenheuvel** [comment]
I'm having this issue on https://github.com/WhisperSystems/Signal-Android/commit/a0489a9f48c19e9a1f72c314c4b1da56ed710b00. Logger line before this one is `InitiatingCallManager.run`, the line after is `ProximityLock: Released proximity lock:false`.

**Comment by 2-4601** [comment]
@vandenheuvel Please post the full debug log if you have still it.

**Comment by vandenheuvel** [comment]
@2-4601 In this log, the last things I did were

1. Successfully send a text message (encrypted)
2. Atempt to call the same contact (then I encounter this issue)
3. Go to settings and send the log

https://gist.github.com/anonymous/7ddd1e56de83e59227ae86325d13f405

**Comment by bl-kl2** [comment]
I'm using a Blackberry Classic with Signal 3.30.2 beta, non-play-services version.
Tried to call another device; this device has "video calling beta enabled", Signal 3.29.6, play-services version.
Synced, and re-registered the numbers, on both devices.
From the device with "video calling beta enabled" to the Blackberry,
always "Number not registered! The number you dialed does not support secure voice".
From the Blackberry, always "Login Failed".
Texts work, both directions.

-- debug log ---
"HTTP/1.0 401 Unauthorized" from WhisperSystems server:
https://gist.github.com/anonymous/cb300f11486beb6e04e16377e22aa765

**Comment by nrizzio** [comment]
This can be closed since it's an old redphone issue.
