### ISSUE TITLE
Language of Contact's Additions

### ISSUE THREAD

**Issue by tehabe** [WhisperSystems/Signal-Android#4573]
When you sync Signal with your contact, you get two additional fields: "Signal call" and "Message". When you change the language of your device it used to be enough to just resync and the language of theses field would also change. Not anymore. You have to remove and readd the Signal account in the Android settings.

It is probably not a important bug because except me, nobody changes the language on a daily basis but well. I think I should mention it.

**Comment by moxie0** [comment]
thanks for the report but we're going to live with that
