### ISSUE TITLE
Signal icon(s) for contacts; possible consolidation

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#4574]
When I look at a contact in my android contact app, if it's a Signal contact, I have two of the same Signal icons, one for call and one for message but I don't know the difference before pressing them.  For the normal phone call icon it shows options in the window below.  I don't know if consolidating the actions and using one icon, or having two slightly different icons with different actions is better.  Something to think about.

**Comment by dcherian** [comment]
This happens with Skype too --- multiple icons for IM, call and video call. Maybe it's an Android thing?

**Comment by jeremymasters** [comment]
Maybe.  Maybe Samsung specific controllability.  If it's a pain in the butt to do this it's not worth it.

**Comment by johanw666** [comment]
On a Sony device, I see the same icons, one preceded by Message and one by Signal Call. WhatsApp does the same. It is clear from the text what the intended action is.

**Comment by mammuth** [comment]
On my phone (Android 5.1.1 (CM12) with Signal 3.4.2) the dialer app shows "Message +12 34567" and "Signal Call +12 34567".

So this doesn't seem to be a problem in Signal, but something else.

**Comment by jeremymasters** [comment]
I think I'll close this to avoid more discussion since it's not a big deal and I'm sure the devs get tons of email.
