### ISSUE TITLE
German invite texts to signal sound rather spammy

### ISSUE THREAD

**Issue by markum** [WhisperSystems/Signal-Android#4578]
I like the invite feature, but what I do not like is the text. "Wechseln wir zu Signal" (Let's move to Signal) + a strange looking link does not sound really trustworthy. Hardly anyone knows about Signal. So I assume recipents would rather thing that someone has hijacked my phone. I would suggest to change the text what people can more relate to: 
- Security and Encription
- Comparing it to SMS or Whats-Apps
- that it's free

That might be a longer text, but more trustworthy and understandable
-> Let's move to Signal, the secure and free WhatsApp/SMS alternative -> Link (one that looks more trustworthy)
-> German: Wechsel wir zu Signal, eine sichere und freie Alternative zu WhatsApp

**Comment by RiseT** [comment]
@markum GitHub is the wrong place to post this as the translations are done at Transifex.

For what it's worth, I sort of agree, so I've just changed it to "Wechseln wir zu Signal, einem sicheren und kostenlosen Messenger: link". Should be short enough to fit into one SMS. The link's adress cannot be changed.

Please close this issue now for the reason mentioned above.

**Comment by moxie0** [comment]
I obviously have no way of monitoring this, but I'd prefer it if translators didn't editorialize.  We put a lot of thought into copy and tone, and would like for that to be carried over as identically as possible into other translations.

Like it or not, we've intentionally chosen not to use the words "free" or "secure" in the invite link right now.  We have analytics that allow us to gauge how different strings do relative to each-other, and we can't effectively measure if it's not translated accurately.

**Comment by RiseT** [comment]
@moxie0 OK - I wasn't aware about your stance on this. I'll revert it.

I am not sure if one language's tone always carries over into others (at least with the same wording), though.

**Comment by moxie0** [comment]
@RiseT For sure, I know it's not possible to "directly" translate text, but I'm hoping that the translations attempt to preserve the tone to the extent that a translated novel does.

**Comment by RiseT** [comment]
@moxie0 OK, I see what you mean.

**Comment by RiseT** [comment]
@moxie0 Btw - I've just noticed that you've just changed the project's name at Transifex to "Signal Android". The iOS project uses "Signal-iOS", i. e. with a hyphen. Don't know which one is better, don't even know if this matters at all. I just want to point it out in case you're interested in that kind of consistency.

**Comment by generalmanager** [comment]
Well we do try to convey the meaning as well as humanly possible. But this often means that we have to change words or phrases, because word-for-word translations either wouldn't make sense or be way too long for the context they are used in.
