### ISSUE TITLE
Upgrading to API 23

### ISSUE THREAD

**Issue by F1rst-Unicorn** [WhisperSystems/Signal-Android#4581]
Hi all, 

I tried to modify build.gradle to use compileSdkVersion 23 and the corresponding appcompat library. Unfortunately OutgoingLegacyMmsConnection.java uses the org.apache.http package with some of its deprecated features since API 23. Are there any plans to fix this problem and migrate the SDK version?

**Comment by agrajaghh** [comment]
see #3985, don't know why its closed though...

**Comment by moxie0** [comment]
@F1rst-Unicorn This isn't a dicussion forum or a place to post questions, thanks.
