### ISSUE TITLE
Translate error

### ISSUE THREAD

**Issue by iZerOo** [WhisperSystems/Signal-Android#4582]
Hello,

On file `res/values-fr/strings.xml#L268` :  the value from `MessageRecord_missed_call_from` should be "Appel manqué de %s" instead of "Apple manqué de %s"

Regards.

**Comment by agrajaghh** [comment]
translations are done via transifex, not github, see https://github.com/WhisperSystems/Signal-Android#contributing-translations

**Comment by jocelynthode** [comment]
I fixed it and added you to the french translation team. You can close this issue

**Comment by iZerOo** [comment]
Thanks !
