### ISSUE TITLE
Impossible to send SMS to short numbers

### ISSUE THREAD

**Issue by LastNetwork** [WhisperSystems/Signal-Android#4583]
It is impossible to send SMS to short numbers because it automatically adds the country code at the beginning of the number.

For example for 2282 it adds +47 to the number so it will be +47 2282 if you live in Norway, that makes it impossible to send because the GSM networks (at least here in Norway) don't allow +47 in front of short numbers.

I tried with version 3.3.3.

**Comment by agrajaghh** [comment]
should be fixed with the next version: https://github.com/WhisperSystems/Signal-Android/commit/69f5aacd2514ba3ea90d1b3cfba3908e229bc40b

**Comment by LastNetwork** [comment]
Just joined the beta program.
Confirmed working with version 3.4.2.
