### ISSUE TITLE
Log spam on animated GIF display, "Called reconfigure on a bitmap that is in use!"

### ISSUE THREAD

**Issue by unrulygnu** [WhisperSystems/Signal-Android#4588]
The following entry spams the log every 9 to 40 milliseconds while an animated GIF (tested 3 different GIF's) is displayed in the conversation list or in a conversation:

    org.thoughtcrime.securesms W/Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!

I haven't crawled the commits to see when this began, but I will update if I get the chance.

Device info: Nexus 5, stock Android 6.0 MRA58K, Signal 3.4.2 (028a1ab)

App state: Signal registered, SMS enabled, default SMS app

**Comment by mcginty** [comment]
looks like a glide issue

**Comment by unrulygnu** [comment]
https://github.com/bumptech/glide/issues/743

Closing
