### ISSUE TITLE
GIF animation quirks

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#4599]
Noticed on https://github.com/mcginty/TextSecure/commit/35d003a1bb978bb28f5ad999806365c67b2c686d (#4589)

GIFs shared 
with forwarding
or from outside Signal don't move in the thumbnail or convo list preview, though the draft preview does move as well as it does in the image view

some repro steps:

in app attach:
- attach animated image gif
- see it move in draft
- send
- see it move in thumbnail
- see it move in convo list
- see it move in image viewer
- see all moving on receiver side

forward *moving preview* gif
- forward message to self (or other convo)
- see draft moving
- send
- see STILL of gif in thumbnail
- see STILL of gif in convo list
- see it move in image viewer
- see SAME behavior on receiver side

share to signal:
- choose your favorite gallery app
- pick animated gif
- share to signal
- pick contact or group
- see draft moving
- send
- see STILL of gif in thumbnail (or in one case just blackness instead of thumb)
- see STILL of gif in convo list (correct still in the above blackness case)
- see it move in image viewer
- see SAME behavior on receiver side

**Comment by McLoo** [comment]
Tested  with these two brain twisters 

![space-warper-small](https://cloud.githubusercontent.com/assets/5326916/11266503/453d6282-8ea5-11e5-8f02-82cfc6ff3d27.gif)
![funny-gifs-when-no-ones-around-large](https://cloud.githubusercontent.com/assets/5326916/11266511/4e92d830-8ea5-11e5-9716-7d5d93895293.gif)

**Comment by mcginty** [comment]
I can't repro on this Jellybean device I just tried it on. Is this a consistent issue or occasional?

**Comment by McLoo** [comment]
I'm very disappointed of bugs nowadays.
They just don't stay until they got fixed... :disappointed: 

Was very consistent. But can't repro anymore on 3.6.0 branch and 3.5.1 play release.
