### ISSUE TITLE
Hands-free button not sticky during call initialization

### ISSUE THREAD

**Issue by Norbert80** [WhisperSystems/Signal-Android#4601]
- Place a call
- Immediately press hands-free button
- Note that hands-free button releases after the server has been contacted
- Immediately press hands-free button again
- Note that hands-free button releases again after the voip connection has established.

Found on Signal 3.4.2 Android.

**Comment by moxie0** [comment]
What is the "hands free button"?

**Comment by 2-4601** [comment]
If it is the speaker button then duplicate of #4188

**Comment by Norbert80** [comment]
Speaker on

**Comment by moxie0** [comment]
Closing as duplicate
