### ISSUE TITLE
Dark theme flaw in "manage linked devices" 

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#4611]
Master at 4314a4b4
![screenshot_2015-11-19-21-13-46](https://cloud.githubusercontent.com/assets/5326916/11283014/c1e5c696-8f02-11e5-8118-06f2256110c3.png)

**Comment by 2-4601** [comment]
Hmm... I see this:
![devprov](https://cloud.githubusercontent.com/assets/174176/11283359/f0b12e0c-8f0c-11e5-8e95-174942fbd689.png)
Is the black rounded rectangle supposed to be a camera view (to scan the QR)?

**Comment by mcginty** [comment]
@2-4601 yep, and the screen that @McLoo is what you get after a scan of the QR. Do you just see a black screen? If so, can you post logs?

**Comment by 2-4601** [comment]
Ok, will create a new issue with logs an delete my comments from here (I thought first that these are the same issue)

**Comment by McLoo** [comment]
And also for the scanning activity. So bright...  
(killed cam therefore the black preview) 



![screenshot_2015-11-26-00-42-02](https://cloud.githubusercontent.com/assets/5326916/11411960/e4e4fde6-93d6-11e5-82a5-dbb0db17da02.png)

**Comment by benmayne** [comment]
this was my log when I saw it: 

https://gist.github.com/anonymous/7e2a22d1d181aeb5a83e

![2015-12-10 03 58 10](https://cloud.githubusercontent.com/assets/3374110/11706682/b2eea858-9eaf-11e5-85a3-63730eb66743.png)
