### ISSUE TITLE
Device provisioning: QR code camera preview is black

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/Signal-Android#4613]
Master with 61386e9ca9eb48fc8c73a2c32d382bd0bcfeadf2 head

![devprov](https://cloud.githubusercontent.com/assets/174176/11283359/f0b12e0c-8f0c-11e5-8e95-174942fbd689.png)

Spammy log:
https://gist.github.com/anonymous/4bad8537594cfd5c7c48

Never had any problems with camera and Signal on this device before. E.g. quick capture has worked fine.

**Comment by 2-4601** [comment]
Is it expected that the old method of using a 3rd party QR code scanner does not work any more?
**Barcode Scanner:**
![dialog](https://cloud.githubusercontent.com/assets/174176/11284035/4fe7f826-8f10-11e5-906b-484b34c10988.jpg)

**Comment by mcginty** [comment]
seems intentional https://github.com/WhisperSystems/Signal-Android/commit/7c0bf0c871c96dd89605e3daf07d3c332522fdef#diff-a48d6def78e18cbabab3c95ae3c9fc49L139

although if the CameraView doesn't work on a phone for whatever reason, it may be good to actually have this as a fallback.

**Comment by moxie0** [comment]
i'd like to leave it out, to avoid the situation where someone inadvertently scans a qr code somewhere instead of intentionally doing it within the app

**Comment by 2-4601** [comment]
The commits of #4616 solved this for me.
