### ISSUE TITLE
"Last active" is odd in "Manage linked devices"

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#4614]
Head master ( 06f2908 )

Device info says:
```
Linked Thu 09:16 PM
Last active Thu 01:00 AM
```

I had this device linked before
unregistered some time today (Thu)
and linked again at 09:16 pm obviously

Last active doesn't change when Signal-Browser sends or receives?!

**Comment by 2-4601** [comment]
I have
```
Linked Thu 23:04
Last active Thu 02:00 AM
```
Master with 61386e9ca9eb48fc8c73a2c32d382bd0bcfeadf2 head

**Comment by moxie0** [comment]
Only day-level precision is being tracked, so I should probably only display day-level precision.

**Comment by 2-4601** [comment]
By the way, the dates/times don't seem to use localization.

**Comment by moxie0** [comment]
in 3.6.0
