### ISSUE TITLE
Send Multiple Images at Once

### ISSUE THREAD

**Issue by 192834** [WhisperSystems/Signal-Android#4629]
Feature Request: The ability to send multiple images at once.  Right now, you can only send one image at once.  Telegram allows the user to send unlimited images at once.

**Comment by moxie0** [comment]
Thanks but I don't think we're going to do this

**Comment by castanley** [comment]
Uh, this is a feature that is available for stock messenger. Can we not get a feature that is available for stock messenger? I mean there is a "bug" report that has been open for 3 years requesting this. 

https://github.com/WhisperSystems/Signal-Android/issues/1300

**Comment by andyggg** [comment]
I would also encourage to implement this feature of sending multiple media (photos) in one go. At the moment, it is really a pain to send 20 photos that are somewhere in the middle of the garrery so that I have  to scroll a lot every time....

**Comment by 2-4601** [comment]
Duplicate of #2159.
This feature request is being discussed and tracked [here](https://community.signalusers.org/t/share-multiple-photos-files/2544).
