### ISSUE TITLE
Add Encrypted SMS between Signal users.

### ISSUE THREAD

**Issue by Eclipse-kun** [WhisperSystems/Signal-Android#4631]
There should really be an option to send encrypted SMS instead of solely relying on an internet connection for encrypted chat. I mean, it's definitely possible between Signal users. The problem arises when one party does not have an internet connection, but both parties have a mobile signal. You have to resort to insecure SMS in order to get a message through. This shouldn't be the case. Between signal users, it should seamlessly be able to switch between secure SMS and secure IM when available.

**Comment by dcherian** [comment]
https://whispersystems.org/blog/goodbye-encrypted-sms/

**Comment by Eclipse-kun** [comment]
Ah, I guess I should have searched it up. Closing this issue.
