### ISSUE TITLE
Unlinking device: endless Wheels of Confusion

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/Signal-Android#4641]
1. Unlink a device
2. The Wheel of Confusion spins till heat death

![black sabbath vol 4 wheels of confusion](https://cloud.githubusercontent.com/assets/174176/11314556/42f48faa-8fef-11e5-8fd8-47cd3d0d2264.gif)

This is just a visual problem. I.e. the device gets actually unlinked.

Tested on 3.5.0 (though the wheels have been spinning since summer... was just too afraid to report it before :)
* Nexus 4, stock 5.1.1
* Huawei U8800, 4.0.4

Edit:
Also tested when there are more than one device linked. Same issue.

**Comment by bartz1** [comment]
I have the same problem. Going back and re-entering the devices page fixes it for me (no devices are shown as linked)

**Comment by FeuRenard** [comment]
I encountered this problem, too. Here is a log:
https://gist.github.com/anonymous/98b3d3ef4d19e23e17c2
