### ISSUE TITLE
NPE when attempting to link devices

### ISSUE THREAD

**Issue by jtracey** [WhisperSystems/Signal-Android#4642]
I have a tablet with Signal still installed on it from #4457 that thinks it's still registered, but isn't. When I use my phone to scan the tablet's identity key QR code to try to link the two, I consistently get a NPE on my phone.
debug log: https://gist.github.com/38db7f98d0e4fe2b36c4

**Comment by bartz1** [comment]
I don't think you can link tablets yet. You should try with the Signal extension after properly changing the server URL.

**Comment by 2-4601** [comment]
I guess without any in-app instructions this might seem the right way to scan the QR code of the device to be linked.
But the device provisioning needs a different kind of a QR code. Not the slave's public identity key.

Currently it only works with the Chrome plugin which will create a provisioning QR for the Android client. But the plugin is unreleased software and as far as I understand you should not really use it yet or if you decide to use it and something goes wrong OWS does not have the resources to support you.

Back to this issue. Tried to scan a random QR code and it went successfully through all the dialogs:
* Link this device?
 * It will be able to...
* Linking device...

And then crashed. It should definitely fail earlier with non-provisioning QRs.
