### ISSUE TITLE
poor voice messages quality

### ISSUE THREAD

**Issue by Mihahn** [WhisperSystems/Signal-Android#4647]
The quality of the voice messages is (e.g. compared to WhatsApp) really poor. You are able to understand what I'm saying in the voice message, but it sounds like the wrong mic is used to record the message or something like that...
https://gist.github.com/anonymous/14c457ad60dd006db28b

Nexus 4, Android 5.1.1, Signal 3.5.0

**Comment by jwittlincohen** [comment]
I tested out the voice messaging feature as well and the quality is great.  Clear voice without obvious compression artifacts or other distortion.  I don't find it any worse than Whatsapp.

**Comment by jwittlincohen** [comment]
I'm using a OnePlus One with CM11 (4.4.4) and Signal 3.5.0.

**Comment by bartz1** [comment]
On my Samsung the quality is worse than when calling, but I wouldn't complain

**Comment by Mihahn** [comment]
Please don't get me wrong, I don't want to complain. I absolutely love the feature! :smile: 

But I think this is a bug and it makes voice messages hardly useable on some devices, so maybe the developers are able to find out what's wrong and fix it...

**Comment by Dyras** [comment]
+900
I thought it was my crappy phone at first, but Telegrams voice messages aren't anywhere near this crappy. My friend can't tell what I'm saying, even on the highest possible volume!

Samsung Galaxy Nexus

**Comment by mcginty** [comment]
we're switching codecs away from AMR narrowband, this will be resolved soon

**Comment by Dyras** [comment]
I'm curious, what will you be switching to?

**Comment by mcginty** [comment]
Looking like AAC for the sake of compatibility with all platforms we're developing on.
