### ISSUE TITLE
1 second voice messages never reach end on playback

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/Signal-Android#4654]
1. Record a short voice message (about 1 second or so)
2. Play it
3. It will play but the slider will never reach the end

![george costanza answering machine](https://cloud.githubusercontent.com/assets/174176/11320012/01dd71ac-9095-11e5-8f47-5ebfdf32165a.gif)

It seems to stop playing almost at the end (95%>). But because it does not get to 100% the slider will never reset itself to the beginning. Does not affect longer voice messages (e.g. 2 seconds and above work fine)

Signal 3.5.0, Nexus 5, stock 5.1.1

Edit:
Here's a debug log: https://gist.github.com/anonymous/9f8dcbd1bfbeb01d02c7
I tried to play the message four times. Last three tries are when the slider is around >95%
Relevant part:(?)

```
W/AudioSlidePlayer( 5132): onComplete
W/AudioView( 5132): playbutton onClick
D/MediaPlayer( 5132): Couldn't open file on client side, trying server side
I/AudioAttachmentServer( 5132): Header: user-agent : stagefright/1.2 (Linux;Android 5.1.1)
I/AudioAttachmentServer( 5132): Header: accept-encoding : gzip
I/AudioAttachmentServer( 5132): Header: host : 127.0.0.1:42460
I/AudioAttachmentServer( 5132): Header: connection : Keep-Alive
I/AudioAttachmentServer( 5132): headers: HTTP/1.1 200 OK
I/AudioAttachmentServer( 5132): Content-Type: audio/*
I/AudioAttachmentServer( 5132): Accept-Ranges: bytes
I/AudioAttachmentServer( 5132): Content-Length: 2214
I/AudioAttachmentServer( 5132): Connection: Keep-Alive
I/AudioAttachmentServer( 5132): 
E/MediaPlayer( 5132): Should have subtitle controller already set
W/AudioSlidePlayer( 5132): onPrepared
W/AudioSlidePlayer( 5132): onComplete
W/AudioAttachmentServer( 5132): java.net.SocketTimeoutException
W/AudioAttachmentServer( 5132):     at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:99)
W/AudioAttachmentServer( 5132):     at java.net.ServerSocket.implAccept(ServerSocket.java:216)
W/AudioAttachmentServer( 5132):     at java.net.ServerSocket.accept(ServerSocket.java:140)
W/AudioAttachmentServer( 5132):     at org.thoughtcrime.securesms.audio.AudioAttachmentServer.run(AudioAttachmentServer.java:85)
W/AudioAttachmentServer( 5132):     at java.lang.Thread.run(Thread.java:818)
W/AudioAttachmentServer( 5132): Caused by: android.system.ErrnoException: accept failed: EAGAIN (Try again)
W/AudioAttachmentServer( 5132):     at libcore.io.Posix.accept(Native Method)
W/AudioAttachmentServer( 5132):     at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:63)
W/AudioAttachmentServer( 5132):     at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:89)
W/AudioAttachmentServer( 5132):     ... 4 more
D/AudioAttachmentServer( 5132): Proxy interrupted. Shutting down.
```

---

Edit:
Example file: http://wikisend.com/download/268952/georges.answering.machine.1.sec.amr
I exported that from Signal (save to storage). Sending that file as an audio attachment on my other device and then playing it causes the same behaviour. However that device does not have the issue when it itself records a 1 sec voice messages. Only when its receiving one or attaching the example file.

**Comment by McLoo** [comment]
#4652 related?!

**Comment by 2-4601** [comment]
Saw that before submitting this but was unable to reproduce it.

I don't have problems with the end cutting off. The playback just never reaches the 100% end position and thus the slider never resets. This only affects <= 1 sec messages. 2 second messages are already fine though.

**Comment by McLoo** [comment]
Can't repro. Is this on the sender's side only?

(btw: what do you use for screen capturing?)

**Comment by 2-4601** [comment]
I can't reproduce this when I record with my other device (Huaweui U8800).
But when I record and send 1 sec message with my Nexus 4 the receiving device has this issue on playback. I might add a sample file to original description later.

I use Android's own `screenrecord` for screen capturing and then ffmpeg, ImageMagick and GIMP for giffing.

**Comment by TheNain38** [comment]
For me it always happen, even if the recording is longer than 1 second... On a Samsung Galaxt SIII

**Comment by 2-4601** [comment]
Unable to reproduce anymore with the original device.
