### ISSUE TITLE
Quick capture preview quirky after 1st init in convo 

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#4657]
Maybe one finds a better title for that 

- enter any convo 
- Open quick capture 
- see blackness for about 1 sec (way to long :stuck_out_tongue:) 
- then the image preview 
- followed by a short focusing action 
- close QC 

Now the funky (issue)   part 
- Open qc again 
- see the previous preview shortly 
- followed by a resize of the preview 
- immediately followed by the correct preview 

And the side  effect: 
While the previous preview is shown, the shutter icon isn't working (it blinks on taping, but doesn't capture). 
Whereas when in first (black preview)  init it seems an immediate tap on the shutter always captures as soon as the preview is up. 

Seen with 
3.5.0 on Z1c 5.1.1
3.5.0 black draft fix on HTC One S CM 12.1

**Comment by McLoo** [comment]
Log after opening and closing  QC 3 times 
(pretty polluted that log is) 
https://gist.github.com/5fc681368483da6924e6

**Comment by McLoo** [comment]
And just to be clear: with "preview"  I mean the camera view, not a draft or whatever might be interpreted there in

**Comment by 2-4601** [comment]
I had the blackness (and sticking on a still frame) at the very first opening of quick capture camera but @mcginty put some WD40 in it and it came unstuck (#4616, #4620).

**Comment by McLoo** [comment]
Ah, that explains the new smell of 3.5.0 😰
Can live with the black init phase, but don't like the other thing

**Comment by mcginty** [comment]
Twitchy preview surfaces have always been an issue because of how Android deals with hardware rendering. This isn't a crash, I think we should push to 3.6.0 and I can look into putting in an artificial black overlay while the surface is preparing.

**Comment by mcginty** [comment]
in 3.6.0
