### ISSUE TITLE
Signal 3.5.0 When scanning the QR code nothing happens

### ISSUE THREAD

**Issue by JStyle21** [WhisperSystems/Signal-Android#4661]
Trying to add a device by scanning a QR code from signal browser does absolutely nothing...
Tried landscape orientating and all possible angles.

**Comment by mawed** [comment]
Same here, there's just a small notification "No device found".

I'm not sure if 3.5.0 is built to also "beta" Signal-Browser. Did the beta version works for anyone to link the browser?

**Comment by Mihahn** [comment]
To use "Signal-Browser" you have to build your own version of Signal that targets the staging server. Otherwise it won't work yet. See https://github.com/WhisperSystems/Signal-Browser#warning-warning-warning for reference.

**Comment by 2-4601** [comment]
@JStyle21 By "nothing happens" do you mean that
* the camera view is black? (#4613)
* camera view shows live picture but is unable to scan? (#4637)

**Comment by moxie0** [comment]
the browser extension hasn't been released yet

**Comment by JStyle21** [comment]
I think based on the case and device that
https://github.com/WhisperSystems/Signal-Android/issues/4637
is the closest to what i'm experiencing.
And it doesn't matter if the extension isn't out it used to work just fine before 3.5.0 with a qr code reader.
