### ISSUE TITLE
Signal 3.5.0: When you click on bottom right button the slider can't go all the way down

### ISSUE THREAD

**Issue by TheNain38** [WhisperSystems/Signal-Android#4664]

**Comment by mammuth** [comment]
I think your issue has a lack of informative description. 

- Which view / slider / buttons are you talking about?
- What are the exact steps to reproduce your problem?
- What's your expected outcome? 

Without such information your issue is worthless and should be closed.

**Comment by TheNain38** [comment]
I talk about the button with a pen, which is on the bottom right when you open Signal.
The slider at the right can't go all the way down

**Comment by TheNain38** [comment]
I think it happens since 61386e9ca9eb48fc8c73a2c32d382bd0bcfeadf2

**Comment by 2-4601** [comment]
![contacts](https://cloud.githubusercontent.com/assets/174176/11325523/c06daa06-9158-11e5-965e-f905c221ffb4.png)
