### ISSUE TITLE
Problems with messages from unknown contact.

### ISSUE THREAD

**Issue by JoEiner** [WhisperSystems/Signal-Android#4668]
With signal 3.5.0 I get the following issue:

Somebody who is not in my contact list sends me a push message. Two issues arise:
 - Although he is using Signal for iOS I cannot respond to the message with an encrypted call (padlock symbol next to phone symbol is missing). The padlock symbol appears when I go into the new message screen and pull down the contact list to refresh the push information. 
 - I then have a conversation with the person via push messaging and later add him to my contact list. Some time after I add him I get a push notification stating "... is now on Signal, say hey!", although the contact was Signal user before he first contacted me.

**Comment by moxie0** [comment]
thanks but these are already represented somewhere here iirc
