### ISSUE TITLE
Move identity verification to use the included XZing

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#4671]
Rather than call for the Xzing app, 
Now that scanning is built in...

**Comment by dcherian** [comment]
Related: https://github.com/WhisperSystems/Signal-Android/issues/2074

**Comment by RiseT** [comment]
I believe the Xzing app is used for rendering the displayed QR-codes as well, so built in scanning might not be enough on its own. But generally, I totally agree.

**Comment by moxie0** [comment]
We're planning on changing this whole flow, so we don't need this issue to track it, thanks.
