### ISSUE TITLE
Generally poor audio quality and high latency with Signal calls

### ISSUE THREAD

**Issue by jwittlincohen** [WhisperSystems/Signal-Android#4676]
Latency: Perhaps the most notable difference between making a Signal and a standard cell phone call is the latency encountered.  In fact, it was the very first comment one of my friends mentioned when we initiated the call.  RTT appears to be at least 1 second even when the person I'm calling is relatively close (several hundred miles on the East cost of the US, where Signal has a server - can't find the link now but Moxie published a blog post indicating where Signal has servers for routing calls).  However, when I call the same person on Jitsi, the RTT is below 100 ms, and latency is barely noticeable.  We are both connecting via Wifi using broadband connections with at least 50 Mbit down and 10 Mbit of upload capacity for him and 100/100 for me (Fiber on my end, cable on his).  Jitsi shows effectively 0% packet loss and sub 5ms jitter with RTT typically around 50 ms.  Thus, I would not expect significant latency in Signal given our geographic proximity and high speed, relatively low-latency connections.  In fact, my Signal calls to the US from China seemed to have similar latency to the East Cost - East Coast US calls.

Audio Quality:  The audio quality in Signal appears to generally be worse than a cell phone call, and is significantly worse than Jitsi or Skype (both of which use wideband codecs - SILK for Skype IIRC and Opus @ 48 Khz for Jitsi).  In addition, I notice more cut-outs and audio distortions with Signal.  Again, both callers are on Wifi with high-speed broadband connections and are in relatively close physical proximity.  

I would imagine that implementing Opus in Signal would improve call quality generally, particularly if it is allowed to run in a wideband setting, as Opus is superior to Speex at all bitrates/sampling rates per the documentation.  However, I'm rather perplexed about the subjectively high latency.

Note: Wasn't sure whether to post this here or on the mailing list.   Please advise.

**Comment by Dyras** [comment]
https://github.com/WhisperSystems/Signal-Android/issues/4647#issuecomment-158691199
They are working on fixing this. But I agree, the delay along with the random disappearing/reappearing of the sound is really annoying.

**Comment by 2-4601** [comment]
Opus codec for voice calls tracked here #4359

**Comment by jwittlincohen** [comment]
@Dyras

I believe AAC would only be used for voice messages.  The internal latency is probably too high for real-time communication.  Opus has similar audio quality and very low internal latency (23 ms default, as low as 5 ms with certain settings).

**Comment by moxie0** [comment]
thanks but we don't need an issue to track this

**Comment by ChaosYoda** [comment]
Has this issue been fixed? Also would OPUS not be a better choice ?
