### ISSUE TITLE
Media forward inside convo fails if media draft exits 

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#4680]
Using in-convo forward as resend-an-old-message feature 

But this fails if a media draft is present already. 
In that case the existing media draft gets deleted and no new on draft  is created  :sob:

**Comment by McLoo** [comment]
#4538 duuuuplicate

**Comment by McLoo** [comment]
ahh! the draft appears back in convo list and also after reentering the said convo

**Comment by FeuRenard** [comment]
This sounds like a duplicate of #5832. Contrary to the rule I suggest to close this issue in favour of #5832 because I investigated the problem in more detail there.
