### ISSUE TITLE
Group: Some messages not received; others twice

### ISSUE THREAD

**Issue by gabrielbenedikt** [WhisperSystems/Signal-Android#4684]
In groupchats, some members receive some messages twice. 
Other messages are not received by some members.

Devices: Various. One of the affected (which both receives messages twice and misses others): Samsung Galaxy SII with CM 11, Android 4.4.4. Signal 3.4.2
Debug log from this device: https://gist.github.com/4bad64695838727faa20

Another device (missed 1 message so far afaik): Jiayu G4S, Salamander ROM (Android 4.4.4) 
Debug log: https://gist.github.com/c61364f3d8f589ffc64b

I'll be glad to provide further information/logs/test what's necessary to track this problem down.

**Comment by riyapenn** [comment]
Double message most likely related to iOS group chat users having to accept key changes:  https://github.com/WhisperSystems/Signal-iOS/issues/951

Contacts not receiving messages should check: 6 & 8 specifically on http://support.whispersystems.org/hc/en-us/articles/213190487-Why-is-there-a-delay-in-receiving-messages-

**Comment by Dyras** [comment]
The people I write to sometimes receive the same message twice, the second time several hours later. No idea why. In 1-1 chat though, not in group chat.

**Comment by riyapenn** [comment]
Will re-open, if this is consistently reproducible and useful debug logs (immediately after the issue happens) are provided.

**Comment by obifur** [comment]
Maybe it is far too late because it is 10 messages ago.. but i also received messages twice:

https://gist.github.com/cb1fee81dafc54becd6d

Group: 3xAndroid (5.1.1, 5.0.0, 5.0.?), 1x iOS. I receive double messages from Android users (both 5.0) only.

**Comment by cb474** [comment]
I have this problem on an Android phone receiving messages from someone with iOS (I don't communicated with Signal with anyone else on Android so I don't know that it couldn't happen that way too).

I will receive a message. Then reply. And as soon as I reply I get the original message again. This just happened. Here's the debug log:

https://gist.github.com/anonymous/45d13a4bbaff57f96f2b
