### ISSUE TITLE
Download indicator keeps spinning 

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#4690]
Just noticed an audio message,  
I received  yesterday with  the black-thumb-fix-build ('exactly' that branch, not merged  )  
has an eternal wheel of download. (leaving convo does not fix this) 

Didn't try to restart, maybe there is more info you need,  @mcginty. 
https://gist.github.com/f82805367fcb706786c5

**Comment by Dyras** [comment]
This also happened for me.
https://gist.github.com/anonymous/748fcdecae9e3c9a254f
Restarting my phone fixed it.

**Comment by McLoo** [comment]
never seen again
