### ISSUE TITLE
Contact list: Unexpected keyboard/dial pad toggle

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/Signal-Android#4700]
1.) Open contact list
2.) Tap into the (rather small) horizontal space directly above or below the text "Enter name or number" (make sure you don't hit the toggle button). I mean exactly that colored stripe where the text ("Enter name...") resides on. Just a hair above or below that text. Try a couple of times if you initially don't hit the critical area - sooner or later you will (pretending that you don't want to hit it might help ;-) ).
3.) See unexpected toggling between the normal keyboard and the dialpad

Signal 3.5.1, Android 6

**Comment by 2-4601** [comment]
Not sure how this is implemented but just in case want to point out that both
* the contact list in SMS invite screen and
* the contact list in group creation/update
also suffer from this.

**Comment by McLoo** [comment]
#3706 and #3750
The toggle button has a really huge tapping area.  It's peeking through underneath the text field. 

Guys wearing shorts are well aware of that issue :elephant:

**Comment by RiseT** [comment]
*Guys wearing shorts are well aware of that issue :elephant:*

ROFL

**Comment by mcginty** [comment]
https://github.com/WhisperSystems/Signal-Android/blob/master/src/org/thoughtcrime/securesms/components/ContactFilterToolbar.java#L100 seems a little high

**Comment by moxie0** [comment]
worked fine before you added that overflow menu!

**Comment by 2-4601** [comment]
Hmmm... now it feels too small again. :mouse2: If I don't tap precisely enough there's no reaction at all. Would be great if the size was just a bit bigger (but not too big) to get the most satisfactory experience.

Nexus 4, 5.1.1, Signal 3.6.0

**Comment by RiseT** [comment]
I'd say, in 3.6.0, I hit the button instantly 7 out of 10 times. So maybe a hair wider could be of some benefit.
