### ISSUE TITLE
Contact list & dark theme: Searching in landscape mode uses very different layout & light theme

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/Signal-Android#4701]
1.) Select dark theme
2.) Open contact list
3.) If not already open, open keyboard by tapping "Enter name or number"
4.) Rotate phone into landscape mode
5.) Notice a very different layout from portrait mode (might be intended, don't know)
6.) Notice that the dark theme is not used here

Signal 3.5.1, Android 6

**Comment by mcginty** [comment]
Currently intentional.

Just like with the conversation input, we let the keyboard take care of landscape input since it's safer that way for different screen and keyboard sizes (android defaults to this behavior).

**Comment by RiseT** [comment]
@mcginty So should I close this for now?
