### ISSUE TITLE
Messages only received over WiFi

### ISSUE THREAD

**Issue by jonblack** [WhisperSystems/Signal-Android#4706]
I'm relatively new to both Android and Signal, so this could be my own mistake.

I've noticed that messages only arrive when I'm on a WiFi network. Over my mobile network (4G) I never receive message. I notice this when I finally connect to a WiFi network and the messages come flooding in.

I checked the Signal settings but can't see anything that would affect this. I've also checked to ensure background data is allowed both globally for mobile internet, and specifically for Signal.

**Comment by agrajaghh** [comment]
please ask your question here: http://support.whispersystems.org

**Comment by jonblack** [comment]
Will do. Thanks.
