### ISSUE TITLE
Pushbullet can read and reply

### ISSUE THREAD

**Issue by jhaubrich** [WhisperSystems/Signal-Android#4709]
I don't know if this is intended behavior, but I was surprised to see my encrypted conversations pop up on my desktop. I was also able to reply to them from my desktop.   
```
Device  : LGE Nexus 5 (hammerhead)
Android : 5.1.1 (1636aa03d7, cm_hammerhead-userdebug 5.1.1 LMY48B 1636aa03d7 test-keys)
Memory  : 47M (0.02% used, 192M max)
Memclass: 192
OS Host : cyanogenmod
App     : Signal 3.4.2
```

https://gist.github.com/anonymous/dfacd7a3253c2e936e03
## Here is the notification on my desktop.
![2015-11-24-102253_6720x3436_scrot-blur](https://cloud.githubusercontent.com/assets/1168043/11373458/0505fc0a-9298-11e5-86d1-677fff0b9514.png)
## I was able to reply to the message from the desktop.
![2015-11-24-094956_6720x3436_scrot-blur](https://cloud.githubusercontent.com/assets/1168043/11373710/18ac5d8e-9299-11e5-8b8f-2020d529ba8c.png)
## The message sent from the desktop was readable by the recipient.
![screenshot_2015-11-24-09-56-41-blur](https://cloud.githubusercontent.com/assets/1168043/11373716/1e580918-9299-11e5-8bf0-ad74715052f3.png)
## FWIW, it works with group conversations too. I think he means my chair. He's a nerd.
![screenshot_2015-11-24-10-28-33-blur](https://cloud.githubusercontent.com/assets/1168043/11373734/28bb4956-9299-11e5-806d-36d213773692.png)

**Comment by moxie0** [comment]
if you install spyware onto your device, you get spyware on your device

**Comment by jhaubrich** [comment]
Fair enough.
