### ISSUE TITLE
Bad UX with expiring Signal versions

### ISSUE THREAD

**Issue by cascheberg** [WhisperSystems/Signal-Android#4712]
Signal can literally expire any second, so that out of a sudden you are not able to send messages anymore (well, of course only if you do not update it for 90 days).
Immediately updating the app right then might not be possible if you require a wifi connection.

I am sure that this is not a problem for any of the people involved here, but for other non tech-savvy users it can be (firsthand experience).

Reasons for apps not updating automatically:
- new permission required (happened before the RedPhone integration)
- not enough free space on the device available
- for some other reason... it is not uncommon for me to see 10 or so pending app updates on other peoples's devices

There should be a time-triggered warning, or some other trigger to inform the user beforehand.

**Comment by 2-4601** [comment]
4696837f2ffa74878db6ee98e03b7f0e8c0a502d absolved us from this
