### ISSUE TITLE
please add user's background photo 

### ISSUE THREAD

**Issue by maxlinux2000** [WhisperSystems/Signal-Android#4724]
It would be nice to be able to change the background of Signal-android, with a photo.

This is not an essential feature, but if Signal-android is more beautiful, it will spread faster.

**Comment by haffenloher** [comment]
Dupe of #809

**Comment by cxarmonato** [comment]
In case you still want it, Signal plus has it https://play.google.com/store/apps/details?id=org.privatechats.securesms
