### ISSUE TITLE
Possibly use the privacy-preserving SCCDP for contact discovery?

### ISSUE THREAD

**Issue by skorokithakis** [WhisperSystems/Signal-Android#4726]
I'm not entirely sure how contacts discovery is done in Signal right now, so if it's done in a private manner feel free to close this ticket, but if contact numbers are currently being sent to a server, you can use the following server/protocol to avoid the server knowing too many details about the user's address book:

https://github.com/SilentCircle/contact-discovery

**Comment by moxie0** [comment]
The mailing list is the right place for posting stuff like this. The short answer, though: that protocol isn't meaningfully privacy preserving.
