### ISSUE TITLE
push service connection  error

### ISSUE THREAD

**Issue by amatanat** [WhisperSystems/Signal-Android#4735]
Hello,

I am trying to run my own textsecure-server.  When I connect android to server it gives connection error as ' Signal was unable to connect to push service'.  I created my own certificate. Changed TEXTSECURE_URL in build.gradle to ip address of my server as 'https://ip_adress/'. When I change this URL to 'http:ip_address:8080\' - android connects to server but after verification,in registering with server part, it gives the same error. Maybe someone can help me.

**Comment by mawed** [comment]
There is no ofgicial support for Signal server.

So you can close this ticket yourself or the admins will do so.

You can try to get contact with other unofficial developers over the mailinglist.
