### ISSUE TITLE
ADB backup not allowed anymore

### ISSUE THREAD

**Issue by fajabird** [WhisperSystems/Signal-Android#4742]
Plesse, allow ADB backup again. Its not something normal users will consider, so minor issues should not become your Problem. I was doing it for few years now and only issue was to fix push by simply re-registering to push Server.

**Comment by fajabird** [comment]
BTW. Currently there is no backup solution within signal to compensate ADB backup. Cleartext backup without media files is not an Option.

**Comment by moxie0** [comment]
duplicate, please check existing issues before opening new ones

**Comment by rdoeffinger** [comment]
When closing as duplicate please reference the duplicate. This issue is currently the top Google hit for "signal adb backup".
It seems #4577 is the ticket you referred to, though its title is more specific.
