### ISSUE TITLE
Messages "not delivered" when sent through the chrome extension

### ISSUE THREAD

**Issue by bartz1** [WhisperSystems/Signal-Android#4743]
I know that the Chrome extension hasn't officially been released yet, but since it looks like it's getting closer, I might as well point out this issue I'm having.
1. Put your phone in offline mode;
2. Use the Signal-chrome to send some messages to some people. Wait until they are delivered;
3. Turn on your phone's wifi/data. All the messages will be synced, but they will appear as not delivered.

I think this is a problem with the app on Android and not the browser extension because this problem is less frequent if I leave my phone's data on (though it's definitely still present, just not 100% of the time).

**Comment by 2-4601** [comment]
Closing in favour of #4924.
