### ISSUE TITLE
"Archived" and outgoing picture bug in conversation list

### ISSUE THREAD

**Issue by bartz1** [WhisperSystems/Signal-Android#4744]
Signal 3.6.0. Screen is about 4.3''.
1. I have a conversation where the last two messages are outgoing pictures;
2. I archived it;
3. When I go to the archived conversations, the label "archived" covers a small part of the picture's preview.

**Comment by McLoo** [comment]
![screenshot_2015-11-28-11-29-46](https://cloud.githubusercontent.com/assets/5326916/11451356/962aef14-95c3-11e5-91ff-91c860924c90.png)

**Comment by McLoo** [comment]
![screenshot_2015-11-28-11-29-46](https://cloud.githubusercontent.com/assets/5326916/11451356/962aef14-95c3-11e5-91ff-91c860924c90.png)

**Comment by bartz1** [comment]
Thanks for the screenshot, that's exactly what I meant :+1:

**Comment by McLoo** [comment]
@moxie0 probably sth. That should be merged with #4710 
Or just drop the "Archived",  as it's redundant because the action bar already tells you're in the archive.
