### ISSUE TITLE
Suddenly Lost Registration

### ISSUE THREAD

**Issue by xloem** [WhisperSystems/Signal-Android#4751]
After I sent an encrypted message to my only signal-using contact this morning (who for some reason sometimes sends me encrypted texts and sometimes unencrypted), Signal suddenly began the registration process again.  I received a message before it finished, and my reply was sent unencrypted.  After exchanging a couple unencrypted messages, clicking the button that appeared up top to enable encrypted functionality and seeing the registration window again, I generated a debug log: https://gist.github.com/e79519a8188d259844c0 .  My device and app version are listed there:

Device  : samsung SGH-T399 (gardaltetmo)
Android : 4.2.2 (T399UVUAOH2, JDQ39.T399UVUAOH2)
App     : Signal 3.5.2

After three attempts to register, I had successfully registered again.  The first two were interrupted by incoming messages or my attempt to generate a bug report.  During this time I successfully received an unencrypted MMS from my contact.  This was the first time I had successfully received an MMS on this phone; this was also my first signal mms.  Earlier I was using smssecure and my mms images just showed as "trying to contact server".  Signal would not complete registration until I'd uninstalled smssecure. 

I asked my contact to generate a debug log.  Here it is: https://gist.github.com/4837204c21c5b7c2ece4

My preferences:
- Receive all SMS, all MMS; SMS delivery reports on; Wifi Calling disabled.
- Notifications enabled; default ringtone; vibrate on; LED blue; LED blink normal; in-thread notifications enabled; never repeat alerts; display name and message in notifications
- passphrase disabled; screenshots blocked; no blocked contacts
- dark theme
- media auto-download only when using wifi (my phone is on wifi now); do not delete old messages
- no linked devices
- signal messages and calls enabled; enter key does not send; do not use system emoji

**Comment by xloem** [comment]
Here's a timeline:
1. Yesterday, contact sends me unencrypted message.  I reply with an encrypted message.  No further contact.
2. Today, contact sends me encrypted message.
3. I send two encrypted replies.
4. After second reply, signal immediately acts like it's been reinstalled, reloads and attempts to reregister.  
5. Receive encrypted text from contact
6. Reply, message is unencrypted
7. Receive encrypted text from contact
8. Receive unencrypted text from contact
9. More unencrypted messages exchanged, receive unencrypted MMS, debug logs generated.
10. I reregister, and send encrypted texts to contact
11. No messages received.
12. Reset secure session and send another encrypted text, contact is probably away from device

**Comment by moxie0** [comment]
Thanks but this is likely a ROM bug or storage corruption issue.  That sharedpref is only written to once, so if it disappeared either you used something like TiBackup or your disk started returning bad data.  I'll reopen if anyone else can reproduce or experiences this.
