### ISSUE TITLE
Play store description is not translatable

### ISSUE THREAD

**Issue by amire80** [WhisperSystems/Signal-Android#4754]
Hi,

I couldn't find where can translate the description of the app for Play store.

For example, if the app is viewed in the Play store in Hebrew, then the short description is shown in machine translation, which is incorrect, and makes it hardly possible to understand what the app is, because it auto-translates the word "Signal" to a Hebrew word that is unrelated to the actual app's name, and makes several grammatical mistakes. That's how machine translations usually are.

The long description with a list of features is shown in English, without any translation.

The solution is to let the translators at Transifex translate these descriptions. That's how it's done for the Wikipedia app, for example, and it works well.

**Comment by moxie0** [comment]
Unfortunately it's too much work for us to maintain play store descriptions in different languages.  We did do it for German, just because such a large portion of the user base is there, but the way the play store works makes it extremely inconvenient for us (every update needs to have its change log written N times for the N different languages, etc) so we don't generally do it.

**Comment by RiseT** [comment]
@moxie0 Would it cause less inconveniences to integrate the remaining parts (title, subtitle, app description) - i. e. without the frequently changing change log - into Transifex?

**Comment by amire80** [comment]
Yes - the change log is not essential.

Even translating just the short main description would be great - it is short and it doesn't change very often.

**Comment by 2-4601** [comment]
I can confirm that many apps have everything else translated in Play Store except the light green area with recent updates.

Just searched and found out that some Android projects in Transifex have a Play Store resource. E.g. Chatsecure: https://www.transifex.com/guardianproject/chatsecureandroid/play-store/

**Comment by 2-4601** [comment]
Sorry if this is something you are already aware of but I found out that the _Google Play Developer API_ seems to support updating Play Store localizations. If I understood correctly this is a fairly recent addition (September 2014).

There are Java and Python libraries here:
https://developers.google.com/android-publisher/libraries

For example using the Python library updating the Play Store descriptions would look something like this for German:
```python
update(editId=edit_id,
       packageName=package_name,
       language='de-DE',
       body={'title': 'Signal – Sicherer Messenger',
             'shortDescription': 'Privatsphäre und Datenschutz sind möglich, und mit Signal wird dies auch endlich einfach.',
             'fullDescription': 'Mit Signal können Sie kostenlos telefonieren, in Echtzeit Nachrichten austauschen und...'})
```
