### ISSUE TITLE
Can't send voice messages

### ISSUE THREAD

**Issue by bartz1** [WhisperSystems/Signal-Android#4761]
With 3.5 I remember being able to send voice messages. Then with 3.5.1 this feature disappeared. I went through the commits and saw that it has been disabled due to problems with the iOS version. However, aren't those problems fixed with the new format for audio messages? Or what issues are there left to fix?

**Comment by RiseT** [comment]
The way I've understood this, voice messages in the iOS version haven't been implemented at all so far.

**Comment by bartz1** [comment]
That's a possibility, but then why is there an open PR saying "audio recording minor fixes"? https://github.com/WhisperSystems/Signal-iOS/pull/740 If someone's fixing it, it means it's there...right?

**Comment by RiseT** [comment]
*If someone's fixing it, it means it's there...right?*

There's some truth to this :smile:

**Comment by Dyras** [comment]
It's there, it's just deactivated while iOS plays ketchup.

**Comment by mawed** [comment]
This is followed in #3563.
So I suggest to close this here.

**Comment by RiseT** [comment]
@Dyras I know it's there on Android. The question has been if it's there on iOS.

**Comment by Dyras** [comment]
Nope it's not there on iOS yet.
https://github.com/WhisperSystems/Signal-iOS/issues/230

**Comment by bartz1** [comment]
Then I'd update my question to: when are they hiring a new iOS developer? Lol it's kind of useless to have people work on the android app if ios gets in the way like this... this app will never improve with new features if development is dead on one of the only two platforms it exists on.. I can see why everyone else here was moving to telegram, I'll switch too. Closing this.

**Comment by moxie0** [comment]
@bartz1 cool see ya
