### ISSUE TITLE
Pictures taken directly in the app seems to be darker/tinted blue on my phone

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/Signal-Android#4762]
Yeah, I know what you're thinking. You're thinking "Are you sure it's not the light is different or something like that?" and my response to that is YES. I am sure. I've taken pictures back and forth, up and down, trying to make them look as similar to each other as I possibly can, yet somehow the pictures taken in the app ALWAYS ends up being darker. It's as if a layer of blue has been added on it.

This only happens when using the front camera. Pictures taken with the back camera are always identical.

Log of a picture taken with the camera, in the attachments drawer.
https://gist.github.com/anonymous/0aa96b2ee4a46ab55212

Log of a picture taken with the quick capture in app thingy
https://gist.github.com/anonymous/22329ca762cb287838dc

Can anyone else try this and see if they have the same results? I'm going to try it with my Galaxy Nexus now.

Just say the word and I'll email you two pictures of myself so that you can see normal me and blue me side by side.

Edit: Same thing on my stock Galaxy Nexus. The pictures are definitely darker in app, compared to the "real" camera.

**Comment by heyimgay** [comment]
Can you add two example pictures to help debug the issue?

**Comment by Dyras** [comment]
I'm not super fond of posting pictures of myself online, that's why I wrote that if Moxie/McGinty wants, I can email it to them. But sure, I can take two pictures without me in it.

**Comment by agrajaghh** [comment]
I couldn't reproduce this with my Nexus 4. I guess this depends on the camera app. Could you check the options of your system camera app, maybe there are some brightness options?

btw, I tried to take reproducable pictures without my face by placing the phone on the desk. So I'm getting two identical pictures of the ceiling...

**Comment by Dyras** [comment]
Interestingly enough, I wasn't able to reproduce this every time, which is why I think it's something in my room causing it. It was really obvious when I took a picture of myself, which is why I used those pictures as an example. You might very well be right about the system camera settings. I'll check it out after I'm done with this fun and exciting essay I'm writing.

**Comment by 2-4601** [comment]
Tried this with Nexus 4 and Huawei U8800. I get very similar looking pictures with similar colors.

Maybe it's your aura?

**Comment by Dyras** [comment]
Since this is probably either my aura or my usual good luck with technology I think I'll close this..
