### ISSUE TITLE
Allow setting status (& messages) / availability.

### ISSUE THREAD

**Issue by Evi1M4chine** [WhisperSystems/Signal-Android#4766]
I’m surprised this is not built-in, and that I could not even find an issue for this.

This is of course not about being “online”, which makes no sense for mobile devices anyway.

**The goal is to be able to tell people (e.g. the ones you love) if you’re currently available to be called, or e.g. sleeping, or don’t want to be disturbed.**
ICQ set the bar high on that back in the days. And the only improvement since then was the ability to write custom status messages. Although this has been misimplemented sometimes, by leaving away the generic status (like “DND” or “N/A”), requiring the other side to read the status message, and making it impossible to automatically sort the contact list by the availability. (E.g. to see who’s currently awake and maybe willing to go out.)

It also probably is very easy to implement.
1. Implement special `status` packets/messages, containing an `Enum` (`Int`) for the generic status, and a `String` for the status message text.
2. Allow setting a (only locally stored) status by tapping the Signal icon in the contact list, and choosing an option from the appearing dropdown. Classic “Away”, “N/A”, “Busy”, “DnD” and modern “Sleeping”, “At Home”, “At Work” “Outside”, “[No Status]” and maybe “At … [GPS]” are a good basic set. The last option should always be “Add new status…”, and open a dialog to set the generic status (which picks the icon too) and type in a custom status message.
3. Allow setting who is allowed to see the status in the global/group/person settings. (Global default, group default, person.) Ask for the global default setting, the first time a status is set.
4. Allow requesting a `status` from other people on the contact list.
5. Optional: Allow actively sending `status` to a group or person. (Which should behave exactly like a `/me` message… e.g. be shown in the message history too.)
5. Display any received statuses in the contact list, with the icon of the user changing accordingly, and the status text appearing below the user name. Optional: Make it possible to switch off requesting statuses e.g. for bandwidth reasons.

Because everything is private and encrypted and user-configured, nobody risks being stalked, unless he actively wants to. (E.g. to tell your partner or your parents.)

**Comment by moxie0** [comment]
Thanks but we're not going to do this
