### ISSUE TITLE
Allow setting arbitrary colors for contacts.

### ISSUE THREAD

**Issue by Evi1M4chine** [WhisperSystems/Signal-Android#4767]
Currently, there only is a list. And it contains a very weird, limited set of colors too. This makes no sense and is patronizing.

Replace the list by a normal H/S/B color picker. Simple. Freedom.

**Comment by mawed** [comment]
Related to #4459.
The developer will surely close this ticket, as they are cool with it.

**Comment by moxie0** [comment]
Thanks but we're not going to do this.
