### ISSUE TITLE
Allow /me messages, like in IRC and unmodified XMPP.

### ISSUE THREAD

**Issue by Evi1M4chine** [WhisperSystems/Signal-Android#4768]
This rather useful feature has a long-standing tradition, and is popular in all kinds of chats. It is part of the XMPP standard, afaik. So Signal should of course implement it, as soon as there is time.

**Comment by Dyras** [comment]
Sorry but I just don't see the point. It feels like there are far more important features to add before adding features that barely no one will ever use.

**Comment by McLoo** [comment]
besides that you can already send message to yourself
Just enter your number for a new conversation or put yourself into you contacts a pick that...

**Comment by Evi1M4chine** [comment]
@Dyras: Nobody said it should be done _now_. 
Also, you hardly qualify for determining what “barely no one will ever use”. And I hope this is not Apple, so we’re not aiming for the most crippled, dumbest common denominator.

@McLoo: That’s not what /me does *at all*.

Does nobody of you use IRC?? Jeez…

**Comment by moxie0** [comment]
Thanks but we're not going to do this.  @Evi1M4chine the mailing list is probably a better place to be throwing out ideas, this is an issue tracker that represents work to be done.
