### ISSUE TITLE
Swipe left to unarchive

### ISSUE THREAD

**Issue by merkste** [WhisperSystems/Signal-Android#4781]
Playing around with the new archive feature, I found it highly unintuitive to unarchive using the same gesture as to archive. It appears more natural to swipe the opposite direction when unarchiving. Additionally the arrow to leave the archive points to the left, too. It appears suggestive. However, this might also be very well my own based perception.

PS: I thought there was already an issue created for this idea, but I was unable to find it. Sorry, if this is indeed a duplicate.

**Comment by agrajaghh** [comment]
take a look at this comment:
https://github.com/WhisperSystems/Signal-Android/pull/4698#issuecomment-159650206

**Comment by merkste** [comment]
Thanks, that's the one I've read. However, I'd like to argue against a  
swipe-action to delete conversations. It is far to likely to accidentally  
delete something.

Am .12.2015, 09:52 Uhr, schrieb agrajaghh <notifications@github.com>:

**Comment by heyimgay** [comment]
One solution to this is only adding the swipe right to delete to the archives list.

**Comment by moxie0** [comment]
That's why we'll have undo support. We'll see, for now we're leaving unarchive as a right swipe.

**Comment by alexreinking** [comment]
I accidentally archived a conversation and missed the undo button since it is placed immediately above the back button on Android. I was pretty panicked as I searched for how to undo that action.

This is a useful feature but a frankly terrible interface. I hate it in the Gmail app, too. The archived conversations view should at least be accessible from the main menu.

**Comment by alan-signal** [comment]
@alexreinking Please use the community forum for feature requests https://community.signalusers.org/ there may already be a thread about this.
