### ISSUE TITLE
Removing call entries from a conversation should be possible

### ISSUE THREAD

**Issue by swltr** [WhisperSystems/Signal-Android#4783]
I can remove a complete conversation, including text messages and entries for accepted/missed calls in it. I can also remove single text messages from a conversation. However, I cannot remove just (single or all) call entries from a conversation, which I would have expected to be possible.

I rarely delete a complete conversation, as there usually are some messages in it that I still want to keep. This currently implies that I also have to keep all call entries, which is slightly annoying, as they contain practically no information.

In my opinion, to make removing call entries possible, there should be at least one of the following features:

1. I should be able to select and remove call entries just like text messages.
1. I should be able to "lock" text messages so they are not removed when I delete the conversation.

(This is currently on Signal 3.6.1 on Android.)

**Comment by mawed** [comment]
duplicate of #4190.

**Comment by swltr** [comment]
@mawed Thanks, I searched but somehow missed that.
