### ISSUE TITLE
Screen Shoots

### ISSUE THREAD

**Issue by ybentlili** [WhisperSystems/Signal-Android#4785]
Hello, 
I need to make screen shoot from application but I can't ? 
Application protected by DRM. 

any help please ?

**Comment by heyimgay** [comment]
There's a preference for this. Can you close this issue please.

**Comment by ybentlili** [comment]
where I can find this preference ?

**Comment by 2-4601** [comment]
This issue tracker is used for bugs.
You can submit support requests at http://support.whispersystems.org

http://support.whispersystems.org/hc/en-us/articles/213191027-Can-I-take-a-screenshot-

**Comment by ybentlili** [comment]
ok thank you.
