### ISSUE TITLE
UI issues with message composition in portrait & landscape

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/Signal-Android#4786]
(See https://github.com/WhisperSystems/Signal-Android/pull/4755 for initial discussion)

**Issues in portrait & landscape:**
- The current compose hint is "Send Signal message" (or "Send unsecured SMS", "Send unsecured MMS"), which doesn't make much sense. After tapping on the compose field, the user types the message and doesn't send it.

**Issues in landscape:**
- Same problem as in portrait with the compose hint
- Additionally, the Send button uses the very same strings as the compose hint (here it makes sense). But these rather long strings make that button very wide, taking far too much screen estate, i. e. leaving not much room for the actual message content.

**Suggested solution:**
- Separate the compose hint strings from the button text strings
- Use appropriate wording in the compose hint strings
- Wrap the button text strings into 3 lines, so the button gets horizontally smaller and vertically larger, leading to more screen estate for the message content on the left side of the button. New lines ("\n") are already used by some currently existing Signal strings, so shouldn't be anything new for translators.

**Suggested Compose Hint strings (portrait & landscape):**
- Type Signal message
- Type unsecured SMS
- Type unsecured MMS

**Suggested Button Text strings (landscape):**
- Send\nSignal\nmessage
- Send\nunsecured\nSMS
- Send\nunsecured\nMMS

Ideally, the Send button in landscape should be colored signal blue for encrypted and gray for unencrypted messages. But I understand this is not feasible right now.

**Comment by jeremymasters** [comment]
@RiseT in line with thinking about a text redo, that whole area seems a little in need of standardization...There is a text box, a tiny camera icon and a larger attachment icon.  Should there be a set of buttons that indicate I want to A, add some text, B, add a picture or C add some other attachment?  Then all of those buttons, could use a similar set of perhaps material icons?

If this is too far past your inclination for this particular undertaking, I understand, but I've been thinking this for awhile now actually.

**Comment by RiseT** [comment]
@jeremymasters I agree that there's certainly more room for improvement in that area - especially for landscape mode. I'm currently just trying to point out obvious improvements that can be done without much work or an extensive redesign.

**Comment by RiseT** [comment]
Potentially fixed by https://github.com/WhisperSystems/Signal-Android/commit/fe1cc3d6d1906b3503309b82aaa68c581e929a80
