### ISSUE TITLE
Binary blob in repository

### ISSUE THREAD

**Issue by hlieberman** [WhisperSystems/Signal-Android#4789]
libs/{armeabi,armeabi-v7a,x86}/libredphone-audio.so is being shipped in the repository as a pre-compiled binary.

I assume this is a library with source somewhere else in the tree?  If so, it should be removed and added to gitignore.  If it's sourceless, then information should be there for where it comes from and how to rebuild it.

**Comment by moxie0** [comment]
gradle support isn't there yet, the source is in the jni package, you can rebuild it yourself if you'd like
