### ISSUE TITLE
Cannot communicate with Signal server on Shaw Wifi

### ISSUE THREAD

**Issue by lukebarone** [WhisperSystems/Signal-Android#4792]
Phone: OnePlus Two with CyanogenMod 12.1
Signal version: 3.6.1
Issue: When I am connected to a Wifi network through Shaw (home, wifi hot spots, etc), I cannot send or receive any messages securely. I also cannot un-register or re-register my phone number until I switch to Mobile Data. On Telus Wifi, it works fine. I can still send un-encrypted SMS messages to other contacts. Tonight, a family member that is also on Signal had issues sending and receiving on Shaw.

I have contacted Support, but this seems like a big problem. [Debug Log](https://gist.github.com/anonymous/f78a2bbbf88fff8951c5) shows lots of errors about the certificates; for example, line 21: `W/OkHttpClientWrapper(16616): javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`. This error repeats a few times.
The date and time on my device is correct, as is the time zone. I do not have any user-installed root certificates.

**Comment by moxie0** [comment]
Looks like your connection is being MITMd by your service provider, or you're dealing with a captive portal.  You can use the openssl command line to see what certificate is being presented to you, but either way it looks like Signal is doing what it should be doing (not accepting an invalid cert).

**Comment by lukebarone** [comment]
For the sake of completeness, and for other Shaw customers...

I solved this issue by changing the DNS servers. I used Shaw's by default, and it kept causing issues. I forced my home router (that I have control over) to use Google's Public DNS Servers (8.8.8.8 and 8.8.4.4), and messages could send and be received. I decided that I'll just use a VPN connection if I'm in someone else's Shaw network.
