### ISSUE TITLE
Unreadable text in "link this device?" dialogue in dark theme

### ISSUE THREAD

**Issue by djoris** [WhisperSystems/Signal-Android#4795]
Replicate:
* Use a Samsung Galaxy S3 or S6 running Android 4.3/5.1 respectively.
* Set dark theme (Settings; Appearance; Theme; Dark)
* Scan barcode (in Signal-Desktop, show QR-code. In Signal-Android, choose Settings; Devices; +; scan QR code)

The resulting screen with title '_Manage linked devices_' has text that is barely or not readable while it is light grey on a white background. Only the text '_Link device_' is blue on white.

In the  light theme, the text is black on white background an easily readable.

Attached is a 'screenshot' made with a camera pointed at the screen of a Galaxy S6.
!['screenshot' with camera](https://cloud.githubusercontent.com/assets/790925/11574981/0bc467b0-9a0f-11e5-86e0-7273bdaa055a.jpg)

**Comment by McLoo** [comment]
Duplicate:
-  #4611 ;)
