### ISSUE TITLE
Signal does not play notification tone as set in settings (Android), just beeps

### ISSUE THREAD

**Issue by cb474** [WhisperSystems/Signal-Android#4796]
After a recent update to Signal, the app no longer plays the notification tone I have set in the Signal settings, when I receive a new message.

I simply have Signal set to my default notification tone for all conversations. But instead of playing my default notification tone, I get an old fashioned PC style system beep.

Here's the debug log:

https://gist.github.com/anonymous/45d13a4bbaff57f96f2b

**Comment by moxie0** [comment]
Nothing actionable in this debug log, and cant' reproduce. I'd guess it's a CM issue.

**Comment by cb474** [comment]
Other apps sound the correct notification tone. If it was a CM issue wouldn't the problem appear across all apps?
