### ISSUE TITLE
sharing/forwarding not working without current thread

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#4797]
I have noticed with Signal 3.6.1 that sometimes things I want to share won't of I don't have an ongoing thread with the I want it to be shared. 
1. Launch Chrome browser
2. A.  Find picture of Princess Bride baby  https://thechive.files.wordpress.com/2015/12/daily-afternoon-randomness-49-photos-301.jpg?quality=94&strip=info&w=600 and hit share 
2.B. OR try to forward any text message to someone 
4. Share with contact with whom you don't have a thread already by using the plus sign and searching for contact and selecting from the list. 
5. No text in the text area! Inconceivable! 

Nothing fancy with my phone. Verizon Galaxy S5 stock 5.0 ROM

**Comment by jeremymasters** [comment]
https://gist.github.com/f477fa4808d45565af43

**Comment by heyimgay** [comment]
Can be closed (#4870 fixed this)

**Comment by 2-4601** [comment]
Killed by ec53c6ab0471a8fa768b9e6e5142e135e376d21a
