### ISSUE TITLE
Conversation list's delivery status icon shows only one checkmark until conversation opened 

### ISSUE THREAD

**Issue by unrulygnu** [WhisperSystems/Signal-Android#4799]
Seems to affect only conversations with the last message sent before updating to 3.7.0.  

After updating to 3.7.0, sending a message then quickly tapping Back before the conversation's delivery status icon is updated works as expected:  the conversation list's delivery status icon is updated in realtime.

**Steps to reproduce**

1. Launch Signal / navigate to the conversation list
2. Find pre-3.7.0 update Signal conversation with only one checkmark
3. Tap conversation
4. If the last message indeed has only one checkmark, repeat steps 1 through 3
5. Observe two checkmarks
6. Tap back to return to the conversation list
7. Behold the updated delivery status icon with two checkmarks

Device info: Nexus 5, stock Android 6.0 MRA58K, Signal 3.7.0 (b99c4e3)

App state: Signal registered, SMS enabled, default SMS app

**Comment by haffenloher** [comment]
Yep, I didn't include a migration for setting the status of old conversations because I didn't think it was necessary (mea culpa). If we want, we could still add something like this to `DatabaseFactory` before 3.7 comes out of beta:

```java
Cursor                cursor = db.query("thread", null, null, null, null, null, null);
ThreadDatabase.Reader reader = thread.readerFor(cursor, masterCipher);
ThreadRecord          record = reader.getNext();

while (record != null) {
  if (record.isOutgoing()) thread.update(record.getId());
  record = reader.getNext();
}
```

I can't test this now, but if such a migration is wanted I could set up a PR later.

**Comment by moxie0** [comment]
Yeah, we should probably do something.  Either not display delivery status for old messages, or migrate the status.

**Comment by unrulygnu** [comment]
I neglected to mention, thanks for the awesome feature!  No culpas. :+1:

**Comment by McLoo** [comment]
On my test device, the info stuck in "Decrypting please wait" for one convo after updating, until I entered and exited the conversation.

Received messages that were not processed until after I opened the update.

(Could also be due to wild testing...)

**Comment by jeremymasters** [comment]
I had this same thing happen with conversations that did have two checkmarks in 3.6.1. In fact, none showed two check marks after the update, even though they had two in 3.6.1. Entering and leaving each conversation fixed it though.

**Comment by McLoo** [comment]
Maybe it's just me, but I got a couple of groups that are shown as pending (the 3 happy dots).  And they aren't after entering and exiting the group convo. 
(1 left for investigation now...) 

![_20151212_113245](https://cloud.githubusercontent.com/assets/5326916/11761484/db461f86-a0c4-11e5-956d-bafdbf757e76.JPG)

![screenshot_2015-12-12-11-31-10](https://cloud.githubusercontent.com/assets/5326916/11761486/e707c84c-a0c4-11e5-8253-21267e0ffd87.png)

![_20151212_113159](https://cloud.githubusercontent.com/assets/5326916/11761487/f721923a-a0c4-11e5-9164-9ae233ab0a3c.JPG)

**Comment by haffenloher** [comment]
@McLoo Damn, I should have added an update to the `type` field to the migration, just to be sure :grin: 
As far as I can tell, this can only happen if you wrote a message, left the conversation while the message was still pending and never entered it again until the update.
