### ISSUE TITLE
Signal-Desktop QR code not recognized

### ISSUE THREAD

**Issue by HansHerbert** [WhisperSystems/Signal-Android#4804]
I gained beta access, but I have trouble with the integrated scanner. There is no way to make it recognizing the qr code. I was so desperate that I printed out the code to scan it, but this led to the same results. 

Signal version: 3.6.1
Android version: 5.1.1 (Cyanogenmod 12.1)
Device: Samsung Galaxy S2 ("i9100")

[signal.log.txt](https://github.com/WhisperSystems/Signal-Android/files/52178/signal.log.txt)

**Comment by 2-4601** [comment]
Camera focus issue? #4637

**Comment by HansHerbert** [comment]
Sorry, didn't saw this issue. That's the same problem I experienced

**Comment by ndevln** [comment]
+1 also on Galaxy S2 and CM12
