### ISSUE TITLE
Don't crop image thumbnails

### ISSUE THREAD

**Issue by piratenpanda** [WhisperSystems/Signal-Android#4806]
At the moment (Signal 3.7) thumbnails for sent images are still cropped versions instead of resized versions of the images. This changes the aspect ratio of the picture and zooms to some "random" area inside the picture. Would love to see the thumbnails rather have a maximum width with fixed aspect ratio. Would make them look so much better.

**Comment by moxie0** [comment]
You're referring to the thumbnails?

**Comment by piratenpanda** [comment]
Yes, sorry if that wasn't clear

**Comment by moxie0** [comment]
ah, cool, that's intentional, thanks though

**Comment by piratenpanda** [comment]
Sorry to be a PITA but what's the reasoning for cropping and destroying the intentions of the photographers choice of layout on the pic and not to go with a fixed width while keeping the aspect ratio fixed? Maybe there are some corner cases like very huge panoramas where this would look bad but like 90% of the sent images would look better, at least to me.
