### ISSUE TITLE
Device QR gets scanned even if not in cam preview

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#4807]
If the QR code comes into view from below (move the cam downwards)
at some point, when the QR code is still not visible, the scan gets perform.

Seems the scanner works in full screen, whereas only the half screen is shown to the user.

(Pretty sure this could be described better, but my brain lacks vocabulary right now)

**Comment by moxie0** [comment]
You're right, but apparently that's just how it has to be.
