### ISSUE TITLE
Detailled preview in recent apps even when screen security is turned on

### ISSUE THREAD

**Issue by vanitasvitae** [WhisperSystems/Signal-Android#4822]
Im on CopperheadOS (hardened Android based on Cyanogenmod 12.1).
When I open the overview of recent apps, I can clearly read my recent conversation.
I can't read it when the app is locked thogh. But shouldn't the preview be disabled at all when screen security is on? That would make more sense in my opinion.

**Comment by 2-4601** [comment]
> But shouldn't the preview be disabled at all [times?] when screen security is on?

It is disabled for me, i.e. can't reproduce with Signal 3.7.0
* Nexus 4, stock Android 5.1.1
* Huawei U8800, Android 4.0.4

**Comment by FeuRenard** [comment]
I can confirm this issue. I use Cyanogenmod 11 and screen security is turned on. I am also able to make screenshots of the app.
Could this issue correlate with rooting a phone?

**Comment by vanitasvitae** [comment]
Maybe its related to cyanogenmod. Afaik the OS is responsible for implementing the flag. Maybe they did something different than AOSP?

**Comment by 2-4601** [comment]
AOSP also has a bug in certain situations with the flag but I don't think @vanitasvitae meant this: #3172?

**Comment by vanitasvitae** [comment]
Oh I just realized that it may be #3172. Same behaviour. When I start the apl and go to recent apps, the screenshot is covered white. When I open the app, press powerbutton to turn screen off and back on and then go to recent apps, the screenshot os visible.

**Comment by vanitasvitae** [comment]
Sorry for the typos. Im writing from my phone.

**Comment by 2-4601** [comment]
Closing as duplicate of #3172.
