### ISSUE TITLE
Message status in conversation overview not always up to date

### ISSUE THREAD

**Issue by Norbert80** [WhisperSystems/Signal-Android#4824]
Since Signal 3.7.0 message delivered/received status in displayed also in the conversation overview screen.
However I sometimes notice that a (old) message there only displays one check mark. If I enter the conversation I see that the last message has two check marks. If I then go back to the conversation overview there are also two check marks.

I also see this with SMS.

Found with Signal 3.7.0.

**Comment by wizardofid** [comment]
Probably duplicate of #4799.

**Comment by Norbert80** [comment]
Can confirm that this issue is a duplicate of #4799 because only conversations that have been inherited from builds older than 3.7.0 are affected.
