### ISSUE TITLE
Should delivery failed messages automatically send again if data signal gets better?

### ISSUE THREAD

**Issue by christianfl** [WhisperSystems/Signal-Android#4825]
If you try to send a message in Signal but you have a very poor data signal, Signal send you a notification that your message could not be delivered. After that, the user can manually select something like "Try sending again". Wouldn't it be a better way to automatically send the message again if the signal is back (like the other messenger apps, e.g. Whatsapp)?

**Comment by 2-4601** [comment]
There are already many issues about this. E.g. see #2384
