### ISSUE TITLE
receipt status incmplete for messages synced from desktop client

### ISSUE THREAD

**Issue by oholika** [WhisperSystems/Signal-Android#4826]
For messages synced from desktop client only one arrow appears on android client (on the desktop client both appear). Vice versa this can not be reproduced.

Android 5.1.1 ; Nexus 4 ; Signal 3.7.0
Desktop client 0.1.3

**Comment by FeuRenard** [comment]
For me it also happens vice versa. But I can not specifically reproduce it. (both directions)

**Comment by 2-4601** [comment]
atoned by 49f60971bde2f3e4fbc8327039c88df4e7b44a60

**Comment by AlfonsoMuskedunder** [comment]
I think this is still a thing sometimes... I just sent a group message via Desktop (0.3.2) which got delivered, but Android (3.13.1) does not indicate delivery.
Just in case someone would like to have a look:
Desktop's log: https://gist.github.com/anonymous/e6a2acf5bd70ffd90c85
Android's log: https://gist.github.com/anonymous/d8259293d5148319817f

**Comment by 2-4601** [comment]
True, groups still have that bug, there's an issue for it #4924
