### ISSUE TITLE
Signal does open itself every time i hit send on the quick reply notification after signal update

### ISSUE THREAD

**Issue by psyfx** [WhisperSystems/Signal-Android#4831]
Since the last update the quick reply notification is not working correctly. Before you could answer a message from within another app via the drop down quick reply.
Since the last update every time i hit send in the drop down reply, signal opens the whole conversation in full screen after 1-2 second pause. This is super annoying, especially since this feature worked flawlessly before.

Signal 3.6.1 on Galaxy S5 Android 5.0

debug log:
https://gist.github.com/046313199cc0ca251291

**Comment by Dyras** [comment]
Happens for me quite rarely on Moto G3. I thought it was just me being clumsy, but now when you mention it it's never done this before.

**Comment by psyfx** [comment]
Any update on this? Bug still present on 3.7.2.

**Comment by moxie0** [comment]
@psyfx sounds like an annoying bug, but please do not post in issues unless you have new information to add. stuff like "+1" or "any update?" just clutters our inboxes and makes it less likely that we have time to work on this

**Comment by psyfx** [comment]
Issue is fixed with the 3.8.1 update. Thx
I'll close this one.

**Comment by h4waii** [comment]
Can this be re-opened? Happening for me on the latest beta release on Play Store, 3.16, on Android 6.0.1.

**Comment by scoobford** [comment]
I agree with ghost. I think this issue should be reopened, as I'm having this bug as well on 3.31.4 and android 6.0. 

Debug log: https://gist.github.com/anonymous/238b6dd1d4a33166919d71633eccb6da
