### ISSUE TITLE
Leaks contact phone numbers to log

### ISSUE THREAD

**Issue by lorenzhs** [WhisperSystems/Signal-Android#4832]
`W/MessageRetrievalService(14346): Retrieved envelope! +49[REDACTED]`

The phone number is not my own.

https://github.com/WhisperSystems/Signal-Android/blob/d543c0b36e477a8d7be555de48399aa02a397803/src/org/thoughtcrime/securesms/service/MessageRetrievalService.java#L86

I think this should be avoided, no? Other log messages redact the phone number.

**Comment by lorenzhs** [comment]
See also https://github.com/WhisperSystems/libtextsecure-java/issues/18 which I filed at the other repo because the class that does the logging lives there.

**Comment by moxie0** [comment]
We filter these out in the debug logs we generate, but we have to emit them for debugging.
