### ISSUE TITLE
Can’t send SMS to phone numbers with brackets after upgrade to 3.3+

### ISSUE THREAD

**Issue by csnover** [WhisperSystems/Signal-Android#4833]
Messages (SMS, not MMS, not data) appear to be sent successfully in the UI but are never received by the contact after upgrading to any version later than 3.1.1. Messages from other contacts are still received, only sending is broken. Manually downgrading to 3.1.1 apk restores SMS sending functionality. Other SMS apps continue to work. Latest 3.6.1 release from Play Store is still broken. Disabling Signal messages in Advanced prefs does not fix the problem. Uninstalling and reinstalling does not fix the problem.

Device info: Samsung Galaxy S5 Dev Ed, stock Android 4.4.4, Signal 3.6.1
App state: Push registered, SMS Enabled, SMS deliver disabled, Wi-Fi Calling compatibility disabled (phone is not Wi-Fi Calling enabled), MMS Default settings, Media auto-download disabled

Log, starting Signal & sending SMS: https://gist.github.com/csnover/dd39624d381160536798

This may be related to the shortcode sending problem reported around the same time but I am *not* sending to shortcode contacts, these are full 10-digit (US) numbers.

**Comment by moxie0** [comment]
According to that log, we hand the SMS to the system, and the system reports that it has been sent. Doubtful there's anything else we can do.

**Comment by csnover** [comment]
I see in SmsSendJob there was a change to strip brackets from numbers between 3.1.1 and 3.3.0 using String.replaceAll. I don’t know why this would affect anything but it seems like the most obvious culprit. I’ll see if I can get a build on my phone without this code and see if it restores sending, or at least figure out what the recipient looks like before and after mangling.

**Comment by csnover** [comment]
I see in SmsSendJob there was a change to strip brackets from numbers between 3.1.1 and 3.3.0 using String.replaceAll. I don’t know why this would affect anything but it seems like the most obvious culprit. I’ll see if I can get a build on my phone without this code and see if it restores sending, or at least figure out what the recipient looks like before and after mangling. If an invalid-but-valid-looking recipient is being passed to the SMS system then it may happily accept it and just send the message into the wilderness.

**Comment by moxie0** [comment]
Does the number you're trying to send messages to have braces in it?

**Comment by csnover** [comment]
Yes, it does. All the numbers in the phone do because TouchWiz (or who knows what) formats them that way. After reviewing the issue related to that change, I thought I should try sending to a number with no brackets, and those numbers work *fine*, it’s only the ones with brackets that are broken.

So, guessing, the number starts as “(xxx) xxx-xxxx” and then ends up as “xxx xxx-xxxx”. This is apparently no good—probably elsewhere in the system there is a check that looks for those brackets to normalise the number, and now that they don’t exist, it doesn’t get properly normalised. I would think that stripping should be using `PhoneNumberUtils.normalizeNumber` or the commented out `PhoneNumberUtils.stripSeparators`.

**Comment by moxie0** [comment]
Ugh, I knew that PR would cause problems for someone.  Problem is that it might not be a phone number, so we can't normalize it, but I think we can strip both spaces and parens.

**Comment by csnover** [comment]
Researching the PhoneNumberUtils calls, I ran across some code in CyanogenMod that deals with non-phone-number contact info. It seems to have existed for a few years now, so might be useful as a template for fixing this issue in a way that doesn’t break anyone else. https://github.com/CyanogenMod/android_packages_apps_Mms/blob/cm-12.0/src/com/android/mms/data/Contact.java#L786-L842

**Comment by csnover** [comment]
371ef3c does not fix the problem, now the numbers are xxxxxx-xxxx which is still invalid to the network.
