### ISSUE TITLE
unable to place a call

### ISSUE THREAD

**Issue by qasimchadhar** [WhisperSystems/Signal-Android#4834]
Unable to place a call to other Android/iOS Signal users. They can't call me either. I've tried both cell and wireless networks. Shows a missed call though. Basically, when placing a call, it keeps ringing and then says call disconnected - even though the other person didn't even see the call. After a minute, Signal app shows call missed. Debug log at https://gist.github.com/3e4a8d45905f96c08254

Thank.

**Comment by riyapenn** [comment]
Check out support page: http://support.whispersystems.org/hc/en-us/articles/213697218-Which-TCP-UDP-ports-need-to-be-available- and if needed, reference this issue when you contact support@whispersystems.org

**Comment by qasimchadhar** [comment]
Thanks @riyapenn. I"ll close the issue because this is the resolution.
