### ISSUE TITLE
Integration with Blackberry Hub on PRIV

### ISSUE THREAD

**Issue by fasihahmed** [WhisperSystems/Signal-Android#4838]
Hi,

As Blackberry has now dipped its toes into the Android eco-system, I would love this app which I use for all my communications (to the extent that I disabled googles messenger app on my device) to integrate the message sending with Blackberry Hub.

The SMS messages do not appear in the Hub after I imported all the text messages to Signal App.

Regards,
Fasih.

**Comment by moxie0** [comment]
Thanks but we're not going to do this, we're developing for the stock Android ecosystem here

**Comment by fasihahmed** [comment]
Really disappointed here.

**Comment by brianbancroft** [comment]
@fasihahmed You can relieve your disappointment: It's now supported. https://play.google.com/store/apps/details?id=com.blackberry.hub&hl=en
