### ISSUE TITLE
When tapping on a contact picture a toast message "No apps for viewing this contact available" (Translation from German) appears and contact details are not displayed

### ISSUE THREAD

**Issue by eknuf** [WhisperSystems/Signal-Android#4842]
Hi,

when tapping a contact picutre in the conversation list i get the toast message "Keine Apps zum Anzeigen dieses Kontakts verfügbar" which translates to "No apps for viewing this contact available.".

Expected result: I contact selected should be opened in the address book or the information should somehow be displayed.

Maybe this has something to do with my phone having a custom (vendor supplied) contacts app.

I am running Signal 3.7.1 on a Honor 7 Stock (Android 5.0.2)

Please let me know if I can be of further help.

**Comment by x2k13** [comment]
I can confirm this issue with Signal 3.7.2
Device: Honor 6, Android 5.1.1, EMUI 3.1

**Comment by eknuf** [comment]
Okay this seems to be a Hauwei/Honor thing, i got the update to Marshmallow yesterday and now it works as expected. Sorry for the noise.

**Comment by x2k13** [comment]
Well, I don't have Marshmallow so the issue still persists!
@eknuf:
Issues should be closed only if all people having the issue confirm it is fixed...
