### ISSUE TITLE
Change 'TextSecurePlaintextBackup.xml' to 'SignalPlaintextBackup.xml'

### ISSUE THREAD

**Issue by siccovansas** [WhisperSystems/Signal-Android#4849]
This is a small change, but it should improve user experience. I can imagine that it is confusing, especially for new users who don't know that Signal was called TextSecure before, to find out that your Signal plaintext backups are saved to a file called `TextSecurePlaintextBackup.xml`. Looking at the code, `PlaintextBackupImporter.java ` should probably keep looking for `TextSecurePlaintextBackup.xml` (besides the new `SignalPlaintextBackup.xml`) for backward compatibility.

**Comment by heyimgay** [comment]
#3054 should change this

**Comment by cascheberg** [comment]
Has been fixed.
