### ISSUE TITLE
Missing text when forwarding SMS to new number

### ISSUE THREAD

**Issue by OlgerDiekstra** [WhisperSystems/Signal-Android#4850]
Samsung S4 mini running Carbon 4.4.4 (custom rom)
Signal Version: 3.6.1

Steps:
1. Highlight text to forward
2. Choose forward message
3. Tap +
4. Enter number (which has not been messaged before and does not show up in "Share with" list)
5. conversation thread to new number does not contain forwarded text

**Comment by jeremymasters** [comment]
Dupe of #4797

**Comment by McLoo** [comment]
Closing as dupe of #4797
