### ISSUE TITLE
Feature Request: Nicknames in groups

### ISSUE THREAD

**Issue by AsamK** [WhisperSystems/Signal-Android#4852]
When joining a new group it's sometimes hard to find out which people belong to which phone number. Asking everyone in the group who they are is tedious.
It would be nice to be able to set a nickname in the app, that's sent in an extra field in each group message. The receiving clients could show this nickname if the number has no associated contact. Setting a nickname would of course be optional and the nickname is only sent in group messages.

Other messengers support this as well and it's very useful to find out who the person is that just sent a message in a group.

**Comment by moxie0** [comment]
In 4.10.0

**Comment by jeanlucthumm** [comment]
Is this feature available on Android 5.3.7? There does not seem to be an option for it in group chats.

**Comment by greyson-signal** [comment]
I'm assuming that back in 2017, Moxie was referring to the addition of Profile Names, which was a new feature at the time. There are no immediate plans for setting custom nicknames in-app at the moment. If you wish to get that, I recommend adding people to your system contacts with the desired name. I agree it'd be cool to have more in-app control over names in the future, though. Feel free to discuss it on the forum. Thanks!

**Comment by mmione** [comment]
Signal lacking this feature is one of the only things preventing my friends and I from moving our large group chat to Signal off of Facebook Messenger. Signal is just so much better in every other way

**Comment by mattBrzezinski** [comment]
...my [post](https://community.signalusers.org/t/nicknames-in-group-chats/36730/5) on Discourse was flagged as inappropriate. So I'll come back here to 👍 this thread.

![Screen Shot 2021-09-30 at 12 25 17 PM](https://user-images.githubusercontent.com/4356074/135502466-a582212d-d8cc-44c6-aee4-4f21a79d9c28.png)

**Comment by Donoghue-Dennis** [comment]
This is definitely a feature I'd love to see. In other group message clients, my friends and I would have a rotating theme, with changes to the chat colors, nicknames, and the like Icon. Current events, holidays, other topical themes.

We're moved over to signal, and we'd love to be able to continue that tradition.

**Comment by MartinL0815** [comment]
Dear developers,

I'm using Signal for example to manage the communication in a soccer club for soccer kids teams.
The parents have often more than one child in several teams, so they are in several Signal-groups.
To have nicknames per group would really ease the communication, the recognition of the child-parent-relation, if the parents can give themselves a nickname, that refers to the current group, soccer-team, to the child in the soccer-team.

To save contacts in the local contacts and name them as needed is not only a lot of work, but is very limited in its possibilities, if I have parents in multiple Signal-groups!
And if I introduce someone new to the Signal-group, this one doesn't have the "name support" and needs to set it up in his local phone contacts as well.

That's not the right way!

Please consider after all these years to give group specific nicknames a chance and an implementation!

**Comment by PenguinPaul** [comment]
Would like to voice support for per-group nicknames as well.

**Comment by aleksanb** [comment]
I would like to see this feature implemented per-group per user as facebook messenger does it (all admins can change nicknames, nicknames are visible to all in the chat and unique to that chat).

I've just migrated a huge group chat from facebook messenger and we extensively use the nickname feature for fun. It's one of the few features i miss from messenger that would make the migration flawless!

I have multiple other groups where we would immediately embrace such a shardd nickname per user per group feature as well.

**Comment by Torsteinws** [comment]
I suggest people give an upvote and voice their use case at [this forum thread](https://community.signalusers.org/t/in-group-nicknames-that-everyone-can-edit/60251/4).

The devs are more likely to implement feature requests that have lots of activity on the forum. 
GitHub issues are mostly used for tracking bugs I believe.
