### ISSUE TITLE
No connection to Server

### ISSUE THREAD

**Issue by luxora** [WhisperSystems/Signal-Android#4856]
Hi Signal team,
I tried to solve this problem via Support Ticket, but I'm still hanging without Signal.
Hope Someone could help!
luxora

Your request (1508) has been updated. To add additional comments, reply to this email.

Dec 10, 10:10

Hi Masha,
so my Playstore is up to date.
I tried to connect via WIFI and via mobile Network.
Reinstalled Gapps, Playstore and so on.
Signal breaks at the first point, because it gets no connection to the
Server.

1. Is your Google account on your phone and Play Store email up to
date? Check that the email address is correct and current. ->
updated right now, installed all that Google Voice bullshit, that
Signal requires since the latest version...

2. Have you re-installed Google Play services/GApps
<https://play.google.com/store/apps/details?id=com.google.android.gms>?->
tried that, too.

3. Do you have a custom ROM? You may need to flash and install GApps.
Check out CM's wiki on Google Apps
<https://wiki.cyanogenmod.org/w/Google_Apps>.
-> normal Oppo Color OS for R7.

Error message this time was: No connection with the Signal Server. But
there is WIFI on, I tried Mobile Data...

Am 09.12.2015 um 21:28 schrieb Masha Kolenkina (Open Whisper Systems):

Masha Kolenkina (Open Whisper Systems)

Dec 9, 13:28

Hi Luis,

Have you checked out the support page here: http://support.whispersystems.org/hc/en-us/articles/214634627-Why-can-t-I-register-or-verify-Signal-Why-does-it-stop-on-the-4th-step?

Registration can not be done manually and will need to be done on your phone.

Dec 9, 12:18

Hi OpenWhisper-Systems-Support-Team,
first of all I would like to mention, that WhatsApp, Telegram and all the other stuff is shit against TextSecure or Signal.
Since the update from I think an old version (2.26 or something) that I made today,
Signal is not working any more.
I downloaded the latest Version (3.61) from the play store. All that stuff installed correctly. Signal ist starting, but not connecting to your Servers.
I can't send you an error log or something, because I cant even register Signal.
What should I do?
I used the old version, which mentioned me to upgrade to the latest, and now it's not working any more.
The network is connected correctly. I can surf in the internet, so network is not the problem.
I don't get a Verification Code via SMS.
I reinstalled Signal around 5 times and tried again.
Problem for me now is, that I can't downgrade to an old version (and I want to try the new features :P)
Thanks for helping & your time you invested in this excellent Project!

Greetings
luxora
This email is a service from Open Whisper Systems. Delivered by Zendesk
Message-Id:JOWM22823N_5669b1fe5af09_bc2d3fb41b2cd32888102e_sprut

**Comment by moxie0** [comment]
Please don't post support questions here, thanks.

**Comment by enragedpixel** [comment]
This is still a recurring bug

**Comment by githtz** [comment]
I've had the same problem, turned out I had 'Google device registration' disabled. Make sure to enable it in the mucroG settings.
I cleared the App data afterwards and tried to register again, and voila!

![img_20171126_165930](https://user-images.githubusercontent.com/15327800/33241809-6910130a-d2cb-11e7-9605-1a614bffa82d.jpg)
