### ISSUE TITLE
"Long Click" enable and disable for encrypted calling

### ISSUE THREAD

**Issue by darryl-grennan** [WhisperSystems/Signal-Android#4857]
Hi folks!

It would be great if you could toggle encrypted calling as a per contact preference by doing a long click on the phone icon similar how you can do the same with the SMS button.  Perhaps a graphic image of a phone with an unlocked image where the padlock is a little bigger for emphasis but unlocked and red.

**Comment by moxie0** [comment]
thanks but we're not going to do this. if you want to initiate an insecure call, tap the contact's avatar and select call from the quick contact badge

**Comment by lrq3000** [comment]
There's a hidden feature that allows you to easily force or disable secure call: Signal's integration in contact's card: to access the contact card from Signal, open the discussion thread, then click at the top on the contact's name, then click on the bubble at the left of the contact name at the top, and now you should see the contact's card and you should see an entry "Signal Call XXXXXX", but you can also use the standard entry to do an unsecured call.

**Comment by mpetito** [comment]
This decision should be revisited. The quality of secure calling is pretty terrible most of the time. Why should users not have the same option as they do with messaging?

The proposed workaround of 3 extra taps to use the contact card is not user friendly either.

**Comment by clxt** [comment]
Hi, I think @lrq3000 feature is not anymore possible. I rarely use Signal secure calls because I have no good internet connection and little data, so I'd love to have opportunity to call my Signal contacts the same way I can call the non-Signal ones (I use Signal as SMS client).
@moxie0 what are the reasons not to allow this?
Thanks a lot!
