### ISSUE TITLE
Disabling all encrypted calling should be possible.

### ISSUE THREAD

**Issue by darryl-grennan** [WhisperSystems/Signal-Android#4858]
Explicitly disabling all encrypted calling to all parties should be possible somehow since a lot of people complain that its functionality is rather limited at this stage (not working most of the time) but they enjoy the text features of the app which are rather solid.

If encrypted calling is disabled the people on the contacts list should be updated via the server that encrypted calling is inhibited for that party and not display a phone locked icon.

Previous to the merge of Textsecure and Rephone we had a choice.  Now we don't.
Maybe an advanced option?

**Comment by moxie0** [comment]
thanks but we're not going to do this
