### ISSUE TITLE
[UX] Invite friends UI should make clear that invitation allows to select contacts (and is not sent to all)

### ISSUE THREAD

**Issue by jnachtigall** [WhisperSystems/Signal-Android#4869]
When I joined Signal I was asked to invite my friends. I hesitated because I was afraid the invatation would be send to all my contacts (many business contacts and rarely used contacts among).

Now again I wanted to do this manually be selecting "Invite friends" from the main menu. This really makes the impression that the SMS would be send to all contacts without being able to preselect which contacts to send it to:

![screenshot_2015-12-12-11-36-27](https://cloud.githubusercontent.com/assets/3307404/11761538/28fdb020-a0c7-11e5-989d-5a9319c78326.png)

1. Input: I can edit the message which is supposed to be send.
2. Submit button: Says "Send SMS" 

Of course I did not! Do not want to send this to all my 300 contacts.

I just learned from the documentation at http://support.whispersystems.org/hc/en-us/articles/213190647-Group-SMS (under option *B) Use the invite flow to share through SMS or other media* at the bottom) that one can indeed select the ones to whom the SMS should be send. 

The UI flow should make it clear that "Send SMS" button does not immediately send the SMS. It should be clear that I can select the contacts to whom the invatation is send. The way it is now I assume that many users hesitate to use the "bulk" friends invitation. This hampers the spread of Signal I am afraid.

**Comment by agrajaghh** [comment]
What do you think about "SELECT CONTACTS" or "CHOOSE CONTACTS" (or maybe FRIENDS)  instead of "SEND SMS"?

**Comment by jnachtigall** [comment]
Yes, just a better wording would probably do. Both sound better to me. 

Maybe even "Choose Contacts for SMS" to make it clear that contacts are chosen for sending SMS. But this is a bit lengthy, depends on how this can fit into the design of course.

To make it really verbose one could have:
* Share with App
* Choose contacts for SMS
