### ISSUE TITLE
Links won't open in new tabs

### ISSUE THREAD

**Issue by hebu** [WhisperSystems/Signal-Android#4874]
Since version 3.7.2, it is impossible to open multiple links from a conversation in separate browser tabs, as every link will be opened in the same tab and so, overwrite the previously opened link. I am using Firefox for Android. It does not seem to be a Firefox bug, as with other apps the browser behaves as expected (it is opening a new tab for every link)

**Comment by hebu** [comment]
Definitely not a Firefox problem, as the same issue can be observed using the default Android browser.

**Comment by 2-4601** [comment]
Confirmed on Nexus 4, stock 5.1.1, Firefox 42.0.2 and Signal 3.7.2.
Could have been before 3.7.x too.

**Comment by 2-4601** [comment]
Just tested this more. I had some old builds laying around so I tried with 3.1.1 and it has the same behaviour: multiple links open on the same tab. I'm confused.

**Comment by hebu** [comment]
That's indeed confusing as I am pretty sure, that this behaviour started with the last update (the version where the status indicator in the contact list was introduced). If it would have happened before, I would have noticed it.

**Comment by 2-4601** [comment]
Firefox 42 introduced tab queues. **Settings -> Customize -> Open multiple links**
This is a (nice) workaround. Also could be the cause of this issue. I have rarely used other browsers to open links from Signal (or other apps) so I don't know how they have behaved.

**Comment by hebu** [comment]
After experiencing this issue, I also tested it using the Android built-in browser (Android 4.3) and I have seen the same behaviour. So I don't think, that Firefox causes this issue.

**Comment by 2-4601** [comment]
Signal 3.1.1 and the built-in browser (Android 4.0.4) has the same issue: all links open in the same tab.

**Comment by hebu** [comment]
Fascinating! :)

**Comment by hebu** [comment]
The workaround using Firefox' "open multiple links" mode now does not work like before anymore. At least not, when I choose "open now" when opening a link. Still, I can collect all links in the background and then, open Firefox from the notification bar. And also, what would non-Firefox users do to get around this bug?

Is there a chance that this "overwriting tabs" behaviour may be fixed?

**Comment by laurencebgood** [comment]
The fix on the Signal side is to set EXTRA_CREATE_NEW_TAB. see https://developer.android.com/reference/android/provider/Browser.html#EXTRA_CREATE_NEW_TAB for details. I guess if some people find the current behavior preferable, this could be a configuration option, though I really think this is almost always unexpected behavior.

**Comment by laurencebgood** [comment]
Haven't been able to track down where in the code, but there is a regression somewhere-links now all open in the same tab, as before this was fixed.

**Comment by hebu** [comment]
I am using Signal 4.70.5 and Firefox 80.1.2 and I can not confirm it. Links still open in different tabs on my phone.

**Comment by laurencebgood** [comment]
I'm using
Signal 4.70.5
Chrome 85.0.4183.81
Android 10 build QQ3A.200805.001

It could be that Firefox now works around this on it's own, but I'm also
wondering if Android is changing semantics on this.

**Comment by cody-signal** [comment]
Hi @laurencebgood, thanks for continuing to a be a signal user. We haven't changed anything about link handling recently so we think something has changed in Chrome. If this continues to be an issue, it's better practice to open a new Github issue and link to this one instead of commenting on a 4 year old ticket.
