### ISSUE TITLE
Multiple notifications from group appear as a single notification

### ISSUE THREAD

**Issue by billie80** [WhisperSystems/Signal-Android#4875]
When receiving messages from two different contacts the notifications are merged into one making both messages looking as if they are from the second contact.

**Comment by billie80** [comment]
First notification:
![2015-12-13 10 31 34](https://cloud.githubusercontent.com/assets/9938306/11767364/7c239b40-a1ab-11e5-828a-2cf8796cab2e.png)
Second notification:
![2015-12-13 10 30 22](https://cloud.githubusercontent.com/assets/9938306/11767365/8146f2d4-a1ab-11e5-9a52-edafbe587617.png)

**Comment by scienmind** [comment]
Possibly relevant: https://github.com/WhisperSystems/Signal-Android/pull/3020

**Comment by moxie0** [comment]
this is fixed in master
