### ISSUE TITLE
Proposal: GIPHY Support

### ISSUE THREAD

**Issue by cyphar** [WhisperSystems/Signal-Android#4876]
While Signal currently supports GIFs, it requires storing them on your local device (which is annoying). Since GIPHY has an API for searching GIFs, it should be plausible to implement a client-side feature where the client finds a GIF using GIPHY and then sends it without saving it locally (or temporarily saving it). The only issue I can see is that GIPHY would be told that a particular person is a Signal user.

**Comment by johanw666** [comment]
Why is that annoying? They are at least encrypted there, and not open for any intelligence agency on some cloud server.

**Comment by cyphar** [comment]
@johanw666 It's annoying because not everyone can stockpile sets of GIFs for every conversation they will ever have. Given the fact that Signal's purpose is not anonymity, I don't understand what you're talking about. The GIFs would be encrypted, it's just that you could search and embed them within Signal. Sure, that means we'd have to poll to an API from the client telling them that we use Signal, but you're already telling Google about the fact you use Signal anyway.

**Comment by nrizzio** [comment]
This has been implemented as of 69d0242574cc68b068afe3a00861e574b176f08b, so this issue can be closed.
> The only issue I can see is that GIPHY would be told that a particular person is a Signal user.

This concern has been addressed in the implementation as well:
> [Since communication is done via TLS all the way to GIPHY, the Signal service never sees the plaintext contents of what is transmitted or received. Since the TCP connection is proxied through the Signal service, GIPHY doesn't know who issued the request.](https://whispersystems.org/blog/giphy-experiment/)

**Comment by cyphar** [comment]
I completely forgot I authored this issue. :wink:

**Comment by dejIO** [comment]
And now OWS is getting flak for supposedly caring more about funny GIFs than helping activists... well done ¯\_(ツ)_/¯

**Comment by dejIO** [comment]
¯\\_(ツ)_/¯

**Comment by dejIO** [comment]
And now OWS is getting flak for supposedly caring more about funny GIFs than helping activists... well done ¯\\_(ツ)_/¯
