### ISSUE TITLE
Not able to Restore Keys/Messages from NAND-Backup

### ISSUE THREAD

**Issue by Alexandero89** [WhisperSystems/Signal-Android#4883]
Hey guys,

I have an OnePlus one with (now) Android 6. I dirty-flashed from Lollipop and got stuck in a Boot-Loop.
After that i tried to restore backup to the Lollipop but still Bootloop so i had to make an Factory-Reset on the phone.

Now i have an complete Backup of my System with TWRP but can't get it to work with my "new" Signal so my old Keys and Messages won't get lost.

The things i tried:
1) Install Signal on new OS and changed the directory /data/data/org.thoughtcrimes.securesms with the one from backup. Also changed owner and group to the new user and group of signal

2) Deinstall everything from Signal. Copy the directory to data/data/ and then install Signal from Play Store in hope it will see that it will find the old files. Still no success

Could you give me a hint how to restore my old Keys? My Messages aren't even so importend. Only the Keys.

If neccessary i will upload some LogCats if you want to

**Comment by johanw666** [comment]
After step method 1 you might have to force close and restart Signal.

**Comment by Alexandero89** [comment]
Didn't help, I even restarted and deleted cache/dalvik to rebuild

**Comment by moxie0** [comment]
Sorry but this isn't a discussion or a support forum, and this seems unrelated to actual Signal Android functionality.
