### ISSUE TITLE
unlinking a device doesnt give confirmation. just a spinning wheel.

### ISSUE THREAD

**Issue by madLyfe** [WhisperSystems/Signal-Android#4888]
when i unlink chrome desktop from my phone i do not get a confirmation and it just get the android loading circle. if i back out and go back into the devices area it shows that it was unlinked though.

![screenshot_20151214-173649](https://cloud.githubusercontent.com/assets/16073360/11797805/2f0bac7c-a28b-11e5-8ae3-f4df6b74992f.png)

**Comment by RiseT** [comment]
Duplicate of https://github.com/WhisperSystems/Signal-Android/issues/4641

**Comment by madLyfe** [comment]
thanks

**Comment by RiseT** [comment]
I. e. you can close this issue now (that is, if it doesn't contain something which isn't contained in the issue mentioned above. Don't know about the confirmation as I'm getting the spinning wheel as well...)

**Comment by madLyfe** [comment]
Duplicate of #4641
