### ISSUE TITLE
linking a device leaves grayed out info popup

### ISSUE THREAD

**Issue by madLyfe** [WhisperSystems/Signal-Android#4889]
when i link a device, in this case chrome desktop, it give the link device popup but the info is grayed out or too faint to read. the link device button functions properly though.
![screenshot_20151214-173708](https://cloud.githubusercontent.com/assets/16073360/11797850/8c8a2f22-a28b-11e5-861d-4371cc71798e.png)

**Comment by McLoo** [comment]
Duplicate of #4611

**Comment by madLyfe** [comment]
thanks @McLoo

**Comment by madLyfe** [comment]
Duplicate of #4611
