### ISSUE TITLE
Exclude meaning rich colors for conversation differentiation initially

### ISSUE THREAD

**Issue by gene1wood** [WhisperSystems/Signal-Android#4891]
I installed Signal on Android and very shortly after got messages from two friends who both use Signal congratulating me on installing it.

The two conversations were colored primary red and primary green.

![green](https://cloud.githubusercontent.com/assets/1134034/11802270/bad5296e-a2a3-11e5-98ab-194d10e37079.jpg) ![red](https://cloud.githubusercontent.com/assets/1134034/11802263/b2200938-a2a3-11e5-9b45-d04707398ac8.jpg)

I assumed that these colors signified some meaning about the conversations like maybe the green one was secure and the red one was insecure.

I did some Googling and found Issue #945 which seemed to imply that the issue color indicated the transport medium that the message arrived by.

I asked @mfb and he figured out what was going on, that these colors were meant to differentiate conversations from each other.

I'd like to recommend / feature request, excluding meaning rich colors from use as differentiating conversation colors, at least initially, to avoid confusing the user. If for example the first two conversations were in pastels or in pretty much any two colors other than red and green (which have a very strong visual meaning of stop/go success/error good/bad) I think I would have begun to intuit that the colors were for conversation differentiation.

I'd also say that if it started out with pastels or some other non-meaning-rich colors and I later encountered red and green conversations I'd probably intuit they were just there for differentiation.

Since it looks like conversation color is driven directly by [the contacts name](https://github.com/WhisperSystems/Signal-Android/blob/e79ee7803fea85ec999e0f6dc803fc1227096cd0/src/org/thoughtcrime/securesms/contacts/avatars/ContactColors.java#L8-L16) I'm not sure it would make sense to tweak the initial colors as the user begins using the app.

Since, by my read, of the [list of colors](https://github.com/WhisperSystems/Signal-Android/blob/e79ee7803fea85ec999e0f6dc803fc1227096cd0/src/org/thoughtcrime/securesms/color/MaterialColors.java#L13-L36), only red and green have a strong meaning. All the others seem not meaning rich to me, maybe just remove red and green. Problem there is that existing users mapping of which conversations have which colors would change, possibly confusing people.

So, hopefully someone here has a better idea of a solution here than what I've come up with.

**Comment by moxie0** [comment]
Thanks @gene1wood for the thoughtful analysis, but we're not going to change colors at this time.
