### ISSUE TITLE
Allow the choice of font size for chat screen

### ISSUE THREAD

**Issue by AKayumov** [WhisperSystems/Signal-Android#4894]
Allow the choice of font size for chat screen : either exact size in points or simply small-medium-large will likely be more than enough.

It's a basic option supported by most messengers - even by the stock sms client ! I have a 6" smartphone and the standard font size is way too large for my screen, which could easily and usefully fit much more text. Others, e.g. those with poor eyesight or those with small screens, might find the standard font size too small to read comfortably.

I believe this would be a useful feature and one that's probably pretty straightforward to implement.

**Comment by 2-4601** [comment]
I think this is already tracked in #1509

**Comment by AKayumov** [comment]
Hm, looks like you are right. Althogh that sure seems like a very complicated and unnecessarily convoluted way to talk about a three-choice (small-medium-large) option... :)

I am frankly a bit baffled by (a) why this has not yet been implemented and (b) why the request is being deferred. This is, in my opinion, an easy-to-implement, essential, and almost universal feature that any decent messenging app should have.

**Comment by haffenloher** [comment]
As 2-4601 noted, there's already an open issue for this, so please close yours as a duplicate :)

> …why this has not yet been implemented […]. This is, in my opinion, an easy-to-implement

As the original request is still open, I guess you're welcome to take a shot at this and submit a PR!

**Comment by AKayumov** [comment]
> As the original request is still open, I guess you're welcome to take a shot at this and submit a PR!

How about everyone sticks to their jobs? ;)

As a recent adopter of Signal and as someone trying to get others to adopt it as well, I am trying to provide feedback on what an average, normal user would like to see in the app. If your response to such requests is going to be "hey, why don't you go and code it yourself?", then I am afraid Signal will not be able to escape the bullpen of security apps that no one but the cryptographers, the geeks, and the paranoid use (like PGP, OTR, etc.).

**Comment by 2-4601** [comment]
@AKayumov This is an open source project with limited resources. It's not @haffenloher's job to write any code to this project but he's still regularly submitting quality PRs. If custom font size is important to you and you think it's easy-to-implement you are free join in and give it a try.
And if you have some new information to add to the issue please use the original one #1509.

**Comment by hiredgunhouse** [comment]
@2-4601 not everyone is a programmer so throwing a "you're welcome to send PR" argument at everyone is wrong and regarding @AlexanderKayumov's "easy-to-implement" argument is about high ROI in this case which I'd support

**Comment by agrajaghh** [comment]
@hiredgunhouse Please don't bump issues https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues
