### ISSUE TITLE
Placeholder size/position doesn't match actual entered text styling

### ISSUE THREAD

**Issue by aprescott** [WhisperSystems/Signal-Android#4903]
The text box message placeholder's size/positioning doesn't match the text you actually see when typing. This leads to a somewhat jarring visual experience when looking at the app.

Here is the placeholder:

![screenshot_20151216-195516 2](https://cloud.githubusercontent.com/assets/342081/11858765/4ce951f6-a432-11e5-9077-543867336ad5.png)

And here is "S" entered in the text box:

![screenshot_20151216-195520 3](https://cloud.githubusercontent.com/assets/342081/11858775/62afd7ee-a432-11e5-8adc-b2b89aa2c25a.png)

The placeholder is smaller than the actual entered S, so when you see the placeholder then start typing, the text feels like it suddenly changes size/style. It would be good if they lined up correctly. For example, here is Hangouts, where the "W" lines up exactly with the placeholder when entered.

![screenshot_20151216-195454 3](https://cloud.githubusercontent.com/assets/342081/11858810/d367e94a-a432-11e5-8729-d3d039f3a8ef.png)

![screenshot_20151216-195448 3](https://cloud.githubusercontent.com/assets/342081/11858811/da4dfca4-a432-11e5-9e78-0e437e0a47b7.png)

With this, there's no discrepancy when beginning typing or deleting all entered text.

All screenshots here are taken at the same scaling, and are only cropped.

**Comment by aprescott** [comment]
I know trying to fix this lead to visual issues such as #5297. Is it possible to resolve this by making the content shorter so that wrapping and truncation issues are less likely on smaller screens? For example, perhaps "Signal" doesn't need to be mentioned since the context is already the Signal app itself.

Just trying to think of ways this could be solved. I find it really stands out when using the app.

**Comment by 2-4601** [comment]
> perhaps "Signal" doesn't need to be mentioned since the context is already the Signal app itself.

I think "Signal" is used here to refer to the secure message transport (in contrast to SMS) so leaving it out would make that unclear.

And the space is going to get even smaller when direct audio capture is re-enabled. It introduces a microphone icon to the same horizontal space.

**Comment by 2-4601** [comment]
This is not an issue anymore.
