### ISSUE TITLE
Don't send me friend suggestions in the middle of the night

### ISSUE THREAD

**Issue by nh2** [WhisperSystems/Signal-Android#4904]
I just got a `XXX is on Signal, say hey!`, with vibration, at 03:52 am while in bed.

Please don't do that.

**Comment by jeremymasters** [comment]
Does that notification not obey the system settings for do not disturb?  Seems like this wouldn't be the only app that could potentially notify in the night.

**Comment by moxie0** [comment]
duplicate of #4572
