### ISSUE TITLE
Disable notification sounds from phone while using desktop client 

### ISSUE THREAD

**Issue by klement** [WhisperSystems/Signal-Android#4905]
Mobile phone plays notification sound for every message received when using desktop client, which is annoying in e.g. office environment.

There should be an option to disable sounds while using desktop client.

Possible implementation:
Start a timer in the android app whenever a desktop client is used (e.g. message is read, sent or so) for, say 1 minute (or configurable) and during that timer, don't play the notification sound. If a message arrives while timer is active, then keep a flag. If the timer is reset (by desktop interaction), clear the flag, otherwise play the notification sound after the timer expires.

This way, the phone is mute while the user is having a desktop conversation, but there will be a notification in case when a message arrives from a remote party shortly after closing the desktop client or so.

**Comment by jeremymasters** [comment]
I think this falls apart a little if I leave my desktop client turned on when I go home for the night after work.  Then all my notifications would be late on my phone.

**Comment by klement** [comment]
Nope, once the desktop activity timer runs out (1 minute without you
interacting with the desktop client) the notification should sound.

**Comment by jeremymasters** [comment]
This would indeed be pretty cool then!  Sorry for my stupidity.

**Comment by dcherian** [comment]
Another option would be to have the desktop client show a small snackbar like thing saying "Mute phone notifications for 10 minutes?" or "Unmute phone notifications" as applicable.

**Comment by adarazs** [comment]
We got notification syncing between Signal Desktop and the Android client, which is a great step ahead. Still, currently how it works is:

1. User actively using Signal Desktop, message arrives.
2. Notification appears on the phone, phone vibrates, plays notification sound, etc. depending on the sound settings
3. The desktop client quickly syncs the "message read" state, making it disappear from the phone.
4. Phone doesn't have any useful notification anymore, but it buzzes and annoys user all day while using the desktop client

This behavior (not suppressing notification while the desktop client is in active use) is the biggest problem I have with Signal for now. Awesome improvements are going on in both clients otherwise, but this should have some priority, as it affects usage a great deal (though I know Desktop is in beta).

**Comment by andersk** [comment]
This is even worse if the phone is off during the Signal Desktop conversation. When the phone is next turned on, it receives all the messages interleaved with the “message read” states, and processes them in the order they were received, resulting in “notification!, cancel, notification!, cancel, notification!, cancel…” once for each message, complete with repeated buzzing and alert tones.

Can you fix the client to download and process all of the synced states before deciding whether to show any notifications?

**Comment by MadaraUchiha** [comment]
Can this be revisited? This is seriously annoying, and I don't want to disable mobile notifications completely.

**Comment by shakurass** [comment]
I like the timer idea, I created a similar post because I didn't find this on in the search. Use of window focus + a timer would be a great way to implement notification squelching in the mobile app when using the desktop app.

**Comment by renselu** [comment]
For me this is also the number 1 problem with Signal right now. Hope it will get fixed soon.

**Comment by ajackofsometrades** [comment]
Notifications sounds are nice, but online status is more valuable to me personally.

**Comment by rjulian** [comment]
This bug seems to make the desktop client pretty much unusable as a form of chat (which I imagine is the only reason you'd ever want to use it) as you're just constantly hearing your phone notifications. Does anyone know if this has been fixed in any of the betas?

**Comment by ajackofsometrades** [comment]
Actually, I would like to parrot what rjulian said. That is the huge issue with combining texts and other messaging into one app -- the notifications aren't granular, so there's no work around should you wish to use a desktop client and not have what sounds like robot sex in your pocket.

**Comment by moxie0** [comment]
An activity timer seems like the only possibility. Though I think people are going to be upset when they walk away from their computer, get a message 59 seconds later, and aren't notified.

**Comment by rjulian** [comment]
I think an activity timer is how Slack handles it, however, they send the notification to your device if that message isn't acknowledged in X minutes which seems to be a good catch for these sort of scenarios. Does this sound feasible?

**Comment by moxie0** [comment]
What would it mean for a message to be "acknowledged" in this case?

**Comment by adarazs** [comment]
@moxie0 What you mention with the 59 second is the worst case scenario and the user had to leave their computer unlocked, and focused on the Signal Desktop client to mark the incoming message as read. In that case there are currently phantom/possibly missed notifications on the Android device, which is quite bad.

The desktop and android client is already in connection, as they can mark stuff read. So how about

1) activity timer prevents the creation of notification on Android when user actively uses the Desktop client
2) user locks the computer and leaves
3) gets message within the timer limit
4) timer expires, desktop client checks for unread messages and triggers the notification for them on Android

In this scenario there would be a maximum of 59 second delay for receiving a message after leaving the Desktop client, which could be also reduced to 30, the point is to not have these quickly disappearing notifications on the phone.

**Comment by Micasaloca** [comment]
Robot sex. funny.
Isn't this something we could work on, as Open Whispers is on github? 
-Mary Ann Steinacker-Grimm 

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 22, 2016 at 0:25, ajackofsometrades<notifications@github.com> wrote:   
Actually, I would like to parrot what rjulian said. That is the huge issue with combining texts and other messaging into one app -- the notifications aren't granular, so there's no work around should you wish to use a desktop client and not have what sounds like robot sex in your pocket.

**Comment by moxie0** [comment]
@adarazs That's not really tenable. The desktop client might not even be running anymore, the entire computer might not even be on anymore.  All the mobile device knows is that the user sent or read a message on the desktop client 59 seconds ago.

**Comment by adarazs** [comment]
@moxie0 The issue at hand ("aka robot sex") could be solved with a very short time out (<5 sec) when actively chatting, reducing the possibility for missed notifications.

Another extra remedy could be cancelling the timer upon a proper termination of the desktop app (closing it/shutting down the computer). This would leave a short window for missed notification in case the desktop app gets killed, the computer loses network connectivity, etc. which seems more acceptable than the constant buzzing of the phone.

**Comment by moxie0** [comment]
If you set the timer to 5 seconds, that means the person you're chatting with only has 5 seconds to respond. Otherwise, your phone notifies you.

**Comment by adarazs** [comment]
@moxie0 Ah, now I see the problem. How about this solution:

If the Android client received a "clear notification" message from the desktop client in the last 60 (or maybe configurable amount of) seconds, delay the notification creation by 5 seconds (or maybe only 2, needs some testing). If it receives a "clear notification" during this time, don't even create the notification, avoiding the excessive buzzing while the Signal Desktop client is focused and notification are read immediately. If not, display the notification.

No extra network traffic required, just a logic in the Android app. You get a delayed notification for a short amount of time after using the desktop client, but you can't miss any. Now tell me what I missed that makes this infeasible . :)

**Comment by moxie0** [comment]
That's a good idea. Only potential problem is that it makes this kind of device muting per-conversation. If I have a conversation open in the desktop app and receive a message from another conversation, my phone will buzz 5 seconds later.  Maybe that's OK.

**Comment by jeremymasters** [comment]
would this include, or at least preclude, having notifications within a 5-second window have just one buzz/ring?

**Comment by haffenloher** [comment]
Not making it per-conversation should be fine too, I think that's what @adarazs intended. One could also interpret any incoming sync message (including sent transcripts) as a sign of desktop activity:

On incoming message: If there has been no sign of desktop activity in the last 60 seconds, notify.
Otherwise, notify after 5 seconds unless there's another sign of desktop activity during these 5 seconds.

**Comment by adarazs** [comment]
@haffenloher The read notification action won't happen unless you switch focus to that conversation. This makes it per-conversation. Unless you can click to the other person's conversation within the 5 second window, there won't be anything that would trigger the timer again to prevent the notification to fire. Having the sent messages trigger this short "don't display notifications for 5 seconds" is a good idea though that could further reduce the unnecessary ones.

**Comment by haffenloher** [comment]
@adarazs ah, I see. A "read" sync message for conversation A could also suppress notifications for conversation B though (if within the 5 second window)

**Comment by hopeseekr** [comment]
What happens now is that there is about a 10 second pause between SIgnal Desktop and Android sync, EVEN ON MEssAGES marked ot disappear after 30 seconds...

After 3 hours of chatting tonight, for instance, it is 00:49 IST yet the android client is still beeping continuously tho my chats ended 20 minutes ago :O The Android client is now on messages from 22:49 IST, fully 2 hours behind!!!!

What's worse, these are messages marked for deletion in 1 minutes.

So does Signal keep these messages???? Are they NOT deleted???

So many problems with this!!!

**Comment by N9PBJ** [comment]
This is a very old issue, but it's driving me nuts. I'll have the app open on my desktop, it's the active window, a message comes in and my phone beeps and shows the notification instantly...

**Comment by N9PBJ** [comment]
Please for the love of all that you hold dear give, this option needs to be added.
