### ISSUE TITLE
Encryption process

### ISSUE THREAD

**Issue by macofmustafa** [WhisperSystems/Signal-Android#4910]
Hell dear,
I'm just wondering about the right place if i want to insert another layer of encryption and in which class your encryption process is takes place?
Thanks

**Comment by 2-4601** [comment]
Hi @macofmustafa,
It's preferred here to open new issues only for bugs or features. Questions and queries should go to the [mailing list](https://lists.riseup.net/www/info/whispersystems). Although in this case it would probably be faster to just search the code base locally or through github https://github.com/WhisperSystems/Signal-Android/search
