### ISSUE TITLE
Call volume stuck at maximum after placing secure call through Signal

### ISSUE THREAD

**Issue by wngroves** [WhisperSystems/Signal-Android#4911]
Steps to reproduce:
1. Attempt secure phone call to another Signal user
2. Disconnect before or after call is connected
3. Place normal (unsecured) call.

Results:
- Normal call volume will be at maximum
- Pressing volume buttons changes only the Bluetooth volume even if Bluetooth isn't enabled. 
- Must reboot phone to restore volume functions

Using Alcatel Onetouch 5042T running Android kernel "android-blb@Perso54 #1". Build no: ALPS.KK2.MP13.V1.39. Firmware ver 4.4.4.

**Comment by 2-4601** [comment]
Which Signal version are you using?

**Comment by cascheberg** [comment]
I started to have a look at that, see #4885

**Comment by cascheberg** [comment]
Please check if the issue is fixed in 3.9.0 if you can. It is available on the Google Play Store as a beta release.

**Comment by cascheberg** [comment]
A fix for this has been released. This issue should be closed unless more information is provided.
