### ISSUE TITLE
Consider SMS spam blocking features

### ISSUE THREAD

**Issue by PicoGeyer** [WhisperSystems/Signal-Android#4917]
Signal is my favourite application for both SMS and encrypted messaging.
However given the fact that SMS spam is on the rise, It would be a very useful feature to support some sms spam blocking.
There are many third party application that do this but they require changing the default SMS application.
I think any of the following features would be useful:
* Options to only issue a notification for messages from known contacts.
* Word based classification/blacklists (perhaps with an option to never block messages from known contacts)
* Number blacklists (arguably easy for spammers to circumvent)

Of course there are more sophisticated options as well, but these may provide the greatest bang for buck.

**Comment by moxie0** [comment]
We already support number blacklisting, I think that's probably as far as we'll take it.
