### ISSUE TITLE
Strip off blank new lines in a message

### ISSUE THREAD

**Issue by shubhekshajalan** [WhisperSystems/Signal-Android#4923]
Whenever there is a message which contains extra new, blank lines at the end, they're not stripped off -- the message is sent along with those newlines at the end. Normally, if the lines are blank, they're removed before the message is sent.

**Comment by scienmind** [comment]
Same goes with "empty" messages that contain new lines only

**Comment by moxie0** [comment]
Thanks, but I think we want to preserve what someone sends or is sent rather than altering the message.
