### ISSUE TITLE
Deliveries not cached if messaging group chats

### ISSUE THREAD

**Issue by ghost** [WhisperSystems/Signal-Android#4924]
1. keep phone in airplane mode
2. send some messages to a group chat using the chrome extension
3. turn on data on your phone
4. sent messages not marked as delivered

It used to be the same with single chats, but this commit (49f60971bde2f3e4fbc8327039c88df4e7b44a60) fixes it. It doesn't fix group chats though

**Comment by x12x** [comment]
This is related to https://github.com/WhisperSystems/Signal-Android/issues/4743 , which should be closed I guess in favor of this more specific one..? Hopefully they will both be closed soon

**Comment by smichel17** [comment]
I am also having this issue on 3.15.0 and desktop 0.5.0. Logs available if you need them.

**Comment by superduperuser** [comment]
This is still a bug in Signal-Android 3.16.0 and Signal-Desktop 0.16.1. The second checkmark does not show up in Signal-Android. This bug makes it hard to keep track of what has and hasn't been delivered. 

These screenshots show the problem. All the messages from my side were sent through Signal-Desktop. 
![screenshot1](https://cloud.githubusercontent.com/assets/20377747/16808458/9c99a018-48ea-11e6-9196-67f5ef05eb00.png)
<img src="https://cloud.githubusercontent.com/assets/20377747/16808475/a7a8b340-48ea-11e6-9fa1-935d7b70e49f.png" width="400"/>

**Comment by strugee** [comment]
I can confirm this bug under Signal Desktop 0.39.1, Signal Android 4.6.0 (on my end). The issue occurred in a group chat with people using Signal Android, no iOS client involved. Some had Signal Desktop installed too.

**Comment by rainerzufall** [comment]
this bug is fixed by https://github.com/WhisperSystems/Signal-Android/commit/2c1337b33efe0063f8d39de974514567becd8be3 / Signal Android 4.11.0. The issue can be closed.
