### ISSUE TITLE
Prefill registration form with user's phone number (no need for manual input)

### ISSUE THREAD

**Issue by jnachtigall** [WhisperSystems/Signal-Android#4929]
During registration (just after installation) the user has to enter its phone number manually. The national code (e.g. `+49` is prefilled). This is not optimal because:

* Users are (psychologically) relactant to (actively) enter personal data like phone number that is sent to some server (which they've just heard about somewhere). So I've really seen friends aborting the registration at this very step. This is really a UX issue.
* It's about 9 unnessary keystrokes more
* At least in Europe people mess up with the leading 0 in phone numbers. A lot of people without internatinal relations do not know (or at least are puzzled about) that the leading 0 is to be ignored after the internal code of  `+49`

Would be good if the users phone number could be automatically retrieved from the phone by Signal and the number prefilled into the input form. A user could still change the prefilled number just in case.

**Comment by moxie0** [comment]
We do. If you're not seeing the number, it means your SIM card isn't returning the data.

**Comment by jnachtigall** [comment]
> If you're not seeing the number, it means your SIM card isn't returning the data.

Then this is probably the same as in https://github.com/WhisperSystems/Signal-Android/issues/3810#issuecomment-166020896 where SIM card contacts show up as tel numbers only and not as names.

**Comment by McLoo** [comment]
For completeness: we try even harder to get the number since 3.8.0 
@jnachtigall did you try on that version?

**Comment by jnachtigall** [comment]
@McLoo No, I used 3.7.2  (there is no 3.8.0 in the Play Store yet, at least in Germany the current version is 3.7.2). 

Otherwise good to hear about the progress :+1:  I was present when Signal was installed on 4 different Samsung phones (friends) and I think 3 of them had to enter their phone number manually.
