### ISSUE TITLE
Which CA root certificate needs to be enabled for Signal on Android?

### ISSUE THREAD

**Issue by uiopc** [WhisperSystems/Signal-Android#4931]
Hi,

I disabled all the 100+ root certificates in my android 4.4.4 trust store, because actually I don't trust any of these CAs.
Nevertheless I need a few of them, so I want to enable only these I really need.

I already figured out, that I need to enable the Equifax root certificate for GCM. (which is needed for message notifications)
But which root certificate do I need to enable to send and receive images and videos within Signal?

Thanks a lot for the info,
uiop

**Comment by agrajaghh** [comment]
This is an issue tracker, please use the mailing list or the support center (http://support.whispersystems.org)
