### ISSUE TITLE
switching between secure and insecure persists between contacts

### ISSUE THREAD

**Issue by xortim** [WhisperSystems/Signal-Android#4932]
I have a few contacts that still have Signal installed in hopes of bugs like https://github.com/WhisperSystems/Signal-iOS/issues/421 being resolved but do not prefer Signal for their daily driver until the application is usuable for them. Which for users that are experiencing this iOS bug, the application is insanely frustrating to use.

Signal rightfully defaults to messaging being secure. However, when I switch to insecure for this contact, move to another contact the method of delivery is still insecure. This is also true the other way around. If I switch that contact back to secure and then go to the contact that prefers insecure (iMessage conveniences etc.) then the delivery is set to secure.

Steps to reproduce:
1. Open Signal contact "A", send insecure message
2. Open Signal contact "B", message defaults to insecure
3. Change delivery of message for Signal contact "B" back to secure.
4. Switch to Signal contact "A", message delivery now set to secure due to action in step 3

I would like to see a per-conversation or per-contact preference for delivery of secure vs insecure. An additional "remind/confirm insecure messages in x days/hours" would also be awesome.

**Comment by 2-4601** [comment]
I'm unable to reproduce with those steps.
Nexus 4, stock 5.1.1, 3.8.1

For Signal contacts the app always uses Signal messages unless you change by long pressing the attachment/send button. And then when you exit the conversation and come back it will automatically change to Signal messages again.

Can you post a debug log after the steps?

**Comment by xortim** [comment]
After the latest update I'm unable to reproduce it using the steps I indicated before. However, the feature to change the default delivery per contact would be immensely helpful. If this happens again I'll comment on this issue with a debug log.

Thanks!

**Comment by 2-4601** [comment]
Thanks, closing for not reproducible any more.
(Default delivery option is a dupe of #2329.)

**Comment by xortim** [comment]
This behavior was observed again. Debjg log https://gist.github.com/anonymous/894da8a95af06389e849 please reopen

**Comment by 2-4601** [comment]
Can you reproduce this consistently with the steps in your first post?

**Comment by xortim** [comment]
At a high level the steps are still the same. It it's happened a few more times. In addition to the original steps to reproduce, could you try these?:

1. Open Signal contact "A", send insecure message
2. Receive message from Signal contact "B"
3. Tap on notification to go to received message from Contact "B"
4. Change delivery of message for Signal contact "B" back to secure.
5. Receive message from Signal contact "A"
6. Tap on notification to go to received message from Contact "A"
5. Message delivery now set to secure due to action in step 4

**Comment by 2-4601** [comment]
All right, I can definitely reproduce a bug with the transport mode now:

1. Open conversation with Signal contact A
2. Long-press send button and change to SMS transport (you don't have to send anything)
3. While you are in the conversation with A receive a message from Signal contact B
4. Tap the notification to open the conversation with B
5. Observe that the transport mode is SMS (should be Signal)

Nexus 4, 5.1.1, 3.9.0
Huawei U8800, 4.0.4, 3.7.2

**Comment by henrykratom** [comment]
Could this be related?

https://github.com/SMSSecure/SMSSecure/issues/309

**Comment by sudhirkhanger** [comment]
@2-4601 One of my contacts is on Signal but he has decided to not purchase data plan for now. Signal insist I send him secure message which will of course not reach him. It's a design flaw that Signal thinks that once you become a Signal user you will always have access to it and it gives Signal to override user choice. If I have switched to unencrypted channel then Signal should honor my choice.

**Comment by shakurass** [comment]
I second @sudhirkhanger.

I had a friend try out Signal on her **iPhone** but when I found out that she isn't able to use Signal for regular SMS conversations as I am able to on **Android** I had her remove Singal. So this means that Signal was installed on her **iPhone**, we sent a message or two, then she uninstalled it. I say this fully understanding that it's IOS that doesn't allow 3rd party apps to manage SMS messages and not the fault of Signal.

I can send her regular SMS messages through my Signal app but it keeps defaulting back to Signal messages when I exit the conversation. So every time I want to have a conversation with her I have to long press the send button and set it back to Insecure SMS. This isn't very user friendly, and as @sudhirkhanger stated, I believe that it is a design flaw to assume that just because Signal may have been associated with someones number once it doesn't mean they will always have it.

A per-conversation setting that allows the user to set the default message mode with **explicitly clear** wording around what changing the default message mode means for security would be a very useful feature to have.

**Comment by shakurass** [comment]
Steps to reproduce the usability issue I mentioned above:

1. Open a conversation with a contact
2. Long press send/attachments button
3. Select "Insecure SMS" option
4. Tap back or hit the back button at the top of the conversation window
5. Open the conversation from step 1

Note how the app has defaulted back to the "Signal" option. Every time I have a conversation with my friend that uninstalled Signal I need to select "Insecure SMS" again.

**Comment by 2-4601** [comment]
@shakurass That's currently expected behavior. This is a different issue. The issue you are describing is tracked at #2285

**Comment by shakurass** [comment]
Thanks @2-4601.

**Comment by nsrosenqvist** [comment]
This is still an issue on Android and it's very frustrating and is almost forcing me to stop using Signal. This seems like a very simple fix to make the setting persist, is there no work being done on this?

**Comment by moxie0** [comment]
I'm unable to reproduce this. I tried these steps from @2-4601 :

1. Open conversation with Signal contact A
2. Long-press send button and change to SMS transport (you don't have to send anything)
3. While you are in the conversation with A receive a Signal message from Signal contact B
4. Tap the notification to open the conversation with B

**Comment by nicholasfoden** [comment]
Perhaps an option to delete the users keys from the app could help with the security issue with default behaviour. If the contact re-installed signal, after the new key exchange Secure would then be the default.

**Comment by nsrosenqvist** [comment]
@moxie0 For me all I have to do is open a conversation with a Signal user, change to "insecure SMS" and then back out of the conversation view, then it will have reset as I go back in again. This makes it really inconvenient to message people who aren't using the app any longer since they can't see my text messages

**Comment by moxie0** [comment]
@nsrosenqvist That's not what this issue is about. This is referring to the opposite situation, where changing to "insecure SMS" *persists* that setting when communicating with *other* contacts.

I'm going to close this as fixed, but please reopen if it's still an issue.

**Comment by nsrosenqvist** [comment]
@moxie0 sorry about that! I must have misunderstood the issue from the description. Is there an equivalent bug where the issue I described is being tracked?
