### ISSUE TITLE
Unable to call or recieve calls

### ISSUE THREAD

**Issue by pwnedm** [WhisperSystems/Signal-Android#4933]
I have a xiaomi mi note with MIUI 7 7.0.6.0 global stable (Android 4.4.4)
When I call or being called by another person i get "Client error". Using both wi-fi and LTE.
Tried with 2 different iOS devices. Was unable to recieve or make any call.
Tried Signal 3.8.0,  3.7.2
Logs: https://gist.github.com/28c82c47f444cb1c5d8d

**Comment by moxie0** [comment]
Looks like the native audio subsystem isn't initializing, seems like a problem with MIUI (not even sure what that is though).

**Comment by pwnedm** [comment]
All other apps with same functionality work fine (whatsapp, viber, sip )
