### ISSUE TITLE
Group Image disappears after adding new member

### ISSUE THREAD

**Issue by samlanning** [WhisperSystems/Signal-Android#4934]
Steps to reproduce:

1. Go to Update Group (image should still be present)
2. Add a person, and click the tick (labeled as "Create Group" btw, that should probably be changed)
3. check the group in the threads list / by going to update group again, and for the person that changed the group, the image is gone. (does not seem to affect other members of the group.

**Comment by AsamK** [comment]
Which version are you running, this should have been fixed by 7aac137fb71e4cb38c3a48e5012fc91eff326730 in version 3.6.0

**Comment by samlanning** [comment]
3.5.0, haven't tested on latest master. Probably not present I'll close now =)
