### ISSUE TITLE
Move messages to correct group after accepting keys

### ISSUE THREAD

**Issue by tinloaf** [WhisperSystems/Signal-Android#4942]
Hi,

when a contact changed his key and sends a message to a group, a "you must accept the new key" message appears in his 1-on-1 thread. Once I accept the key, the message is then also displayed in his 1-on-1 thread, and not in the group.

I think Signal should decode messages with unknown keys even before the key was accepted (shouldn't be a security risk?), and extract from that where to place the message, i.e. whether it's a 1-on-1 message or a group message.

**Comment by agrajaghh** [comment]
what version are you running? https://github.com/WhisperSystems/Signal-Android/commit/edbbb15a41f98a7e57f8eef68e569cf060e22289 (in 3.8.0) should at least put the message in the group after accepting the new key.

But, I agree, it would be optimal to decrypt the message before. Don't know how complicated that would be though...

**Comment by moxie0** [comment]
this is fixed in 3.8, the latter isn't going to happen though
