### ISSUE TITLE
signal's own notification service, instead of GCM

### ISSUE THREAD

**Issue by piecam** [WhisperSystems/Signal-Android#4947]
Hi,

I am no expert in this area, and just want throw this in in case. It seems that Telegram can use either GCM as notification channel, or its own Notification service bypassing GCM.

I know that Signal is replying on GCM for notification service, just wonder wehther you guys can use some of techniques used by Telegram, so that you don't have to rely on GCM.

Again, not an expert on this and just a curious thoughts.

THanks

**Comment by 2-4601** [comment]
#1000 is the issue for that, closing as duplicate...
