### ISSUE TITLE
[UX] Registration does not offer a call-first verification

### ISSUE THREAD

**Issue by nrizzio** [WhisperSystems/Signal-Android#4951]
[Per documentation,](http://support.whispersystems.org/hc/en-us/articles/212535508-How-do-I-verify-a-number-) the user is unable to get a call-first registration. This alienates users who use calling-only cell plans where sending and receiving texts is *possible* but **costs money**.

A simple solution would be to add a "call me instead" button to the bottom left of the "Connect With Signal" prompt, which immediately calls the user.
![register](https://cloud.githubusercontent.com/assets/13669330/11965762/d4db54e2-a8c4-11e5-9fef-6ed99f45847f.png)

This would allow those users to use Signal while causing no friction to anyone else.

Side note: Although I do not know for sure, I believe the iOS app behaves in the same way. Can anyone else confirm?

**Comment by moxie0** [comment]
Thanks but we're not going to do this

**Comment by nrizzio** [comment]
If I were to implement these changes myself in a fork, test them, and open a PR, would it be accepted? (Provided that changes adhere to the coding style guidelines, functionally works with no issues, etc..)

**Comment by moxie0** [comment]
@nrizzio thanks but no we would not accept that change
