### ISSUE TITLE
Senders name doesn't update after adding to contacts

### ISSUE THREAD

**Issue by agrajaghh** [WhisperSystems/Signal-Android#4953]
If you are in a group conversation and receive a message from an unkown contact, the sender is displayed as a number. After adding him to the contacts (by clicking on the avatar) the number is not replaced by the new name. (just the avatar and the number in the group update message)

before and after adding to contacts:
![group](https://cloud.githubusercontent.com/assets/5296073/11982714/dbc77d64-a9ad-11e5-9380-43574d7a208c.png)

**Comment by dcherian** [comment]
Dupe of #4074?

**Comment by agrajaghh** [comment]
shame on me, didn't find it while searching...
