### ISSUE TITLE
Can't hear my contact's voice

### ISSUE THREAD

**Issue by eternaltyro** [WhisperSystems/Signal-Android#4955]
Creating a new ticket because the existing tickets that are similar do not have relevant titles and/or are similar but different problems. 

I can't hear my contact's voice at all. The mute/unmute or speaker phone buttons don't have any effect. The problem is that it's absolutely silent like my contacts have put my call on mute. I can't hear anything on a  voice call at all; not even feebly.  

This is on a Motorola Moto E (2nd Gen). Logs here:

https://gist.github.com/anonymous/e31c228270dd22f8f5b6

**Comment by mlsxlist** [comment]
Almost same for me since I updated to 3.8.1. But when I touch the speaker button I can hear the other party. Before the update I only suffered from #4733.

**Comment by lazlolazlolazlo** [comment]
This might be fixed by #4885 in 3.9.0.

**Comment by eternaltyro** [comment]
Hopefully. But just to be clear, the speaker button trick doesn't help at all and none of the other reports of voice issues seem similar to the issue I'm facing.

**Comment by 2-4601** [comment]
Closing as RedPhone issue.
