### ISSUE TITLE
Panoramic pictures look ugly

### ISSUE THREAD

**Issue by ghost** [WhisperSystems/Signal-Android#4958]
1. Send a panoramic picture
2. Open it

I think it's because of the compression, but I don't think their dimension should be reduced this much. I am barely able to tell if it's the same picture I sent.

**Comment by 2-4601** [comment]
Related #4380.

**Comment by x12x** [comment]
That's not very related, I can see the image "properly". I mean, I can't see much but it's not just a black image.

**Comment by peterpanondrugs** [comment]
Android 6.0.1, Signal 3.16.0
https://gist.github.com/anonymous/72f80d600cde3af8be49cc928b8d895f
