### ISSUE TITLE
[UX] The text under camera in the attachment menu is not aligned.

### ISSUE THREAD

**Issue by mimi89999** [WhisperSystems/Signal-Android#4959]
The text under camera in the attachment menu is not aligned. Look at my screenshot.
![screen](https://cloud.githubusercontent.com/assets/8530546/11997462/810e7fba-aa7c-11e5-9025-dd60a6f6bd33.png)
Device info: Samsung Galaxy S4 mini, CM13

**Comment by McLoo** [comment]
Make a multi line issue. 
(French needs even more space than German 😊)
