### ISSUE TITLE
Support Tamil

### ISSUE THREAD

**Issue by kracekumar** [WhisperSystems/Signal-Android#4960]
I am updating the translation for [Tamil](https://www.transifex.com/moxie/signal-android/translate/#ta/master/50704466). What is the minimum cutoff required to support Tamil ? As per old [issue](https://github.com/WhisperSystems/Signal-Android/pull/3773), does 90% still hold true ?.

If the translation reaches 90%, will support be added automatically or one need to open an issue ?

**Comment by McLoo** [comment]
If you reach 90%, don't stop and proceed to 100% 😨

The 90% minimum limit is set for the import from transifex  and therefore it will be pull automatically the next time after reaching the limit. 
The automatic language selection works out of the box then, but the entry for the manual selection needs to be added in the arrays.xml (entry and value)
