### ISSUE TITLE
Call doesn't get through

### ISSUE THREAD

**Issue by ndurner** [WhisperSystems/Signal-Android#4967]
Calls between two Android devices (cyanogen & MIUI) always fail.

https://gist.github.com/anonymous/3511d10a7cbe92998834

**Comment by johanw666** [comment]
I had issues with that too, iOS to Android didn't get trough, although I later received a "missed call" message. Android to iOS came through but the other side didn't hear me. One Android to another worked, the other way around it didn't work.

Sounds like a server issue to me. This has worked in the past, with the same Signal versions, so I doubt it's a bug in Signal.

**Comment by 2-4601** [comment]
Related or duplicate of #4933. Logs have same exceptions.

**Comment by moxie0** [comment]
Something weird with your ROM's audio subsystem. There's another issue somewhere on here with the same thing.

**Comment by 2-4601** [comment]
That would be #4933, closing as dupe of that.
