### ISSUE TITLE
Group chat not supported

### ISSUE THREAD

**Issue by sedrubal** [WhisperSystems/Signal-Android#4969]
A friend wanted to start a new group chat and wanted to add me and some others but got a notification, that my client does not support group chat. I'm member of at least one other group conversation and I can get and send messages.

**Device Info:** Nexus 5, Omnirom 5.5.1, Signal 3.8.1 (Btw. why is this tag not present on github?)

**App state:** Push registered, SMS/MMS disabled, Privacy off

**Comment by Jens14L** [comment]
Paste the URL(s) for the log(s) (see Signal options), please?

Could you reproduce the error? (Let your friend delete the group and create the group with the same attributes again.)

**Comment by 2-4601** [comment]
Is your friend a new Signal user?

**Comment by sedrubal** [comment]
Ah I'm sorry. We found out that he tried to add my old number which isn't connected to a signal account. Can you maybe highlight signal user in the drop down when creating new groups or simply not show non-signal-numbers?

**Comment by 2-4601** [comment]
Signal contacts are already highlighted with blue capital letters.
Non-Signal users are not shown if Signal is not the default SMS app.
