### ISSUE TITLE
Direct capture front camera preview different compared to taken picture

### ISSUE THREAD

**Issue by billie80** [WhisperSystems/Signal-Android#4972]
When taking a picture with the front camera using direct capture in collapsed state the resulting image is different compared to the preview.
The preview shows the lower portion from a full screen capture, while the resulting image is from the middle portion of a full screen capture.

I will try to explain the issue with an image series.

The first one is an image of the phone with the camera preview. Note the detail marked with the red circle in the upper right corner.

![tmp_18514-2015-12-26 23 47 43-2040068800](https://cloud.githubusercontent.com/assets/9938306/12009736/ca024246-ac85-11e5-98fe-50abfaf9af49.jpg)

The next one is the preview of the taken picture. Note the detail mentioned before is now in the lower left corner.

![tmp_18514-2015-12-26 23 46 481570556342](https://cloud.githubusercontent.com/assets/9938306/12009753/c5080ffe-ac86-11e5-8997-d03cb10290c6.jpg)

I wanted to take a screenshot from the camera preview but strangely the screenshot shows the view like for the taken picture. This is why the first pictures a not screenshots. See the third picture.

![tmp_18514-2015-12-26 23 50 42-109390329](https://cloud.githubusercontent.com/assets/9938306/12009755/db73deb2-ac86-11e5-9780-cfb9c32cc4f9.png)

The last image is a full screen capture of the same scene. I suppose the region in the camera preview is different to the final region applied.

![tmp_18514-2015-12-26 23 51 42-2006969739](https://cloud.githubusercontent.com/assets/9938306/12009756/e8b3729a-ac86-11e5-934c-bf7e4787f0ea.png)

This happens only with the front camera using direct capture in collapsed state. The back camera works as expected.

Device info: Samsung Galaxy S5 Mini, Stock Android 4.4.2, Signal 3.8.1

Debug log: https://gist.github.com/anonymous/b3bc25fd68eb6fc8bec2

**Comment by 2-4601** [comment]
Great illustrations! Is this the same as #4715?

**Comment by billie80** [comment]
Yes you are right. It is the same issue. I thought I have seen a report about this but found nothing while searching for existing issues. Probably I did not search that far back for closed issues.

So it looks like there are more devices affected by this.

Strange thing is that a screenshot does not expose this behaviour.

**Comment by 2-4601** [comment]
All right, let's use that issue to track this bug because it has more data.
Could you post your illustrations to #4715?
