### ISSUE TITLE
Location message fails when no gps fix

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/Signal-Android#4978]
When try I send a location message and have no gps fix, it fails without giving any feedback on what's wrong.

Debug log: https://gist.github.com/anonymous/1e1941ebce8369c828a9

I saw some dependency changes in the manifest file, so perhaps this info is usefull as well: Google Maps 7.7.0 (came with the device, never upgraded), Google Play Services 8.4.89.

**Comment by agrajaghh** [comment]
self-build version? maybe its #4949?

**Comment by johanw666** [comment]
Yes, self built (I always add .x-JW to the version number string of my self built versions to make clear which version I'm running). Since there is an API key in the manifest file (I was surprised to be honest that is was there) I assumed it should work. I'll try building a new version after requesting an api key.
