### ISSUE TITLE
Location message zoom level always the same

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#4980]
No matter what you zoom level is set in the picker,
the image always has the same (default?) zoom level.

**Comment by McLoo** [comment]
![screenshot_2015-12-28-13-31-03](https://cloud.githubusercontent.com/assets/5326916/12018742/5c90dd0c-ad67-11e5-9881-20f4f9a4a0e2.png)
![screenshot_2015-12-28-13-31-14](https://cloud.githubusercontent.com/assets/5326916/12018741/5c8ef5dc-ad67-11e5-9cf6-2ff2978c367f.png)

**Comment by moxie0** [comment]
Yeah, that's just how that's gonna be.  =(

**Comment by heyimgay** [comment]
This could probably be fixed if we're using some open street maps implementation instead of Google's.

@moxie0 would you accept a PR changing the provider and fixing this?

**Comment by moxie0** [comment]
@heyimgay Probably not, it'd be a huge amount of work to rewrite the place picker and I doubt OSM has that capability. It'd be much easier just to write our own place picker implementation using google maps.
