### ISSUE TITLE
Call name, number, and status are obstructed by volume change menu Galaxy S4

### ISSUE THREAD

**Issue by kb100** [WhisperSystems/Signal-Android#4982]
I'm running a stock Galaxy S4. When making a signal call, pressing the volume up/down button brings up the system volume menu, which appears directly on top the name and number of the person being called, as well as the call status (ringing, performing handshake, etc.). The system phone app also suffers from this, but I think Signal can do better. I am not able to take a screenshot as taking a screenshot closes the volume menu.

A few solutions:

-  Move the system volume menu down slightly
-  Move the call info/status up slightly or down a lot
-  Block system menu from appearing, put volume controls on in-call menu

**Comment by moxie0** [comment]
Thanks but we're not going to do this
