### ISSUE TITLE
Using AdBlock (localhost proxy) and Signal

### ISSUE THREAD

**Issue by akaleeroy** [WhisperSystems/Signal-Android#4986]
I noticed I couldn't send media from Signal, even though text was going through. I figured it's AdBlock, which runs a localhost proxy on my phone, and it was. I turned it off and Signal was able to send pictures and audio without a hitch.

Now I would just like to know, is there a way to __bypass the proxy for Signal?__
Can I just bypass certain domains in the network settings?

![Bypass proxy suggesting domains in Android's WiFi settings](http://i.imgur.com/arj3Za0.png)

HTC phone with Android 4.1.2, not rooted.

**Comment by moxie0** [comment]
Sorry this isn't a discussion forum, please write to support for support questions, or the mailing list for discussion.
