### ISSUE TITLE
“Your build of textsecure has expired”; Signal Update Not Working in Play Store

### ISSUE THREAD

**Issue by Vartigoan** [WhisperSystems/Signal-Android#4992]
My girlfriend has my old Galaxy S4 and upgraded to the very last version of TextSecure. Today she got a message stating the following:

“Your build of textsecure has expired.”

When she tries to update to Signal, the Playstore progress bar hangs forever.  Everything else on the phone  (including the Playstore) is working except the Signal update.  Can you please help? Nothing is working so far.

Her phone is running the version of Android that preceded Kitkat.  Whatever the last update for the Galaxy S4 official version might have been, she’s got that.

She's also looking for an SMS backup utility that works with TextSecure if she can't get the Signal upgrade to work and has to uninstall.

**Comment by moxie0** [comment]
This sounds like a problem with the play store, not signal.  In any case, the best place for support questions is support@whispersystems.org, thanks!

**Comment by neurotensin** [comment]
Hi, I'm getting a "your version expires in 9 days message". If this is the store, anyway we can get rid of the annoying banner? Or is this google trying to drum up more business?

**Comment by nrizzio** [comment]
@neurotensin See #5609 - this problem will go away soon, when Moxie gets around to updating Signal in the next week.
