### ISSUE TITLE
Signal cannot connect even though it just did

### ISSUE THREAD

**Issue by lgommans** [WhisperSystems/Signal-Android#4994]
System info: Cyanogenmod based on Android 4.4

Steps to reproduce:

1. Install Signal from the Play Store and open it

2. Enter phone number and hit register

It now shows a couple of steps: connect to server, waiting for sms, generating keys and something else (I annoyingly can't make a screenshot, a bug exclusive to this app). The connect to server (to request an SMS) succeeds. Then SMS arrives and Signal goes on to generate keys. When that finishes, which is really quick, it complains about not being able to connect to the server.

Wait, what? It can contact the servers to send an SMS but is then unable to contact the server? I guess it must be a bug.

**Comment by 2-4601** [comment]
Please post a debug log immediately after the error.

In the registration process there's a menu item where you can capture a debug log.

Or if you can get in the main conversation list then **Settings -> Advanced -> Submit debug log**

Paste the link here.

**Comment by lgommans** [comment]
There is no menu, not even when I hit the menu button on my device, anywhere in the registration process. The only clickable things are my country, the twilio ad, the register button, and "edit +31[phonenumber]" after it failed.

**Comment by 2-4601** [comment]
Sorry, I remembered wrong, Just tested on my 4.0.4 and there's indeed no menu for debug log while registering.

What happens after the error? Do you get to the main conversation list? It has a blueish top bar and the text Signal in it. Bottom right corner has a blue circle with a white pen in it?
If you see this you can submit a debug log from **Settings -> Advanced -> Submit debug log**

**Comment by lgommans** [comment]
No, I do not get into that screen so cannot give you a debug log. I might be able to get adb or do something with root if that'd help?

After the error really only the option for me is to change the number and try again. I am not even given an option to try again without having to put my phone number in anew. 

-----Original Message-----

**Comment by mimi89999** [comment]
@lgommans Do you know how to save a logcat?

**Comment by 2-4601** [comment]
@lgommans If you have `adb` installed you can capture the log with `adb logcat` while going through the registration.
Root not required.

**Comment by Frankstar** [comment]
just got the same error.
But i could connect with wifi.

**Comment by matzefisi** [comment]
Same problem here. Also Wifi is not working. Maybe worth to know: I was already registered with Signal on that device, but I tried to reinstall it because I got no new notifications.

**Comment by matzefisi** [comment]
Hi guys, I had to reset my S5 today anyway and now it´s working again. So this error is maybe because of some artifacts of Signal which remain on the phone, even if you remove the app?

**Comment by Frankstar** [comment]
see last Posts from here https://github.com/WhisperSystems/Signal-Android/issues/970#issuecomment-168635128

**Comment by lgommans** [comment]
This issue was referenced from #970 saying something about Google Play Services. I did not know that besides a trillion permissions, it *also* does something with Google. For the messenger that everyone says is the best with encryption and privacy, this looks pretty terrible.

After disabling the firewall system-wide and reinstalling the app (just to be sure), registering works. I just re-enabled the firewall and everything still seems to work.

**Comment by Frankstar** [comment]
yes, its was me - afte re-read the topic i realized im mixing up two different problems and deleted the reference.

By the Way - Singal is Using GCM (Google Cloud Messaging) - and that is avaible over Google Play Services.

**Comment by lgommans** [comment]
It doesn't seem to be necessary to send or receive messages, or is it? I tested by sending a message to myself, but I guess Signal might have detected that it's me and not actually sent it over the network.

**Comment by Frankstar** [comment]
well, if you are speaking in context of this Problem - i dont know - but i dont think it is.
Thats why i said i mixed up two complete different problems.
