### ISSUE TITLE
Signal will not use permissions with Privacy Guard enabled, nor prompt for confirmation code

### ISSUE THREAD

**Issue by lgommans** [WhisperSystems/Signal-Android#4995]
Cyanogenmod's Privacy Guard has three settings for each permission: Allow, Ask Each Time, or Deny. When set to Ask Each Time it will ask you, every time the app uses the permission, whether you want to allow that. Signal however will not even try.

I don't want Signal to read incoming SMS messages so I ask it to Ask. If it then wants to read the incoming text message, it can ask me, and I can either deny or allow it for that one instance (like when I'm actually waiting for Signal's registration text, I would allow it). Instead, Signal doesn't even try to read incoming texts anymore. This is the first app I ever encountered whose behavior changes after setting it to Ask instead of Allow, so it's probably a bug in Signal (or a feature, if you wrote code to check for permissions).

So if it doesn't even try to use the permission because apparently it assumes it's disallowed or it broke or something, then I would expect a box to be there where I can put in the confirmation code. In fact I'd always expect that box to be there, regardless of whether the app thinks it got its shit together, but that's a separate discussion. Instead what Signal does is let the time expire, then you can request a call (which works), then I reject the call, and then finally I can put in the confirmation code.

(And then what? It says "could not connect to server" -- no, right, you only requested an SMS and a call and that worked just fine -- but see my other issue for that.)

**Comment by moxie0** [comment]
Whatever CM is doing is not "standard," in the sense that there's no way to "request" a permission on <M.  So it sounds like a CM bug to me.
