### ISSUE TITLE
unable to connect to the push service

### ISSUE THREAD

**Issue by cayba** [WhisperSystems/Signal-Android#4996]
i want to build my own secure messagging service (TextSecure Server+PushServer+Android App+another necessary project) How can i run TextSecure Server on my Server? first i built WebSocket-Resources with maven. second i built TextSecure Server.(mvn clean install -DskipTests) after i run java -jar target/textsecure-server.jar server config/server.yml

and

i changed

buildConfigField "String", "TEXTSECURE_URL", "\"https://my_server_ip:8080\""
line in build.gradle file (Android App)

but i got error first error (client,) -> Connectivity Error.... was unable to connect to the push service

second error(textsecure-server)--->

WARN [2015-12-01 13:45:43,789] org.eclipse.jetty.http.HttpParser: Illegal character 0x16 in state=START for buffer HeapByteBuffer@4c112d16[p=1,l=208,c=8192,r=207]={\x16<<<\x03\x01\x00\xCb\x01\x00\x00\xC7\x03\x01V]\xA4\xC1\x08e\xC6...\x01\x00\x02\x00\x03\x00\x0f\x00\x10\x00\x11\x00#\x00\x00>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00} WARN [2015-12-01 13:45:43,789] org.eclipse.jetty.http.HttpParser: badMessage: 400 Illegal character 0x16 for HttpChannelOverHttp@3669e012{r=0,c=false,a=IDLE,uri=-} WARN [2015-12-01 13:45:43,795] org.eclipse.jetty.http.HttpParser: Illegal character 0x16 in state=START for buffer HeapByteBuffer@86064c8[p=1,l=118,c=8192,r=117]={\x16<<<\x03\x00\x00q\x01\x00\x00m\x03\x00V]\xA4\xC1\xAe\x9a\xEf...\x15\x00\x12\x00\x03\x00\x08\x00\x14\x00\x11\x00\xFf\x01\x00>>>e\r\n\r\n\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00} WARN [2015-12-01 13:45:43,796] org.eclipse.jetty.http.HttpParser: badMessage: 400 Illegal character 0x16 for HttpChannelOverHttp@6fdc750b{r=0,c=false,a=IDLE,uri=-}
what can i do?

**Comment by 2-4601** [comment]
Sorry @cayba but the server is not officially supported. This tracker is for Android client related bugs and features requests only.
Try the mailing list instead https://lists.riseup.net/www/info/whispersystems (hint: search the archives)

**Comment by s2deathgod** [comment]
I have same problem. so cayba now you solved ? If yes please tell me.
