### ISSUE TITLE
Limit of 2 linked devices

### ISSUE THREAD

**Issue by jzbz** [WhisperSystems/Signal-Android#4997]
When attempting to link a third instance of Signal Desktop through Signal Android I received an error informing me of the limit of two and suggesting I remove one of the previously linked devices. Is the limit in place due to technical limitations? If not is there any chance of it being raised? Thanks.

**Comment by nrizzio** [comment]
Look at TextSecure-Server/59

**Comment by jzbz** [comment]
Seen, thanks.

**Comment by e12e** [comment]
Apparently WhisperSystems/TextSecure have disabled issues? Where can I find the text from the above linked issue?

I have a laptop and a dual-booting desktop, so it'd be nice to be able to use Signal desktop with those.
