### ISSUE TITLE
"Internet connexion required" warning

### ISSUE THREAD

**Issue by liar666** [WhisperSystems/Signal-Android#4999]
Hi,

First of all, thanks for acting for our privacy.

I'm having a phone that is very seldomly connected to internet. 

I installed "Signal" and started using it before realizing that the cyphered SMS/MMS/Calls required internet conection (Wifi, 4G, etc.) to work and that my friends did not receive my messages.

This is not normal! There should be plenty of warnings telling users that the cyphered parts of the software ONLY work when an internet connexion is up&running. Warning can be placed: when installing, when sending a message,etc.

**Comment by moxie0** [comment]
thanks but we're not going to do this
