### ISSUE TITLE
Outgoing cyphered message not sent but GUI says so 

### ISSUE THREAD

**Issue by liar666** [WhisperSystems/Signal-Android#5000]
Hi,

My phone is rarely connected to the Internet. 

When I send a cyphered message, the GUI tells me everything is OK (double check mark is shown, date of departure is "right now"/"à l'instant" - in French -, etc) even if there is no internet connection and the message has not left my device!
There should be, at least, a warning that the message has not been sent, better, that an internet connection is required, or even better, a proposition to start a connection (Wifi/4G/...) or an automatic opening/closing of a connection just to send the message.

**Comment by agrajaghh** [comment]
how do you know it was an encrpyted message? Does it have the little padlock?

The double checkmark means that the message was received, so it has been sent (either you had internet or it was a SMS)
