### ISSUE TITLE
Answer to a non-cyphered message is cyphered

### ISSUE THREAD

**Issue by liar666** [WhisperSystems/Signal-Android#5001]
Hi,

As I said in previous bug reports (https://github.com/WhisperSystems/Signal-Android/issues/4999), my phone is seldomly connected to the internet and cyphered messages are not sent if no connection is up&running.

As a consequence, when I have no internet connection and I want to contact a friend, I sent a non-cyphered SMS. "Unfortunately", when my friend replies to such a message, Signal sends a cyphered response. Since I have no connection, I cannot receive it :[

I think that using crypto by default is a good idea, but warning the user that she is replying in a different mode than the one used by the sender would be welcome.

**Comment by moxie0** [comment]
thanks but we're not going to do this, you can long-press the send button to swtich to SMS if you'd like
