### ISSUE TITLE
Forwarded message empty if recipient selected via search

### ISSUE THREAD

**Issue by merkste** [WhisperSystems/Signal-Android#5006]
1. select message, chose forward from the menu
2. lookup recipient via search
3. conversation opens but message draft is empty

Signal 3.8.1, Moto G 3rd gen

**Comment by 2-4601** [comment]
Closing as duplicate of #4797 (fixed in 3.9)

**Comment by merkste** [comment]
Sorry for the dupe. Probably I searched open issues only.
