### ISSUE TITLE
Disconcerting 'X is on Signal, say hey!' notifications

### ISSUE THREAD

**Issue by brbsix** [WhisperSystems/Signal-Android#5009]
I'm submitting this report on behalf of a concerned friend.

Their phone is setup in such a way that many of the contacts stored in the phone are not to be contacted directly (i.e. via the phone number registered with WhisperSystems). These contacts are *only* to be contacted via some off channel (email, other phone, etc).

Anyways, upon installing or updating (I don't recall which it was) to the latest version of Signal, they received a number of 'X is on Signal, say hey!' notifications. Obviously this was very disconcerting, as the first thought was that people on the other end might be receiving similar notifications. Is that the case, or are they "one-way" in the sense that you only receive notifications for numbers that you already have in your contacts? Surely Signal isn't leaking contact details to third-party users...

This seemed to be very un-Signal like behavior and the person in question was concerned enough to consider discontinuing use of the app. I wanted to find out more regarding this behavior beforehand, as this issue is very unclear. Perhaps there is some way to opt-out of this (or preferably make it opt-in)? Some clarification would be much appreciated! Thanks for the awesome product by the way.

**Comment by mammuth** [comment]
This is an issue tracker, no support center. 

In short: 
If the android app locally detects that one of your non-signal-contacts has registered with signal recently it triggers this notification. 

There is no need to be afraid due to any privacy concerns, since it's no critical information who is using signal and who not. 

You might shout out at support@whispersystems.org, the guys can greatly explain you everything.

Please close this issue.

**Comment by pnathan** [comment]
This is actually a meaningful information leakage issue, since it directly instructs your contacts (who may have Signal), that you are attempting to use covert messaging. It's like raising a flag and shouting to your network "HEY HEY HEY I AM DOING SECRET STUFF OK?".

**Comment by 2-4601** [comment]
Like @mammuth pointed out this is an issue tracker.
For discussion you can go to https://whispersystems.discoursehosting.net/
