### ISSUE TITLE
Signal location message fail to auto-snap to more precise locations

### ISSUE THREAD

**Issue by Norbert80** [WhisperSystems/Signal-Android#5010]
Hi,

Signal 3.9.0 introduces location messages. While generating such a location message the phone starts GPS service of the device. Typically position precision increases after several seconds in several steps. But Signal stays at the very first  (inaccurate) position.

Other messengers like Telegram keep track on position updates and always auto-snap to the newest (typically most accurate) position.

In Signal I have to press the center button several times before sending the location message in order to send an exact position.

It would be great if Signal supports auto-snap like other messengers.

**Comment by Norbert80** [comment]
@moxie0 Build 3.9.1 is still affected by this issue.

**Comment by scienmind** [comment]
I'd rather suggest against "location auto-snapping".

While it may sound convenient for sharing "your" location, it will prevent sending "custom location", i.e. sending a location that is not where you actually are - such as meet up location you're heading to, etc...

**Comment by Norbert80** [comment]
Nope. Please try Telegram. Telegram has auto-snap enabled initially. The user can move the map to any position which is disabling auto-snap. Auto-snap is enabled again after pressing the go-to-current-position-button.

This is exactly like Signal should also behave.

**Comment by moxie0** [comment]
thanks but we're not going to do this

**Comment by Norbert80** [comment]
@moxie0 could you please leave a comment why you don't plan implement it. Knowing reasons for decisions makes contribution more fun.

I just would like to know if you don't prefer the requested behaviour or if it is more a lack of resources. Thanks in advance.
