### ISSUE TITLE
Delete and renegotiate identity / error in "verify identity"

### ISSUE THREAD

**Issue by vitoller** [WhisperSystems/Signal-Android#5012]
Signal 3.8.1 on Android 5.1

Background:
I played with textsecure command line client (https://github.com/janimo/textsecure). This did reset my identity (key).

After doing that I now have the problem that I can not have a secure conversation with contacts. I would expect to have an option to delete paring information.

Also: When the other contact used my new identity in the "verify the connection" option it crashed Signal.

=====
Procedure to reproduce:
1. start secure conversation between phone A and phone B
2. force new identity on phone A

3 A: it is not possible to delete the identities (and reconnect) on A & B
3 B: verify identity on phone B crashes the application

**Comment by 2-4601** [comment]
Closing in favour of #5057.
