### ISSUE TITLE
"Mute until" time values left in database after expiration

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#5013]
Found this in the log  for 3.9.0.  Looks like Mute settings are staying in the db after expiration as I have no conversations muted and if that's a Unix timestamp it's in the past.

I/Timeline(27857): Timeline: Activity_idle id: android.os.BinderProxy@3712368a time:17220266
W/RecipientPreferenceDatabase(27857): Muted until: 0
W/RecipientPreferenceDatabase(27857): Muted until: 0
W/RecipientPreferenceDatabase(27857): Muted until: 1451097303190
W/RecipientPreferenceDatabase(27857): Muted until: 1451097303190
W/RecipientPreferenceDatabase(27857): Muted until: 0
W/RecipientPreferenceDatabase(27857): Muted until: 0
W/RecipientPreferenceDatabase(27857): Muted until: 0
W/RecipientPreferenceDatabase(27857): Muted until: 0
W/RecipientPreferenceDatabase(27857): Muted until: 0
W/RecipientPreferenceDatabase(27857): Muted until: 0
W/RecipientPreferenceDatabase(27857): Muted until: 0

**Comment by moxie0** [comment]
what is the issue you're experiencing?

**Comment by jeremymasters** [comment]
I just saw it in the logs when I was perusing them because I sometimes face an issue where an SMS will fail to send for no apparent reason but that's unrelated to this IMO.  Just noted it as data left lying around and thought I'd mention it.  If you feel it's not worth dealing with I can close it.  I just know how left-over data in a database can be misleading and foul future stuff up sometimes.  Not trying to be pedantic or idealogical.

**Comment by moxie0** [comment]
It sounds like you aren't having an issue, so I'm going to close this.
