### ISSUE TITLE
Outgoing messages sent via IFTTT are not present in Signal

### ISSUE THREAD

**Issue by msturgill** [WhisperSystems/Signal-Android#5014]
SMS sent via the IFTTT Android SMS channel are present in other messaging applications installed on the device, but not in Signal (Signal is the default messaging application).

**Comment by msturgill** [comment]
On the same note, if one uses 'OK Google' functionality to send an SMS, that message is also not present in Signal.

Example: 'OK Google, send a text to John Smith telling him that I'm running late'

**Comment by moxie0** [comment]
Correct, Signal does not use the system SMS database.

**Comment by msturgill** [comment]
I am aware of that. That being said, by offering to become the default SMS application on a device I would expect Signal to at least attempt to maintain some degree  of functional parity.

IFTTT is probably a bad example, but 'OK Google' is ubiquitous.

Is there another open issue that addresses this, or is this issue closure a WONTFIX.

**Comment by msturgill** [comment]
Looks like #4037 is the same issue.

There are a few other applications that can hook outgoing SMS, I'm not sure why Signal couldn't do something similar to catch these edge-cases and bring them into the Signal environment.

It's certainly an annoyance to have missing context in a conversation. It's also not fun to find a few random outgoing messages floating around in the stock messenger when you expect them to all be in Signal.

**Comment by msturgill** [comment]
Hooking should be possible, i.e. https://ifttt.com/channels/android_messages/triggers/1143127988-any-new-sms-sent (note I understand there is a lot of functionality not possible with Signal due to security, I'm just using this as an example of hooking a stock outgoing SMS).

I guess I envision something like:

void onMessageSend(Message m)
{
if (signalIsDefaultMessagingApp && signalSettingCatchExternalMessage)
{
// block sending and send via signal if possible (secure with sms fallback)
// -- or if the hook only occurs after the message is actually sent --
// add to signal's database as a new outgoing SMS

// if we can't actually block the message from being sent and send it ourselves, remove it from the stock db
if (signalSettingRemoveExternalMessagesAfterHandling)
{
// remove from stock db
}
}
