### ISSUE TITLE
Error sending pictures

### ISSUE THREAD

**Issue by Eyowen** [WhisperSystems/Signal-Android#5024]
Unfortunately I am not able to send any pictures out of signal. I tried this with several WIFIs. However, I am not connected thru mobile data, only over WIFI. Sending text messages is no problem and I am receiving pictures from my friends, too. 

I am not writing about MMS, just attached pictures (with or without text) between internal, encrypted friends. 

You can find my log hier: https://gist.github.com/anonymous/e38cdfeea4fe400dd5dc

Any recommandation is higly appreciated.

**Comment by moxie0** [comment]
looks like your network is killing connections to s3
