### ISSUE TITLE
Turkish description of the Signal app for Android

### ISSUE THREAD

**Issue by canerbasaran** [WhisperSystems/Signal-Android#5029]
Signal gizliliği kolaylaştırır. Ücretsiz Metin mesajları, Resimler ve Grup mesajları gönderin!

Gizlilik mümkün, Signal bunu kolaylaştırır.

Signal kullanarak, SMS ücreti ödemeden anında iletişim kurabilir, grup oluşturarak aynı anda tüm arkadaşlarınızla gerçek zamanlı olarak sohbet edebilir ve tam bir gizlilik altında medya paylaşımı yapabilirsiniz. Sunucunun iletişiminize erişimi yoktur ve sizinle ilgili herhangi bir veriyi asla depolamaz.

★ İstediğini söyle. Signal her zaman, her mesaj için gizlilik sağlayan uçtan uca gelişmiş bir şifreleme protokolü kullanır.

★ Özgür ve açık kaynak yazılım. Herkese, Signal'in güvenliğini doğrulamak için kodu denetleme olanağı sağlar. Signal, mesajlarınızı güvenli tutmak için şifreleme protokolleri kullanan açık kaynak kodlu tek uygulamadır.

★ Kendin ol - Signal mevcut telefon numaranı ve adres defterini kullanır. Hesabını yönetmek için ayrı olarak oturum açma, kullanıcı adı, şifre veya PIN'a ihtiyaç duymaz.

★ Grup Sohbeti. Signal tüm arkadaşlarınızla özel konuşmalar için şifreli gruplar oluşturmanıza olanak sağlar. Sadece şifrelenmiş mesajlar değil, Signal sunucusunun aynı zamanda üyelik listesi, grup başlığı veya grup simgesi gibi herhangi bir grup meta verisine de erişimi yoktur.

★ Hızlı. Signal protokolü mümkün olan en kısıtlı ortamlarda çalışmak üzere tasarlanmıştır. Signal kullanılarak, mesajlar arkadaşlarınıza anında teslim edilir.

★ Serbestçe konuşun - Hiçbir ücret olmadan, şehir genelinde yaşayan ya da dünyanın öbür ucundaki insanlarla kristal berraklığında telefon görüşmeleri yapın.

* (Uygulamanın bazı özellikleri internet bağlantısı gerektirir, veri ücreti uygulanabilir. Detaylar için operatörünüzle iletişime geçin.)

Signal henüz tablet ile uyumlu değil, ancak daha büyük ekranlar için çalışmalarımız sürüyor ve gelecekteki bir sürümde bu destek eklenecektir!

Destek, sorularınız veya daha fazla bilgi için, lütfen bu adresi ziyaret edin: http://support.whispersystems.org

Daha fazla ayrıntı için:
http://www.whispersystems.org/#encrypted_texts

Kaynak kodu:
https://github.com/WhisperSystems/Signal-Android

**Comment by moxie0** [comment]
thanks but we don't localize the description
