### ISSUE TITLE
no communication on dual sim phone when the not used sim has 0 asu

### ISSUE THREAD

**Issue by maehschaf** [WhisperSystems/Signal-Android#5032]
Hello community,

I use signal 3.8.1 on android 5.1.1 on a dual sim S6 (SM-G920F).

I configured the first SIM for telephony and SMS only. The second SIM is for mobile data.

When the firs SIM has no net connection, signal refuses to send messages although the second SIM (which I supposed it to use) has good quality connection.

Is this possible?

I found out by search that there have been some other issues about dual sim, but I did not find exactly this one.

Thanks a lot & a happy new year!
Martin

**Comment by 2-4601** [comment]
Thanks, #555 is used for tracking this dual SIM thing so closing this a duplicate.
AFAIK the situation you are describing falls under the general fact that dual SIM devices currently don't work as expeceted with Signal.
