### ISSUE TITLE
Can't set Signal as default SMS app

### ISSUE THREAD

**Issue by TheNain38** [WhisperSystems/Signal-Android#5033]
The device is a TCL-M3G.

**Comment by 2-4601** [comment]
Could you post a debug log immediately after you try to set Signal the default SMS app?

**Settings -> Advanced -> Submit debug log**
and paste the link here

**Comment by TheNain38** [comment]
In reality, in the system settings Signal isn't in the choices for a default SMS app

**Comment by 2-4601** [comment]
How about in Signal **Settings -> SMS and SMS ->** _Touch to make signal your default SMS app_

[It seems](http://www.gearbest.com/cell-phones/pp_203567.html) that your phone is a dual SIM device. They are know to have issues with Signal, see #555.

**Comment by espinozagabe** [comment]
I'm having this issue as well and. I have a Nexus 6 which is not a dual sim device. If you wouldn't mind telling me how to submit a debug log I would love to help.

**Comment by 2-4601** [comment]
**Settings -> Advanced -> Submit debug log**
and paste the link here

More detailed guide:
http://support.whispersystems.org/hc/en-us/articles/212535838-How-do-I-send-a-debug-log-

**Comment by espinozagabe** [comment]
Ok thanks for the response.

As previously mentioned I am using a Nexus 6. Running Android Version 6.0.1. 

The Signal Version I am using is 3.8.1.

Signal Messenger was set as my default messenger. So I removed it as the default and restarted the app. I then set it as my default again and submitted the debug log.

Heres the debug log: https://gist.github.com/258ce790fdc17cf84967

**Comment by 2-4601** [comment]
> Signal Messenger was set as my default messenger. So I removed it as the default and restarted the app. I then set it as my default again and submitted the debug log.

Hmmm... I'm not quite following. This issue is not being able to set Signal as the default SMS app, however you said it **was the default**? And then you **set it as default** again?

**Comment by espinozagabe** [comment]
Sorry, I realise my post came across a bit confusing. My issue is that incoming SMS messages will go through hangouts instead of Signal, which was set as my default.

Since Signal was set as my default messenger already I removed it as the default just so I could add it as the default again before sending the debug log.

**Comment by espinozagabe** [comment]
I must not have been paying attention very well either because I just realised this issue is for not being able to set Signal as the default app at all lol.

I realise now my issue is actually a bit different. I am able to set Signal as the default messaging app, however none of my SMS messages come through Signal. Instead they continue to come through Hangouts which was my previous default messenger. Let me know if I should make a different issue thred for this.

**Comment by 2-4601** [comment]
@espinozagabe Yeah, it would be better for clarity if you posted your case as a new issue. Also please search for duplicates in existing issues before you do. I don't know if there are any but there could be. Thanks!

Closing this as a dual SIM issue.

**Comment by webzorg** [comment]
https://gist.github.com/d896ee874defa71d3ed78ac7935fa23f
my phone is lenovo s989t+, dual sim. I suspect my phone has no setting for setting default phone/sms or contact app, how can I avoid this?

**Comment by riyapenn** [comment]
@espinozagabe Are you expecting to send/receive SMS from a Google Voice number or is it to the number attached to your SIM.  Write to support@whispersystems.org  (Also related if it's a GV number http://support.whispersystems.org/hc/en-us/articles/213980898-How-does-Signal-work-with-my-Google-Voice-number-when-I-send-SMS-)

@webzorg Dual Sim is supported for Android 5.1 and higher. Contact support@whispersystems.org to troubleshoot if Signal is not available as the default for at least one SIM.  See http://support.whispersystems.org/hc/en-us/articles/216786548-I-am-on-a-multi-SIM-device-and-my-messages-are-not-sending-What-do-I-do-
