### ISSUE TITLE
Check if Identical Publickey is send back at keyexchange

### ISSUE THREAD

**Issue by henrykratom** [WhisperSystems/Signal-Android#5035]
Hello there i noticed that in SMSSecure (i know where i am) there is kind of a glitch that, if you send out a key-exchange message to a non-SMSSecure user and sayed User forwards you that exact Message, the communication is afterwards shown to be encrypted which it most-likely is but with the own publickey which will result in more gibberish being send to the user.

I am not sure if this affects Signal too, which it probably won't as the server automatically checks if sayed user has indeed Signal installed but a basic routine that checks if the send back publickey at key-exchange is indeed not identical to ones own publickey would be appreciated.

Truth be told i am by no means a Cryptographer and can not estimate how trivial if at all such a routine would be to be implemented and even if this is something you consider important as it is a probably a rather rare occasion. 

I am just forwarding this to the crypto-guys which created the underlying protocol in the first place

Greetings, Henry Kratom

**Comment by moxie0** [comment]
not a signal issue
