### ISSUE TITLE
Android access needs

### ISSUE THREAD

**Issue by ThomasMW** [WhisperSystems/Signal-Android#5037]
Can somebody explain to me why Signal Private Messenger needs these access rights on Android?

- Identity
- Device & App History
- Location
- Provider badge permission
- SMS
- (whole other lists but seems logical)

For a messenger app it kinda asks a lot? If I remember correctly older versions didn't ask these permissions. If someone could explain, because everybody seems to be totally fine with it.

**Comment by McLoo** [comment]
I'm fine with it. Older versions also lacked of some features ^^
Did you also check other messengers? They are all pretty equal in there hunger for permissions...

Anyway this is a duplicate. You might have found some issues by searching:

#4274
and like @2-4601 said in #3860:
 [Duplicate](https://github.com/WhisperSystems/TextSecure/issues?utf8=%E2%9C%93&q=is%3Aissue+permissions) of #3782, #3781, #3771.
