### ISSUE TITLE
Overview of existing groups on contacts list

### ISSUE THREAD

**Issue by gerdneuman** [WhisperSystems/Signal-Android#5039]
Whenever I want to sent a Signal message to more then one person, I need to setup a new group (btw: which is not the best UX imho, a more email like way might be better with being able to have many `TO` or `CC` recipients). 

I already have about a dozen groups now. Unlike the single Signal contacts, that are visible when I tap on the "write new message" button there is no overview of currently existing groups. There is only the initial history of recent messages but for not so often used groups these vanish there quickly and are then hard to find.

Maybe there should be an extra tab on the contacts list overview. Or just all groups listed in between the Signal lists and SMS contacts would do too.

**Comment by agrajaghh** [comment]
> Whenever I want to sent a Signal message to more then one person, I need to setup a new group (btw: which is not the best UX imho, a more email like way might be better with being able to have many TO or CC recipients).

is tracked in #3301

**Comment by 2-4601** [comment]
and the rest now tracked with #6053
