### ISSUE TITLE
Use Signal without needing a phone #

### ISSUE THREAD

**Issue by raedah** [WhisperSystems/Signal-Android#5041]
Id like to be able to use signal on my wifi tablet without needing a phone #. Also, requiring a user to sign up with a unique identifier like a phone number seems to be like the first obvious identifier we would not want to require a user to submit if we are interesting in anonymity. Snowden talks about unique identifier databases. Bleep allows account creation with just a key pair. My request is not to require the user to submit identification information on a device that tracks their physical location, can be pinpointed by a stingray, and is most likely directly linked to their billing records. It also makes it a pain to keep a signal account portable when a user changes phone numbers. If a user wants to submit their phone number so that their contacts can locate them that way, fine, but as a requirement its a total game killer.

**Comment by moxie0** [comment]
this isn't a discussion forum
