### ISSUE TITLE
Better UI distinction for encrypted and non-encrypted chats

### ISSUE THREAD

**Issue by paul-schulze** [WhisperSystems/Signal-Android#5045]
At the moment there is only this text in the entry field for sending text which says "send unsecured SMS" or "Send Signal message". When I open a chat there should be something really obvious to see if I am safe to write something or if I have to be careful. 

I also noticed once that there was the wrong text. It said " Send unsecured SMS" in a preciously encrypted Signal chat, after restarting the app the text was correct.

But again, I think security/privacy is the most important feature this app has to offer. Users should see on first sight if they are on an encrypted channel. 

Also the contact list UI should be more clear about the difference of SMS vs. Signal chat.

**Comment by scienmind** [comment]
@paul-schulze, the encryption is also denoted by the "send" button: 
* blue, with locked lock on it - for encrypted signal messages
* gray, with unlocked lock on it - for unsecure SMS

(however, i won't oppose the addition of extra clues to it)

**Comment by 2-4601** [comment]
> @paul-schulze 
> I also noticed once that there was the wrong text. It said " Send unsecured SMS" in a preciously encrypted Signal chat, after restarting the app the text was correct.

That was most likely #4932.

-----

There was a fairly recent change (2.21.0) to drop colours as distinguishing the transport channel and just denote it with the compose text and colour of the send/attachment button. So it seems unlikely that more in the face option is in the plans.
Also there are lengthy issues about this #945, #1172. I think the preferred place to discuss this would be [the mailing list](https://lists.riseup.net/www/info/whispersystems).

**Comment by paul-schulze** [comment]
I understand.

But please consider this is cryptography for the masses right?

If I already find it "too hard" to see if I am on a secure channel, others will have these problems all the more.
