### ISSUE TITLE
MMS Delivery Failed to non-signal users

### ISSUE THREAD

**Issue by mc2016** [WhisperSystems/Signal-Android#5047]
I'm on a 2014 moto x running marshmallow and whenever I send an mms to someone who isn't a signal user I get a message that the delivery failed. Here is the log: https://gist.github.com/69f09e054f7b7a3acfa0

**Comment by mc2016** [comment]
Sorry, I should have mentioned that my carrier is Cricket.

**Comment by agrajaghh** [comment]
did you try it on wifi or mobile internet?

**Comment by mc2016** [comment]
Tried it on both no luck on either.

**Comment by mc2016** [comment]
Been working on this today and it looks like my VPN was the problem. I turned it off, sent an mms and it went right through. Also didn't have any trouble getting mms with VPN off. As soon as I turned it on I couldn't send or receive MMS.

It's a clunky work-around-anyone know how I can send and receive MMS with disconnecting the VPN?

**Comment by agrajaghh** [comment]
thanks for reporting back.

closing since it doesnt look like a signal issue

**Comment by mc2016** [comment]
Okay, thanks!
