### ISSUE TITLE
Can't open the settings

### ISSUE THREAD

**Issue by Blupi** [WhisperSystems/Signal-Android#5048]
On an old Wiko Cink running android 4.1.1, the app seems to run fine except that the three dots icon are never shown. Therefore, the app settings or options of a conversation cannot be open.

**Comment by 2-4601** [comment]
Looks like your phone has a capacitive menu button. Does it not open the Signal menus?

**Comment by edo0** [comment]
I've always had this kind of issue with Firefox for Android, and long-pressing the "show running apps" square button on my device does it. I checked and it also works with signal (although I have the 3 points displayed)

**Comment by Blupi** [comment]
You are correct, the capacitive button tiggers the menus. It's not my phone and I'm not used to these capacitive buttons, sorry for the bother.
