### ISSUE TITLE
"Unable to write to storage"

### ISSUE THREAD

**Issue by SyntaxNero** [WhisperSystems/Signal-Android#5049]
I am unable to save pictures to my SD card from Signal Private Messenger. I get "Unable to write to storage".
I am using a rooted N910T, running RAPTURE 6.0, Android version 5.0.1
This is a new issue. I have uninstalled Signal, wiped both Cashes, rebooted and reinstalled Signal.
The issue still persists.
Also I am unable to export a backup to storage with the same error stated above.
No new apps have been installed or removed between Signal functioning correctly and the appearance of this issue.

Please advise and thank you in advance.

https://gist.github.com/anonymous/c3a646f0108b6c3fbaf0
<script src="https://gist.github.com/anonymous/c3a646f0108b6c3fbaf0.js"></script>

[cat.TXT](https://github.com/WhisperSystems/Signal-Android/files/83924/cat.TXT)

**Comment by SyntaxNero** [comment]
Device  : samsung SM-N910T (trltetmo)
Android : 5.0.1 (N910TUVU1COD6, LRX22C.N910TUVU1COD6)
Memory  : 75M (0.00% used, 256M max)
Memclass: 256
OS Host : SWDD6308
App     : Signal 3.9.1

--------- beginning of system
V/ActivityThread(28573): updateVisibility : ActivityRecord{27ac10a8 token=android.os.BinderProxy@1da91ab7 {org.thoughtcrime.securesms/org.thoughtcrime.securesms.RoutingActivity}} show : false
V/ActivityThread(28573): updateVisibility : ActivityRecord{27ac10a8 token=android.os.BinderProxy@1da91ab7 {org.thoughtcrime.securesms/org.thoughtcrime.securesms.RoutingActivity}} show : false
V/ActivityThread(28573): updateVisibility : ActivityRecord{27ac10a8 token=android.os.BinderProxy@1da91ab7 {org.thoughtcrime.securesms/org.thoughtcrime.securesms.RoutingActivity}} show : false
V/ActivityThread(28573): updateVisibility : ActivityRecord{287f7b token=android.os.BinderProxy@375fe6ae {org.thoughtcrime.securesms/org.thoughtcrime.securesms.ConversationActivity}} show : false
--------- beginning of main
W/MessageRetrievalService(28573): Network requirement: true, active activities: 0, push pending: 0
W/MessageRetrievalService(28573): Network requirement: true, active activities: 0, push pending: 0
W/PassphraseRequiredActionBarActivity(28573): onCreate(null)
W/ExperienceUpgradeActivity(28573): getExperienceUpgrade(181)
W/PassphraseRequiredActionBarActivity(28573): routeApplicationState(), state: 0
W/PassphraseRequiredActionBarActivity(28573): initializeClearKeyReceiver()
W/DirectoryRefreshListener(28573): Scheduling for: 1452401200448
D/Activity(28573): performCreate Call secproduct feature valuefalse
D/Activity(28573): performCreate Call debug elastic valuetrue
W/PassphraseRequiredActionBarActivity(28573): onResume()
D/ResourcesManager(28573): creating new AssetManager and set to /system/priv-app/SecMms_Candy/SecMms_Candy.apk
W/KeyCachingService(28573): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
W/KeyCachingService(28573): Incrementing activity count...
W/MessageRetrievalService(28573): Active Count: 1
W/MessageRetrievalService(28573): Network requirement: true, active activities: 1, push pending: 0
W/MessageRetrievalService(28573): Making websocket connection....
W/WebSocketConnection(28573): WSC connect()...
W/OkHttpClientWrapper(28573): Connecting to: wss://textsecure-service.whispersystems.org/v1/websocket/?login=%s&password=%s
W/MessageRetrievalService(28573): Network requirement: true, active activities: 1, push pending: 0
W/MessageRetrievalService(28573): Reading message...
I/Timeline(28573): Timeline: Activity_idle id: android.os.BinderProxy@329789a5 time:74203386
D/ViewRootImpl(28573): ViewPostImeInputStage ACTION_DOWN
I/Timeline(28573): Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:74205309
W/PassphraseRequiredActionBarActivity(28573): onPause()
W/KeyCachingService(28573): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService(28573): Decrementing activity count...
W/MessageRetrievalService(28573): Active Count: 0
W/PassphraseRequiredActionBarActivity(28573): onCreate(null)
W/ExperienceUpgradeActivity(28573): getExperienceUpgrade(181)
W/PassphraseRequiredActionBarActivity(28573): routeApplicationState(), state: 0
W/PassphraseRequiredActionBarActivity(28573): initializeClearKeyReceiver()
W/ConversationActivity(28573): onCreate()
W/QuickAttachmentDrawer(28573): updateControlsView()
D/Activity(28573): performCreate Call secproduct feature valuefalse
D/Activity(28573): performCreate Call debug elastic valuetrue
W/PassphraseRequiredActionBarActivity(28573): onResume()
W/MmsSmsDatabase(28573): Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 4) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 4) ORDER BY date_received DESC LIMIT 500)
W/KeyCachingService(28573): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
W/KeyCachingService(28573): Incrementing activity count...
W/MessageRetrievalService(28573): Active Count: 1
W/KeyboardAwareLinearLayout(28573): rotation changed
W/KeyboardAwareLinearLayout(28573): onKeyboardClose()
W/MmsSmsDatabase(28573): Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (read = 0) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (read = 0) ORDER BY date_received ASC)
W/CameraView(28573): skipping layout due to zero-width/height preview size
W/RecipientPreferenceDatabase(28573): Muted until: 0
W/ThumbnailView(28573): loading part with id content://org.thoughtcrime.securesms/part/1452368556105/3, progress 0
D/OpenGLRenderer(28573): endAllStagingAnimators on 0x9a21f400 (RippleDrawable) with handle 0xb4ae42e0
I/Timeline(28573): Timeline: Activity_idle id: android.os.BinderProxy@1cd5a79f time:74205709
V/ActivityThread(28573): updateVisibility : ActivityRecord{7c489cd token=android.os.BinderProxy@329789a5 {org.thoughtcrime.securesms/org.thoughtcrime.securesms.RoutingActivity}} show : false
D/ViewRootImpl(28573): ViewPostImeInputStage ACTION_DOWN
W/WebSocketConnection(28573): onConnected()
W/ThumbnailView(28573): Not re-loading slide content://org.thoughtcrime.securesms/part/1452368556105/3
D/ViewRootImpl(28573): ViewPostImeInputStage ACTION_DOWN
I/AppCompatDelegate(28573): The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
W/ThumbnailView(28573): Not re-loading slide content://org.thoughtcrime.securesms/part/1452368556105/3
D/ViewRootImpl(28573): ViewPostImeInputStage ACTION_DOWN
E/ViewRootImpl(28573): sendUserActionEvent() mView == null
E/ViewRootImpl(28573): sendUserActionEvent() mView == null
D/ViewRootImpl(28573): ViewPostImeInputStage ACTION_DOWN
W/ThumbnailView(28573): Not re-loading slide content://org.thoughtcrime.securesms/part/1452368556105/3
D/ViewRootImpl(28573): ViewPostImeInputStage ACTION_DOWN
I/AppCompatDelegate(28573): The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
W/ThumbnailView(28573): Not re-loading slide content://org.thoughtcrime.securesms/part/1452368556105/3
D/ViewRootImpl(28573): ViewPostImeInputStage ACTION_DOWN
E/ViewRootImpl(28573): sendUserActionEvent() mView == null
E/ViewRootImpl(28573): sendUserActionEvent() mView == null
D/ViewRootImpl(28573): ViewPostImeInputStage ACTION_DOWN
W/ThumbnailView(28573): Not re-loading slide content://org.thoughtcrime.securesms/part/1452368556105/3
D/ViewRootImpl(28573): ViewPostImeInputStage ACTION_DOWN
I/AppCompatDelegate(28573): The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
W/ThumbnailView(28573): Not re-loading slide content://org.thoughtcrime.securesms/part/1452368556105/3
D/ViewRootImpl(28573): ViewPostImeInputStage ACTION_DOWN
E/ViewRootImpl(28573): sendUserActionEvent() mView == null
E/ViewRootImpl(28573): sendUserActionEvent() mView == null
D/ViewRootImpl(28573): ViewPostImeInputStage ACTION_DOWN
W/ThumbnailView(28573): Not re-loading slide content://org.thoughtcrime.securesms/part/1452368556105/3
D/ViewRootImpl(28573): ViewPostImeInputStage ACTION_DOWN
I/AppCompatDelegate(28573): The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
W/ThumbnailView(28573): Not re-loading slide content://org.thoughtcrime.securesms/part/1452368556105/3
D/ViewRootImpl(28573): ViewPostImeInputStage ACTION_DOWN
E/ViewRootImpl(28573): sendUserActionEvent() mView == null
E/ViewRootImpl(28573): sendUserActionEvent() mView == null
D/ViewRootImpl(28573): ViewPostImeInputStage ACTION_DOWN
W/ThumbnailView(28573): Not re-loading slide content://org.thoughtcrime.securesms/part/1452368556105/3
D/ViewRootImpl(28573): ViewPostImeInputStage ACTION_DOWN
I/AppCompatDelegate(28573): The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
W/ThumbnailView(28573): Not re-loading slide content://org.thoughtcrime.securesms/part/1452368556105/3
D/ViewRootImpl(28573): ViewPostImeInputStage ACTION_DOWN
E/ViewRootImpl(28573): sendUserActionEvent() mView == null
E/ViewRootImpl(28573): sendUserActionEvent() mView == null
D/ViewRootImpl(28573): ViewPostImeInputStage ACTION_DOWN
I/Timeline(28573): Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:74225043
W/PassphraseRequiredActionBarActivity(28573): onPause()
W/KeyCachingService(28573): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService(28573): Decrementing activity count...
W/MessageRetrievalService(28573): Active Count: 0
W/PassphraseRequiredActionBarActivity(28573): onResume()
W/KeyCachingService(28573): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
W/KeyCachingService(28573): Incrementing activity count...
W/MessageRetrievalService(28573): Active Count: 1
D/OpenGLRenderer(28573): endAllStagingAnimators on 0xa0a2c200 (RippleDrawable) with handle 0x9e80a990
I/Timeline(28573): Timeline: Activity_idle id: android.os.BinderProxy@329789a5 time:74225208
W/PassphraseRequiredActionBarActivity(28573): onDestroy()
W/MmsSmsDatabase(28573): Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type, attachment_id, unique_id, mid, data_size, _data, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 4) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type, unique_id, NULL AS mid, data_size, NULL AS _data, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 4) ORDER BY date_received DESC LIMIT 1)
D/ViewRootImpl(28573): ViewPostImeInputStage ACTION_DOWN
D/AbsListView(28573): Get MotionRecognitionManager
D/ViewRootImpl(28573): ViewPostImeInputStage ACTION_DOWN
I/Timeline(28573): Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:74227272
W/InputEventReceiver(28573): Attempted to finish an input event but the input event receiver has already been disposed.
W/PassphraseRequiredActionBarActivity(28573): onPause()
E/ViewRootImpl(28573): sendUserActionEvent() mView == null
W/KeyCachingService(28573): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService(28573): Decrementing activity count...
W/MessageRetrievalService(28573): Active Count: 0
W/PassphraseRequiredActionBarActivity(28573): onCreate(null)
W/ExperienceUpgradeActivity(28573): getExperienceUpgrade(181)
W/PassphraseRequiredActionBarActivity(28573): routeApplicationState(), state: 0
W/PassphraseRequiredActionBarActivity(28573): initializeClearKeyReceiver()
D/Activity(28573): performCreate Call secproduct feature valuefalse
D/Activity(28573): performCreate Call debug elastic valuetrue
D/AbsListView(28573): Get MotionRecognitionManager
W/PassphraseRequiredActionBarActivity(28573): onResume()
W/KeyCachingService(28573): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
W/KeyCachingService(28573): Incrementing activity count...
W/MessageRetrievalService(28573): Active Count: 1
I/Timeline(28573): Timeline: Activity_idle id: android.os.BinderProxy@37a3b475 time:74227489
V/ActivityThread(28573): updateVisibility : ActivityRecord{7c489cd token=android.os.BinderProxy@329789a5 {org.thoughtcrime.securesms/org.thoughtcrime.securesms.RoutingActivity}} show : false
D/ViewRootImpl(28573): ViewPostImeInputStage ACTION_DOWN
D/AbsListView(28573): Get MotionRecognitionManager
D/ViewRootImpl(28573): ViewPostImeInputStage ACTION_DOWN
I/Timeline(28573): Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:74229905
W/PassphraseRequiredActionBarActivity(28573): onPause()
W/KeyCachingService(28573): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService(28573): Decrementing activity count...
W/MessageRetrievalService(28573): Active Count: 0
D/Activity(28573): performCreate Call secproduct feature valuefalse
D/Activity(28573): performCreate Call debug elastic valuetrue

**Comment by moxie0** [comment]
sorry, looks like a ROM issue
