### ISSUE TITLE
improvements: display last online activity

### ISSUE THREAD

**Issue by edo0** [WhisperSystems/Signal-Android#5051]
How about displayng (just like whatsapp does) how much time ago one contact was online last, and when he/she is, mark it? Of course, giving the option to enable and disable this feature.
To distinguish from whatsapp, it could be "X min ago" instead of the "HH:MM" format; well, of course, this is entirely up to you devs ;)

**Comment by x12x** [comment]
Stuff like this has been discussed several times in the past, and usually the main concern of the users was privacy. However, the right place to discuss this kind of thing is the mailing list. Please close this issue, as it would be closed by the developers anyway. Have a look at the mailing list archives and if necessary use that to suggest new features :)

**Comment by edo0** [comment]
My bad, I didn't know it.
Thanks for your word of advice!
