### ISSUE TITLE
Push Notifications don't seem to work on Asus Zenfone 2

### ISSUE THREAD

**Issue by mantaplatte5000** [WhisperSystems/Signal-Android#5052]
I'm using the ASUS Zenfone 2 ZE550ML (Z008d) and I'm not receiving messages until I'll open Signal again. I think it doesn't start automatically on boot up and the App gets terminated at some point/ stops running in the background.

**Comment by moxie0** [comment]
Hey @mantaplatte5000 the best place for support questions is support@whispersystems.org.  They can walk you through the normal troubleshooting for getting push working on your device. You can also check http://support.whispersystems.org thanks!

**Comment by apagano93** [comment]
Hello,
I am having the same issue on the same Asus Zenfone 2 model.
@mantaplatte5000 how did you solve the issue?

**Comment by nrizzio** [comment]
@apagano93 as Moxie said, you should contact support@whispersystems.org. The issue tracker isn't used for support questions.
