### ISSUE TITLE
contact appears in contact list with wrong number

### ISSUE THREAD

**Issue by micwill** [WhisperSystems/Signal-Android#5054]
i have a signal contact that started messaging me 2 days ago when we were meeting face to face. messaging works well but contact appears with a number which isnt its real number nor does anyone of the two of us know the number which shows up. its not in my nor in the contacts contact list. what can be done about that strange behaviour?

both on android, my signal version is 3.9.1, contacts signal version is 3.8.1

**Comment by johanw666** [comment]
Duck for cover, that's a NSA man in the middle attack. :-)

Seriously though, does the number appear nowhere in your contacts? Is it a valid number anyway? Could it be related to https://github.com/SMSSecure/SMSSecure/issues/301?

**Comment by micwill** [comment]
> Duck for cover, that's a NSA man in the middle attack. :-)
thats what we thought immediatly ;-)
> Seriously though, does the number appear nowhere in your contacts?
No we checked that twice
> Is it a valid number anyway?
its not even a valid number. i called it. it says "this number doesnt exist"
> Could it be related to SMSSecure#301?
as far as i understand this issue has to do with multiple numbers same contact. thats not the case here. both participants have only one number in contact list. and we are not talking about groups here

**Comment by micwill** [comment]
We fixed it now. Contact forgot to register its current number, now everything works as expected. The "wrong" number was sitting in the previous registration settings. no idea how it got there. it wasnt any previous number or the like...
