### ISSUE TITLE
Groups I have left are getting synced to Desktop

### ISSUE THREAD

**Issue by liliakai** [WhisperSystems/Signal-Android#5056]
Desktop users are unexpectedly seeing long-ago left groups surfaced when searching their newly installed Desktop conversations. See WhisperSystems/Signal-Desktop#586.

Either omit previously-left groups from a group sync message, or add a flag to the GroupDetails proto indicating we left the group.

**Comment by RiseT** [comment]
Is this fixed in https://github.com/WhisperSystems/Signal-Android/commit/03efe02e65408a0b8afe902cd6cf659ad0261988 ?

**Comment by moxie0** [comment]
yep
