### ISSUE TITLE
Remove Play Services dependency

### ISSUE THREAD

**Issue by pizzamaker** [WhisperSystems/Signal-Android#5058]
As of now, Signal is unusable without a big, Google-owned, proprietary and invasive dependency: Play Services. Ideally it should run without the need for it.

**Comment by skulumani** [comment]
These are some of the other issues after about 45 seconds of searching

#4361 #330 #127 #722 #525 #725 #4276 

> The thesis essentially being, if you aren't able to build TextSecure from source, you probably aren't capable of managing the risks associated with 3rd party sources.

**Comment by pizzamaker** [comment]
Fantastic, thanks.

**Comment by 2-4601** [comment]
Thanks @skulumani
