### ISSUE TITLE
Ripple Integration

### ISSUE THREAD

**Issue by vanitasvitae** [WhisperSystems/Signal-Android#5059]
Hi
The guardianproject develops an ecosystem called Ripple. Ripple is used to define actions in apps that trigger when the owner of the phone gets in danger and pushes a panic button.

SMSSecure for example hides itself when the panic button is triggered.
It would be nice if Signal also would support this (hiding/locking the app, sending predefined messages to trusted contacts etc.)

https://guardianproject.info/2016/01/12/panickit-making-your-whole-phone-respond-to-a-panic-button/

**Comment by moxie0** [comment]
thanks but we're probably not going to do this
