### ISSUE TITLE
problem during signal call

### ISSUE THREAD

**Issue by dcherian** [WhisperSystems/Signal-Android#5060]
Everything was going fine till I couldn't hear what the other person was saying. I heard absolutely nothing but she could hear me during this time. I cancelled the call and redialled. The call didn't go through, got the calling screen with big white "unknown contact" picture and no phone number. Had to force close and restart Signal, after which things worked fine.

Log taken after cancelling the redial and before the force-close: https://gist.github.com/anonymous/e2fcf9b0476b04af9df6

**Comment by edo0** [comment]
That happened to me as well once, when I was still using previous 3.9.0 version. Since the upgrade to 3.9.1 I didn't notice crashes of that kind, although I still have to test it more thoroughly

**Comment by dcherian** [comment]
Closing because redphone bug.
