### ISSUE TITLE
No SMS while no internet connection.

### ISSUE THREAD

**Issue by LNow** [WhisperSystems/Signal-Android#5065]
I'm not sure if it's a bug or feature as I'm new user of the application.

If I have no internet access the app does not receives ANY text messages. They are gone for good.
Senders get delivery confirmation, but I can't read their messages as I haven't received any.

**Comment by moxie0** [comment]
Plain old SMS messages are received and displayed whenever there's cellular service.  Signal messages do require a data connection of some kind, and are queued server-side until you have one.  The sender will see a sent check mark, and a second delivered check mark after you've received it.

**Comment by LNow** [comment]
@moxie0 what you described is a desirable and proper way of handling text messages. And that's clear for me.
However I have a problems with ALL text messages.
If I'm not connected to the network (wifi/4g data connection) no matter who send me a text, I do not receive them at all...
More than that, when finally I connect phone to the internet, I do not receive those messages as well.
All messages sent to me while I'm not connected to the internet are lost somewhere.
I can't even read those messages when I switch back to original messaging app. They are gone.

So I think it's a bug.

**Comment by moxie0** [comment]
You can post a debug log immediately after not receiving an SMS you should have, but we have very little control over the SMS behavior of the device -- that's all handled by the system.
