### ISSUE TITLE
[Android Wear] Unable to send SMS from Okay Google - Moto360 2015

### ISSUE THREAD

**Issue by castanley** [WhisperSystems/Signal-Android#5067]
When I use the Motorola 360 2015 (2nd Gen) device to receive messages, it works fine. However, when trying to send a message (not reply) it fails to send using signal.

Not sure if this is a flaw with Signal or unexpected behavior with the way Android Wear handles that function call.

Decive: Nexus 6P

**Comment by agrajaghh** [comment]
closing as duplicate of #218
