### ISSUE TITLE
Signal desktop messages ambushing me on my phone when I wake it up

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#5069]
I've had a couple cases today of where I was using the desktop client 0.1.6 and when I woke up my phone (wasn't off, just the screen was off) all the messages came flooding into my phone's signal instance.  Not sure if that's intended behavior but it can get extensive if the conversation was a bunch of messages which do tend to be longer due to the freedom of typing on a normal keyboard.
https://gist.github.com/5dc02749edad36c2060f

**Comment by moxie0** [comment]
sounds like normal gcm stuff, possibly doze settings

**Comment by jeremymasters** [comment]
for posterity....galaxy note 5, stock verizon android 5.1.1.  could indeed by gcm laziness.  I'll reopen if consistently repeatable in the near future.

**Comment by jeremymasters** [comment]
I did some testing with my other phone and another desktop client.  A restart of my original problematic phone seemed to clear things up with it.  As silly as my fix (rebooting my phone) might sound, it's probably worth adding to the support steps if it's not there already since it's a pretty common phone.  Hopefully this is not annoying.
