### ISSUE TITLE
Add esperanto to the language list

### ISSUE THREAD

**Issue by x12x** [WhisperSystems/Signal-Android#5070]
Although Esperanto is listed on Transifex, I can't see it as an option on my phone. Why is that?

**Comment by McLoo** [comment]
@x12x the Esperanto translation is far from the 90% threshold that is set for adding a language to the list. 

But you're must welcome to help in translating a few phrases  😊

**Comment by x12x** [comment]
Will it be added automatically once it reaches 90%? I can probably help a little if you need it (I've already joined the translation team)
