### ISSUE TITLE
wrong and/or missing thumbnails

### ISSUE THREAD

**Issue by edo0** [WhisperSystems/Signal-Android#5071]
When I wish to visualize all of the pictures from a conversation, it often happens that 2 or 3 (of some 20 pics) have a wholly black thumbnail or one that is a duplicate from another thumbnail, save for when I open them the right photo shows up. version is 3.9.1, the debug log is below
https://gist.github.com/7d6655a45cc85e6b74ea

**Comment by 2-4601** [comment]
Do you mean that this happens in the _All images_ view?

**Comment by edo0** [comment]
Yeah, that should be the exact term for the English language version

**Comment by 2-4601** [comment]
This behaviour is also described in https://github.com/WhisperSystems/Signal-Android/issues/4732#issuecomment-165123049

**Comment by edo0** [comment]
You are right. Should I close this issue and post my debug log in the other one?

**Comment by 2-4601** [comment]
I'm not sure if it's exactly the same issue. Underlying cause might be same though. @mcginty is the Glide expert, maybe he can give a quick answer.

**Comment by mcginty** [comment]
Yep, this sounds like the same bug (categorized in my head as "some kind of bitmap memory re-use/corruption thing") and I'm finally experiencing it on my install. Haven't had time to plug-and-debug yet.

Closing as dupe since it's pretty likely a fix would solve both these issues.

**Comment by edo0** [comment]
You are welcome. And thanks for the great job you devs are doing!!
