### ISSUE TITLE
Advanced settings menu UI inconsistency

### ISSUE THREAD

**Issue by janimo** [WhisperSystems/Signal-Android#5073]
The emoji setting uses a checkbox while the other two boolean settings use toggle buttons.

**Comment by tehabe** [comment]
This isn't all. 

In the Notifications settings, "Vibrate" and "In-conversation notifications" have checkboxes
And in Privacy: Inactivity timeout passphrase

And yes, the emoji setting is still a checkbox.

Tested with Signal 3.12.0 on Android 6.0.1

**Comment by janimo** [comment]
The others are subpreferences, as moxie pointed out in the related PR.
