### ISSUE TITLE
Feature request: multi select & save in "All images"

### ISSUE THREAD

**Issue by SlappyHours** [WhisperSystems/Signal-Android#5088]
With Signal it is possible to browse through all images sent/received in a conversation ( ... / All images ). But it is not possible to batch export them.

I would like to switch to a new phone and backup all these images contained in the encrypted Signal storage. I could manually select each image and save to internal storage, but that would take ages.

**Comment by 2-4601** [comment]
You mean something like #1619?

**Comment by agrajaghh** [comment]
@2-4601 no, I think multi select + save in the *All images* Activity

**Comment by SlappyHours** [comment]
#1619 would help creating a backup and then importing the backup on the new device (which is useful, too).

But in my case a "multi select + save" would be better so I can save the images on my desktop pc.

**Comment by cascheberg** [comment]
See #3975

**Comment by BT80** [comment]
Also consider #2798

**Comment by 2-4601** [comment]
:white_check_mark: 238471b847e6d106af9eaabcf59b38104f9e0097

**Comment by nrohwer** [comment]
@2-4601 Unfortunately this has been undone in (I think) version 4.11.3.
The button to save all media files does not exist anymore.

Vote to reopen!

**Comment by VTCop** [comment]
Any news? Some prevision about putting back the "Save All" button?

**Comment by Fmstrat** [comment]
Still no re-implementation? Lots of people switching to S9s soon and no way to save media easily anymore.

**Comment by haffenloher** [comment]
@Fmstrat full backups are coming with 332ccbb

**Comment by Fmstrat** [comment]
@haffenloher Thanks for the update. What are the chances of this hitting the Play Store prior to March 16th? That's going to be the trade-in date for a lot of people.

**Comment by Chaos99** [comment]
I'll also vote for a re-open. I want to export images to be used  by other applications/archived. An app-specific backup is not a replacement for this use-case.
