### ISSUE TITLE
Signal crashes when notification sound is set to "none" and in-conversation notifications are enabled.

### ISSUE THREAD

**Issue by tim-george** [WhisperSystems/Signal-Android#5090]
Android 5.1
Signal 3.9.1 (also observed on previous versions - can't be more specific).

https://gist.github.com/anonymous/291abefd9fa914074d60

If notification sound is set to "None" and "In-conversation notifications" are turned on Signal will crash whenever you receive a message while having the conversation open.

This only occurs when the conversation the message is a part of is currently open. It doesn't occur if a different conversation is open or if Signal is in the background. When you re-open the app the message that caused the crash will display properly.

This affects both Signal conversations and regular SMS conversations with Signal as the SMS client.

**Comment by lolstarz** [comment]
I can't reproduce this. Android 6.0.1, Signal 3.9.1
In the main Signal menu: Notifcations > Sound > None 
(Noteworthy that this shows up as "Silent" in the main menu after selecting "None" - I would expect it to show None)
In the main Signal menu: In conversation notifications: ON

I then open a conversation, and while it's open, receive a message. It plays a sound. No crash.

**Comment by cascheberg** [comment]
The docs say that `RingtoneManager.getRingtone` can return a fallback sound or `null`. #5091 fixes both problems.
