### ISSUE TITLE
Adding devices with the dark theme - Confirmation text very hard to read.

### ISSUE THREAD

**Issue by dd23** [WhisperSystems/Signal-Android#5092]
I have just been added to the Signal Desktop Beta and added my computer to Signal on my Android device.

After scanning the QR-Code of my desktop I get a screen that asks me to accept that my Desktop can read my messages and post messages in my name.

This screen uses a white background and light grey text and is very hard to read. I assume this is related to the dark theme, that I use and looks fine if you use the light/white theme. Probably you just need to adapt either background or text color for the dark theme.

**Comment by haffenloher** [comment]
This is a duplicate of #4611, will be fixed with #5066 :)

**Comment by dd23** [comment]
Oh well, thanks for pointing out the duplicate. I didn't go back all the way back to November. Great that it will be fixed sood.
