### ISSUE TITLE
"Clean media storage" functionality

### ISSUE THREAD

**Issue by if13b023** [WhisperSystems/Signal-Android#5107]
It would be a great feature if one could delete all stored media files which are older than a specific time.
My problem is that my phone has a small internal storage and i have no possibility to delete a bunch of images (e.g. from group chats) at once.
I hope someone understands what i mean.

**Comment by 2-4601** [comment]
Tracked here #4242, closing as duplicate.

**Comment by if13b023** [comment]
i've looked through the issues but must have missed that, sry =)
