### ISSUE TITLE
App does not prompt for password

### ISSUE THREAD

**Issue by vanitasvitae** [WhisperSystems/Signal-Android#5116]
Hi
Sometimes I encounter a strange behaviour:
When I get a message, I enter my phones pin code to unlock it. Than I end up in the conversation with the contact that sent me the message and I can read most of the conversation. Only the message that just arrived is replaced with "Encryption in progress" (or something similar. In German it sais "Entschlüsselung läuft. Bitte warten").
I should add, that the Signal should be locked when this happens. It just did not ask for the password.
When I close Signal and open it again, I'm prompted to enter the password and only then I can see the message that did arrive.

At the moment I'm using the websocket fork of Signal, but I don't think this is caused by the fork. If you say it is, feel free to close this issue. For the record, the issue I opened in the forks repo can be found here: https://github.com/JavaJens/TextSecure/issues/58

I'm on CopperheadOS based on AOSP and my phone has no GApps installed.

**Comment by moxie0** [comment]
sorry we can't support non-official builds

**Comment by vanitasvitae** [comment]
So this is likely to be a bug of the websocket fork?

**Comment by moxie0** [comment]
no idea, but you're running someone else's software, so please ask them for support
