### ISSUE TITLE
Weak SSL certificate

### ISSUE THREAD

**Issue by zero77** [WhisperSystems/Signal-Android#5121]
Can you update your SSL certificate as it is very weak. I am not meaning the fact that it is not CA signed as you are using certificate pinning which is more secure. Things like being vulnerable to the POODLE attack and other things.

It explains more in the link. 
https://www.ssllabs.com/ssltest/analyze.html?d=textsecure-service.whispersystems.org

**Comment by Dyras** [comment]
I think you are better off posting this here: https://github.com/WhisperSystems/whispersystems.org/issues

**Comment by zero77** [comment]
I am not sure as this is the SSL certificate the android app uses not the main website SSL certificate.

**Comment by zero77** [comment]
This has also found some more problems with the SSL certificate. 
https://www.htbridge.com/ssl/?id=05a76743932cd3c1d2b9c627a3ded3b60af29da5b4331bf68fa65b2c803f8e03

**Comment by 2-4601** [comment]
Please don't open duplicate issues. Closing for #5100.

**Comment by mimi89999** [comment]
@moxie0 Thanks for your reply under #5100 . I still have some questions.

> The cipher suites we support enable us to receive connections from old gingerbread devices.

AFAIK old gingerbread devices support TLS1.0 and TLS_DHE_RSA_WITH_AES_128_CBC_SHA which are considered more secure.

Also could you please not lock conversations?

**Comment by zero77** [comment]
yes thanks for your reply, also what is your reason for using SSLv3 as I thawt this is unsecure or is it also due to compatibility issues.
