### ISSUE TITLE
Group SMS image download failure

### ISSUE THREAD

**Issue by geoffcorey** [WhisperSystems/Signal-Android#5122]
Android 6.0.0
Moto G 3rd Gen
Signal 3.9.1

Signal setup as default SMS.   Group text message on signal and non-signal users sending MMS.   Group was listed as individuals in Signal and resulted in "Download" to view.   Confirmed that one of the Signal users was not using Signal app to send but was using iMessage.   Cannot confirm if other Signal users were sending through the app or not.  Click "Download" and never received.   Switched back to making the regular Google Messaging app as default SMS and could retrieve MMS.   

Signal was installed on Lollipop and the device upgraded to Android 6.0.0 two weeks ago.

https://gist.github.com/9160ac730b4647a81ed9

**Comment by geoffcorey** [comment]
Tried uninstall an reinstall and made it the default sms app.   Had a non-signal user send MMS.  Unable to download the MMS and still get failure.

**Comment by 2-4601** [comment]
There are a lot of MMS download failed issues open. Have you checked if there are any similarities between your case and those?

**Comment by jjohns71** [comment]
Who is your cell carrier?

**Comment by geoffcorey** [comment]
cell carrier is AT&T and I did look at other issues

**Comment by jjohns71** [comment]
Seems to be related to #4474

**Comment by geoffcorey** [comment]
yep looks related.

**Comment by jjohns71** [comment]
'This should probably be closed per #4474 being fixed.
