### ISSUE TITLE
Problem while building project with Gradle

### ISSUE THREAD

**Issue by santteegt** [WhisperSystems/Signal-Android#5123]
Hi,

I'm having an issue when trying to build the project with Graddle. The dependencies on repositories https://raw.githubusercontent.com/whispersystems/maven/master/preferencefragment/releases/ and https://raw.github.com/whispersystems/maven/master/shortcutbadger/releases/ are not reachable. I have installed the Android SDK and Build Tools v 22.x.x . How can I solve this ?

Main error: peer not authenticated

Thanks

**Comment by eosrei** [comment]
I just built it correctly for the first time last night. Can you post more details from the gradle log?
