### ISSUE TITLE
[Sugestion] Register to Signal with e-mail address

### ISSUE THREAD

**Issue by spacekookie** [WhisperSystems/Signal-Android#5129]
Make it possible to use Signal and register to a server without the need of a phone number.

E.g. the idea would be to mirror what [Threema]() is currently doing where you have an ID and you link either your phone number and/ or your e-mail address. Or nothing - you're still able to use the server without providing that data.

But...it would make it easier for people to use Signal together if they, for example, only know each others e-mail.

Is something like this on the roadmap? And if it isn't, can I put it there? :) Thanks for listening.

**Comment by 2-4601** [comment]
Thanks but this is already tracked at #1085. Please search for existing issues in the future.

**Comment by spacekookie** [comment]
Ah, sorry. I did search but that issue didn't show up in the search.
