### ISSUE TITLE
"Network Error"[(błąd sieci) in polish version]  toast during connecting Signal-desktop with android phone

### ISSUE THREAD

**Issue by KarolTrzeszczkowski** [WhisperSystems/Signal-Android#5130]
After taking a photo of QR-code I received toast "network error" and it turned me to "Devices" menu. I tried adding my desktop few times and after about fourth time it worked. It seems that you can see it in log.

https://gist.github.com/anonymous/2cd2e541d556cd84822f

My phone is under Flyme OS 4.5.4.2l and Signal-Desktop is under Linux Mint and in chromium. Maybe it was just delay in connection and sending photo, I live in Poland.

**Comment by KarolTrzeszczkowski** [comment]
Friend of mine, also from Poland, had this problem but with no toast. He tried scanning code few times and it pulled him to devices menu. Finally it worked but he was confused. His phone model is Samsung Note 3.

**Comment by riyapenn** [comment]
Not registered? http://support.whispersystems.org/hc/en-us/articles/216948747-What-do-I-do-if-I-see-Network-connection-failed-

**Comment by KarolTrzeszczkowski** [comment]
But it worked without that. It was just a delay. And I'm just informing. I thought it might be helpful for you.
