### ISSUE TITLE
Delete Signup

### ISSUE THREAD

**Issue by Miladniaz** [WhisperSystems/Signal-Android#5133]
Hello 
I want to delete the signup activities from the source code how can i do it whenever i delete the registration activity it will finish by some errors can you help me with this please????
what should i to delete from the source code???
i want to enter the app without registration!!!!
thanks TS Developers.

**Comment by johanw666** [comment]
If you just want to use it as an SMS client, why not install https://github.com/SMSSecure/SMSSecure ? They have done that work already (and kept the SMS encryption in it too).

**Comment by agrajaghh** [comment]
#5131
