### ISSUE TITLE
Stop preventing people from sending texts when update is required

### ISSUE THREAD

**Issue by simonv3** [WhisperSystems/Signal-Android#5137]
I'm regularly outside of data zones but would still like to communicate with people. Especially when not it's an emergency.

It's happened a couple of times now that Signal prevents me from sending a text when an update is required and I'm without access to the internet. This is pretty poorly thought out. 

![signal problem](https://cloud.githubusercontent.com/assets/485583/12625277/e91a8614-c4e7-11e5-8cfc-325c0a151fc4.png)

It also just blocks the message from being sent - you only see the warning on the inbox list, rather than on the message list - without giving any indication why the message wasn't sent (when looking at the message thread). This is for ordinary messages to people who don't use Signal and thus don't have encrypted texts.

Instead of preventing the message being sent, how about warning the user that their signal app is insecure every time they try updating the message.

**Comment by moxie0** [comment]
thanks but we're not going to do this
