### ISSUE TITLE
README.md image link broken

### ISSUE THREAD

**Issue by jzbz** [WhisperSystems/Signal-Android#5139]
Same issue essentially as https://github.com/WhisperSystems/whispersystems.org/issues/100 except you will likely need to resize and host your own image...

Google has stopped hosting the Google Play badge linked in the README.md file[1]. A new one can be grabbed form their site[2].

[1] https://developer.android.com/images/brand/en_app_rgb_wo_60.png
[2] https://play.google.com/intl/en_us/badges/

**Comment by 2-4601** [comment]
Resolved by c5bb606
