### ISSUE TITLE
verify identity - please add "get your key scanned" also on iPhone/iOS

### ISSUE THREAD

**Issue by ralfhauser** [WhisperSystems/Signal-Android#5142]
I see the QR function on Android, but not on my colleague's iPhone

**Comment by agrajaghh** [comment]
this is the android repo, please have a loot at the iOS repo: https://github.com/WhisperSystems/Signal-iOS

**Comment by ralfhauser** [comment]
thx, uuh, appears to be a problem since last may
https://github.com/WhisperSystems/Signal-iOS/issues/1057 or rather
https://github.com/WhisperSystems/Signal-iOS/issues/788
