### ISSUE TITLE
transmitted pictures of QR - offer not only save but also translate to text and vice versa

### ISSUE THREAD

**Issue by ralfhauser** [WhisperSystems/Signal-Android#5143]
as you do have ZXING or alike as plug-in, this should be really easy.

Also, when trying to transmit to another device that does not have Signal, but a QR Reader, offer to convert a text into a QR image

**Comment by agrajaghh** [comment]
sorry, I don't fully understand, what is your proposal? Transmit text messages to other devices via QR codes?

**Comment by ralfhauser** [comment]
yes, an vice versa.
This way, I could use my trusted signal contact to transmit an AES symmertic key to this contact that is used by a 3rd party bulk file encryption/decryption

**Comment by agrajaghh** [comment]
I don't think thats something that should be in an instant messenger. You can use a third party app to generate/read the QR codes and send these pictures via Signal

closing this, if @moxie0 disagrees he will reopen it
