### ISSUE TITLE
Names with accents (diacritics) wrong sorted in contact list 

### ISSUE THREAD

**Issue by boorman79** [WhisperSystems/Signal-Android#5144]
Contact list displays names with accents in the wrong order resulting in people named "Álvaro" being sorted after "Zacarías" (not able to attach image at the moment).

I think COLLATE LOCALIZED in https://github.com/WhisperSystems/Signal-Android/blob/master/src/org/thoughtcrime/securesms/contacts/ContactsDatabase.java (line 150) will do the trick but i'm not a programmer. According to what I've found: 

_[LOCALIZED] It instructs SQLite to sort non-ASCII characters appropriately. Chars with diacritics (some call them accents) have higher byte codes than the character Z, so a plain ASCII sort wouldn't fit to many foreign languages._

_For example, the capital A char's byte code is 0x41 and the capital Z char's is 0x5A. Then we have the Á (capital A accute) which code in Unicode is 0x00C1. So a plain byte code sort would result the Á to be after the Z._

_But in languages that have this kind of characters the convention is to put those with diacritics as if they didn't have the diacritic. So the Á should be together with the plain A, at least before B._

_And to illustrate, we have below a list of names sorted using their bytecode:_

    Brenda
    Debby
    George
    Álvaro
    Érico

_Now using the COLLATE LOCALIZED it would sort by the "base" of the character:_

    Álvaro
    Brenda
    Debby
    Érico
    George"
Thank you very much for your great work.

**Comment by moxie0** [comment]
nice bug report
