### ISSUE TITLE
Signal doesn't show which SIM received message when on dual-SIM devices

### ISSUE THREAD

**Issue by anterguy** [WhisperSystems/Signal-Android#5145]
I have a dual-SIM phone and use Signal instead of the preinstalled SMS-app.

When I receive new messages I have no possiblity to find out to which SIM-card the message was send to. 
Since this information is definetly available to the system it would be nice to have an option in settings to show for new messages which SIM-card received it!

**Comment by agrajaghh** [comment]
please dont open duplicate issues (intentionally!)

**Comment by anterguy** [comment]
It's a different issue, isn't it?

**Comment by agrajaghh** [comment]
afaik all dual sim issues are tracked in #555

**Comment by Vinnl** [comment]
This issue could be solved without solving #555. That might or might not imply a different issue depending on your policy :)
