### ISSUE TITLE
Delivery of push messages to some contacts fails/works only if Signal is opened

### ISSUE THREAD

**Issue by TheRealCuran** [WhisperSystems/Signal-Android#5149]
I have a contact which only sees my push messages, when she opens Signal. (On my end they're marked as sent but not delivered). The notification about new messages is also missing. Sending and SMS to the same contact works all the time.

My contact has one other messenger app: WhatsApp. Can this cause conflicts? (I only have Signal and I'm also not seeing this issue with other contacts that only have Signal.) I was told, that WhatsApp works at the same time as expected.

**Comment by 2-4601** [comment]
Hi @TheRealCuran please tell her to read http://support.whispersystems.org/hc/en-us/articles/213190487-Why-is-there-a-delay-in-receiving-messages- and if that doesn't help contact support@whispersystems.org
Closing as support issue.
