### ISSUE TITLE
Audio attachment: button should always offer selection between file from disk and new recording

### ISSUE THREAD

**Issue by TheRealCuran** [WhisperSystems/Signal-Android#5150]
If you press the audio button in the attachment screen, you get asked, if you want to add a file from storage or record something. In this window you can select an option to always use the selected app (I know that this is a system dialog). This leads to the point, where some contacts can't send me audio recordings, because they made that choice a long time ago.

Signal should offer a button to always record a new message like you can always make a new photo with the camera.

**Comment by 2-4601** [comment]
> This leads to the point, where some contacts can't send me audio recordings, because they made that choice a long time ago.

This is an Android/ROM issue

> Signal should offer a button to always record a new message like you can always make a new photo with the camera.

There is a quick recording feature but it's on hold atm because the current Signal iOS version has issues with audio attachment support.
So what you ask is coming :)
