### ISSUE TITLE
SMS sending/receiving not working for secondary users

### ISSUE THREAD

**Issue by mbanck** [WhisperSystems/Signal-Android#5151]
I have installed signal in a secondary user profile (Android 5.1.1, Signal 3.9.1) and enabled signal as default SMS app, as well as enabled that profile to make calls and send sms.Signal is not installed for the primary user (phone owner).

I verified that the system SMS app is receiving SMS fine, however, as soon as I switch to signal as the default SMS app, I no longer receive SMS on that profile. If I switch back to the primary user, the SMS is there.

Unless I am missing something important, I don't see why signal should not be able to handle this case, e.g. if a user wants to use signal with a different Google account and/or sync contacts from a different source than the main account (my case).

This is the log: https://gist.github.com/anonymous/6e8bb5eadfba96dbe8ba

I get this, I assume that indicates an incoming SMS:

```
W/SMSListener( 8759): Got SMS broadcast...
```

however, signal does not act on it apparently, though I cannot see an obvious error message off-hand.

Another log: https://gist.github.com/anonymous/ab72cc595bdb3212f106

This time, there is the following:

```
W/SMSListener( 8759): Got SMS broadcast...
W/ResourceType( 8759): Found multiple library tables, ignoring...
```

I have the feeling I saw the second message quite often in correlation with this when I tested it.

**Comment by moxie0** [comment]
That's how Android works. From:
https://source.android.com/devices/tech/admin/multi-user.html

> The secondary user may receive inbound calls but cannot send or receive texts.

**Comment by mbanck** [comment]
No, that's just how Android works /by default/, but there is an option in the user settings to allow "outgoing phone calls and SMS" (translated from german). It is (on my Xperia) in Settings -> Users -> [gearwheel icon next to a seconday user]. i believe this is not a Sony extension, see .e.g. https://support.google.com/nexus/answer/2865944?hl=en section "Control what users and guests can do".

This is consistent with the full quote:

> The default state is only the primary user has full access to phone calls and texts. The secondary user may receive inbound calls but cannot send or receive texts. The primary user must enable these functions for others.

**Comment by mbanck** [comment]
Hrm, I tested sending SMS now, and that does not work either, I get a backtrace: https://gist.github.com/anonymous/03f75618246afd172822

```
W/SmsSendJob(11384): Sending message: 14
W/SmsSendJob(11384): java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.content.pm.PackageInfo.packageName' on a null object reference
[...]
```

I can file that as a different issue if you want, or update the issue title to sending/receiving

**Comment by moxie0** [comment]
That exception is being thrown from a bug in your Android OS, not from Signal.  So you have a ROM bug, and at no point are you going to be able to receive an SMS in the secondary profile anyway.

**Comment by mbanck** [comment]
I can certainly send and receive SMS with the system (granted, from Sony I think) SMS/messaging app as secondary user, otherwise I would not have filed this as a signal issue:

> I verified that the system SMS app is receiving SMS fine

I also tried this on a OnePlus X some weeks ago and was able send/receive SMS there as secondary user as well (I think they have the stock Android SMS app). But that one has dual-SIM, so I wasn't sure it was a signal issue with the OnePlus X.

**Comment by userdsp** [comment]
Tasker did not trigger when i receive sms
settings are from any sender and any text
My prone is rooted and all permissions are granted to tasker

**Comment by shrimprugbysnowowl** [comment]
This still appears to be an issue with Signal being able to receive SMS/MMS in secondary user profiles. Other SMS apps do not experience this issue - is a solution to this possible by the Signal team? Thanks everyone

**Comment by mbanck** [comment]
In light of https://signal.org/blog/sms-removal-android/ probably not :-/
