### ISSUE TITLE
No notification if a message was not received

### ISSUE THREAD

**Issue by MH2016s** [WhisperSystems/Signal-Android#5154]
Dear Madam or Sir,

Unfortunately Signal contains a bug that makes it unusable for me. For me there are many situations in which a message is not received:

-Not send due to missing online connection by myself
-Not received due to missing online connection by receiver
-Not received due to uninstalled Signal without un-registering the device of the receiver

It would be more than helpful if Signal would notify me in these situations (e.g. after 30 seconds) so that I can decide to wait or to call/SMS the receiver.

I’m aware that the one or two check marks show this information, but in practice people don’t pay attention to this detail and assume that the message was send.

Best regards,
MH2016s

**Comment by 2-4601** [comment]
Hi, there are already issues about the situations you mentioned. You can search for existing issues in https://github.com/WhisperSystems/Signal-Android/issues

> -Not send due to missing online connection by myself
#687, #877, #2098, #2384, #3068

> -Not received due to missing online connection by receiver
See https://github.com/WhisperSystems/Signal-Android/issues/678#issuecomment-36029957

> -Not received due to uninstalled Signal without un-registering the device of the receiver
Unfortunately it's difficult for the Signal servers to distinguish in the short term if the recipient has uninstalled or if their device is just not available.
https://github.com/WhisperSystems/Signal-Android/issues/1026#issuecomment-36717211
