### ISSUE TITLE
Indication or auto-activation as protected app

### ISSUE THREAD

**Issue by Jens14L** [WhisperSystems/Signal-Android#5157]
A feature which enables Signal automatically as “protected app” (“geschützte Anwendung”) e.g. in Huawei’s ‘task manager’ or informs/asks the user about this behaviour would be great, especially for unexperienced users. Otherwise, Signal is not able to run in background and push …

![signal_huawei](https://cloud.githubusercontent.com/assets/11010835/12698663/0b432ec2-c7a3-11e5-9441-feb161e52c1d.jpg)

**Comment by 2-4601** [comment]
Does Huawei offer a way to do it?

**Comment by Jens14L** [comment]
IdI don’t know. However, the WhatsApp and Facebook apps seem to do it themselves or Huawei supports them.
