### ISSUE TITLE
Manually link devices without phone camera/QR Code

### ISSUE THREAD

**Issue by bmaleck1** [WhisperSystems/Signal-Android#5158]
Sorry to post again.  But I was wondering why you don't want to add an option to manually link devices?  
If you are too busy I can figure it out and create a pull request.  I just don't want to go through the effort for it to be denied for unknown reasons. I imagine there are others with broken camera's that can't link their desktops.

**Comment by moxie0** [comment]
Please don't intentionally open duplicate issues.  This is not a discussion forum.

**Comment by bmaleck1** [comment]
Do you even read these? Does anyone care? Do you want people to use the app? I was trying to help.

**Comment by simsid66** [comment]
@moxie0 @bmaleck1 sorry to bump this old thread, but why is it not possible to implement a one-time password system for people with broken cameras/devices without cameras? You enter your phone number on the desktop client, and then it sends your cell phone/Signal app a code that you can enter on your computer to verify yourself. Another idea would be to allow use of the front camera to scan the code.
