### ISSUE TITLE
Lock Signal with passphrase and fingerprint

### ISSUE THREAD

**Issue by onealj** [WhisperSystems/Signal-Android#5161]
I've been using TextSecure/Signal for a while now and want to get more involved with the project. I figured adding fingerprint sensor app unlock support for the Android app would be a good first project.

Before jumping into implementation, I found Issue #4439, where someone requested fingerprint app unlock as an alternative to passphrase, which was closed as wontfix. Was the reasoning for rejecting this feature request due to feature parity with iOS, placing trust in the OS's fingerprint store and authentication, privacy or security concerns, or software testing concerns? I'm not sure if the reasoning from Issue #420 significantly intrudes on the security levels I suggest below, especially when combined with exponential delays on failed attempts and database wipe after too many failed attempts within a period of time. This comes down to giving the user a choice of convenience and security, which I assume is why the no-passphrase option has not been removed yet.

I was wondering if I implemented fingerprint app unlock if the Open Whisper team would be interested. Requiring both a passphrase and fingerprint is more secure than either one. In a public setting with wandering eyes, a fingerprint is more secure than a passphrase. Fingerprint sensor support would also allow quicker message checking while keeping Signal in a lock-after-5 minutes state.

Here's what I was thinking of adding to the Settings menu
* always unlocked
* unlock with passphrase
* unlock with fingerprint or passphrase
     * require passphrase every X hours
     (passphrase would be required after 3 fingerprint unlock attempts, and after any device reboot)
* unlock with passphrase and fingerprint
      (requires both to unlock the phone every time it is locked)
* erase all conversation history after Y failed unlock attempts
      (any combination of fingerprint and passphrase)

Signal would use the Android Fingerprint API, using whatever fingers are registered with the OS.

**Comment by lozinge** [comment]
+1 for this

**Comment by 2-4601** [comment]
Some useful info:
https://lists.riseup.net/www/arc/whispersystems/2015-12/msg00037.html
https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#smaller-is-better

**Comment by moxie0** [comment]
Hey @onealj we don't use GH as a discussion forum, so this isn't the right place to ask questions. In any case, we're not interested in a fingerprint lock.  Thanks!
