### ISSUE TITLE
Verification code and telephone voice still reference TextSecure instead of Signal

### ISSUE THREAD

**Issue by piratenpanda** [WhisperSystems/Signal-Android#5162]
I guess SMS should read Signal verification code and not TextSecure anymore. Same goes for phone verification

**Comment by 2-4601** [comment]
Thanks, I think this is a server thing.
See:
* https://github.com/WhisperSystems/TextSecure-Server/issues/45
* https://github.com/WhisperSystems/TextSecure-Server/pull/60
