### ISSUE TITLE
distinguish unread messages

### ISSUE THREAD

**Issue by an64** [WhisperSystems/Signal-Android#5163]
Sometimes it hard to finda place , where i stop read conversation last time, especially in group chat
It will be nice to show some border (some thin line or so) under the last readed message

**Comment by agrajaghh** [comment]
duplicate of #1211 ?

**Comment by x12x** [comment]
No, I think it's a duplicate of #965

**Comment by agrajaghh** [comment]
@x12x true :blush:

**Comment by an64** [comment]
Yes, this is duplicate, sorry!
