### ISSUE TITLE
Feature Request: Change the deault sending method to sms per contact 

### ISSUE THREAD

**Issue by geg2048** [WhisperSystems/Signal-Android#5164]
Because I use signal as my default sms app, sometimes I need to send my signal contacts multiple sms and I don't want to long press the sending button every time I need to send one.

I would suggest to put a additional entry in the contact settings.

Examples:
If they on vacation and disable there mobile data.
Or if they lost there phone and need to use there old nokia until they get a new one.

**Comment by moxie0** [comment]
thanks but we're not going to do this
