### ISSUE TITLE
Display SMS sent time instead of received time

### ISSUE THREAD

**Issue by breversa** [WhisperSystems/Signal-Android#5165]
There should be an option to display SMS sent time instead of received time (or maybe even both ?), as it's the case with many other SMS/instant messaging apps. :-)

**Comment by FeuRenard** [comment]
This issue was already discussed in #1970.

**Comment by breversa** [comment]
Thanks for the pointer ; I was pretty sure the issue had been discussed
already, but did not manage to find it.

2016-02-01 14:02 GMT+01:00 FeuRenard <notifications@github.com>:
