### ISSUE TITLE
Signal can not be set as Default SMS App (Android 6.0.1)

### ISSUE THREAD

**Issue by SkateScout** [WhisperSystems/Signal-Android#5166]
1) I use an N5 Android 6.0.1 M8974A-2.0.50.2.28
2) When i open Signal goto Settings and Select SMS und MSS (aus) i could not select signal.
Because when i tap "SMS deaktivated" i have "Hangouts", MyPhoneExplorer", "Messenger" and "Titanium Backup" but no "Signal".
3) When i open the SMS-App change menu i receive the logcat from bellow.

01-31 23:21:24.094 26592 26608 W MessageQueue: Handler (com.android.internal.os.HandlerCaller$MyHandler) {6250e3} sending message to a Handler on a dead thread
01-31 23:21:24.094 26592 26608 W MessageQueue: java.lang.IllegalStateException: Handler (com.android.internal.os.HandlerCaller$MyHandler) {6250e3} sending message to a Handler on a dead thread
01-31 23:21:24.094 26592 26608 W MessageQueue:  at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
01-31 23:21:24.094 26592 26608 W MessageQueue:  at android.os.Handler.enqueueMessage(Handler.java:631)
01-31 23:21:24.094 26592 26608 W MessageQueue:  at android.os.Handler.sendMessageAtTime(Handler.java:600)
01-31 23:21:24.094 26592 26608 W MessageQueue:  at android.os.Handler.sendMessageDelayed(Handler.java:570)
01-31 23:21:24.094 26592 26608 W MessageQueue:  at android.os.Handler.sendMessage(Handler.java:507)
01-31 23:21:24.094 26592 26608 W MessageQueue:  at com.android.internal.os.HandlerCaller.sendMessage(HandlerCaller.java:86)
01-31 23:21:24.094 26592 26608 W MessageQueue:  at android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.onAccessibilityEvent(AccessibilityService.java:725)
01-31 23:21:24.094 26592 26608 W MessageQueue:  at android.accessibilityservice.IAccessibilityServiceClient$Stub.onTransact(IAccessibilityServiceClient.java:72)
01-31 23:21:24.094 26592 26608 W MessageQueue:  at android.os.Binder.execTransact(Binder.java:453)
01-31 23:21:24.159   816   826 I ActivityManager: START u0 {act=android.provider.Telephony.ACTION_CHANGE_DEFAULT cmp=com.android.settings/.SmsDefaultDialog (has extras)} from uid 10096 on display 0

**Comment by moxie0** [comment]
looks like a rom issue, nothing we can do unfortunately
