### ISSUE TITLE
In conversation, make the typing cursor the same color as the contact's color

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#5168]
When tapping into a conversation, the cursor in the typing area matches the pretty signal blue for both secure and normal SMS contacts.  I think it'd be a nice touch to have the cursor color match the contact's color.  I know this wouldn't be a high priority issue at all but it would be low-hanging fruit for someone who does android programming and wanted to start getting involved with signal development.

**Comment by moxie0** [comment]
thanks but we're not going to do this
