### ISSUE TITLE
Unredacted phone number in debug log after PhoneNumberFormatter failure

### ISSUE THREAD

**Issue by BradRubenstein** [WhisperSystems/Signal-Android#5170]
I noticed in the last line of the Android debug log of https://github.com/WhisperSystems/Signal-Desktop/issues/649 that a unparseable phone number is logged on Android without redaction (as in nearly all other cases). Just thought I'd note it.

02-01 13:27:22.986: W/EarlyReceiptCache(19337): Checking early receipts (1454329639749, +82604946527386932081): null

**Comment by moxie0** [comment]
Probably because that's not a valid phone number, but this would be a bug in libpastelog, not this app.

**Comment by 2-4601** [comment]
@BradRubenstein Please open an issue at https://github.com/WhisperSystems/libpastelog/issues
