### ISSUE TITLE
Signal does not detect if another user has uninstalled

### ISSUE THREAD

**Issue by bmaleck1** [WhisperSystems/Signal-Android#5171]
Signal does not detect if a user has uninstalled signal and should instead default to sms. I rebooted the device assuming it would connect and check if a user has uninstalled. However, the default is still to send signal messages which are never received.

**Comment by 2-4601** [comment]
Closing as duplicate of #1026.
Tell your uninstalled contact to unregister: http://support.whispersystems.org/hc/en-us/articles/213190627-How-do-I-unregister-
