### ISSUE TITLE
No sim selection dialog on dual simcard phones

### ISSUE THREAD

**Issue by kenjoe41** [WhisperSystems/Signal-Android#5172]
The app doesn't provide a sim selection dialog on dual simcard phones when the send button is pressed and 'Always ask' is set in which sicard to use for SMS.

**Comment by JavaJens** [comment]
There is no support for dual sim (yet?). Maybe check #555

**Comment by agrajaghh** [comment]
closing as duplicate of #555 

please search for existing issues before opening new ones. Thanks
