### ISSUE TITLE
Transfer sms to new phone

### ISSUE THREAD

**Issue by mehmehmehmeh** [WhisperSystems/Signal-Android#5175]
I want to transfer all my sms from Nexus 5 to a new Nexus 5x.
The export function on N5 says Success but the TextSecurePlaintextBackup.xml is nowhere to be found. Have also testet creating an export on N5x. Same issue there.. Cannot find any backup file and app does not say where its stored..

**Comment by moxie0** [comment]
Hey for support questions please contact support@whispersystems.org thanks!
