### ISSUE TITLE
developers edit other people's bug reports to falsify original intent

### ISSUE THREAD

**Issue by ghostlands** [WhisperSystems/Signal-Android#5182]
See #5181

I definitely laughed. But you really shouldn't do that.

**Comment by agrajaghh** [comment]
are you serious?

https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md
https://github.com/WhisperSystems/Signal-Android/wiki/Welcome-to-the-Signal-Community
http://xkcd.com/1357/
