### ISSUE TITLE
Crash on startup after connecting to Signal Desktop

### ISSUE THREAD

**Issue by yourcelf** [WhisperSystems/Signal-Android#5183]
I just received my invite to Signal Desktop, and connected it to android.  But after connecting, the android app now consistently crashes on startup.  Logcat shows this error message:

    W/IdentityDatabase(24834): org.whispersystems.libaxolotl.InvalidKeyException: Bad key type: 1
    W/IdentityDatabase(24834): 	at org.whispersystems.libaxolotl.ecc.Curve.decodePoint(Curve.java:52)
    W/IdentityDatabase(24834): 	at org.whispersystems.libaxolotl.IdentityKey.<init>(IdentityKey.java:39)
    W/IdentityDatabase(24834): 	at org.whispersystems.libaxolotl.SessionBuilder.process(SessionBuilder.java:106)
    W/IdentityDatabase(24834): 	at org.whispersystems.libaxolotl.SessionCipher.decrypt(SessionCipher.java:183)
    W/IdentityDatabase(24834): 	at org.whispersystems.libaxolotl.SessionCipher.decrypt(SessionCipher.java:153)
    W/IdentityDatabase(24834): 	at org.whispersystems.textsecure.api.crypto.TextSecureCipher.decrypt(TextSecureCipher.java:148)
    W/IdentityDatabase(24834): 	at org.whispersystems.textsecure.api.crypto.TextSecureCipher.decrypt(TextSecureCipher.java:122)
    W/IdentityDatabase(24834): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
    W/IdentityDatabase(24834): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
    W/PushDecryptJob(24834): org.whispersystems.libaxolotl.UntrustedIdentityException
    W/PushDecryptJob(24834): 	at org.whispersystems.libaxolotl.SessionBuilder.process(SessionBuilder.java:107)
    W/PushDecryptJob(24834): 	at org.whispersystems.libaxolotl.SessionCipher.decrypt(SessionCipher.java:183)
    W/PushDecryptJob(24834): 	at org.whispersystems.libaxolotl.SessionCipher.decrypt(SessionCipher.java:153)
    W/PushDecryptJob(24834): 	at org.whispersystems.textsecure.api.crypto.TextSecureCipher.decrypt(TextSecureCipher.java:148)
    W/PushDecryptJob(24834): 	at org.whispersystems.textsecure.api.crypto.TextSecureCipher.decrypt(TextSecureCipher.java:122)
    W/PushDecryptJob(24834): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
    W/PushDecryptJob(24834): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
    W/JobConsumer(24834): 	at org.whispersystems.libaxolotl.protocol.PreKeyWhisperMessage.<init>(PreKeyWhisperMessage.java:48)
    W/JobConsumer(24834): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
    W/JobConsumer(24834): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
    E/AndroidRuntime(24834): 	at org.whispersystems.libaxolotl.protocol.PreKeyWhisperMessage.<init>(PreKeyWhisperMessage.java:48)
    E/AndroidRuntime(24834): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
    E/AndroidRuntime(24834): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)

The phone is a Motorola xt907 running CyanogenMod 11, with Signal v3.10.0.  I can't obtain a debug log directly from Signal because it won't run long enough for me to enable logging in Signal's settings.

Signal Desktop seems to still be working fine.

**Comment by moxie0** [comment]
huh, there are a bunch of lines omitted from this stack trace, is that the whole thing unedited?

**Comment by yourcelf** [comment]
That was logcat grepping for `whisper`.  Here's full logcat dump during the crash:

    I/Timeline( 1178): Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:49121296
    I/ActivityManager(  793): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.thoughtcrime.securesms/.RoutingActivity bnds=[323,766][423,892]} from pid 1178
    W/BroadcastQueue(  793): Permission Denial: broadcasting Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } from com.cyanogenmod.trebuchet (pid=1178, uid=10045) requires com.google.android.launcher.permission.RECEIVE_LAUNCH_BROADCASTS due to receiver com.google.android.gms/.icing.proxy.ApplicationLauncherReceiver
    W/BroadcastQueue(  793): Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } to com.google.android.gms/.icing.proxy.ApplicationLauncherReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.cyanogenmod.trebuchet (uid 10045)
    V/Zygote  (29300): Switching descriptor 34 to /dev/null
    V/Zygote  (29300): Switching descriptor 10 to /dev/null
    I/ActivityManager(  793): Start proc org.thoughtcrime.securesms for activity org.thoughtcrime.securesms/.RoutingActivity: pid=29300 uid=10072 gids={50072, 3003, 1028, 1015, 1006, 3002}
    D/ActivityThread(29300): handleBindApplication:org.thoughtcrime.securesms
    D/ActivityThread(29300): setTargetHeapUtilization:0.75
    D/ActivityThread(29300): setTargetHeapMinFree:2097152
    W/PartProvider(29300): onCreate()
    I/dalvikvm(29300): Could not find method android.view.Window.setStatusBarColor, referenced from method org.thoughtcrime.securesms.BaseActionBarActivity.setStatusBarColor
    W/dalvikvm(29300): VFY: unable to resolve virtual method 11676: Landroid/view/Window;.setStatusBarColor (I)V
    D/dalvikvm(29300): VFY: replacing opcode 0x6e at 0x000a
    W/PassphraseRequiredActionBarActivity(29300): onCreate(null)
    W/ExperienceUpgradeActivity(29300): getExperienceUpgrade(157)
    W/PassphraseRequiredActionBarActivity(29300): routeApplicationState(), state: 2
    I/Timeline(29300): Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:49121782
    I/ActivityManager(  793): START u0 {cmp=org.thoughtcrime.securesms/.PassphrasePromptActivity (has extras)} from pid 29300
    I/dalvikvm(29300): Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.internal.widget.TintTypedArray.getChangingConfigurations
    W/dalvikvm(29300): VFY: unable to resolve virtual method 536: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
    D/dalvikvm(29300): VFY: replacing opcode 0x6e at 0x0002
    I/dalvikvm(29300): Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.internal.widget.TintTypedArray.getType
    W/dalvikvm(29300): VFY: unable to resolve virtual method 558: Landroid/content/res/TypedArray;.getType (I)I
    D/dalvikvm(29300): VFY: replacing opcode 0x6e at 0x0002
    I/dalvikvm(29300): Could not find method android.content.res.Resources.getDrawable, referenced from method android.support.v7.internal.widget.ResourcesWrapper.getDrawable
    W/dalvikvm(29300): VFY: unable to resolve virtual method 499: Landroid/content/res/Resources;.getDrawable (ILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
    D/dalvikvm(29300): VFY: replacing opcode 0x6e at 0x0002
    I/dalvikvm(29300): Could not find method android.content.res.Resources.getDrawableForDensity, referenced from method android.support.v7.internal.widget.ResourcesWrapper.getDrawableForDensity
    W/dalvikvm(29300): VFY: unable to resolve virtual method 501: Landroid/content/res/Resources;.getDrawableForDensity (IILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
    D/dalvikvm(29300): VFY: replacing opcode 0x6e at 0x0002
    I/Adreno200-EGL(29300): <qeglDrvAPI_eglInitialize:265>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_JB_2.5.2.04.02.02.088.027_msm8960_JB_2.5.2_CL3374520_release_AU (CL3374520)
    I/Adreno200-EGL(29300): Build Date: 08/02/13 Fri
    I/Adreno200-EGL(29300): Local Branch: 
    I/Adreno200-EGL(29300): Remote Branch: quic/jb_2.5.2
    I/Adreno200-EGL(29300): Local Patches: NONE
    I/Adreno200-EGL(29300): Reconstruct Branch: AU_LINUX_ANDROID_JB_2.5.2.04.02.02.088.027 + 109d3c2 + 0f798a2 +  NOTHING
    D/OpenGLRenderer(29300): Enabling debug mode 0
    I/ActivityManager(  793): Displayed org.thoughtcrime.securesms/.PassphrasePromptActivity: +299ms (total +644ms)
    I/Timeline(  793): Timeline: Activity_windows_visible id: ActivityRecord{42476450 u0 org.thoughtcrime.securesms/.PassphrasePromptActivity t24} time:49122118
    E/RichInputConnection( 1094): Unable to connect to the editor to retrieve text... will retry later
    I/InputAttributes( 1094): InputType.TYPE_NULL is specified
    I/Timeline(29300): Timeline: Activity_idle id: android.os.BinderProxy@42597e60 time:49122169
    W/PassphraseRequiredActionBarActivity(29300): onDestroy()
    W/TextSecureSessionStore(29300): No existing session information found.
    W/IdentityDatabase(29300): org.whispersystems.libaxolotl.InvalidKeyException: Bad key type: 1
    W/IdentityDatabase(29300):  at org.whispersystems.libaxolotl.ecc.Curve.decodePoint(Curve.java:52)
    W/IdentityDatabase(29300):  at org.whispersystems.libaxolotl.IdentityKey.<init>(IdentityKey.java:39)
    W/IdentityDatabase(29300):  at org.thoughtcrime.securesms.database.IdentityDatabase.isValidIdentity(IdentityDatabase.java:75)
    W/IdentityDatabase(29300):  at org.thoughtcrime.securesms.crypto.storage.TextSecureIdentityKeyStore.isTrustedIdentity(TextSecureIdentityKeyStore.java:41)
    W/IdentityDatabase(29300):  at org.thoughtcrime.securesms.crypto.storage.TextSecureAxolotlStore.isTrustedIdentity(TextSecureAxolotlStore.java:51)
    W/IdentityDatabase(29300):  at org.whispersystems.libaxolotl.SessionBuilder.process(SessionBuilder.java:106)
    W/IdentityDatabase(29300):  at org.whispersystems.libaxolotl.SessionCipher.decrypt(SessionCipher.java:183)
    W/IdentityDatabase(29300):  at org.whispersystems.libaxolotl.SessionCipher.decrypt(SessionCipher.java:153)
    W/IdentityDatabase(29300):  at org.whispersystems.textsecure.api.crypto.TextSecureCipher.decrypt(TextSecureCipher.java:148)
    W/IdentityDatabase(29300):  at org.whispersystems.textsecure.api.crypto.TextSecureCipher.decrypt(TextSecureCipher.java:122)
    W/IdentityDatabase(29300):  at org.thoughtcrime.securesms.jobs.PushDecryptJob.handleMessage(PushDecryptJob.java:135)
    W/IdentityDatabase(29300):  at org.thoughtcrime.securesms.jobs.PushDecryptJob.onRun(PushDecryptJob.java:115)
    W/IdentityDatabase(29300):  at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
    W/IdentityDatabase(29300):  at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
    W/PushDecryptJob(29300): org.whispersystems.libaxolotl.UntrustedIdentityException
    W/PushDecryptJob(29300):    at org.whispersystems.libaxolotl.SessionBuilder.process(SessionBuilder.java:107)
    W/PushDecryptJob(29300):    at org.whispersystems.libaxolotl.SessionCipher.decrypt(SessionCipher.java:183)
    W/PushDecryptJob(29300):    at org.whispersystems.libaxolotl.SessionCipher.decrypt(SessionCipher.java:153)
    W/PushDecryptJob(29300):    at org.whispersystems.textsecure.api.crypto.TextSecureCipher.decrypt(TextSecureCipher.java:148)
    W/PushDecryptJob(29300):    at org.whispersystems.textsecure.api.crypto.TextSecureCipher.decrypt(TextSecureCipher.java:122)
    W/PushDecryptJob(29300):    at org.thoughtcrime.securesms.jobs.PushDecryptJob.handleMessage(PushDecryptJob.java:135)
    W/PushDecryptJob(29300):    at org.thoughtcrime.securesms.jobs.PushDecryptJob.onRun(PushDecryptJob.java:115)
    W/PushDecryptJob(29300):    at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
    W/PushDecryptJob(29300):    at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
    W/JobConsumer(29300): java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
    W/JobConsumer(29300):   at org.whispersystems.libaxolotl.protocol.PreKeyWhisperMessage.<init>(PreKeyWhisperMessage.java:48)
    W/JobConsumer(29300):   at org.thoughtcrime.securesms.jobs.PushDecryptJob.handleUntrustedIdentityMessage(PushDecryptJob.java:453)
    W/JobConsumer(29300):   at org.thoughtcrime.securesms.jobs.PushDecryptJob.handleMessage(PushDecryptJob.java:171)
    W/JobConsumer(29300):   at org.thoughtcrime.securesms.jobs.PushDecryptJob.onRun(PushDecryptJob.java:115)
    W/JobConsumer(29300):   at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
    W/JobConsumer(29300):   at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
    W/dalvikvm(29300): threadid=12: thread exiting with uncaught exception (group=0x41faece0)
    E/AndroidRuntime(29300): FATAL EXCEPTION: JobConsumer-0
    E/AndroidRuntime(29300): Process: org.thoughtcrime.securesms, PID: 29300
    E/AndroidRuntime(29300): java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
    E/AndroidRuntime(29300):    at org.whispersystems.libaxolotl.protocol.PreKeyWhisperMessage.<init>(PreKeyWhisperMessage.java:48)
    E/AndroidRuntime(29300):    at org.thoughtcrime.securesms.jobs.PushDecryptJob.handleUntrustedIdentityMessage(PushDecryptJob.java:453)
    E/AndroidRuntime(29300):    at org.thoughtcrime.securesms.jobs.PushDecryptJob.handleMessage(PushDecryptJob.java:171)
    E/AndroidRuntime(29300):    at org.thoughtcrime.securesms.jobs.PushDecryptJob.onRun(PushDecryptJob.java:115)
    E/AndroidRuntime(29300):    at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
    E/AndroidRuntime(29300):    at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
    V/Zygote  (29329): Switching descriptor 34 to /dev/null
    V/Zygote  (29329): Switching descriptor 10 to /dev/null
    W/SurfaceFlinger(  311): FB is protected: PERMISSION_DENIED
    I/ActivityManager(  793): Start proc android.process.acore for content provider com.android.providers.contacts/.ContactsProvider2: pid=29329 uid=10001 gids={50001, 3003, 1028, 1015}
    W/ActivityManager(  793):   Force finishing activity org.thoughtcrime.securesms/.PassphrasePromptActivity
    W/WindowManager(  793): Screenshot failure taking screenshot for (246x437) to layer 21070
    D/ActivityThread(29329): handleBindApplication:android.process.acore
    D/ActivityThread(29329): setTargetHeapUtilization:0.75
    D/ActivityThread(29329): setTargetHeapMinFree:2097152
    I/Timeline( 1178): Timeline: Activity_idle id: android.os.BinderProxy@423e70a8 time:49123567
    I/Timeline(  793): Timeline: Activity_windows_visible id: ActivityRecord{42c42010 u0 com.cyanogenmod.trebuchet/org.cyanogenmod.trebuchet.CustomHomeLauncher t1} time:49124013
    I/ActivityManager(  793): Killing 28868:com.android.defcontainer/u0a15 (adj 10): empty for 2059s
    I/ActivityManager(  793): Killing 28810:org.whispersystems.whisperpush/u0a146 (adj 15): empty for 2155s
    W/ActivityManager(  793): Scheduling restart of crashed service com.android.defcontainer/.DefaultContainerService in 1000ms
    I/ContactLocale(29329): AddressBook Labels [en_US]: [, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, Α, Β, Γ, Δ, Ε, Ζ, Η, Θ, Ι, Κ, Λ, Μ, Ν, Ξ, Ο, Π, Ρ, Σ, Τ, Υ, Φ, Χ, Ψ, Ω, , А, Б, В, Г, Д, Е, Є, Ж, З, И, І, Ї, Й, К, Л, М, Н, О, П, Р, С, Т, У, Ф, Х, Ц, Ч, Ш, Щ, Ю, Я, , א, ב, ג, ד, ה, ו, ז, ח, ט, י, כ, ל, מ, נ, ס, ע, פ, צ, ק, ר, ש, ת, , ا, ب, ت, ث, ج, ح, خ, د, ذ, ر, ز, س, ش, ص, ض, ط, ظ, ع, غ, ف, ق, ك, ل, م, ن, ه, و, ي, , ก, ข, ฃ, ค, ฅ, ฆ, ง, จ, ฉ, ช, ซ, ฌ, ญ, ฎ, ฏ, ฐ, ฑ, ฒ, ณ, ด, ต, ถ, ท, ธ, น, บ, ป, ผ, ฝ, พ, ฟ, ภ, ม, ย, ร, ฤ, ล, ฦ, ว, ศ, ษ, ส, ห, ฬ, อ, ฮ, , ㄱ, ㄴ, ㄷ, ㄹ, ㅁ, ㅂ, ㅅ, ㅇ, ㅈ, ㅊ, ㅋ, ㅌ, ㅍ, ㅎ, , あ, か, さ, た, な, は, ま, や, ら, わ, #, ]
    V/Zygote  (29350): Switching descriptor 34 to /dev/null
    V/Zygote  (29350): Switching descriptor 10 to /dev/null
    I/ActivityManager(  793): Start proc com.android.defcontainer for service com.android.defcontainer/.DefaultContainerService: pid=29350 uid=10015 gids={50015, 1028, 1015, 1023, 2001, 1035}
    D/ActivityThread(29350): handleBindApplication:com.android.defcontainer
    D/ActivityThread(29350): setTargetHeapUtilization:0.75
    D/ActivityThread(29350): setTargetHeapMinFree:2097152

**Comment by moxie0** [comment]
Looks like local storage corruption.  What's coming out of the database is definitely not what was originally put in there, something bad is up with your device.  =(

**Comment by yourcelf** [comment]
Just for reference, if anyone else comes across this:

It appears that the crash is arising from the process for syncing contacts/messages with the desktop app.  There may indeed be a corrupted contact key in the database that is responsible; this would explain why linking Signal-Android to Desktop precipitated this, even though I hadn't noticed a problem previously.

I was able to get Signal to launch by clearing the job queue table -- `/data/user/0/org.thoughtcrime.securesms/__jobqueue-TextSecureJobs` -- using sqlite3.  This made it possible to run Signal long enough to export a plain-text backup of messages/contacts before clearing the app data.  Unfortunately, there isn't a way to export keys right now (other than [whole-app backup methods](https://github.com/WhisperSystems/Signal-Android/wiki/Backup-and-restore-Signal-messages), which [may not work anymore anyway](https://github.com/WhisperSystems/Signal-Android/issues/4577)).  Even if I could do a whole-app backup, that would probably retain the corrupted keys.  So I'm stuck with generating new keys re-verifying keys with my signal contacts. :(

After clearing app data, launching Signal and generating new keys, then restoring plaintext backup, syncing with Signal desktop seems to be working.

**Comment by tomsib2001** [comment]
@yourcelf Can you detail a bit more how you deleted this file? I have exactly the same problem and I can't seem to access it, at least from my phone. I've lost access to all my conversations, contacts and pictures so far..

**Comment by yourcelf** [comment]
Hey @tomsib2001, the method I used requires that you have android debugging enabled and connect to your device using `adb`.  

1. Connect to the shell from a terminal: `adb shell`
2. Open the database: `sqlite3 /data/user/0/org.thoughtcrime.securesms/__jobqueue-TextSecureJobs`
3. List the tables in the database with `.tables`. Identify the correct job queue table.
4. Clear the rows in that table with `DELETE FROM <tablename>;`
5. Launch the Signal app and make a plaintext backup.
6. Find the app in Android's Settings -> Apps, and "Clear Data" from the app to start over with a clean slate and new keys.
7. Restore the plaintext backup.

This is (obviously) mucking around with internals of Signal in a very warranty-voiding sort of way, so you might consider whether it's worth diving into this if things like adb and SQL are new to you.

**Comment by 2-4601** [comment]
If the crash only happens when your device has a network connection, you can put your phone in airplane mode, and then do the backup.

**Comment by tomsib2001** [comment]
@yourcelf thanks for this. I will try it once I get a USB to mini-USB cable. But since I have not tinkered with my signal install in any way, it seems like this might be a more general issue and might warrant some help for non-power users. 
I'm thinking about @moxie0 suggestion that this was a problem with your device, we will have to see if other people come forward with the same problem, but in this case, it might indeed be due to an update or to whatever the desktop beta does when it attempts to sync up.

**Comment by sewelol** [comment]
This happend to me when trying to send a video (mp4 i think)  to someone. The app crashed, and would not start up again. I put the phone in airplane mode, and was able to start up and delete the video message. Works fine now.
