### ISSUE TITLE
unable to build, can't find referenced method 

### ISSUE THREAD

**Issue by aaronke** [WhisperSystems/Signal-Android#5184]
Can anyone help me, i keep getting the following warnings when first time build the project

Information:Gradle tasks [:assembleDebug]
signing.properties not found
Verifying me.leolin:ShortcutBadger
Verifying se.emilsjolander:stickylistheaders
Verifying com.google.android.gms:play-services-gcm
Verifying com.google.android.gms:play-services-maps
Verifying com.google.android.gms:play-services-location
Verifying com.jpardogo.materialtabstrip:library
Verifying org.w3c:smil
Verifying org.apache.httpcomponents:httpclient-android
Verifying com.github.chrisbanes.photoview:library
Verifying com.github.bumptech.glide:glide
Verifying com.makeramen:roundedimageview
Verifying com.pnikosis:materialish-progress
Verifying de.greenrobot:eventbus
Verifying pl.tajchert:waitingdots
Verifying com.soundcloud.android:android-crop
Verifying com.android.support:appcompat-v7
Verifying com.android.support:recyclerview-v7
Verifying com.android.support:design
Verifying com.android.support:cardview-v7
Verifying com.melnykov:floatingactionbutton
Verifying com.google.zxing:android-integration
Verifying com.android.support:support-v4-preferencefragment
Verifying com.android.support:gridlayout-v7
Verifying com.squareup.dagger:dagger
Verifying com.doomonafireball.betterpickers:library
Verifying com.madgag.spongycastle:prov
Verifying org.whispersystems:jobmanager
Verifying org.whispersystems:libpastelog
Verifying com.amulyakhare:com.amulyakhare.textdrawable
Verifying org.whispersystems:textsecure-android
Verifying com.h6ah4i.android.compat:mulsellistprefcompat
Verifying com.google.zxing:core
Verifying com.google.android.gms:play-services-base
Verifying com.android.support:support-annotations
Verifying com.nineoldandroids:library
Verifying javax.inject:javax.inject
Verifying com.madgag.spongycastle:core
Verifying org.whispersystems:textsecure-java
Verifying org.whispersystems:axolotl-android
Verifying com.google.android.gms:play-services-basement
Verifying com.google.protobuf:protobuf-java
Verifying com.squareup.okhttp:okhttp
Verifying com.googlecode.libphonenumber:libphonenumber
Verifying com.fasterxml.jackson.core:jackson-databind
Verifying org.whispersystems:axolotl-java
Verifying org.whispersystems:curve25519-android
Verifying com.squareup.okio:okio
Verifying com.fasterxml.jackson.core:jackson-annotations
Verifying com.fasterxml.jackson.core:jackson-core
Verifying org.whispersystems:curve25519-java
Verifying com.android.support:support-v4
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:preDevBuild UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:prepareComAmulyakhareComAmulyakhareTextdrawable101Library
:prepareComAndroidSupportAppcompatV72221Library
:prepareComAndroidSupportCardviewV72221Library
:prepareComAndroidSupportDesign2221Library
:prepareComAndroidSupportGridlayoutV72220Library
:prepareComAndroidSupportRecyclerviewV72221Library
:prepareComAndroidSupportSupportV42221Library
:prepareComAndroidSupportSupportV4Preferencefragment100Library
:prepareComDoomonafireballBetterpickersLibrary153Library
:prepareComGithubChrisbanesPhotoviewLibrary123Library
:prepareComGoogleAndroidGmsPlayServicesBase810Library
:prepareComGoogleAndroidGmsPlayServicesBasement810Library
:prepareComGoogleAndroidGmsPlayServicesGcm810Library
:prepareComGoogleAndroidGmsPlayServicesLocation810Library
:prepareComGoogleAndroidGmsPlayServicesMaps810Library
:prepareComH6ah4iAndroidCompatMulsellistprefcompat100Library
:prepareComJpardogoMaterialtabstripLibrary109Library
:prepareComMakeramenRoundedimageview210Library
:prepareComMelnykovFloatingactionbutton130Library
:prepareComPnikosisMaterialishProgress15Library
:prepareComSoundcloudAndroidAndroidCrop0910Library
:prepareMeLeolinShortcutBadger110WS1Library
:prepareOrgWhispersystemsAxolotlAndroid131Library
:prepareOrgWhispersystemsCurve25519Android022Library
:prepareOrgWhispersystemsJobmanager102Library
:prepareOrgWhispersystemsLibpastelog107Library
:prepareOrgWhispersystemsTextsecureAndroid184Library
:preparePlTajchertWaitingdots010Library
:prepareSeEmilsjolanderStickylistheaders270Library
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues UP-TO-DATE
:generateDebugResources
:mergeDebugResources
AAPT: /Users/aaronke/workspace/signal-android/build/intermediates/exploded-aar/com.doomonafireball.betterpickers/library/1.5.3/res/drawable-xxhdpi/ic_recurrence_bubble_outline.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Users/aaronke/workspace/signal-android/build/intermediates/exploded-aar/com.doomonafireball.betterpickers/library/1.5.3/res/drawable-xxhdpi/ic_recurrence_bubble_disabled.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Users/aaronke/workspace/signal-android/build/intermediates/exploded-aar/com.doomonafireball.betterpickers/library/1.5.3/res/drawable-xxhdpi/ic_recurrence_bubble_outline_disabled.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Users/aaronke/workspace/signal-android/build/intermediates/exploded-aar/com.doomonafireball.betterpickers/library/1.5.3/res/drawable-xxhdpi/ic_recurrence_bubble_fill.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
:processDebugManifest
:processDebugResources
:generateDebugSources
:processDebugJavaRes
:compileDebugJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:compileDebugNdk UP-TO-DATE
:compileDebugSources
:proguardDebug
Note: there were 245 duplicate class definitions.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass)
Warning:com.google.protobuf.CodedInputStream$SkippedDataSink: can't find referenced method 'int access$000(com.google.protobuf.CodedInputStream)' in program class com.google.protobuf.CodedInputStream
Warning:com.google.protobuf.CodedInputStream$SkippedDataSink: can't find referenced method 'byte[] access$100(com.google.protobuf.CodedInputStream)' in program class com.google.protobuf.CodedInputStream
Warning:com.google.protobuf.DescriptorProtos$OneofDescriptorProto: can't find referenced method 'com.google.protobuf.Descriptors$Descriptor access$6500()' in program class com.google.protobuf.DescriptorProtos
Warning:com.google.protobuf.DescriptorProtos$OneofDescriptorProto: can't find referenced method 'com.google.protobuf.GeneratedMessage$FieldAccessorTable access$6600()' in program class com.google.protobuf.DescriptorProtos
Warning:com.google.protobuf.DescriptorProtos$OneofDescriptorProto$Builder: can't find referenced method 'com.google.protobuf.Descriptors$Descriptor access$6500()' in program class com.google.protobuf.DescriptorProtos
Warning:com.google.protobuf.DescriptorProtos$OneofDescriptorProto$Builder: can't find referenced method 'com.google.protobuf.GeneratedMessage$FieldAccessorTable access$6600()' in program class com.google.protobuf.DescriptorProtos
Warning:com.google.protobuf.Descriptors$OneofDescriptor: can't find referenced method 'java.lang.String access$1500(com.google.protobuf.Descriptors$FileDescriptor,com.google.protobuf.Descriptors$Descriptor,java.lang.String)' in program class com.google.protobuf.Descriptors
Warning:com.google.protobuf.GeneratedMessage$3: can't find enclosing method 'com.google.protobuf.GeneratedMessage$GeneratedExtension newFileScopedGeneratedExtension(java.lang.Class,com.google.protobuf.Message,java.lang.String,java.lang.String)' in program class com.google.protobuf.GeneratedMessage
Warning:com.google.protobuf.GeneratedMessage$FieldAccessorTable$OneofAccessor: can't find referenced method 'java.lang.reflect.Method access$1000(java.lang.Class,java.lang.String,java.lang.Class[])' in program class com.google.protobuf.GeneratedMessage
Warning:com.google.protobuf.GeneratedMessage$FieldAccessorTable$OneofAccessor: can't find referenced method 'java.lang.Object access$1100(java.lang.reflect.Method,java.lang.Object,java.lang.Object[])' in program class com.google.protobuf.GeneratedMessage
Warning:com.google.protobuf.LazyStringArrayList$ByteArrayListView: can't find referenced method 'byte[] access$000(java.lang.Object)' in program class com.google.protobuf.LazyStringArrayList
Warning:com.google.protobuf.LazyStringArrayList$ByteStringListView: can't find referenced method 'com.google.protobuf.ByteString access$100(java.lang.Object)' in program class com.google.protobuf.LazyStringArrayList
Warning:com.google.protobuf.MessageReflection: can't find referenced method 'boolean needsUtf8Check()' in program class com.google.protobuf.Descriptors$FieldDescriptor
Warning:com.google.protobuf.MessageReflection$BuilderAdapter: can't find referenced method 'boolean hasOneof(com.google.protobuf.Descriptors$OneofDescriptor)' in program class com.google.protobuf.Message$Builder
Warning:com.google.protobuf.MessageReflection$BuilderAdapter: can't find referenced method 'com.google.protobuf.Message$Builder clearOneof(com.google.protobuf.Descriptors$OneofDescriptor)' in program class com.google.protobuf.Message$Builder
Warning:com.google.protobuf.MessageReflection$BuilderAdapter: can't find referenced method 'com.google.protobuf.Descriptors$FieldDescriptor getOneofFieldDescriptor(com.google.protobuf.Descriptors$OneofDescriptor)' in program class com.google.protobuf.Message$Builder
Warning:com.google.protobuf.MessageReflection$BuilderAdapter: can't find referenced method 'com.google.protobuf.ExtensionRegistry$ExtensionInfo findImmutableExtensionByName(java.lang.String)' in program class com.google.protobuf.ExtensionRegistry
Warning:com.google.protobuf.MessageReflection$BuilderAdapter: can't find referenced method 'com.google.protobuf.ExtensionRegistry$ExtensionInfo findImmutableExtensionByNumber(com.google.protobuf.Descriptors$Descriptor,int)' in program class com.google.protobuf.ExtensionRegistry
Warning:com.google.protobuf.MessageReflection$BuilderAdapter: can't find referenced method 'java.lang.Object readPrimitiveField(com.google.protobuf.CodedInputStream,com.google.protobuf.WireFormat$FieldType,boolean)' in program class com.google.protobuf.FieldSet
Warning:com.google.protobuf.MessageReflection$ExtensionAdapter: can't find referenced method 'com.google.protobuf.ExtensionRegistry$ExtensionInfo findImmutableExtensionByName(java.lang.String)' in program class com.google.protobuf.ExtensionRegistry
Warning:com.google.protobuf.MessageReflection$ExtensionAdapter: can't find referenced method 'com.google.protobuf.ExtensionRegistry$ExtensionInfo findImmutableExtensionByNumber(com.google.protobuf.Descriptors$Descriptor,int)' in program class com.google.protobuf.ExtensionRegistry
Warning:com.google.protobuf.MessageReflection$ExtensionAdapter: can't find referenced method 'java.lang.Object readPrimitiveField(com.google.protobuf.CodedInputStream,com.google.protobuf.WireFormat$FieldType,boolean)' in program class com.google.protobuf.FieldSet
Warning:com.google.protobuf.TextFormat$2: can't find enclosing method 'java.lang.String escapeBytes(byte[])' in program class com.google.protobuf.TextFormat
Warning:com.google.protobuf.TextFormat$Parser: can't find referenced method 'java.util.logging.Logger access$1100()' in program class com.google.protobuf.TextFormat
Warning:com.google.protobuf.TextFormat$Parser: can't find referenced method 'boolean lookingAt(java.lang.String)' in program class com.google.protobuf.TextFormat$Tokenizer
Warning:com.google.protobuf.TextFormat$Parser: can't find referenced method 'com.google.protobuf.Descriptors$OneofDescriptor getContainingOneof()' in program class com.google.protobuf.Descriptors$FieldDescriptor
Warning:com.google.protobuf.TextFormat$Parser: can't find referenced method 'boolean tryConsumeString()' in program class com.google.protobuf.TextFormat$Tokenizer
Warning:com.google.protobuf.TextFormat$Parser: can't find referenced method 'boolean tryConsumeIdentifier()' in program class com.google.protobuf.TextFormat$Tokenizer
Warning:com.google.protobuf.TextFormat$Parser: can't find referenced method 'boolean tryConsumeInt64()' in program class com.google.protobuf.TextFormat$Tokenizer
Warning:com.google.protobuf.TextFormat$Parser: can't find referenced method 'boolean tryConsumeUInt64()' in program class com.google.protobuf.TextFormat$Tokenizer
Warning:com.google.protobuf.TextFormat$Parser: can't find referenced method 'boolean tryConsumeDouble()' in program class com.google.protobuf.TextFormat$Tokenizer
Warning:com.google.protobuf.TextFormat$Parser: can't find referenced method 'boolean tryConsumeFloat()' in program class com.google.protobuf.TextFormat$Tokenizer
Warning:com.google.protobuf.TextFormat$Parser: can't find referenced method 'java.lang.String access$1200(com.google.protobuf.TextFormat$Tokenizer)' in program class com.google.protobuf.TextFormat$Tokenizer
Warning:there were 33 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile the code.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedprogramclassmember)
:proguardDebug FAILED
Error:Execution failed for task ':proguardDebug'.
> java.io.IOException: Please correct the above warnings first.
Information:BUILD FAILED
Information:Total time: 46.054 secs
Information:1 error
Information:34 warnings
Information:See complete output in console

**Comment by johanw666** [comment]
Try Android Studio, commandline building seems to be broken.

**Comment by art1fa** [comment]
Seems like you should do
`gradle clean`
(#3890)
Commandline build works fine for me.
