### ISSUE TITLE
Cannot reply to contact who just joined Signal

### ISSUE THREAD

**Issue by lorenzhs** [WhisperSystems/Signal-Android#5186]
I cannot reply to a contact who joined Signal yesterday using Signal-Android. I can receive encrypted messages just fine, but Signal-Android does not find the user on the server: The input bar reads "Send unsecured SMS" and there is no option to reset the encrypted connection. A lock is shown next to the messages I received from the contact, and the messages sync correctly to Signal-Desktop, so the encrypted connection seems functional. It seems that the registration is a bit mucked up, though. When I try to reply with Signal-Desktop, I get the following lines in the log:
```
PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]838
PUT https://textsecure-service-ca.whispersystems.org:4433/v1/messages/+[REDACTED]838 404 Error
SendMessageNetworkError: Number is not registered.
Failed to create or send message Error
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:28:33
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:97:3
    at chrome-extension://bikioccmkafdpakkkcpdbppfkghcmihk/js/libtextsecure.js:37835:3
```

I can't provide a meaningful log for Signal-Android because it doesn't even let me reply to the conversation. The (redacted) phone number never shows up in the log either.

I can privately send you mine my contact's number if you want to investigate the registration on the server or anything.

**Comment by 2-4601** [comment]
Have you tried [refreshing](http://support.whispersystems.org/hc/en-us/articles/213132447-Who-can-I-call-) your Signal contacts?

**Comment by lorenzhs** [comment]
Yes, multiple times.

My contact now re-registered and it works now. If I understood correctly some permission blocker might have interfered with the registration the first time around. I still don't understand how this inconsistent state came to be, though. How can I receive messages from an unregistered number?

**Comment by bingmann** [comment]
I was using http://www.moboclean.com/ to limit permissions on an older Android system.
I don't know for sure if it somehow interfered with Signal; Moboclean somehow augments the apk with a permission shield. We could only chat one-way. After disabling it and re-registering, it worked fine.

**Comment by lorenzhs** [comment]
Right, I'll close this then since that sounds more like MoboClean bug than a Signal bug. Sounds shady in any case.
