### ISSUE TITLE
Bad Encrypted Message for one user in group chat

### ISSUE THREAD

**Issue by kakariki** [WhisperSystems/Signal-Android#5188]
Added a user as a new contact during a group chat session as I wasn't receiving any messages in the group chat from them. I received about 4 successful messages from them, but after that every message is returning as Bad Encrypted Message. These return in a separate thread. My debug log is here: https://gist.github.com/bb031250ae878195ebd5

**Comment by AlfonsoMuskedunder** [comment]
To me this sounds more like a support question. However, have your contact's keys changed (by reinstalling the app or a fresh install on a new device etc.)?

**Comment by riyapenn** [comment]
Go to a private message with this contact and reset the secure session. http://support.whispersystems.org/hc/en-us/articles/215238178-What-do-I-do-if-I-have-a-bad-encrypted-message- 
Contact support@whispersystems.org for further support

**Comment by kakariki** [comment]
I wasn't seeing this option in a private message. I ended up uninstalling the app and reinstalling it and now everything is fine.
