### ISSUE TITLE
LED notification does not work

### ISSUE THREAD

**Issue by AlexanderKayumov** [WhisperSystems/Signal-Android#5189]
I've run into a weird little issue : my phone's LED indicator is not working as part of "new message" notifications. The sound and the vibration do work, but the LED does not, which results in **_very poor usability_** : since without the blinking LED, having missed the initial sounds and vibrations, there is then no way to tell, by just looking at the phone, whether or not there are new messages except by unlocking the screen - so in order to not miss messages _**one has to constantly unlock the screen and check for a notification in the status bar**_.

The LED used to work fine with text messages prior to the installation of Signal. It still works correctly with WhatsApp. Signal seems to be the only app where the LED is malfunctioning.

Here's my debug log : https://gist.github.com/anonymous/a4338e57a0ee8ddfc0a3 .

I submitted this issue as a support request (ID 1667) **_back on December 13_**, but have since despaired of getting any reply and so decided to create an issue here.

**Comment by 2-4601** [comment]
migrating to #1036
