### ISSUE TITLE
Additional text-only emoticons?

### ISSUE THREAD

**Issue by eosrei** [WhisperSystems/Signal-Android#5191]
This isn't important, so I am asking before creating a PR. Is there interest (chance of merge?) in adding additional text-only emoticons? There's plenty of room in the Signal keyboard emoticon tab, it's actually barren compared to the rest. Would be simple to add to `EmojiPages.java`.

Examples:
```
 ¯\_(ツ)_/¯
(╯°□°）╯︵ ┻━┻
 ┬──┬ ノ( ゜-゜ノ)
 ᕙ(⇀‸↼‶)ᕗ
 ( •_•) ( •_•)>⌐■-■ (⌐■_■)
 ( ͡° ͜ʖ ͡°)
\(ˆ˚ˆ)/
```
Far more complex option: Adding the ability for users to add custom items to the emoticon tab.

**Comment by bmaleck1** [comment]
I'm going to go with no,  far more useful features have been shutdown.

**Comment by eosrei** [comment]
@bmaleck1 Just to clarity. My primary request is literally just some additional strings added to: https://github.com/WhisperSystems/Signal-Android/blob/d543c0b36e477a8d7be555de48399aa02a397803/src/org/thoughtcrime/securesms/components/emoji/EmojiPages.java No preferences, no real code changes, and I'd make the PR.

Current list:
```java
    new StaticEmojiPageModel(R.attr.emoji_category_emoticons, new String[] {
      "=-O",  ":-P",  ";-)", ":-(", ":-)", ":-!",
      ":-$",  "B-)",  ":O",  ":-*", ":-D", ":'(",
      ":-\\", "O:-)", ":-[",
    }, null));
```

**Comment by moxie0** [comment]
I think the problem would be the alignment. Can you post a screenshot of how it looks in the emoji pane?

**Comment by eosrei** [comment]
Ah... I understand the problem, this is a fixed width 32sp GridView. I'm testing with the following EmojiPages array values:
```java
    new StaticEmojiPageModel(R.attr.emoji_category_emoticons, new String[] {
      "=-O",  ":-P",  ";-)", ":-(", ":-)", ":-!",
      ":-$",  "B-)",  ":O",  ":-*", ":-D", ":'(",
      ":-\\", "O:-)", ":-[","\u00af\\_","(\u30c4)","_/\u00af",
      "( \u2022_\u2022)","12345","1234567","\u00af\\_(\u30c4)_/\u00af",
    }, null));
```

I've discovered there is a bug in the `EmojiView.java` overflow resizing code. It attempts to resize the font when too large, but doesn't update `textBounds`.
```java
      float overflow = textBounds.width() / (getWidth() - getPaddingLeft() - getPaddingRight());
      if (overflow > 1f) {
        paint.setTextSize(targetFontSize / overflow);
      }
      canvas.drawText(emoji, 0.5f * (getWidth() - textBounds.width()), 0.5f * (getHeight() + textBounds.height()), paint);
```
Original code:
![screenshot from 2016-02-08 02 37 24](https://cloud.githubusercontent.com/assets/195061/12883446/f580cb1a-ce0c-11e5-8a03-f4acbc3adf57.png)
Modified to update `textBounds`:
![textbounds](https://cloud.githubusercontent.com/assets/195061/12883791/e0aa728e-ce0e-11e5-9124-d6374eefe5a8.png)

The slight overlap is due to the differences between .measureText() vs .getTextBounds(): http://stackoverflow.com/questions/7549182/android-paint-measuretext-vs-gettextbounds 

As you can see from the screenshots, Signal runs in the emulator with a one line change to `src/org/thoughtcrime/securesms/PassphraseRequiredActionBarActivity.java`. So that's useful.
```patch
@@ -151,7 +149,7 @@ public abstract class PassphraseRequiredActionBarActivity extends B
     } else if (DatabaseUpgradeActivity.isUpdate(this)) {
       return STATE_UPGRADE_DATABASE;
     } else if (!TextSecurePreferences.hasPromptedPushRegistration(this)) {
-      return STATE_PROMPT_PUSH_REGISTRATION;
+      return STATE_NORMAL;
     } else {
       return STATE_NORMAL;
     }
```

I'll submit a PR to fix the resizing tomorrow, then circle back to this issue.

**Comment by 2-4601** [comment]
@eosrei btw the text emojis are not vertically aligned #3426

**Comment by eosrei** [comment]
@2-4601 Thanks! I fixed both issues in the new PR.

**Comment by eosrei** [comment]
@moxie0 Ok, here are some screencaps of a sorted set of new text-only emoji/emoticons/kaomoji using the fix in #5196 . I know many more could be added, but these are good range of reasonable/useful/fun.

![newemoji1](https://cloud.githubusercontent.com/assets/195061/12903904/469fe710-ce80-11e5-954a-7286770f687b.png)
![newemoji2](https://cloud.githubusercontent.com/assets/195061/12903905/49a19a62-ce80-11e5-840b-1962c5b09505.png)

**Comment by McLoo** [comment]
What **I** do miss:
```
:-|
:->
:-x
^^
```
And as Signal is very well RTLed now, at list him:
```
(-:
```


@eosrei 1. awesome, 2. thanks for aligning (and @2-4601 for mentioning)

**Comment by eosrei** [comment]
@McLoo Great! No problem, I can add those. Even with the additions, it's still the smallest pane by far.

**Comment by eosrei** [comment]
@McLoo What's the definition for `^^`? Did you mean `^.^` ?
