### ISSUE TITLE
Please clarify some of the "other" permissions

### ISSUE THREAD

**Issue by AdKiller** [WhisperSystems/Signal-Android#5192]
Comparing the permissions of Signal with other similar apps, they are pretty standard, but under the other section there are some that raise the eyebrows, and I would appreciate some clarifications about their usage:

Signal Private Messenger Open Whisper Systems  Version 3.10.0 can access: 

1. access Bluetooth settings
2. close other apps
3. draw over other apps
4. modify system settings
5. pair with Bluetooth devices
6. read Google service configuration
7. read your social stream
8. set wallpaper
9. toggle sync on and off
10. write to your social stream

Thanks in advance

**Comment by agrajaghh** [comment]
have a look at:
http://support.whispersystems.org/hc/en-us/articles/212535858-What-are-all-these-permissions-

also, please use the support center for support questions next time, github issues are just used for tracking bugs: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md

**Comment by johanw666** [comment]
That list is slightly outdated:
`•  precise location (GPS and network-based) - Location permissions are not used at the moment but they will be used in the future so you can share your current location by sending it as a message to your friends.`
3.9.0 introduced location messages.
