### ISSUE TITLE
App in background not polling new messages

### ISSUE THREAD

**Issue by legarspol** [WhisperSystems/Signal-Android#5195]
Often time I have to open the app for Signal to poll new messages.
Basically the app do not fetch for days and it is only when you manually open the app that it actually fetch all the messages.

It happens on many devices, actually many android devices of my relatives. It happens more often with miui/xiaomi devices which is known to often kill background services for performances purposes.

It happens since months and I thought it would be a common bug. Other app do get notifications.

**Comment by 2-4601** [comment]
Closing as support issue: http://support.whispersystems.org/hc/en-us/articles/213190487-Why-is-there-a-delay-in-receiving-messages-
