### ISSUE TITLE
Phone Calls Fail When Calling via VPN

### ISSUE THREAD

**Issue by Zer0Nin3r** [WhisperSystems/Signal-Android#5198]
Signal fails to complete a phone call while connected to a VPN.

Additionally, Signal will sometimes crash.

Also, receiving a call fails while connected to the VPN.

https://gist.github.com/anonymous/c1b888eb6998facf2856

**Comment by cascheberg** [comment]
The crash in your log is a duplicate, see #4184

**Comment by Zer0Nin3r** [comment]
Should note that this issues does not happen with the OpenVPN app for Android; issue occurs with another VPN app and can discuss further over secure channels.
