### ISSUE TITLE
Verifying APK at Google Play is built from this source code?

### ISSUE THREAD

**Issue by jluttine** [WhisperSystems/Signal-Android#5202]
I searched for the answer but couldn't find it so I thought I'd ask here. Probably this has been answered somewhere already, though.

Is it possible to verify that the APK distributed at Google Play has been built from the exact source code in this repository? I suppose this would require that the source code can be compiled in a reproducible way.

Thanks for any help!

**Comment by agrajaghh** [comment]
Please use the mailing list for discussions, we are using this issue tracker just for bugs: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#issue-tracker-is-for-bugs

**Comment by jluttine** [comment]
Ok, thanks and sorry!
