### ISSUE TITLE
Logcat may contain phone numbers

### ISSUE THREAD

**Issue by eosrei** [WhisperSystems/Signal-Android#5204]
I don't know if this counts as sensitive information per the [Code-Style-Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines#be-careful-what-you-log), but I consider it to be. 

```
02-09 11:39:23.253 4698-6230/org.thoughtcrime.securesms W/EarlyReceiptCache: org.thoughtcrime.securesms.database.EarlyReceiptCache@1e9da75b
02-09 11:39:23.253 4698-6230/org.thoughtcrime.securesms W/EarlyReceiptCache: Checking early receipts (1XXXXXXXXXXXX, +1XXXXXXXXXX): null
```
*Actual phone numbers have been replaced by Xs*

Caused by: https://github.com/WhisperSystems/Signal-Android/blob/4c7d2d2c66bef15494780d27c81b34a4f273b2fb/src/org/thoughtcrime/securesms/database/EarlyReceiptCache.java#L30

Can this check the DEV_BUILD buildConfigField before logging?

**Comment by moxie0** [comment]
libphonenumber strips these out for public reporting, otherwise we need the logs clean

**Comment by eosrei** [comment]
Ok! My mistake, I didn't realize there would be a difference.

For anyone else who finds this issue: https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports#debug-log-privacy
