### ISSUE TITLE
Letter->color synesthetes have a weird feeling using Signal

### ISSUE THREAD

**Issue by ringelblum4** [WhisperSystems/Signal-Android#5205]
Because each contact has an initial (a letter) and a (randomly assigned?) color, which may be (and almost always are) terribly mismatched for letter->color synesthetes.

**Comment by agrajaghh** [comment]
you are able to change the colors for every conversation. What is your suggestion?

**Comment by ringelblum4** [comment]
@agrajaghh thank you, I didn't know.
