### ISSUE TITLE
Unable to take normal calls while speaking on Signal

### ISSUE THREAD

**Issue by darkman088** [WhisperSystems/Signal-Android#5206]
Dear Whispter Systems,

first of all I would like to express my HUGE appreciation for your product !!!
I have been testing a LOT of apps and your is by FAR the best out there !!!
I absolutely admire the CRYSTAL CLEAR call quality, it is really outstanding!
Although your app is almost perfect, I would kindly like to ask you to take a
look at one issue, which troubles me and if this gets fixed, I would pronounce
your product as PERFECT !!!
When speaking on Signal, if somebody tries to call me by phone, he simply
gets a voice message that I am unable to take his call and I just get an entry
in the missed calls list. This is not OK, as I need to call back that person.
I would like to be informed about incoming calls and have the possibility to
pause or drop the Signal call and to take the normal phone call. Please kindly
make it the default behaviour or provide an option that would enable this
behaviour.

Many thanks !!

**Comment by riyapenn** [comment]
Contact support@whispersystems.org.  Signal does not have voice messages/voicemail, so looks like your contact is not placing a Signal call.

**Comment by johanw666** [comment]
If this is true, I think it should be kept that way. When I am talking I can't take another call, wether that call is via "normal" phone, WhatsApp voice, Skype or whatever. Just as when I'm taking a "normal" call I can' take a Signal call.

**Comment by eosrei** [comment]
@johanw666 I think @darkman088 means the same functionality as when you are on a regular call and another regular call comes in. It should be possible for Signal to ask if you'd like to put the current Signal call on hold and answer the regular call.

**Comment by johanw666** [comment]
@eosrei is that standard behaviour? When I'm on call and another comes in it gets a busy tone and I hear a small beep to notice me something is on, just as when an sms comes in. If I had not deactivated voicemail it would go straight to the provider's voicemail.

**Comment by eosrei** [comment]
@johanw666 Call waiting has been a regularly enabled feature in all mobile phones I've ever used. It *is* an option though: http://www.pcadvisor.co.uk/how-to/mobile-phone/how-to-activate-call-waiting-on-a-google-android-smartphone-3305326/ Signal already has the required permissions: `PROCESS_OUTGOING_CALLS` and `READ_PHONE_STATE`. Further details: http://stackoverflow.com/questions/15563921/detecting-an-incoming-call-coming-to-an-android-device

**Comment by moxie0** [comment]
sorry there's no way to do this on android

**Comment by darkman088** [comment]
What a pity, but thanks for having a look at it anyway!
