### ISSUE TITLE
works again - Signal 3.10: messages don't appear in signal app

### ISSUE THREAD

**Issue by sirld** [WhisperSystems/Signal-Android#5209]
Hi,

since the last update I've found a problem with the signal app. When I receive messages, they appear in the notification bar on top of the phone but they don't show up in the main windows of the app, neither do they show up when I directly press "reply" from the notification bar. The problem occurs only after the latest update to 3.10. I already uninstalled and reinstalled signal - same issue.

I confirmed that it is not a problem of the sending phone; that works fine with other contacts.

Device: Samsung Galaxy S4 Mini
Android: 4.4
Debug log: [debug log](https://gist.github.com/anonymous/476c7dfa059988beabf3)
Signal is standard SMS app.

Steps to reproduce: send message to the phone.
Any help possible there?

**Comment by haffenloher** [comment]
Sounds annoying :\
Does that happen only with a particular message type (SMS / MMS / Signal messages)?

**Comment by sirld** [comment]
SMS seems to work. MMS not tested, Signal messages don't.

[Debug log of receiving a SMS](https://gist.github.com/anonymous/a02c03335ffb856de9d8)

**Comment by ddecola** [comment]
I had this happen to me as well after the most recent update. I could received a few SMS's then the rest just passed through the notification bar. This was only for one non-signal contact, other's worked fine. I don't have "message trimming" turned on, not certain if that's related or not.

**Comment by sirld** [comment]
Alright, now it works again. Probably the new update.
