### ISSUE TITLE
Messages not sent from signal don't appear in signal app

### ISSUE THREAD

**Issue by libeclipse** [WhisperSystems/Signal-Android#5211]
In certain circumstances, messages are sent but not from within the signal app. For example, when you decline a call with a message or send bulk messages with other apps. Signal only checks the local message database on first install, and messages that appear there later are ignored. If I decline a call with a message, it appears in the stock messaging app, but not in signal. Not sure if this is a feature request or a bug fix, but signal should show non-native outgoing messages, and also display delivered status.

**Comment by 2-4601** [comment]
Same cause as in #218?

**Comment by moxie0** [comment]
Yep, Signal's message store is separate from the system's.

**Comment by libeclipse** [comment]
Well, yes of course it's separate. What's your point?
