### ISSUE TITLE
Network error - which ports are required for calls?

### ISSUE THREAD

**Issue by ka223** [WhisperSystems/Signal-Android#5212]
Hi,
I can send text messages over my network without any problems, but calls are not working.

error message: "network error"

Which ports and protocols uses signal for calls?
I need to check this first.

Thanks

**Comment by 2-4601** [comment]
Closing as support issue: http://support.whispersystems.org/hc/en-us/articles/213697218-Which-TCP-UDP-ports-need-to-be-available-
