### ISSUE TITLE
Button rendering colors inconsistent

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/Signal-Android#5227]
There is a pretty wild **mixture of blue & turquois** (Android's standard color?) regarding the **button text color** in Signal's dialogs and the color of switches.

One of many examples would be _Settings >> Appearance >> Theme_ uses blue, vs. _Settings >> Advanced >> Signal messages and calls_ uses turquois.

**Some example info regarding the exact colors used (provided by @unrulygnu):**

_Settings >> Appearance >> Theme:_
CANCEL button render color: 1c7ac5 **[i. e. blue]**

_Settings >> Advanced >> Signal messages and calls:_
Switch render color: 1b78c1 **[i. e. some other blue]**
CANCEL / OK buttons render color: 80cbc4 **[i. e. turquois]**

**I suggest changing all of those consistently to Signal-blue (whatever that is - $1c7ac5 or $1b78c1).**

Edit: I've noticed that some of these (e. g. the CANCEL/OK buttons of Settings >> Advanced >> Signal messages and calls) only occur when using the **dark theme**.

Below are some example screenshots of dialogs still using turquois.

![screenshot_20151129-122541_cr](https://cloud.githubusercontent.com/assets/12624674/13033872/c96e54e8-d325-11e5-9dc4-dd93a7b39f82.jpg)
![screenshot_20151129-122645_cr](https://cloud.githubusercontent.com/assets/12624674/13033874/c96fed6c-d325-11e5-91e4-5298923c52a4.jpg)
![screenshot_20151129-122757_cr](https://cloud.githubusercontent.com/assets/12624674/13033873/c96eed4a-d325-11e5-9508-5bff74122c50.jpg)

**Comment by edo0** [comment]
Also, the pencil button uses a different (darker) shade of light blue if compared to the upper bar

**Comment by 2-4601** [comment]
I was confused at first because I saw turquoise everywhere, but then I realised that I'm using the dark theme. I.e. this seems to only affect the default light theme. Tested on stock Android 5.1.1

**Comment by RiseT** [comment]
@2-4601 I'm using the dark theme as well (see my "edit" above), and many of the dialogs use blue button colors with the dark theme as well.

Example:
*Settings >> Appearance >> Theme*

So it's inconsistent with both themes, but partially in a different way.

**Comment by 2-4601** [comment]
I see turquois buttons:
![screenshot_2016-02-14-15-58-31](https://cloud.githubusercontent.com/assets/174176/13034095/8e76d900-d334-11e5-9303-be90d5a8e0b4.png)
![screenshot_2016-02-14-15-58-37](https://cloud.githubusercontent.com/assets/174176/13034096/91ecebba-d334-11e5-8ac7-d80c91bf99fd.png)
![screenshot_2016-02-14-15-59-12](https://cloud.githubusercontent.com/assets/174176/13034098/94cc6dce-d334-11e5-8953-8fc426faed51.png)
Nexus 4, stock Android 5.1.1, Signal 3.11.1

**Comment by RiseT** [comment]
@2-4601 That's strange. Mine are blue (if really necessary, I'll create & post screenshots).

Nexus 5, Stock Android 6.01, Signal 3.11.1 (the colors have been that way for a long time, though).

**Comment by RiseT** [comment]
@2-4601 Added some screenshots.

**Comment by signalguest** [comment]
I confirm that in Marshmallow everthing is blue.

**Comment by Dyras** [comment]
I can also confirm that with Marshmallow everything is blue. I think we should go with blue as the standard, instead of the lighter blue shown in the OP. It just looks more professional, and less "baby".

**Comment by FeuRenard** [comment]
I am working on this.
