### ISSUE TITLE
Notifications showing old signal icon

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#5234]
I've noticed that for a couple versions now, the signal notification icon is showing the old one with a hole in the top of the circle. Verizon Note 5, Stock 5.1.1, dark theme.

**Comment by hankarun** [comment]
You are right, drawable-xxxhdpi-v11/icon_notification.png - should be replaced with new icon.

**Comment by HolgerJeromin** [comment]
a comment in #5250 says, this was fixed... can this be closed?

**Comment by agrajaghh** [comment]
yep, thanks
