### ISSUE TITLE
Remove single '_' identifiers from java source.

### ISSUE THREAD

**Issue by johnspurlock** [WhisperSystems/Signal-Android#5236]
Rename the conventional ignored exception variable name in catch clauses where they exist.

i.e. prefer something like `try { ... } catch (TException ignored)  { }` to `try { ... } catch (TException _)  { }`

These result in compile-time warnings under Java 8, and will be compile-time errors in Java 9.

To reproduce:
 - Build Signal-Android using a Java 8 SDK [1]

[1] $ java -version
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

**Comment by moxie0** [comment]
you're looking at upstream code, so we're not going to change it
