### ISSUE TITLE
Inconsistencies in rendering colors on Marshmallow vs. Lollipop

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/Signal-Android#5239]
While first thinking of a strange design decision (I'm on Marshmallow), I've just noticed that using the **light theme**, the **background colors** of the **conversation list** vs. the **contact list** are are different ones on Marshmallow vs. Lollipop.

**Marshmallow, light theme**
Conversation list: EEEEEE
Contact list: FAFAFA

**Lollipop, light theme**
Conversation list: EEEEEE
Contact list: EEEEEE

On the other hand, with the **dark theme**, the background colors of the conversation list and the contact list - while respectively using different colors (which IS a strange design decision) - **are identical on both platforms**.

**Marshmallow & Lollipop, dark theme**
Conversation list: 000000
Contact list: 303030

The background colors of the conversation list and the contact list should be identical per theme imho.

This is in addition to the button text & switch coloring issues mentioned in #5227, which partially behave differently on Marshmallow & Lollipop as well.
There might be more coloring inconsistencies between Marshmallow & Lollipop, but these are the ones I've discovered so far.
Colors have been measured from screenshots with paint.net

**Comment by RiseT** [comment]
**Additional background color inconsistencies**

**Recipient preferences**
Marshmallow, light theme: FAFAFA
Lollipop, light theme: EEEEEE
Marshmallow & Lollipop, dark theme: 303030

**Comment by FeuRenard** [comment]
Mainly solved by https://github.com/WhisperSystems/Signal-Android/commit/d71fb4c958693db09ba48cae0e14a2b87e34c165
