### ISSUE TITLE
Can't easily close quick response overlay

### ISSUE THREAD

**Issue by sedrubal** [WhisperSystems/Signal-Android#5241]
After tabbing on reply in messages there is no easy way to close the overlay and not sending a message.

### Steps to reproduce:

 - wait in homescreen until a message arrives
 - tab on reply
 - try to close the reply overlay without sending

### expected behaviour/proposal:

 - Swipe up to close the overlay. (The overlay appeared by sliding down, so I want to swipe it up)
 - add a close button next to raise/open button (but that's ugly)

### Device info:

Nexus 5, OmniRom 6.0.1, Signal 3.10.0

**Comment by moxie0** [comment]
thanks but I think we're cool with it the way it is (tapping back)
