### ISSUE TITLE
FEATURE REQUEST: PIN for privacy alternative to passphrase

### ISSUE THREAD

**Issue by brettus78** [WhisperSystems/Signal-Android#5243]
Hi,
I've searched for references to PIN in existing issues and was unable to find any existing references. If there is one, I apologise in advance but I wasn't able to locate any.

I use the passphrase option to lock the app (privacy settings) and love the feature but would like it if there was an alternative option to have it as a passcode/PIN instead of a passphrase. Keep the passphrase for first use after a restart of the phone and for encryption, etc. but for inactivity timeout a PIN entry in the same style as Nine (email client) and Telegram would be awesome. Where you set a PIN. It provides the buttons so that keyboard isn't required (handy especially if keyboard is recording strokes for autocorrect, etc.) and no need to press "return/enter" - it just unlocks if correct PIN is entered.

Cheers,
Brettus

Examples below:
![image](https://cloud.githubusercontent.com/assets/4017235/13097735/c597990c-d55e-11e5-8416-902dea16cfbf.png)

![image](https://cloud.githubusercontent.com/assets/4017235/13097748/e55bb55c-d55e-11e5-8aec-ecabfd31422f.png)

![image](https://cloud.githubusercontent.com/assets/4017235/13097765/0107c390-d55f-11e5-8c61-fd71234c9dd1.png)

**Comment by moxie0** [comment]
Thanks but we're not going to do this

**Comment by brettus78** [comment]
No worries. Keep up the excellent work though. Great product that is only getting better.
