### ISSUE TITLE
Connectivity Error

### ISSUE THREAD

**Issue by bearfacts** [WhisperSystems/Signal-Android#5244]
Sorry to clutter things up with what may be a support issue here, but I've been unable to register Signal Private Messenger (3.10.0):
- App installed (and reinstalled) from the Play store.
- The same errors occur using both mobile data and WiFi.
- Google Play Services are current.
- The email address for the play account is current.
- Push Notification Fixer appears to work.
- Android is 4.3.
- Phone is a Verizon Samsung Galaxy SIII.

Since I can't register, I can't get to the internal debug log generation. An adb logcat output is at https://gist.github.com/bearfacts/5f6c4eb5b2bab2ac6f71

Any assistance or even a simple message that my issue does not merit developer consideration would be appreciated.

**Comment by moxie0** [comment]
Sorry to say, but it looks like there's something wrong with your google services setup:

```
W/RegistrationService( 2961): java.io.IOException: PHONE_REGISTRATION_ERROR
W/RegistrationService( 2961): 	at com.google.android.gms.gcm.GoogleCloudMessaging.zza(Unknown Source)
W/RegistrationService( 2961): 	at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
W/RegistrationService( 2961): 	at org.thoughtcrime.securesms.service.RegistrationService.handleCommonRegistration(RegistrationService.java:247)
W/RegistrationService( 2961): 	at org.thoughtcrime.securesms.service.RegistrationService.handleSmsRegistrationIntent(RegistrationService.java:208)
W/RegistrationService( 2961): 	at org.thoughtcrime.securesms.service.RegistrationService.access$000(RegistrationService.java:63)
W/RegistrationService( 2961): 	at org.thoughtcrime.securesms.service.RegistrationService$1.run(RegistrationService.java:95)
W/RegistrationService( 2961): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
W/RegistrationService( 2961): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
W/RegistrationService( 2961): 	at java.lang.Thread.run(Thread.java:841)
```

There's nothing we can do about that on the software development side of things, so this is going to be more of a support issue.  Sorry!

**Comment by bearfacts** [comment]
Please don't apologize!

This was everything that I needed to get my issue addressed. A very 
little searching led to:

https://stackoverflow.com/questions/23553571/gcm-registration-fail-java-io-ioexception-phone-registration-error

Which resolved the issue.

Thanks!

**Comment by bearfacts** [comment]
Thanks for identifying the issue! 
http://grokbase.com/t/gg/cerberus-support-forum/139md9h3g6/gcm-phone-registration-error
by way of
https://stackoverflow.com/questions/23553571/gcm-registration-fail-java-io-ioexception-phone-registration-error
resolved the issue. Just in case of bit rot the solution was:
- Go to Settings -> Applications -> Manage applications -> All
- Select "Clear data" for "Google Play services" and "Google services
framework"
- Temporarily unlink your Google account from the phone
- Reboot the phone
- Re-associate your Google account
