### ISSUE TITLE
No way to move to new device??? - Some Suggestions

### ISSUE THREAD

**Issue by Grunthos** [WhisperSystems/Signal-Android#5245]
Backup is disabled, and there is no full backup in the app. 

Any chance of publishing an APK that is interchangeable with the main APK (signing my own won't do the job) that allows backup? Then at least I'll be able to use Helium again.

Or create a non-secure local backup?

Or remove keys from backup, enable backup again, and add a 'share/send keys' option?

**Comment by moxie0** [comment]
Hey @Grunthos sorry but we don't use the issue tracker as a discussion forum.  There are open issues for backup.
