### ISSUE TITLE
What happened to encrypted SMS fallback?

### ISSUE THREAD

**Issue by penguinpowernz** [WhisperSystems/Signal-Android#5248]
I just installed the latest Signal (3.9.1), and installed it on GFs phone as well.  Then I text her and she didn't get my text until she turned her data on the next day.

This used to work so well, especially in our country where mobile data is finite and very expensive and where we may not want to have our data enabled for fear of further tracking/random apps eating your cap.  Sending messages over data is great and all I understand the metadata security implications of SMS but surely it is better to send metadata in the clear, and the message encrypted, than sending both in the clear? Seemed like a great way to backport encryption to older technologies.

The other great thing about the app was that you could replace the shitty stock SMS apps that come with smartphones with this beautiful application and get encryption to people who have the same app, over data or SMS.

I read over issue #2847 and they seemed to completely discount this whole user base and the above use cases... pretty sad.

I don't want to have to go back to the shitty stock SMS app :(

**Comment by penguinpowernz** [comment]
OK searched wrong keywords found some other issues now.

**Comment by penguinpowernz** [comment]
Can't seem to find anyone saying whether you can enable encrypted SMS messages. Is this possible?  It used to work great.

**Comment by agrajaghh** [comment]
You can still use Signal to send and receive normal SMS. Go to Settings -> SMS

**Comment by agrajaghh** [comment]
also have a look at: https://whispersystems.org/blog/goodbye-encrypted-sms/
