### ISSUE TITLE
New smileys use unknown symbols

### ISSUE THREAD

**Issue by He-Ro** [WhisperSystems/Signal-Android#5249]
Some of the new smileys use characters that are not present on my device and are represented with a crossed out box.

My device is a Sony Xperia Z5 compact with stock Android 5.1.1.
I do not think that a debug log would be helpful, but here is one anyways:
https://gist.github.com/anonymous/f5ec6be2ba2d629aaa65

And a screenshot to illustrate the issue:
![broken_smileys](https://cloud.githubusercontent.com/assets/3579374/13106711/0050d1de-d56a-11e5-9939-35b99bf90e80.png)

**Comment by agrajaghh** [comment]
CC @eosrei

**Comment by McLoo** [comment]
Guess Sony isn't covering enough Unicode  characters on there systems. 
Same for me on Z1 compact. (systemwide, not only signal. See here: https://en.m.wikipedia.org/wiki/Syriac_alphabet )

**Comment by eosrei** [comment]
Of course. :disappointed: I thought this Unicode was supported everywhere.

Solutions:

0. Do nothing. Probably not really an option. ;)
1. Adding a font from stock Android. Excessive.
2. Removal/Replacement/Adjustment. Frustrating, but probably ideal.

8 need changes. A few can be fixed using characters I see working in this screenshot. My Sony runs cyanogenmod, so I don't have a way to test for what's available.

**Comment by agrajaghh** [comment]
I have a Sony with Stock ROM as well, so I could send you a screenshot if you give me some test strings if that helps. But how can we know what other vendors support?

**Comment by eosrei** [comment]
I wanted a full range, so I sourced some from a few Japanese websites. It's those kaomoji causing the problems. The majority of these characters have been supported for years.

**Comment by eosrei** [comment]
Original:
```
(͡• ͜ʖ ͡•) (͡° ͜ʖ ͡°) ^.^  ^_^  •ᴗ• ƪ(˘⌣˘)ʃ \(ˆ˚ˆ)/ \(•◡•)/ (✿◠‿◠)
(っ⌒‿⌒)っ (っ'з')っ (ღ˘⌣˘ღ) ~(˘▾˘~) ᕕ( ᐛ )ᕗ ¯\(°_o)/¯
¯\_(ツ)_/¯ (─‿‿─) (¬_¬) (>_<) (͠◉_◉᷅ ) (╥﹏╥) ಥ_ಥ ಠ_ಠ
ᕦ(ò_óˇ)ᕤ (ง︡'-'︠)ง (☞ﾟヮﾟ)☞  ☜(ﾟヮﾟ☜) ☜(⌒▽⌒)☞  (╯°□°)╯︵ ┻━┻  ┬─┬◡ノ(°–°ノ)
ヽ(°◇° )ノ (☉̃ₒ☉) (^._.^)ﾉ ฅ^•ﻌ•^ฅ (•_•) (•_•)>⌐■-■ (⌐■_■)
```

Reduced and modified to use existing working characters:
```
(͡• ͜ʖ ͡•) (͡° ͜ʖ ͡°) ^.^  ^_^  •ᴗ• ƪ(˘ᴗ˘)ʃ \(ˆ˚ˆ)/ \(•‿•)/ (✿⌒‿⌒)
(っ⌒‿⌒)っ (っ'з')っ (ღ˘ᴗ˘ღ) ~(˘▾˘~) ¯\(°_o)/¯
¯\_(ツ)_/¯ (─‿‿─) (¬_¬) (>_<) (͠◉_◉᷅ ) (╥﹏╥) ಥ_ಥ ಠ_ಠ
(ง︡'-'︠)ง (☞ﾟヮﾟ)☞  ☜(ﾟヮﾟ☜) ☜(⌒▽⌒)☞  (╯°□°)╯︵ ┻━┻  ┬─┬ノ(°–°ノ)
ヽ(°◇° )ノ (^._.^)ﾉ ฅ^•ﻌ•^ฅ (•_•) (•_•)>⌐■-■ (⌐■_■)
```

ᕕ( ᐛ )ᕗ is the only one I'm sad about losing, it's so good. Does this reduced set work?

**Comment by He-Ro** [comment]
At least in the GitHub App they appear to all display correctly:

![screenshot_2016-02-17-19-23-55](https://cloud.githubusercontent.com/assets/3579374/13120099/77c22f46-d5ac-11e5-82c6-84751a023b76.png)

**Comment by McLoo** [comment]
Sony... Japan 
Kaomoji... Japan 
Weird 

![screenshot_2016-02-17-20-16-31](https://cloud.githubusercontent.com/assets/5326916/13121672/9c3505b8-d5b3-11e5-9275-3268dcf9e822.png)

Shown in Chrome

**Comment by eosrei** [comment]
@McLoo I suppose we need to remove all of the Kaomoji then, sigh. So weird that Sony drops all these extended characters on English phones. Gotta save those bytes! Wouldn't want to remove some of the hardcoded Sony apps instead?! Those apps are one of the reasons my Sony has cyanogenmod.

**Comment by D4nte** [comment]
Similar issue with my cyanogenmod oneplus one. This character shows as a crossed box in signal : 🤓

**Comment by 2-4601** [comment]
Android 4.0.4 has issues with 14 of those smileys.
![4 0 4](https://cloud.githubusercontent.com/assets/174176/13152625/c46cd568-d678-11e5-8a1c-ed18319cb209.png)
I'd vote for solution 1, i.e. do nothing :)
The old and shitty ROMs are annoying party poopers. They should just deal with it (⌐■_■)

**Comment by agrajaghh** [comment]
for Android <= 4.0.4 I would maybe agree, thats "just" 5% (altough it might be more for Signal)

But even the reduced set above isn't correctly displayed for me on a Sony Z3C with 5.1.1

btw, Chrome is displaying less emojis correctly than Signal for me

**Comment by moxie0** [comment]
if there are any devices that don't display these characters correctly, please remove them

**Comment by eosrei** [comment]
Ok, will do.

**Comment by eosrei** [comment]
@D4nte That's a separate, but related issue. The 🤓 is [U+1F913](http://www.fileformat.info/info/unicode/char/1f913/index.htm) and was added to iOS 9.1 and Android 6.0.1. It is not supported by Signal ([current supported people emoji](https://github.com/WhisperSystems/Signal-Android/blob/9a18be0a6194d4dd8ef420e9b567b1d7ce69c613/assets/emoji-people.png)). It's going to require updating: http://blog.emojipedia.org/ios-9-1-emoji-changelog/

@moxie0 FWIW regarding my # 2 (adding a font) above, Betterpickers is already adding three fonts to the APK:
```
./build/intermediates/exploded-aar/com.doomonafireball.betterpickers/library/1.5.3/assets/fonts/AndroidClockMono-Thin.ttf
./build/intermediates/exploded-aar/com.doomonafireball.betterpickers/library/1.5.3/assets/fonts/Roboto-Bold.ttf
./build/intermediates/exploded-aar/com.doomonafireball.betterpickers/library/1.5.3/assets/fonts/Roboto-Light.ttf
```
Plus there is https://github.com/WhisperSystems/Signal-Android/blob/master/assets/fonts/Roboto-Light.ttf The problem is in both cases this is Version 1.200310 of Roboto Light, a very old version. Much more recent versions are available here: https://github.com/google/roboto/tree/master/hinted Although it still doesn't contain, for example, the [Unified Canadian Aboriginal Syllabics](https://en.wiktionary.org/wiki/Appendix:Unicode/Unified_Canadian_Aboriginal_Syllabics) required to display: ᕕ( ᐛ )ᕗ

**Comment by eosrei** [comment]
Here is a severely reduced set. I believe it removes everything importantly broken per the screenshots above. Let me know if anything is broken on any other devices. (>_<) 
```
:-)  ;-)  (-:  :->  :-D   \o/
:-P  B-)  :-$  :-*  O:-)  =-O
O_O  O_o  o_O  :O   :-!   :-x
:-|  :-\  :-(  :'(  :-[   >:-(
^.^  ^_^  \(ˆ˚ˆ)/   ~(˘▾˘~)
¯\(°_o)/¯  ¯\_(ツ)_/¯  (¬_¬)
(>_<) (╥﹏╥)
(☞ﾟヮﾟ)☞    ☜(ﾟヮﾟ☜)   ☜(⌒▽⌒)☞
(╯°□°)╯︵ ┻━┻    ┬─┬ ノ(°–°ノ) 
ヽ(°◇° )ノ  (^._.^)ﾉ  ฅ^•ﻌ•^ฅ
(•_•)  (•_•)>⌐■-■    (⌐■_■)
```
I'll make a PR with this list when I have confirmation. Thanks everyone!

FWIW I figured out a solution (untested and not that I expect to implement it): subset the required glyphs into a new font using the Noto fontset: https://android.googlesource.com/platform/external/noto-fonts/+/master/other/

**Comment by agrajaghh** [comment]
looaks good for me on Nexus 4 (5.1.1), Sony Z3C (5.1.1), HTC Desire (2.3.7)

**Comment by He-Ro** [comment]
For me as well on Sony Xperia Z5C.

**Comment by 2-4601** [comment]
Two characters don't work in Android 4.0.4:
* [U+25BE](http://www.fileformat.info/info/unicode/char/25be/index.htm) or `▾` or the "mouth" in `~(˘▾˘~)`
* [U+2310](http://www.fileformat.info/info/unicode/char/2310/index.htm) or `⌐` or the "left sunglass temple" in `⌐■-■`

I guess the mouth has a lot of other options and is easy to replace.
For the sunglasses you could e.g. turn the emoji around by using the regular [not sign](http://www.fileformat.info/info/unicode/char/00ac/index.htm) `■-■¬`

**Comment by agrajaghh** [comment]
> Two characters don't work in Android 4.0.4:
> 
>     U+25BE or ▾ or the "mouth" in ~(˘▾˘~)
>     U+2310 or ⌐ or the "left sunglass temple" in ⌐■-■

puhh, I missed them, they don't awork for me on 2.3.7 (makes sense I gues...)

**Comment by eosrei** [comment]
I'll remove `~(˘▾˘~)`, because changing the mouth character IMO changes the meaning and I don't want to found out ▼ is broken elsewhere.

I'd like to argue for keeping ⌐■-■ as is, even if that one character doesn't display. The missing  ⌐ (revlogicalnot/U+2310) doesn't change the meaning and the unicode character is still sent by the device. The problem is that is part of the entire (•_•)    (•_•)>⌐■-■    (⌐■_■) sequence, so I can't just reverse the one.

Here is the even more reduced version with the sunglasses sequence removed. :cry: At least ¯\_(ツ)_/¯ is holding up. I had no idea this would be so complicated... haha
```
:-)  ;-)  (-:  :->  :-D   \o/
:-P  B-)  :-$  :-*  O:-)  =-O
O_O  O_o  o_O  :O   :-!   :-x
:-|  :-\  :-(  :'(  :-[   >:-(
^.^  ^_^  \(ˆ˚ˆ)/   ~(˘▾˘~)
¯\(°_o)/¯  ¯\_(ツ)_/¯  (¬_¬)
(>_<) (╥﹏╥) (•_•) 
(☞ﾟヮﾟ)☞    ☜(ﾟヮﾟ☜)   ☜(⌒▽⌒)☞
(╯°□°)╯︵ ┻━┻    ┬─┬ ノ(°–°ノ) 
ヽ(°◇° )ノ  (^._.^)ﾉ  ฅ^•ﻌ•^ฅ
```
 Ok?

**Comment by 2-4601** [comment]
Looks ok.

Couldn't you reverse the whole sequence like this:
`(■_■¬)    ■-■¬<(•_•)    (•_•)`

**Comment by eosrei** [comment]
Yes, but that's taking the glasses off to Left to Right readers, plus we don't know if the substitute character is available everywhere.

**Comment by 2-4601** [comment]
How about this then?
`(•_•)    ■-■¬<(•_•)    (■_■¬)`

Looks like it's putting them on now :)

Btw, you are using the `¬` already in one of the emojis: `(¬_¬)`

**Comment by eosrei** [comment]
Ah good point! Plus since they are separate it can be written in either reading direction. I'll add and PR in a few min.
