### ISSUE TITLE
Signal can text but call always fail

### ISSUE THREAD

**Issue by JohnyM01** [WhisperSystems/Signal-Android#5251]
Hello,

I from Australia can text my friend in Macau China both are using Signal on Android 3.10.0. But when I call the other party, Signal rings for a while but then it says "Call End" and call failed. Same thing happens when the other party initiates the call.

Attach is a debug log https://gist.github.com/d57c2f884b3726a8dce9 for call initiated by me that fails. Hope this will help to unlock the mystery.

Could this be because that the other party in Macau is using a network on a university campus that is blocking the require ports?

Skype to Skype works perfectly and it seems strange that about a brief chat on Signal we have to flick over to Skype for voice.

My Signal using voice works wonderfully to US without trouble.

Thanks.

Johny

**Comment by moxie0** [comment]
Looks like someone is killing the connection, either the other party or something on the network.

**Comment by JohnyM01** [comment]
Thanks. The other party advised me after the call failed that they have a message saying "Signal has stopped" Why would signal suddenly stopped?

**Comment by moxie0** [comment]
couldn't tell you without a debug log

**Comment by JohnyM01** [comment]
I will try to coach the other party to submit the log and I will report link. Voice on that Signal on Android worked flawlessly in US.

**Comment by JohnyM01** [comment]
Hello I am just wondering if it is related to this problem http://support.whispersystems.org/hc/en-us/articles/213697218-Which-TCP-UDP-ports-need-to-be-available-

Does Signal still require port 31337, which seems to be used by trojan? etc Won't be surprise people not block it.

Johny
