### ISSUE TITLE
Google Play Store: "Package File is invalid" (Android 2.3.3)

### ISSUE THREAD

**Issue by Floody2003** [WhisperSystems/Signal-Android#5254]
After downloading the app (v3.11.1) from the Google Play Store, the installation abort with the error message "Package File is invalid".

The device is a HTC with Android 2.3.3. A factory reset was made on the cellphone.

When I trying to build and install the APK with Android Studio 2 the following error occurs:

`02-17 21:53:55.254 1244-1244/? W/installd: DexInv: --- END '/data/app/org.thoughtcrime.securesms-1.apk' --- status=0x000b, process failed
02-17 21:53:55.254 1244-1244/? E/installd: dexopt failed on '/data/dalvik-cache/data@app@org.thoughtcrime.securesms-1.apk@classes.dex' res = 11
02-17 21:53:55.264 1332-1362/? W/PackageManager: Package couldn't be installed in /data/app/org.thoughtcrime.securesms-1.apk`

**Comment by riyapenn** [comment]
This is an issue with your phone and Google Play store.  http://support.whispersystems.org/hc/en-us/articles/217293017-What-do-I-do-if-i-see-Package-file-is-invalid-
