### ISSUE TITLE
Allow deleting conversations from the "conversation item" view

### ISSUE THREAD

**Issue by salty-horse** [WhisperSystems/Signal-Android#5259]
When receiving an SMS, the "conversation screen" with the SMS has no "delete" option in menu.
To delete the conversation, one has to go back to the Conversation List screen, long-press an item to enter Batch selection mode, and click the delete button.

This is very cumbersome. There should be a delete option in the menu. The native Android messaging app provided by Google already has such an option.

**Comment by 2-4601** [comment]
This is intended: https://github.com/WhisperSystems/Signal-Android/pull/4698#issuecomment-159414370

**Comment by salty-horse** [comment]
Sad to see the linked comment doesn't provide any rationale.
