### ISSUE TITLE
Does the string "Signal system database import" make any sense...?

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/Signal-Android#5262]
The recent commit https://github.com/WhisperSystems/Signal-Android/commit/25d7931358658764b99881d8a507ebd806dc53ef uses the string **"Signal system database import is complete."** (I am aware that @haffenloher just made the already existing string translatable and replaced "TextSecure" with "Signal" - so not pointing fingers).

**"Signal system database"** doesn't make any sense to me, i. e. having "Signal" and "system" in the same expression imho contradicts itself.

There are
a) Signal's (encrypted) database and
b) Android's central database for SMS/MMS, which is used by other messaging apps.

What this string means to describe is the process of importing from (b) to (a), i. e. **from the system database to Signal's database**.

So this really should read **"System database import is complete."**, correct?

While I'm at it, I'd rather suggest **"Import of the system's SMS/MMS database has been completed."** (this assumes that this string is the text body of a dialog - more space for more detailed info available - while "Import complete" is the dialog's title) or **"Import of system database completed."** if something shorter is needed.

**Comment by haffenloher** [comment]
Yep, I agree, I should have changed it immediately. Went for the shorter string now as it is displayed in a one-line notification.
