### ISSUE TITLE
Choose preferred SIM

### ISSUE THREAD

**Issue by mach-o** [WhisperSystems/Signal-Android#5266]
Signal seems to send unsecured SMS on dual-SIM phones using the first SIM (present) in the device irrespective of the user's "preferred SIM" Android-system setting.

A choice of SIM to send from would be great.

When a conversation is opened, I suggest having Signal tell the user that it will send SMS from the SIM that the most recent message in the conversation was sent or received on. If no messages yet exist in the conversation, I would instead use the preferred SIM for SMS in Android's settings. If Android's preferred SMS SIM has been set to "ask every time", then I would simply choose one arbitrarily. You could instead prompt the user, but that seems unnecessarily obtrusive to me.

Finally, it would also be nice to be able to, at any moment, toggle between SIMs (or cycle between them, in the case of a 4+ SIM phone), using some mechanism like swiping left or right on the compose message box. Other apps will actually pop up a SIM selector dialog, but I find this to be annoyingly obtrusive.

Thanks for considering this feature!

**Comment by mitar** [comment]
I like the idea. I also think remembering the last SIM for a conversation would be the best trade-off between complexity and utility.

**Comment by moxie0** [comment]
> I also think remembering the last SIM for a conversation would be the best trade-off between complexity and utility.

This is already how it works.

**Comment by mitar** [comment]
Oh, I understood from the ticket that there is no way to choose from which number the message is send.

**Comment by John-Kenney** [comment]
I have a dual SIM Huawei Honor 5x. SIM 2 is set as the default for calls & messages in Android settings, but I can only send SMS for new conversations from SIM 1 in Signal.

**Comment by HackBug** [comment]
I have the same issue with the Honor 5x as John-Kennedy. Even when I fully disable the other sim card Signal does not respect the chosen card. No other app has the same issue.

**Comment by mach-o** [comment]
Should this issue be closed? New versions allow you to choose SIM by pressing + holding send, which I like, although is not at all obvious for users who don't know this and are trying to figure out how to do it. Something to improve on, maybe.

**Comment by HackBug** [comment]
I did not even realize that was an option mach-o. The interface is very clunky for this, and regardless, it doesn't respect the system settings for the default SIM. It would be really nice if there was an option to change the default SIM in the settings somewhere so I didn't have to remember to switch it every time I start a new conversation.

**Comment by martijnotto** [comment]
Another issue with this is replying to an incoming text message Signal does not try to respond using the SIM the message came in on. This means the receiver will see a message coming in from an unexpected number instead of the number that he/she just sent a message to.

**Comment by kaimast** [comment]
I second @martijnotto's comment. This is super annoying.

**Comment by kaimast** [comment]
I also just noticed that whenever I send a MMS it switches back to the wrong SIM.

Also one of my SIMs is actually disabled but Signal still tries to send from it. Should I file a separate bug report for this?

**Comment by mlofjard** [comment]
On my dual-sim phone it defaults to the SIM last used to send a message in the conversation. But when I receive a message on SIM2 in a whole new conversation, then it defaults to replying with SIM1, which is kind of annoying. It would be great if it would default to reply on the SIM that the message was received on.

**Comment by Asphahyre** [comment]
Signal should let us be able to chose to send unsecure messages by default, in addition to be able to select the default SIM card by conversation.
Signal choose to send secure messages by default each time I open a conversation with someone who installed Signal, even people who don't use this app by default or people who don't have internet access on their phone.

**Comment by decon89** [comment]
So, are there any plans to fix this? I have two sims, one US and one DK. I have disabled the DK sim in the Android settings and set the US sim as the default. However, Signal still insists on using the DK sim - at least it says so in the message text field. I haven't tried to send a text after having disabled the DK sim/set it as default, as it would irritate my friends and also cost me a lot of money. So I cannot tell if Signal will actually send the text from my DK sim as it says in the text field. I have tried restarting the app, and it doesn't change anything. 

Please, if the contact I'm writing to does not have signal, then let me change the default sim from one to another. I would love to use Signal as my default text app, but unfortunately I have to switch back. It's to much of a hassle to always remember to long press on send, and then select the correct sim.

**Comment by moxie0** [comment]
Based on this feedback, here's what I've done:

1) If you receive an SMS for someone on a SIM, the default for that conversation will update to that SIM, unless you're actively in the conversation and have explicitly selected a different SIM manually.

2) The Android N API will give me access to the "preferred SMS SIM" system setting, so if you're on Android N new conversations use that.

Thanks for all the info

**Comment by jemfinch** [comment]
This seems to have regressed now; multiple times over the last month I've been bitten by signal replying via SIM1 to MMS sent to SIM2.
