### ISSUE TITLE
Selecting multiple attachments to send crashes the app

### ISSUE THREAD

**Issue by hlorenz** [WhisperSystems/Signal-Android#5272]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
If I want to send someone more than one image at once (I know that's not implemented (#4629), but selecting them is possible with e.g. Amaze File Manager or any other file managing app I guess), Signal crashes.
As far as I investigated there is no difference between a Signal contact and an SMS contact.
Tested it with images and audio files.

### Steps to reproduce
- Press the attachment button and select image
- Choose your favorite file managing app for the action (I used Amaze File Manager)
- Select multiple images and click select
- Crash

### Device info

 **Model:** Fairphone 1U
 **Android version:** 4.2.2
 **Signal version:** 3.11.1

Edit:
Added debug log: https://gist.github.com/anonymous/e886d1a7dbececee762e

**Comment by 2-4601** [comment]
@hlorenz Could you provide a debug log? I tried to reproduce but don't have the option to choose a file manager.

**Comment by FeuRenard** [comment]
I tried to reproduce with Amaze File Manager on Fairpone 2 running Android 5.1.1 but I was not able to long-press select an image.

**Comment by agrajaghh** [comment]
had a quick look at the code:
https://github.com/WhisperSystems/Signal-Android/blob/master/src/org/thoughtcrime/securesms/mms/AttachmentManager.java#L292

we don't set `EXTRA_ALLOW_MULTIPLE`
http://developer.android.com/reference/android/content/Intent.html#EXTRA_ALLOW_MULTIPLE
> Extra used to indicate that an intent can allow the user to select and return multiple items. This is a boolean extra; the default is false.  [..]

So this looks like a bug of Amaze File Manager, but I guess Signal shouldn't crash anyway. Debug log would be helpful to see where exacly its crashing...

**Comment by hlorenz** [comment]
I uploaded the debug log:
https://gist.github.com/anonymous/e886d1a7dbececee762e
