### ISSUE TITLE
Slow sync after resume and no sync in standby after 3.11.1

### ISSUE THREAD

**Issue by signalguest** [WhisperSystems/Signal-Android#5273]
### Bug description
I get like 1 message/second or worst and if i'm on signal window
In standby i'm not getting even synced, it just pause syncing
In the 5 mins before debug log i did some standby and resume
The standby no sync is apparently not constant

### Steps to reproduce
- exchange lot of messages on desktop client
- open your mobile client

### Device info
 **Android version:** 6.0.1 aka Marshmallow

 **Signal version:** 3.11.1 (from 3.10)

### Link to debug log
https://gist.github.com/3ba0f0647246586a3f44

Edit:
Sorry for the title rename hell, why github hasn't any latency to correct the title?

**Comment by moxie0** [comment]
looks like you're running CM, so I'm inclined to believe it's a rom issue

**Comment by signalguest** [comment]
Standby syncing is kinda working, but is slow as when i'm watching

Any other kind of debug log that i can add? Even a system one?

I use XMPP too with Conversations, but i guess we can't compare with Signal.
What about Telegram? Doing fine, i don't get that slow motion messages

**Comment by moxie0** [comment]
Try rebooting your phone, this is almost certainly a rom issue

**Comment by signalguest** [comment]
Woah that really affected the behaviour. I need to check if it's going like that if i don't sync for a lot of time

**Comment by signalguest** [comment]
Often i can't get messages to signal server

https://gist.github.com/9de3f1f18d5d2c2af3ec

**Comment by signalguest** [comment]
I discovered that the first message is notified, and when i wakeup everything sync.
(in background i just get notified but not synced)

But after the first message, everything that come later does only that:
GcmBroadcastReceiver: GCM message...
W GCM-DMM : broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10000000 pkg=org.thoughtcrime.securesms (has extras) }

**Comment by signalguest** [comment]
Ok, let's update my issue status.

I got new CM build and GApps, plus phone reset.

If signal is on background anything is synced or notified.

https://gist.github.com/f728a424c6bc4798afb6

**Comment by agrajaghh** [comment]
did you exclude Signal from the marshmallow doze feature? Btw, is this even needed? (sry I don't have a marshmallow phone :disappointed:)

**Comment by 2-4601** [comment]
+ rule out all these http://support.whispersystems.org/hc/en-us/articles/213190487-Why-is-there-a-delay-in-receiving-messages-

**Comment by signalguest** [comment]
Well I tried to whitelist Signal in Doze for some time and I din't notice any change, anyway i'm going to leave Signal out of Doze and check for a long time, maybe i should try a fresh restart after the whitelist.

The only thing in that list that i missed is the app to keep alive push notification but this is not the case, really.
Other Apps that use push notifications work fine, the're all in Doze too.

I'm using ADB to monitor logcat and i can tell you that push things are received, the only problem is that the phone doesn't react to them, Signal doesn't sync after a GCM broadcast intent.

Every message i get in background produce the thing i said before:
GcmBroadcastReceiver: GCM message...
W GCM-DMM : broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10000000 pkg=org.thoughtcrime.securesms (has extras) }

This is happening for each message i get. So is not a network issue, is a reaction one.

**Comment by 2-4601** [comment]
@signalguest Try to capture a log while the three dots ... dance for too long.

**Comment by signalguest** [comment]
Actually bunch of my later log are when dots ... are still dancing.

I will try later to help with some system log instead of just Signal

**Comment by signalguest** [comment]
Doze disabled is going fine at the moment.
