### ISSUE TITLE
Hide recipient's phone number on conversation screen

### ISSUE THREAD

**Issue by legendavey** [WhisperSystems/Signal-Android#5277]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description

This is more of a UI request, but it would be great if there was an option to hide the _recipient's phone number on the conversation screen_. If I recall correctly, the iOS version at the time of writing this lets you _toggle the display between the name and the number_.

### Screenshots

![index](https://cloud.githubusercontent.com/assets/16050627/13215887/956010d8-d97e-11e5-9f81-ee42adce3362.png)

### Device info

 **Model:** Moto G

 **Android version:** 6.0.1, Cyanogenmod 13

 **Signal version:** 3.11.1

**Comment by agrajaghh** [comment]
why do you want to hide it?

**Comment by legendavey** [comment]
I love the way Signal is right now, but I think displaying the recipient's phone number, say while in public or possibly around someone inquisitive would be undesirable. 

Just my two cents. :smile:

**Comment by legendavey** [comment]
Maybe have the phone number show up in the conversation options instead or show up upon long-pressing the recipient's name?

**Comment by vtewar** [comment]
I agree, the phone number in the chat window should not be shown directly, rather in the conversation setting to ensure privacy

**Comment by moxie0** [comment]
thanks but we're not going to do this

**Comment by legendavey** [comment]
Alright, thanks for your time! :+1:

**Comment by ArmeF97** [comment]
@moxie0  could you please tell us why not?

**Comment by rahulthewaffle** [comment]
bumping @ArmeF97's request, seems really problematic for user privacy (imo the main point of using signal) if you can't use the app on desktop or mobile in public without the danger of exposing PII

**Comment by Meteor0id** [comment]
Just giving followers of this gifhub issue an update:
After years if not knowing why Moxie told us "we're not gonna do this" the devs have changed their mind and are now working on releasing a new version which does hide the pjone number from the header of conversations.

https://community.signalusers.org/t/option-to-hide-contact-phone-number-on-the-top-of-the-chat/4455/38

Thanks to everyone here for rowing against the stream, you made it happen.
