### ISSUE TITLE
Feature request: A way to store incoming pictures in bulk

### ISSUE THREAD

**Issue by Argafal** [WhisperSystems/Signal-Android#5282]
Some of my contacts use Signal to send me pictures of their lives. i want to store them permanently rather than in Signal. Currently I have to tap each picture individually, then the save button, then answer a question, the tap back, rinse and repeat. I would like to propose a more efficient way for this scenario. Different options could be considered:

a) extend the "all images" view to allow selecting and storing all pictures at once. 
b) an option to automatically store all incoming pictures in a folder on the sd-card.
I'm sure other options might be perceivable. Thanks for your consideration.

**Comment by agrajaghh** [comment]
should be in 3.12.0

see #3975
