### ISSUE TITLE
Faroese phone numbers

### ISSUE THREAD

**Issue by boginw** [WhisperSystems/Signal-Android#5291]
Phone numbers from the Faroe Islands have length of 6 digits. The land-code is +298.
If I enter my number into the app, f.x +298 123456, the app will return the connectivityFailureLayout. However, if I type my number with a zero at the end (+298 1234560) it will work. This is not pratical, as all my contacts will not be able to contact me encrypted, because I always will reply with my normal number, and not the one with a zero at the end.

I'm searching around in the source code, and when debugging the application, I find that the problem is maybe not in the app itself, but in the online service.

Here's one log from the app:
Opening URL: https://textsecure-service.whispersystems.org/v1/accounts/sms/code/+298123456

And then the app receives a warning:

org.whispersystems.textsecure.api.push.exceptions.NonSuccessfulResponseCodeException: Bad response: 400 Bad Request

And if add a zero to the end, the 400 Bad Request error goes away.

I suspect you have a minimum requirement for at least 7 digits to be typed, but could you edit that to 6?

**Comment by riyapenn** [comment]
Related: https://github.com/WhisperSystems/Signal-Android/issues/4549

**Comment by 2-4601** [comment]
This issue is now aggregated to #6027.
