### ISSUE TITLE
Lacking "delivered" message info

### ISSUE THREAD

**Issue by benboggart** [WhisperSystems/Signal-Android#5292]
I have a few contacts who have issues with delayed messages. (I'm aware of the multiple threads on the topic.)
However, especially with those contacts, the extended info "send time" and "delivered time" per message were very helpful. (The wording might be different; I use the German version.) They were only displayed for sent messages, not for recieved, and I was rather looking forward to get them on both.

Anyhow, now I don't even get the "delivered" info for sent messages anymore. Is this a server issue/feature/bug? Because I do not recall a Signal update since it still worked. 

Thanks and regards,
Ben

I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

Android 4.2.2
Signal 3.9.1

**Comment by 2-4601** [comment]
Received messages have dates for **Sent** and **Received**
Sent messages have only date for **Sent**

That's how it's been for as long as I have used the app and there has not been any recent changes to that.

**Comment by scienmind** [comment]
Probably duplicate of #1692 , #2055 . 

As those issues are open - it is an acknowledged issue. 
Hopefully will be implemented one day (and contributions are welcomed)...

**Comment by 2-4601** [comment]
OP said that sent messages had both dates displayed before but not any more. That seems to be impossible unless I'm misunderstanding something here.

**Comment by benboggart** [comment]
@2-4601 You are absolutely right! I'm sorry; apparently, my memory of what info was available for **sent** and **received** messages was totally messed up.

And @scienmind, thanks for links. It's good to see that this acknowledged as an issue.
