### ISSUE TITLE
Force SMS for specific user?

### ISSUE THREAD

**Issue by mseddon** [WhisperSystems/Signal-Android#5293]
A friend of mine has stopped using signal without deregistering.  Unfortunately that means every time I attempt to send them a message, I have to remember to manually move from "Signal" to "Insecure SMS" messaging for them to get my messages at all.  Is there a way that I can override this setting for that number specifically?

**Comment by riyapenn** [comment]
Best thing is to ask your contact to unregister: https://whispersystems.org/textsecure/unregister/

**Comment by mseddon** [comment]
Would it not be possible to add a feature where one sets the default until the contact sends a new signal message?

**Comment by mseddon** [comment]
The reason I'm suggesting this is now I have to make *them* do something to solve *my* problem, which doesn't  seem to be the right solution at all!

**Comment by TxHawks** [comment]
+1 on this.

One should not be dependant on someone else's behavior.

**Comment by agrajaghh** [comment]
@TxHawks Unfortunately bumping or +1's don't help fixing this issue (they just create extra email notifications for the devs).

https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues

**Comment by jnns** [comment]
Please consider reopening this issue as there's another reason for permanently chosing the method of transportation: 

In case my contact disabled mobile data for a prolongued time (roaming for example), I have to manually switch to sending them an SMS instead of a Signal message every time I reopen the conversation window. This is very cumbersome and most of the time I forget to do this in the first place and only notice it because no answer is received.

**Comment by 2-4601** [comment]
> This is very cumbersome and most of the time I forget to do this

Now imagine the opposite. Someone could also **forget** to switch back to Signal transport and consequently find themselves in a situation where they have sent multiple unencrypted messages unintentionally.

> reason for permanently chosing the method of transportation

There's already an issue for this #2285. But please only comment on it if you have relevant new information to add (see the remark two comments above).

**Comment by ArmEagle** [comment]
Good point 2-4601. But wouldn't it be better to detect on the receiving end that an insecure message was received, while data (and secure connection to the system) is available? People give valid reasons why temporary insecure messages are wanted. And this seems like a good detection to me.

**Comment by signaldefaultmessage** [comment]
Many of my contacts have got new phones and not installed signal yet, many many messages have never been delivered. Worst is when I get an sms from them and quickly reply it sends as encrypted so they think I've just ignored it. Had some pretty important business stuff lost over this.

When I tell them why they get angry at signal and are less likely to reinstall on their new phone.

Needs a simple option of "set default behavoir for this contact to unsecured"

**Comment by z1chickentender** [comment]
As many others have stated here and elsewhere, this issue has caused a number of users I know to simply stop using Signal. I've given up asking them to deregister - many just don't care any longer so now it is a problem for me and me only that is not solvable currently. I am frankly on the verge of deregistering myself - at first it was just an occasional nuisance but it's become a genuine time waste cumulatively.
