### ISSUE TITLE
Taking a picture with the camera under attachments results in blank message

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/Signal-Android#5295]
When I try to send a picture taken with "camera" under attachments in Signal nothing is actually sent. Everything is the same as it should, except when I try to send the picture the message is blank. Adding a message to the picture only sends the picture. This only started happening this morning when I installed the latest beta.

1. Open a chat
2. Click attachment icon
3. Click camera
4. Take a picture
5. Accept picture
6. Send the picture
7. Blank message

Moto G (2015)
Android 6.0.0
Signal is the last beta

https://gist.github.com/anonymous/aec4ccbbf8c887ab2b0e
https://gist.github.com/anonymous/212ba2b19eba908789a1

**Comment by 2-4601** [comment]
Can reproduce this with

- Nexus 4, stock 5.1.1, 3.13.0
- Huawei U8800, 4.0.4, 3.13.0

**Comment by moxie0** [comment]
Pretty sure this bug is assigned to @unrulygnu

**Comment by peterpanondrugs** [comment]
dito: https://gist.github.com/9ed23c4f7182c83e89ff

**Comment by unrulygnu** [comment]
I will have a fix today. Thanks for the report, and sorry for the regression!
