### ISSUE TITLE
Writing at least 1 letter and then going back makes the message line "jump" down/up

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/Signal-Android#5297]
1. Open a chat
2. Write "A"
3. Remove "A"
4. The background "Send Signal..." message will go down in the message bar. Trust me, you will see what I mean.

Easily reproducable on Moto G (2015)

**Comment by 2-4601** [comment]
Can't reproduce on Nexus 4, stock 5.1.1, Signal 3.13.0
What keyboard are you using?

**Comment by ryaeng** [comment]
Can't reproduce. 

Note II (SCH-I605), stock 4.4.2
Signal 13.12.0

**Comment by Dyras** [comment]
This only seems to happen on the Swedish translation, because the Swedish translation is now too long to appear at once. If you want to try it out, try the "Svenska" translation.
![2016-02-28 12 07 12](https://cloud.githubusercontent.com/assets/12563436/13378899/fff6fd62-de15-11e5-8313-311ca452be6b.png)
![2016-02-28 12 07 20](https://cloud.githubusercontent.com/assets/12563436/13378900/0535d96a-de16-11e5-8b4f-8126cb3ec041.png)

**Comment by 2-4601** [comment]
Thanks, I can reproduce this now on my Nexus 4. I used Greek, it's even longer than Swedish.

**Comment by 2-4601** [comment]
Related #4645

**Comment by moxie0** [comment]
Had a feeling this might happen. I'm just going to revert #5275 unless someone has a better fix.
