### ISSUE TITLE
NPE: answering or rejecting an incoming call crashes (ICS)

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/Signal-Android#5298]
I have:
- [x] searched open and closed issues for duplicates (there are so many :cold_sweat:)
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
All incoming Signal calls to my ICS device crash (**edit: when the device is in silent or in vibration mode**). Doesn't matter if I reject them or answer them, Signal always crashes. After the crash I see a call notification in the system status bar that's stuck and doesn't go away unless I make a new Signal call to someone.
~~No idea when this crashing has started. Last time I tried calls with this device was 3.4 or 3.5 or somewhere around there...~~
**edit: 3.9.1 does not crash, in 3.10.0 the crashing appears the first time**

### Steps to reproduce
1. Place a Signal call to my ICS device
1. Answer or reject the call on the ICS device
1. ICS device's Signal crashes

### Device info
Huawei U8800, Android 4.0.4, since Signal 3.10.0

### Debug log
https://gist.github.com/anonymous/5f2ea45724d47f4104ac

**When answering:**
```
E/AndroidRuntime( 9118): FATAL EXCEPTION: Thread-556
E/AndroidRuntime( 9118): java.lang.NullPointerException
E/AndroidRuntime( 9118): 	at org.thoughtcrime.redphone.audio.IncomingRinger.stop(IncomingRinger.java:113)
E/AndroidRuntime( 9118): 	at org.thoughtcrime.redphone.RedPhoneService.handleAnswerCall(RedPhoneService.java:253)
E/AndroidRuntime( 9118): 	at org.thoughtcrime.redphone.RedPhoneService.onIntentReceived(RedPhoneService.java:148)
E/AndroidRuntime( 9118): 	at org.thoughtcrime.redphone.RedPhoneService.access$200(RedPhoneService.java:77)
E/AndroidRuntime( 9118): 	at org.thoughtcrime.redphone.RedPhoneService$IntentRunnable.run(RedPhoneService.java:525)
E/AndroidRuntime( 9118): 	at java.lang.Thread.run(Thread.java:856)
```
**When rejecting:**
```
E/AndroidRuntime( 9519): FATAL EXCEPTION: Thread-582
E/AndroidRuntime( 9519): java.lang.NullPointerException
E/AndroidRuntime( 9519): 	at org.thoughtcrime.redphone.audio.IncomingRinger.stop(IncomingRinger.java:113)
E/AndroidRuntime( 9519): 	at org.thoughtcrime.redphone.RedPhoneService.handleDenyCall(RedPhoneService.java:262)
E/AndroidRuntime( 9519): 	at org.thoughtcrime.redphone.RedPhoneService.onIntentReceived(RedPhoneService.java:149)
E/AndroidRuntime( 9519): 	at org.thoughtcrime.redphone.RedPhoneService.access$200(RedPhoneService.java:77)
E/AndroidRuntime( 9519): 	at org.thoughtcrime.redphone.RedPhoneService$IntentRunnable.run(RedPhoneService.java:525)
E/AndroidRuntime( 9519): 	at java.lang.Thread.run(Thread.java:856)
```

**Comment by agrajaghh** [comment]
introduced by #4987? cc @haffenloher

**Comment by 2-4601** [comment]
Just noticed that if the phone is in silent mode or in vibration mode it crashes
But if it has sounds on, then there is **no crash**

**Comment by 2-4601** [comment]
Tested with old builds. I think @agrajaghh is right:
- 3.9.1 does not crash
- 3.10.0 crashes

**Comment by agrajaghh** [comment]
why isn't there any `Stopping ringer` log entry? should have been called before `player.release()` or do I miss something?

**Comment by haffenloher** [comment]
Wow, this shouldn't happen. Looks like we have to wrap `player.release()` in another null check? :confused: 
Or we could follow this advice:

> just remove a call to stop() before release(). We have tried it in a couple of our games and no side effects were found, so it seems rather safe on everything with 2.3+ (we do not target lower releases).

(from https://code.google.com/p/android/issues/detail?id=63345#c4)

> why isn't there any `Stopping ringer` log entry?

For some reason `Log.d()` was used here, so the log entry will only be visible when running a debug build.
