### ISSUE TITLE
Warning:Module 'com.github.afollestad:material-dialogs:0.7.9.1' depends on one or more Android Libraries but is a jar

### ISSUE THREAD

**Issue by chethan1333** [WhisperSystems/Signal-Android#5302]
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"
    defaultConfig {
        applicationId "com.gabriel.workoutrecipes"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.android.support:design:23.0.1'
    compile 'com.github.rey5137:material:1.2.2'
    compile('com.mikepenz:materialdrawer:4.6.1@aar')
    compile('com.github.afollestad:material-dialogs:0.7.9.1@aar'){
        transitive = true
    }
    repositories {
        jcenter()
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url "https://jitpack.io" }
        maven { url 'https://dl.bintray.com/drummer-aidan/maven' }
    }
    compile 'com.github.afollestad:material-dialogs:0.7.9.1'
    compile 'se.emilsjolander:StickyScrollViewItems:1.1.0'
    compile 'com.melnykov:floatingactionbutton:1.3.0'
    compile 'com.android.support:cardview-v7:23.0.0'
    compile 'com.android.support:recyclerview-v7:23.0.0'
    compile 'com.etsy.android.grid:library:1.0.5'
    compile 'com.google.android.gms:play-services-ads:8.4.0'
    compile 'com.google.android.gms:play-services-analytics:8.4.0'
}

**Comment by agrajaghh** [comment]
I'm not sure what you are trying to build there, but thats definitely not Signal...

**Comment by chethan1333** [comment]
Model:app
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"
    defaultConfig {
        applicationId "com.gabriel.workoutrecipes"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:23.2.0'
    compile 'com.android.support:design:23.2.0'
    compile 'com.github.rey5137:material:1.2.2'
    compile('com.mikepenz:materialdrawer:4.6.1@aar')
    compile 'se.emilsjolander:StickyScrollViewItems:1.1.0'
    compile 'com.melnykov:floatingactionbutton:1.3.0'
    compile 'com.android.support:cardview-v7:23.2.0'
    compile 'com.android.support:recyclerview-v7:23.2.0'
    compile 'com.etsy.android.grid:library:1.0.5'
    compile 'com.google.android.gms:play-services-ads:8.4.0'
    compile 'com.google.android.gms:play-services-analytics:8.4.0'
    compile ('com.github.afollestad:material-dialogs:0.7.9.1'){
        transitive = true
    }
}

Error ---------------Warning:Module 'com.github.afollestad:material-dialogs:0.7.9.1' depends on one or more Android Libraries but is a jar

**Comment by chethan1333** [comment]
Build.Gradle Project

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        maven { url "https://jitpack.io" }
        jcenter()
    }
}

**Comment by agrajaghh** [comment]
WTF?
