### ISSUE TITLE
Incoming message has country prefix from wrong country. 

### ISSUE THREAD

**Issue by mxa** [WhisperSystems/Signal-Android#5306]
I got a message that had a German prefix (+49) while it was almost certainly sent from Korea. I previously was using a German SIM card, but now use a Korean one.

**Comment by mxa** [comment]
Actually ALL my messages now have the +49 prefix while they are definitely not originating from Germany. Please fix this.

**Comment by moxie0** [comment]
Is your Signal number still registered as the German one?

**Comment by mxa** [comment]
Yes, but does it matter? I think it should not. I use both numbers regulary. Do i need to re-register every time I switch the SIM?

**Comment by moxie0** [comment]
Unfortunately, if a message arrives with no country code information, we have no other way of determining what country code you're in other than the number you gave us.  In the future the best place for support questions is support@whispersystems.org, thanks!
