### ISSUE TITLE
Cannot delete my own number in my contacts

### ISSUE THREAD

**Issue by Manouchehri** [WhisperSystems/Signal-Android#5307]
Steps to reproduce:

1. Register the number `123-456-7890` on phone # 1.
2. On phone # 2, add `123 456 7890` as a contact in Signal.
3. Transfer the number/SIM card on phone # 1 to phone # 2.

At this point, phone # 2 will have it's own number, `123 456 7890`, stuck at the top of Signal's contact list. Unlike the previous bug reports, unregistering the number is not an option as it *is* a valid Signal number. (But obviously I don't want to message my own phone.)

I've reset the session, removed and unlinked `123 456 7890` from my contact list with no luck.

Related: #682, #4678, #274, #439

**Comment by riyapenn** [comment]
Contact support@whispersystems.org.
