### ISSUE TITLE
Received same message with same timestamp ~13 hours later

### ISSUE THREAD

**Issue by Viperized** [WhisperSystems/Signal-Android#5309]
I have:
- [x ] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description

I have received a message from a contact yesterday night. Later on, I sent a few messages, all of which were not received yet to this contact (just one tick mark).

Today, after almost 13 hours after the last contact's message, I've received the same exact message again from the contact, with the same yesterday timestamp, even though between those two repeated messages I can see my messages with later timestamps. Seems a server-side issue since the contact is still offline.

### Steps to reproduce

Sorry this is the first time it happens and seems random enough to reproduce. Will update this issue if it happens again.

### Device info

 **Model:** Huawei Nexus 6P

 **Android version:** 6.0.1

 **Signal version:** 3.12.0

### Link to debug log
https://gist.github.com/88bb76d3c64855d3740c

**Comment by Dyras** [comment]
This happened for me on my Moto G (2015), also with Signal 3.12.0. Never happened before 3.12.0 either.

**Comment by moxie0** [comment]
If you received the same message twice, it means the other client sent it twice.  Cryptography ensures that there's no way to receive a replayed/duplicate message.

**Comment by Dyras** [comment]
@moxie0 Uh yeah, I checked my friend's phone afterwards and she only sent the message ONCE so... But hey, you're the boss!

**Comment by moxie0** [comment]
The device sent it twice, not your friend. She was probably in an area with bad service, didn't get the ack from the first send attempt even though it went through, scheduled a re-send which got queued until there was service, at which point you get the message again.
