### ISSUE TITLE
Chat history search

### ISSUE THREAD

**Issue by kofalt** [WhisperSystems/Signal-Android#5312]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
I have Signal conversations that have been going on for weeks and months - it's an inevitability that I'll want to find something in the history. These usually end in frustrating infinite-scroll re-read.

It would be great to have a search feature that can list matches, which when clicked would send you to that scroll position or similar.

Apologies if this is a dupe. As you can imagine, searching for this was difficult.

### Steps to reproduce
- Converse with a contact or group for several weeks
- Try to find something important in the chat history

### Device info
**Model:** HTC One M8
**Android version:** 4.x
**Signal version:** 3.12.0

**Comment by 2-4601** [comment]
GitHub issue search leaves a lot to be desired :)
This is tracked at #1232
