### ISSUE TITLE
Possible bug in send() in RtpAudioSender.cpp

### ISSUE THREAD

**Issue by cosmomill** [WhisperSystems/Signal-Android#5317]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
I tried to get Signal working on BlackBerry's Runtime for Android.
Sadly voice calls only partially working. I can call other Signal users but they can't hear my voice. I'm getting a lot of `sendto() failed!` errors in `/dev/log/main`. After some further debugging I found that
[`sendto()`](https://github.com/WhisperSystems/Signal-Android/blob/432e229698c585edbbc9f76f539a623540d04e80/jni/redphone/RtpAudioSender.cpp#L36) always fails with error 22 (EINVAL - invalid argument). As far as I understand the code the socket is already connected in [RtpSocket.java](https://github.com/WhisperSystems/Signal-Android/blob/432e229698c585edbbc9f76f539a623540d04e80/src/org/thoughtcrime/redphone/network/RtpSocket.java#L50) so a `send()` should be enough in [RtpAudioSender.cpp](https://github.com/WhisperSystems/Signal-Android/blob/432e229698c585edbbc9f76f539a623540d04e80/jni/redphone/RtpAudioSender.cpp#L36). I changed `sendto()` to `send()` and got voice calls working. I'm not sure if this is a BlackBerry specific issue cause it works with `sendto()` on pretty any Android device.

### Steps to reproduce
- Install Signal on a  BlackBerry
 - Install Cobalt's Google Apps follow the instructions on [Cobalt's official Google Apps landing page](http://forums.crackberry.com/android-apps-amazon-store-apk-files-f413/cobalts-official-google-apps-landing-page-965257/).
 - You need to install Google Account Manager, Blackberry Google ID and Google Play services the Google Play store itself is not needed.
 - Patch and install Signal follow the instructions on [How to patch Android Apps depending on Google Maps and Google Play Services](http://forums.crackberry.com/android-apps-amazon-store-apk-files-f413/how-patch-android-apps-depending-google-maps-google-play-services-914930/).
- Call a another Signal user.

### Device info
 **Model:** BlackBerry Passport OS v10.3.2.2836

 **Android version:** 4.3.0

 **Signal version:** 3.13.0

**Comment by moxie0** [comment]
Thanks but BlackBerry isn't supported.  Please don't post BB-related bugs here, thanks.

**Comment by josephtindle1986** [comment]
Okay, and I hope it works because I deleted my first data and I don't remember how it was done.﻿<a href="http://serialkeygeneratorfree.com/how-to-hack-whatsapp-account-free-download/">How To Hack Whatsapp Account</a>
