### ISSUE TITLE
No way to send plaintext SMS to Signal user from within Signal

### ISSUE THREAD

**Issue by untitaker** [WhisperSystems/Signal-Android#5319]
Signal "forcibly" upgrades my conversations. This seems to be intentional, so I totally understand if you close the issue on this basis.

I need this functionality because I don't have a data plan. This might seem weird to you, but in my case I just don't need one, generally.

I'm currently working around this by using the default Messaging app, but I wish I didn't have to.

**Comment by untitaker** [comment]
Just noticed there is an issue template. I didn't notice before because the mobile client I'm using doesn't support it. I still hope the report is clear.

**Comment by agrajaghh** [comment]
you can long press the send button to switch to unencrypted SMS

btw, the issue template is displayed for me on the mobile webpage...

**Comment by untitaker** [comment]
Ahh, sorry for the noise. I'm using OctoDroid.

**Comment by mderazon** [comment]
> you can long press the send button to switch to unencrypted SMS

This is great and I had no idea about it, I think it's very hidden this way
