### ISSUE TITLE
Signal forces 'so and so is on signal, say hey' messages over and over again after titanium backup restore

### ISSUE THREAD

**Issue by Viss** [WhisperSystems/Signal-Android#5322]
### Bug description
I've had to reinstall my phone (oneplus2), and I've used titanium backup to conduct that operation. Once the phone was operational again, I restored my apps (including signal) using titanium. Upon reinstallation, signal sent me 200+ 'so and so is on signal' messages, as one would expect to receive when someone joins - except this was for everyone in my phonebook that has signal installed. 

When I mark the messages read, it pushes them down to me again so that they are 'new'. When I try to delete them, it pushes them to me again. The only thing i can do is sit here with several hundred new, unread messages. 

I've attempted to uninstall and completely delete all traces of signal from my phone, as well as removing the desktop application to 'start from scratch', but nothing I do seems to tell the server side that it should stop sending me this tidalwave of welcome messages.

### Steps to reproduce
- install signal
- send a few messages
- make a backup of signal using titanium backup
- format phone / factory reset
- re-root, install old rom (i'm using stock oneplus2 roms)
- install titanium backup
- restore apps, or even just signal by itself
- resulting scenario is signal re-pushing welcome messages to you forever.

### Device info
Rooted OnePlus2, on newest stock oxygenOS
Rooted, with twrp and supersu
signal version newest from google play store as of 3/6/2015 (3.12.0)
android version 5.1.1
osxygenOS version 2.2.0

#Debug log
https://gist.github.com/anonymous/ed19ae2bcd519833fd57

**Comment by mawed** [comment]
This message is generated on your device and not server-side.
You can deactivate them via Settings->Notifications->New Contact Notification (on the bottom).

Additionally there is no support for using titanium backup, which generated this problem propably.
So please clsoe this ticket

**Comment by agrajaghh** [comment]
@mawed is right. If you got further questions you can go to the unofficial community forum at https://whispersystems.discoursehosting.net

**Comment by squarewave24** [comment]
why anyone thought it was a good idea to set this as default is beyond me.

**Comment by alan-signal** [comment]
@squarewave24 This is a very old resolved issue. Are you saying by your comment that is has resurfaced for you? Please ideally, open a new issue. But at least provide more details.
