### ISSUE TITLE
Can't receive messages

### ISSUE THREAD

**Issue by rebizant** [WhisperSystems/Signal-Android#5324]
Not all messages are displayed by Signal. I have also problem with secured messages. Application is not notyfing about new message if is runned in the background. When I open an app all messages and notification are displayed in a batch

I saw a classcastexception in the log, maybe this will help

https://gist.github.com/anonymous/8cef34d78a52fff505fe

**Comment by riyapenn** [comment]
Check the steps here: http://support.whispersystems.org/hc/en-us/articles/213190487-Why-is-there-a-delay-in-receiving-messages-, especially steps 4&8. Contact support@whispersystems.org
