### ISSUE TITLE
[Feature Request]  Internal "secure" popup keyboard.

### ISSUE THREAD

**Issue by olokoo** [WhisperSystems/Signal-Android#5329]
Hi All,

I was thinking that it would be cool to have a popup keyboard that opens in the app only. This would not be a keyboard app for android, really just a series of buttons that are displayed in the app that would allow the user to type "seriously secure content" without being tracked.

I know that we could find a keyboard that "doesn't track anything" but it seems much more secure to have a internal keyboard that isn't a keyboard at all. Even if they say they don't track, you can't really be sure, plus, for most of my other activities, I enjoy the auto-correct and predictiveness of Google. Even most of my messages, I don't really have an issue with Google storing the data they store. But if I did want to send something I was worried about Google seeing, having a quick button I could click to open up a keyboard to enter a quick message would be amazing.

Websites have done this for years, typically older government sites. They would have a little popup keyboard that you would use your mouse to select they keys to ensure a keylogger wasn't recording your social security number.

Seems like a good idea to me, what do you think?

I have:
- [ x] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

**Comment by moxie0** [comment]
thanks but we're not going to do this
