### ISSUE TITLE
Installing on Grandstream - GXV3240

### ISSUE THREAD

**Issue by theochino** [WhisperSystems/Signal-Android#5330]
Hello,

I am trying to install the software on the Grandstream - GXV3240 android type desktop phone.
Any luck in making the installer available to every device ?

Regards,
Theo Chino

I have:
- [X ] searched open and closed issues for duplicates
- [ ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Steps to reproduce
- add your steps here
- as a list
- using hyphens

### Device info

 **Model:** Manufacturer Model XVI
GXV3240
![img_0069](https://cloud.githubusercontent.com/assets/5959961/13724761/6e1abd0a-e85d-11e5-976c-3499b875a0ab.JPG)

 **Android version:** 0.0.0

 **Signal version:** 0.0.0

### Link to debug log

![Uploading IMG_0069.JPG…]()

**Comment by 2-4601** [comment]
I guess that device does not have SIM (wifi only) and that's why it's not available through Play Store.
If you want further help, please post at the community forum https://whispersystems.discoursehosting.net/
