### ISSUE TITLE
Regression: "LinearAlloc exceeded capacity" when installing on older device

### ISSUE THREAD

**Issue by ra--** [WhisperSystems/Signal-Android#5333]
When trying to upgrade from an ancient version of TextSecure, I encountered that Signal could not be upgraded/installed.

Device:
Samsung Galaxy Ace (GT-S5830)
Stock Android 2.3.5
Google Play services 8.4.89

logcat shows the following error:
E/dalvikvm(  926): LinearAlloc exceeded capacity (5242880), last=160
E/dalvikvm(  926): VM aborting

Signal versions 187, 186, and 185 show the error above. Since version 181 works fine, I assume that this is some kind of regression introduced between version 182 and 185.

**Comment by 2-4601** [comment]
8c8cd413597d5b6da105f759eaa5d4744f55fada should fix this. See https://github.com/WhisperSystems/Signal-Android/pull/5325#issuecomment-195637629
