### ISSUE TITLE
feature suggestion : direct p2p calls and file transmission

### ISSUE THREAD

**Issue by edo0** [WhisperSystems/Signal-Android#5334]
I have:
- [X] searched open and closed issues for duplicates

What about implementing in (distant) future versions p2p-like capabilities when it comes to phone calls, with the central server working as a simple switchboard operator? That would be even more secure and would save bandwidth as well as open possibilities to higher quality calls.

The same could work with pictures/audios/videos, with the server taking them on board only if the other party isn't online.

**Comment by moxie0** [comment]
thanks but we're not going to do this

**Comment by 2-4601** [comment]
@edo0 in the future it's best to open discussions such as this at the [community forum](https://whispersystems.discoursehosting.net) which is better suited for this kind of general, non-bug related topic
