### ISSUE TITLE
Chat scrolls when new messages are received

### ISSUE THREAD

**Issue by vrabac** [WhisperSystems/Signal-Android#5335]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
Chat scrolls when new messages are received and you can't catch them to read, and if you get new messages, you will be immediately thrown to that last message and need to scroll up again to see old ones, and so on.

### Steps to reproduce
- chat with someone, or in group (this is even worse, because if members in group are active you will not be able to read old messages), try to read old message and let someone write you something while you reading old messages.

### Device info
 **Model:** Nexus 5 and BQ M5

 **Android version (both):** 5.1.1

 **Signal version:** 3.13.1

### Releted to:
[#1211](https://github.com/WhisperSystems/Signal-Android/issues/1211) which is locked and 2 years old.
[#3955](https://github.com/WhisperSystems/Signal-Android/issues/3955) which is 8 Months old

**Comment by 2-4601** [comment]
This is effectively same as #1211. That issue is still open so it's valid. I guess it was locked because someone asked for an update :D https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#dont-bump-issues

**Comment by Schweineschwarte** [comment]
@2-4601
I want to ask, why these feature does not implement, respectively has no high importance? Of cause, signal is a free app and individual wishes are inopportune, but the first report is from 21 Mar 2014 (2 years ago) and many other people ask about these feature, too.

**Comment by 2-4601** [comment]
@Schweineschwarte The developers wish to use this issue tracker just for bugs, not for questions or discussions. Please see: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#not-a-discussion-forum
