### ISSUE TITLE
Optional periodic check for new messages (when push isn't working reliably)

### ISSUE THREAD

**Issue by seanlano** [WhisperSystems/Signal-Android#5336]
I have:
- [x] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
Signal should fall back to periodic update checks when GCM Push doesn't work

### Steps to reproduce
- Tried installing Signal on a Motorola RAZR M, with Android 4.4.2
- I have a friend with the same model, who also has the same issue with Signal
- I have followed all the steps here: http://support.whispersystems.org/hc/en-us/articles/213190487-Why-is-there-a-delay-in-receiving-messages-
  - The RAZR M does not have any options for "Phone specific optimisation" 
- When the screen is off, push notifications do not work for Signal messages (but do work for SMS)
- Only when the screen is unlocked, and the Signal app is opened, new message notifications arrive

### Expected behaviour
- There should be a manual option to perform the same routine as opening the app to check for new messages at a defined interval, say every 10 minutes. Messages do arrive, but only when the app is opened. 
- To stop impact to other users for whom GCM Push works properly, this setting should be off by default
- This would mean that Signal messages are at least delivered eventually, rather than only when opening the app and manually refreshing

### Device info
 **Model:** Motorola RAZR M

 **Android version:** 4.4.2

 **Signal version:** 3.13.1

**Comment by moxie0** [comment]
Thanks but I think you should look into why push messages aren't working for your device. If you're looking for help with that, please contact support.
