### ISSUE TITLE
App reading SMS when Signal is locked

### ISSUE THREAD

**Issue by ephexeve** [WhisperSystems/Signal-Android#5340]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
I am not sure if this is a vulnerability, if it's a bug or a "feature". When using Signal as a default SMS app and enable the locked option, as far as I know, no one should be able to access any received message. However, if you have any two factor-authentication enable on Google (using Google as an example) and try to login to your Google account, you will receive an SMS and Google will automatically read the SMS and authenticate you, without any need of manually having to unlock Signal, copy the authentication code and paste it to Google's prompt.

This should probably work with any app that will automatically read any SMS received to authenticate any 2 second-authentication code. 

This concerns me, because if I have any type of malware listening to my SMS app, it will be able to read any message I receive without worrying if Signal is locked or not. 

### Steps to reproduce
- Remove your Google account from your Android settings.
- Make sure Signal is locked and is your default SMS app.
- Login to your Google Account.
- Wait for the SMS.
- Google will automatically authenticate you.

### Device info
Samsung Galaxy S5 running Cyanogen lastest nightly build of KLTE.
** Signal Version: 3.13.1

**Comment by moxie0** [comment]
Any app that has SMS permission can read incoming SMS messages.  If you upgrade to N, you can selectively disable that permission for other apps.
