### ISSUE TITLE
Missing icon for "Lock with passphrase"

### ISSUE THREAD

**Issue by haffenloher** [WhisperSystems/Signal-Android#5342]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description

On current master, the lock notification is missing an icon on my hdpi device.
Related: #5325 / cc @passy

### Screenshots
![screenshot_2016-03-15-15-57-10](https://cloud.githubusercontent.com/assets/264472/13782641/39c631d4-eac8-11e5-83b0-bfa0bbeb6b04.png)

### Device info
 **Android version:** 4.2.2

 **Signal version:** 3.14.1

### Link to debug log

https://gist.github.com/anonymous/d6f1f9be41b0c1e9ab56

**Comment by agrajaghh** [comment]
damn, didn't test it on the 4.4 emulator... What color was it before? white as well?

its currently 54% black, I guess thats pretty bad with a black background :smirk:

**Comment by passy** [comment]
I've just tried it on my Marshmallow device reducing the density to 240 and it still appears, so it must be the background color. So do we need to provide white versions for earlier verisons?

**Comment by passy** [comment]
So I've just tried all notification action icons converted to white and the display on Marshmallow is still the expected one. I guess on newer platforms the color is automatically normalized and 54% black is the actual display rather than the recommended format for the icons?

**Comment by agrajaghh** [comment]
yeah, just make ic_menu_lock_dark 100% white

**Comment by passy** [comment]
Okay, I'm on it.
