### ISSUE TITLE
Cryptic failure toast when USERTRUST cert disabled

### ISSUE THREAD

**Issue by RamKromberg** [WhisperSystems/Signal-Android#5346]
If the USERTRUST RSA ssl cert Signal uses is disabled in Settings -> Security -> Trusted Certificated, Signal correctly fails to register.
However, the message is a generic server connection failure... Technically correct, practically not very helpful.

To be honest, I recently disabled all the certs on my phone and started running apps one by one and approving only what needs approving. So far, not a single app did too well in these regards. A few even failed silently...

Regardless, even if it's not worth improving on, I figured I should at least put it out there just in case someone runs into some obscure but related issues. I also saw the last few commits touched some elliptic curve cipher related stuff so this might actually be useful one day ;)

**Comment by moxie0** [comment]
We don't use CA certs for anything. More likely you broke GCM's communication channel and are getting that error from play services.
