### ISSUE TITLE
Unable to receive or make calls

### ISSUE THREAD

**Issue by liphistius** [WhisperSystems/Signal-Android#5350]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
When attempting to establish a call Signal gets hung up on the dialling phase. Shortly afterwards it presents a "Network Failed!" message and occasionally crashes completely. It is still possible to send and receive messages.
- Google play services are installed and enabled
- Firewall is permissive for Signal and all Google services
- Previously tested on a custom Cyanogenmod by "MoKee"
    - Calls were received
    - Unable to make calls

### Steps to reproduce
- Call a person
- Dialling
- Network Failed and optional crash

### Device info
 **Model:** Xiaomi Redmi Note 2
 **Android version:** 5.1.1
 **Signal version:** 3.14.2

### Link to debug log
https://gist.github.com/ac96f2b7fa957211c8bc

**Comment by funkydude** [comment]
There's something wrong with the server, also getting connection refused log entries @moxie0

**Comment by jagajaga** [comment]
I have the same issue now.

**Comment by moxie0** [comment]
problem with a relay in europe, should be working now

**Comment by funkydude** [comment]
@moxie0 How about fail safes so this doesn't happen in future? If it was a relay in a specific location, why not fall back to a further location?
