### ISSUE TITLE
Network Failed

### ISSUE THREAD

**Issue by peterpanondrugs** [WhisperSystems/Signal-Android#5351]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
When calling a partner I get a "Network Failed" 
### Steps to reproduce
- call partner wait for crash

### Device info

 **Model:** Manufacturer Model XVI
Samsing S3 LTE GT-i9305
 **Android version:** 5.1.1

 **Signal version:** 3.14.2

### Link to debug log
https://gist.github.com/9008ba3048b5c79be8c3

**Comment by peterpanondrugs** [comment]
Related #5350

**Comment by funkydude** [comment]
> searched open and closed issues for duplicates

Do that prior to creating the ticket, not afterwards. ;)

**Comment by Dyras** [comment]
This also happened for me, I'm guessing the server is down. There you go kids, now you can all go back to sleep.

**Comment by peterpanondrugs** [comment]
It took me a little time to finall post. So...shht funkydude. Useless comment.
