### ISSUE TITLE
Repeatable builds

### ISSUE THREAD

**Issue by MariusVolkhart** [WhisperSystems/Signal-Android#5354]
I have:
- [x] searched open and closed issues for duplicates

## Description
My goal is to verify that the APK distributed on Google Play is executing the code at the commit of the release tag on GitHub. Even though I trust OWS to publish the untampered code, they could be compelled to alter it without revealing it, and it is better to know than to assume.

To do the verification, I'm looking at the hash of each file in the APK I get from Google Play and comparing it with the hash of the APK I built myself.

In `build.gradle` a timestamp is populated as a `BuildConfig` field at build time. This field has millisecond accuracy and is used to expire the binary after 90 days. Due to it changing during every build, `classes.dex` in the APK has a different hash, so it's impossible to verify the integrity of the code.

## Proposal
I'd like to submit a PR to:

1. change the timestamp to be granular only to the day (1458190800000ms).
2. be replaceable by an environment or system variable.

This would allow for easy APK verification. The signing date of the Play APK can be used to determine the build date which can then be replaced during a verification build. The timestamp can still be used to determine when 90 days have gone by and a build has expired.

## Risks
1. The risk of this feature regressing in the future is fairly high due to the external nature of the verification. This could be mitigated by a build step that performs the verification, or reduced through good commenting. The code I'm using for verification is available [here](https://github.com/MariusVolkhart/ApkCompare).

 **Signal version:** 3.14.1, and `master` at time of filing.

**Comment by moxie0** [comment]
Hey @MariusVolkhart we don't use GH as a discussion forum.  If you're asking whether we'd accept a PR as outlined above, we would not.  That isn't the only thing required for reproducibility, so we'd prefer to do it right rather than doing it half-way.
