### ISSUE TITLE
Can't verify SMS with a samsung galaxy grand prime

### ISSUE THREAD

**Issue by francogp** [WhisperSystems/Signal-Android#5363]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
Can't verify SMS with a samsung galaxy grand prime. The SMS arrives (I tested hangout, default SMS program and even signal itself as SMS admin), but signal time-out clock finish without verification success.

### Steps to reproduce
- start the program (ok), 
- wait SMS to arrive (ok), 
- wait to verify SMS (fail with timeout)
- "call me" does nothing

### Screenshots
SMS example:
http://img.photobucket.com/albums/v282/francopellegrini/2016-03-21%2018.13.57.png

### Device info
 **Model:** Samsung galaxy grand prime SM-G531M

 **Android version:** 5.1.1

 **Signal version:** 3.14.2

**Comment by agrajaghh** [comment]
did you try the call button? If this doesn't work `adb logcat` would be helpful

**Comment by francogp** [comment]
I press "call me" but nothing happens. I'm not root, so I can't see the logs using a program. Is there other way without being root?

**Comment by skulumani** [comment]
I don't think you need to be root to use the `adb` program.

http://developer.android.com/tools/help/adb.html

I'm pretty sure you just have to check the android debugging check box on the phone and run it from the terminal on a connected computer.

**Comment by agrajaghh** [comment]
> I'm pretty sure you just have to check the android debugging check box on the phone and run it from the terminal on a connected computer.

yep, you need the android sdk and connect the phone via usb to the computer

**Comment by francogp** [comment]
ok, I will try that when I return to home, thanks for the tips.

**Comment by francogp** [comment]
I update the op to avoid misleading

**Comment by francogp** [comment]
[logcat.txt](https://github.com/WhisperSystems/Signal-Android/files/183529/logcat.txt)
here the logcat while trying to call myself with the button.

**Comment by agrajaghh** [comment]
I sppoeded these two:

```
E/Parcel  ( 3079): Class not found when unmarshalling: org.thoughtcrime.securesms.crypto.MasterSecret
E/Parcel  ( 3079): java.lang.ClassNotFoundException: org.thoughtcrime.securesms.crypto.MasterSecret
E/Parcel  ( 3079): 	at java.lang.Class.classForName(Native Method)
E/Parcel  ( 3079): 	at java.lang.Class.forName(Class.java:309)
E/Parcel  ( 3079): 	at java.lang.Class.forName(Class.java:273)
E/Parcel  ( 3079): 	at android.os.Parcel.readParcelableCreator(Parcel.java:2281)
E/Parcel  ( 3079): 	at android.os.Parcel.readParcelable(Parcel.java:2245)
E/Parcel  ( 3079): 	at android.os.Parcel.readValue(Parcel.java:2152)
E/Parcel  ( 3079): 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
E/Parcel  ( 3079): 	at android.os.BaseBundle.unparcel(BaseBundle.java:221)
E/Parcel  ( 3079): 	at android.os.BaseBundle.getString(BaseBundle.java:918)
E/Parcel  ( 3079): 	at android.content.Intent.getStringExtra(Intent.java:5224)
E/Parcel  ( 3079): 	at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1490)
E/Parcel  ( 3079): 	at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1073)
E/Parcel  ( 3079): 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4438)
E/Parcel  ( 3079): 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4337)
E/Parcel  ( 3079): 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:144)
E/Parcel  ( 3079): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2898)
E/Parcel  ( 3079): 	at android.os.Binder.execTransact(Binder.java:461)
E/Parcel  ( 3079): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.thoughtcrime.securesms.crypto.MasterSecret" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/Parcel  ( 3079): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/Parcel  ( 3079): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/Parcel  ( 3079): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/Parcel  ( 3079): 	... 17 more
E/Parcel  ( 3079): 	Suppressed: java.lang.ClassNotFoundException: org.thoughtcrime.securesms.crypto.MasterSecret
E/Parcel  ( 3079): 		at java.lang.Class.classForName(Native Method)
E/Parcel  ( 3079): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/Parcel  ( 3079): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/Parcel  ( 3079): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/Parcel  ( 3079): 		... 18 more
E/Parcel  ( 3079): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

```
W/JobConsumer(15690): org.whispersystems.textsecure.api.push.exceptions.AuthorizationFailedException: Authorization failed!
W/JobConsumer(15690): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:511)
W/JobConsumer(15690): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.setCurrentSignedPreKey(PushServiceSocket.java:347)
W/JobConsumer(15690): 	at org.whispersystems.textsecure.api.TextSecureAccountManager.setSignedPreKey(TextSecureAccountManager.java:209)
W/JobConsumer(15690): 	at org.thoughtcrime.securesms.jobs.CreateSignedPreKeyJob.onRun(CreateSignedPreKeyJob.java:53)
W/JobConsumer(15690): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/JobConsumer(15690): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
W/JobConsumer(15690): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
```

maybe someone else got an idea?

**Comment by francogp** [comment]
> @francogp you might want to redact your phone number from that log
ups... fixed! thanks

**Comment by moxie0** [comment]
Are you running a custom ROM? There's something deeply wrong with your OS.

**Comment by francogp** [comment]
> Are you running a custom ROM? There's something deeply wrong with your OS.

No. Official samsung 5.1.1 stock andorid for SM-G531M

**Comment by moxie0** [comment]
Either your device is fucked up or you have some kind of disk corruption. If the classloader isn't finding the classes we ship, there's nothing we can do.  You might try reinstalling.

**Comment by francogp** [comment]
@moxie0 
I just try to reinstall it.. same problem. 

Note: And If I type a number on the verification textbox for "call me" button, I get an error saying that I'm not online, and must be connected online to achieve that (an that's not true, I'm on WIFI and 4G as an emergency ISP if wifi internet does not work)

**Comment by francogp** [comment]
I just tried with another phone (same model).... same problem

**Comment by 2-4601** [comment]
@francogp Do you have an Argentinian phone number? See #3490 (there are also other issues with Argentinian phone numbers)

**Comment by francogp** [comment]
@2-4601 yes, my number is from Argentina

**Comment by riyapenn** [comment]
In summary, for Argentina/Argentinian Numbers: Make sure there is a **total of 13 digits**. It will be  +549 (+ 10 digit number)
- [ ] +549
- [ ] (add the 2-4 digit city code)
- [ ] (remove prefix 15)
- [ ] (add 6-8 digit phone number)
- [ ] Total of 13 digits

Examples: 
national format 03312 15-34-5678 will be +5493312345678
national format 98812345678 will be +5498812345678

**Comment by francogp** [comment]
@riyapenn yes! now it works! the 9 is necessary to use the "call me" button (but SMS verification failed). Now I can loggin using the "call me" button verification :D

**Comment by francogp** [comment]
@riyapenn the problem now, is that all my contacts does not recognize me because of the 9. This program think that is not my number.

**Comment by francogp** [comment]
@moxie0 you should reopen this... the problem is your end, because of the 9. And the contacts can't "recognize" me because of that

**Comment by agrajaghh** [comment]
@francogp could you please open another issue regarding the number problematic in argentina? this one seems a bit off topic with the other device problems

**Comment by francogp** [comment]
@agrajaghh it's the same problem, because it's solve the OP adding a 9.

**Comment by agrajaghh** [comment]
the stacktraces you posted have nothing to do with it

**Comment by 2-4601** [comment]
There's an open issue for this: #1511

**Comment by agrajaghh** [comment]
pff, I searched but just found closed ones, shame on me

**Comment by unrulygnu** [comment]
>  If the classloader isn't finding the classes we ship, there's nothing we can do.

If further work is needed on preventing this or related `ClassNotFoundException`s (hi, Samsung), this might provide some ideas: 

https://stackoverflow.com/questions/28589509/android-e-parcel-class-not-found-when-unmarshalling-only-on-samsung-tab3
