### ISSUE TITLE
When your number exists in your contacts, you show up ain Signal and receive error messages

### ISSUE THREAD

**Issue by Fmstrat** [WhisperSystems/Signal-Android#5367]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
Hopefully this isn't a dup, many different ways this could have been identified.

I have a contact card on my phone that has my Google Voice number in it. When I go to compose a new message in Signal, that contact shows up in the list. This didn't seem to be an issue at first, but then I realized something was getting transmitted as when using Signal Desktop every message I get shows up under that contact as "Error handling incoming message".

### Steps to reproduce
- Create a contact on an Android phone named "Google Voice" with your phone number
- Install Signal
- Send a message to any contact
- Wait for a response
- Install Signal Desktop in Chrome on any machine
- Click on the "Google Voice" contact
- You will see "Error handling incoming message" displayed

### Screenshots

![capture](https://cloud.githubusercontent.com/assets/971474/13958215/b46217f2-f025-11e5-8c3f-fa02671b9e92.PNG)

### Device info

 **Model:** Samsung Galaxy Note 5

 **Android version:** 5.1

 **Signal version:** 3.14.2

**Comment by 2-4601** [comment]
I have my own number in contacts but I can't reproduce this.
And this looks more like an issue with Signal Desktop.
Please open an issue at https://github.com/WhisperSystems/Signal-Desktop/issues?utf8=%E2%9C%93&q=is%3Aissue+Error+handling+incoming+message with a debug log from all clients.
