### ISSUE TITLE
Message filter

### ISSUE THREAD

**Issue by fajabird** [WhisperSystems/Signal-Android#5369]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Feature Request

Most apps today offer a filter to narrow down the elements (=Messages) of  a list of elements (=Chat) to those matching the flter query. I'm using TS/Signal for many years now and my chats are constantly growing. Meanwhile it is nearly impossible to find Information within the chats manually by scrolling up/down (not heaving a scroll-handle like e.g. in the contacts-app makes this even worse). This is different from a search because a search will need more UI-changes (e.g. search next/prev buttons), a filter will only need a small text-box and will just narrow down the messages of the current chat-list. It would be great to jump into the unfiltered chat to the position of the selected message from the filtered list. 

### Device info

 **Model:** OnePlus One (Bacon)

 **Android version:** 6.0.1
 **Signal version:** 3.14.2

**Comment by agrajaghh** [comment]
Could you explain more what the difference to a search would be? I don't really see the benefit of adding both, so I'm thinking this is a duplicate..

**Comment by fajabird** [comment]
Oh - did I miss something - do we already have "search"? 

For me a search requests something to search and jumps to the position of the first occurence. In contrast a filter will just remove everything from your list that does not match the search pattern. In most apps today I see what I refer to as "filter" (e.g. contacts app).

**Comment by agrajaghh** [comment]
no, its not implemented yet. But there is a valid/open feature request at #1232

closing as duplicate

**Comment by fajabird** [comment]
Sorry - I was searching for the wrong terms, additionally this one is 2 years old making it even harder to find. Any time estimations?
