### ISSUE TITLE
receive only messages when the app is opened.

### ISSUE THREAD

**Issue by jedie** [WhisperSystems/Signal-Android#5370]
I have:
- [x] searched open and closed issues for duplicates
- [ ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description

Same as #4266 : I receive only messages when the app is opened.

### Steps to reproduce

It seems, that this always happens, after i update CyanogenMod via Recovery.

To fix this, i use the normal way: Simply disable and re-enable "Signal messages" in the advanced settings. Then GCM works.

Question: Is there no way to warn the user, like: "GCM is turn off, please re-enable Signal messages in the advanced settings" if he opens signal app.
or even better: Check GCM status on first start and auto-re-enable GCM if it's not working.

### Device info

 **Model:** Sony Xperia Z1

 **Android version:** CyanogenMod 12.1 nightly: android v5.1.1

 **Signal version:** 3.14.2

**Comment by moxie0** [comment]
There is no way for us to know that you reflashed your ROM from within the app.  Fuck with your phone, and fucked up things are going to happen to your phone.
