### ISSUE TITLE
Official support forum, where?!?

### ISSUE THREAD

**Issue by jedie** [WhisperSystems/Signal-Android#5372]
Creating new issue included this text:

> Please note this is a bug tracker, **not a support forum**. If you need support, please use
> http://support.whispersystems.org/
> or email support@whispersystems.org

But where is a official forum about signal?!?

**Comment by agrajaghh** [comment]
There is no official forum. There is just offical support at http://support.whispersystems.org and support@whispersystems.org

There is an UNOFFICAl community forum at https://whispersystems.discoursehosting.net

**Comment by jedie** [comment]
OK, then the Text should be IMHO changed, isn't it?

Why not add a link to https://whispersystems.discoursehosting.net/ until there is a official forum ?!?

**Comment by agrajaghh** [comment]
we also have:
https://github.com/WhisperSystems/Signal-Android/blob/master/README.md
https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md
https://github.com/WhisperSystems/Signal-Android/wiki

we can't put every information in the issue template
