### ISSUE TITLE
3.15 fails to build (missing file signal-service-android.aar?)

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/Signal-Android#5375]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
 Building Signal 3.15.0 fails.

### Steps to reproduce
- Get the source with git clone https://github.com/WhisperSystems/Signal-Android.git
- Open it in Android Studio
- Make

Result: I see this error:
```
Error:Could not download signal-service-android.aar (org.whispersystems:signal-service-android:2.1.1): No cached version available for offline mode
```
System: Windows 7 with Android Studio 1.5.1 (latest version when I write this)..

**Comment by agrajaghh** [comment]
you are in offline mode, so gradle can't download the new version.

go to setting ->  build -> build tools -> gradle and remove the checkmark

**Comment by johanw666** [comment]
Odd, I checked that before and the error remained. After a clear project, close project and reopening it it builds.
