### ISSUE TITLE
Regression: Displayed identity key format

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/Signal-Android#5376]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Hexadecimal numbers used for identity keys are displayed in the format "(byte)0xaa" for each byte since the latest beta.

### Steps to reproduce
- Contact preferences
- Verify identity

**Actual result:** Hex identity key bytes are displayed as "(byte)0xaa"
**Expected result:** Hex identity key bytes should be displayed in the format "aa"

### Screenshots

None

### Device info

**Device:** Google Nexus 5
**Android version:** 6.0.1
**Signal version:** 3.15.0

### Link to debug log

None

**Comment by agrajaghh** [comment]
![screenshot_2016-03-25-13-39-51](https://cloud.githubusercontent.com/assets/5296073/14044311/3b1ac990-f28f-11e5-9f09-1e555a6ad6f0.png)
