### ISSUE TITLE
In Call Notifications

### ISSUE THREAD

**Issue by zero77** [WhisperSystems/Signal-Android#5380]
Can you add a permanent message that appears in the middle of the screen when the call has been muted or is on hold. That notifies the user that the call has been muted or is on hold and tells them who put the call on mute or on hold for instance you or the other person in the call.

**Comment by moxie0** [comment]
Thanks but we're not going to do this.  There is no hold, and there's already a mute indicator on the audio transmit side.  Generally you don't want to communicate to the receiver that the call has been muted, and I don't know of any other calling system that does that.
