### ISSUE TITLE
Text cursor invisible in conversation list search (light theme only)

### ISSUE THREAD

**Issue by FeuRenard** [WhisperSystems/Signal-Android#5382]
### Bug description

No text cursor is visible when searching through the conversation list.
### Steps to reproduce
- Go to conversation list (light theme)
- tap the magnifier icon
- (optional) type something with the keyboard

**Actual result:** No cursor visible in input field.
**Expected result:** Blinking cursor is visible in input field.
### Device info

**Device:** Fairphone 2
**Android version:** 5.1.1
**Signal version:** 3.14.2
### Assignment

I am working on this issue.

**Comment by RiseT** [comment]
Btw, I think the cursor color in the contact list search (dark theme!)  is different from e. g. the one in conversation list search.

**Comment by FeuRenard** [comment]
This is going to be solved by #5412.

**Comment by FeuRenard** [comment]
This is fixed around here: 405ee3b741d0ff06473fc9a6f9a56b2809145c91 1cee253b41cf57b0702eecf105922855be58b02e
