### ISSUE TITLE
Feature Request - Default message type per contact

### ISSUE THREAD

**Issue by lenisko** [WhisperSystems/Signal-Android#5386]
An additional option for **default message type** (Signal, Insecure SMS) in **contact settings** would be really helpful. There are cases, when someone is using this app as main SMS application along with chat member but sometimes we don't want to use secure connection for specified amount of time (battery drain problems, roaming and other reasons).

**Comment by Dyras** [comment]
I think this is a duplicate

**Comment by 2-4601** [comment]
#2285
