### ISSUE TITLE
Record and send audio ("software walkie talkie") for using in bad connectivity conditions

### ISSUE THREAD

**Issue by drws** [WhisperSystems/Signal-Android#5391]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Enhancement description
There are many sharing options in Signal, including sending of images and videos taken from camera or audio files, recorded by another application, but there is no convenient way to send and receive (play in-app) audio recordings, recorded only with the microphone. This is a very useful feature in bad connectivity or harsh audio environments, where live audio call is not an option (a very notable case being a warzone or aftermath of a natural disaster). There are also many markets such as Spain where people use this function on a daily basis.

If the description is not evident enough, try to think of it as a "software walkie talkie", which allows the first Signal user to only press a button in the application (like "push-to-talk" button on a walkie talkie) and it starts recording the audio, which is then compressed with a suitable speech codec and sent via Signal to the receiving user. In this way the talk is not real-time, but it allows for disturbances in the connectivity between the two users and it also allows the second user to listen to the message repeatedly in case of loud audio environment on any side of the conversation.

----------------------------------------

ps: Maybe TextSecure-Server would be a better repository to post this enhancement to, but it doesn't seem too live, and I haven't been able to found the Signal-Server one... If it's necessary, I'll repost this elsewhere, just let me know where.

**Comment by 2-4601** [comment]
Thanks, this is already tracked at #3563, closing as duplicate
