### ISSUE TITLE
buggy comparison in apkdiff

### ISSUE THREAD

**Issue by h01ger** [WhisperSystems/Signal-Android#5404]
hw42@ipsumj.de found that https://github.com/WhisperSystems/Signal-Android/blob/master/apkdiff/apkdiff.py#L64 should be 'or' not 'and'. with 'and' an empty file is equal to everything.

(hw42 doesnt have a github account, so I commited this on his behalf.)

**Comment by h01ger** [comment]
hw42 added "if the files size of the shorter files is divisible by 1024 it compares only the content up to the length of the shorter file".

**Comment by 2-4601** [comment]
Tested by replacing AndroidManifest.xml with empty file

**Comment by h01ger** [comment]
thank you! :)
