### ISSUE TITLE
Can't build with older Android Support package

### ISSUE THREAD

**Issue by wcummings** [WhisperSystems/Signal-Android#5406]
The build instructions are out of date:

```
Could not find com.android.support:appcompat-v7:22.2.1. Required by: :Signal-Android:unspecified Please install the Android Support Repository from the Android SDK Manager.
```

The SDK manager doesn't provide a way to install old versions of Android Support

**Comment by riyapenn** [comment]
http://developer.android.com/tools/support-library/setup.html 
File > Settings > Plugins > search for Android Support and check it on

**Comment by 2-4601** [comment]
> The build instructions are out of date

I checked https://github.com/WhisperSystems/Signal-Android/blob/master/BUILDING.md and https://github.com/WhisperSystems/Signal-Android/wiki/How-to-build-Signal-from-the-sources
Neither of them instruct to use any specific version of the support library.
E.g. the wiki guide says:
```
# when you see "Could not find com.android.support:support-v" ...
# ... you have also forgotten to install the support library
```

I have the latest 23.2.1 and everything works fine.

**Comment by wcummings** [comment]
Seeing this when I invoke gradle from the command line:

```
                  > Could not GET 'https://raw.github.com/whispersystems/maven/master/shortcutbadger/releases/com/android/support/support-v4/'. Received status code 400 from server: Bad Request
      > Could not find com.android.support:appcompat-v7:22.2.1.
```

Could it be related?

**Comment by 2-4601** [comment]
This doesn't seem to be a bug in the docs or in the build scripts because several people have recently compiled Signal without issues using Docker. So I think the best place to continue with this would be here https://whispersystems.discoursehosting.net/c/development
Open a topic there and someone will help you out.

**Comment by wcummings** [comment]
>Docker

Did you just tell me to go fuck myself?

**Comment by 2-4601** [comment]
Sorry, can't take credit for that. Looks like you managed to do that all by yourself.
https://www.youtube.com/watch?v=oApBlWipc2A
