### ISSUE TITLE
Display message info on single tap

### ISSUE THREAD

**Issue by breversa** [WhisperSystems/Signal-Android#5413]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
This is a feature request :
A single tap on a message should display the message's info (currently, a single tap does nothing), à la [Kontalk](http://kontalk.org/).

### Current behaviour
- long-tap on a message to select it
- tap the "info" icon to display the message's info

### Suggested behaviour
- tap a message to display the message's info.

**Comment by moxie0** [comment]
thanks but we're not going to do this

**Comment by breversa** [comment]
Any reason why not ?
Le 4 avr. 2016 19:33, "Moxie Marlinspike" <notifications@github.com> a
écrit :

**Comment by 2-4601** [comment]
Possible reasons
- it's not a feature that majority of the users need that often
- it makes tapping logic unnecessary complicated (links, images)
- https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#development-ideology
- https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#my-issue-was-closed-without-giving-a-reason

**Comment by breversa** [comment]
Thank you for the explanation. The second point in particular is sound.

2016-04-04 23:10 GMT+02:00 2-4601 <notifications@github.com>:
