### ISSUE TITLE
fallback to a different SMS provider than builtin SMS carrier

### ISSUE THREAD

**Issue by anarcat** [WhisperSystems/Signal-Android#5414]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

Since I do not have a phone carrier plan, I use signal to send and receive messages over Wifi connections. This works because I have a VoIP provider with which I was able to go through the voice-based registration procedure (and thank you so much for that!).

However, to send and receive SMS messages, I use a [different app](https://github.com/michaelkourlas/voipms-sms-client), which works pretty well. In fact, during the registration process, I *did* receive the SMS confirmation message - i just wasn't able to use it because Signal didn't intercept it. But that's fine as well because I could work around the problem.

My main concern at this point is that I need to consciously switch between my SMS and Signal apps, based on whether or not I know that the user has Signal at all. In fact, I think there's a usability issue there, even for regular user: if Signal has trouble sending SMS messages (e.g. problem with the SIM card, connectivity issues), how does it tell the user? From my point of view here, Signal tries to send the message and I get the "bouncing 3 dots" forever, even though there's no SIM card on the phone and this will never succeed.

What I would like would be for Signal to be able to talk to other apps to send and receive insecure SMS messages. I am not sure i clearly understand how the insecure fallback works right now - it doesn't feel like Signal uses the builtin messaging app but talks to the SMS subsystem of Android on itself. Could it be possible to fallback to some other SMS provider?

I guess this also applies to competing protocols like Whatsapp or Telegram: what if my contact is not using signal? Could I still use Signal as a unified messaging app? (and coincidentally invite my poor Whatsapp or Telegram user to join Signal!)

Note that other apps would need support for such process, of course. I have opened an issue for my specific app (https://github.com/michaelkourlas/voipms-sms-client/issues/55) but I guess there would need to be such systems in place for this to work with Telegram or Whatsapp or whatever...

Finally, I understand if you close my feature request as out of scope, but please do consider at least the case where the sim card is misplaced, removed, or the phone is in airplane mode. Usability could be improved at that level. At least having a timeout (or a shorter one, if there is one already) would improve the situation here.

### Steps to reproduce
- remove your SIM card
- register a SIP account with SMS support (e.g. at https://voip.ms/)
- install an app to manage SMS in Android (e.g. https://github.com/michaelkourlas/voipms-sms-client)
- try to send an insecure message in Signal

**Actual result:** the message never gets sent and gets stuck in the "bouncing 3 dots" state forever (or at least, I have a few messages stuck in that state since saturday, so 48h+)
**Expected result:** detect there is no SIM card and fail, or offer some configuration option to send messages through another messaging app

### Screenshots

![screenshot_2016-04-04-14-36-44](https://cloud.githubusercontent.com/assets/796623/14258996/fa4a0412-fa72-11e5-8041-e6b007071954.png)

The above screenshot shows Signal functioning normally for secure messages, but shows the last message stuck in the "three bouncing dots" state for 3 minutes. Earlier in the history, there are two more messages stuck in that state from saturday (not shown in screenshot).

### Device info

**Device:** HTC One S4 ("Ville")
**Android version:** 5.1.1 (Cyanogenmod 12.1-20160323-NIGHTLY-Ville)
**Signal version:** 3.15.2

### Link to debug log

https://gist.github.com/5b0303234463bc3ce4146f9bbec802e4

**Comment by FeuRenard** [comment]
Why is disabling SMS in Signal no option?

**Comment by moxie0** [comment]
It's functioning normally by queuing the message until an SMS network is available.  Sorry but we're not going to include integration into third party SMS apps.
