### ISSUE TITLE
After installing Signal Desktop, my Signal Android crashes on startup

### ISSUE THREAD

**Issue by ericp44** [WhisperSystems/Signal-Android#5426]
I have:
- [ x] searched open and closed issues for duplicates - Perhaps similar to #5173
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashes on startup.  (adb log attached).

### Steps to reproduce
After attempting to setup the Signal Desktop on the Chromium browser, my Android Signal now crashes immediately after putting up the Passphrase prompt.   Tried the "airplane mode" article suggestion - no change.  Rebooted, cleared cache , again it continues to crash.

Note that this was the second try at installing Signal Desktop - the first one I aborted as the key generation was taking way too long ( > 8 hrs.)  The second try worked (for the Desktop, at least), but the my Android started crashing... (I sent one crash report from the phone - not sure where that goes.)

### Screenshots
Likely not useful.

### Device info
**Device:** Samsung Galaxy S4 (AT&T model)
**Android version:** 5.0.1
**Signal version:** 3.15.2

### Link to debug log
See attached adb log (trimmed to just before and after attempting to start Signal.)
[adb.txt](https://github.com/WhisperSystems/Signal-Android/files/209370/adb.txt)

**Comment by moxie0** [comment]
Dang, sorry but it looks like disk corruption.  =(

It's reading something off the disk that we definitely didn't write there.

**Comment by ericp44** [comment]
Darn.  Oh well, thanks for so quickly looking into it...

Eric
