### ISSUE TITLE
Moving signal from one phone to another causes issues.

### ISSUE THREAD

**Issue by vext01** [WhisperSystems/Signal-Android#5430]
### Bug description

Last week I was travelling. Prior to my trip I had asked a question on the Signal site about migrating my session to my old phone (which would not matter too much if it were lost or stolen). The response I got was:

```
You can install Signal on your other phone.  Any new
installation of Signal will generate new keys.
```

However, it doesn't seem to be as simple as this.

### Steps to reproduce

This explains my pre-travel actions:

* Install signal for android on phone1.
* Use signal for a while. Partake in private and group messages.
* Remove sim card from phone1 and install in phone2.
* Install signal on phone2.

At this point, I am on the road with phone2. If you message people, they are informed that my keys have changed, which is fine.

However, if other people post in a group chat that you were involved in on phone1, then the group is named `Unnamed group` on phone2 and the message entry box is un-tappable. You see messages come in, but you are unable to send messages.

Then I returned home, and replaced the sim card into phone1.

Now I cannot message anyone. The messages have a red message next to them saying `Failed to send` and `Tap for details`. When you tap, you see `( i ) Some issues need your attention` and `Failed to send. There is a `re-send` button, but it doesn't help in this case.

### Expected Outcome

Signal should work on multiple devices per account (and it would be nice if it worked on tablets too).

I think the issues I outline are because each user is expected to have exactly one keypair. This would be fine if there were a way to share a keypair between more than one device, or if Signal allowed one account to have multiple key-pairs. Maybe this design decision relates to the fact that a phone number can be active in only one device at a time?

I also note that signal still works on phone1 which has no SIM card inserted. Not sure if that is desired behaviour(?).

I'm not sure what I should do to get signal working again, please advise.

Thanks

**Comment by 2-4601** [comment]
> However, if other people post in a group chat that you were involved in on phone1, then the group is named Unnamed group on phone2 and the message entry box is un-tappable. You see messages come in, but you are unable to send messages.

This is a known issue: #1048, #2581

> Then I returned home, and replaced the sim card into phone1. Now I cannot message anyone.

That's because phone2 registered "over" phone1 and now phone1 is confused. There's an issue for this #5057.

> I'm not sure what I should do to get signal working again, please advise

Go to **Advanced Settings** and disable and enable **Signal messages and calls**
If that doesn't work contact support@whispersystems.org
