### ISSUE TITLE
Process 'command 'git'' finished with non-zero exit value 128

### ISSUE THREAD

**Issue by anvesh523** [WhisperSystems/Signal-Android#5432]
Error:(254, 0) Process 'command 'git'' finished with non-zero exit value 128
<a href="openFile:C:\Users\Downloads\Signal-Android-master\build.gradle">Open File</a>

I downloaded and imported into Android Studio, but build is not finished.

**Comment by agrajaghh** [comment]
you need to install git (and probably place it in the PATH variable), also have a look at: 
https://github.com/WhisperSystems/Signal-Android/pull/5398#issuecomment-203235677

**Comment by nomanzafarminhas** [comment]
where to find (PATH VARIABLE)?

**Comment by nomanzafarminhas** [comment]
i have already placed the GIT path but still the error occurs

**Comment by cyleunggg** [comment]
me too.. anyone can tell us this problem? thanks
