### ISSUE TITLE
Unable to upload / download media files on Android

### ISSUE THREAD

**Issue by swagitda** [WhisperSystems/Signal-Android#5434]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I'm unable to upload or download media files, including images and video files, since the latest Signal update on Android (3.15.2 on March 25, 2016). 

### Steps to reproduce
- Open Signal
- Open conversation
- Attach image
- Press send

or

- Open Signal
- Open conversation
- Tap image message for viewing

**Actual result:** For upload, it immediately gives says it is not delivered / failed to send. For download, it continually shows the active spinning-circle showing it is attempting to download, but never does so.
**Expected result:** Successful upload and delivery of media files and successful download of media files so they can be viewed in the conversation. 

### Screenshots
![screenshot_20160412-124335](https://cloud.githubusercontent.com/assets/18424886/14468229/c4a1371e-00ac-11e6-9fe6-f08d9fa82749.png)

### Device info
**Device:** LGE Nexus 5
**Android version:** 6.0.1
**Signal version:** 3.15.2

### App state
Signal messages and calls registered, SMS disabled, dark theme, passphrase enabled

### Link to debug log
https://gist.github.com/anonymous/1cbece0505b8c48c5e641bd7868a98e0

**Comment by moxie0** [comment]
Looks like either your manually removed the TLS CA that Amazon S3 uses, or your network is MITMing your connection to S3. I'm guessing the former.

**Comment by swagitda** [comment]
Thanks -- for anyone else, Amazon recently updated to new certs so Baltimore CyberTrust Root CA needs to be added: https://forums.aws.amazon.com/ann.jspa?annID=3544
