### ISSUE TITLE
Not getting notification in real time unless I open the app

### ISSUE THREAD

**Issue by mkmustafa** [WhisperSystems/Signal-Android#5447]
Device  : HUAWEI HUAWEI CRR-UL00 (CRR-UL00)
Android : 5.1.1 (C433B114, CRR-UL00C433B114)
Memory  : 29M (5.51% free, 256M max)
Memclass: 256
OS Host : WUH1000006455
App     : Signal 3.15.2

not getting notification in real time, i installed signal in my wife phone, and when sending messages from her to me or vise versa, we dont get the messeage unless opening the app.

the all must be like whatsapp we getting notifications in real time.

thanks

I have:
- [ ] searched open and closed issues for duplicates
- [ ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by 2-4601** [comment]
This is not a bug in Signal. It is a bug in Huawei.

You should add Signal as a protected app in Huawei settings: http://www.androidheadlines.com/2016/01/how-to-fix-missing-notifications-on-huawei-phones.html

For further help, please read http://support.whispersystems.org/hc/en-us/articles/213190487-Why-is-there-a-delay-in-receiving-messages- and contact support@whispersystems.org

**Comment by mkmustafa** [comment]
Hello,

Its not in Huawei then alone when I'm sending to my wife mobile, i'm facing the same issue, Samsung Note 5.

Why we are not facing the same issue on Whatsapp???

Thanks

**Comment by 2-4601** [comment]
> Why we are not facing the same issue on Whatsapp???

Because Huawei and Samsung have made sure that WhatsApp is not restricted in any way by default. If it was, they would get a lot of complaints why the most popular messenger is not working out of the box. That would make the vendors look really bad and they would lose sales. But when it comes to smaller apps, they don't care.

Please go through the support article: http://support.whispersystems.org/hc/en-us/articles/213190487-Why-is-there-a-delay-in-receiving-messages- 
And if you still have issues after that, please contact support@whispersystems.org

**Comment by mkmustafa** [comment]
I understand Huawei has a problem, but why I don't receive realtime notification on Samsung Note 5 ??

I really love Signal and I want to use it but I can't if no real notifications

**Comment by agrajaghh** [comment]
> Please go through the support article: http://support.whispersystems.org/hc/en-us/articles/213190487-Why-is-there-a-delay-in-receiving-messages-
> And if you still have issues after that, please contact support@whispersystems.org
