### ISSUE TITLE
Signal doesn't receive new messages when re enabling mobile internet after it was disabled over night.

### ISSUE THREAD

**Issue by towlie** [WhisperSystems/Signal-Android#5452]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I disable my mobile internet connection over night and it always happens that signal will start receiving new messages only when I open the app manually.

### Steps to reproduce
- Disable mobile internet via android settings (wi-fi is always disabled)
- Go sleep for 7 h
- enable mobile internet

After waiting some minutes I notice that no message is received by signal. (While other apps like whatsapp already show new messages) The messages are only received when you manually open signal.
The expected result would be that I don't have to open signal manually to get notified about new messages when disabling mobile internet over some time.

### Device info

**Device:** Vodafone 890N
**Android version:** 4.4.4
**Signal version:** 3.15.2

### Link to debug log

https://gist.github.com/f5d5a381434753ea588c9bc6df0f4ed8
I can tell you that the app is running in the background and gcm seems to work again after signal was manually opened.

**Comment by riyapenn** [comment]
Contact support@whispersystems.org. See also, at minimum, Stpes 4, 6,& 8 on the support page: http://support.whispersystems.org/hc/en-us/articles/213190487-Why-is-there-a-delay-in-receiving-messages-

**Comment by towlie** [comment]
I tried your steps from the FAQ but those onky lasted one day. Now it is like before.
Here is a Log:
https://gist.github.com/f5d5a381434753ea588c9bc6df0f4ed8

**Comment by towlie** [comment]
I close this because I figured out that this is caused by signal itself which sometimes crashes with all it's services. This explains why it worked sometimes.
