### ISSUE TITLE
Msg. repeatedly sent in group chat

### ISSUE THREAD

**Issue by metasoma** [WhisperSystems/Signal-Android#5459]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The posts I receive in group chat appear from time to time repeatedly.
My own posts are shown regular (one time) at my device, but in some cases repeatedly at others.
Possibly it is a problem between signal and textsecure, but I have no idea how to fix it. Can anybody help with this issue?

### Steps to reproduce
- send a post in lager group chat
- members receive this post repeatedly
- ID-key will also change from timt to time (automatically)

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** iPhone 4s
**Android version:** 0.0.0
**Signal version:** 2.2

### Link to debug log

https://gist.github.com/ebdb2cfb2e327c1375e1b406dc4cdd24

**Comment by FeuRenard** [comment]
1. This is a Signal-iOS issue, but this issue is posted in the Signal-Android project
2. This issue seems to be already tracked. Have a look at https://github.com/WhisperSystems/Signal-iOS/issues/951

**Comment by metasoma** [comment]
thanks, but I can't find a clear solution.
Is it just that one member of the group hasn't actualized the ID-key,
or is it a problem of weakness of the network-signal?

**Comment by FeuRenard** [comment]
It's a yet unresolved issue but the developers are aware of it. There is nothing you can do about it, I think.

**Comment by 2-4601** [comment]
If you receive a message multiple times in a group and the sender was using Android, it's most likely #2639
If people receive your message twice it's most likely the issue @FeuRenard referred to.
If you receive a message about an identity key change, it means that your friend changed their device, reinstalled Signal etc.
