### ISSUE TITLE
Group Images are still not getting resized.

### ISSUE THREAD

**Issue by tokariu** [WhisperSystems/Signal-Android#5461]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Sending a large Image (f.i. 13MPixel, ~6MB .jpg) to a Group doesn't resize the Image to a lower dimension and filesize. When you send the same Image to a single Contact in contrary, it -does- resize the image.

This leads to a large amount of traffic use on both ends. Group images should ideally be handled the same way as single contact images.
In a perfect version, the user should be asked for whether it should resize the image or not.

This issue has actually been found and fixed 1 year ago here **BUT** it is still happening in the latest Version of Signal: [https://github.com/WhisperSystems/Signal-Android/issues/2913](https://github.com/WhisperSystems/Signal-Android/issues/2913)

### Steps to reproduce
- create a group, add one or more contacts.
- send a large image (13 MPixel / ~ 6 MB) to this group. 

**Actual result:** The Image is not getting resized and Signal sends a whole 6 MB image to the group. The group receives (and has to download) a full 6 MB Image.
**Expected result:** You actually send a resized image (1280 * xxxx, ~200 KB) to that group. The group receives and downloads just a 200 KB Image.

### Device info

**Device:** LG G3
**Android version:** 6.0.1
**Signal version:** 3.15.2

**Comment by 2-4601** [comment]
Can reproduce on Nexus 4, stock 5.1.1, Signal 3.15.2

@liliakai https://github.com/WhisperSystems/Signal-Desktop/issues/417

**Comment by Dyras** [comment]
I wish this "bug" also applied to one-on-one chats, preferably as an option you can enable/disable.

I can also confirm on Moto G (2015)

**Comment by tokariu** [comment]
@Dyras indeed.
Signal not asking the user if he actually wants the image to be resized or not, is somewhat patronizing. Signal should have a bit more confidence in the abilities and knowledge of the user.

**Comment by dkasak** [comment]
Agreed. Please don't change this, at least until [the bug with overresizing images in 1-on-1 chats](https://github.com/WhisperSystems/Signal-Android/issues/672#issuecomment-220685988) gets resolved. Preferably, resizing would be configurable since most of my Signal-using friends end up sending photos through other (unsecure) means because of this.

**Comment by FeuRenard** [comment]
The fix #2913 was (accidentally?) reverted by #4248. I am working on this.
