### ISSUE TITLE
Sent videos shouldn't take up extra space on internal memory

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/Signal-Android#5464]
Ever since I installed Android M on my Moto G3 I've had problems not filling my internal memory by accident, because Play Music now refuses to put my music on my SD-card. Ordinarily I can handle this quite well, with one exception..

Signal keeps using all the internal space, because everytime I send a video the app creates a duplicate of the file **inside **of Signal and I can't help but ask: Why? Why would I ever need a copy of my video inside of Signal? If you send a video you already have it on your phone, so why make another copy? The obvious explanation is that that way you know which video you sent, but really, can't you just add a file name instead? 

I think this behavior would be fine if I could put Signal on my SD-card, or if Signal could somehow only save transferred files on the SD-card, but in a world where internal space is scarce I think this is a really stupid design decision.

Yes, I know about the feature that trims conversations and yes I know I can just delete the video from Signal after sending the file. But come on guys, that shouldn't be necessary!

**Comment by moxie0** [comment]
Please use the issue template when opening issues.  GH isn't the place to ask questions or discuss:
https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#not-a-discussion-forum
