### ISSUE TITLE
Enhancement: Only open keyboard in contact list when long-pressing the Compose button

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/Signal-Android#5469]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

I've always found it unnerving that **the keyboard always pops up when opening the contact list** (and I'm sure I'm not the only one). Nine out of ten times, I'll immediately close the keyboard. At the same time, I understand that this behavior has its purpose.

So in order to make everybody happy, I suggest a small (but quite elegant imho) change that additionally is completely in line with Android's (i. e. Marshmallow's) own behavior regarding e. g. the *All Apps* button (the button that opens Android's app drawer):
- Tapping the Compose (i. e. pencil) button opens the contact list (but *not* the keyboard),
- Long-pressing the Compose button opens the contact list *AND* the keyboard.

Ok, that's it. My suggestion.

**Comment by moxie0** [comment]
Thanks but we've already gone back and forth on this and eventually settled on keyboard open, I don't think another option would help
