### ISSUE TITLE
Invasive invite banner

### ISSUE THREAD

**Issue by chmol** [WhisperSystems/Signal-Android#5471]
I have:
- [x] a useful feedback
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
It's worst than a spam, even with an ablocker you can't get rid of it : it's the invite banner in text mode. 

This is not a feature! it's reductive, I've seen people losing 1/5 of their screen because they are too lazy to click on that small cross and the banner stay forever. 

It make sense, it's a nice — maybe cool —  way to advertise the product, but it is invasive. 

### Steps to reproduce
- download the app
- text a non signal friends
- endure a smaller screen for your 100+ text messaging.

**Actual result:**  invasive banner
**Expected result:** no banner. A option to invite friends after registering for the first time would be nice. Or an option in the menu

**Comment by moxie0** [comment]
thanks but we're not going to do this
