### ISSUE TITLE
RedPhone server source code

### ISSUE THREAD

**Issue by DroidFire** [WhisperSystems/Signal-Android#5474]
@moxie0 Could you please release RedPhone server source code? You could release it under the AGPL license, so everybody, who wants to run a modified of the RedPhone server would have to open source the changes. You can read more here: [](https://gnu.org/licences/why-affero-gpl.html)

After reading your replies on the list, I understand, that the main reason for not releasing it is that you don't want to be flooded with support questions. Now, that you have an unofficial support forum, you could just redirect support questions there.

Are there any other reasons for not releasing RedPhone server source code?

I had already asked this question on the mailing list, but I haven't received any official reply. That's why I'm opening an issue here.

**Comment by moxie0** [comment]
This is not a discussion forum: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#not-a-discussion-forum
