### ISSUE TITLE
Failure sending/receiving images

### ISSUE THREAD

**Issue by voidzero** [WhisperSystems/Signal-Android#5475]
People in my contact list report that they are unable to send and receive images. The delivery "just fails". This occurs both in groups, and with single recipients.

**Comment by 2-4601** [comment]
It would require a bit more information to get to the root cause of the issue.
Could you ask your contacts to submit bug reports?
https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

**Comment by voidzero** [comment]
Thanks for the link. I'll try to get this done when I can do this myself using one of their phones. I don't have these issues myself, sending works for me. But when I send pictures, some recipients are unable to open them.

When I get my hands on one of their phones, I'll let you know by updating this bug.

**Comment by voidzero** [comment]
As it turns out, this issue was caused by a disabled CA certificate for both contacts. Re-enabling the certificate fixed the issue and means that this is not a bug, but a user error and may be labelled as such. I'll close it; my apologies.
