### ISSUE TITLE
Send using "Enter" Key on Hardware Keyboard

### ISSUE THREAD

**Issue by rfkrocktk** [WhisperSystems/Signal-Android#5476]
Feature request: when using an external USB keyboard with my device on Signal, make it possible to send messages using either:

 - <kbd>Enter</kbd>
 - <kbd>Ctrl</kbd>+<kbd>Enter</kbd>
 - <kbd>Shift</kbd>+<kbd>Enter</kbd>

If desired to send on plain <kbd>Enter</kbd>, <kbd>Shift</kbd>+<kbd>Enter</kbd> should enter a newline.

**Comment by 2-4601** [comment]
What happens when you change the setting **Enter key sends** in **Advanced settings**?
See #2374

**Comment by rfkrocktk** [comment]
@2-4601 to be honest I haven't tried that yet, though I'd prefer it be a separate setting for strictly hardware keyboards only. With a hardware keyboard, it's easy enough to use <kbd>Shift</kbd>+<kbd>Space</kbd> to force a newline and have <kbd>Enter</kbd> send by default. On a software keyboard, not so much. If the enter key on a software keyboard sends by default, how would one insert a newline if needed?

**Comment by moxie0** [comment]
Thanks but we're not going to do this

**Comment by rcdailey** [comment]
Would you reconsider this request? There needs to be a way to insert newlines and submit the message independently, regardless of the specific configuration of each. With the "Enter to send" option ON or OFF, there is still not a way to independently control each of these actions without constantly toggling the option.

It's very annoying to have to remove my hands from my bluetooth keyboard to hit the Send button. I much prefer to hit CTRL+Enter to send, and press ENTER to get a newline.

**Comment by huettenwirt** [comment]
Yeah, just came across this since I love to type messages using my bluetooth keyboard switching easily between devices. 

A CTRL-Enter to send would be perfect! So I second this request!!!

Thx a lot for considering this!

**Comment by anEXPer** [comment]
Control Enter or Shift Enter is standard in other applications that allow both multi-line messages and external keyboards. Would y'all please reconsider?

**Comment by jweickm** [comment]
I know that this is an old issue, but I am encountering the same issue in 2022 and was surprised to find that there seems to be no solution to have the option to send or enter a new line with a hardware keyboard on the android app. Would love if this were implemented, especially considering how viable connecting android devices via usb-c to a workstation has become.

**Comment by ArchxxAngel** [comment]
If you're using the Samsung Smart KBD Trio 500 to type text messages you have to press **Alt+Enter** to send the message within the phone messaging app. I don't know if this works for all texting/messaging platforms but this does work with the default Samsung phone keyboard in the Samsung messages app. This may work on other Bluetooth keyboards as well so I thought it was worth sharing.

**Comment by Divade011** [comment]
Don't expect much since this was closed, but I'll still comment just in case it helps it get revisited. Thank yall for the app.
