### ISSUE TITLE
 Cannot reply to contact who just joined Signal

### ISSUE THREAD

**Issue by wynkoop** [WhisperSystems/Signal-Android#5478]
Please see and re-open or merge in  #5186.  I have been struggling with the exact same problem for about two months.  I do not have MoboClean installed on my phone.  This has happened with two contacts so far and nothing I can do on my end will fix the issue.

Symptoms are they send to me via encrypted signal over IP.  My outbound to them shows  sms as my only choice and I have the "Invite" item in my menu.

I use signal as my only messenger for sms or signal contacts.

**Comment by 2-4601** [comment]
Make sure your contacts' phone numbers are [correctly formatted](http://support.whispersystems.org/hc/en-us/articles/212535528-Who-can-I-message-).
The best place to get help for this is contacting support@whispersystems.org
