### ISSUE TITLE
Allow manual selection between SMS and Signal messages (feature request)

### ISSUE THREAD

**Issue by dluciv** [WhisperSystems/Signal-Android#5481]
There were a lot of cases for this already. After looking through conversations, it seems that each of them references others as duplicates and so all of them are considered closed =).

I have a person in my contact list, who is mostly offline but this person is Signal user. I am also Signal user ans I also often get offline. When I send message to this person, it stays undelivered for hours. In case when it is urgent but not confidential at all, I want to have an ability to send it as SMS explicitly.

I can just use built-in SMS application to send and receive SMS (as I am going to do now), but it is more comfortable and safe to use Signal here too. So the only wish is to let me decide when talking to Signal users, what exactly I want to send: Signal message, or SMS.

Finally, until Signal allows to select between its messages and SMS, replacing stock SMS app with Signal just looks confusing because of above reasons.

**Comment by 2-4601** [comment]
You can already do this: http://support.whispersystems.org/hc/en-us/articles/212535548-How-do-I-send-an-insecure-SMS-

**Comment by dluciv** [comment]
Cool, thank you. Unobvious a bit, but quite usable. Is there any way to keep this selection persistent?

**Comment by 2-4601** [comment]
Nope, but there's an open issue for it #2285
