### ISSUE TITLE
Can only send unsecured SMS

### ISSUE THREAD

**Issue by johman10** [WhisperSystems/Signal-Android#5482]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I can only send unsecured sms to someone that has the Signal app. And once I install the Chrome app I can send him Signal messages in a secure way and they show up with lock and everything in the Android app.

### Steps to reproduce
This is more like a default s
- Install the Signal app
- User was not in list of possible persons contact
- Searched by phone number
- Open conversation with user

**Actual result:** Can only send unsecured sms.
**Expected result:** Can send secured Signal message

### Things I already tried to fix it
- Force stop in Android settings
- Clear data in Android settings

### Screenshots
Can't make one because of app security measures.

### Device info

**Device:** Google Nexus 5
**Android version:** 6.0.1
**Security patch level:** April 2, 2016
**Signal version:** 3.15.2

### Link to debug log
[https://gist.github.com/anonymous/104da68c63c0485aa2741eaa740df83e](https://gist.github.com/anonymous/104da68c63c0485aa2741eaa740df83e)

**Comment by 2-4601** [comment]
Thanks for the well written report.
Have you tried refreshing your Signal contact list? (tap blue pen, contact list shows up, pull to refresh like you would do in other apps like gmail)
If that doesn't work go through this support article: http://support.whispersystems.org/hc/en-us/articles/215089628-Why-can-I-only-privately-message-one-way-

**Comment by johman10** [comment]
I tried to refresh but that didn't work. I will add it to the original post about the things I already tried. ;)

... Or wait! I found the issue using your link.
My contact didn't have the "+" sign before it's number. That's why it didn't work. I'm sorry for the trouble. I will close this issue.
