### ISSUE TITLE
Messages not sent

### ISSUE THREAD

**Issue by aplainzetakind** [WhisperSystems/Signal-Android#5484]
Since about a week ago, very often the messages I send get stuck on the wavering dots stage, which I presume means not even sent let alone delivered. Today I tried reinstalling, and now the contact list does not get populated (one contact sent me a message and so showed up, but that's it).

**Comment by aplainzetakind** [comment]
The problem seems to occur when I'm on WiFi. I switched to mobile data and first got a deluge of failure notifications, then everything started working fine.

**Comment by 2-4601** [comment]
Please use the issue template when opening new issues.
