### ISSUE TITLE
JPG image from MMS saved in database with wrong header 

### ISSUE THREAD

**Issue by Killeroid** [WhisperSystems/Signal-Android#5485]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I'm unable to view a received MMS.
The thumbnail is badged with a red error triangle and is just blank when I click on it. 
When I try saving the image, I get a corrupt jpg file which cannot be viewed.
The logs say its due to the thumbnail having illegal dimensions ( org.thoughtcrime.securesms.util.BitmapDecodingException: Failed to decode image dimensions: -1, -1  ).

After analyzing the image file, it appears that the first two bytes of the image file which should be **FF D8** (the JPEG start of image marker) is instead, **5C 52** ( the ascii string "**\R**" ). After modifying on my desktoip, a manually saved copy of the file, changing the first two bytes to the correct values, the image displayed correctly. 

### Device info

**Device:** samsung SM-N910F (trltexx)
**Android version:** 5.1.1
**Signal version:** 3.15.2

### Link to debug log
https://gist.github.com/anonymous/f265feabaac36b94e15cd50c97a4f1a4

**Comment by Killeroid** [comment]
After analysing the image file, it appears that the first two bytes of the image file which should be **FF D8** (the JPEG start of image marker) was replaced with  **5C 52** ( the ascii string "**\R**" )

**Comment by 2-4601** [comment]
Was the image already corrupted before it was sent or did it get corrupted after it was sent?
If latter, can you reproduce this every time? Does it get corrupted if you send it through another carrier?

**Comment by Killeroid** [comment]
The image was uncorrupted before it was sent, so I assume it was corrupted after it was sent.  I unfortunately dont have the means to reproduce this bug right now(I'm not in touch with original sender and no one else sends me MMS :( ) . I can update this bug if the problem crops up again.

**Comment by Killeroid** [comment]
I'm going to close this because I have not been able to replicate this issue. I will re-open it and provide more details if it crops up again.
