### ISSUE TITLE
Read notifications

### ISSUE THREAD

**Issue by cornim** [WhisperSystems/Signal-Android#5488]
I would like to have Signal display read notifications to contacts that I choose.

I have read the lengthy discussion in #957 about read receipts but since this is over 2 years old, I would like to reopen the discussion.
From my point of view, having a feature that transmits information (like when a message was read) in an app that is about communication (i.e. the transmission of information) is a good thing.

Whether to make this feature on/off by default or opt-in/opt-out is obviously debatable. My personal opinion is that I'd probably like it to be opt-out on a per contact basis, but to not change the current behavior for people from how it currently is, it would probably be more sensible to have Signal ask the question once per contact (when you start a new conversation) unless a default setting is set in the settings section.

Even if the feature is delivered as off by default and has to be manually enabled, it would be a big improvement over the status-quo.
Because (and I cannot stress this enough after reading through the discussion in #957) having a minority restrict the choices of a majority is the opposite of freedom and democracy and it seems to me these are among the most important things that free secure messaging is trying to protect.

**Comment by cornim** [comment]
After some additional searching I've seen that there have been quite a number of request for this feature. #866, #2667, #2779, #3251 are the ones that I found so far. While all of them have been closed with the statement, that the current decision is to not do this, none of them provide any reasoning for it.
So if you do decide to close this issue as well I would appreciate it, if you could give me an explanation as to why my arguments don't make sense to you.

**Comment by 2-4601** [comment]
If you read #957, you must have also read the comments that say that this issue tracker is not the preferred place for discussions like this. This is also mentioned in [CONTRIBUTING.md](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#not-a-discussion-forum).
