### ISSUE TITLE
Signal not recognising contact

### ISSUE THREAD

**Issue by libeclipse** [WhisperSystems/Signal-Android#5495]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal won't recognise friend as a signal-contact. He's from Sweden, and I'm in the UK. I added him to my contact list, and then later a mutual friend added us both to a group chat. In the group chat, he could send messages but wouldn't receive anything. However, to us, it would look as if the messages have been delivered. When I try sending a private message, it defaults to SMS. However, he is able to send me private messages, so clearly his client recognises my number as a signal contact. Later I reinstalled signal and created a group again, this time the entire group defulted to SMS from the start. He also uses signal for iOS, while I use signal for Android.

### Screenshots
Reinstalled signal. Will try and capture screenshots later.

### Device info

**Device:** Samsung Galaxy S III GT-i9305
**Android version:** 4.4.4
**Signal version:** 3.15.2

### Link to debug log
Reinstalled signal, will try and capture another debug log.

**Comment by skulumani** [comment]
Is you number stored in E.164 format?

http://support.whispersystems.org/hc/en-us/articles/212535528

Or you/friend may have to reregister

http://support.whispersystems.org/hc/en-us/articles/218928858

https://en.wikipedia.org/wiki/E.164

**Comment by 2-4601** [comment]
And please go through this article with your Android device:
http://support.whispersystems.org/hc/en-us/articles/215089628-Why-can-I-only-privately-message-one-way-

**Comment by libeclipse** [comment]
Ah that seems to have fixed the issue. I think there was an extra 0, so +XX07 instead of +XX7.
