### ISSUE TITLE
Redphone/Phone: encrypted calls not for all contacts

### ISSUE THREAD

**Issue by mistersixt** [WhisperSystems/Signal-Android#5497]
Android 6.0.1, Nexus-5, Signal version 3.15.2.

I have a few contacts (maybe 5% of all my Signal partners) where I am able to send encrypted messages to, but this lock sign next to the earphone symbol is missing, indicating unsecure/unencrypted/regular calls only.

The phone number syntax is the same across all contacts, removing the account and refreshing things does not help (for testing purposes I tried new, different phone number layouts, prefix vs. +-sign etc. etc., with no improvement).

The funny thing is that with those 5% the other contacts do see this lock sign with my contact, and they can successfully inititate Redphone calls to me. It is just my side which cannot initiate encrypted calls.

So what is wrong with this 5% of my Signal contacts?

Any help is welcome,

Kind regards, mistersixt.

**Comment by riyapenn** [comment]
Try Android Settings > Accounts > Signal > Menu > Remove Account > then Resync

**Comment by mistersixt** [comment]
As I've mentioned in my first message I exactly tried the steps you've mentioned already, without any improvement.

Regards, mistersixt.

**Comment by riyapenn** [comment]
I misread. Redphone is no longer supported. Contact support@whispersystems.org.

**Comment by mistersixt** [comment]
The problem occurs with Signal version 3.15.2., I've just mentioned "Redphone" so that you know I am talking about the phone/call functionality, and not the messaging part.

**Comment by moxie0** [comment]
@mistersixt For these contacts, do you know anything about whether other people are able to call them?  Or how long they've been Signal users?

**Comment by mistersixt** [comment]
Interesting point you did: I am using the app since a very long time, and as far as I remember those contacts with the issue mentioned, too (so starting with some ancient TextSecure version with all the updates during the time and doing the merge to Signal at some point). And I do know that those other contacts got a new mobile phone in the meantime doing a fresh TextSecure/Signal installation at some point while I am running my Nexus-5 since day one without any fresh installation or factory reset.

Maybe related to this?

Whether those other contacts have contacts they cannot initiate encrypted calls with either I need to clarify.

regards, mistersixt.

**Comment by moxie0** [comment]
If these are very old contacts, it could be that there was a problem during the migration and they never got registered for calls.  You could ask them to unregister and reregister (don't need to uninstall) in Signal Settings -> Advanced -> Signal messages in order to see if that helps

**Comment by mistersixt** [comment]
That did the trick, thanks a lot :-) !

Kind regards, and thanks for the speedy responses,

mistersixt.
