### ISSUE TITLE
Signal is my default SMS app but incoming messages are routed to Hangouts

### ISSUE THREAD

**Issue by bbusenius** [WhisperSystems/Signal-Android#5498]
I have:
- [ x] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I have set Signal as my default SMS app. It sends messages fine and launches when I click the message icon from my contact list. Signal does not, however, receive SMS messages. SMS messages sent to me are routed through hangouts. This happens even though Signal is recognized as the default SMS app and Settings > Apps > Hangouts > Permissions > SMS is toggled off.  Toggling Wifi Calling support in settings doesn't seem to make a difference. 

This looks similar to what was happening to what was happening to user espinozagabe in [issue 5033](https://github.com/WhisperSystems/Signal-Android/issues/5033). He was told to post his case to a new issue but I could not find it.

### Steps to reproduce
- Install Signal 
- Set Signal as the default SMS app
- Send messages, it will work fine

**Actual result:** 

When people respond to the messages sent with Signal, they are routed to Hangouts. 

**Expected result:** 

Incoming messages should go to Signal since it is the default SMS app.

### Device info

**Device:** LGE Nexus 5X, on Project Fi
**Android version:** 6.0.1
**Signal version:** 3.15.2

**Comment by FeuRenard** [comment]
#5044 might be related, also Project Fi.

**Comment by bbusenius** [comment]
Yes, that looks like the same issue. I apologize for not commenting there. I couldn't find that one when I searched.

**Comment by bbusenius** [comment]
We should probably close this thread and continue on the other.
