### ISSUE TITLE
[Feature request] Support offline mesh network messaging

### ISSUE THREAD

**Issue by hchaase** [WhisperSystems/Signal-Android#5501]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature Request: Offline mesh network messaging.
Implement an option to use an offline mesh message network like e.g. [firechat](https://play.google.com/store/apps/details?id=com.opengarden.firechat).
firechat and the like use the phones Wi-Fi and Bluetooth antennas to transmit messages, calls and files without connection to cell towers or Wi-Fi. if more people are using it, it can relay messages through other users to the recipient (less server load).

it could be nice if signal could send messages like:

is local mesh-network available? yes: use no: ↓
is signal message possible? ues: use, no ↓
use sms.

##### usercase1: privacy
This will give great privacy reassurance. if you are within range to use a local mesh-network you can communicate "offline" with less chance of mass surveillance. 
Firechat was used for this reason during the umbrella revolution in Hong Kong for democracy and free speach.

##### usercase2: travel/mass gatherings
If you are travelling (to a country where you don't have a mobile plan or in a place without coverage (plane or underground train)) you can use local mesh-network messaging to contact people and to find people in the crowd of a festival etc. 

This would give great convenience, privacy, communication redundancy and save on you money on your mobile plan.

**Comment by moxie0** [comment]
thanks but we're not going to do this
