### ISSUE TITLE
voice calls not working when routing through Orbot

### ISSUE THREAD

**Issue by Iommala** [WhisperSystems/Signal-Android#5506]
**Device:** Nexus 5
**Android version:** 6.0.1
**Signal version:** 3.15.2

Routing Signal through Orbot (Tor network). Everything works fine, except for voice calls. Upon trying to call someone else on Signal, Signal will ring twice, then return "Network failed!".

**Comment by haffenloher** [comment]
This is not a Signal bug; Tor simply doesn't support UDP.
