### ISSUE TITLE
Your incoming random UDP port for audio makes the port unavailable under router's NAT

### ISSUE THREAD

**Issue by ache** [WhisperSystems/Signal-Android#5509]
### Bug description
Since you make incoming UDP port for audio random and don't implement UPnP to open hole in the router for it, it becomes unavailable under router's NAT. Please add an option to change this port to the user-supplied value (to allow open router hole manually) or implement UPnP (better).

### Steps to reproduce

I call someone or someone calls me.

**Actual result:** 

I can't hear other side, other side hears me well.

**Expected result:** 

I can.

### Device info
**Device:** Nexus 5
**Android version:** 6.0.1
**Signal version:** 3.15.2

**Comment by Dyras** [comment]
I think this is exactly why a friend of mine can't hear me, at all. So I can confirm this on a Moto G 2015 calling an Xperia Z3

**Comment by 2-4601** [comment]
AFAIK, calling uses TURN relays. So you only need to be able to make outgoing UDP connections to the internet (the relay) and not block the incoming traffic to the selected UDP port. In other words, don't block UDP.
http://support.whispersystems.org/hc/en-us/articles/213697218

**Comment by ache** [comment]
> you only need to be able to make outgoing UDP connections

There is no problem with outgoing traffic, it is already allowed.
> and not block the incoming traffic to the selected UDP port

Nobody knows which port is selected by Signal since it is random. The router must know exactly to which device on the LAN map incoming port to. It impossible to map when no rules (router holes) describes where. Placing smartphone into DMZ make things worse since _all_ unrecognized external traffic will pass to it eating battery at least.

**Comment by 2-4601** [comment]
> Nobody knows which port is selected by Signal since it is random. The router must know exactly to which device on the LAN map incoming port to.

Your Signal client knows and your router's NAT will know when Signal makes the connection. That's what NAT is supposed to do. You don't need to do any manual mapping (port forwarding). Sounds like your NAT is not working correctly. Or UDP in general is blocked. Please ensure that you are not blocking any UDP traffic.

Also note, that the issue might be on the caller's side.

**Comment by ache** [comment]
> That's what NAT is supposed to do.

Router may detect outgoing traffic for some port and map incoming traffic to it to the same device afterwards. But somehow it is not happens for Signal.

> Sounds like your NAT is not working correctly. 

I doubt. It works for VOIP clients, Viber, WhatsApp, Skype and Facebook Messenger audio calls. Only Signal is not working so far. VOIP clients use incoming UDP for sure, don't know about others.

> Or UDP in general is blocked.

I don't specially block anything, only allow single ports for programs which can't do it themselves via UPnP.

> Also note, that the issue might be on the caller's side.

I can't test right now. Other side uses internet from its mobile provider without any NAT and can hear me which means that his mobile provider does not block UDP in general.

**Comment by 2-4601** [comment]
Please provide a [debug log](https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports#how-to-capture-debug-log) right after a failed call.
Also ensure that you are not using any firewall apps or network blocking functionality on your Android device.

It would also help if you could try calls in different networks with different people.

**Comment by ache** [comment]
Ok. It will take some time to get in touch - I'll report when it will be done. I have only one Signal correspondent so far, but I can try my mobile provider internet to exclude NAT and see what happens. I don't have any firewall, network blocking or active VPN in my Android - they usually damage VOIP calls.

**Comment by ache** [comment]
Good news: this bug is not related to the NAT at all, since I can reproduce it with my mobile provider internet too, sorry for the wrong guess, so this topic probably need to be closed and new one started with steps to reproduce preserved and details below, I am not sure.
Bad news: the bug still present. Details about other side: Sony Xperia, Android 4.4.4 (perhaps Signal not works well with old Android, I see lots of errors in the debug log below).

Debug logs. From my side: https://gist.github.com/anonymous/635f8b0027451cb9e0a41ebda2b50add
from other side: https://gist.github.com/anonymous/19a83e8292919a40e49fff6e5ed2a8ff
I also notice occasional  crashes on other side during the calls, sent as reports using Google Play standard mechanism.

**Comment by 2-4601** [comment]
Probably more clear to open a new issue.
Similar issues where the other party can't hear the other: #4955, #5060. Can't tell if exactly duplicate or not.
