### ISSUE TITLE
Option to send my location with messages

### ISSUE THREAD

**Issue by altring** [WhisperSystems/Signal-Android#5510]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I want to know where my kid is. 
It would be amazing if there will be an option for each group/contact "Send my location info to this contact/group". By checking this option Signal will send info about location with messages and the person who receives the message will see a small marker right after the text/image/content of message.
User clicks on it and google map opens showing the location.
I am not sure if it's good to send info with every message (and not needed i believe!) so let it send info with every 10th message starting from the first. "Starting from the first" I also mean if time interval from the last message is more than 1 min send the location. 

### Screenshots
How it may looks like:

![2016-05-24_220755](https://cloud.githubusercontent.com/assets/3490663/15516658/75785d86-21fc-11e6-99be-b2a9187b2e60.png)

**Comment by 2-4601** [comment]
You can already send your location. Open the attachment drawer by tapping the blue paper clip icon and then choose location.

**Comment by altring** [comment]
I want this to done automatically
I want to know where my family members are when they are sending.

**Comment by johanw666** [comment]
Do your family members want this too? I think this is not something the average Signal user wants, not even as opt-in.

**Comment by moxie0** [comment]
thanks but we're not going to do this
