### ISSUE TITLE
I can't hear other side, other side hears me well.

### ISSUE THREAD

**Issue by ache** [WhisperSystems/Signal-Android#5513]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

It happens both with LAN WiFi and internet from mobile provider. It happens independently of who initiates the call. Code words are shown normally on both screens.

Details about other side: Sony Xperia T3, Android 4.4.4. Perhaps Signal not works well with old Android, I see lots of errors in the other side debug log, see below.
### Steps to reproduce

Just place a call, from which side does not matter.

**Actual result:** I can't hear other side, but other side can hear me.
**Expected result:** I can.
### Device info

**Device:** Nexus 5
**Android version:** 6.0.1
**Signal version:** 3.15.2
### Link to debug log

From my side: https://gist.github.com/anonymous/635f8b0027451cb9e0a41ebda2b50add
From other side: https://gist.github.com/anonymous/19a83e8292919a40e49fff6e5ed2a8ff

**Comment by 2-4601** [comment]
Closing as old RedPhone issue.

**Comment by ache** [comment]
This issue still active.
