### ISSUE TITLE
Killing Signal when lock with passphrase is enabled should lock Signal.

### ISSUE THREAD

**Issue by jain-ruchi** [WhisperSystems/Signal-Android#5514]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Killing Signal when lock with passphrase is enabled should autolock Signal. Instead Signal stays unlocked until reopening app and locking manually or after timeout interval passes.

### Device info
**Device:** Samsung Galaxy S4
**Android version:** 4.4.4.
**Signal version:** 3.15.2

**Comment by moxie0** [comment]
What do you mean by "killing signal?"

**Comment by johanw666** [comment]
Settings - Apps - Signal - Force stop doesn't show this behaviour here (Android 4.4, Signal 3.16.0): restarting requires me to re-enter the password.

**Comment by scienmind** [comment]
I think @jain-ruchi means "swiping away" from the "recent apps".

**Comment by jain-ruchi** [comment]
@moxie0 @johanw666 yeah I mean what @scienmind said

**Comment by moxie0** [comment]
Oh I see, thanks but I don't think we're going to do that.  Swiping an app out of the recents history doesn't actually kill the app, and we already have the quick lock on the persistent notification.
