### ISSUE TITLE
Message shown in status bar with enabled option "Display in notifications: Name only"

### ISSUE THREAD

**Issue by hlorenz** [WhisperSystems/Signal-Android#5517]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The option "Name only" in the notification settings under "Display in notifications" is enabled.
If you only receive messages from one person this works as intended. But if you have an unread message from one person and receive a new message from another person, the text of the second message is shown in the status bar of the phone.

### Steps to reproduce
- Change the notification settings under Notifications > Display in notifications to Name only
- Receive message from one person (do not read the message!)
- Receive message from another person

**Actual result:** The message from the second person should appear as "New message" in the status bar of the phone
**Expected result:** The actual message appears

### Device info

**Device:** Fairphone 1U
**Android version:** 4.2.2
**Signal version:** 3.16.0

### Link to debug log
https://gist.github.com/anonymous/b314d9bf5fb0184386839b471e801f1e

**Comment by 2-4601** [comment]
Unable to reproduce on Nexus 4, stock 5.1.1, Signal 3.16.0

**Comment by hlorenz** [comment]
I don't know if i described it clearly enough. You have to actually look at the screen while receiving the message / the notification in the status bar. Afterwards it says "New message", but while receiving the message text appears in the status bar.

**Comment by 2-4601** [comment]
Tried again, still cannot reproduce.
Perhaps because in Lollipop notifications don't appear in the system status bar?

**Comment by hlorenz** [comment]
Yeah, I just tried to reproduce it with a friend with Lollipop and it also works normally. Maybe this only affects Android 4..

**Comment by 2-4601** [comment]
I can reproduce this on Android 4.0.4.

**Comment by mawed** [comment]
I experience this sometimes on 4.2.2

**Comment by FeuRenard** [comment]
I can reproduce this on Android 4.4.4.
