### ISSUE TITLE
How should we verify the self-signed certificate used for APK signing?

### ISSUE THREAD

**Issue by martin-cs** [WhisperSystems/Signal-Android#5526]
The APK distributed by the Google Play store is signed with a self-signed certificate.  Is the public key / hash of this available anywhere / via any trusted route?  Thanks

**Comment by nrizzio** [comment]
This isn't a discussion forum. Please read the issue template and follow it.

https://whispersystems.discoursehosting.net is an appropriate place for you to ask your question.
