### ISSUE TITLE
Feature: add option to enforce signal as default sms app

### ISSUE THREAD

**Issue by geekpete** [WhisperSystems/Signal-Android#5527]
I'm on MIUI OS (Xiaomi) and it continually flips default sms app back to the stock one without me knowing.

I find out when an sms comes in and lands in the stock message app.

Would be great to enable a setting in signal that enforces setting signal as default message/sms app by frequently checking and resetting it if it gets changed. This might be a nice default setting also?

**Comment by johanw666** [comment]
You probably need root for that, and if you have root you can also disable or remove the stock sms app.

**Comment by moxie0** [comment]
seems like a rom bug

**Comment by geekpete** [comment]
Probably more of a feature than a bug ;)

But all good, I should be a super edge case.
