### ISSUE TITLE
Disable "Screen security" by default

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/Signal-Android#5529]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Feature description

It's quite common to see non-passphrase users wonder why screenshots in Signal don't work. It probably doesn't make sense to have **Screen security** enabled by default for them.
For passphrase users it makes sense.

One option would be to remove the feature completely from settings and make it an implicit feature which depends on the passphrase setting.

> In https://github.com/WhisperSystems/Signal-Android/issues/1431#issuecomment-41502999 moxie0 wrote:
> [The Screen security feature i]s not designed to prevent screenshots, it's designed to notify the task manager that it shouldn't cache screenshots of conversations. The side effect is that it prevents screenshots.

**Comment by haffenloher** [comment]
Disabling it by default may be a good idea. But why the distinction between people using a passphrase and people who don't? I imagine that if the *Screen security* setting changes automagically when people change the passphrase setting, this could create additional confusion.

**Comment by johanw666** [comment]
> One option would be to remove the feature completely from settings and make it an implicit feature which depends on the passphrase setting.

That would making screenshots in case of issues complicated. Changing the default might work, but removing the option completely seems a bit overdone to me.

**Comment by moxie0** [comment]
I'm fine with disabling it by default.

**Comment by 2-4601** [comment]
> But why the distinction between people using a passphrase and people who don't?

Just thought that a passphrase user would not expect to see a screenshot of a conversation in the recents list after they have locked the app.

But I guess it's true that disabling the _Screen security_ for all users by default is the most straightforward way.

**Comment by 2-4601** [comment]
Was handled in
* ba849bce2c90287e820a3008e9dc9a1b14de19fc
* 5270dad78966f67c51d9aaa2a6747cf4f0259eba
