### ISSUE TITLE
Feature Request: Need phone + tablet support

### ISSUE THREAD

**Issue by RyanSinger** [WhisperSystems/Signal-Android#5532]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Pairing only works for desktop, not for additional android devices. Related to https://github.com/WhisperSystems/Signal-Android/issues/5102 and https://github.com/WhisperSystems/Signal-Android/issues/614
### Steps to reproduce
- Click Settings
- Click linked devices
- Click the addition sign
- Can't add a tablet

**Actual result:** No ability to add a tablet
**Expected result:** I should be able to message on my tablet just like my phone and desktop.

**Comment by 2-4601** [comment]
Thanks, this feature is not yet ready but the issues you mentioned are used to track it.
