### ISSUE TITLE
Messages (delivery receipts?) are slow to deliver

### ISSUE THREAD

**Issue by strugee** [WhisperSystems/Signal-Android#5536]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

For some reason, all messages delivered through Signal are slow to deliver. I say this based on the checkmark (sent/delivered) indicator, but also based on manually talking to a contact to figure out when things came through.

I find that when this happens, asking the other person to send me a Signal message will force all undelivered messages to go through. In this case, calling through Signal doesn't work - it's just stuck at dialing forever (although it's _possible_, though unlikely, that I just didn't wait long enough). However, once pending messages are "flushed", calling starts working again.

This happens both on Signal Android and a linked Signal Desktop. I've also seen it happen when contacting contacts on both Android and iOS. At least one of the contacts I've seen this with has been on Signal for months, and at least one contact I've seen this with had literally _just_ installed and registered. When this doesn't happen, I find that messages will sometimes take a couple seconds to go through, but before I started running into this issue (which was a week or two ago), messages would generally go through almost instantly.

All contacts that I'm sending messages to are in the same geographic area, so in theory we should all be contacting the same server region (in case there servers run in e.g. multiple AWS regions).

### Device info

**Device:** Nexus 6P
**Android version:** CyanogenMod 13.0-20160604-NIGHTLY-angler, based on Android 6.0.1
**Signal version:** 3.16.0, installed via the Google Play Store

gapps was installed via the [OpenGApps nano package][1]. I'm on Play Store `6.5.08.D-all [0] 2792142`, Google Play Services `9.0.83 (440-121911109)`.

The problem seems to occur regardless of whether or not I'm on a WiFi network. I called my contact over the cell network - he was on WiFi while I was seeing the issue, and said that both my test messages went through when he disconnected (although I only saw a delivery receipt on one of them - possibly a different bug).

### Link to debug log

https://gist.github.com/7e71ea3ce262b82d798d5b5bdd40b49b

 [1]: https://github.com/opengapps/opengapps/wiki/Nano-Package

**Comment by moxie0** [comment]
Someone involved has a bad gapps install. If you're running CM, that's likely the culprit.

**Comment by strugee** [comment]
@moxie0 as I said, I don't think so. It can't be the other contact, because I've seen this when sending to an iOS device. And it can't be me, since I've seen this in Signal Desktop. (Unless Signal Desktop messages are routed through the phone app? But AFAICT this isn't the case.)
