### ISSUE TITLE
android N - Signal is not a dialer app

### ISSUE THREAD

**Issue by diakopter** [WhisperSystems/Signal-Android#5544]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Signal does not get registered as a Dialer app in Android N, and so the "Signal call" option doesn't appear in any Contact card, and secure calls cannot be initiated either from the Signal app or from Contacts app.
### Steps to reproduce
- use Android N June 2016 update

**Actual result:** no way to initiate secure calls
**Expected result:** able to initiate secure calls
### Device info

**Device:** Nextus 6P
**Android version:** N June 2016
**Signal version:** 3.16.0

**Comment by merge** [comment]
I cannot confirm this. In december 2016's android 7.1.1 I see Signal in my contacts and can call from Signal itself

**Comment by diakopter** [comment]
Yes, the latest version works. This bug was filed 7 months ago
