### ISSUE TITLE
Please consider supporting Firefox

### ISSUE THREAD

**Issue by fsignal** [WhisperSystems/Signal-Android#5546]
Signal is an open source application meant to protect users' privacy. Firefox is an open source browser with privacy as one of its main goals. It doesn't feel right to use Signal on Chrome, a closed-source browser.

Please consider supporting Firefox.

**Comment by nrizzio** [comment]
This isn't even the right repository, and there's already an issue open for this.

**Comment by fsignal** [comment]
Sorry.

**Comment by inoas** [comment]
Ref https://github.com/signalapp/Signal-iOS/issues/4243
