### ISSUE TITLE
Signal asks for access to everything

### ISSUE THREAD

**Issue by snakecharmer1024** [WhisperSystems/Signal-Android#5557]
This is a credibility issue. I try to get everyone to use Signal, but twice in a row now when I try to get Android users (i have iOS) to do it, they are fine until Signal requires access to everything. Then I look like a liar, a dummy, or both. 

For example, why does Signal need access to the calendar? Just because it's open source isn't enough for many people to trust it if their phone tells them it wants to see everything.

Is there a way to let users opt out of some features so they can decide what the appropriate level of access is?

**Comment by KarolTrzeszczkowski** [comment]
Hi! See this first:
http://support.whispersystems.org/hc/en-us/articles/212535858-What-are-all-these-permissions-

**Comment by 2-4601** [comment]
And support for Marshmallow permissions is tracked here: #3983
