### ISSUE TITLE
Provider reusing old phone number leads to some fun

### ISSUE THREAD

**Issue by lifebarier** [WhisperSystems/Signal-Android#5558]
Changing phone number after verifying old phone number can lead to interesting stuff if provider decides to reuse old phone number.
NOTE: This might not be an issue with app or might not be an issue at all but something to keep in mind, or maybe it is known (quick google returned nothing similar). Or maybe something can be done with protocol or by making app verify SIM_card/phone_number did not change. No idea. Just putting this here.

Steps to reproduce
1. Register and verify current phone number with signal.
2. Change phone number. (get new sim card in my case).
2.1. Forget to register and verify your new phone number with signal (because it still works! I still get messages from my signal contacts...).
3. Get old phone number blocked and reused by provider. (someone else now has your old phone number) 
(I think this could be easily reproduced without providers reusing your phone number and just putting sim card into some other phone)
(TO RESEARCH: what would happen if new owner of my old phone number also registered that phone number with signal? Would I receive his/her messages assuming I did not change my signal phone number?)

Actual result: Other people can still send SMS to you by using your old phone number while using signal. Using not_signal to send messages sends them to person who now has your old phone number. Calling them via signal (icon was of not encrypted call) calls new owner of your old phone number (awkward conversation...).

Expected result: No idea. Check if user has not changed their phone number to prevent such fun incidents?

**Comment by 2-4601** [comment]
Thanks, this is a known issue / design decision.
The person who registers Signal with your old number will get the messages sent to that number. The senders will get a warning that recipient has reinstalled Signal.

AFAIK WhatsApp has the same issue.
