### ISSUE TITLE
Sending regular SMS to a Signal user

### ISSUE THREAD

**Issue by davux** [WhisperSystems/Signal-Android#5563]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I can't send a regular SMS to a contact with whom I normally use Signal. This is sometimes necessary if a contact exhausted their data plan for example.

The only workaround I've found is to make the regular SMS app the default app,  send the message, then set the default back to Signal.

### Steps to reproduce
- Make sure Signal is the default app for SMS
- Look up the contact in the address book
- Click in the message icon next to the number
- Compose a message

**Actual result:** Message is sent through the Signal protocok, and there is no way to change that behaviour. The contact doesn't get it if they don't have an internet connection on their device 
**Expected result:** There would be a way to switch temporarily to regular messages for the contact. Not sure of the exact optimal behaviour in terms of UX, but it should be technically possible to send an SMS.

**Comment by mateoeh** [comment]
Long-press the send button and you can choose to send SMS messages

**Comment by davux** [comment]
Thanks for the tip, @mateoeh! Very useful when you know it.

I think of it as an easter egg, though. One of the reasons is that the send button doesn't appear until you entered some content in the "Send Signal message" box (which is what you don't want to do), so I didn't even reach the step of having the button visible. And if I had, I'm fairly confident that it would never have occurred to me to try long-pressing on it.

I realise the use case is not the general use case, but it is not extremely improbable either. The feature is so well hidden to most users that it's nearly the same as missing.

**Comment by 2-4601** [comment]
You can also long-press the attachment button and it does the same thing.
And yes, switching to SMS is not the general use case :)

**Comment by davux** [comment]
Also, I realise that in Western Europe and in the US many people have illimited data plans, but in poorer countries such as Peru for example (where I live), it's very common to run out of megas, and then you inevitably have to fall back to regular SMS. Please don't assume your normal user is wealthy.

Maybe an idea would be to detect whether there's an internet connection available as the time of composing the message and do something clever? (e.g. changing the default, a dialog... not sure).

**Comment by FeuRenard** [comment]
#2285 adresses also the button. When it will be implemented, there could be an entry in the recipient preferences to activate SMS transport. That would improve discoverability.

**Comment by davux** [comment]
I agree, #2285 will most probably improve the UI. I'm fine with leaving this closed. Thanks @FeuRenard!
