### ISSUE TITLE
Message changed to insecure message (SMS) gets saved as secure message draft.

### ISSUE THREAD

**Issue by mawed** [WhisperSystems/Signal-Android#5565]
I have:
- [ x ] searched open and closed issues for duplicates
- [ x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When typing a message and changing the message protocol to insecure message (SMS) and leaving the conversation, the message is saved as draft. But when reopening the protocol is changed to signal messaged.

### Steps to reproduce
- Type message
- change to SMS transport
- leave conversation
- reenter conversation

**Actual result:** Draft is selected to signal protocol
**Expected result:** Draft should stay in selected and choosen protocol (here SMS)

### Device info
**Signal version:** 3.16.0

**Comment by FeuRenard** [comment]
This issue is related to #2285 and therefore should be closed.

**Comment by 2-4601** [comment]
Yeah, it's a general issue/feature of defaulting to Signal transport whenever the conversation is left.
