### ISSUE TITLE
the OtpCounterProvider.getOtpCounter always returns 1

### ISSUE THREAD

**Issue by skal1ozz** [WhisperSystems/Signal-Android#5569]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
In the /src/org/thoughtcrime/redphone/signaling/OtpCounterProvider.java
getOtpCounter always returns 1.

### Steps to reproduce
- open https://github.com/WhisperSystems/Signal-Android/blob/master/src/org/thoughtcrime/redphone/signaling/OtpCounterProvider.java
- take a look at the "getOtpCounter" and you will see that method returns 1 

**Actual result:** OTP doesn't work
**Expected result:** OTP should works.

**Comment by moxie0** [comment]
yes, this is being phased out
