### ISSUE TITLE
Panoramas suffer considerably from image compression

### ISSUE THREAD

**Issue by peterpanondrugs** [WhisperSystems/Signal-Android#5574]
I have:
- [x] searched open and closed issues for duplicates : "panorama"
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Sending a Panorama does crop the size / compress it to an unviewable picture. neither thumbnail nor picture when u open/save has a correct quality.
Funny thing is, that i got a panorama send from IOS, and quality was perfect after receiving.
### Steps to reproduce
- send attachment panorama picture
- see the quality / crop ...

**Actual result:** signal cropping or resizing the quality way to heavy.
**Expected result:** receiver or sender should see the sent panorama in full quality
### Screenshots

![fsdfsdfsd](https://cloud.githubusercontent.com/assets/8776733/16810676/2743aa3a-4925-11e6-8dc4-12702348af14.jpg)
### Device info

**Device:** samsung i9305
**Android version:** 6.0.1
**Signal version:** 3.16.0
### Link to debug log

https://gist.github.com/anonymous/3c649e2e6a1658ecc7a0c9b542b04f63

**Comment by 2-4601** [comment]
Same as #4958? (asking because you commented on that issue a while ago :)

**Comment by peterpanondrugs** [comment]
OMG! i hate this search. they should search for incl. text. 
Well since there is more! information here and a keyword. i'll leave it open, correct me if im wrong.

**Comment by 2-4601** [comment]
Essentially this is the same as #672. But panoramic pictures suffer the most from the compression because the horizontal resolution is so much bigger than the vertical resolution.
Leaving this open in the case that panoramas should be handled as a special case.

(Somewhat related  #4380.)

**Comment by Dyras** [comment]
@2-4601 My phone doesn't compress panoramas anywhere near this much, so I think this might be a phone specific problem

**Comment by peterpanondrugs** [comment]
My Panorama specs: 888x3456=3.1MP 90°
@Dyras But it does compress!? So i tried several phones, and all look the same. It could depend on resolution. Maybe u use a low MegaPixel format. ? If so try to send a high MP picture. 
Let us know what resolution u use.
