### ISSUE TITLE
Duplicate messages being received during standard TextSecure messaging (non group).

### ISSUE THREAD

**Issue by SamClarke2012** [WhisperSystems/Signal-Android#5579]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

In standard two device messaging (signal messages, not SMS), one user receives some messages twice, however the sender doesn't see the duplicate message in their history. The log shows that around the same time, the **MessageRetrievalService** logs a time-out, causing it to loop around for another go.  In reality both attempts seem to result in a message being rendered.
### Steps to reproduce
- Use two devices (Nexus 5 and Nexus 5x)
- Proceed to have a secured (TextSecure) conversation

**Actual result:** Nexus 5 receives some messages twice.
**Expected result:** Nexus 5 should receive exactly one message for each message the Nexus 5x sends to it.
### Device info

**Device:** LGE Nexus 5 (hammerhead)
**Android version:** 6.0.1 (2960889, MOB30P)
**Signal version:** Signal 3.16.0
### Link to debug log

https://gist.github.com/anonymous/177442603d179b543fc9ef6ac7c58ba3#file-cat-log-L229

**Comment by SamClarke2012** [comment]
**Update:**
It happened again, however this time the log seems a little more verbose regarding errors.

**Link to debug log**
https://gist.github.com/anonymous/b871ec65e3b5a5f8fd1214a7387fd3a4#file-cat-log-L61

**Comment by mantono** [comment]
I've had the same problem, all tough with regular SMS. Don't know if it is the same cause or for different reasons. See #1835, you can find my debug log there as well.

**Comment by ngharo** [comment]
Various people apart of my group chat experienced this multiple times but it was only happening when the sender received "failed to send to X people" or similar message.  It was if when pressing _retry_ on each contact the retry attempt went to all contacts.

If this is far enough off from original issue lemme know

**Comment by szhang1000** [comment]
I received this issue tonight, when messaging a friend who did not have Signal. I'm on Signal version 3.19.1, on a Motorola G phone [Android 5.1] The issue only occurred when attempting to send messages longer than the 160 character single-text-message limit [which appears to have been[ an issue]([url]https://github.com/WhisperSystems/Signal-Android/issues/387(url)) in the past as well]; Signal displayed "Not delivered" and "Failed to send."
