### ISSUE TITLE
Feature: Delete encrypted database with deletion passphrase

### ISSUE THREAD

**Issue by volviq** [WhisperSystems/Signal-Android#5581]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

Currently it is possible to retry and to guess the passphrase for an encrypted database.
In case a person is enforced to reveal the data, after some time and multiple threats one may decide to use the correct passphrase and the data gets decrypted although it may contain sensible information.

It might be useful to be able to set a deletion passphrase which causes creates an empty new database or a sane version with some dummy messages and deletes the actual messages.

### Steps to reproduce
This is not a bug report but a features request. 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
The feature does not exist yet.
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Ideal steps:

- In Settings -> privacy, in case a passphrase is set, provide a field "set deletion passphrase".
- It should not be visible if such a passphrase is enabled. Old ones may not be overwritten.
- If this passphrase is entered to access signal, all data shall be deleted.

### Concerns: 
Professionals  who know about this feature would first backup all data, so this feature won't provide full security of the data. It is assumed that in most cases the technical competence and knowledge about app specifics of enforcement is limited.

**Comment by moxie0** [comment]
thanks but we're not going to do this
