### ISSUE TITLE
Signal freezes on Android 7 Preview 5 when trying to add an attachment

### ISSUE THREAD

**Issue by sbaum** [WhisperSystems/Signal-Android#5583]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal was working without problems on latest Android 6.0.1 on my Nexus 6. Today I've "dirty" flashed the latest Android 7.0 Preview 5 image. I have wiped the cache partition afterwards. Signal is working on Android 7 Preview 5, but when I click the paperclip button to add an attachment, Signal freezes immediately. The blinking cursor in the text input field stops blinking and the app does not respond to any further input. After closing the app by swiping it off the recent apps list, Signal can be opened again. The same happens if I select the respective menu item instead of clicking the paperclip button.

### Steps to reproduce
- Open Signal app.
- Enter a conversation.
- Click on paperclip button or select respective menu item to add an attachment to the message.

**Actual result:** Signal hangs/freezes immediately. The cursor stops blinking and the app does not respond to any further input.
**Expected result:** The "attachment selection dialogue" is shown, so I can select an attachment to be added to the message.

### Device info
**Device:** Motorola Nexus 6
**Android version:** 7.0 Preview 5 (NPD90G)
**Signal version:** 3.16.0

### Link to debug log
https://gist.github.com/anonymous/a8c508d1b94d8be848149cd9025fccda

**Comment by timmylamoule** [comment]
Hello,
Got the same issue with Nexus 5X on Android N Developer Preview 5. Strangely, it worked great on Preview 4.

Link to debug log : 
https://gist.github.com/anonymous/063dbd3511bf6ced12d3b1c9776d3297

**Comment by d4l3k** [comment]
This is also an issue on my Nexus 6P after updating to Android N Developer Preview 5.

**Comment by arafey** [comment]
I have the same problem on Android 7 Preview 5 (NPD90G) on a Nexus 6.

**Comment by thetaeo** [comment]
I have a similar problem on my Nexus 5x running preview 5, but it also crashes when using the share intent.
Debug log: https://gist.github.com/anonymous/19a1e8c331386530457b8eba4ca146f6

**Comment by d4l3k** [comment]
@moxie0 Any updates on this? Seems like a major issue when Android N is released in a month.

**Comment by arafey** [comment]
@d4l3k It looks like commit fe4c57d should fix the problem. 
Does Signal have a release schedule for commits to the master branch?

**Comment by element515** [comment]
Is there any fix coming for this? I've basically stopped using Signal because it crashes any time I try to attach something.

**Comment by d4l3k** [comment]
Android Nougat launched today and this still remains an issue.

https://android-developers.blogspot.com/2016/08/taking-final-wrapper-off-of-nougat.html
