### ISSUE TITLE
Limit contact access to user-chosen contact group

### ISSUE THREAD

**Issue by retorquere** [WhisperSystems/Signal-Android#5588]
I'd prefer not to share my Signal availability to all my contacts, but rather to a contact group I can select. I recognize this is perhaps a niche request, I'd also be helped with pointers how I can program this myself in a private build.

I have contacted support@whispersystems.org and they said they couldn't help me, so it looks like that channel isn't the right path for feature requests or tips on how to get into the code base.

I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal uses all my system contacts when looking for people to contact/sending the list of number hashes to the signal servers for discovery. I'd prefer not to announce my usage of Signal to everyone in my contacts list but rather to a specific contact group.

### Steps to reproduce
- Sign up for Signal
- All my system contacts are notified I use Signal

**Actual result:** All my system contacts get notified I use Signal if they also have Signal installed
**Expected result:** Only those contacts which are in a special selected group (Let's say "Signal") should get that notification

**Comment by zoff99** [comment]
thats easy, use my fork:

https://github.com/zoff99/Signal-Android/tree/z_only_local_contacts

the contacts you want signal to know about:
*) add a 2nd phonenumber to those contacts in the form of
<pre>###+3916373248</pre>

prefix with 3 \# char.

**Comment by retorquere** [comment]
@zoff99 super, thanks! It looks like you're keeping your fork in sync with this repo, so it should be easy enough to verify what changes have been made.

Issue tracking is not enabled on your fork -- are you open to a pull request that would do group filtering?

**Comment by zoff99** [comment]
moxi will never put this into the main app

**Comment by zoff99** [comment]
but sure u can do a PR

**Comment by retorquere** [comment]
When you say "this", do you mean your particular change, or anything that voluntarily limits address book access? I'm ok either way (don't mind running a private build), but I'm curious why a privacy-minded app would object to such a feature.

**Comment by zoff99** [comment]
you can try my build here: https://circleci.com/gh/zoff99/Signal-Android/20#artifacts
!! at your own risk !!
!! at your own risk !!
