### ISSUE TITLE
Application not "compatible" with Nexus 9 LTE

### ISSUE THREAD

**Issue by josteink** [WhisperSystems/Signal-Android#5603]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

Unable to install Signal from Play Store. Play Store claims application is incompatible.

### Steps to reproduce
- Start Play Store on Nexus 9 LTE device.
- Search for signal sms in the Play Store.
- Select the application among the results.

**Actual result:** No install button. Play Store claims device is incompatible.
**Expected result:** App to be compatible. It runs fine on a Nexus 5X with the same version of Android.

### Device info
**Device:** HTC Nexus 9 LTE
**Android version:** 7.0 DP5
**Signal version:** N/A

**Comment by FeuRenard** [comment]
Tablets are not supported #614.

**Comment by Trolldemorted** [comment]
not officially supported. In #614 it is mentioned that deploying the APK works, but with odd side effects.

**Comment by josteink** [comment]
In that case... Anyone know a reputable source to fetch the APK from?

My phone are currently running Android N, and I can't decrypt that one in recovery to pull the file myself...

**Comment by nrizzio** [comment]
@jostling I'd compile it from the sources yourself.

**Comment by dreng** [comment]
@josteink Here's what I did:
1. Installed Signal from Play Store on my mobile phone
2. Used ES File Explorer (similar apps should do the trick as well) to save the APK
3. Transferred APK to my tablet and installed the APK
No need to trust anybody but yourself in this case

**Comment by josteink** [comment]
@dreng That would require rooting the device, and I can't bother doing that right now.

@nrizzio I just did and it was fairly simple really. Thanks for the nudge.

Closing issue for now.
