### ISSUE TITLE
Format "Secure session reset" as conversation update

### ISSUE THREAD

**Issue by FeuRenard** [WhisperSystems/Signal-Android#5605]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The information that the session was reset is rendered like an outgoing or an incoming message. But it should be displayed as a conversation update (e.g. "xxx joined Signal. Say Hey...").

### Steps to reproduce
- go to a Signal conversation
- open the menu
- tap on "reset secure session"

**Actual result:** A message bubble appears like if I sent something to my chat partner. It is saying "Secure session reset."
**Expected result:** A conversation update message (no bubble) appears saying the same thing and who initiated the reset.

### Screenshots
![screenshot_2016-08-07-13-48-18](https://cloud.githubusercontent.com/assets/16167751/17462307/185b747a-5ca9-11e6-8cd0-e808bbf613db.png)

### Device info
**Device:** Fairphone 2
**Android version:** 5.1.1
**Signal version:** 3.16.0

**Comment by cascheberg** [comment]
Changing the code should be easy, but you'll need an according icon. Maybe the icons `ic_lock` or `ic_refresh` could be used, but they are not available in grey.

**Comment by FeuRenard** [comment]
We don't need a grey icon. In a reply to a PR it was [stated](https://github.com/WhisperSystems/Signal-Android/pull/5457#issuecomment-243961365):
> [W]e're generally trying to go with the technique of using white assets and tinting them rather than having separate assets for light and dark.

And in recent commits there are white assets used that are only presented in grey:

- https://github.com/WhisperSystems/Signal-Android/pull/5646/commits/c19696619acb8fc6b8e66dd203d6b4669bad8820#diff-e97e1d300dfe0a0fb5abc9eef65b335aR129
- https://github.com/WhisperSystems/Signal-Android/commit/d7e4928f22e0a0e123eadd7442c32296b6eb6fad#diff-e97e1d300dfe0a0fb5abc9eef65b335aR105
