### ISSUE TITLE
Secure Call network failure, no debug report

### ISSUE THREAD

**Issue by rene0720** [WhisperSystems/Signal-Android#5607]
I have:
[x] searched open and closed issues for duplicates
[x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

**Bug description:**
When I try to call another signal user I get instantly a network failure. I can't post a debug log, because I get no one. I've no problem to write encrypted messages.
Logcat: https://dl.dropboxusercontent.com/u/17888900/log

I've cleared all data, cache, reinstalled it doesn't work. 

**Actual result:** 
Can't call another signal user.

**Expected result:** 
Get an encrypted connection to another signal user.

**Device info:**
Device: Huawei P8 Lite
Android version: stock 5.0.1
Signal version: 3.16.1

**App state**
Signal messages and calls registered, SMS enabled, passphrase enabled

**Comment by georgeowell** [comment]
Can confirm this is affecting all iOS to Android calls. Not able to test iOS to iOS calls unfortunately. 

Could be server problem?

**Comment by 2-4601** [comment]
@rene0720 Have you tried this on other networks (wifi, cellular)?

**Comment by rene0720** [comment]
Sorry, it was my fault. I thought it's not the connection because another signal user told me he has the same problem, but this router blocks voip, this was the problem.
I still didn't get a debug report.

**Comment by riyapenn** [comment]
Closing as user reported it was not an issue with Signal.
