### ISSUE TITLE
identical symptoms to #5396 but different device

### ISSUE THREAD

**Issue by boroncw** [WhisperSystems/Signal-Android#5608]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
A duplicate MMS or "picture message" is received after a period of about 4 days.

### Steps to reproduce
reinstalled, had someone send another MMS message, received again 4 days later
removed app had someone send an MMS only received once

**Actual result:** Receive an MMS picture message.  4 days later receive the same message.  SMS working as normal with only 1 being delivered.
**Expected result:** Only expect to receive the message once.  Sender only ever has 1 sent notification.

### Device info

**Device:** Samsung Galaxy S7
**Android version:** 6.0.1
**Signal version:** 3.16.0

### Link to debug log
I've uninstalled the app as there were previous reports of the issue as a Signal only issue and no longer have the log available.

**Comment by 2-4601** [comment]
Thanks, #5396 is good for tracking this even if device is different.
