### ISSUE TITLE
"Your signal version is outdated"

### ISSUE THREAD

**Issue by char32** [WhisperSystems/Signal-Android#5609]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Starting from today the Signal expiration banner is shown which tells me that signal will expire in 9 days, starting form today.
This is due to the lack of updates in the PlayStore.

### Steps to reproduce
- start Signal
-> blue banner is displayed at the top

**Actual result:** blue banner is displayed at the top
**Expected result:** Signal should be updated at the playstore, and shouldn't show the message if the most current version is used

### Device info

**Device:** HTC One M8
**Android version:** 6.0
**Signal version:** 3.16.0

**Comment by s0r00t** [comment]
Can confirm this, Nexus 5 on latest CM13 and Play Store Signal.

**Comment by real-or-random** [comment]
Same here (in beta channel). Samsung Galaxy S4, CM.

**Comment by dns2utf8** [comment]
Same on FairPhone 2, Android 5.1

**Comment by aibaraiduas** [comment]
Same for me, stock Android on a Nexus 5.

**Comment by thirtythreeforty** [comment]
Would it be better for the client to ask the server every so often if its build number is still considered "fresh"?  This would allow the server to force people to update known-vulnerable builds (which is what I believe this reminder was originally for), while still allowing builds older than the 90 day window to remain "fresh" if no updates have been published, as is the case now.

**Comment by Maltimore** [comment]
Same here, Moto G3, Android 6

**Comment by kofalt** [comment]
Because I was curious: the trigger appears to be in [OutdatedBuildReminder](https://github.com/WhisperSystems/Signal-Android/blob/975ae735dc4617410681a02e4fe9a9a492417ef8/src/org/thoughtcrime/securesms/components/reminder/OutdatedBuildReminder.java), which references a [util method](https://github.com/WhisperSystems/Signal-Android/blob/975ae735dc4617410681a02e4fe9a9a492417ef8/src/org/thoughtcrime/securesms/util/Util.java#L340-L343) that tracks 90 days from the build timestamp. In addition to [displaying the notification](https://github.com/WhisperSystems/Signal-Android/blob/975ae735dc4617410681a02e4fe9a9a492417ef8/src/org/thoughtcrime/securesms/ConversationListFragment.java#L176-L177), it appears that it might not [send messages](https://github.com/WhisperSystems/Signal-Android/blob/975ae735dc4617410681a02e4fe9a9a492417ef8/src/org/thoughtcrime/securesms/jobs/SendJob.java#L36-L44) after expiry. 

As it currently stands, it seems that TextSecure must be updated every few months.

**Comment by slpopejoy** [comment]
Me too, Samsung Galaxy S7.

It might be nice to confirm @kofalt's comment above, will my app really stop working in 9 days? Scary.

**Comment by Trolldemorted** [comment]
@slpopejoy if it does, you can either build it yourself or install an apk that was built more recently.

**Comment by slpopejoy** [comment]
@Trolldemorted thanks, but will that work for the same version? 3.16.0 is the latest I could find an apk for, and dated May 24. 

There probably needs to be a notice on the support site or something with user-friendly workarounds provided if this is not resolved soon, no?

**Comment by Trolldemorted** [comment]
@slpopejoy i think so, as signal compares the build timestamp. My self-built signal is not complaining, i know this problem only because of this issue and [this ](https://whispersystems.discoursehosting.net/t/new-signal-for-3-16-0-expires/447) thread in the unofficial forum.

**Comment by roadkillazpartybird** [comment]
Same issue on Nexus 6 Android 6.0. I wonder what happens when the timer runs out...

**Comment by jnathan** [comment]
Looks like the UI change went in with #4322.  There's obviously a little time, but with #5561 having been rejected, there may be some users with some serious rage if this isn't dealt with.

**Comment by Dyras** [comment]
@roadkillazpartybird If it runs out the app will essentially stop working. However, I'm guessing @moxie0 will respond in time with a new update to fix this issue. If he doesn't, well.... I have a feeling WhatsApp will have a spike of signups in 10 days.

He's probably either 1. Out on his boat 2. Helping Google fix Allo for its release at the end of the summer.

**Comment by d9h02f** [comment]
Good job, @moxie0! This really makes Signal easy to use!

**Comment by ferranti** [comment]
Wow, they're deprecating signal on Android 6 too? I'm on 4.2.2 so I get my OS not being supported but 6? Really?

On August 8, 2016 4:52:25 PM MDT, Dyras <notifications@github.com> wrote:
>@roadkillazpartybird If it runs out the app will essentially stop
>working. However, I'm guessing @moxie0 will respond in time with a new
>update to fix this issue. If he doesn't, well.... I have a feeling
>WhatsApp will have a spike of signups in 10 days.
>
>He's probably either 1. Out on his boat 2. Helping Google fix Allo for
>its release at the end of the summer.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/WhisperSystems/Signal-Android/issues/5609#issuecomment-238402125

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Dyras** [comment]
@ferranti Uh... Source for that statement? They're not intentionally deprecating anything, he's probably busy with something else. Or he's on summer vacation.

**Comment by ferranti** [comment]
Well the play store doesn't have an update available so I assumed my OS wasn't gonna be supported. So does that mean there will be an update eventually?  If they're on vacation or busy it seems they should not have automated this system. 

On August 8, 2016 4:56:48 PM MDT, Dyras <notifications@github.com> wrote:
>@ferranti Uh... Source for that statement? They're not intentionally
>deprecating anything, he's probably busy with something else. Or he's
>on summer vacation.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/WhisperSystems/Signal-Android/issues/5609#issuecomment-238402920

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Chaseabbott** [comment]
Verizon HTC One M9 w/Android 6 Marshmallow.  Expiry message confirmed.

**Comment by Dyras** [comment]
@ferranti This system was put into place to prevent people from using a 3 year old build, causing all kinds of compatibility problems. I don't think they ever intended for this to happen. Remember that since Jake McGinty left, Moxie has been running the development all by himself. On top of that he has been helping WhatsApp and Google Allo, since his end game goal isn't for Signal to conquer the universe, but instead it's to make encryption simple. 
Moxie has made plenty of strange decisions over the years, but he's only human. Personally I think he should put more effort into making Signal more grandma-friendly with updated emojis, for example. But hey, it's his project and the closest thing to a friendship I have with him is when he responds to my issues. So yeah, let's just wait for an official response, shall we?

We will be getting an update, just wait. He's not abandoning the whole project just like that, I'll bet my stones on it.

**Comment by im-grey** [comment]
I and several friends all have this bug as well.

**Comment by bmatsunaga** [comment]
Message also present on Nexus 6p, 6.0.1.

**Comment by ferranti** [comment]
I didn't know we lost a developer. I'd be happy to help in any way I can. I'm no iOS dev but I could probably help with the android side of the world. Would have to bone up on my Java some more. Been a while since I coded in Java.


On August 8, 2016 5:06:05 PM MDT, Dyras <notifications@github.com> wrote:
>@ferranti This system was put into place to prevent people from using a
>3 year old build, causing all kinds of compatibility problems. I don't
>think they ever intended for this to happen. Remember that since Jake
>McGinty left, Moxie has been running the development all by himself. On
>top of that he has been helping WhatsApp and Google Allo, since his end
>game goal isn't for Signal to conquer the universe, but instead it's to
>make encryption simple. 
>Moxie has made plenty of strange decisions over the years, but he's
>only human. Personally I think he should put more effort into making
>Signal more grandma-friendly with updated emojis, for example. But hey,
>it's his project and the closest thing to a friendship I have with him
>is when he responds to my issues. So yeah, let's just wait for an
>official response, shall we?
>
>We will be getting an update, just wait. He's not abandoning the whole
>project just like that, I'll bet my stones on it.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/WhisperSystems/Signal-Android/issues/5609#issuecomment-238404579

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by fat-tire** [comment]
I see 48 pull requests sitting there.  Doesn't give much incentive to want to contribute if existing contributions aren't processed... hopefully though someone can come in to assist @moxie0 if he's short on time/resources.

**Comment by Dyras** [comment]
@ferranti @fat-tire Yeah, I wish more people worked on this project too. The problem, like always, is money. Having someone work 8 hours a day on an app isn't free. So if helping with the coding is out of the question, I'd suggest donating. https://freedom.press/bundle/encryption-tools-journalists

**Comment by Trolldemorted** [comment]
@Dyras There would be more people working on this project, if the pull requests would actually be declined or accepted, and not left uncommented for half a year.

OWS is trying to hire developers, so i guess money is not the primary problem but capable (or cheap) applicants are.

**Comment by im-grey** [comment]
What happens in 9 days? All my non-technical friends are spooked by this.

**Comment by johanw666** [comment]
In 9 days the official version of the app becomes unusable, even for sms.

**Comment by jeetpei** [comment]
Same for me  Nexus 6P

**Comment by rusvnc** [comment]
I am sure Moxie is also seeing this on his own phone and it will be fixed soon. I don't really understand the point of drive-by sniping at OWS developers because of this.

**Comment by ardrigh** [comment]
Have been using TextSecure for a long time before Signal, and it's the first time I have seen this message.

It would be less of a concern to non-technical users if the standard SMS function still worked after expiry, but Signal disables this also.

Hopefully the Google Play Store won't take long to push through a new build.

**Comment by im-grey** [comment]
>In 9 days the official version of the app becomes unusable, even for sms.

Oh no. So, do we have to use something else now?

**Comment by ElijahCaine** [comment]
I'm also getting this message.

(*Places two cents on table*) 
I think we would all appreciate some acknowledgement of the issue; something on the Google Play page for Signal that said something like:

*"We are working on the fixing the issue relate to Signal saying `Your Version of Signal is outdated` by doing X and Y. We are apologize for any confusion. You do not need to take action at this time."*

I'm not a writer, but something like that would really help.
Love the app, appreciate everything your team does. Keep it up.

**Comment by aliceriot** [comment]
looks like Moxie is on it: https://github.com/WhisperSystems/Signal-Android/commit/643da569ec77a1b88c54cd81d6f5b06c347ee0fb

**Comment by moxie0** [comment]
Making its way through the play store now

**Comment by kofalt** [comment]
Any thoughts for next time? Longer grace period, automatic dev reminder?

**Comment by mapguy109** [comment]
well at least there's no federation that would've slowed it down
