### ISSUE TITLE
Play Store: Your version of Signal is outdated

### ISSUE THREAD

**Issue by Fmstrat** [WhisperSystems/Signal-Android#5610]
I have:
- [ X ] searched open and closed issues for duplicates
- [ X ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When opening Signal from the Play Store, an "outdated' message is displayed.

### Steps to reproduce
- Install the latest version of Signal from the Play Store
- Open Signal

**Actual result:** A message is displayed about being outdated.
**Expected result:** No message, or a newer version in the Play Store.

### Screenshots

![screenshot_20160808-172658 2](https://cloud.githubusercontent.com/assets/971474/17497236/dc6ef414-5d8e-11e6-98ea-f4d85f6252c1.png)
![screenshot_20160808-172652 2](https://cloud.githubusercontent.com/assets/971474/17497238/e0f5a136-5d8e-11e6-8a39-09c14c8e8f83.png)

### Device info

**Device:** Samsung Galaxy S7 Edge
**Android version:** 6.0.1
**Signal version:** 3.16.0

### Link to debug log

https://gist.github.com/f279b67a1cc06d28fce122e908effc65

**Comment by s0r00t** [comment]
Can confirm this, Nexus 5 on latest CM13 and Play Store Signal.

**Comment by s0r00t** [comment]
Duplicate of #5609

**Comment by Fmstrat** [comment]
Doh, 1 issue before. Must have submitted right before me. Closing out.
