### ISSUE TITLE
[feature request] Support for vCards

### ISSUE THREAD

**Issue by BilliAlpha** [WhisperSystems/Signal-Android#5612]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Well, it's not exactly a bug. More of a feature request. But it would be a great Idea to support vCards.

**Comment by FeuRenard** [comment]
Duplicate of #535

**Comment by BilliAlpha** [comment]
OK. Didn't found/see it when doing research.
