### ISSUE TITLE
Rekey(ish) support for group chats?

### ISSUE THREAD

**Issue by mpcsh** [WhisperSystems/Signal-Android#5613]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Upon reinstalling Signal or (more commonly for me) flashing a new android ROM, group chats don't recognize my new key.

### Steps to reproduce
- Install Signal, set up a group chat
- Reinstall Signal, thus generating a new set of keys for the same phone number
- Have a friend send a message to the previously-set-up group chat
- Realize that you are unable to respond to the message

**Actual result:** I essentially become a ghost reader. Friends are unable to remove and re-add me to the group (or re-verify my key, allowing me to become a normal member again), causing us to have to create an entirely new group. As per the screenshots, this is very confusing for the less tech-savvy members of the group: there are always several chats floating around and it's hard to tell which one I can write in. The only workaround we've found is for me to remove myself from the group, flash a ROM, and then have a friend re-add me to the group. But that seems like bad UX.

**Expected result:** This is a little tricky, but here's what I'm envisioning. Upon reinstalling Signal, the group gets a notification that my key has changed (similar to individual chats) and they have to re-verify it. Once they do, the group shows up in my Signal app, where perhaps all I can see is a note reading "Mark Cohen was added back into the group", or something similar (same design as "Mark Cohen left the group" messages). After that step, I'm again a normal member of the group and can read/write as before.

**Note:** I'm more than happy to contribute a PR for this, provided y'all think this is something worth implementing. I'm also unsure if the eventual fix belongs in both apps, or server-side. Let me know!

### Screenshots
Pressing the "Send Signal message" text entry bar does nothing
![screenshot_20160812-163946](https://cloud.githubusercontent.com/assets/2894019/17637118/75fedcca-60af-11e6-871f-4e89846aa9c5.png)

Group members list is empty to me, but to them I'm added normally
![screenshot_20160812-164000](https://cloud.githubusercontent.com/assets/2894019/17637121/7d992fc6-60af-11e6-8740-e64d557c7169.png)

No "Update/Leave Group" options
![screenshot_20160812-164005](https://cloud.githubusercontent.com/assets/2894019/17637131/86624caa-60af-11e6-962c-d887ea24dda4.png)

### Device info

**Device:** Nexus 5X
**Android version:** This has occurred on several Android 6.0 ROMs (PureNexus, CM, etc), as well as stock Android 6.0.1 (MTC20F), and the most recent Android N developer preview (NPD90G)
**Signal version:** 3.16.1 (and many versions previous)

### Link to debug log

https://gist.github.com/anonymous/e7839cbd427ccf46f622672478a4cd14

<3

**Comment by johanw666** [comment]
You could use Titanium Backup or something similar to restore Signal's settings. Then you keep the same key.

**Comment by mpcsh** [comment]
@johanw666 not rooted at the moment, also see #4577 among others. In any case, requiring a third-party, potentially closed-source piece of software to touch my Signal private key is definitely a bad permanent solution IMO.

**Comment by nrizzio** [comment]
@mpcsh Have you asked your friends to trigger a group update? (They can do this by changing the group photo, or by just opening the update dialog and pressing the check button.)

**Comment by mpcsh** [comment]
@nrizzio I have not. I'll try it tomorrow when they're all awake and post the results. If this works, triggering such an update automatically could be the answer here!

**Comment by mpcsh** [comment]
@nrizzio it worked! So I guess the solution is to somehow trigger a group update automatically. Would a Signal maintainer be able to chime in to see if this is something working on?

**Comment by 2-4601** [comment]
Unfortunately groups don't currently handle these cases well. Thanks for the well written bug report, this is tracked at #1048 and #2581.
