### ISSUE TITLE
Message Compose Enhancement

### ISSUE THREAD

**Issue by Ste4thOverride** [WhisperSystems/Signal-Android#5614]
Steps to reproduce
- Open Signal and compose a long SMS message

Issue
The message text will be typed and previous written text will be out of the user views and the only way to view the text is to grab and scroll vertically 

Fix 
Text should be composed in line by line horizontally instead of a vertical line of text. This will make it easier for the user to see what they have wrote previously and change a word or edit spelling mistakes before they send a message

Device: Nexus 6P
Android version: 6.0.1 
Signal version: 3.16.1

**Comment by FeuRenard** [comment]
I understand this issue but not the fix. :blush: Could you please explain it in other words?

**Comment by 2-4601** [comment]
#5264?

**Comment by Ste4thOverride** [comment]
Nevermid it seems this is an issue caused by using the Enter Key #4219 so closing
