### ISSUE TITLE
Add "Paranoid Mode" or something similar to further encapsulate the complexity and make Signal even more userfriendly

### ISSUE THREAD

**Issue by CaneAtGit** [WhisperSystems/Signal-Android#5621]
Hey there,

I hope this issue is correctly placed here. I want to split it in two tiers: My perception of what the Signal client lacks to be even more user-friendly and easily adaptable, and my personal suggestion, how this situation could be improved.

I just realized, that this is a extension of #838 with a slightly different approach. Its still a relevant and interesting topic, in my opinion.

**The Problem**
There is a huge trade-off between privacy / trustworthiness and usability (ok, this was obvious). I use signal ever since it was TextSecure and started with SMS (maybe 3 years ago?) and watched it evolve over the time. It continuously became more seamless to use but in my perception, some of this implementations are diametrically opposed to the reason, we all use Signal: privacy. And on the other hand, there are some _features_ that are still very annoying, and I'd bet that this is because of the integrity of the encryption.

**My Suggestion**
Eliminate the trade-off between security and convenience: Every feature, that makes the usage more smoothly but on the other hand compromises security / integrity / privacy, should be opt-in/opt-out (with reasonable defaults or a wizard to set them).

I assume, that this could help signal to differentiate itself from the competition (e.g. WhatsApp, Threema, Telegram), while makeing it smoothly and even more secure and trustworthy at the same time.

**Some examples**
Convenience features, that should be defeatable
- The sync of my contacts (and everything, that is connected to it): The option could be something like "Stop uploading my contactlist to the servers" - with an explanation what that means to usability.

Annoying "features", that kill the user experience
- when re-registering or reinstalling the app, my friends need to manually add me to our groups. (My guess would be that this is because of the changed encryption-keys, however, it annoys me.) The option could be something like: "Ignore key-changes in all conversations" - with an explanation of what that means to vulnerability.

What do you think? 
Is this even reasonable? 
Do you have more suggestons of opt-in-features?

Best Regards!

**Comment by 2-4601** [comment]
> I hope this issue is correctly placed here.

Hi, this repository is mainly for reporting issues and topics like these are preferred to be discussed at https://whispersystems.discoursehosting.net/
