### ISSUE TITLE
It is impossible to revoke Google Drive permissions.

### ISSUE THREAD

**Issue by JasonLeeH** [WhisperSystems/Signal-Android#5623]
### Bug description
When I attempt to send a photo using Signal using Android, the first new screen I am presented with contains the "Recent" photos. These photos include photos uploaded to Google Drive and are not limited to just my device. I would prefer if Signal did not have access to my Google Drive account. I have checked if Signal has access permissions to Google Drive by checking the connected apps page on the Google Drive website itself and discovered that Signal isn't even listed. I have attempted to view permissions in the Signal app itself but I see nothing about disconnecting or connecting Google Drive.

### Steps to reproduce
- Open Signal
- Tap on a contact you wish to message
- Attempt to send an image
- See that your "Recent" photos contain Google Drive photos
- sigh because you don't want to see those photos in Signal at all

**Actual behavior:**
Signal has access to Google Drive photos

**Expected behavior:**
Signal should not have access to my Google Drive photos 

### Device info

**Device:** Huawei Nexus 6P
**Android version:** N
**Signal version:** 3.16.1

**Comment by moxie0** [comment]
It doesn't. That picker is provided by OS (or alternatively a third party app if you install one), not Signal.
