### ISSUE TITLE
"Signal is sending a large number of SMS messages."

### ISSUE THREAD

**Issue by corysimmons** [WhisperSystems/Signal-Android#5624]
I have:
- [✔] searched open and closed issues for duplicates
- [✔] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Steps to reproduce
- Use Signal for texting. I still have plenty of SMS's with my carrier.

**Actual result:** `Signal is sending a large number of SMS messages. Do you want to allow this app to continue sending messages? [Deny | Allow ]` error. When I click Allow, it immediately reopens the exact same message. Not sure if they're queued from every text I've ever sent, but don't have the time to click "Allow" several hundred times.
**Expected result:** This is an Android defense mechanism to make sure apps aren't sending tons of SMS's in the background. "Allow" should add Signal to a whitelist and the error should stop popping up.

### Device info
**Device:** Nexus 5
**Android version:** 6.0.1
**Signal version:** 3.16.1

### Link to debug log
https://gist.github.com/anonymous/f1e297c38f66fa62cfe5da1ff684be80

**Comment by corysimmons** [comment]
Nevermind, sorry for the report. My carrier just decided to do a scheduled service outage without telling me and then denied it when I emailed them for a while...

**Comment by jeffgdotorg** [comment]
I'm seeing this message only when  registered for WiFi  calling on inflight WiFi. Once I land and re-enable the cellular radio, the issue vanishes. If it doesn't self-resolve the next time I fly, I'll hook up adb and gather some data.Will also test with other WiFi networks.

**Comment by SnoopyWQ** [comment]
It is a problem, I click on No and despite of it Signal sent tons of SMS /about 400 SMS/ just to one phone number within seconds. Unfortunately my phone operator set me threshold of 100 SMS and I have to pay that shitty 300 SMS

**Comment by pachpict** [comment]
> "Signal is sending a large number of SMS messages. Do you want to allow this app to continue sending messages? [Deny | Allow ] error. When I click Allow, it immediately reopens the exact same message. Not sure if they're queued from every text I've ever sent, but don't have the time to click "Allow" several hundred times."

I am getting the exact same issue. It is getting worse with time. Therefore I share _corrysimmons_ suspicion that it is somehow linked to the total number of SMS's you've tried to send in total.

By clicking _Deny_ the endless messages stop and you can continue sending SMS messages anyway.
