### ISSUE TITLE
comparing mac digests with Arrays.equals

### ISSUE THREAD

**Issue by usergoodvery** [WhisperSystems/Signal-Android#5632]
Hi,

out of interest, when comparing MAC digests, current implementation uses Arrays.equals(ourMacBytes, theirMacBytes) (in lieu of, lets say, the  crypto friendly java.security.MessageDigest.isEqual).
Not sure how relevant timing attack is in the context of the client performing such comparison in non-constant time fashion, but as a matter of principle, in a crypto conscious app, you'd think that ought to be there regardless, specially, that  MAC digests are already truncated relative to their original ful length values.

**Comment by moxie0** [comment]
you're referring to the redphone code? there's no oracle, but you're right that it wouldn't hurt to switch some day

**Comment by usergoodvery** [comment]
no, I dont think it is redphone. It is found in the verifyMac() method where the client processes push messages from the server.

**Comment by moxie0** [comment]
that's dead code, holdover from when push notifications contained encrypted contents instead of just being wakeup events. also no oracle though.
