### ISSUE TITLE
Signal Desktop app keeps sending notifications in case of "error handling incoming message"

### ISSUE THREAD

**Issue by Sagar-Waghmode** [WhisperSystems/Signal-Android#5633]
Somehow, there were errors in some of the incoming messages. Signal kept on sending desktop notifications saying 10 new messages, 20 new messages, 30 new messages and so on. I had to restart signal on desktop. The message I was getting was "Error handling incoming message".

### Link to debug log
https://gist.github.com/anonymous/2cf7232bf156a62929acd5226aa45428

**Comment by FeuRenard** [comment]
This should be posted [here](https://github.com/WhisperSystems/Signal-Desktop) as it doesn't sound like an issue occuring with the Android app.
