### ISSUE TITLE
InviteReminder from an SMS intent for a phone number displays the contact name from the previous InviteReminder

### ISSUE THREAD

**Issue by adhintz** [WhisperSystems/Signal-Android#5637]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
InviteReminder from an SMS intent for a phone number displays the contact name from the previous InviteReminder

### Steps to reproduce
- Open Android Dialer, choose call history tab.
- Click on a recent phone call you've had with a contact that has a name, (let's say "ContactName"), but that you have not used signal with, and select "Send a message"
- Signal opens and displays the invite reminder: "Take your conversation with ContactName to the next level." (from InviteReminder.java)
- Open Android Dialer, choose call history tab.
- Click on a recent phone call you've had with that has just a phone number listed with no contact name (let's say "PhoneNumber"), but that you have not used signal with, and select "Send a message"
- Signal opens and displays the invite reminder: "Take your conversation with ContactName to the next level." (from InviteReminder.java)

**Actual result:**
The InviteReminder displays the ContactName from the previous conversation.
**Expected result:**
The previous ContactName is not in the InivteReminder. It looks like the InviteReminder is generally not displayed for SMS conversations with phone numbers (no contact name), so perhaps do not display the InviteReminder in this situation.

### Screenshots
![screenshot_20160826-085815](https://cloud.githubusercontent.com/assets/455883/18011778/684b06dc-6b6b-11e6-89bb-82bd515309c2.png)

### Device info
**Device:** Nexus 5X
**Android version:** 7.0
**Signal version:** 3.17.0

### Link to debug log
Not included, but please let me know if you need one.

**Comment by adhintz** [comment]
Perhaps updateInviteReminder at /src/org/thoughtcrime/securesms/ConversationActivity.java#L854
should require recipients.getPrimaryRecipient().getName() != null

**Comment by FeuRenard** [comment]
I can reproduce this on Android 5.1.1.
