### ISSUE TITLE
Fix To eliminate Voice Echo

### ISSUE THREAD

**Issue by Ste4thOverride** [WhisperSystems/Signal-Android#5641]
This is A Feature Request 

Add support for WebRTC AEC for Signal calls to eliminate the current voice echo issues. 
https://webrtc.org/blog/2011/07/11/webrtc-improvement-optimized-aec-acoustic-echo-cancellation.html

The code is open and free to use.

**Comment by moxie0** [comment]
we already do

**Comment by Ste4thOverride** [comment]
Thanks for the update
