### ISSUE TITLE
Add shortcut to jump to end of conversation

### ISSUE THREAD

**Issue by FeuRenard** [WhisperSystems/Signal-Android#5651]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Feature Request

When you are in a conversation and scrolled a bit away from the most recent message (upwards direction) a shortcut to the bottom of the conversation could be displayed near the scroll bar. This would make it easier to return to the most recent messages after reading some old messages.
### Screenshot (WhatsApp)

![screenshot_2016-08-31-22-12-07](https://cloud.githubusercontent.com/assets/16167751/18144980/a5c635c4-6fc9-11e6-9907-9925d34ef47c.png)

**Comment by haffenloher** [comment]
A possible alternative would be a fast scroll bar as proposed in this PR's discussion: #4696

**Comment by johanw666** [comment]
The quickest way to go to the end in that case is to return to the list of conversations and to open the conversation again.

However, a faster scroll might be handy to go to the beginning of the conversation. Some kind of bookmarking system like WhatsApp has with its starred messages would be even nicer but I can understand if that would not be high on the priority list now.
