### ISSUE TITLE
[WIP]: unread badge on homescreen (for all launchers)

### ISSUE THREAD

**Issue by zoff99** [WhisperSystems/Signal-Android#5652]
I have:
- [x] searched open and closed issues for duplicates
- [ ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by zoff99** [comment]
#4818
#2366

i have a working version for this. the only thing i need to know, if and where signal stores the number of unread messages? can anybody point me in the right direction?

my solution does not depend on any special launcher (hack). it's a widget, that you can put on your homescreen instead of the normal app-icon.
it will show the unread count beautfully and server the same purpose as the normal app-icon

**Comment by moxie0** [comment]
Hey @zoff99 thanks for getting involved, but this is not a discussion forum.  You might try the unofficial forum for discussion.
