### ISSUE TITLE
A problem to translate %dh, %dd and %dw to Slovenian language

### ISSUE THREAD

**Issue by bungabunga** [WhisperSystems/Signal-Android#5657]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Due to differencies between languages I can't properly translate %dh, %dd and %dw to Slovenian language. There's no problem with %ds and %dm which can be translated to %dsek and %dmin, but there's no way for other time periods to get shorten and look proper in Slovenian language.

**This issue can be solved if I just don't shorten %dh, %dd and %dw but that means that these strings should also have their plurals in Transifex.**

**Comment by RiseT** [comment]
I suggest leaving these strings as they are as this is the international scientific notation for time periods.

**Comment by bungabunga** [comment]
yeah, maybe it's better to leave this alone...

**Comment by RiseT** [comment]
@bungabunga I'm not saying that your suggestion doesn't have it merit. I'm only saying that leaving these strings in their original form, i. e. not translating them isn't wrong.

**Comment by bungabunga** [comment]
i agree with you. as i was thinking about this, whatever solution i thought of sucked more than just leaving this as is. ;)
