### ISSUE TITLE
Bug in new selection of notification messages (save button visible)

### ISSUE THREAD

**Issue by Norbert80** [WhisperSystems/Signal-Android#5661]
Hi,

build 3.18.0 has introduced the ability to select  (and delete) notification messages.
For group update messages there is a bug. If you select one the save button becomes visible. (Further on it can be clicked. The same procedure like for media messages will be initiated. However I don't know if really something is saved.)

Solution: Hide save button for all kinds of notification messages.

Please note that only the notification messages of self initiated group updates are affected by this bug. Notification messages of group updates from other group members are not affected.

Found in build 3.18.1.

**Comment by FeuRenard** [comment]
I tried to reproduce. I changed the title of the group and then marked the group update message. Then there is the trash can to delete this message and "resend message" after tapping the three dots. No save button.
3.18.1.
![screenshot_2016-09-04-17-57-26](https://cloud.githubusercontent.com/assets/16167751/18232111/597c7838-72c9-11e6-802d-af169405a2cd.png)

**Comment by Norbert80** [comment]
Here you can see the save button. But I have no resend. Resend would be a bug for notification messages too.

![signal](https://cloud.githubusercontent.com/assets/6921696/18232574/6b0c23a6-72d2-11e6-913f-186426e9f268.png)

**Comment by FeuRenard** [comment]
And what exactly did you do?

**Comment by Norbert80** [comment]
I did select one of my group updated. Seems to be the same bug for all my group updates in all my groups.

**Comment by FeuRenard** [comment]
Now I can reproduce. The save button only appears when the group has an avatar ("profile picture"). Every group update seems to contain this avatar and when you hit the save button you export the group avatar.

My groups did not have an avatar and so I saw no save button.

**Comment by Norbert80** [comment]
You are right. I can confirm that the avatar is saved.
