### ISSUE TITLE
messages marked as sent sometimes tomorrow

### ISSUE THREAD

**Issue by edo0** [WhisperSystems/Signal-Android#5672]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description
- opened Signal today
- chatted with a friend of mine
- discovered that each and every message he has sent me since yesterday is marked as received on the right day, but as sent on the next day.
### Screenshot

[https://drive.google.com/file/d/0B9aaqi6krwjpRXNqVDhaT3FYS3c/view?usp=drivesdk](https://drive.google.com/file/d/0B9aaqi6krwjpRXNqVDhaT3FYS3c/view?usp=drivesdk)
### Device info

**Device:** Acer Z520
**Android version:** 4.4.2
**Signal version:** 3.17.0
### Link to debug log

https://gist.github.com/bae2ab1a6e8a3218d6426f8bb9e0a2ea

Latest messages should be close to the end of this log

**Comment by cascheberg** [comment]
The sent time is set by the sender. Did you ask him if his devices time, date and timezone is set correctly?

**Comment by edo0** [comment]
Well, usually it's something you wouldn't change from one day to another. Nevertheless, I'll try asking him.

**Comment by edo0** [comment]
Nope, he say he hasn't. On the other side, he also gets my messages marked as sent a couple of hours later. Might this be a sever-related issue?

**Comment by cascheberg** [comment]
Is this still an issue? Related: #5577

**Comment by edo0** [comment]
Not anymore, now everything works fine
