### ISSUE TITLE
Crashes when interacting in app

### ISSUE THREAD

**Issue by mrgtreeskier** [WhisperSystems/Signal-Android#5674]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashes upon interacting with threads or trying to start new conversation. I also cannot view contacts who are not using Signal. The crash will give the "Unfortunately, Signal has stopped," message and exit signal entirely or revert to the main screen with all threads. Had the same issue during beta testing last week. Logged the problem and then uninstalled the beta version.

Cleared cache, uninstalled, reinstalled, same problems.

Turned on airplane mode, deleted threads, same problem.

Messages are being retrieved and presented as notifications through Signal. Changed to phone's messenger as default SMS app in the meantime.

### Steps to reproduce
- Open app
- Touch a conversation
or
- Begin new conversation
- Select a contact
or
- Click reply on notification

**Actual result:** Immediately, the error message "Unfortunately, Signal has stopped." appears and exits to the home screen of my phone.
**Expected result:** Ability to look at the thread and type and send messages.

### Device info
**Device:** HTC One M7
**Android version:** 5.0.2
**Signal version:** 3.18.2

### Link to debug log
https://gist.github.com/98d1c821855df39a648ab4b7e107af93
https://gist.github.com/097fe9ba87240354e5108db0dcac35fe

**Comment by FeuRenard** [comment]
This seems to be introduced by e4fccbe. Sorry.

**Comment by FeuRenard** [comment]
I cannot reproduce this.

Can you @mrgtreeskier or anyone who can reproduce this issue test this branch:
https://github.com/FeuRenard/Signal-Android/tree/fix-character-calculation2 ?
Would be interesting, what the character count below the input field in the conversation says.

**Comment by parryc** [comment]
Another [Sprint/HTC combo](https://gist.github.com/anonymous/98d1c821855df39a648ab4b7e107af93) with the same error, but different OS version (6.0).

**Comment by moxie0** [comment]
Thanks for the report @mrgtreeskier. In the future if you encounter something in a beta release, it's important to file an issue for it here before the production release. Hopefully this change fixes things for you.

**Comment by mrgtreeskier** [comment]
Thank you @FeuRenard, @parryc, @moxie0!

**Comment by FeuRenard** [comment]
I would still be interested:
When you now open a SMS conversation, does the character counter appear below the text input field? If yes: what does it show? And what happens, when you enter some characters?

**Comment by mrgtreeskier** [comment]
@FeuRenard the character counter only shows when I approach 140 characters.
