### ISSUE TITLE
Allow user to specify the directory where media, backups, etc are saved

### ISSUE THREAD

**Issue by laurencebgood** [WhisperSystems/Signal-Android#5677]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

This is a pretty straightforward feature request. Right now, saving media places it in the root of the media type (eg the "Pictures" directory) and backups get exported to the root of the device. I'd like to be able to specify an alternate directory, to keep my device less-cluttered. In the case of media in particular, it would be great if it would be possible to do in settings, so that the user won't have to choose a location in a dialogue every time they save something (or if there must be a dialogue, have it remember the last chosen location so the user doesn't have to navigate to the right directory every time)

**Comment by moxie0** [comment]
Thanks but we're not going to do this

**Comment by laurencebgood** [comment]
Might I ask why? I can't see a down side, I'm sure I'm just missing it. (Or would you prefer this be discussed on the forums?)

**Comment by laurencebgood** [comment]
And just to give some additional background, since I was perhaps-unfairly assuming this is common knowledge: all other android apps create a directory inside of the "Pictures" directory for themselves and put anything you save in that app-specific directory; Signal is the only app I have ever used that dumps them directly into "Pictures". So if any form of configuration is out of the question, I would be perfectly happy to see Signal just use the same pattern as all other android apps.

**Comment by 2-4601** [comment]
> why?

https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#development-ideology
_"1. The answer is not more options. If you feel compelled to add a preference that's exposed to the user, it's very possible you've made a wrong turn somewhere."_
​

> all other android apps create a directory inside of the "Pictures" directory for themselves and put anything you save in that app-specific directory

That's tracked at #2791.
