### ISSUE TITLE
Problem registering on Android N

### ISSUE THREAD

**Issue by returntoreality** [WhisperSystems/Signal-Android#5678]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
On a current Android N running on a nexus 5X the registering fails with: Connection Error
logcat shows that the Intent com.google.android.c2dm.intent.REGISTER fails with java.io.IOException: SERVICE_NOT_AVAILABLE
The registration works on other devices

### Steps to reproduce
- install Signal 
- enter phone number
- tap on register

**Actual result:** The registration fails with Connection Error
**Expected result:** The registration succeeds

### Screenshots
Signal does not allow screenshots at this point and the setting cannot be changed until registered

### Device info

**Device:** Google Nexus 5X
**Android version:** Stock Android 7.0
**Signal version:** 3.18.3

### Link to debug log
As the debug log is not accessible before registering, here is the relevant logcat exerpt:
https://gist.github.com/returntoreality/21aa90217f3721be4730ce6d9be83279

**Comment by moxie0** [comment]
Did you flash a rom to your device? Looks like you have a bad gapps install.

**Comment by 2-4601** [comment]
Unable to reproduce with Signal 3.18.3, Nexus 5X, stock 7.0

**Comment by returntoreality** [comment]
It worked after waiting some time. Thanks for your help anyways.
