### ISSUE TITLE
Feature Request: Distribute Signal w/ deterministic biuilds (Gitian).

### ISSUE THREAD

**Issue by Geremia** [WhisperSystems/Signal-Android#5683]
[Deterministic builds (Gitian)](https://gitian.org/) is an excellent, decentralized, secure means of distributing binaries:

>Gitian is a secure source-control oriented software distribution method. This means you can download trusted binaries that are verified by multiple builders.

>Gitian uses a deterministic build process to allow multiple builders to create identical binaries. This allows multiple parties to sign the resulting binaries, guaranteeing that the binaries and tool chain were not tampered with and that the same source was used. It removes the build and distribution process as a single point of failure.

Gitian is used in the [Bitcoin](https://bitcoincore.org/) project.

Yes, there have been many issues (e.g., #122, #127, #281, #282, #458, #525, #722, #2858, #3435, #3954, #4429, #4430) regarding distributing Signal in other ways than via Google Play or Apple Store, but I do not think my feature request is a duplicate of those.

**Comment by moxie0** [comment]
Thanks but we're not going to do this.

https://whispersystems.org/blog/reproducible-android/
