### ISSUE TITLE
Plans for Numberless accounts

### ISSUE THREAD

**Issue by zpskj** [WhisperSystems/Signal-Android#5684]
While contact discovery is useful for the usecase of an average user just wanting secure communication with their friends, it is a huge security risk for activists. Although Signal is not primarily aimed at activists, there are no suitable alternatives on mobile. Are there plans to improve Signal in this area?

- Numbers are available to anyone in the group chat, so adding someone to a group requires you have to trust them not to leak phone numbers.
- There are no display names, so having everyone introduce themselves to each other is tedious and requires adding each other to contact lists, which is potentially a security risk as well.
- Global display names would not solve the problem, as you'd need to use a separate one in your activism group chats and with your friends.

**Comment by Geremia** [comment]
Yes, unfortunately Google Play services is needed just to register, too.

**Comment by nrizzio** [comment]
Duplicate of #1085.

**Comment by moxie0** [comment]
Thanks @zpskj but we don't use GH issues as a discussion forum.
