### ISSUE TITLE
Linking New Device - was working, now fails.

### ISSUE THREAD

**Issue by DiagonalArg** [WhisperSystems/Signal-Android#5686]
### Bug description
I am trying to link Signal desktop to my android phone.  I have done this before, but the new version of signal desktop is asking me to do it again.  When I try to scan the QR code, the camera on my phone does not focus and the code does not scan.   I am able to use a 3rd party scanner, which scans fine, giving me a link.  I tried that link in the browser, but Signal said that for my own protection I should scan from inside Signal.  I attempted again after having unlinked my previously linked device, with the same result.  So, I'm stuck.

### Device info
Andorid 4.0.4 and Signal 3.18.3 on HTC Thunderbolt
I am only using the Signal client, it is not set as the default SMS app.
Ubuntu 16.04 Gnome and Signal 0.22.2 on Thinkpad T530

**Comment by 2-4601** [comment]
Sounds like #4637. Which ROM are you using?

**Comment by riyapenn** [comment]
Have you tried these steps?
1. Take a screen shot on your computer of Signal Desktop with the QR code
2. Open the screen shot image in an image viewer 
3. Zoom in on the image
4. Take your HTC Thunderbolt phone and scan the "zoomed-in QR code".

**Comment by DiagonalArg** [comment]
@riyapenn - thanks.  That worked perfectly.  Thanks.

@2-4601 - I am rooted, using the stock ROM though it's a little cleaned up.

Seconding the comments in #4637.  There should be a fall-back, so we can type in the data by hand and have the link proceed.

Thanks everyone for your work!
