### ISSUE TITLE
Android N Additional emoji Support

### ISSUE THREAD

**Issue by jjohns71** [WhisperSystems/Signal-Android#5687]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal doesn't support the full range of emoji's now offered in Android N such as skin color. I know Signal uses the Apple emoji's but it doesn't offer the latest emoji's incorporated into iOS either.

List of Emoji's on Android N: http://emojipedia.org/google/android-7.0/
List of Emoji's on iOS: http://emojipedia.org/apple/

Is it possible to add support for the new emoji's supported by Apple and Google? I know this is a pretty low priority issue but from a "usability" standpoint, it stands out as an "issue" for non technical people who have been converted by their techy friends.

Would be nice to stay current on the flashy parts of the Android and iOS ecosystems so it is easier to be an evangelist and get people to convert to Signal.

### Steps to reproduce
- Use the new skin tone emoji's using a keyboard such as google keyboard or Swiftkey

**Actual result:** Unicode support for skin tone are not supported in Signal.

**Expected result:** Accurate depiction of the most recent emoji's used by Apple and Google.

### Screenshots
![screenshot_20160915-141859](https://cloud.githubusercontent.com/assets/6795795/18562090/5bcc2e28-7b50-11e6-913a-652ab6868881.png)

### Device info

**Device:** Nexus 6P
**Android version:** 7.0
**Signal version:** 3.19.0

**Comment by 2-4601** [comment]
Yeah, they should be updated. These are tracked here #4279, #3556.
