### ISSUE TITLE
New secure session reset strings not shown in conversation list snippet

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/Signal-Android#5690]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Steps to reproduce
- reset session
- go back to conversation list

**Actual result:** Snippet says: "Secure session reset."
**Expected result:** Snippet says: "You reset the secure session."

### Screenshots
![screenshot_20160916-163149](https://cloud.githubusercontent.com/assets/174176/18587692/ed334064-7c2b-11e6-8c52-5cbcea414d17.png)
![screenshot_20160916-163155](https://cloud.githubusercontent.com/assets/174176/18587698/f30e538e-7c2b-11e6-88ff-9b8da167f6c2.png)

### Device info

**Device:** Nexus 5X
**Android version:** 7.0
**Signal version:** 3.19.0

cc @cascheberg

**Comment by FeuRenard** [comment]
This is not necessarily an issue. When you look at `strings.xml`, you will notice that there are already some strings that aren't the same for `MessageRecord` (conversation) and `ThreadRecord` (conversation list).

**Comment by p4nci** [comment]
I agree with @FeuRenard .
BTW: I miss the translation (in german) for "You reset the secure session." (within conversation).

**Comment by FeuRenard** [comment]
Another important argument against a change here:
The strings shown in the conversation list should be as short as possible because there is only one line to display them.

**Comment by 2-4601** [comment]
True, group updates also use different strings in the list and inside the conversation. That has always confused me a bit but in the end I don't really care.
