### ISSUE TITLE
Reduce image compression

### ISSUE THREAD

**Issue by libeclipse** [WhisperSystems/Signal-Android#5692]
This is a duplicate of #672, which was opened almost three years ago and forgotten about.

Image compression in signal is ridiculous. Any text is completely illegible and anything else isn't worth saving. I'm not sure why it was set so high in the first place, but in 2016 it's just an annoying "feature".

**Comment by nrizzio** [comment]
Please do not open duplicate issues.

**Comment by Dyras** [comment]
I don't think it's forgotten, I just think they are trying to work out all the kinks before they start fixing the usability aspects. This is after all an app primarily aimed at geeks.

Totally agree with you though, I don't really see why the compression is so low. The files are only stored temporarily on the server, right? So no massive storage needed, or am I wrong?

**Comment by 2-4601** [comment]
#672 is still open and not forgotten
