### ISSUE TITLE
Group Messages Not Importing

### ISSUE THREAD

**Issue by mlam0413** [WhisperSystems/Signal-Android#5694]
I have:
- [x ] searched open and closed issues for duplicates
### Bug description

Importing from system SMS database did not transfer my group messages. No messages appeared in the individual messages either.
### Device info

**Device:** Samsung Galaxy S7 Edge
**Android version:** 6.0.1
**Signal version:** 3.18.3
### Link to debug log

https://gist.github.com/849285702a37a9609cc0e228157d03d1

**Comment by 2-4601** [comment]
Are the group text messages actually MMS based? If so that's not supported (#4095)
