### ISSUE TITLE
Where can I find the Signal-Android 'Release History' for ALL Prior Releases ??

### ISSUE THREAD

**Issue by orthelllo99** [WhisperSystems/Signal-Android#5699]
Where can I find the Signal-Android **Release History** for ALL Prior Releases ??

i.e. that shows what '**fixes / functional additions**' that were in each release ??

I have looked at the Github's main section (https://github.com/WhisperSystems/Signal-Android) but could NOT find it

Thanks

**Comment by 2-4601** [comment]
https://github.com/WhisperSystems/Signal-Android/commits

Please note that this issue tracker is used for bugs, not questions and comments.
For more information please see: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#not-a-discussion-forum
