### ISSUE TITLE
Unlisted phone number shown

### ISSUE THREAD

**Issue by Ceaus** [WhisperSystems/Signal-Android#5701]
My remote Signal partner uses an unlisted phone number and has her caller ID blocked.
Yet Signal shows me her number although it should be kept secret.

Remote partner is on iPhone/IOS,
I am on Android + Linux Chrome apps (seen on both)

iPhone: Signal version as per Apple app store  17-SEP-2016.
Android: Signal 3.18.3
Linux Chrome app: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36 Signal-Desktop/0.22.2

**Comment by nrizzio** [comment]
Your phone number is your identifier. Having a withheld caller ID is not something that Signal supports.
