### ISSUE TITLE
SMS only, non-Signal Android contact showing up on Signal Desktop after changing its color

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/Signal-Android#5710]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Not sure if this problem is on Signal Android's end or on Signal Desktop's.

One of my SMS (non-Signal) contacts just got synched with Signal Desktop after changing its color on Signal Android, i. e. the contact is (was) listed on Signal Desktop's contact list - not the conversation.

After exiting Signal Desktop and starting it again, that contact magically disappeared again.

Edit: I've been able to reproduce this a second time and updated this issue with new debug logs for Signal Android and Signal Desktop. All logs are now taken directly after the issue happened.

Potentially related issue: https://github.com/WhisperSystems/Signal-Desktop/issues/903

### Steps to reproduce
- Change color of a non-Signal contact
- Start Signal Desktop

**Actual result:** Contact shows up on Signal Desktop
**Expected result:** Contact shouldn't show up on Signal Desktop

### Device info

**Device:** Google Nexus 5
**Android version:** 6.01
**Signal version:** 3.19.1

### Debug logs:
[Signal Android directly after changing contact color](https://gist.github.com/RiseT/c8b24245919e7eae72dcfefd2c8b88f6#file-signal-android-issue-5710-1-txt)
[Signal Desktop directly after contact appeared and is still present](https://gist.github.com/RiseT/c8b24245919e7eae72dcfefd2c8b88f6#file-signal-android-issue-5710-2-txt)
[Signal Desktop after contact disappeared again](https://gist.github.com/RiseT/c8b24245919e7eae72dcfefd2c8b88f6#file-signal-android-issue-5710-3-txt)

**Comment by scienmind** [comment]
On the desktop client that imported sms-only contacts due to this bug in the past, I still see sms-only contacts. Re-importing don't clear them.

Any way to fix it without wiping the desktop installation? Open another issue for this?

Signal android version: 3.24.1
