### ISSUE TITLE
Add support for bundled notifications (Android 7.0)

### ISSUE THREAD

**Issue by rkoesters** [WhisperSystems/Signal-Android#5712]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Android 7.0 (Nougat) adds bundled notifications which allows the app to group notifications in a way that lets the user expand the group to work with each notification individually (https://developer.android.com/about/versions/nougat/android-7.0.html#notification_enhancements).
Currently, when Signal has notifications from two or more conversations, the notifications are grouped together into one notification that cannot be expanded, preventing the user from preforming quick actions on the notifications without entering the app. Implementing the new notification feature will allow Signal to continue to group notifications with the added benefit of preforming quick actions on each notification individually.
### Screenshots

Bundled notifications example (from https://developer.android.com/about/versions/nougat/android-7.0.html)
![](https://developer.android.com/images/android-7.0/notifications-1.png)
### Device info

**Device:** Nexus 5X
**Android version:** 7.0.0

**Comment by FeuRenard** [comment]
Fixed by 4a072c4.

**Comment by 2-4601** [comment]
a9bd84c69c72601539b9b305ebfb231ef01fadda
