### ISSUE TITLE
Offer option to choose emoji font

### ISSUE THREAD

**Issue by PanderMusubi** [WhisperSystems/Signal-Android#5716]
After reading https://github.com/WhisperSystems/Signal-Android/issues/3675 and https://github.com/WhisperSystems/Signal-Android/issues/3445 I would like to request a feature that the user can choose which emoji font (Apple or Emoji One) to use. The default would be whatever is used now.

**Comment by moxie0** [comment]
Thanks but we're not going to do this.  We offer the option to use the system emojis or the Signal emojis.
