### ISSUE TITLE
Option to display contact in terms of name and/or number

### ISSUE THREAD

**Issue by PanderMusubi** [WhisperSystems/Signal-Android#5717]
In order to counter [shoulder surfing](https://en.wikipedia.org/wiki/Shoulder_surfing_(computer_security)) an option could be added to show a contact in:
* name + (wherever possible) phone number (as is currently done and default option
* name only (no phone numbers are shown anywhere unless contact is not in address book
* phone numbers only (no names are shown anywhere, only initial letter in contact avatar) (alternatively as name, the same initial could be used as is used for the contact's avatar)

Places where this applies is the overview of contacts, a dialogue, notification drawer et cetera.

Implementing would greatly counter shoulder surfing in terms of with whom one is commuicating.

**Comment by moxie0** [comment]
Thanks but we're not going to do this.  We have notification privacy settings, and that's as far as we're going to go with it.
