### ISSUE TITLE
Need way to persistently mark contact as insecure contact

### ISSUE THREAD

**Issue by TJC** [WhisperSystems/Signal-Android#5719]
We need a per-contact setting to disable secure messaging, and just use regular SMS.

Why?
I have come across contacts who are incorrectly considered to be Signal users.
That is to say: Signal wants to send them encrypted messages over data, but these people do not have Signal installed, and claim to have never used Signal or TextSecure previously.
I assume the issue comes about from mobile number re-use.

**Comment by Trolldemorted** [comment]
Signal can send regular sms if you long-press the send button. The UI maybe needs some polishing, i was also unable to notice this feature without using google.

The TextSecure servers are sometimes uncertain who is registered or not. Couldn't send messages to a friend (server responded that he unregistered/is not registered) but he could send messages to me without any problems.

**Comment by TJC** [comment]
I'm aware that you can over-ride the settings per message -- I'm talking about a way to _persistently_ do that per contact.

**Comment by 2-4601** [comment]
Closing as duplicate of #2285.
