### ISSUE TITLE
Should messages be marked read when notification is swiped away?

### ISSUE THREAD

**Issue by magicbane** [WhisperSystems/Signal-Android#5720]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

When the message can be read in the drop down menu, swiping/clearing the notification should mark message to read.
### Steps to reproduce
- Saw message from dropdown notification
- swipe to remove from notification
- Message should be marked read
- Further notifications should not stack with the read mesages.
### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by 2-4601** [comment]
Do other messaging apps behave like this?

**Comment by magicbane** [comment]
Textra does.
My issue is that if not set this way, when new message comes in, it stacks and gets very messy from the notification bar.

**Comment by 2-4601** [comment]
Related #5712, #4922

**Comment by retrry** [comment]
Please don't. I've sometimes just dismiss notifications and read them later. We already have ability to mark messages as read from notifications with button: Mark Read.

**Comment by moxie0** [comment]
I don't think we want to mark messages read if you swipe away the notification, but maybe we do want to change notifications so that they don't reappear once they've been dismissed. That's my understanding of how most other messaging apps, gmail, etc... all behave. Can't decide if the way we do things is a bug or a feature.

**Comment by magicbane** [comment]
I'm fine with the compromise of making the message not reappear.
