### ISSUE TITLE
App does not use android 7.0 system quick reply from the notification drawer

### ISSUE THREAD

**Issue by walshbm15** [WhisperSystems/Signal-Android#5728]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Signal app does not utilize new Android system quick reply from notification pull down.
### Steps to reproduce
1. Receive a message
2. Open notification drawer

**Actual result:** Quick reply from the notification drawer is not an option.

**Expected result:** I expect I would be able to reply to messages from the system quick reply like in other messaging applications.
### Device info

**Device:** Nexus 5X
**Android version:** Android 7.0
**Signal version:** 3.19.1

**Comment by blunden** [comment]
Switching to using this API would also have the added benefit of allowing Android Wear users to respond from their watch.

**Comment by Lokesh-Krishna** [comment]
Can we please move to this on Nougat and above?
Like @blunden mentioned, using the [RemoteInput API](https://developer.android.com/reference/android/support/v4/app/RemoteInput.html?utm_campaign=android_series_notificationsandroidnblog_060816&utm_source=anddev&utm_medium=blog) would also be beneficial to Android Wear users.
It will not affect users on Marshmallow and below anyways if properly implemented and they can continue to enjoy Signal's implementation, which is definitely way better than anything else I've seen until this native method came in.
Also, the new [MessagingStyle](https://developer.android.com/reference/android/support/v4/app/NotificationCompat.MessagingStyle.html?utm_campaign=android_series_notificationsandroidnblog_060816&utm_source=anddev&utm_medium=blog) lets users continue conversations from the notification itself and you can bundle notifications from multiple conversations into one neat summary notification.
It looks like implementing all of this is well documented: [Notifications in Android N](http://android-developers.blogspot.in/2016/06/notifications-in-android-n.html#directreply)
Will it be possible to work towards this? This is a beautiful and elegant implementation and with everything ready and waiting to be integrated, it's a shame to miss out on it.

**Comment by FeuRenard** [comment]
Fixed by cce1362.

**Comment by Lokesh-Krishna** [comment]
@FeuRenard Will this issue be closed once that commit is part of the next update or will it be kept open until the messaging history style is also implemented?
I ask because I wanted to know if a separate issue needs to be created for it or if this can stand in for that as well.

**Comment by FeuRenard** [comment]
I would recommend to open a new issue for that, if the mentioned commit doesn't enable your desired feature. Let's wait for the (beta) release.

**Comment by 2-4601** [comment]
Does 373a0f952708996c584f92e4e000d270cb22af01 fix this? (It's on the Play Store release.)

**Comment by Lokesh-Krishna** [comment]
That only implements direct reply, not MessagingStyle, though now that the former already exists, implementing the latter would be easier.

**Comment by Lokesh-Krishna** [comment]
Yes, it does.
