### ISSUE TITLE
Disappearing message notification disappears in group thread but not in contact thread

### ISSUE THREAD

**Issue by michaelkirk** [WhisperSystems/Signal-Android#5732]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description

When you change the disappearing message timer, a notification appears, but whether that notification hangs around depends on whether you're in a group vs. contact thread.
 
#### Given I'm in a group thread
- When I enable the (unreleased) disappearing messages feature
- And set the timer to 5 seconds
- Then I see the "You set disappearing message time to 5 seconds."  
- In five seconds that info message is deleted.

#### Given I'm in a contact thread
- When I enable the (unreleased) disappearing messages feature
- And set the timer to 5 seconds
- Then I see the "You set disappearing message time to 5 seconds."  
- The info message never gets deleted.

**Actual result:** 

Contact thread "You set disappearing message time" info messages are never deleted.

**Expected result:**

Primarily I expect the Contact thread info message to be deleted. 

Though if you could make a case for why the notification should remain, then at least it should be consistent across group and contact threads.

**Comment by FeuRenard** [comment]
Is (sort of) filed in https://github.com/WhisperSystems/Signal-Android/pull/5628#issuecomment-249995727 and will probably be fixed by #5727.

**Comment by michaelkirk** [comment]
closed as dupe of https://github.com/WhisperSystems/Signal-Android/pull/5727
