### ISSUE TITLE
Use read receipt envelope timestamp to infer startExpirationTime of disappearing messages

### ISSUE THREAD

**Issue by liliakai** [WhisperSystems/Signal-Android#5733]
- Link Android and Desktop with disappearing messages support
- Go to conversation list on Android
- Open a conversation on Desktop
- Receive a 10s disappearing message on Desktop
- Note that it is also received and marked read in the Android conversation list
- Wait 10 seconds

**Actual result:** 
Message expires from Desktop, but is still readable Android

**Expected result:** 
Message expires on both clients at about the same time

Note that it's not enough to start the timer when marking the message read. You have to back-date it by looking at the send time of the read receipt itself in case your client has been offline for a while.

**Comment by moxie0** [comment]
Code already uses that timestamp, must be another problem somewhere.

**Comment by moxie0** [comment]
fixed in 3.20.0
