### ISSUE TITLE
Restore accidentally removed contacts

### ISSUE THREAD

**Issue by mueller-ma** [WhisperSystems/Signal-Android#5737]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
In my Android address book the Signal contacts (with "Signal Call" and "Signal message") were seperated from the real contact (with the phone number, mail address and other stuff) (this isn't the bug I want to report here, it could be caused by moving my contacts from google to owncloud). I thought I can just remove the "duplicates" (signal contacts), refresh contact list and this will be fixed, but now the contacts are broken (see Actual result).

### Steps to reproduce
- open address book
- remove the signal-part from the contact
- open signal
- refresh contact list

**Actual result:** The contacts appear as SMS-only users, but when I click on them, a secure Signal chat opens
**Expected result:** They should appear as Signal users again

### Screenshots

For privacy reasons, I don't want post screenshots or debug logs

### Device info

**Device:** Oneplus X
**Android version:** 6.0.1
**Signal version:** 3.19.1 (Google Play Version)

### App state
Signal messages and calls registered, SMS enabled, passphrase disabled, dark theme, default notification settings, using chrome app

**Comment by ByteHamster** [comment]
Might be a duplicate of #5730

**Comment by mueller-ma** [comment]
Related, but no duplicate. #5730 workaround is matching contacts manually again.
Here no workaround possible, since the contacts are gone

**Comment by E3V3A** [comment]
Unfortunately this sound like an Android issue more than a Signal issue. Loads of apps have the same issue because of the tantalisingly crappy AOSP contact implementation. soways trying to automatically sync to your gmail etc.

**Comment by mueller-ma** [comment]
I think an easy way to fix this would be an option to rescan all contacts in the contact book and add missing signal parts to contacts.
An option in Threema sounds like that: "Checks connection between Threema contacts and Android contacts and corrects them, if necessary"

**Comment by haffenloher** [comment]
> I think an easy way to fix this would be an option to rescan all contacts in the contact book and add missing signal parts to contacts.

Although there's no explicit option for that, you can still go into your Android settings, go to *Accounts*, delete the Signal account (don't worry about the warning), open Signal, tap the blue pencil, and pull down the contact list to refresh, at which point the Android account should be recreated together with the contact associations

**Comment by mueller-ma** [comment]
Will my keys, groups and chat history be deleted?

**Comment by 2-4601** [comment]
> Will my keys, groups and chat history be deleted?

No.

**Comment by mueller-ma** [comment]
Working good. Great work guys
