### ISSUE TITLE
Changing default SMS app away from Signal displays wrong settings page on Android 6 & 7

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/Signal-Android#5739]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Tapping on 'SMS Enabled'/'Touch to change your default SMS app' displays Android's 'Wireless & networks' settings page. The problem here is that while on Android versions lower than 6 this indeed used to be the correct place to change the default messaging app, this has changed with Android 6 and 7.

The correct setting pages are on
- Android 6: 'Settings' >> 'Apps' >> 'Configure apps' (= cogwheel icon) >> 'Default Apps' >> 'SMS app'
- Android 7: 'Settings' >> 'Apps' >> 'Configure apps' (= cogwheel icon) >> 'SMS app'

### Steps to reproduce
- In Signal (when Signal is currently the SMS default app) tap on 'Settings' >> 'SMS and MMS' >> 'SMS Enabled'

**Actual result:** Android's 'Wireless & networks' settings page is displayed independently of Android version
**Expected result:** Correct settings page to change the default messaging app should be displayed (which depends on the Android version used).

### Device info

**Device:** LG Nexus 5X
**Android version:** 7.0.0
**Signal version:** 3.19.1

**Comment by FeuRenard** [comment]
For Android 7 this is already reported in #5541.

**Comment by RiseT** [comment]
@FeuRenard Do you currently have an Android 6 device available in order to confirm this issue?

Mine got stolen and I'm not completely sure if this already has been solved for Android 6. What I know, though, is that the correct 'landing page' on Android 6 is different from the one on Android 5 (see above). And on Android 7, Signal is currently pointing to the page where these settings used to be on Android 5. Which makes me believe that Android 6 behaves the same way. But I'm unable to check this on an actual device as I have none anymore.

**Comment by FeuRenard** [comment]
I can confirm that this issue also exists on Android 6. But that is also mentioned in #5541. I suggest to close this one in favor of #5541.

**Comment by RiseT** [comment]
Oh, ok. You mentioned that this issue had already been reported for Android 7, so I surmised that it hadn't been reported yet for Android 6. Closing.
