### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by x-x-x-x-x-x-x** [WhisperSystems/Signal-Android#5740]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Can't remove people from group chats.

I had a group chat with my friend and 2 of my own numbers, a work and a private phone. I don't have access to the Company phone anymore, but the number is in the group chat.

### Steps to reproduce
- create a group chat
- try removing someone

**Actual result:** Nothing happens
**Expected result:** Being able to deny access to a random person having my old number and not revealing all our private conversations.

### Screenshots
N/A

### Device info
**Device:** Samsung i9300 / Samsung i9301 / iPhone SE
**Android version:** 4.3, 4.4, iOS 9
**Signal version:** 3.19.1

### Link to debug log
N/A

**Comment by sweeper3000** [comment]
There is no support for removing other people from groups. Only the person that needs to be removed can remove themselves.

**Comment by x-x-x-x-x-x-x** [comment]
Thank you for your answer! 

So that means it is a feature that from now on everyone who ever gets that number will be able to read all of our messages and write messages to us and there is nothing we can do about it?

**Comment by sweeper3000** [comment]
I don't know why we can't remove other people from groups. Probably a protocol thing. I could see *future messages* getting seen, but not past messages thanks to forward secrecy.

**Comment by x-x-x-x-x-x-x** [comment]
I didn't even know it has forward secrecy and just checked it with the two remaining numbers, and it indeed does work as in I can't see past messages.

Thank you VERY much for your quick response!
