### ISSUE TITLE
How to rebuild Lib C

### ISSUE THREAD

**Issue by mdtuyen** [WhisperSystems/Signal-Android#5742]
I want to rebuild jni code but when I use "ndk-build" command it show:
> make (e=87): The parameter is incorrect

What is the parameter of the command ?

**Comment by 2-4601** [comment]
As you were told [before](https://github.com/WhisperSystems/Signal-Android/issues/5688#issuecomment-247507991), this is a [bug tracker](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#not-a-discussion-forum). You may find your luck with [Google](http://bfy.tw/81Bd)

**Comment by mdtuyen** [comment]
Sorry, I clone your app, don't change every thing. and rebuild. It error, I searched on google but can't resolved.

Other question: I see that in your lib C have some code have been compiled so that I don't know about them. I want to use my service for your app. Is it supported ?

**Comment by nrizzio** [comment]
Please ask your questions in the community forum located [here](https://whispersystems.discoursehosting.net/), as this bug tracker sends an email to approximately 500 people currently watching this repository.
