### ISSUE TITLE
No notifications shown on new message receive

### ISSUE THREAD

**Issue by velteyn** [WhisperSystems/Signal-Android#5743]
I have:
- [X ] searched open and closed issues for duplicates
- [ X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
No notifications shown on new message receive

### Steps to reproduce
send a message to a friend
mesage not notified...

### Device info

**Device:**  HUAWEY P8 Lite
**Android version:** 6.0.0  EMUI 4.0
**Signal version:** 3.19.1

### Link to debug log

https://gist.github.com/anonymous/78150130bb7a951280ac2c1590e8b3ac

**Comment by 2-4601** [comment]
#5447
You should add Signal as a protected app in EMUI settings: http://www.androidheadlines.com/2016/01/how-to-fix-missing-notifications-on-huawei-phones.html

For further help, please read http://support.whispersystems.org/hc/en-us/articles/213190487-Why-is-there-a-delay-in-receiving-messages- and if you still have issues contact support@whispersystems.org
