### ISSUE TITLE
Build fails due to invalid checksums in build.gradle

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/Signal-Android#5748]
The Android Play Services and play-services-maps were upgraded from 8.1.0 to 9.4.0, but the checksums in build.gradle (line 107 and 108) were not changed, so the build fails. Removing the lines solved the issue, but the checksums have to be updated.

The same holds for com.android.support:appcompat, com.android.support:recyclerview, com.android.support:cardview, com.android.support:design, com.google.android.gms:play-services-base, com.google.android.gms:play-services-basement and com.android.support:support-v4.

I wonder how OWS builds the project. Are there things not checked in or do they disable the checksums completely?

After that, the build fails with
`
Signal-Android\build\intermediates\res\merged\debug\values-v23\values-v23.xml
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
Error:(34) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.
`
I'm still working on that one.

**Comment by haffenloher** [comment]
You probably upgraded those yourself, [everything's still at 8.1.0 here](https://github.com/WhisperSystems/Signal-Android/blob/master/build.gradle#L40-L42)

**Comment by johanw666** [comment]
Indeed, I just checked. That must have been one of those strange quirks of Android Studio. I'm sorry to have bothered you with it.
