### ISSUE TITLE
Messages sent from 3.20.0 to other contacts not in the beta are delayed or sent multiple times

### ISSUE THREAD

**Issue by piratenpanda** [WhisperSystems/Signal-Android#5754]
I have:
- [x ] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Messages sent to contacts with probably Signal 3.19 still, are either delayed or are received multiple times at the receiving end.

### Steps to reproduce
- Use the latest beta 3.20.0
- Send messages to other contacts

**Actual result:** 
Messages are delayed, the two checkmarks take minutes sometimes to appear, the dots keep dancing and the messages are delivered several times from time to time

**Expected result:** 
Send message right away and only once

### Device info

**Device:** Moto X Play
**Android version:** 6.0.1
**Signal version:** 3.20.0

### Link to debug log
https://gist.github.com/anonymous/a5e505230708d350938bb72c97f171bd

**Comment by piratenpanda** [comment]
Also happens from the desktop client, so I'm not sure it's actually caused by the latest Android version

**Comment by nrizzio** [comment]
I believe this is a server problem rather than a client issue. See https://whispersystems.discoursehosting.net/t/intermittent-message-send-failures/537/2?u=nrizzio

**Comment by piratenpanda** [comment]
Interesting, thank you

**Comment by Trolldemorted** [comment]
moxie has stated the issue has been resolved, and all my devices i can currently access are operating again.
