### ISSUE TITLE
Missing punctuation in timer change messages

### ISSUE THREAD

**Issue by Norbert80** [WhisperSystems/Signal-Android#5764]
I found an error in the germane translation of the notifications when changing the time for disappearing messages.

> Du hat die Zeit zum Verschwinden der Nachricht auf 1 Woche festgelegt

The string above contains three errors. Correct is:

> Du ha**s**t die Zeit zum Verschwinden der Nachricht**en** auf 1 Woche festgelegt**.**

(Also note the dot at the end.)

Since I don't know if the English language string is correct and if the German string can be fixed by translation I post this one as issue.

Found with build 3.20.3 (and older).

**Comment by FeuRenard** [comment]
This is tracked in #5658.

**Comment by Norbert80** [comment]
@FeuRenard OK this should fix the first bug. But singular instead of plural (Nachricht_en_/message**s**) and the missing trailing dot (which is present in group update notifications) are not covered by #5658.

**Comment by FeuRenard** [comment]
The original strings are ok. The remaining issues have to be fixed in the translation:
https://www.transifex.com/projects/p/signal-android/

**Comment by Norbert80** [comment]
@FeuRenard thanks for your investigation. I don't know how to change the German strings. Would you mind to fix them?

**Comment by RiseT** [comment]
@Norbert80 I'll look into it.

**Comment by RiseT** [comment]
Ok. I've taken a look.

The original string is
```%1$s set disappearing message time to %2$s```

- At the time of translation, I haven't had the opportunity to see this feature in action, so it wasn't clear to me if "message" should be translated as singular or as plural. But you're correct, so thanks for the hint.

- As you can see, there's no period at the end of the original string neither. These message record strings in the conversation view never have periods at the end, so no period is correct

I've now changed the translation to
```%1$s hat die Zeit für das Verschwinden von Nachrichten auf %2$s festgelegt```

**Comment by Norbert80** [comment]
@RiseT thanks but "Gruppe wurde aktualisiert." has a trailing  period at the end. Do you know if the English version has a period at the end?

**Comment by RiseT** [comment]
@Norbert80 Oh, you're right. That's an inconsistency indeed. I guess since the majority of these strings doesn't have a period at the end, that's the way it is wanted. But I could be wrong of course.

**Comment by Norbert80** [comment]
"Updated the group."
"You set disappearing message time to 1 week" (dot at the end missing)

It has to be investigated if further notification messages are missing dots.

**Comment by Norbert80** [comment]
@moxie0 would take a decision on that?

**Comment by 2-4601** [comment]
Don't know if the stance is dots or nots but it's probably not a good idea to start changing the strings just for punctuation. When a string is changed in Transifex all languages need to be retranslated for that string or it will default to English. Thus only fix strings when there's a clear typo or ambiguous or incorrect expression. Then you can also correct punctuation.

**Comment by Norbert80** [comment]
I found that the messages for generating groups, adding members and changing group names have dots at the end.

So the consequent solution seems in fact to be to add punctuation to these timer change messages.

**Comment by RiseT** [comment]
Changing these strings is no problem. The real question is: Dot or not? What is intended and what is the mistake?

**Comment by FeuRenard** [comment]
This is fixed by f5966af, issue can be closed.
