### ISSUE TITLE
No google play service , can not use signal android

### ISSUE THREAD

**Issue by netroby** [WhisperSystems/Signal-Android#5767]
I have android phone without google play service. i hate google, i do not want google watch me . i have no Google service package installed no play store, no google play. 
so i can not install signal android. 

Please help me out. i want using signal , but do not want to install google play service.

**Comment by rainerzufall** [comment]
You clearly have not searched for similar issues. There is for example #127 (https://github.com/WhisperSystems/Signal-Android/issues/127) or #1000 (https://github.com/WhisperSystems/Signal-Android/issues/1000). A lot of people would like to have this (including me), but opening up duplicates does not make it happen. So please close your issue.

**Comment by FeuRenard** [comment]
Maybe these tweets can help anyone:
https://twitter.com/whispersystems/status/783817903120318465
