### ISSUE TITLE
Timer updates are displayed in notifications

### ISSUE THREAD

**Issue by FeuRenard** [WhisperSystems/Signal-Android#5768]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Timer update messages are shown in notifications and are marked as "Media message".

### Steps to reproduce
- set your notification settings to "Name and message" on device A
- close Signal (go to homescreen) on device A
- go to conversation with device A on phone B
- change the disappearing message time on device B
- send a message from device B to device A

**Actual result:** The timer message is displayed and in front of it marked as "Media message"
**Expected result:** The timer update should not appear at all in the notification? At least it shouldn't be marked as "Media message".

### Screenshots
Device 1
![screenshot_2016-10-10-18-10-16](https://cloud.githubusercontent.com/assets/16167751/19243666/c581773e-8f18-11e6-8f86-8ecd89970683.png)
Device 2
![screenshot_2016-10-10-18-23-29](https://cloud.githubusercontent.com/assets/16167751/19243665/c57e9d48-8f18-11e6-9b1f-84203712b7df.png)
"Nachricht mit Medieninhalten" means "Media message"

### Device info 1

**Device:** Sony Xperia U
**Android version:** 4.4.4 (CyanogenMod)
**Signal version:** 3.20.3

### Device info 2

**Device:** Fairphone 2
**Android version:** 5.1.1
**Signal version:** 3.20.0

**Comment by cascheberg** [comment]
I think timer updates should be displayed in the notification, because tapping "marked read" from the notification will now start the timer, which is irritating if the user does not know about it. Any thoughts?
