### ISSUE TITLE
Unable to register - fails in step 4

### ISSUE THREAD

**Issue by einalex** [WhisperSystems/Signal-Android#5774]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Registration fails in step 4 after successfully receiving SMS.
Situation as follows:
new phone
new carrier
same number
unregistered from signal via website

### Steps to reproduce
- start signal
- enter phone number
- click register
- get frustrated

**Actual result:** Registration process stops with a connection error.
**Expected result:** Registration process is able to connect to server and completes successfully.

### Device info
**Device:** Nexus 5X
**Android version:** google's stock android 7.0.0
**Signal version:** 3.19.1

### Link to debug log
unavaillable. Here is the [logcat.txt](https://github.com/WhisperSystems/Signal-Android/files/522285/logcat.txt). (btw it would be highly appreciated if you could keep private data out of adb logs as well (device unique id's should be sufficient in most cases).

**Comment by moxie0** [comment]
sorry this should be resolved

**Comment by einalex** [comment]
Hi moxie!
You mean I fell victim to a git commit - app update delay?

Btw I really enjoyed your sailing documentary. :)

**Comment by moxie0** [comment]
It was a server side issue. Thanks!
