### ISSUE TITLE
Call dials and "Network Failed" comes up

### ISSUE THREAD

**Issue by shondray** [WhisperSystems/Signal-Android#5777]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

When making a call it continues "dialing" but never connects. I will eventually get a "Network Failed" on the screen and then I get sent back to the contacts page.
### Steps to reproduce
- Choose a contact
- Choose lock and phone in top right corner

**Actual result:** Stays in "Dialing" mode for 10-15 seconds and then "Network Failed" comes up on the screen and returns to the contact page.
**Expected result:** Call would connect.
### Device info

**Device:** samsung SGH-M919 (jgedlteue)
**Android version:** 6.0.1 (24095844ea, cm_jfltetmo-userdebug 6.0.1 MOB31E 24095844ea test-keys)
**Signal version:** 3.20.4
### Link to debug log

https://gist.github.com/anonymous/fef4805f2774e75dc8a98ffb6c2f9b11

**Comment by shondray** [comment]
Got more updated logs.

From my phone when I tried to make a call to phone B: https://gist.github.com/anonymous/f6366f634b309427ffbde8a66f71704d

Shortly after I tried a phone call from B to my phone: https://gist.github.com/anonymous/9e17bebada34fb2933174e66a076eef2

Hopefully this may shed some light on the issue.

I know nothing about any of this but when in the log it says that there are no subscribers for event 30171 I think that may point to something.

**Comment by shondray** [comment]
Tried it again and my end kept ringing while phone B called a missed call message.

My log: https://gist.github.com/anonymous/7e986a7550e822896e221080db5b4536

Phone B: https://gist.github.com/anonymous/becd893e16f62bdeeb52fbe7b42195c0

I am going to unregister and retry.

**Comment by shondray** [comment]
Re-registered both phones, then uninstalled/reinstalled and still the same issue. Very frustrating to say the least. Its lime the server is purposely not wanting to recognize my phone.

**Comment by 2-4601** [comment]
Have you tried making calls on different networks? Cellular or other Wi-Fis?

**Comment by shondray** [comment]
Yes I have called on both cell network and WiFi with the same result.

**Comment by shondray** [comment]
Small breakthrough. Tried both cell phones on cell network and they connected to each other. Only thing was phone B could not hear me at all. O could hear phone B perfectly fine.

My log: https://gist.github.com/anonymous/382312069e232498586fecdb54d3e1c3

Phone B log: https://gist.github.com/anonymous/d6011aff86d7922e7d7827d48b890927

**Comment by 2-4601** [comment]
Do you have some permission restriction software or firewall on your phone?

**Comment by shondray** [comment]
Signal has all the permissions is requests and I do not have a firewall on my phone.

**Comment by shondray** [comment]
Now the calls will connect even on same WiFi but phone b isn't getting any audio. When I speak through my phone I get a delayed echo of what I just said.

Log: https://gist.github.com/anonymous/498a199577877f967705a3745371c6dc

 B: https://gist.github.com/anonymous/3cde8c83c31cced78d7a5d3360124db5

**Comment by 2-4601** [comment]
Can you make normal calls with other Signal users besides phone B?

**Comment by shondray** [comment]
Nope. I called phone C and got the same issue. Call goes through, but they dont hear anything and I can hear them clearly. I also hear myself on a 2-3 second delay.

My log :https://gist.github.com/anonymous/ad16b1935cbf0435a7f36670420d0f9c

**Comment by 2-4601** [comment]
@shondray Have you had the chance to try newer Signal versions? In 3.31 the calling has been changed to WebRTC

**Comment by shondray** [comment]
Yeah I actually flashed my phone to a different version of CM. So far this has worked well. On Monday it happened again where the person on the other side couldn't hear me at all, but It cleared itself up the next day. Thanks again for your help!
