### ISSUE TITLE
Disappearing message can be viewed in notification dropdown preview without starting deletion timer

### ISSUE THREAD

**Issue by lem503** [WhisperSystems/Signal-Android#5781]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Disappearing messages can be viewed repeatedly and without starting a timer when they are in the notification drawer.

### Steps to reproduce
- Have message notifications enabled
- Receive a disappearing message
- Open android notification drawer to read message

**Actual result:** The message can be viewed without a time limit via the notification drawer. Closing and reopening the notification drawer does not start the deletion timer either, hence messages can be viewed repeatedly.

**Expected result:** I would expect the message to be hidden until it is either opened in app (to start the deletion timer) or would expect to be able to start a timer by previewing the message in the notification drawer after actively clicking to read message - I would imagine that this could happen in a similar fashion as is possible already when replying to a message directly from the notification drawer, without fully entering the app.

### Device info

**Device:** Oneplus 2
**Android version:** 6.0.1
**Signal version:** 3.20.4

### Link to debug log

If you want I can supply one, but don't think this is necessary here.

**Comment by sweeper3000** [comment]
Would it be possible when the message expires, for it to be replaced with *message expired* in the notification? Or maybe kill the notification like it does when you read a message in signal desktop

**Comment by 2-4601** [comment]
You can tap the "MARK READ" button on the notification to start the timer. Not sure if it's trivial to otherwise detect just from the notification when you have read a certain message. Especially since the notifications are bundled together. You can also adjust the visibility of your notifications from Signal's settings. Or use the passphrase lock.

**Comment by moxie0** [comment]
We're comfortable with this behavior. Even if we abuse the accessibility API to determine if a notification was visible, it's still not clear that it has been read.

**Comment by yawnoc** [comment]
How about redacting the content of all disappearing messages in notifications (e.g. with the string "\<disappearing message\>"), so that disappearing messages can *only* be read in the app?

**Comment by mgorinova** [comment]
Hi was the fix to [hide disappearing messages' content](https://github.com/signalapp/Signal-Android/pull/10791) ever merged in the main app? I was able to read a disappearing message in notifications hours before I started the actual disappearing timer by opening the message in Signal. Would be great to have the disappearing messages' content hidden in notifications.
