### ISSUE TITLE
Notification message shown repeatedly for specific contact

### ISSUE THREAD

**Issue by merkste** [WhisperSystems/Signal-Android#5782]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

I turned on "repeat alerts" (one time) after the new update. No conversation appeared to contain unread messages. Since, I repeatedly get the notification that a particular thread has three new **locked** messages, although Signal is unlocked. I tried to open the conversation, to mark the messages as read in the notification itself and to mark all messages as read from the dots-menu. However, the notification pops up again after some time.
The conversation in question is pretty long (>>> 500 messages) and old but otherwise seem unsuspicious. I also attempted to disable notification temporarily for that conversation and in general - did not help.
### Steps to reproduce

Unfortunately, I do not know how to trigger the bug for a conversation.
### Device info

**Device:** Motorola Moto G 3rd Gen
**Android version:** 6.0.1
**Signal version:** 3.20.4
### Link to debug log

https://gist.github.com/443b78af9386dc4b2bb2efee981ebf57

**Comment by merkste** [comment]
It even happens while writing a message in that conversation.

**Comment by He-Ro** [comment]
I experience most likely the same issue here.
## Device info
Device: Sony Xperia Z5 compact
Android version: 6.0.1
Signal version: 3.21.3
## Debug log
https://gist.github.com/anonymous/747ac1b0e16bc1552775788670f3db12

The issue appeared randomly for one conversation with another Signal contact.
I have repeated alerts set to two times and have no passphrase for Signal.
Now, every time the contact sends a message and I read it before the repeated alert is triggered, a notification about a locked message pops up at about the same time the repeated alert would be triggered.
Selecting "Mark read" from the notification dismisses the notification, but the problem persists.
Even resetting the secure session did not help, the problem persists.

**Comment by He-Ro** [comment]
Just some additional information:
Here is a screenshot to illustrate the situation. The first message is from another contact. The bottom three messages are from the contact, that has the issue. As you can see, the messages are displayed in clear, but the last message is the "locked message…" message, which should not be there.

![anonymised_screenshot](https://cloud.githubusercontent.com/assets/3579374/20034132/f3feeb82-a3b3-11e6-9107-067ba5095e0c.png)

In my last comment, I noted, that the "locked message…" reappears when the affected contact sends a message. I have now even seen this, when another Signal contact sends me a message and after 2 minutes the "locked message…" notification appears.

**Comment by janvlug** [comment]
I still have this issue, here are two debug logs taken immediately after the incorrect notification:
https://gist.github.com/e6a725a125361fc2d784bd4292412965
https://gist.github.com/d44debfa28dfb9474dff81bd43a7cf57
Is there anything I can do to further investigate/debug this issue?

**Comment by moxie0** [comment]
So I understand this better, if you disable "repeated" notifications, do you stop seeing "locked message?"  And then when you re-enable "repeated" notifications, you start seeing it again?

**Comment by merkste** [comment]
Yes Moxie, that's exactly the behavior I am seeing. The affected conversation is pretty long. Maybe this somehow prevents marking certain messages as read effectively?

**Comment by moxie0** [comment]
Pretty sure that change should do it, sorry for the trouble everyone, let me know if this doesn't resolve things for you in the next release
