### ISSUE TITLE
Double tick color for read message

### ISSUE THREAD

**Issue by AndreaHistoryX** [WhisperSystems/Signal-Android#5789]
OLD IDDUE
> Can you add a double tick color to show when a message is read??
> So i can know when a contact read my message and my contact can see when i read a message also when i tap mark as read in notification tab

If you can't add this feature I would like if you add a new button in notification tab so when i receive a message I can "mark as read", I can "quick reply" and ALSO I can SEND "MESSAGE READ" in that chat so I can tell someone that i've read his/her message very quickly and simply in a tap

thank you in advance

EDIT

**Comment by FeuRenard** [comment]
These issues should cover the content of your issue:
#2667 Optionally send read receipts for TextSecure messages
#4821 Manual read receipts

So this issue here can be closed as there shouldn't be duplicate issues.

**Comment by AndreaHistoryX** [comment]
thanks for the information, I read the two issues and I hope that at least is added the automatic answer "message read"
change the title
