### ISSUE TITLE
Safety numbers should be copyable

### ISSUE THREAD

**Issue by stupidsquirrel** [WhisperSystems/Signal-Android#5795]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

When viewing safety numbers for a contact, the only option is to scan them. I'm not able to copy the numbers to my clipboard and paste them elsewhere.
### Steps to reproduce
- Click on conversation
- Click settings
- Click conversation settings
- Click verify safety numbers
- Attempt to copy to clipboard

**Actual result:**

Nothing happens on long-press.

**Expected result:**

Something should be highlighted and some options should come up, prompting for copying and pasting.
### Device info

**Device:** Nexus 6P
**Android version:** 7.1.1
**Signal version:** 3.20.4

Note: posting this from a throwaway account since my real account seems to be banned for some reason.

**Comment by FeuRenard** [comment]
I would suggest to implement a share button. Is there a use case, which would still require copying to clipboard?

**Comment by johanw666** [comment]
Email clients that don't understand sharing.

**Comment by stupidsquirrel** [comment]
Well most of my contacts don't live close to me so it isn't possible to scan the QR code. Fingerprints don't need to be secret so I could just tweet it to people and verify it like that.

**Comment by FeuRenard** [comment]
Sharing text to Twitter works. And in general the workflow via share button should be slightly faster than copy&paste.

@johanw666 Sharing to K9 works for me. Try the steps below:

- Open Signal
- Tap the three dots in the top right corner
- Choose "Invite friends"
- Tap the button "Share"
- Choose K9 (or e.g. Twitter)

**Comment by johanw666** [comment]
Sorry I must have overlooked that in the rather long list I got. However, the other mailclient I use - OWM, it's a paid Outlook Web client I use for reading corporate mail - does not.

**Comment by RiseT** [comment]
On iOS:
https://github.com/WhisperSystems/Signal-iOS/commit/1e417ea93fc2aea660653c93c3948338d32dee15

**Comment by iav** [comment]
@FeuRenard 

>     Open Signal
    Tap the three dots in the top right corner
    Choose "Invite friends"
    Tap the button "Share"
    Choose K9 (or e.g. Twitter)

Then I will share url and text about welcome into signal. 
But topic was about a check of authentication of contact already in signal via communication channel different from qr code scanning with phone camera.
There should be kind of text that cound be copyed from some other app and pasted into signal contact to see "yes, it's contact I see" or "no, I see other key, one of channel compromised".

**Comment by FeuRenard** [comment]
This issue is solved by https://github.com/WhisperSystems/Signal-Android/commit/b55a7ff5c05adc0b2e5c5c0b2b54f116f964cec3 . The following menu appears after long-pressing the safety numbers:
![device-2016-11-15-112332](https://cloud.githubusercontent.com/assets/16167751/20302018/faa33d84-ab25-11e6-97f5-bee6e0397798.png)
