### ISSUE TITLE
GCM alternative for custom roms without gapps

### ISSUE THREAD

**Issue by godfuture** [WhisperSystems/Signal-Android#5806]
I have:
- [x] searched open and closed issues for duplicates
https://github.com/WhisperSystems/Signal-Android/issues/1106
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal does not notify me in case a friend has responded in chat, when my phone is in standby or Signal is in background. I do not have gapps installed, and therefore lack of GCM.

### Steps to reproduce
- Start a chat with someone
- Wait till he/she responds
- Set Signal to background and turn your display off
- Check if you got notified automatically

**Actual result:** Sent messages are only received when Signal is running in front (as active app).
**Expected result:** Signal is informing me about new messages.

### Device info

**Device:** Samsung Galaxy S 4 Mini (GT9195)
**Android version:** 6.0.1
**Signal version:** 3.20.4

**Comment by nrizzio** [comment]
Please see the extensive discussion at #127.

**Comment by 2-4601** [comment]
Closing as duplicate.
You can try microg

**Comment by mateoeh** [comment]
Also see the [microG project](https://microg.org/download.html) for an open-source GMS/GCM implementation. There is simply no viable alternative to GCM at this stage.

**Comment by godfuture** [comment]
I had a look at this. MicroG seems nice but requires quite a lot manual work in the system to get GCM working (blankstore or fake gapps required for cyanogenmod as singature spoofing is not possible).

Anyhow, Threema allows polling to their servers. Which looks quite straight forward. Isnt it possible to add a polling for Signal as well?
