### ISSUE TITLE
Keyboard should hide after Giphy search

### ISSUE THREAD

**Issue by skulumani** [WhisperSystems/Signal-Android#5807]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After using the new Giphy gif search 🎆 , the keyboard should automatically hide when pressing the return/enter button.

Great job on the app and all the hard work 👏  👍 

### Steps to reproduce
- Go to Giphy and tap the search input field
- Type a search string and press return/enter
- Keyboard is still displayed (shows a shift in the top row on my phone) 
- Must use keyboard down arrow to view all of the results

**Actual result:** Keyboard is still displayed and obscures half of the screen, covering all the sweet, sweet GIFS
**Expected result:** After searching and hitting return the keyboard should disappear

### Screenshots
- Search string entry
<img src="https://cloud.githubusercontent.com/assets/5266022/19708403/48843f3e-9aec-11e6-961e-51086a45e9c7.png" width="200" />
- After pressing return/enter
<img src="https://cloud.githubusercontent.com/assets/5266022/19708404/48847800-9aec-11e6-8040-17f6511991a1.png" width="200" />
- Manually hiding the keyboard
<img src="https://cloud.githubusercontent.com/assets/5266022/19708401/48817b28-9aec-11e6-9423-63fff144b56e.png" width="200" />

### Device info

**Device:** 2013 Moto X1
**Android version:** 5.1
**Signal version:** 3.21.0

### Link to debug log
Captured immediately after the steps above 

[Debug log](https://gist.github.com/anonymous/03d4fc931b55854321c7a13f0a7bafb1)

**Comment by moxie0** [comment]
Hmm I dunno. It's worth thinking about, but generally when I'm searching I like to have what I searched for visible so that I can easily modify it or clear it.  The search bar hides as soon as you start scrolling, which I think is the moment that you've "accepted" the search results in a way.  I'm going to leave it the way it is for now, but I'll keep this in the back of my mind.

**Comment by skulumani** [comment]
That's a good point that I didn't consider. I failed to notice that the search bar hides, but that's another way to handle the situation.

I appreciate all the hard work.

**Comment by rainerzufall** [comment]
I just wanted to report the same issue, because it does not close after scrolling.

Log: https://gist.github.com/anonymous/3471faa0703d385811777fed9ba17f84

**Comment by moxie0** [comment]
@rainerzufall seems like you have an android issue, that's all happening within the coordinatorlayout

**Comment by rainerzufall** [comment]
Ah. That's too bad! :- / thanks for having a look!

**Comment by 2-4601** [comment]
I'm also experiencing the issue where the keyboard does not get dismissed after scrolling on
- 5.0 https://gist.github.com/b1386651577b03402894301fd50e0836
- 6.0.1 https://gist.github.com/fca4cf98ddf4b7d85fbea5279b8061c1

I'm using Google keyboard.

**Comment by moxie0** [comment]
Oh sorry I read the original thing wrong, I thought you meant the search bar. Yeah, the keyboard should probably dismiss itself.
