### ISSUE TITLE
Allow notification messages in muted groups

### ISSUE THREAD

**Issue by siccovansas** [WhisperSystems/Signal-Android#5815]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Feature description

It is currently not possible to still receive notification messages for a group when you have enabled the `Mute notifications` option in a group chat. In other words, both the notification sound and the notification messages are muted. WhatsApp gives you the option to still receive notifications for a group chat after you muted it, thus effectively only muting the notification sound. I received a complaint from a user who just converted from WhatsApp to Signal who would like this feature to also be present in Signal.
### Steps to reproduce
- open a group chat
- click on the options menu > `Mute notifications`

**Wanted result:** - ideally there would be a check box allowing you to choose if you still want to receive notification messages 
### Screenshots

This shows how WhatsApp implemented this feature
![screenshot_20161027-183245](https://cloud.githubusercontent.com/assets/696839/19776691/6df351bc-9c75-11e6-8028-52351f8b7458.png)
### Device info

**Device:** Nexus 5
**Android version:** 6.0.1
**Signal version:** 3.20.4

**Comment by cascheberg** [comment]
Similar discussion in #3957, would be fixed by #4957.

**Comment by 2-4601** [comment]
Fixed by #4957
