### ISSUE TITLE
Group avatar stuck to some old version after change

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/Signal-Android#5817]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
It seems changing the group avatar has a weird issue where it's stuck to some old (the last successfully changed?) group avatar. It's kinda weird that the old one can be from an entirely different group :/
Also it's not just a local (cache) issue. The wrong avatar gets actually sent to every member.

### Steps to reproduce
- change the group avatar to a new photo

**Actual result:** group avatar is stuck to some old avatar (possibly from another group)
**Expected result:** group avatar should change to the new image

### Device info

**Device:** bq Aquaris E4.5 and Nvidia K1
**Android version:** 5.0 and 6.0.1
**Signal version:** 3.21.0

### Link to debug log
https://gist.github.com/f7514791daed60132fd95e57d387e236

This is kinda shitty report. Would be great if someone tried to reproduce. I have this issue on two devices.

**Comment by 2-4601** [comment]
Downgrading to 3.20.4 fixes the issue.

**Comment by cascheberg** [comment]
Confirmed on 3.21.1!
* Group A with no picture: successfully select and saved group picture A
* try to edit group A picture: select new picture, edit screen preview still shows picture A
* trying to edit any other group with an existing group image: always shows picture A in the edit group screen as well

**Comment by moxie0** [comment]
huh so this is fully reproducible on 3.21.1 but not on 3.20.4?

**Comment by FeuRenard** [comment]
I noticed that some cache strategies for Glide were changed when Giphy was introduced. Especially `ContactPhotoFactory.java` seems interesting in this case.
So maybe something similar to this happens (highly speculative):
http://stackoverflow.com/questions/33443146/remove-image-from-cache-in-glide-library

**Comment by 2-4601** [comment]
> huh so this is fully reproducible on 3.21.1 but not on 3.20.4?

Yes. Just tested again with 3.21.1 and could reproduce the bug. Downgraded to 3.20.4 and the issue is gone.

**Comment by moxie0** [comment]
thanks yeah it was a caching thing
