### ISSUE TITLE
Crash when viewing thread with media messages

### ISSUE THREAD

**Issue by mdecker** [WhisperSystems/Signal-Android#5818]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
---
### Bug description

The app crashes immediately upon viewing a message thread that contains a media message (i.e. image).
The thread can never be viewed, not even in airplane mode. It is also not possible to delete the thread: moving to archive works, but trying to delete from archive results in the same crash.

Because I expected it to be a corrupt database issue I have completely removed the signal app data and re-registered my phone. The app worked again but was more unstable than I previously experienced. As soon as I received a media message the thread makes the app crash again like before.

Two things I did before I ran into those problems:
1. Updated Fairphone OS from FP2 release 1.6.1 to 1.8.1
2. Updated Android Web View from Play Store

I have no idea if any of those events are really related to the crashes, though.
Just to try I have also uninstalled the Web View updates but that did not lead to an improvement.

Note: The updates to the Fairphone OS should only have contained the latest google security fixes up to October and no other feature changes.
### Steps to reproduce
- receive media message from contact
- try to open message from notifications or from contact list in app

**Actual result:** App force closes immediately
**Expected result:** Message thread should be displayed
### Screenshots

none
### Device info

**Device:** Fairphone2
**Android version:** 5.1 (r4275.1_FP2_gms66_1.8.1)
**Signal version:** 3.20.4
### Link to debug log

https://gist.github.com/anonymous/845adc40ff80f0d3fdd506641bc41f2c

**Comment by rainerzufall** [comment]
I cannot reproduce on my Fairphone 2, media messages don't cause any trouble.

**Device:** Also Fairphone2
**Android version:** also 5.1 (r4275.1_FP2_gms66_1.8.1)
**Signal version:** 3.21.1 (but it also did not make any troubles before)

**Comment by mdecker** [comment]
Your signal version is newer than mine. I'd love to give that a try but cannot find it on the Play Store. What's your source and is this an official release, yet?

**Comment by rainerzufall** [comment]
Hm. I am no dev, but I am not confident that it would change with 3.21.1 (which is currently in beta), because I had no problems with Signal 3.20.4 or any other version before and I also did the updates you mentioned. If you want to join the beta anyway you can find the info here: https://github.com/WhisperSystems/Signal-Android#joining-the-beta

**Comment by moxie0** [comment]
Looks like the crash is happening in libstagefreight native code. Seems like an OS thing.

**Comment by mdecker** [comment]
It looks like this was indeed a general phone screw up. I've completely reinstalled/reset my phone and the problem went away.
Thanks for having a look at it anyway.
Closing.
