### ISSUE TITLE
Add search for  Giphy GIFs and stickers

### ISSUE THREAD

**Issue by oceanofsolaris** [WhisperSystems/Signal-Android#5819]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
This is a feature request/wish:
A recent update added Giphy support. While I am not too convinced by the usefulness of this, I understand that for many users it is very important. However, trying to find a useful GIF or sticker in Signal is a fools errand of scrolling through a myriad of rather low-quality GIFs/stickers (does it just display the most recently uploaded ones?). A search field would in my opinion go a long way to make this more useful.

### Steps to reproduce
- Try to send a friend a "Thanks Obama" GIF (example specimen: https://giphy.com/gifs/13ypZYdIckeO5O).
- Select Attachment->Giphy.
- Scroll through endless list of other GIFs that don't express the sentiment I try to convey.

**Actual result:** I give up before ever sending the message.
**Expected result:** I should be able to find a GIF if I already roughly know what I am looking for.

### Device info

**Device:** Moto X 2013 (ghost)
**Android version:** 6.0.1 (Cyanogenmod)
**Signal version:** 3.21.1

**Comment by FeuRenard** [comment]
There was a search field in the initial PR:
https://github.com/WhisperSystems/Signal-Android/pull/5788#issuecomment-254892515
Is it gone in the beta version?

**Comment by oceanofsolaris** [comment]
Sorry, I feel awefully dumb now. It seems it is still there (but I could swear it didn't show before?!). Anyway, I will close this bug.
