### ISSUE TITLE
Signal crash when timeout reading from giphy

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/Signal-Android#5825]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When scrolling through giphy images Signal crashed.

### Steps to reproduce
- Unable to reproduce till now.

**Actual result:** I see a message "Unfortunately, Signal has stopped" and Sigal restarts.
**Expected result:** Something else, not a crash.

### Device info
**Device:** Sony Xperia Z1 Compact
**Android version:** 4.4.4
**Signal version:** 3.21.2

After Signal restarted I immediately made a debug log:
https://gist.github.com/anonymous/0c874c81bcef51a0e7ec2f25dfd0269c

The crash seems to be at line 83. After that there are some errors about unresolved methods.

**Comment by moxie0** [comment]
Those are just stack traces, not a crash. The crash is a segfault which happens later. Looks like you're running xprivacy, so it's either that or maybe OOM. I'm going to close this since there's nothing usable in the log. Thanks!

**Comment by moxie0** [comment]
When you're scrolling through the giphy images, they're stills and not animated right?

**Comment by johanw666** [comment]
I have Xposed installed, but I disabled it on a few apps I trust like Signal, so it should not interfere with Signal. When I'm scrolling through the giphy images they do animate. I thought the animation was only disabled on low-memory devices? On an el cheapo phone I use mainly as navigator (Acer Z205 with 4.4.4 and 512MB memory) they don't animate.

**Comment by johanw666** [comment]
Another point: I saw that the Signal cache size had grown to 250MB on that Sony device... Quite large IMO. When I cleared the cache and did one search on giphy it already grew back to 46MB. Is this size limited? And is this the intended behaviour?
