### ISSUE TITLE
App permissions can't be edited in the OS

### ISSUE THREAD

**Issue by mkae** [WhisperSystems/Signal-Android#5826]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Permissions if Signal app can't be edited in the OS

### Steps to reproduce
- go to app permissions for Signal in system's settings
- try to disable one of Signal's listed permissions (all are switched to enabled)

**Actual result:** Settings app denies permission change and states that the app was designed for an older Android version and that denying the permission may cause the app to no longer function.

**Expected result:** Signal should respect additional restrictions of its needed ones imposed by the user and deal with it.

### Device info
**Device:** One Plus X
**Android version:** 6.0.1 - CM13
**Signal version:** 3.20.4

**Comment by moxie0** [comment]
can't reproduce, sounds like a CM thing

**Comment by Tonat** [comment]
Can reproduce on stock. You get the popup message "This app designed for an older Version of Android. Denying permission may cause it to no longer function as intended." BUT you can just hit "Deny" anyway and Signal works completely fine. 
Samsung Galaxy S7, stock Android 6.0.1 (TouchWiz)

**Comment by riyapenn** [comment]
From a user: "I believe that the targetSdkVersion in the APK manifest is less than API level 23, which is the minimum target SDK version necessary to correctly support run time permissions on Android."

**Comment by moxie0** [comment]
It will show you a warning, but it works fine.
