### ISSUE TITLE
Crash while browsing GIFs (GIPHY)

### ISSUE THREAD

**Issue by dcherian** [WhisperSystems/Signal-Android#5829]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Multiple crashes while scrolling up and down through GIF list from GIPHY.

### Steps to reproduce
I've had 3 crashes. All of them happened while scrolling up and down through the GIF list quite quickly. The GIFs had not loaded yet, all I was seeing were multicolored boxes.

**Actual result:** Signal crashes.
**Expected result:** Signal doesn't crash.

### Device info
**Device:** Moto G 2013 Falcon
**Android version:** CM 13.1 nightly
**Signal version:** 3.21.2

### Link to debug log

*3.21.2 crash* https://gist.github.com/anonymous/f2e78794ad09df1dfae847492ebd4030
`--------- beginning of crash
10-31 16:23:19.864  5164  5164 E AndroidRuntime: FATAL EXCEPTION: main
10-31 16:23:19.864  5164  5164 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 5164
10-31 16:23:19.864  5164  5164 E AndroidRuntime: Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
10-31 16:23:19.864  5164  5164 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.isEmpty()' on a null object reference
10-31 16:23:19.864  5164  5164 E AndroidRuntime: 	at org.thoughtcrime.securesms.giph.ui.GiphyFragment.onLoadFinished(GiphyFragment.java:69)
10-31 16:23:19.864  5164  5164 E AndroidRuntime: 	at org.thoughtcrime.securesms.giph.ui.GiphyFragment.onLoadFinished(GiphyFragment.java:28)
10-31 16:23:19.864  5164  5164 E AndroidRuntime: 	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:427)
10-31 16:23:19.864  5164  5164 E AndroidRuntime: 	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:395)
10-31 16:23:19.864  5164  5164 E AndroidRuntime: 	at android.support.v4.content.Loader.deliverResult(Loader.java:104)
10-31 16:23:19.864  5164  5164 E AndroidRuntime: 	at org.thoughtcrime.securesms.util.AsyncLoader.deliverResult(AsyncLoader.java:48)
10-31 16:23:19.864  5164  5164 E AndroidRuntime: 	at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:223)
10-31 16:23:19.864  5164  5164 E AndroidRuntime: 	at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:61)
10-31 16:23:19.864  5164  5164 E AndroidRuntime: 	at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:461)
10-31 16:23:19.864  5164  5164 E AndroidRuntime: 	at android.support.v4.content.ModernAsyncTask.access$500(ModernAsyncTask.java:47)
10-31 16:23:19.864  5164  5164 E AndroidRuntime: 	at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:474)
10-31 16:23:19.864  5164  5164 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-31 16:23:19.864  5164  5164 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
10-31 16:23:19.864  5164  5164 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
10-31 16:23:19.864  5164  5164 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-31 16:23:19.864  5164  5164 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-31 16:23:19.864  5164  5164 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

*3.21.0 crash* https://gist.github.com/anonymous/e92444ecd5901be6b23621d1e795a31d

`10-25 21:12:35.725   689   689 E WindowManager: 
10-25 21:12:35.725   689   689 E WindowManager: android.view.WindowLeaked: Activity org.thoughtcrime.securesms.ConversationActivity has leaked window android.widget.PopupWindow$PopupDecorView{f9fc219 V.E...... ......ID 0,0-408,672} that was originally added here
10-25 21:12:35.725   689   689 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:372)
10-25 21:12:35.725   689   689 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
10-25 21:12:35.725   689   689 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:86)
10-25 21:12:35.725   689   689 E WindowManager: 	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1258)
10-25 21:12:35.725   689   689 E WindowManager: 	at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1110)
10-25 21:12:35.725   689   689 E WindowManager: 	at android.support.v7.internal.widget.AppCompatPopupWindow.showAsDropDown(AppCompatPopupWindow.java:74)
10-25 21:12:35.725   689   689 E WindowManager: 	at android.support.v4.widget.PopupWindowCompatKitKat.showAsDropDown(PopupWindowCompatKitKat.java:30)
10-25 21:12:35.725   689   689 E WindowManager: 	at android.support.v4.widget.PopupWindowCompat$KitKatPopupWindowImpl.showAsDropDown(PopupWindowCompat.java:54)
10-25 21:12:35.725   689   689 E WindowManager: 	at android.support.v4.widget.PopupWindowCompat.showAsDropDown(PopupWindowCompat.java:93)
10-25 21:12:35.725   689   689 E WindowManager: 	at android.support.v7.widget.ListPopupWindow.show(ListPopupWindow.java:654)
10-25 21:12:35.725   689   689 E WindowManager: 	at android.support.v7.internal.view.menu.u.tryShow(MenuPopupHelper.java:159)
10-25 21:12:35.725   689   689 E WindowManager: 	at android.support.v7.widget.ActionMenuPresenter$OpenOverflowRunnable.run(ActionMenuPresenter.java:756)
10-25 21:12:35.725   689   689 E WindowManager: 	at android.os.Handler.handleCallback(Handler.java:739)
10-25 21:12:35.725   689   689 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-25 21:12:35.725   689   689 E WindowManager: 	at android.os.Looper.loop(Looper.java:148)
10-25 21:12:35.725   689   689 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
10-25 21:12:35.725   689   689 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
10-25 21:12:35.725   689   689 E WindowManager: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-25 21:12:35.725   689   689 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`
*another 3.21.0 crash* https://gist.github.com/anonymous/3b8a7d44bf189974c19ed91e61ab66f3
`-------- beginning of crash
10-25 21:38:35.976   689   689 E AndroidRuntime: FATAL EXCEPTION: main
10-25 21:38:35.976   689   689 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 689
10-25 21:38:35.976   689   689 E AndroidRuntime: Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
10-25 21:38:35.976   689   689 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 1638412 byte allocation with 470120 free bytes and 459KB until OOM
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at com.bumptech.glide.gifdecoder.GifDecoder.setData(GifDecoder.java:380)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at com.bumptech.glide.load.resource.gif.GifDrawable.<init>(GifDrawable.java:92)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at com.bumptech.glide.load.resource.gif.GifDrawable$GifState.newDrawable(GifDrawable.java:368)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at com.bumptech.glide.load.resource.drawable.DrawableResource.get(DrawableResource.java:32)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at com.bumptech.glide.load.resource.drawable.DrawableResource.get(DrawableResource.java:16)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at com.bumptech.glide.load.engine.EngineResource.get(EngineResource.java:44)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:487)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at com.bumptech.glide.load.engine.Engine.load(Engine.java:155)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at com.bumptech.glide.request.GenericRequest.onSizeReady(GenericRequest.java:449)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at com.bumptech.glide.request.target.ViewTarget$SizeDeterminer.getSize(ViewTarget.java:211)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at com.bumptech.glide.request.target.ViewTarget.getSize(ViewTarget.java:100)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at com.bumptech.glide.request.GenericRequest.begin(GenericRequest.java:272)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at com.bumptech.glide.request.ThumbnailRequestCoordinator.begin(ThumbnailRequestCoordinator.java:90)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at com.bumptech.glide.manager.RequestTracker.runRequest(RequestTracker.java:37)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at com.bumptech.glide.GenericRequestBuilder.into(GenericRequestBuilder.java:661)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at com.bumptech.glide.GenericRequestBuilder.into(GenericRequestBuilder.java:697)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at com.bumptech.glide.DrawableRequestBuilder.into(DrawableRequestBuilder.java:448)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at org.thoughtcrime.securesms.giph.ui.GiphyAdapter.onBindViewHolder(GiphyAdapter.java:154)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at org.thoughtcrime.securesms.giph.ui.GiphyAdapter.onBindViewHolder(GiphyAdapter.java:31)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5138)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4433)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4326)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.support.v7.widget.LayoutState.next(LayoutState.java:86)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1415)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.support.v7.widget.StaggeredGridLayoutManager.scrollBy(StaggeredGridLayoutManager.java:1918)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.support.v7.widget.StaggeredGridLayoutManager.scrollVerticallyBy(StaggeredGridLayoutManager.java:1838)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1363)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2227)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:9301)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
10-25 21:38:35.976   689   689 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGro`

**Comment by FeuRenard** [comment]
When you browse GIFs (slowly), what do you see: animated GIFs or stills?

**Comment by dcherian** [comment]
Animated, if I wait long enough for them to load.
