### ISSUE TITLE
Signal crashes regurarly on Android 7.1 (LG Nexus 5X)

### ISSUE THREAD

**Issue by Janoosh** [WhisperSystems/Signal-Android#5838]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashes regurarly on Android 7.1 (LG Nexus 5X).
It turns silent every few minutes or even every few seconds. Either the person I talk to gets muted or I get muted. After that happens a few times, the app crashes totally (doesn't react when I press "call" button) and it's impossible to make or receive calls at all. 
When it crashes like that it's only possible to write messages, calls don't work at all. Only phone restart helps, which is really irritating and time consuming. And then it starts again right away. 

### Steps to reproduce
-Just receive or make a call using Signal 
-After a couple of seconds/or about minute or two in the conversation (I think it's more or less random, but happens every single time I use Signal) the person I talk to gets muted. I can't hear them at all. Them after some time either the voice comes back (and then gets muted again several times in a row in a matter of next minutes) or the coversation ends spontaneously and I'm taken back to contacts menu
-When the call drops, I'm unable to call anyone again or receive calls

**Actual result:** Call gets muted a couple of times and then drops. The app doesn't allow me to make calls and the other side is unable to call me as well.
**Expected result:** call doesn't drop or go mute until I press End Call button (big red). The app doesn't crash every single time and allows me to make and receive calls without restarting the phone

### Device info

**Device:** LG Nexus 5X
**Android version:** 7.1
**Signal version:** 3.21.3

### Link to debug log
https://gist.github.com/4992ca7edb89f637e9b2d08b9c9f8340

**Comment by benefaktorix** [comment]
Maybe we could merge this with #5836? Since calls are basically out of question since 3.21.3

**Comment by mmirg** [comment]
I see this same behavior on 7.1.1 (NPF10C).
[Debug log](https://gist.github.com/anonymous/9306b3b4897fecd3feff7799bad79f21)

**Comment by sneakyfox1964** [comment]
benefaktorix, what do you mean by "calls are basically out of question since 3.21.3"?

Thanks.

**Comment by ChaoticMind** [comment]
Related to #5660 (at least the part where "When the call drops, I'm unable to call anyone again or receive calls")

**Comment by vikishah90** [comment]
Same here with my Nexus 5x Android version 7.1.1

**Comment by dwayne80** [comment]
Signal app crashes for me whenever I try to place a call through the app, or when I receive one.
Nexus 5X, Android 7.1.2

**Comment by moxie0** [comment]
This was originally a RedPhone issue, which should now be resolved with the new calling infrastructure. @dwayne80 if you're still seeing crashes with the latest version of the app, we definitely need to fix that. Please open a new issue with a debug log that you've captured after a crash and we'll take a look. Thanks!
