### ISSUE TITLE
Make an additional app with android:allowBackup set to true

### ISSUE THREAD

**Issue by superbonaci** [WhisperSystems/Signal-Android#5842]
There's the app "org.thoughtcrime.securesms" which has 'android:allowBackup' set to false.

I request to make another app for those who want to be able to backup Signal's data, for example 'org.thoughtcrime.securesmsadbbackup'

**Comment by moxie0** [comment]
We're not going to do this, but feel free to submit a PR for in-app backup and restore functionality.

**Comment by Trolldemorted** [comment]
would you merge a PR that also backups the identity?

**Comment by moxie0** [comment]
@Trolldemorted possibly, depends how it's done. that makes building in restore functionality much harder, though.

**Comment by superbonaci** [comment]
There's no problem at all. Those users still wanting to use the adb backup feature on Signal can check this tutorial made by a developer in XDA:

[[GUIDE] How to enable adb backup for any app changing android:allowBackup
](http://forum.xda-developers.com/android/software-hacking/guide-how-to-enable-adb-backup-app-t3495117)
