### ISSUE TITLE
Pixelapse art asset repository seems to be down

### ISSUE THREAD

**Issue by dephekt** [WhisperSystems/Signal-Android#5845]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The art asset repository [referenced](https://www.pixelapse.com/openwhispersystems/projects/signal-android/) in the Signal-Android [build instructions](https://github.com/WhisperSystems/Signal-Android/blob/master/BUILDING.md) was giving internal server 500 errors yesterday and today seems to be timing out when I browse to it.

### Steps to reproduce
- Go to the following URL in a browser: https://www.pixelapse.com/openwhispersystems/projects/signal-android/

**Actual result:** The website never loads or produces an internal server error
**Expected result:** The signal-android art repository loads in the web browser.

### Screenshots

![signal_error_art](https://cloud.githubusercontent.com/assets/7564683/20085881/b610bc04-a531-11e6-85b8-ab6d743c51c1.png)

**Comment by Kajisav** [comment]
Is there an alternative repository?

**Comment by FeuRenard** [comment]
They shut down their service and recommend using Dropbox. http://blog.pixelapse.com/post/148426406445/dropbox-migration
