### ISSUE TITLE
Signal deleted all my texts =(

### ISSUE THREAD

**Issue by glamrock** [WhisperSystems/Signal-Android#5848]
I received several texts at once, leading my phone to crash somehow. When I restarted the phone, Signal forced me to re-register and had deleted ~everything~ (texts, call history, pictures people had sent me, EVERYTHING)

Is it possible to restore any of this? How can I prevent this in the future?

**Comment by moxie0** [comment]
@glamrock It's helpful if you can use the issue template when filing new issues; it's hard to respond when we don't have basic information like what version of Android you're running, what version of Signal you're running, or a debug log.

From what you're saying, it sounds like you have a device problem that caused some disk corruption.  If Signal isn't displaying information like your conversation history, that means the files aren't there anymore. You could use standard disk recovery techniques to try to find the data on the disk, but there's probably not anything Signal can do about this situation.

**Comment by Jop-V** [comment]
The same happened on iOS a while ago.. Forced to re-register, whole history gone. Phone's fault?

**Comment by moxie0** [comment]
@Jop-V sorry to hear that, but this issue tracker is for the android app. you can file issues over in the ios repo if you'd like

**Comment by moxie0** [comment]
Closing due to lack of info, please reopen if available

**Comment by Jop-V** [comment]
Of course, I just wanted to mention that it's not an Android-specific issue.

I wasn't expecting help and I'm not filing an issue because it could have been the phone's fault (just like in @glamrock's case).
