### ISSUE TITLE
Server issue: refuses New-Caledonia numbers

### ISSUE THREAD

**Issue by laurentdinclaux** [WhisperSystems/Signal-Android#5850]
It is impossible to set it up in New Caledonia (https://en.wikipedia.org/wiki/Telephone_numbers_in_New_Caledonia). The app shows an error "Connectivity issue".

I had a look to the logcat, and the app sends a request to the server with this url: https://textsecure-service.whispersystems.org/v1/accounts/sms/code/+687xxxxxx

If I access it in a browser I get this reply from your server:
{"code":400,"message":"HTTP 400 Bad Request"}

Then I tried a phone number from France and accessed the url https://textsecure-service.whispersystems.org/v1/accounts/sms/code/+33xxxxxxxxx

And it works (well I get an empty response instead of a "400 Bad Request"). There definitely is a server issue not accepting New-Caledonia 6 digits numbers.

**Comment by laurentdinclaux** [comment]
I tried to add two zeros at the end of my phone number (so 8 digits instead of 6) and I don't have such an issue, the app normally tries to send the SMS and wait for it to arrive (which doesn't happen as the number is wrong with the two added digits for the test)

**Comment by 2-4601** [comment]
Related #4549

**Comment by laurentdinclaux** [comment]
Vanuatu numbers are affected too. 
Any idea on when the server side be fixed ?

A clue: https://github.com/googlei18n/libphonenumber

**Comment by laurentdinclaux** [comment]
Found a sort of workaround. I added a "0" to my number. The SMS doesn't arrive but then I use the call me option, and the server called me properlly and I could register.

But now I am registered with my number and the added "0" so my contacts cannot find me....

**Comment by 2-4601** [comment]
This issue is now noted and aggregated to #6027.

**Comment by p4nci** [comment]
@laurentdinclaux it's up to you, but maybe you can now update your rating at playstore? SCNR
