### ISSUE TITLE
Error sending photo to Signal recipient

### ISSUE THREAD

**Issue by karldw** [WhisperSystems/Signal-Android#5860]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I try to send a photo to a friend on Signal, it fails with the error message:
> Not delivered
> Tap for details

I'm able to exchange text messages and voice calls with the same Signal friend, and I'm able to send MMS photos to non-Signal recipients.  
I'm also unable to receive photos.  (Separate bug report coming soon.)

### Steps to reproduce
- Click the paper clip to add attachment
- Click "Image" to select an image from the gallery
- Select the image.
- Press send.

**Actual result:** I get the "Not delivered" message mentioned above.
**Expected result:** The image sends.

### Screenshots

![error screenshot](https://cloud.githubusercontent.com/assets/12504708/20289106/b13b6d54-aa8c-11e6-8c30-b12648e5ebcb.jpg)
Note that while it says "Tap for details", I've already clicked.  It doesn't provide any additional information, just gives me the option of resending.  (Resending doesn't work either.)

### Device info

**Device:** HTC M8 (HTC HTC6525LVW) 
**Android version:** 6.0
**Signal version:** 3.21.3
**HTC Sense version:** 7.0

### Link to debug log

https://gist.github.com/anonymous/afe910e5beadba8886d29880a5522293

**Comment by nrizzio** [comment]
Have you disabled any security certificates from your certificate trust store?

**Comment by karldw** [comment]
Ugh, sorry, that was exactly it.  Thanks for such a quick reply!
