### ISSUE TITLE
Inconsistent boolean GUI controls

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/Signal-Android#5861]
I have:
- [x] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The GUI controls used for a boolean setting are inconsistent.

### Steps to reproduce
- Open Signal
- Go to settings, 
- Go to privacy

**Actual result:** Some booleans are set by a slider conytrol, some by a checkbox.
**Expected result:** All controls are the same.

### Screenshots
![screenshot_2016-11-15-02-39-08](https://cloud.githubusercontent.com/assets/8427572/20290102/506c4a0a-aade-11e6-98d6-d892b67b5fbf.jpg)

### Device info

**Device:** Sony Z1 compact
**Android version:** 4.4.4
**Signal version:** 3.22.1

No debug log required since nothing crashed.

**Comment by moxie0** [comment]
hey @johanw666 the convention we use is that top-level booleans are sliders and booleans which are sub-prefs (dependent on a top-level) are checkboxes

**Comment by johanw666** [comment]
Sorry, I didn't know that.
