### ISSUE TITLE
Emoji implementation breaches copyright

### ISSUE THREAD

**Issue by Jop-V** [WhisperSystems/Signal-Android#5862]
Signal includes the Apple Color Emoji library to render emoji's on Android. The problem is that Apple developed it strictly for their own use and they are not licensing it to anybody. 

This puts the Android version of Signal in a legal grey area.

This could be fixed by switching to an alternative emoji library. For something similar to Apple's library, Twitter's [Twemoji](https://github.com/twitter/twemoji/tree/gh-pages/72x72) could be considered.

**Comment by moxie0** [comment]
Thanks for the heads up
