### ISSUE TITLE
Accessing archived messages

### ISSUE THREAD

**Issue by jmayday** [WhisperSystems/Signal-Android#5869]
Hi. 

I'm using Signal since some time and there is one thing which still confuses me. There is no visible option to access archived messages. Swiping message right archives a message. If you made a mistake you can undo the action. But how to access archived messages in general? I can not see any option to do this.

**Comment by nrizzio** [comment]
The button at the very bottom of your conversations list. It says "archived conversations".

In the future, please send an email to support@whispersystems.org for support questions.

**Comment by jmayday** [comment]
Thks @nrizzio for quick answer. This solves the problem. What could be then improved is the layout: after scrolling the list, "archived conversations" could show up at the bottom (so it's detached from the list and has fixed position). I believe it would improve the usability.

**Comment by riyapenn** [comment]
Also referenced on the support page [here](http://support.whispersystems.org/hc/en-us/articles/214582088).

**Comment by jmayday** [comment]
True @riyapenn - haven't seen this page.

**Comment by anthonymillion2005** [comment]
Yes I agree that the user accessibility of the archived messages is terrible. This can be solved by adding a tab on the top right under the menu pull down.
