### ISSUE TITLE
Can't register Signal from Faroe Islands

### ISSUE THREAD

**Issue by eydunn** [WhisperSystems/Signal-Android#5873]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Can't register Signal from Faroe Islands (+298) xxxxxx

### Steps to reproduce
- Start Signal
- choose country code (+298) and enter 6-digit phone number

**Actual result:** Connectivity error - Signal was unable to connect to the server
**Expected result:** The rest of the steps- i.e receive an sms for verificatition etc.

At one point there was an [bug](https://github.com/WhisperSystems/libsignal-service-java/commit/a8d6f5974f4a900c7bfc5ab99a0d48928b2a8878) in a library that Signal uses, so I wouldn't even get this far in the registration process. That got fixed. 

But I guess that the  _**same or similar error is still running server-side**_.

Because if I:

### Steps to reproduce
- Start Signal
- choose country code (+298) and enter 6-digit phone number+0000

**Actual result:** 
- Connecting - check  
- Wating for SMS verification - times out
- I get the option to make a voice verification or edit my number again

**Expected result:** 
Well, since it's not really my number, I did expect the SMS to hang.

# Conclusion:
I am guessing that this is a server-side issue with an old version of:

`api/util/PhoneNumberFormatter.java`

:-)

**Comment by 2-4601** [comment]
Is this duplicate of #5291?

**Comment by eydunn** [comment]
Yes
