### ISSUE TITLE
'Verify safety numbers' missing

### ISSUE THREAD

**Issue by JuangDse** [WhisperSystems/Signal-Android#5878]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I cannot verify contacts anymore. Clicking the contact's name, there is no item 'Verify safety numbers'. On my synced Signal Desktop the option 'Verify identity' exists.

### Steps to reproduce
- Do a fresh install of Signal
- choose a contact that you know is using Signal

**Actual result:** the menu item 'Verify safety numbers' is missing
**Expected result:** the menu item 'Verify safety numbers' is not missing

### Screenshots

![screenshot_2016-11-21-11-35-51](https://cloud.githubusercontent.com/assets/17064606/20479672/61a0cc14-afdf-11e6-9fc4-db3e520ace2b.png)

### Device info

**Device:** Samsung Galaxy Note 3 Neo
**Android version:** 4.4.2
**Signal version:** 3.22.2

### Link to debug log

https://gist.github.com/anonymous/56d73f7a56a54ccd82586a73920bc881

**Comment by FeuRenard** [comment]
I see this behaviour too for a Signal contact I never exchanged messages with.
I suppose you will first have to exchange a message (send or receive) with a contact to be able to verify your safety numbers.

**Comment by cascheberg** [comment]
By the way, same situation after "reset secure session": you cannot verify safety numbers until you have sent a message.

**Comment by haffenloher** [comment]
Hmm, shouldn't we keep this open and think about how to avoid the confusion? Maybe we can gray out the option instead of hiding it, or otherwise convey the idea that *this is indeed the place where you can normally verify, it's just not possible right now*? We'd then probably also have to explain why though...

**Comment by JuangDse** [comment]
yes, I had thought so too, plus I haven't found anything in the documentation. So I reopen it.

**Comment by 2-4601** [comment]
Hiding the safety numbers screen after resetting the session seems weird because the numbers are not session specific. Was it like this with the previous identity key fingerprints?
