### ISSUE TITLE
After ReRegister - Groups "unkown" and no post possible - On Desktop no Problem!

### ISSUE THREAD

**Issue by jamfx** [WhisperSystems/Signal-Android#5879]
I have:
- [x ] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After reregistering Signal on my Google Nexus 5x (even after reinstall) I can not post in a Group, I opened before. BUT! If I reconnect my DesktopApp of Signal (Chrome App), I can communicate in this group with no issues.

### Steps to reproduce
- install Signal on Android-Device
- Connect Signal with Desktop App
- Open up a Group and post something
- Uninstall / Install or just ReRegister your Android-Device
**Actual result:** 
on Android-Device: You can see the Group as unknown, can see what is posted there from others, but you can not post yourself into the group.
On Desktop-App you can still post and follow everything in the group.

**Expected result:** 
On AndroidDevice -> Post and interact with group as before
On Desktop-App -> No chance needed. Works properly.

### Screenshots
-/-

### Device info
**Device:** Google Nexus 5x, root
**Android version:** 7.0 (;8994F-2.6.33.2.14 (Patchlevel 5. November)
**Signal version:** 3.22.2

### Link to debug log
As there is no "bug", just wrong behaviour, no log available.

**Comment by FeuRenard** [comment]
This issue already exists and is related to #5876 (PR). In the PR's discussion are some links to other issues, which describe your problem.

**Comment by jamfx** [comment]
To be honest, I can not read out, that my issue is similar to them, but If you think it is, my ticket could be closed. If not, please leave it open.

**Comment by jamfx** [comment]
I think https://github.com/WhisperSystems/Signal-Android/issues/2581 is the closest. But as far as I can see, the Desktop-App-Combination is not mentioned yet. Maybe this is an interessting point, too.

**Comment by FeuRenard** [comment]
You desktop combination is also mentioned in the discussion of #2581. So this issue is actually a duplicate and should be closed.

**Comment by jamfx** [comment]
Yeah, ok, close it. I thought I had searched everywhere. Sorry for duplicate.
