### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by pintopwnie** [WhisperSystems/Signal-Android#5881]
I have:
- [X ] searched open and closed issues for duplicates
- [ X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Instant crash on startup and displays message "Unfortunately, Signal has stopped."

### Steps to reproduce
- Open Signal
- Error message displayed

**Actual result:** Signal crashes and displays the message
**Expected result:** Open message 

### Device info

**Device:** Samsung Galaxy S5
**Android version:** 6.0.1
**Signal version:** beta 3.22.2

### Link to debug log

https://gist.github.com/anonymous/b2666e62b70b874a5513297d2b4a16d4

**Comment by moxie0** [comment]
I don't see a crash in this log, you'd have to capture it immediately after the crash.

**Comment by pintopwnie** [comment]
Moxie, thanks for the quick response. I figured out it was a SIM (phone number) change.

**Comment by Trolldemorted** [comment]
nevertheless, signal might show a more verbose error description instead of crashing, so you might want to reopen this.

**Comment by lnicola** [comment]
For anyone running into this after replacing a SIM, you can fix it by clearing the app data.
