### ISSUE TITLE
Signal crashes on startup after entering passphrase

### ISSUE THREAD

**Issue by dnivra** [WhisperSystems/Signal-Android#5884]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

Yesterday, I noticed that Signal crashes everytime I try to open it. As soon as I enter the correct passphrase, it crashes.

### Steps to reproduce

- Open Signal and enter passphrase.
- Crash.

**Actual result:** I get a window saying "Signal has crashed." with "Ok" and "Report[to Google]" options.
**Expected result:** I expect to be able to access messages in Signal.

### Device info
**Device:** Motorola Moto G4
**Android version:** 6.0.1
**Signal version:** 3.22.2

### Link to debug log

https://gist.github.com/anonymous/35cde58bf0705025f2b3532e3e6f9d44

**Comment by 2-4601** [comment]
Looks like a problem with sending an SMS. Put your phone in airplane mode and try to delete the message that has the issue.

**Comment by dnivra** [comment]
@2-4601 Thanks for the suggestion! That fixed the problem. Shall I close the issue or leave it open in case there might be further interest in this problem?

**Comment by moxie0** [comment]
Was there anything unusual about the content of the SMS?

**Comment by dnivra** [comment]
@moxie0 Sadly I deleted the message and only realized later I probably shouldn't have. Nothing was displayed in the message when I viewed it before deleting. Are there any characters that Signal doesn't display? Also, as far as I remember, I didn't explicitly send the message. I received notification that a contact of mine recently installed Signal(the "say hey" message) and dismissed it. I noticed that the message was sent to this contact.

**Comment by moxie0** [comment]
Bizarre. Thanks for the report, sorry for the trouble. I'm going to close this for now since there's not enough info to investigate further, but please reopen if you have further problems.

**Comment by dnivra** [comment]
Bizarre indeed - I was surprised to see that a message was sent when I didn't send it. Very strange how it was sent despite Signal being locked with my passphrase. Thanks for help @moxie0 and @2-4601! Will come by if I discover any more issues.
