### ISSUE TITLE
Unable to send signal messages after responding to normal sms within signal app and without having a sim card

### ISSUE THREAD

**Issue by sigenc** [WhisperSystems/Signal-Android#5888]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I have had this problem several times now. Sometimes when i respond to a signal message, it send's an sms (I'm not Holding the send button) wich don't get delivered because i don't have a simcard in my phone. It is sitting in airplane mode just with wifi turned on and connected to the interent via hotspot. When i delete this particular sms message and try to send another message to an registered Signal user it just shows the bouncing 3 dots. It never leaves the phone. It never tells that the message can't be delivered or something similar. I have to wait till an update is avalable or reinstall signal.

EDIT:

And i just noticed that the camera ain't working in the app too at the moment.
I will terminate the signal process and capture another log.

When i get my other Phone back i will try to reproduce this behaviour. The last time it happened, was when i got a msg from a user who just registered and typed my phone number in and hit send after the app showing him that i am a signal user. I got the msg, but couldn't reply to it with a data msg. Only SMS

### Steps to reproduce

-I could not reproduce this one

**Actual result:** Signal users dissapear. Can't send any Messages. Just make calls
**Expected result:** Don't stuck in any thread where it tries to deliver the sms and send normal signal data Messages.

### Device info

**Device:** Nexus 5
**Android version:** 6.0.1
**Signal version:** 3.22.2

### Link to debug log
First Log:
https://gist.github.com/anonymous/95674be12129d233c47fcb359807f72a

Second Log:

I terminated signal and startet with logging in and trying to connect a device. The screen where the camera should show what i wan't to scan is just black. Then i typed a msg to a friend that is a signal member and hit sent.

https://gist.github.com/anonymous/b516a5b6355be7141c19a8062738b3ec

**Comment by 2-4601** [comment]
Sounds like #4390, #5531

**Comment by riyapenn** [comment]
Check out the support page on this one way messaging: https://support.whispersystems.org/hc/en-us/articles/215089628-Why-can-I-only-privately-message-one-way- 

Also check your permissions: Go to Android Phone Settings > Apps > Signal > App Permissions > Enable all permissions. Even if this is enabled, please re-toggle the setting (turn it off and back on) and restart your phone.

You may want to physically keep an invalid SIM in the slot.
