### ISSUE TITLE
SMS drafts are deleted after tapping a "failed to send MMS" message

### ISSUE THREAD

**Issue by strugee** [WhisperSystems/Signal-Android#5889]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description

SMS drafts are deleted after tapping a "failed to send MMS" message

### Steps to reproduce

* Go into a non-secure conversation
* Attach a picture from the gallery, caption it, and send it
* Compose a draft and tap the back arrow to return to the conversations list
* Close the app
* Somehow make the MMS delivery fail
* When the "message delivery failed" notification pops up, tap on it

**Actual result:** the message compose box is empty
**Expected result:** the draft is retained

### Device info

**Device:** Nexus 6P
**Android version:** CyanogenMod 13.0-20160819-SNAPSHOT-ZNH5YAO0IN-angler based on Android 6.0.1
**Signal version:** 3.23.0 (I'm a beta tester on the Play Store)

### Link to debug log

https://gist.github.com/anonymous/afcbb8c5dbdbfb5c5e1a3a5b0b3ccd5c

**Comment by FeuRenard** [comment]
What will happen, if you go back to the conversation list and reenter your conversation directly after your steps? I cannot reconstruct "Somehow make the MMS delivery fail".

This issue could be related to or even be a duplicate of #4729.

**Comment by strugee** [comment]
Hey, sorry for the delay.

> What will happen, if you go back to the conversation list and reenter your conversation directly after your steps?

That seems to fix it, kind of.

Going back to the conversations list shows the draft deleted in the conversation (i.e. there's no "_Draft_: foobar" text under the conversation participants' names). However, reentering the conversation restores the draft, and tapping back to get back to the conversation list shows the conversation as having a draft.

> I cannot reconstruct "Somehow make the MMS delivery fail".

Yeah, sorry. At the time I filed this it was just a problem that I was having - maybe something related to my carrier. If you can't reproduce this your best bet will be to compile a build of Signal that makes this happen intentionally.

(FWIW I just reproduced this with a failed-to-send group text message. Unsurprising since that's also just an MMS message.)

**Comment by FeuRenard** [comment]
I've already written down in https://github.com/WhisperSystems/Signal-Android/issues/4729#issuecomment-170927763 these steps to reproduce:

> 1. write a message
> 2. leave the conversation with a back-button (so that a draft is saved)
> 3. leave Signal
> 4. **receive a message from the person you wrote in 1)**
> 5. **Tap the notification to get to the conversation.** Then the draft is gone.
> 6. Go to the conversation list. The draft is still gone (no preview).
> 7. Enter the conversation again. The draft reappears.

The notification in steps 4 & 5 and the one you observed (sending failed) seem to be equivalent in the context of this issue. So this issue is a duplicate of #4729.

**Comment by strugee** [comment]
Closing per the above comment. Thanks for finding a dupe I didn't, @FeuRenard! :+1:
