### ISSUE TITLE
Turn on SMS delivery reports by default

### ISSUE THREAD

**Issue by strugee** [WhisperSystems/Signal-Android#5890]
Signal messages have delivery reports by default, but SMS conversations do not. That results in kind of a confusing UX where some conversations have double checkmarks to confirm delivery, and some do not.

Turning on the "SMS delivery reports" option by default would improve this.

**Comment by zoff99** [comment]
delivery reports often cost extra, even when sms are free. so this is not a good idea.

**Comment by moxie0** [comment]
Yep, used to be on by default, we had to turn it off as a result of a bunch of problems. Different carriers charge for it, some send you back an SMS instead of sending the delivered event, some send a failed event instead of sending the delivered event, etc.

**Comment by strugee** [comment]
:( that sucks. Sorry for the noise!
