### ISSUE TITLE
Error on last register step

### ISSUE THREAD

**Issue by Ralvke** [WhisperSystems/Signal-Android#5897]
### Bug description
Register sms will get, but not auto type. (Telegram does it)
After requested call, i wrote code and it verified, but on last step (registration on server) error occurs: no connection

### Steps to reproduce
- wait 2 min (no auto type sms)
- request call
- type code

**Actual result:** Error occurs (no connection to server)
**Expected result:** Register

### Device info
**Device:** HTC Desire 601
**Android version:** 4.2.2
**Signal version:** 3.22.2

Logcat: http://pastebin.com/8qtUdHLH

**Comment by 2-4601** [comment]
What kind of a ROM are you running?

**Comment by Ralvke** [comment]
Unofficial ROM from XDA
http://forum.xda-developers.com/desire-601/development/rom-insertcoin-3-0-6-zaraul-m7-port-5-t2819869

**Comment by 2-4601** [comment]
Seems like an issue with Google Play Services in your ROM. Signal needs it for push.

**Comment by moxie0** [comment]
Yep looks like bad gapps

**Comment by Ralvke** [comment]
Yes, after reinstalling Gapps all work.
Thanks
