### ISSUE TITLE
Incorrect Icon For FAB?

### ISSUE THREAD

**Issue by Lokesh-Krishna** [WhisperSystems/Signal-Android#5900]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The current FAB in the main conversations list shows a pencil icon which is indicative of composing a message while the button actually leads to a screen letting you pick a contact and initiate a new conversation. This button actually *adds* a new conversation to the screen and this is why other apps use the "add" button while email apps use the compose button as they mostly directly take you the message composing screen (Gmail and Outlook are examples).

**Actual result:** The FAB icon is not consistent with its action.
**Expected result:** The icon should be replaced with the "add" icon from Google's Material Design Icons like in other messaging apps (Google Messenger, Facebook Messenger, QKSMS, etc.)

### Screenshots
![unnamed](https://cloud.githubusercontent.com/assets/20235646/20701590/ed123958-b639-11e6-8030-14c2a8d2bcae.png)

**Comment by FeuRenard** [comment]
Duplicate of #5226

**Comment by Lokesh-Krishna** [comment]
I'm so sorry. I only searched for FAB.
