### ISSUE TITLE
create process error 2

### ISSUE THREAD

**Issue by nomanzafarminhas** [WhisperSystems/Signal-Android#5901]
i downloaded this project and run on android studio but it occur an error 
(create process error 2=The system cannot find the file specified)
please tell me the solution for this  kindly...

**Comment by 2-4601** [comment]
Hi,

This GitHub issue tracker is used for bugs. For help on building Signal try https://whispersystems.discoursehosting.net/

**Comment by nomanzafarminhas** [comment]
Now what is the solution for this
