### ISSUE TITLE
Push to talk is enabled in SMS Mode

### ISSUE THREAD

**Issue by halb9** [WhisperSystems/Signal-Android#5906]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal lets you send voice notes, even if it is plaintext sms. Therefore GSM message. And therefore extremely expensive. 

### Steps to reproduce
- Have Signal installed as your default messenger. Use it to send regular SMS. 
- Open conctact who is not a Signal user. 
- Press push to talk. Send voice note. 

**Actual result:** Voice note is send. Since it is transmitted via GSM it is converted to an MMS message. And MMS messages are extremely expensive. I pay 0.49€ for a single one. 
I know that in other countrys you pay a lot less, if at all. So I wanted to you to be aware of it. 

**Expected result:** I don't know really know to be honest. Just hide it in sms mode works for me. But at the same time is probably quite annoying for someone who does not have to pay for mms messages and would like to use that feature even in sms mode. 
Differentiate userbase for location and mms fees and hide/show push-to-talk button accordingly is probably a PITA. 

Sorry no easy solution here. But I can see people using the voice-notes. And paying a hefty bill afterwards. Which, although it is the users fault, could lead to bad Signal reputation. 

### Device info

**Device:** should not matter
**Android version:** should not matter
**Signal version:** 3.23.0

Cheers, have a nice day

**Comment by moxie0** [comment]
I don't think there's anything we can do about this.  You could say the same thing about the camera button, or the attachment button.  If people don't want to use MMS, it's kind of up to them.
