### ISSUE TITLE
Automatically remove leading 0 in UK numbers stored in phone otherwise can receive not send Signal messages to numbers of +440xxxxxxxxxx (zero after the country code)

### ISSUE THREAD

**Issue by cyrus-and** [WhisperSystems/Signal-Android#5928]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Fresh installation: the registration procedure completes successfully.

Basically nothing else works:

- the contact list is empty;
- I can receive secure messages (blue lock, "Via: Data (Signal)") yet Signal prompts me to invite the sender: "Take your conversation with Xxxxxx Yyyyy to the next level.";
- I cannot reply: I only see a big gray button "ENABLE SIGNAL FOR SMS";
- SMS and MMS are off and I'd like to leave it that way, but if I enable it then I'm able to see the contacts (awkwardly duplicated, e.g., xxxxxxxxxx and xxx xxx xxxx);
- this situation lasts for months (since the first time I tried signal), I even performed an hard reset recently;
- the phone is not rooted.

**Note:** due to an operator switch my current SIM cannot always provide the correct phone number (like in this case), so I need to manually fix that. It happens for other services as well, e.g., WhatsApp, without any problems. Anyway, as I said the registration procedure works.

### Device info
**Device:** Nexus 5
**Android version:** 6.0.1
**Signal version:** 3.23.0 (from Play store)

### Link to debug log
https://gist.github.com/anonymous/86ddc6e25f17dacb07b1415d0bd294f7

**Comment by riyapenn** [comment]
You need to edit your contact's phone number format in your phone. See the [support page](https://support.whispersystems.org/hc/en-us/articles/215089628-Why-can-I-only-privately-message-one-way-) or contact support@whispersystems.org.

**Comment by cyrus-and** [comment]
My contact's phone number already contains the +<country code>. Maybe I have not made myself clear, this is not a problem with **one** particular contact.

**Comment by riyapenn** [comment]
Contact support@whispersystems.org with which steps from the support page you've completed.

**Comment by cyrus-and** [comment]
I'll do it, but the lack of in-app warnings or any type of feedback is still an issue worth to be fixed IMHO; merely showing an empty contact list is terrible UX.

**Comment by cyrus-and** [comment]
It turned out that Signal got confused by the 0 after the country code (for UK numbers): +440xxxxxxxxxx. Dropping the zero was the solution. Note that the zero is successfully ignored when I manually enter the number (from the blue pencil), that is Signal recognizes the contact and properly shows the name regardless of the presence of the 0 in the stored number. Yet, it is unable to send secure messages to the contact (only SMS) if it is stored with the zero.

Please note that almost certainly I didn't enter the number manually the first time, rather I must have saved it from a received call or whatever. So that is probably how Android stores it by default and it would be nice if Signal would be aware of that.

Also, it seems that WhatsApp is unaffected by this, i.e, it is able to strip away the zero and save **its own** contact without it.

**Comment by moxie0** [comment]
@cyrus-and Can you tell me more about how your contact's number ended up formatted this way? As far as I know +440 isn't a valid e164 encoding. Did you manually enter it that way, or did it get in your contacts through some other vector? Is it common to enter numbers as +440 in the UK? Thanks!

**Comment by cyrus-and** [comment]
@moxie0 it happened a couple of years ago, but I'm pretty sure I didn't enter it by hand, most likely I saved it from a regular SMS (vanilla SMS app or Hangouts).

But the thing that puzzles me is that WhatsApp is able to overcame this, so at first I didn't think about the number formatting issue, apart from what concerns the presence/lack of the international prefix.

> Is it common to enter numbers as +440 in the UK?

I don't live in the UK myself, so I can't tell.

Thank for investigating this!

**Comment by moxie0** [comment]
in 3.25.0
