### ISSUE TITLE
Widget contact shortcut

### ISSUE THREAD

**Issue by Transisto** [WhisperSystems/Signal-Android#5929]
I'm a big user of having a folder right under my finder with widget icons of every contact I use the most.

To me this is very important to use Signal over regular phone / SMS to contact people with in a rush.

**Comment by jeremymasters** [comment]
This also would make it easier to share things with specific contacts instead of always having to share with signal, then choose contact.  1st world problems I guess :wink:

**Comment by FeuRenard** [comment]
Duplicate of #1484?

**Comment by Hanzei** [comment]
@FeuRenard Looks like. I think we can close this one
