### ISSUE TITLE
Deleted group reappears when contact safety number changes

### ISSUE THREAD

**Issue by cascheberg** [WhisperSystems/Signal-Android#5930]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
A deleted group shows up again when a group member's security number changes, so without exchanging messages in that group. The group then appears to be in an inactive state, i.e. sending messages is not possible.

### Steps to reproduce
- Create a group, group members A and B
- Delete group on device A (you can even leave the group first)
- Re-install Signal on device B (safety number changes)
- Send a message from A to B
- Confirm safety number change notification on device A

**Actual result:** All deleted groups that contain B reappear on device A. The only content is a safety number change notification, see 848a25664b746f89b4435b01728247bf3d3135f4. Sending messages is not possible.
**Expected result:** The groups should not reappear. I was surprised to see that group information where still available at all.

### Device info
**Android version:** stock Android 5.1.1
**Signal version:** 3.24.1

**Comment by moxie0** [comment]
in 3.25.0
