### ISSUE TITLE
Incorrect glossary term "number" is shown to Transifex translators

### ISSUE THREAD

**Issue by amire80** [WhisperSystems/Signal-Android#5935]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I am translating Signal at Transifex. Transifex shows glossary terms. Instead of showing the correct translation of "safety number", it is showing me the translation for "number", even though "safety number" appears in the glossary.

### Steps to reproduce
- Look at Transifex at the translation of the string "Share safety number via..."

**Actual result:** In the sidebar I see "number (n) As in "Phone Number""
**Expected result:** In the sidebar I should see "Safety number" and not "number".

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by RiseT** [comment]
This cannot get solved on GitHub.

Apart from that, I've looked into Transifex, and the only related glossary entry existing is (or rather was: I've deleted it) the old "safety numbers" (plural). I've then created a new one for the new "safety number" (singular), and it is working as expected.

**Comment by amire80** [comment]
Great, this is fixed! Thank you!
