### ISSUE TITLE
Pixel Launcher round icon (and make Android icon consistent with desktop and iOS)

### ISSUE THREAD

**Issue by trgeiger** [WhisperSystems/Signal-Android#5936]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The new Pixel Launcher on Google's Pixel and Pixel XL now allows app-makers to use a round, stylistically coherent icon, as you can see in the screenshots below.

You might also notice in that screenshot that the current Signal icon in the Pixel Launcher looks a little out of place--taller, and not round in the same way as the rest of the icons. It would be great if Signal could match the UI/UX of the Pixels as many other top apps have done since the release of these new phones.

You can also see how some apps have adapted to the round icon support even with square or otherwise non-round icons below, such as the Play Store and Inbox.

### Screenshots
![image](https://cloud.githubusercontent.com/assets/18582917/21013943/8859d040-bd21-11e6-8766-e2b2633057f5.png)
![image](https://cloud.githubusercontent.com/assets/18582917/21014051/01557198-bd22-11e6-9492-a4e0888dbfc2.png)

### Device info

**Device:** Pixel XL (marlin)
**Android version:** 7.1.1
**Signal version:** 3.24.1

**Comment by toa697** [comment]
I feel that the UX trends of other applications, as well as the UX choices of devices such as the Pixel are not sufficient reason alone to modify the style and look of the icon of Signal. There are plenty of very popular apps that do not follow the mainstream form of icon design, such as Discord, Twitch, Snapchat, and the settings app for the Nova Launcher. All of these are very popular apps.

**Comment by trgeiger** [comment]
Pixel Launcher doesn't require the app to change their primary icon--it allows an opt-in sort of mechanism for a round icon option. For example, the default Twitter icon is a square, but on Pixel Launcher it uses the round icon option. I guess that's what I'm suggesting, an opt-in to the Pixel round icon, especially since the Signal icon already almost fits.

**Comment by trgeiger** [comment]
As just another example, Materialistic - Hacker News also uses a square icon by default, but uses a round icon version on the Pixel Laucher. Some apps also, albeit less elegantly, integrate into the launcher by putting their default icon onto a white background, as you can see with some of the Google apps and Simple Habit in the screens above.

**Comment by moxie0** [comment]
We need to change the Signal Android icon to match the Signal iOS and Signal Desktop icon anyway. If anyone wants to take a shot at making that both material and round, please go for it.

**Comment by carstn** [comment]
@moxie0 The icon source assets are no longer online at Pixelapse (see #5845), and I haven't found them in the Signal-iOS or Signal-Desktop repos either. Do you know where the source assets used iOS/Desktop icons can be found?

**Comment by mawed** [comment]
![logo-round-1024](https://cloud.githubusercontent.com/assets/11197868/21022913/a3a002d6-bd7e-11e6-9e6a-79776b2471ed.png)

I don't know if a round cut of the not round speech ballon will look so good, as the blue edge around will not be similar wide all around.

**Comment by mawed** [comment]
![logo-unround-1024](https://cloud.githubusercontent.com/assets/11197868/21023408/b5698ea4-bd80-11e6-83c9-538f7fb7232a.png)
I think I would prefer something in the old Signal-logo-style more.

**Comment by moxie0** [comment]
hmm yeah doing a cutout unfortunately doesn't work very well with this logo. we might have to settle for a tile that we try to make "material." @liliakai had a few mockups that were looking somewhat promising in that direction

**Comment by trgeiger** [comment]
I think that would be cool - there's precedent from Google themselves for round icons with a bit of an extension, so to speak. The Allo and Duo icons, for example:

![image](https://cloud.githubusercontent.com/assets/18582917/21023572/b58e75d2-bd46-11e6-9e5e-d0959da0aea1.png)

**Comment by moxie0** [comment]
@trgeiger I love those and would love it if we could make the new signal icon in that style, but it's kind of an overwhelming number of circles (the speech circle, the "whisper" circle, and then the outer circle).  Ends up looking too visually confusing I think, but maybe someone can make it work.

**Comment by trgeiger** [comment]
Hmm, yeah. I agree. I wonder if something like @mawed 's suggestion above where the whisper lines *are* the outer circle would work. A friend might be able to do a mock up, will keep posted.

**Comment by mawed** [comment]
![signal](https://cloud.githubusercontent.com/assets/11197868/21024089/83a282a6-bd83-11e6-98b8-e25414bb9912.png)
@moxie0 something like this?

**Comment by jeremymasters** [comment]
imo, that's too much blank white space.  I'd submit that the quote bubble would have to be smaller by 1/3 or so.  Also, there is a shadow from what would be light from about 10:30 clock position.  Also, on the google ones there isn't a border as part of the key to understanding what the app is/does, but just part of the material shading.

**Comment by mawed** [comment]
@moxie should it be the exact same icon? Or just the same "style"?
If so the whisper lines could form as the outer form of the icon with the big white speech circle in it. But this would cause another icon in the same style.

**Comment by trgeiger** [comment]
Another possible source of inspiration, the round Hipchat logo: 
![image](https://cloud.githubusercontent.com/assets/18582917/21025160/0fd8db4e-bd4d-11e6-92ab-1210b761d7b1.png)

**Comment by jeremymasters** [comment]
A couple more things out there that caught my eye.  I realize these are ones that might need to be paid for, but directions to go might be sussed out by looking.  Perhaps a lock inside or something.
https://www.colourbox.com/vector/vector-illustration-of-paper-round-speech-bubbles-eps10-vector-7148654

**Comment by moxie0** [comment]
@mawed I think it has to be basically the same, maybe just a materialized version of the same.

**Comment by liliakai** [comment]
I went with a square tile to avoid excessive bubble nesting.

![signal-material](https://cloud.githubusercontent.com/assets/1039940/21033640/1d1a74d8-bdb2-11e6-958a-c069495c4e9c.png)

**Comment by bungabunga** [comment]
@liliakai wow, it looks very nice. maybe only the circles should be a bit bigger compared with other icons on the homescreen.

![screenshot_20161209-052507](https://cloud.githubusercontent.com/assets/2994878/21038094/196d7b7a-bdd3-11e6-97c2-38412a099f27.png)

**Comment by mawed** [comment]
@liliakai which program do you use to create this? 
I think I would really like the version using the whisper lines as edges an I would try to make one.

**Comment by trgeiger** [comment]
Here's @liliakai 's made round:

![image](https://cloud.githubusercontent.com/assets/18582917/21049196/0cf92ce4-bdd9-11e6-9796-9c24d7327622.png)

**Comment by p4nci** [comment]
here another mockup
![signal-new-v1](https://cloud.githubusercontent.com/assets/16047081/21050982/427a237e-be1e-11e6-95de-462f6391d7b3.png)

**Comment by liliakai** [comment]
Looks like the D in https://www.discourse.org/. Pretty sure Allo and Duo chose their shapes to be reminiscent of the letters a and d. That doesn't really make sense with Signal.

**Comment by trgeiger** [comment]
I agree--too different than the icon on iOS and desktop also.

**Comment by jeremymasters** [comment]
I think @liliakai has the most material-istic design so far.

**Comment by p4nci** [comment]
@liliakai 
with some imagination we can "see" the s(ignal) ???
![signal-s-v1](https://cloud.githubusercontent.com/assets/16047081/21067603/a18a6a56-be6c-11e6-8301-59320f4f6d41.png)

**Comment by sweeper3000** [comment]
I really like the square icon by @liliakai and the round one by @trgeiger can be used for the pixel launcher. They have a really polished, hi-res look and I like how the round one has padding around the whisper lines.

**Comment by AlfonsoMuskedunder** [comment]
Are the shadows introduced sofar really in the spirit of [material design](https://material.google.com/material-design/material-properties.html#material-properties-physical-properties)? At least to me, they don't add a feeling of three dimensionality so much.

**Comment by cavega** [comment]
Please keep in mind that Google themselves have not updated all of their icons to have a round version. Just look at Play Music, Play Movies, Photos, etc...they just placed the original icon inside a circle.  I'm sure as time passed they will fix the inconsistencies across their icons. I'm not designer but the solutions posted here just look to closed (copied from) Hipchat and Duo/Allo.

I don't think that the round icon has to fully resemble the shape of the original one.  Take for instance the following examples from the Elun and Cryten icon packs.

![elun](https://cloud.githubusercontent.com/assets/1613268/21152685/046dc3bc-c12d-11e6-98e7-d319ee47e3e1.png)
![cryten](https://cloud.githubusercontent.com/assets/1613268/21152689/06afa280-c12d-11e6-95cc-5a0d3fd8b4a8.png)

IMO, the lock shape is what gives the Signal icon its identity.

**Comment by trgeiger** [comment]
@cavega That round keyhole icon is sort of what I pictured when I originally made this issue, and I still like it. I think the point @moxie0 brought up is that they want to unify the icon across desktop, iOS, and Android which would necessitate moving away from the keyhole.

**Comment by Stanzilla** [comment]
Here's a really good video about the guidelines for Material icons that also includes a template https://www.youtube.com/watch?v=GiFV-xfW9pk 

You're mostly just missing the shadows though.

**Comment by iadmir** [comment]
Why not go the other way, something like this might facilitate the unification?

![mobile](https://cloud.githubusercontent.com/assets/23726384/21954561/e84b58b6-da54-11e6-91b8-413645c5bbbe.png)

And it could be applied to the desktop icon.

![desktop-icon](https://cloud.githubusercontent.com/assets/23726384/21954560/e81f4956-da54-11e6-8b5f-f3fe7502631c.png)

**Comment by iadmir** [comment]
Material design
![signal-android-material](https://cloud.githubusercontent.com/assets/23726384/21957453/a46f806c-da96-11e6-860a-d59e9112999d.png)

**Comment by moxie0** [comment]
Looks nice! But it kind of breaks the metaphor, you know? Original design was inspired by the "whispering" speech bubble in comics

**Comment by iadmir** [comment]
@moxie I didn't know it, seems @liliakai have best solution but I think it should be less space between the  bubble and whisper lines like on original icon.

![signal-material-square](https://cloud.githubusercontent.com/assets/23726384/21962292/a75cfc00-db22-11e6-9fc3-7a3e5234c093.png)
![signal-material-circle](https://cloud.githubusercontent.com/assets/23726384/21962291/a72b439a-db22-11e6-8eec-365315ef3881.png)

**Comment by p4nci** [comment]
IMO:
a) speech bubble must be more symmetric (within square icon):

![signal-symmetric](https://cloud.githubusercontent.com/assets/16047081/21983560/3af5ee52-dbf2-11e6-8760-17b608493b64.gif)

b) more "centered" bubble:
![signal-centered](https://cloud.githubusercontent.com/assets/16047081/21983873/99e8479c-dbf3-11e6-8af3-f7a01c18fe33.gif)

**Comment by iadmir** [comment]
a) I agree, it looks better
b) Bubble is precisely aligned using the software without deviations. It may seem optically because of the shadows.

**Comment by moxie0** [comment]
This is great work everyone! The other thing we'd need to make this transition is a version for the notification bar, as well as a version for the action bar.

**Comment by AlfonsoMuskedunder** [comment]
Am I alone in thinking that the use of shadows is a bit inconsistent so far...?

E.g., the large bubble actually throws _two_ shadows - one small one, and the large one. (And why is the upper half of the bubble darker than the lower in some versions?)

In turn, the whisper dashs (pardon my english) around the bubble don't throw any kind of shadows. Why not use the smallish shadows for both the bubble and the dashs?

Please don't get me wrong, the logo looks pretty cool already.

**Comment by liliakai** [comment]
> E.g., the large bubble actually throws two shadows - one small one, and the large one. (And why is the upper half of the bubble darker than the lower in some versions?)

This is consistent with duo/allo icons.

>In turn, the whisper dashs (pardon my english) around the bubble don't throw any kind of shadows. 

They do. In [this version](https://github.com/WhisperSystems/Signal-Android/issues/5936#issuecomment-265901888), at least.

**Comment by p4nci** [comment]
here a mockup for the notification bar:
![screenshot_20170116-215732](https://cloud.githubusercontent.com/assets/16047081/21999195/2d501448-dc39-11e6-9ca1-6b8965f81b62.png)
where:
1. the current one
2. new one original bubble resized: IMO the whisper line is not thick enough
3. new one modified (thicker whisper line + smaller inner bubble)

P.S. all my icons are not "materialized" (=mockups)

**Comment by AlfonsoMuskedunder** [comment]
@liliakai 
>> E.g., the large bubble actually throws two shadows - one small one, and the large one. (And why is the upper half of the bubble darker than the lower in some versions?)

> This is consistent with duo/allo icons.

OK, point taken. And yet - the Allo icon looks clean, while in my view the Signal logo mockup looks a little bit untidy (I hope you understand what I mean). In my view, there's "happening" a bit much. It could have something to do with the fact that the dashs and the bubble get a different shadow treatment.
(Has anyone tried leaving the one large shadow to the lower right out?)

But of course, just my two cents, I won't insist any further :)

**Comment by iadmir** [comment]
@p4nci was right about symmetry, I think it is necessary to modify existing icon (bubble and whispers line). I made some changes I think this looks up better.

![redesigned-signal-demonstrative](https://cloud.githubusercontent.com/assets/23726384/22000073/8f936c28-dc3d-11e6-8061-c5fa89e41560.png)

# iOS

![ios-signal-icon](https://cloud.githubusercontent.com/assets/23726384/22000094/a6879602-dc3d-11e6-9450-7b18bf03e0fb.png)

# Android

![android-signal-icon-square](https://cloud.githubusercontent.com/assets/23726384/22000133/d6663cc0-dc3d-11e6-9e7c-d03e75672934.png)
![android-signal-icon-circle](https://cloud.githubusercontent.com/assets/23726384/22000137/dba25c32-dc3d-11e6-8b32-27cb8e7f77e0.png)
![android-signal-icon](https://cloud.githubusercontent.com/assets/23726384/22000140/e0c41afc-dc3d-11e6-98f2-e9a42b7d4107.png)

# macOS / Desktop

![macos-signal-icon](https://cloud.githubusercontent.com/assets/23726384/22000154/f2f94d50-dc3d-11e6-97e4-47173d4dbcd7.png)

**Comment by p4nci** [comment]
@iadmir 👍 but I didn't meant the perfect symmetry.
I prefer more the original "elliptic" bubble, but it's up to OWS.

**Comment by iadmir** [comment]
I understand, but it is necessary to make this change with rotation of the original bubble!
IMO it's look much better.

Mockup for notifications:

![barnav](https://cloud.githubusercontent.com/assets/23726384/22023044/df3c2198-dcc4-11e6-93a4-692f585e339c.png)
![lock](https://cloud.githubusercontent.com/assets/23726384/22023061/f043db34-dcc4-11e6-85f4-4ed2bcf8843d.jpg)

**Comment by p4nci** [comment]
@iadmir yep, 👍 for rotated but more elliptic!
> Mockup for notifications:

the whisper line is almost unvisible (tested with real device: Nexus 5X).
IMO: we need modified icon for notification and action bar, see also [my mockup](https://github.com/WhisperSystems/Signal-Android/issues/5936#issuecomment-272965161).

**Comment by 2-4601** [comment]
Is it required by Material design or other design guidelines that the notification icon must be the same as the app icon? If not, would it make sense to just use a whisper-lined bubble in notifications? I.e. remove the solid, white-filled bubble inside. This would make the whisper lines stand out better.

**Comment by iadmir** [comment]
@p4nci it's difficult to properly center the bubble when is elliptic!
IMO: "perfect symmetry" is best solution.

Comparation with WhatsApp icon.
![wa-sgnl](https://cloud.githubusercontent.com/assets/23726384/22031393/cf43340e-dce0-11e6-8544-2eacf271f5df.png)

Yes whisper dashs must be bold in some way, some of my suggestions:

![navbar](https://cloud.githubusercontent.com/assets/23726384/22031559/42e620c4-dce1-11e6-8e4a-2c02c6dcec3c.png)

**Comment by liliakai** [comment]
Perfect symmetry pleases the eye, though in this case I think it sacrifices something friendly and organic from the original design, and moves us a little bit further from that comic book metaphor.

Also, if our goal here is cross platform icon consistency with least time and effort, it may be advisable to avoid imposing changes on the ios & desktop icons.

Here's another possible style for notification bar:
![signal-notification-bar-sm](https://cloud.githubusercontent.com/assets/1039940/22051841/f5208c8e-dcfa-11e6-8c13-69dfc1199001.png)

And action bar:
![signal-action-bar-sm](https://cloud.githubusercontent.com/assets/1039940/22051854/038afe26-dcfb-11e6-85dc-c68cefce9a1f.png)

**Comment by iadmir** [comment]
This is only my design proposal, I wouldn't agree that moving away from the comic book metaphor because dialogue shapes may be different, elliptic dialogue bubble isn't the rule.

I think these design modifications contribute to future development and facilitate the necessary icon unification.

**Comment by bungabunga** [comment]
@iadmir comic cloud dialogues are rearly perfect circles, they're also mostly hand made (or at least looking so), so making signal cloud a perfect circle also makes it look a bit artificial.

**Comment by iadmir** [comment]
Does this looks better?

![img_4800](https://cloud.githubusercontent.com/assets/23726384/22072797/c1baa8ee-dda3-11e6-95a8-5b6a4239ca1f.PNG)
![img_4801](https://cloud.githubusercontent.com/assets/23726384/22072801/c20d3cc6-dda3-11e6-8b1b-1613a32221ac.PNG)

**Comment by p4nci** [comment]
here @liliakai's elliptic bubble in comparison with new elliptic bubble with "moved" bubble pointer:
![signal-elliptic](https://cloud.githubusercontent.com/assets/16047081/22072816/cb6f75ae-dda3-11e6-91d7-9e92862ab96a.png)
The whisper lines must be redone!

**Comment by iadmir** [comment]
Ok, here is redesigned icon with elliptic bubble.

![current-new](https://cloud.githubusercontent.com/assets/23726384/22117369/fc1e24e0-de73-11e6-8044-d8192eca3d08.png)

**Vector / EPS:** https://www.dropbox.com/s/20j7ar2d554vodu/source-vector-signal.eps?dl=0

## iOS
![ios-250](https://cloud.githubusercontent.com/assets/23726384/22117628/fddaf528-de74-11e6-82ce-96b4cfee2f36.png)
## Android - Material design
![android-square-250](https://cloud.githubusercontent.com/assets/23726384/22117505/9174c74c-de74-11e6-95ed-75aa2e00f446.png)

![android-circle-250](https://cloud.githubusercontent.com/assets/23726384/22117504/9173a754-de74-11e6-9663-dbe697f19074.png)

**Comment by Stanzilla** [comment]
That fold in the Android icon looks a bit off

**Comment by bungabunga** [comment]
Nice. The grey color in the comic cloud gives icon a nice 3D feeling. But it's a question if this 3D feeling isn't making the logo less comic-book-ish. Maybe a white only variant should also be here to compare and decide.

**Comment by iadmir** [comment]
@bungabunga I just updated my previous comment

**Comment by moxie0** [comment]
Thanks everyone, some real talent in this thread. Let's stick with the current "rotation" for now and focus on getting Android into parity with iOS and the desktop. Then we can think about whether or not we want to rotate all three later.

I think what we need here is a PR with the launcher icon, actionbar icon (top left in conversation list activity), and notification bar icon for all the screen densities.  Thanks!

**Comment by FeuRenard** [comment]
> I think what we need here is a PR with the launcher icon, actionbar icon (top left in conversation list activity), and notification bar icon for all the screen densities.

You missed the lock screen icon. lockscreen_watermark_light.png & lockscreen_watermark_dark.png

**Comment by sweeper3000** [comment]
There's now a PR: #6100

**Comment by mueller-ma** [comment]
The square icon is used to indicate Signal when using the direct share feature. In my opinion a round icon would look better here

**Comment by mspacek** [comment]
Seems I'm very late to the party, because I only update sporadically (I typically run my phone without a google account). IMO, changing the icon is a bad decision for several reasons:

1. Branding. The keyhole represented the most important feature of Signal: security. Playing devil's advocate, does no more keyhole mean no more encryption?

2. Familiarity. For very technically naive users, and visually impaired users (my Mom rates as both), a drastic change in icon is confusing. It's easy to come to the conclusion that "Signal has disappeared, now all I have is this weird icon in its place, has someone hacked my phone?"

3. It looks awful. I appreciate that a lot of work went into it, but the icon is uglier, more complex, yet conveys no meaning whatsoever. It's now just another generic chatty app icon. Why all the white space? What's with the dashed lines? Cut here with scissors? "Whisper" is the last thing the dashed lines say to me, and even if they did, most users would not associate "whisper" with Signal.

My impressions are based on what I've seen in Android 5 (CM 13), and I feel as strongly now about this as I did a week or two ago when I first saw it. If this is what the icon looked like the whole time on iOS, and there was a dire need to sync the icons between the two platforms, was there a discussion somewhere about which one should be changed? Was the decision based on which platform has more users?

**Comment by FeuRenard** [comment]
This issue should be fixed by #6100, right?

**Comment by Stanzilla** [comment]
Well I guess work never stops, you could make a new one for moving to Android O's adaptive icons https://developer.android.com/preview/features/adaptive-icons.html

**Comment by FeuRenard** [comment]
That's already tracked in #6511.

**Comment by jeremymasters** [comment]
Seems like this thread should get locked because it's just an ongoing discussion which would probably be better for the discussion forum.

**Comment by trgeiger** [comment]
I'm gonna close the issue since the original issue has been addressed in #6189
