### ISSUE TITLE
Unable to make call

### ISSUE THREAD

**Issue by jsmootiv** [WhisperSystems/Signal-Android#5937]
A contact called me and we talked for a few minutes. I was randomly disconnected for no apparent reason.

Now when I click the call button it changes to the "calling contact" view but nothing happens.

Restarting the app does nothing.

Debug log:
https://gist.github.com/e91931917bacfddd3ff97c22392e1a90

**Comment by riyapenn** [comment]
Dupe #5660?

**Comment by 2-4601** [comment]
Yeah, seems very much like a duplicate.
save us webrtc :pray:
