### ISSUE TITLE
Inconsistency: When watching a video and pressing the gallery button, the video is not in the list of "all pictures"

### ISSUE THREAD

**Issue by EmilVogt** [WhisperSystems/Signal-Android#5941]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Thanks for adding support to play videos in-app. When playing videos of a conversation in-app, the button to go to the gallery ("all pictures") is visible. After pressing the button one can see all the pictures of the conversation. The video, from where I was directed to the gallery, is not visible, though.

### Steps to reproduce
- go to a conversation
- open a video
- press the gallery button ("all pictures")

**Actual result:** I see all pictures of the conversation.
**Expected result:** Two possibilities:
1. I can see the video in the gallery view as well, since the video is where I come from. (Renaming of the string "all pictures" to "all pictures and videos" or similar)
2. There's no gallery button when watching the video.

### Device info
**Signal version:** 3.24.1

**Comment by 2-4601** [comment]
https://github.com/WhisperSystems/Signal-Android/commit/09ff8d58659708f0162d1fd68ed84c25201cae41#commitcomment-20060347
