### ISSUE TITLE
The first contacts disappeared

### ISSUE THREAD

**Issue by Jens14L** [WhisperSystems/Signal-Android#5942]
### Bug description
The alphabetically first 4 contacts (Alexander, Andreas, Annika, Bennet) are not displayed in Signal’s contact list.

### Steps to reproduce
- Open contact list
- Sync contact list (if applicable), but no change

**Actual result:** The alphabetically first 3 contacts are missing in the contact list.
**Expected result:** All contacts are displayed in the contact list.

### Device info
**Device:** LG Google Nexus 5 (Hammerhead)
**Android version:** 7.0
**Signal version:** 3.24.1/3.25

### Link to debug log
https://gist.github.com/anonymous/435977b9eca138170271328ac39eb87d

**Comment by riyapenn** [comment]
Just pointing out some ways to test/check in case it applies, feel free to disregard:
1. If you have Signal as your default messaging app, then you will see all contacts.  If not, you will only see Signal contacts.  
- [ ] Do you have Signal set as your default messaging app? 
- [ ] Are these "missing" contacts, Signal users?  

2. Check if these first three contacts are showing up lower down your conversation list. 
- [ ] If you manually enter the phone number for one of the expected first three contacts, does a conversation thread pop up with a contact name?  
- [ ] If yes, would that contact name be shown at a later point in your contact list? 

3. Does a complete resync of Signal contacts resolve this? 
Android phone settings > Accounts > Signal > Remove (the alert of clearing data is incorrect, your messages will not be deleted) > Open Signal > Message compose icon > Menu > Refresh

**Comment by Jens14L** [comment]
1. - [x] Signal is not anymore my default messaging app because now I use SMSSecure for SMS/MMS.
- [x] No.
- [x] Yes, all missing contacts are Signal users.
2. - [x] I am able to write with all my active Signal contacts.
- [x] Entering manually the number: Yes, it pops up with a contact name.
- [x] No, it does not.
3. - [x] Unfortunately, that made no difference.

**Comment by riyapenn** [comment]
Did you check the formatting of the phone numbers of these contacts to exclude leading 0's and include area code etc? See also the [support page here (specifically the THIRD step)](https://support.whispersystems.org/hc/en-us/articles/215089628-Why-can-I-only-privately-message-one-way-)

**Comment by Jens14L** [comment]
Thank you! But the number format changes did not make a difference. Signal links of the affected contacts were missing and not added (after syncs) in the Android contacts.
The update (dirty installation) from version 3.24.1 to 3.25 could not correct the malfunction.

Unfortunately, the only thing that resolved the issue was the complete re-installation.
