### ISSUE TITLE
Notification light does not appear to work on Android 7.1.1 (Signal Beta)

### ISSUE THREAD

**Issue by AboveMyPaygrade** [WhisperSystems/Signal-Android#5946]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Notification light does not appear to work on Android 7.1.1 (Signal Beta)

### Steps to reproduce
- Receive a text from another Signal user

**Actual result:** Notification sound plays, and notification appears on the screen and notification bar, but notification light does not blink on the phone itself.
**Expected result:** Notification sound plays, notification appears on the screen and notification bar, and notification light blinks on the phone itself.

### Device info

**Device:** Huawei Nexus 6P
**Android version:** 7.1.1, Stock, Rooted, Build number NMF26F, Security patch level December 5, 2016
**Signal version:** 3.24.1 (Beta Tester)

### Link to debug log
https://gist.github.com/anonymous/92753336929b028440eb77bec0569020

**Comment by mateoeh** [comment]
Can't reproduce

**Device:** Galaxy S5
**Android version:** CyanogenMod 14.1 (Android 7.1.1) with December patch
**Signal version:** 3.24.1 (beta)

**Comment by piratenpanda** [comment]
Works fine here too N6p, nitrogen rom, latest 7.1.1r4

but well, maybe it's a stock issue then?

**Comment by 2-4601** [comment]
@AboveMyPaygrade Is this something that happened after you updated to 7.1.1 and the notification light worked before that?

**Comment by AboveMyPaygrade** [comment]
I recently upgraded from 6.0.1 to 7.1.1.  However, when I upgraded, I did a full wipe and reinstall of stock, so technically, it's not an in-place upgrade.

**Comment by piratenpanda** [comment]
Does it work for all other apps?

**Comment by AboveMyPaygrade** [comment]
@piratenpanda Actually, I hadn't checked to see if it was an issue with any other messaging apps (apologies; my goof).  I went ahead and checked it out with the other two messaging apps I frequently use:  _Conversations_ and _Hangouts._  

_Conversations_ appears to be working without a hitch, notifications and all.  _Hangouts_, on the other hand, appears to be suffering from the same issue _Signal_ is (on my device).  Other than the obvious commonality of both apps relying on GMS (_Hangouts_ being used in conjunction with GV), I don't know why it would affect _Hangouts_ and _Signal_ without affecting _Conversations_.  I checked all the notification settings to make sure there wasn't something bizarre happening on that end (both per-app settings and global settings).

Considering this new bit of information, could it be it's a bug with stock 7.1.1 Android, as opposed to with _Signal_?  If you and others feel this is the case, I'll close out the issue.

**Comment by AboveMyPaygrade** [comment]
After digging around a bit more, I found another global setting within Android for notifications, which had been toggled off.  I don't know if it defaults to off, or if it was just user error (that user being me), but everything seems to be working well enough now.  Sorry for the hassle.
