### ISSUE TITLE
Crash loop on attempting to send image

### ISSUE THREAD

**Issue by btittelbach** [WhisperSystems/Signal-Android#5949]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
A friend tried to send me a just then taken photo. On preparing the image for sending, signal enters a crash loop. The application becomes unsuable. The crash loop can be broken by disabling wifi and mobile internet and deleting the faulty multimedia message.

Symptoms are similar to Bug #5310, the difference being that on my friends phone the error log shows an OutOfMemoryError which does not appear there. Btw: larger images sent without problems.

Even though the image displays fine everywhere else, it might be faulty.

### Steps to reproduce
- Download 20161210_133710.jpg from dropbox link below to phone
- Check sha256 hashsum to verify it is indeed the same image that crashes Singnal on my friends Samsung 
- Enable Wifi / Mobile Internet
- Send Image to another contact using Signal

**Actual result:** Signal crashes repeatedly every few seconds when not in use or when entering the application and becomes unusable.
**Expected result:** Signal should catch all image-processing errors and not crash.

### Steps to recover from error
- Disable Wifi / Mobile Internet
- Enter Signal, delete faulty Image / Message to stop Singal from crashing

### Image that crashes signal + Versioninfo

https://www.dropbox.com/sh/ou6tintrxzw6okd/AABYd3GrkjnkS1SH0dgGl3oZa?dl=0

### Device info

**Device:** samsung SM-G900F (kltexx)
**Android version:** 6.0.1
**Signal version:** 3.24.1

### Link to debug log

https://gist.github.com/anonymous/4257a85bab5f738c8496329c80d5d655

**Comment by 2-4601** [comment]
5/5 bug report :sparkles: 

I can reproduce this with two devices: 1 Gb RAM Lollipop 5.1.1 and 2 Gb RAM 6.0.1
After Signal crashed I turned on airplane mode, did NOT delete the pending message, turned off airplane mode and then the message got sent successfully without crashing.
Debug log:
https://gist.github.com/58e36041e1e832f7695cbdeca61043fe

**Comment by moxie0** [comment]
@btittelbach Thanks for the exceptionally well done bug report. I'm going to look into making some larger structural changes in the way we handle image scaling as part of addressing this, so I'm going to move it to 3.26.0

**Comment by ashjas** [comment]
i tested this on Nexus 4 Running 7.1.1 NitrogenOS . No crashes, it sends fine.
Attaching logs for the session, if it can help in any way..
Log:
https://gist.github.com/ashjas/71c017d560aa2f5348dfad3ce378c3d1

**Comment by moxie0** [comment]
in 3.26.0
