### ISSUE TITLE
MMS Remove GIF ability or filter GIFs to <300kb

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-Android#5958]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Most Gifs fail to send on MMS, user frustration

### Steps to reproduce
- Open thread with non-Signal contact
- tap attachment icon > choose GIF
- choose nearly any GIF
- attempt to send message

**Actual result:** message fails to send
**Expected result:** Do not have option to attach GIF that is greater than the size limit
Options (though not limited to this)
1. Only display gifs that are within the size limit
2. Show alert that the gif size is too large / fail immediately and do not display draft
3. Remove GIF attachment for non-Signal users (still creates conflict if user switches from Signal messages to insecure MMS mode)

Somewhat related:
Size constraint handling: https://github.com/WhisperSystems/Signal-Android/issues/3768
Increase MMS size: https://github.com/WhisperSystems/Signal-Android/issues/496

**Comment by sweeper3000** [comment]
I think filtering the gifs for MMS would be best, it allows users to easily send gifs (not as much of a diverse selection as Signal -> Signal users get) to sms/mms only contacts. It shouldn't be harder to send a gif, that's a big reason why gify was implemented.

**Comment by moxie0** [comment]
in 3.25.0
