### ISSUE TITLE
"Our Signal safety numbers:" string appears twice with some Share targets

### ISSUE THREAD

**Issue by isislovecruft** [WhisperSystems/Signal-Android#5959]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
With some Share targets, such as Twitter DMs, the string "Our Signal safety numbers:" appears twice, followed by the safety number.

### Steps to reproduce
- Go into "Conversation Settings > Verify safety numbers"
- Press the Share button in the upper right corner
- Share via Twitter DM

**Actual result:** The string appears twice.
**Expected result:** The string should only appear once.

### Screenshots
![snapshot105](https://cloud.githubusercontent.com/assets/907241/21167877/8def86a0-c1a7-11e6-9fed-786454c85756.png)

### Device info

**Signal version:** 3.23.0

**Comment by isislovecruft** [comment]
I think this is due to this code in `VerifyIdentityActivity.handleShare()`:

```
  private void handleShare() {
    String shareString =
        getString(R.string.VerifyIdentityActivity_our_signal_safety_number) + "\n" +
        displayFragment.getFormattedSafetyNumbers() + "\n";

    Intent intent = new Intent();
    intent.setAction(Intent.ACTION_SEND);
    intent.putExtra(Intent.EXTRA_SUBJECT, getString(R.string.VerifyIdentityActivity_our_signal_safety_number));
    intent.putExtra(Intent.EXTRA_TEXT, shareString);
    intent.setType("text/plain");
```

Specifically, the `Intent.EXTRA_SUBJECT` line. We probably want to leave that one, so that the Subject line in e.g. emails is set to "Our Signal safety numbers:" and remove it from `shareString`. However, would that also remove it from things which disregard the `Intent.EXTRA_SUBJECT`?

**Comment by FeuRenard** [comment]
Exactly that is the problem, I already mentioned in #5854.

**Comment by moxie0** [comment]
Can we identify anything that ignores EXTRA_SUBJECT?

**Comment by isislovecruft** [comment]
@moxie0 Yes, unfortunately, nearly everything else ignores EXTRA_SUBJECT, e.g. Signal, Conversations, Xabber, Google Hangouts, Twitter (public tweets, not DMs). Everything except email clients appear to ignore it.

**Comment by moxie0** [comment]
I see, so the only problem we know of is w/ Twitter DMs?

**Comment by FeuRenard** [comment]
Threema shows the same behaviour as Twitter DMs, description string twice but separated by a hyphen.

**Comment by moxie0** [comment]
in 3.26.0
