### ISSUE TITLE
Block numbers outside my contact list

### ISSUE THREAD

**Issue by shrakrak** [WhisperSystems/Signal-Android#5963]
Add an option to allow completely blocking messages from contacts not in my contact list.
This is very useful for children, to disable the possibility of them being approached by strangers.

**Comment by nullpointer17** [comment]
I am working on this, I will warn you here when finished... and let's hope they will accept the request :)

**Comment by shrakrak** [comment]
Thanks for the update :)
good luck.

**Comment by nullpointer17** [comment]
Done, I've tested it on my device and it's working... if you want to try it you can compile from my fork or just wait for the merge.

**Comment by shrakrak** [comment]
great, thanks!
