### ISSUE TITLE
3.25.0 introduced probably unintended UI changes 

### ISSUE THREAD

**Issue by FeuRenard** [WhisperSystems/Signal-Android#5965]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
6308e64 introduced this, let the screenshots speak for themselves.

Besides the changes you can see in the screenshots the animation when you send a message and the new bubble appears changed slightly, I think.

### Screenshots
A wild Signal icon appears in...
... NewConversationActivity
![device-2016-12-17-122927](https://cloud.githubusercontent.com/assets/16167751/21286633/e706d19e-c459-11e6-8247-4a40efcd2651.png)
... RecipientPreferenceActivity
![device-2016-12-17-122942](https://cloud.githubusercontent.com/assets/16167751/21286635/e8d24350-c459-11e6-8b6f-6c3f5fd48e43.png)
... InviteActivity
![device-2016-12-17-123004](https://cloud.githubusercontent.com/assets/16167751/21286636/ea7623de-c459-11e6-996f-bc63e29c066b.png)
... GiphyActivity
![device-2016-12-17-123039](https://cloud.githubusercontent.com/assets/16167751/21286637/ed0403a0-c459-11e6-91cd-ccaf02dcf8d5.png)

Mind the gap between back arrow and recipient, before 6308e64
![bildschirmfoto von 2016-12-17 12-42-49](https://cloud.githubusercontent.com/assets/16167751/21286642/fd4a97f6-c459-11e6-8882-a0a6b2cacdee.png)
After 6308e64
![bildschirmfoto von 2016-12-17 13-01-04](https://cloud.githubusercontent.com/assets/16167751/21286647/09779b64-c45a-11e6-878e-e2175ccc0ebc.png)

**Comment by Dyras** [comment]
I actually like the last change...

**Comment by moxie0** [comment]
That's what we get for updating. Thanks!

**Comment by 2-4601** [comment]
> the animation when you send a message and the new bubble appears changed slightly, I think.

Yeah, noticed that too. It's weird but I guess one gets used to it quickly.

**Comment by moxie0** [comment]
I got rid of the surprise app icon everywhere. The padding change is apparently to enforce the material standards. I think it's a waste of space on the contact search/selection activities so I disabled it there, but left it everywhere else.

That animation change is terrible! Anyone want to look into it?

**Comment by moxie0** [comment]
It looks like the ItemAnimator's "add" animation is getting canceled, so it displays immediately before the move animation for the items above it is complete. There are many changes to the data set in quick succession (pending, sent, delivered), and it seems that those changes are canceling the animation. Not sure why.

**Comment by moxie0** [comment]
I've reverted the support library updates. I think we'll have to stop calling notifyDataSetChanged() in order to update them, which is kind of a big change, so I'm going to delay making it for now.

**Comment by nrizzio** [comment]
Is it just me, or are a lot of these problems back in 3.26.0? I think this issue should be re opened.

**Comment by FeuRenard** [comment]
I spotted the wild Signal icon in GIF search and the additional space in several activities' action bars.

**Comment by moxie0** [comment]
@nrizzio what are you seeing other than the signal icon in gif search?

**Comment by nrizzio** [comment]
@moxie0 the extra padding between the back arrow and recipient in a conversation thread is back, along with the awkward animation when a new message is sent/received.

**Comment by moxie0** [comment]
@nrizzio That extra padding is "intentional" now. You should be seeing the normal animation, though. What kind of conversation is it?

**Comment by nrizzio** [comment]
@moxie0 It's an encrypted Signal conversation. The problem exists in encrypted one-on-one and group chats. But the awkward animation will go away when using unencrypted text transport.
Here is a debug log: https://gist.github.com/6bdeb7312cefccec54619ee07746aab0

**Comment by FeuRenard** [comment]
I see the old animation for Signal messages on Android 5.1.1.

**Comment by moxie0** [comment]
I decided to just remove the conversation item animations. There are some pretty bad recyclerview bugs that I can't work around, and it actually feels faster this way.

**Comment by Trolldemorted** [comment]
I have upgraded from 3.24.0 to ~the current master branch~ b7d4294314a2fca23821d56077ae382e8f90bfdb and i am pretty sure opening threads takes a little bit (something between 100 and 500ms i guess) longer.

I have held two signal instances on the same phone (same model, same OS version, same gapps) next to each other and opened the same thread multiple times: the 3.24.0 build has beaten the current master every time.

If i close a thread, press the home button and press the signal icon on the homescreen (must be homescreen) to open signal again, the next thread is opened significantly faster (i.e. long before the button-press animation finishes).

My local changes should not be related to this particular issue.

**Comment by moxie0** [comment]
@Trolldemorted if you can reproduce a performance issue please profile it and see where the time is going

**Comment by Trolldemorted** [comment]
First i will have a look whether it is better after 5804213152b8f6cf6a9bd0225c5e2677ed39a5e2, since this sounds like it could be a recyclerview issue to me. If it is not, i will have a look!

**Comment by Trolldemorted** [comment]
5804213152b8f6cf6a9bd0225c5e2677ed39a5e2 did not fix it. I played a little around with the android device monitor:

[top: "normal" thread selection", bottom: thread selection using method described above]
![190ms](https://cloud.githubusercontent.com/assets/10261186/21754967/09c0185e-d60b-11e6-9163-08ef94cccd2a.png)

As you can see, during the "normal" thread selection we spend ~190ms more in `android.view.ViewRootImpl.doTraversal`, which would match my estimation of the delay. Any ideas what has caused this?

**Comment by moxie0** [comment]
@Trolldemorted sounds like a job for git bisect!

**Comment by Dyras** [comment]
I can confirm that on my Moto G4, opening a thread takes noticeably longer now.

**Comment by moxie0** [comment]
Bummer, if someone who can reproduce this wants to find the offending commit with git bisect, that'd probably help a bunch. Also let's open a new issue specifically for this performance degradation.
