### ISSUE TITLE
Feature: send messages to yourself

### ISSUE THREAD

**Issue by pedzed** [WhisperSystems/Signal-Android#5966]
(I'm not sure if this is the right place to put this issue, so sorry about that)

Often times it happens that I want to send a message to myself, but then I basically _have_ to send it to a contact (because I can't send it to myself). It would be nice to send messages to yourself, similar to what Slack has.

![image](https://cloud.githubusercontent.com/assets/8146593/21287021/08f41808-c463-11e6-980b-e23e9a533870.png)

Some possible reasons would be: not wanting to use a notepad, wanting to send a message from mobile to pc/pc to mobile, etc.

**Comment by Trolldemorted** [comment]
PR https://github.com/WhisperSystems/Signal-Android/pull/5905 will do exactly that, but i am waiting for moxie's approval before investing time to implement it.

**Comment by pedzed** [comment]
> PR #5905 will do exactly that, but i am waiting for moxie's approval before investing time to implement it.

Oh, I looked at the issues, but forgot about the PR's. Thanks.

**Comment by Trolldemorted** [comment]
There also is an issue: https://github.com/WhisperSystems/Signal-Android/issues/4844

**Comment by 2-4601** [comment]
:+1: That's probably enough to track this
