### ISSUE TITLE
Emoji glitching in emoji drawer

### ISSUE THREAD

**Issue by haffenloher** [WhisperSystems/Signal-Android#5973]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Apparently, tinting something that is not an ImageView is not supported on API <21. Therefore the new category icons from f7474362f look like this on 4.2:

![screenshot_2016-12-18-18-50-43](https://cloud.githubusercontent.com/assets/264472/21298856/0d6130fe-c596-11e6-813e-4f8158d7ecc4.png)

(also note how my phone still shows slight signs of #2957 :/) 

Looks like we would have to either generate separate light and dark theme PNGs or use setColorFilter somewhere to fix this?

**Comment by moxie0** [comment]
Damn, we'll have to make assets. What's your phone info? I'd like to create an emulator that will reproduce those visual glitches.

**Comment by moxie0** [comment]
Generated assets to fix the tinting issue, reopening to track the glitching you're seeing.

**Comment by lazlolazlolazlo** [comment]
I can reproduce the glitches (slight signs of #2957) with the following phone:
Device  : motorola XT1021 (cm_condor)
Android : 4.4.4 (430c6b1557, cm_condor-userdebug 4.4.4 KTU84Q 430c6b1557 test-keys)

**Comment by moxie0** [comment]
@lazlolazlolazlo I built an emulator with those device specifications and am unable to reproduce. Can you post a screenshot?

**Comment by haffenloher** [comment]
@moxie0 the phone's specs are [here](https://fairphone.zendesk.com/hc/en-us/articles/201064718-What-are-the-technical-specifications-of-the-Fairphone-1-)!

**Comment by lazlolazlolazlo** [comment]
![signal-2016-12-19-215427](https://cloud.githubusercontent.com/assets/601905/21329565/397ee500-c631-11e6-9cb1-2947cd09790e.jpeg)

**Comment by moxie0** [comment]
I can't seem to reproduce this in an emulator, guess I'm going to have to get a phone

**Comment by FeuRenard** [comment]
This issue is also reported in the community forum:
https://whispersystems.discoursehosting.net/t/updated-emojis-are-not-showing-correctly/1024

**Comment by haffenloher** [comment]
FYI, this issue disappeared for me after I played with Android's Accessibility settings (I turned the "Large text" option on and off again, which seems to have changed my phone's DPI settings?). Now everything is slightly larger. I have 8 instead of 9 emoji per row in the emoji drawer and the glitching is gone.

**Comment by FaizKhan5** [comment]
@moxie0 Again this problem happens in 4.12.0

**Comment by warblend** [comment]
But this time it is not restricted to the drawer but also happens in messages.

**Comment by moxie0** [comment]
I'm unable to reproduce this on a Samsung S4 (Android 4.4), OnePlus One (Android 5), Nexus 5 (Android 6), Moto G (Android 6), or Pixel (Android 8). @warblend Is there anything particular about your device that you can think of?

**Comment by FaizKhan5** [comment]
@me and my friend using Qmobile my Android 6.0 and friend Android 5.2 i think we have same problem like @warblend

**Comment by warblend** [comment]
@moxie0 I will think about it,but right now nothing specific comes to my mind. It seems to be related to the device as a friend of mine who owns a phone of the same model is experiencing the same issue.

**Comment by nrizzio** [comment]
I'm also having the same issue. Interestingly, my emoji drawer has a pattern to it: 6 emojis are spread out over 8 emoji boxes. If more screenshots/information is needed, let me know.

![signal-2017-11-03-194754](https://user-images.githubusercontent.com/13669330/32399901-7093507c-c0d0-11e7-9e8b-17445574e1ae.jpeg)

**Device:** Samsung Galaxy Grand Prime
**Android version:** 5.1.1
**Signal version:** 4.12.0
**Debug log:** https://gist.github.com/anonymous/8078d907268ba77d99bc01a5b9fe169e

**Comment by Oisins** [comment]
It's also broken for me.
![](https://i.imgur.com/rzS2pwL.png)
Huawei P8 lite ALE-21
Android 6.0
Signal 4.12

**Comment by IronJunkie** [comment]
Also have this issue on LineageOS 7.1.2 after  latest Signal beta 4.12.2 update. Samsung S4 Mini. Also emoji generated by keyboard show the same multiple/split emoji images when entered into Signal text field but appear correctly within the keyboard. I haven't adjusted pixel display etc… but It is a small phone.

**Comment by IronJunkie** [comment]
Possible workaround, turn off Signal emoji in Signal settings so that signal uses your phones system emoji, then emojl appear correctly in Signal messages.

**Comment by FaizKhan5** [comment]
@moxie0 but now after 4.12.3 update emojis edges are rough now not clear circle face emojis.
