### ISSUE TITLE
Most phone numbers lost link to contacts after update to Signal 3.25.0

### ISSUE THREAD

**Issue by cryptomilk** [WhisperSystems/Signal-Android#5974]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After the update to Signal 3.25.0 most of my conversation show just the phone number and not the name anymore. I think this is because of the update of libphonenumber.

The strange thing is phone number are displayed differently:

+49 173 xxxxxxx
+49176xxxxxxxx
+49 176 xxxxxxxx

Why do some number have spaces an others don't?

### Device info
I'm running Android 7.1.1 (CyanogenMod 14.1). Let me know if I can provide more details.

This is related to the libphonenumber update in libsignal-service-java:
https://github.com/WhisperSystems/libsignal-service-java/issues/29

There is an upstream libphonenumber issue here:
https://github.com/googlei18n/libphonenumber/issues/1443

**Comment by cryptomilk** [comment]
Some of the numbers are rendered correctly (with spaces) like +49 176 1234567 others aren't like +4916012345678 (one additional digit compare to the example before). I will provide a log file later.

**Comment by cryptomilk** [comment]
The number with 10 digits seem to be rendered correctly, the ones with 11 aren't. The history from pre-3.25.0 conversations are intact.

**Comment by moxie0** [comment]
Thanks @cryptomilk can you give an example of how a number is rendered incorrectly?

**Comment by cryptomilk** [comment]
Normally libphonenumber splits numbers up with spaces. A prefix (+49 for international, 0 for national) then the area code (150, 151, 160, 170, 171 etc) an then the end user number. Area code and end user number are normally 10 or 11 digits. However it looks like libphonenumber only accepts 10 digits and not 11.

+49 176 1234567

This seems to be a correctly processes number by libphonenumer, but it doesn't have a link to a contact.

Then I see conversations for

+4916012345678

This has 11 digits (160 area code + end user number) and seems not to be correctly recognized by libphonenumber. They have a bug open and requested an official document which state longer numbers are allowed. I've posted them the document form the office in Germany regulating the numbers and give out the blocks. I will create a log file now

**Comment by cryptomilk** [comment]
Log from Signal:

https://gist.github.com/anonymous/d430d19f0ead6d0c06b642947564420c

What you see:
The log is from a clean startup, entering the passphrase. Then I selected the conversation from a correctly detected number (+49 176 1234567) and next the conversation from a incorrectly detected number (+4916012345678).

**Comment by cryptomilk** [comment]
The test only tests number with 9 digits. I'm not sure if they exist. It is possible that such numbers were used before 2009. So duplicate the tests from line 46 to 56 with longer numbers: 1234567 and 12345678.

Reading the official document from the Budesnetzagentur only number with 10 or 11 digits are allowed (7 or 8 digits for the end user number). Should I create a PR for that test adding them?

**Comment by moxie0** [comment]
@cryptomilk Please just give me a sample phone number input and its erroneous output.  Eg.

+491231234 is formatted erroneously as +491231235

Thanks

**Comment by moxie0** [comment]
Wait, are you just saying that the phone number is correct but there's no spaces?

**Comment by cryptomilk** [comment]
Contacts in Signal shown as:

+4916012345678
+491701234567

this is how they are stored on the phone, after libphonenumber parses the numbers, they are normally printed in the format:

+49 160 12345678
+49 170 1234567

**Comment by cryptomilk** [comment]
https://libphonenumber.appspot.com/phonenumberparser?number=+4916012345678+&country=DE

Here it is parsed correctly

**Comment by moxie0** [comment]
I see, so just spaces? That shouldn't make a difference. 

In your first post you seem to mention that even the numbers with spaces do not show contact information, is that true? How long have you been running 7.1.1, are you sure this isn't #5808?

**Comment by cryptomilk** [comment]
#5808 seems to be the issue.

**Comment by moxie0** [comment]
Thanks, so you upgrade to 3.25.0 coincided with an Android upgrade?

**Comment by cryptomilk** [comment]
No, I upgraded to Android 7.1.1 earlier. It might be that it came with an upgrade of my server where my contacts are stored, so the sync might have triggered this at the same time with the Signal upgrade.

**Comment by moxie0** [comment]
Alright, it seems like Signal is going to have to start storing contact names in order to support 7.x, but we'll have to get to that in 3.26.0.  Thanks for all the help!

**Comment by cryptomilk** [comment]
Here is a guess. Signal contacts where linked to the Contacts App. DAVdroid sync. The sync was redone so all accounts where gone. The mapping disappeared and Signal created or linked them with these read-only accounts. It looks like to get the correct mapping you need to hide all these read-only accounts in Signal again to get the correct mappings.

**Comment by cryptomilk** [comment]
**Workaround**

- Open the "Contacts" App
- Open the menu and select "Contacts to display"
- Select Signal
- Long press on the first contact (opens multiple selection option)
- Select all your Signal contacts
- In the menu select "Delete"

The Signal contacts are read-only contacts. This will hide all Signal contacts and Signal will map all accounts to Contacts (Google, DAV, etc.)

moxie0 you might want to post that in the FAQ section ...

**Comment by riyapenn** [comment]
Would your work around accomplish the same as removing the[ Signal account from Settings > Contact's app](https://support.whispersystems.org/hc/en-us/articles/216595418-Where-are-my-Signal-contacts-How-can-I-see-the-names-of-my-Signal-contacts-)?

1. Go to Android Settings or 
2. Android Contacts App > Menu 
3. Choose Accounts
4. Choose Signal
5. Tap on the Menu
6. Choose Remove Account (the alert of clearing data is incorrect, your messages will not be deleted)

**Comment by cryptomilk** [comment]
Yes, I think this achieves the same.

I guess the following happend in my case:

I had to resync my contacts as I updated the DAV server. So Signal lost the contacts mapping and created its own. When you "delete" them you hide them and your Contacts are used to map accounts. I didn't look at the Android sources yet so this is just a guess.

**Comment by moxie0** [comment]
in 3.26.0
