### ISSUE TITLE
Possible server issues on european servers?

### ISSUE THREAD

**Issue by MatejKovacic** [WhisperSystems/Signal-Android#5976]
I have:
- [ X ] searched open and closed issues for duplicates
- [ X ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I am trying to call someone via Signal, and call does not go through. I can hear only "sonar voice" and then get "Network error" message.

I contacted some of my friends, and they are experiencing the same error. Hoever, messages are going through just fine.

My location is Slovenia, Europe.

### Steps to reproduce
- Try to call someone.

**Actual result:** No call can be made, I get "Network error" message.
**Expected result:** Call should be made or at least ringing should be heard.

### Device info

**Device:** Nexus 5
**Android version:** CM 13
**Signal version:** the latest (up to date)

**Comment by sweeper3000** [comment]
It doesn't look like something on [Amazon's end](https://status.aws.amazon.com) (Signal uses Amazon servers).  Check out this [support article](https://support.whispersystems.org/hc/en-us/articles/216479567-Why-does-my-call-never-ring-Why-do-I-only-hear-the-sonar-sound-Why-can-t-I-hear-on-the-call-). Are you aware of the provider blocking VoIP traffic?

**Comment by MatejKovacic** [comment]
I am not really sure, but oficially mobile providers in my country are not allowed to block anything. And also they never blocked Signal in the past - few days ago everything was working smoothly.

**Comment by sweeper3000** [comment]
Is your contact connected to the internet when you attempt the call? A debug log captured right after a failed attempt may help the developers out.

**Comment by MatejKovacic** [comment]
This is the system log after a friend of mine tried to call me: https://gist.github.com/f878118caeb1c797aa11a4d59005540b

I have heard ringing, answered but connection was not successfull.

In fact, I can place a call now, I can hear ringing, but after connection, nothing is happening. I cannot talk to the other party. After a few moments I just got disconnected. I tried via 4G and wifi.

However, messaging goes through well.

**Comment by MatejKovacic** [comment]
Right now, I was able to answer the call, but communication was so bad, I couldn't talk at all. I remember there has been a similar bug:
https://github.com/WhisperSystems/Signal-Android/issues/5836

**Comment by sweeper3000** [comment]
I don't develop Signal, I don't know VoIP issues too well. But I think this should be enough info for @moxie0 to take over.

**Comment by sweeper3000** [comment]
It may be helpful to see [this](https://support.whispersystems.org/hc/en-us/articles/213697218-Which-TCP-UDP-ports-need-to-be-available-). It has to do with what TCP and UDP ports need to be open. It also tells you how to know if your or your contact's ports are blocked.

**Comment by MatejKovacic** [comment]
C'mon people. Ports are open. A day ago everything was working. I tested Signal from several networks (mobile, wifi,...).

Anyway, now it is working again.
