### ISSUE TITLE
Signal is censored in Cuba

### ISSUE THREAD

**Issue by legovini** [WhisperSystems/Signal-Android#5978]
As I see from https://github.com/WhisperSystems/Signal-Android/commit/541718fd114a6f2336222a571869e1056cd122dd Signal does implement some ways to circumvent censorship. This issue is mostly a report, I'm not sure if anything can actually be done.

- I've been in Cuba recently with Signal, registered with an European phone number (there are wifi hotspots in public locations);
- The Signal servers are not reachable from Cuba, I could not send/receive messages;
- It did work properly using Tor (Orbot).

I see from the commit I referenced that Signal identifies censoring countries with their international phone prefix, so I'm not sure if it would have helped in my case. I did not try to register with a Cuban phone number.

**Comment by moxie0** [comment]
Thanks @legovini. Is google.com also censored in Cuba?

**Comment by legovini** [comment]
I clearly remember google.com working, but I'm not completely sure I could reach it via https. Anyway I think so, as google uses HSTS, so it's not easy to tls-strip. Sorry for the lack of details, I could dedicate very little time to these issues.

If I was actually using https (as I believe) the certificate was valid. (For the record, this was not the case for a popular "anonymous VPN" provider, for which I was served a fake and clearly invalid certificate.)

**Comment by moxie0** [comment]
Thanks @legovini. How were you accessing google.com, via Chrome?

**Comment by legovini** [comment]
@moxie0 via Chrome (from the Play Store) and Lightning (webview-based browser from f-droid).

**Comment by johanw666** [comment]
I doubt that would help @legovini , since Signal looks at the phone number of the sender of the message to determine if reflection should be used. If you're in Cuba with an European number Signal will try the default server. There should be some method implemented that checks the country you're in, or switches automatically to reflection if the default serer  appears to be blocked.

**Comment by moxie0** [comment]
in 3.26.0
