### ISSUE TITLE
[feature-request] Possibility to disable multiple clients

### ISSUE THREAD

**Issue by shibumi** [WhisperSystems/Signal-Android#5979]
Hello,
There was a case in Germany some months ago, where a suspects end-to-end messenger traffic has been decrypted by the German police. In this case it was the application `telegram`.
But I started thinking about this issue, and maybe the same hack could be used with signal too.

You might know that signal has a desktop application. The German police used a desktop Application like this to get access to the messages of the suspect.
They just requested access to a desktop application, man-in-the-middle'd the incoming Activation-SMS, and had full access to the messages. [1]

Is this possible with Signal, too? 
It would be nice to have an option to disable multiple clients

[1] https://motherboard.vice.com/de/read/exklusiv-wie-das-bka-telegram-accounts-von-terrorverdaechtigen-knackt (GERMAN, sorry no english version available)

**Comment by mawed** [comment]
No it should not be possible with Signal-Desktop as their is no possibility to activate Signal-Desktop within the active registration over sms, only with a QR-Code within an active registration on a mobile client.

But they could register your phone number on a new device using man-in-the-middle on the registration sms. In this case your active registration will be deregistered, your contacts will get a message for a new security number, but as there are no messages stored on the server, they won't have access to your previous messages on this way.

**Comment by johanw666** [comment]
It should also not work with Telegram's secret chat, which does have e2e encryption (wether that encryption is good or bad is aniother question). Normal Telegram chats don't have e2e encryption.

**Comment by Trolldemorted** [comment]
@johanw666 are you sure the desktop does not support e2e? that would be ridiculous!

**Comment by 2-4601** [comment]
Sounds like this discussion should go somewhere else than the tracker :)
