### ISSUE TITLE
[feature-request] Make domain fronting an option (for now)

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/Signal-Android#5986]
Because domain fronting will not work when, for example, you go to Egypt as a tourist with a number from another country, it would be nice to be able to switch it on with an option. When automatic detection of blocking is implemented this option could then be removed again.

Another question: why not enable domain fronting for everyone? In some countries Signal may not be blocked but contacting the Signal servers may give you a big "red flag" from intelligence agancies. Is there some technical or other reason why activating it for everyone would not be a good idea?

**Comment by moxie0** [comment]
Thanks but we're not going to do this.  The answer is not more options.
