### ISSUE TITLE
SMS verification not working in UAE

### ISSUE THREAD

**Issue by md3kung** [WhisperSystems/Signal-Android#5988]
I have:
- [y] searched open and closed issues for duplicates
- [y] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
SMS verification doesn't work in the UAE for new users with phone numbers beginning with +971.

### Steps to reproduce
- Open application for first time
- Enter phone number
- Wait for number verification
- No verification message received and Verification fails

**Actual result:** Stuck in phone verification step.
**Expected result:** Receiving verification SMS and verifying phone number.

**Comment by johanw666** [comment]
Maybe they block the verification sms too at the provider level? Does the phone call work?

**Comment by md3kung** [comment]
SMS is blocked, phone call works for verification ! Thanks ... Tried an audio calls to an iPhone user that has signal installed it doesn't work, simple messages however do get sent.

**Comment by Trolldemorted** [comment]
Why is this closed? The sms issue was not resolved, or was it?

**Comment by johanw666** [comment]
Ifthe UAE blocks the verification sms, there is not much Whispersystems can do about that. Other than offer another registration option, which they already do.

**Comment by Trolldemorted** [comment]
since signal has a record of having trouble with numbers from smaller countries, i would not make that assumption without having a look. i mean, why would they block sms but no calls?

**Comment by johanw666** [comment]
I don';t know if they looked into it or not, but it is quite possible of course.

The sms is easily recognizable: it says "Your TextSecure verificationcode: 123-456" (numbers differ per activation). Flitering this string at the provider level is not that hard. The calls are made by voice systems that are used for a lot of other functions as well, blocking that may cause a lot of collateral damage.

**Comment by Trolldemorted** [comment]
anonymising the content seems reasonable to me, then. not just for this case, but also in general, as you might not want your provider/government/anyone to know that you are registering to signal!
