### ISSUE TITLE
Add Iran to censored countries list

### ISSUE THREAD

**Issue by jus7forfun** [WhisperSystems/Signal-Android#5992]
Here is the log that I can't connect to textsecure-service.whispersystems.org

https://gist.github.com/anonymous/fea6d946aea279e0a748ef4094d575af

Thank you so much.

**Comment by pprucia** [comment]
Could you verify that Google.com is working in Iran.

**Comment by jus7forfun** [comment]
Yes, google.com works in Iran.

**Comment by mrphs** [comment]
This is not going to work due App Engine being blocked to Iranian users by Google. Unless you switch to Amazon, Azure or other CDNs.

**Comment by haffenloher** [comment]
Just verified using some Iranian proxy:
```
curl https://google.com --header 'Host: maps.google.com' --proxy http://94.182.181.38:80
```
works, while
```
curl https://google.com --header 'Host: signal-reflector-meek.appspot.com' --proxy http://94.182.181.38:80
```
returns a 403 Forbidden HTML error document.

:(

**Comment by mrphs** [comment]
Yes, this has been an issue since the day that front domaining was used to bypass censorship. Google for whatever reason has decided to put harsher sanctions than what US gov imposes on Iranian people.
