### ISSUE TITLE
leaving a group turns off disappearing messages

### ISSUE THREAD

**Issue by radii** [WhisperSystems/Signal-Android#5996]
### Bug description
when a user leaves a group, the disappearing messages setting is turned off for the remaining members of the group.

### Steps to reproduce
- in a group, turn on disappearing messages. my group had ~8 members.
- verify that the disappearing setting is on (hourglass on messages)
- a member who was not the group creator left. (checking with the user to verify platform and version)
- my android build showed "[creator] set disappearing message time to Off" immediately after "[user] has left the group".
- the group creator states they did not turn off disappearing messages.
- following messages were not marked as disappearing. previous messages disappeared correctly. creator was able to re-enable disappearing after noticing the problem and new messages are disappearing, but the non-disappearing ones are still there.

**Actual result:** disappearing setting disabled when a user left.
**Expected result:** disappearing setting should remain enabled unless turned off explicitly.

**Comment by radii** [comment]
creator reports using Android 3.23.0 (unknown if an upgrade occurred since the original occurrence of the bug, but given how old that is, likely not)
user-who-left reports using ios 2.6.9

**Comment by haffenloher** [comment]
> user-who-left reports using ios 2.6.9

It's probably a Signal-iOS bug then (unless this also happens when an Android client leaves a group?)

**Comment by radii** [comment]
> It's probably a Signal-iOS bug then (unless this also happens when an Android client leaves a group?)
seems likely, we tried to repro with android 3.25.3 and disappearing stayed enabled. Feel free to move this to iOS if that's the right next step.
Sorry for filing in the wrong project, we didn't know which client was most likely responsible and didn't know that leaving-user was on iOS until recently

**Comment by michaelkirk** [comment]
Confirmed this looks like a bug in the iOS client, though I haven't personally been able to reproduce it even with an Android user in the group.

Moved here: https://github.com/WhisperSystems/Signal-iOS/issues/1566

**Comment by michaelkirk** [comment]
After looking into this a bit, I was only able to reproduce when Signal-Desktop got involved, and it appeared to affect Signal-Android and Signal-iOS equally. Is this consistent with what you saw @radii ?

Alex Android and Irma iOS are in a group with disappearing messages. Both are linked to Desktop.
When Alex leaves the group

- Irma's iOS device show "Alex left the group" (disappearing messages are still enabled)
- Irma's Desktop shows "Alex set the timer to off." and "Alex left the group."

Similarly if Irma left the group:

- Alex's Android device show "Irma left the group" (disappearing messages are still enabled)
- Alex's Desktop shows "Irma set the timer to off." and "Irma left the group."

**Comment by radii** [comment]
@michaelkirk I think you're seeing a different root cause than I saw, I'd be surprised if my ios user had desktop signal (but I will ask).
I definitely do not have desktop linked, I just have android. We saw the disappearing flag turned off globally in the group, not just for a subset of clients (which you seem to be reporting in your desktop scenario). My android still has the relevant metadata messages showing in the scrollback. (I can't post screenshots because the content is sensitive.)

**Comment by radii** [comment]
> @michaelkirk I think you're seeing a different root cause than I saw, I'd be surprised if my ios user had desktop signal (but I will ask).

The group creator does use Desktop as well as android, and:
 - creator sent the first message after the user left
 - the message was probably (fuzzy user memory) sent using desktop
 - and creator was reported by my client as turning off the setting

so does that make this a Signal-Desktop bug instead?
