### ISSUE TITLE
Incorrect notification: "contact name: Locked message..."

### ISSUE THREAD

**Issue by janvlug** [WhisperSystems/Signal-Android#6000]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
For one specific contact I receive regularly the _notification_ that I received a locked message. But I never received a direct message from this contact. However, I did receive messages from this person in a group in the past. This contact is currently not part of any Signal groups on my phone. It is always the same contact that is mentioned in the notfication.

### Steps to reproduce
- send myself a message from the dsktop
- quickly read the message on m phone
- wait a short while
- I receive a notification that I received a locked message from a specific contact
- touching the notification takes me to the contact, but there are no messages from this contact

### Device info

**Device:** bq Aquaris 3.5
**Android version:** 4.2.2
**Signal version:** 3.25.3

### Link to debug log
https://gist.github.com/9a4b4dbaf43f1655240bec9ce0565b0e
https://gist.github.com/fd1cb3a353a7fec64a3912aad38f6214

**Comment by He-Ro** [comment]
This could be a duplicate of #5782.

**Comment by janvlug** [comment]
Indeed, this is probably a duplicate of #5782.
