### ISSUE TITLE
After leaving a group I can still change disappearing messages setting

### ISSUE THREAD

**Issue by pprucia** [WhisperSystems/Signal-Android#6007]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I am in a group chat with someone and when I leave the group I am still able to change disappearing messages setting.

### Steps to reproduce
- become a part of a group chat
- leave a group
- choose disappearing messages from menu
- change a setting

**Actual result:** Group members are sending messages with new setting.
**Expected result:** Disappearing messages settings can be changed only be existing members of a group chat.

### Device info

**Device:** Multiple
**Android version:** 4.3+
**Signal version:** 3.25.4

**Comment by cascheberg** [comment]
I have implemented the UI fix in #5582.

**Comment by moxie0** [comment]
in 3.26.0
