### ISSUE TITLE
Remove Contact Pic Preceding Messages From Within Individual Conversations

### ISSUE THREAD

**Issue by lokesh-krishna** [WhisperSystems/Signal-Android#6008]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature Request
Could it be possible to remove the contact pic preceding every message (chat bubble) in a conversation in order to reduce the clutter and also make things consistent with the iOS and Desktop versions?

### Detailed Description
While the presence of contact pics before messages is helpful in group conversations (but still overwhelming when multiple messages are sent by the same person in succession as mentioned in #964), they are extremely redundant and make the screen more busy in one-to-one conversations. 
The colour of the chat bubbles is already an excellent method of distinguishing between messages. 

While doing something along the lines of other messaging apps (QKSMS, Hangouts, Facebook Messenger or Google Messenger) is what #964 sought by requesting that successive messages from the same contact be bundled, with the contact pic appearing only once for one message bundle, I am suggesting going the WhatsApp route and doing away with contact pics entirely, at least in individual conversation where they add very little, especially in excess.

Doing so would have the added benefit of making the Android app consistent with the iOS and Desktop apps where the contact pic doesn't appear within conversations. The desktop app instead displays the contact pic in the action bar which could be one alternate location for displaying the contact pic. 

Also, hopefully there should be no database issues in implementing this change like was mentioned in that other issue and that might expedite its implementation as it would be a purely UI move?

### Screenshots

Here are the iOS and desktop versions respectively:
![screen322x572](https://cloud.githubusercontent.com/assets/20235646/21637917/14bb552c-d28f-11e6-9b95-c63cf08ccbca.jpeg)

![unnamed](https://cloud.githubusercontent.com/assets/20235646/21637932/24d34e06-d28f-11e6-805f-8478b33e4dbd.jpg)

Here is how WhatsApp handles things presently:

![unnamed](https://cloud.githubusercontent.com/assets/20235646/21638018/7f8a93e0-d28f-11e6-85a3-9372da8534cb.png)

The contact pic is relegated to the action bar and messages bubbles only carry the name of the contact. Of course, even the name isn't present in case of individual conversations but I couldn't get a screenshot of that on the Play Store.

**Comment by Lokesh-Krishna** [comment]
@mateoeh I hope I don't sound entitled in suggesting that you take a look at this issue. Loving all the UI improvements you've made and just wanted to let you know of this issue in case you could do something about it.

**Comment by dcherian** [comment]
Fixed by 0cb1ff4290003ac2  ?

**Comment by FeuRenard** [comment]
Yes, this issue should get closed.
