### ISSUE TITLE
Feature Request: Add contact management options into Signal itself

### ISSUE THREAD

**Issue by Enekk** [WhisperSystems/Signal-Android#6015]
Per my 'mis-bugreport'  #6014 please add some form of contact management to Signal itself.
It seems unlikely that any reasonable user would figure out the method mentioned in #6014 for removing contacts or even just resyncing them with the Android address book.
Even if they were motivated enough to find this method, the process even warns the user that their data will be lost when this is not the case.

**Comment by moxie0** [comment]
Not sure what you mean. If you remove a contact from Android, it should be removed from Signal. If it isn't, that's a bug. Give us steps to reproduce and we'll look at it.  Thanks!

**Comment by Enekk** [comment]
@moxie0: In the bug report I linked, I did put that in as a bug, but my ticket was closed with a pretty convoluted way of 'resyncing' contacts.  Maybe we need to reopen #6015?
