### ISSUE TITLE
Link containing "$" get broken / cut after the $ sign.

### ISSUE THREAD

**Issue by Transisto** [WhisperSystems/Signal-Android#6019]
`Example link : https://www.investing.com/news/economic-indicators/china-december-forex-reserves-fall-less-than-expected-to-$3.011-trillion-451716`

**Comment by nikwen** [comment]
Screenshot:

![bildschirmfoto von 2017-01-09 19-59-26](https://cloud.githubusercontent.com/assets/3309657/21779041/2dcc989e-d6a6-11e6-8455-5ea0d1073435.png)

I'll see if I can fix this.

**Comment by nikwen** [comment]
So I investigated this problem and I do not think that this is an issue on Signal's side.

Signal uses the following code for finding links in messages:

```
<org.thoughtcrime.securesms.components.emoji.EmojiTextView
        ...
        android:autoLink="all"
        android:linksClickable="true" />
```

So it relies on TextView's [autoLink](https://developer.android.com/reference/android/widget/TextView.html#attr_android:autoLink) attribute, which then uses the [Linkify](https://developer.android.com/reference/android/text/util/Linkify.html) class.

Apparently, Linkify does not consider usage of the dollar sign `$` to be allowed in an URL.

That means that if this is an issue at all, it is one on Android's side. I don't think there is an easy way to work around this in Signal. And I don't think a complicated workaround would be worth the trouble. Usually, special characters should be escaped by the browser when copying or sharing a link.

This is how the example link looks after escaping: `https://www.investing.com/news/economic-indicators/china-december-forex-reserves-fall-less-than-expected-to-%243.011-trillion-451716`

Now, of course, we could escape characters when the user sends a message to a contact, but that would mean that we would have to modify the text the user typed in and I don't like that!

After all, I vote for closing this issue for not being Signal's fault.

(Heck, why does a website use a dollar sign in a URL at all?!)

**Comment by Transisto** [comment]
Thanks for investigating this, the $ is allowed so the url generator use the title of the text, which in this case is $3.011-trillion

**Comment by off-my-lawn** [comment]
I agree with closing this.

While Linkify does have functions for customizing matches and specifying different patterns for links, I can't see a way that the TextView exposes that.

As an aside, even if browsers accept it I'm not sure it's valid. The official definition for [URL](http://www.ietf.org/rfc/rfc1738.txt) and [URI](http://www.ietf.org/rfc/rfc3986.txt) disagree on the usage of $, with URL being more permissive even though conceptually the difference between them is that a URL actually needs to reference a concrete thing. As far as I can tell, Linkify must use the more recent URI specification which says that $ is a reserved symbol.

**Comment by idupree** [comment]
^ #6224 is more clearly one where a valid URL is poorly linkified.  It looks like `Linkify` itself has a mechanism to specify any regexp for matching links, but `autoLink` does not.  Possibly helpful post about using Linkify instead of autoLink: http://www.indelible.org/ink/android-linkify/
