### ISSUE TITLE
Build failes with dex error: "The number of method references in a .dex file cannot exceed 64K."

### ISSUE THREAD

**Issue by nikwen** [WhisperSystems/Signal-Android#6023]
When trying to build the current master, I'm getting the following error message:

```
Dex: The number of method references in a .dex file cannot exceed 64K.
Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html
```

I used `./gradlew clean assembleDebug` to build the project.

The full message can be found here: https://gist.github.com/nikwen/7bb8bcd5fede742c8d8b6a074b18628b

**Comment by nikwen** [comment]
I fixed this locally by adding [multidex support](https://developer.android.com/studio/build/multidex.html). Give me a few minutes to create a pull request.

**Comment by johanw666** [comment]
Just build with Android studio, apart from some changes it made when I incorrectly alowed it to upgrade the gradle plugin I've never had those errors.
