### ISSUE TITLE
Voice verification is required even when SMS verification code is available

### ISSUE THREAD

**Issue by fortran77** [WhisperSystems/Signal-Android#6029]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------
### Duplication

This issue overlaps with old issues #1399 and #1467, which were raised in a different context and remain unresolved.

### Bug description

During initial registration, if the SMS verification code arrives but remains undetected by the Signal app, voice verification is mandatory, even though the user could have manually entered the code.

### Steps to reproduce

1. Have some other app installed that handles SMS (in my case: Google Hangouts).
2. Install Signal app and register.
3. The SMS verification code will arrive but will remain undetected by Signal.
4. Signal will time out and require voice verification, even though the user could have manually entered the SMS code, had the app permitted this.

**Actual result:** As above.

**Expected result:**  Opportunity to manually enter the SMS code.

### Device info

**Device:** Nexus 6P
**Android version:** 7.1.1
**Signal version:** 3.25.4
**Cellphone provider:** Google Project Fi in US

**Device:** Nexus 6
**Android version:** 6.0.1
**Signal version:** 3.25.4
**Cellphone provider:** T-Mobile in US

**Comment by moxie0** [comment]
I can't reproduce this. If it's reproducible for you, can you include a debug log?

**Comment by fortran77** [comment]
Clarification please, which of the steps do you observe differently?

I have edited my original report to also include the phone service providers.

**Comment by fortran77** [comment]
OK, I understand now, and the failure of Signal to detect the SMS verification code was entirely user error on my part — I had denied it phone/SMS permissions (as I routinely do for every app, purely out of habit).

However, the real issue that I was wanting to report was that should the SMS not be seen by the app, the option to enter it manually would be greatly useful.

**Comment by moxie0** [comment]
Thanks for the update! We've found that if we include an option for people to enter it in manually, they'll do that on a secondary device thinking it will pair a sibling rather than clobbering the primary.

**Comment by niffrig** [comment]
I have a counter-anecdote @moxie0.  I am a Fi user that used to use Hangouts for "messages" before switching to Signal.  This is different from using Hangouts as the default SMS app.  Within Hangouts there is a setting for Google Voice/Fi users that intercepts the SMS message on the server and delivers it as a Hangouts message.  In that case you get a "text" and Signal spins making you wait for the SMS wait timeout within the Signal app before allowing you to move on to voice verification.  I'm not sure how but Allo was able to automatically verify under these circumstances.  Voice verification is a pretty painful workflow.  I had a few friends that balked at onboarding Signal because of the same issue.   It's clearly not without workaround but it could deter less savvy users as a first impression.

**Comment by fortran77** [comment]
I'll add for historical accuracy that the original situation did not entirely arise out of user error on my part.

On the Nexus 6 with T-Mobile service in US, I did cause the problem by denying phone/SMS permissions to the Signal app.

On the Nexus 6P with Google project Fi service in US, the problem arose without my denying phone/SMS permissions to the Signal app. Quite likely it's the same problem reported by user niffrig.

**Comment by gbenson** [comment]
I have a similar issue.  There's no signal where I live, so I have an app (Three inTouch) that retrieves SMS over wifi from some server my network provider runs.  When I try and register I see the message arrive in that app, but Signal doesn't spot it (and likely couldn't be made to) so I'd need to manually enter it.

**Comment by vvug** [comment]
Well, manually entering the SMS code on a new device should probably register that as a secondary device, as the users expects, according to @moxie0's comment. Then, from the "linked devices" option, the user should be able to remove the previous device, it that was lost or stolen.

**Comment by fortran77** [comment]
I have a third example of the SMS code arriving and not being detected by Signal. This happened on an HTC One phone running Android 5.1 that has a T-Mobile SIM, in the US. I'm using this phone as a secondary device for holding communications apps that require a mobile phone number. These include WhatsApp, KakaoTalk, and Signal. Quite likely one of the other two tried to intercept the incoming SMS message.

**Comment by LaughlinElkind** [comment]
Ran into this issue on a moto x4. I disabled hangouts and it still wasn't able to see the SMS.

**Comment by faceze** [comment]
Same issue on a huawei p9 lite.
