### ISSUE TITLE
Contacts are shown double when inviting friends

### ISSUE THREAD

**Issue by MaartenDeen** [WhisperSystems/Signal-Android#6034]
### Bug description
When I use the menu option to invite friends, some contacts are listed double. One instance is shown with a space between the international accessnumber and one is shown without the space. I do not have both number formats in my contact list.
e.g.: 
Random Friend
 +31 123456789 Mobile
Random Friend
 +31123456789 Mobile

### Device info
**Device:** Wiko Rainbow Jam
**Android version:** 5.1
**Signal version:** 3.26.2

**Comment by riyapenn** [comment]
Is this also a WhatsApp contact?  If you remove the WhatsApp account, does this clear up?  
(Opening WhatsApp again after will then relist this contact as a WA contact)

Go to Android Settings
Choose Accounts
Choose WhatsApp
Tap on the Menu
Choose Remove Account
Open Signal

**Comment by MaartenDeen** [comment]
The instructions are not clear. I problably have to select whatsapp again in the whatsapp account. If I do Accounts-> Whatsapp, then the menu only says "synchronize now". But if I select whatsapp in that screen (not in the menu) I have the option "synchronize now" and "remove account".
But I'm a little hesitant to use remove account there because it also tells me all messaged will be removed.
I am not willing to do that.

This is about multiple contacts, not just one. The only correlation there seems to be is that all double accounts are also whatsapp accounts. This is not a causal correlation though: not all whatsapp accounts are listed double.

If this is about getting contacts from different places where one lists a phonenumber as +31 123456798 and the other +31123456789 then the fix is easy: remove spaces from phone numbers before comapring them.

**Comment by jkdf2** [comment]
I can confirm this on a Nexus 6P running Android 6.0.1

**Comment by redstwice** [comment]
Same problem on google pixel android 7.1.1.

**Comment by FeuRenard** [comment]
Please check, whether this issue is fixed for you by dc18f73 / #6475 (in 4.6.0).

**Comment by jkdf2** [comment]
@FeuRenard Did not cherry pick that specific commit but I FF'd my branch to `4.6.0` and duplicates are now gone. I have a before & after screenshot that I would prefer not to share as I would have to do excessive cropping but it's absolutely fixed.

**Comment by 2-4601** [comment]
Reported as fixed, closing
