### ISSUE TITLE
LED notification bug

### ISSUE THREAD

**Issue by Warrost** [WhisperSystems/Signal-Android#6036]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
LED notification doesn't work if Signal doesn't use a sound for notifications.

### Steps to reproduce
Simply go to the "notifications" options, and then choose under "sound" "silent".
No LED notification will appear.
Undo the notifications settings and it will work again

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info
**Device:** Oneplus 3
**Android version:** 7.0
**Signal version:** 3.26.2

**Comment by piratenpanda** [comment]
Works fine here. Most likely a rom issue

**Comment by Warrost** [comment]
Seems like Google fixed it. Oneplus 3 still has 7.0

**Comment by turlir** [comment]
I dont repeat this behavior. Nexus 5, android 6.0. LED flag setup isolated sound and not override, see AbstractNotificationBuilder#setLed.

**Comment by Warrost** [comment]
Nope, it definetly doesn't work on Oxygen OS 4.0.1 (aka Android 7)
I can repeat this behavior, but I believe it is an OS issue, since whatsapp and similar apps are acting the same way.

**Comment by 2-4601** [comment]
Thanks for the multiple reports, closing as OS bug
