### ISSUE TITLE
"domain fronting" availability

### ISSUE THREAD

**Issue by A5DkjGQUZx** [WhisperSystems/Signal-Android#6037]
The "domain fronting" technique to circumvent censorship can be enabled for all users regardless of what mobile number they had used to register or will use to register.
Consider the case in which a user with a Canadian number already registered in Canada goes to UAE where Signal is blocked! He must use a VPN solution to access Signal servers.
Signal can try main servers if it needs to establish a connection, if failed then try again using domain fronting and this can be enabled for all users by default OR can be added as an option in the welcome screen (first time registration) and in the advanced setting page.

**Comment by moxie0** [comment]
Please do not intentionally delete the issue template.  This is not a forum for discussion, please see the community forums for that.  Thanks.
