### ISSUE TITLE
App crashed when I attempted to share a link to Signal

### ISSUE THREAD

**Issue by i7u** [WhisperSystems/Signal-Android#6044]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
App crashed when I attempted to share a link (URL) from the Firefox browser to Signal.
(but the log may prove I'm lying - it's too late, I'm doing other time critical things and my head is fuzzy)

### Steps to reproduce
This doesn't appear to be a reproducible bug. I share links to Signal all the time and it works fine. Having said that, please note that I did just upgrade to the latest version (v. 3.26.2), launched and used the app, and this crash occurred only a few minutes later.

**Actual result:** The app crashed.
**Expected result:** The app should have asked me who I want to share the link with.

### Device info
**Device:** Samsung Galaxy S5 Neo
**Android version:** 6.0.1
**Signal version:** 3.26.2

### Link to debug log
 https://gist.github.com/52ddc0b2340febedd38ec03f38e3dc50

**Comment by moxie0** [comment]
thanks edac0e85c76edb6c6632481611794cf13bb8456c
