### ISSUE TITLE
Build failed: wrong checksum for org.whispersystems:signal-service-android

### ISSUE THREAD

**Issue by motatuc** [WhisperSystems/Signal-Android#6047]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
./gradlew clean and ./gradlew build fail because of a wrong checksum for org.whispersystems:signal-service-android

### Steps to reproduce
- git pull to get the latest source
- run ./gradlew clean or ./gradlew build

**Actual result:** 
Checksum failed for org.whispersystems:signal-service-android:c7835376e426d4789444f1e8c02c3528fb57f148441d8f96d5d595244d7120a2
**Expected result:** ./gradlew finishes without an error

### Debug log

> Verifying
org.whispersystems:signal-service-android
FAILURE: Build failed with an exception.
What went wrong:
A problem occurred configuring root project 'Signal-Android'.
> Checksum failed for org.whispersystems:signal-service-android:c7835376e426d4789444f1e8c02c3528fb57f148441d8f96d5d595244d7120a2
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 6.377 secs

**Comment by fischli** [comment]
... and wrong checksum for signal-service-java
should be:
org.whispersystems:signal-service-android:0b5e607c1ffdbc90f8b1117c43ceaba62e3e19c01c8d29b3e1bf57cffce07f2b
org.whispersystems:signal-service-java:9738c26c17069a2f1eff47a46da5df62efa875bd66321933bed78f2584b7cc70

**Comment by 2-4601** [comment]
9779604932b5c11b361022624b105de70da9ceef
