### ISSUE TITLE
Signal keeps restarting itself since 3.26 on Xperia Z3 stock

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/Signal-Android#6058]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Posting this for a friend
Signal often restarts itself without giving any time of crash message. **Started after updating to 3.26+**

**Actual result:** Signal restarts itself at random. The app even crashed (showed a crash message) once while not running
**Expected result:** The app should preferably not restart every 10 minutes

### Device info
Device  : Sony D6603 (D6603)
Android : 6.0.1 (2769308465, 23.5.A.1.291)
Memory  : 72M (12.66% free, 192M max)
Memclass: 192
OS Host : BuildHost
App     : Signal 3.27.0

### Link to debug log
https://gist.github.com/anonymous/a739741d12f599512cb1e7e3496bb64b

**Comment by 2-4601** [comment]
Cause seems to be same as in #6057
Closing as dupe
