### ISSUE TITLE
Frequent crash on viewing new message from conversation thread

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-Android#6068]
I have:
- [X] searched open and closed issues for duplicates, but can not tell if these are duplicates: https://github.com/WhisperSystems/Signal-Android/issues/6057, https://github.com/WhisperSystems/Signal-Android/issues/6043 (2nd crash)
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Crashes frequently when viewing new text from conversation view 

### Steps to reproduce
- Receive message
- go to conversation thread
- view new message

**Actual result:** crashes, but still marks message as read.  Opening Signal after this and viewing the message does not cause a crash again.  Occurs nearly every 4th message according to user
**Expected result:** does not crash

### Screenshots
N/A

### Device info

**Device:** Motorola Droid Turbo 2
**Android version:** 6.0.1
**Signal version:** 3.26.2

### Link to debug log
https://gist.github.com/0f1a6eb6821bfe203622d9212a8361fc and
https://gist.github.com/c726a2c82f924ec96f3276a92e259c6f

**Comment by 2-4601** [comment]
Nooooo! Not another Motorola!
You're right, this is the same as https://github.com/WhisperSystems/Signal-Android/issues/6043#issuecomment-272277308
