### ISSUE TITLE
Unread notification badges do not work on Huawei EMUI

### ISSUE THREAD

**Issue by thenktor** [WhisperSystems/Signal-Android#6069]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I've installed Signal on a Honor 8 (made by Huawei) with EMUI 4.1 (Android 6.0). I've noticed that Signal receives notifications on new messages and they are also listed in the notification area, but the unread notifications badge on the app icon on the home screen is not shown.
In Signal support articles there is mentioned, that badge icons are supported for some launchers, see [https://support.whispersystems.org/hc/en-us/articles/215766077-How-can-I-see-my-unread-badge-count-What-launcher-should-I-use-](url)
So far I could not find out if this is a Signal or EMUI problem, but Threema and Conversations show the notification badges.

### Device info

**Device:** Honor 8
**Android version:** 6.0
**Signal version:** 3.26.2

**Comment by riyapenn** [comment]
Sounds related, but unsure: Another user is reporting the same issue on with badge notifications not showing for Signal on a different device. 

Device: LG V20 with Nova launcher
Android: rooted stock 7.0 (Build NRD90M, Software H91810d)

This user's work around was use nova launcher with the app notifyer to create a widget icon that displays the badge notification

**Comment by moxie0** [comment]
in 3.28.0
