### ISSUE TITLE
[Wishlist] Media Gallery

### ISSUE THREAD

**Issue by MartinX3** [WhisperSystems/Signal-Android#6074]
I want a media gallery, like in whatsapp.
There you can see every video/picture/gif you shared with your contact.

**Comment by FeuRenard** [comment]
In a conversation we already have a menu entry "all images" that leads us to a gallery of all images and GIFs. What you actually want is that videos are shown in this gallery, too, right?

**Comment by MartinX3** [comment]
Not only the videos and gifs.
I also want to slide between the pictures.
If i want to look at 2 pictures, every time i need to go back to the whole gallery, instead of sliding the image to the right or left.

**Comment by FeuRenard** [comment]
That's tracked in #2355.

**Comment by MartinX3** [comment]
Thank you!
I searched through the issues with the wrong parameters. xD
