### ISSUE TITLE
Update libphonenumber to >=8.2.0 (Cannot send SMS to my mobile provider)

### ISSUE THREAD

**Issue by kpuljek** [WhisperSystems/Signal-Android#6077]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
My friend made me aware of this as I'm never checking my account status via SMS, but it doesn't work for me neither. To check our account status, we have to send an SMS message to 13977, but Signal fails to deliver it. I tried sending it through the native Oneplus SMS app and it goes through just fine, with an immediate response. I can send an SMS to other people, though, so it has something to do with that number. (Signal adds +385 to it for Croatia, maybe that's it?)

### Steps to reproduce
- send an SMS to my provider through Signal 

**Actual result:** it doesn't go through, "Failed to send", "Some issues need your attention."
**Expected result:** Message should go through and I should get a response. 

### Device info
**Device:** OnePlus3T
**Android version:** 7.0
**Signal version:** 3.27.1

### Link to debug log
https://gist.github.com/anonymous/f656572561ea3a91d0f4bbdeb98e587b

**Comment by riyapenn** [comment]
On some phones there is a setting to enable sending messages to Short codes or short numbers.
You will need to allow sending "Premium SMS".
Go to Settings > Apps > Signal > scroll to the permissions section > tap on the down arrow for the section "Send premium SMS" and choose 'Ask' or 'Always allow'

**Comment by kpuljek** [comment]
Once I saw the Premium SMS setting in my App permission menu, I was sure that was it. But Signal wasn't on that list. I see all the other applications that have SMS capabilities there (Google Messenger, OnePlus Messenger and Facebook Messenger), but not Signal. When I first sent my short numbered SMS, they specifically asked for permission to send, Signal doesn't, it just fails. (I didn't put two and two together that this is a special permission, I figured they were asking general SMS privileges since I just switched to them)

Under Apps > Signal > Permissions there's no mention of Premium SMS, only if I go through general app permissions as stated above.

**Comment by kpuljek** [comment]
Checked with my friend, he has Signal listed under Premium SMS, but it already was on Always Allow. He also had to go through general settings, there's no Premium SMS under Signal > permissions

**Comment by kpuljek** [comment]
Can anyone with a better understanding of code check if this https://github.com/googlei18n/libphonenumber/blob/master/resources/ShortNumberMetadata.xml#L4982 allows for 13977 as a shortcode number in Croatia?

**Comment by nribeka** [comment]
@kpuljek 13977 doesn't match that regular expression. I think that regular expression will allow the following numbers only:
112
118
116000
116006
116117
116111
116123
1987
192
193
194
195
93
94

I hope I don't miss any number.

**Comment by kpuljek** [comment]
Thats how it looked to me, but I'm a noob when it comes to regex. Thanks!  And if it is so, then that's the issue here. My provider Bonbon uses 13977 to check account balance and status.

**Comment by nribeka** [comment]
I think you need to create into libphonenumber then since this seems to be related to how libphonenumber parse your number and then signal need to up the dependency for the libphonenumber.

**Comment by kpuljek** [comment]
The libphonenumber issue was fixed and closed! Will it be automatically included in the next version of Signal?

**Comment by 2-4601** [comment]
No, it has to be manually updated to libsignal-service and here. I added that to the subject.

**Comment by Nazta** [comment]
I almost have to ask why you limit shortcodes by country like this in the first place?

The reference for norway for instance, doesn't exist anymore. So no one checked it in ages. Therefore signal  now refuses to send messages to my bank(default app does, and signal did it a few weeks ago). Because someone decided for me that my country can only have 3, 4 and 6 digit shortcodes, but not 5 all of a sudden. Even though the online resources say 3-5(3 being emergency).

**Comment by kpuljek** [comment]
Thanks for the quick response, but I would hardly call this a feature. Maybe it's just an internal thing I don't know about, but feature sounds a lot less important than bug.

**Comment by Nazta** [comment]
Don't suppose it will be updated it again any time soon, so it fixes it for my country as well(currently unable to send, even if saved as a contact)?
