### ISSUE TITLE
[Wishlist] Groupselect / Multiselect resent messages

### ISSUE THREAD

**Issue by MartinX3** [WhisperSystems/Signal-Android#6087]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

I was in a room without internet, i sent many messages (pictures) to another contact.
Of course, textsecure/signal told me, that the messages wasn't sent.
After that i was in the need to resent every message manual.

The feature I'm missing is the possibility to groupselect/multiselect every message, which couldn't be sent and to resent it (dependent on the sent time).

At the moment, it is only possible to select one message, click on the options and click on resent.
If I select two or more entry's, this option is gone.

**Comment by FeuRenard** [comment]
It would be even better, if the user won't be forced to mark all unsent messages. There could be a button named "Resend all failed". But I have no idea where to place it.

> If I select two or more entry's, this option is gone.

This option is called "message details". It only makes sense for one message.

**Comment by Trolldemorted** [comment]
It would be even better if we resend messages w/o user interaction. I can think of no reason why user action is required when a network failure occurs, at least not for the first few thousand tries.

**Comment by MartinX3** [comment]
> It would be even better, if the user won't be forced to mark all unsent messages. There could be a button named "Resend all failed". But I have no idea where to place it.

A kind of popup button at the downside of the screen with a button, which would disappear after clicking would be nice.
Or swiping.

Click for okay and swipe for cancel.
And it would reappear after you reopen the app?
__
> This option is called "message details". It only makes sense for one message.

Yes, there a "i" in a cylce, which directs me to the message details, and if the message couldn't be sent, i can click on the text "message details".

But there is also a option called "Neu senden" in german.
I'm not sure how it is named exactly, but i used this button, instead of going into the message details.

__

Yes, it would be even better if we resend messages w/o user interaction.

**Comment by FeuRenard** [comment]
That's right. And we already have an issue for that, I think.

**Comment by MartinX3** [comment]
There are similiar open issues, if I search for "resent", but I didn't found an issue, which focues my wish.

**Comment by FeuRenard** [comment]
Maybe #2384?

**Comment by MartinX3** [comment]
>  fungs commented on 26 Aug 2015 
After the last updates, this works much better now. I've not had a single undelivered message in the last couple of months. Others, please report so we can close this issue ASAP.

Thats the conclusion.

They arn't realy working on it

**Comment by 2-4601** [comment]
#2384 is good for this

**Comment by donnm** [comment]
I have this problem all the time too, often when using an unreliable 3g router, or in areas with bad cellular service. Auto-resend would be a fantastic solution, like how WhatsApp works!

**Comment by nrizzio** [comment]
@donnm Please don't bump issues.
