### ISSUE TITLE
Call drops, then Signal cannot re-initiate the call from either party

### ISSUE THREAD

**Issue by lukehutch** [WhisperSystems/Signal-Android#6090]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
So far in both of the last voice calls I have placed in Signal, the call started getting choppy and breaking up (after talking for a few minutes), then eventually went dead. When trying to re-initiate the call from either end, the Signal dialer shows up as a blank screen, with no hang up button on the bottom. Killing the app and trying to re-launch and re-dial doesn't fix the problem. Calling on WhatsApp immediately after worked fine, so it was not a data signal problem.

Interestingly, the other party could not re-initiate the call either. (They were also on Android, I think, but I'm not sure.)

### Steps to reproduce
- Dial a call
- Talk for a few minutes until the call breaks up and then dies
- Try calling back

**Actual result:** As described above
**Expected result:** Calls should not drop when there is a good Wifi/cell signal, and even if the call drops, you should be able to call back immediately.

### Screenshots
(Didn't take a screenshot, but I can add one if it happens again)

### Device info

**Device:** Google Pixel XL
**Android version:** 7.1.1
**Signal version:** 3.27.1

### Link to debug log

https://gist.github.com/anonymous/d0d7e313551832c07b271816cc3ca3f6

**Comment by ladurera** [comment]
Similar to #5660 
Having the same issue here.. (see my post in there)
My debug log
https://gist.github.com/anonymous/36c914a1cebc5a0ccdfbbf645ba98693

**Comment by 2-4601** [comment]
Yeah, probably dupe or very related to the following issues #4186, #4835, #5132, #5660.

**Comment by lukehutch** [comment]
This does look like #5660, closing.
