### ISSUE TITLE
Send e164 formatted phone numbers when syncing contact details and blocked lists

### ISSUE THREAD

**Issue by liliakai** [WhisperSystems/Signal-Android#6093]
### Bug description
Contact info and blocked lists sometimes fail to sync correctly on Desktop due to non-e164 phone number formats. Repro steps below demonstrate this for contact color syncing, though blocked number sync messages are similarly affected (see screenshots from Chrome's debugger).

### Steps to reproduce
- Edit a contact number so it includes punctuation, such as parentheses, spaces, or dashes.
- Refresh the contact info in Signal (see that the punctuated number is rendered in the conversation header).
- Change the contact's color in signal

**Actual result:** Signal Desktop becomes [confused](https://github.com/WhisperSystems/Signal-Desktop/issues/903) and fails to save the change in contact info or blocked state.

**Expected result:** Signal Desktop correctly updates the conversation color.

### Screenshots
<img width="229" alt="screen shot 2017-01-24 at 3 43 13 pm" src="https://cloud.githubusercontent.com/assets/1039940/22272351/6c13b304-e24e-11e6-8a07-280467c05dd3.png">
<img width="176" alt="screen shot 2017-01-24 at 3 44 42 pm" src="https://cloud.githubusercontent.com/assets/1039940/22272352/6c173d3a-e24e-11e6-9152-60d9f328be42.png">

### Device info
**Device:** Galaxy Nexus
**Android version:** 4.3
**Signal version:** 3.27.1

### Link to debug log
https://gist.github.com/faf5c52bfecc2672a4b7fc9581e4e2c5

**Comment by Trolldemorted** [comment]
Am i correct if i assume this will happen only if i didn't save the contact in e164 in my android contacts?

**Comment by ruicruzpt** [comment]
Hapening also with Galaxy S6 and Android 6.x on last stable Android Signal version.

**Comment by Trolldemorted** [comment]
Shouldn't every contact [be in e164](https://github.com/WhisperSystems/Signal-Android/pull/4306)?

**Comment by liliakai** [comment]
Every contact has a canonical address but the sync messages aren't being populated from that table (apparently).

**Comment by Trolldemorted** [comment]
Aaah, i think you are completely right.

e164 numbers are stored in `canonical_addresses`, but the numbers for the contact sync objects are fetched from the droid contact store.

Could you test #6094? Can't test it myself right now, haven't got a smartphone with Signal-Android as a master in reach.

**Comment by Trolldemorted** [comment]
85aa5c5 only fixed one half of this issue, the details are fixed by https://github.com/WhisperSystems/Signal-Android/pull/6094.
