### ISSUE TITLE
[Crash] Scrolling to the top in conversation with more then 500 messages

### ISSUE THREAD

**Issue by p4nci** [WhisperSystems/Signal-Android#6098]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Reproducible Signal crash when scrolling to the top in conversation with more then 500 messages.

### Steps to reproduce
- Open conversation with more then 500 messages
- Scroll to the top

**Actual result:** Signal craches
**Expected result:** Show button "SEE FULL CONVERSATION" (Signal loads only the latest 500 messages by defualt).

### Device info
**Device:** Nexus 5X + Nexus 5
**Android version:** 6.0.1 (CM 13.0)
**Signal version:** 3.28.0

**Device:** Moto 4G
**Android version:** 4.4.4 (CM 11)
**Signal version:** 3.28.0

### Link to debug log
see also https://github.com/WhisperSystems/Signal-Android/pull/4696#issuecomment-275066620
Signal v3.27.1 worked fine.

EDIT: updated Android Version for Nexus 5X

**Comment by johanw666** [comment]
I can confirm this also on Android 6.0.1 (Z3 compact with stock ROM). Debug log at https://gist.github.com/anonymous/9cc3e9b04ef37fe2236a86f14fae345d
