### ISSUE TITLE
Some sticky date headers show incorrect date

### ISSUE THREAD

**Issue by haffenloher** [WhisperSystems/Signal-Android#6101]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
For me the date headers are correctly placed, but some show an incorrect date. Here are some screen shots from a single convo:

First header:

<img src="https://cloud.githubusercontent.com/assets/264472/22314682/d16ba8c8-e362-11e6-8f1f-282f0cee3e82.png" height="600">

First & second header:

<img src="https://cloud.githubusercontent.com/assets/264472/22314686/d3992724-e362-11e6-96f1-45d9d3e97788.png" height="600">

Second & third header:

<img src="https://cloud.githubusercontent.com/assets/264472/22314688/d5312302-e362-11e6-9928-f9033ea4ede0.png" height="600">

Only the third header is correct. Fast-forwarding the emulator's clock to the next day simply changes all three headers to "Yesterday".

---

Playing around with the emulator's time zone produces one more header, leading to this:

<img src="https://cloud.githubusercontent.com/assets/264472/22314754/22452e04-e363-11e6-9d95-58f1a74dd707.png" height="480"> <img src="https://cloud.githubusercontent.com/assets/264472/22314757/23feb45e-e363-11e6-86c2-baf6599386bc.png" height="480"> <img src="https://cloud.githubusercontent.com/assets/264472/22314758/258f4e32-e363-11e6-9285-047a7d458001.png" height="480">

Headers 1, 3 and 4 are correct, but header 2 erroneously reads "Yesterday" instead of "Mon, Jan 23, 2017"

### Device info

**Device:** AVD
**Android version:** 7.1.1
**Signal version:** 3.28.0

### Link to debug log
https://gist.github.com/anonymous/fef900cd2c4b35293cd975b9636f6577

**Comment by moxie0** [comment]
How did you generate these screenshots? Keep in mind that the headers are generated by the message "receive" time rather than the "send" time.

**Comment by haffenloher** [comment]
Whoops, that was it, thanks. I'll close this issue.

Their positions are determined by the "send" time though, is that on purpose? That's why I got multiple headers with the same text.
