### ISSUE TITLE
Selecting a message with a link makes the link unclickable

### ISSUE THREAD

**Issue by rmueller83** [WhisperSystems/Signal-Android#6106]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Selecting a message with a web link makes it unclickable

### Steps to reproduce
- Have a message with a web link. The web link is underlined and clickable
- Long-press the message in order to select it
- Either copy the message to the clipboard, or click back to unselect it

**Actual result:** The web link is not underlined and not clickable any more
**Expected result:** The web link is underlined an clickable

### Device info

**Device:** Motorola Moto G
**Android version:** Lineage 7.1.1
**Signal version:** 3.28.1
Also happens in emulator.

**Comment by rmueller83** [comment]
Also, if I long-press the link to select the message, the link opens when removing the finger from the touchpad. So when I want to copy a link, I have to press on the message timestamp of the message box, being careful not to hit the link itself. It would be nice if a long-press would not open the link.

**Comment by FeuRenard** [comment]
I'm quite sure that this bug is caused by this change:
https://github.com/WhisperSystems/Signal-Android/commit/183f8742a7d034c951eca20e854b49cee5541d31#diff-14fea86262bd360896dbeabe0b2cd915L195

I cannot test this or open a PR at the moment, but anyone should try to move `setBodyText(messageRecord);` after `setInteractionState(messageRecord);` to fix this.

**Comment by motatuc** [comment]
Can confirm that the fix suggested by @FeuRenard works and solves the problem. Unfortunately I cannot do the PR either.

**Comment by FeuRenard** [comment]
I already opened one: #6108

**Comment by rmueller83** [comment]
Thanks @FeuRenard !
