### ISSUE TITLE
Camera buttons misaligned

### ISSUE THREAD

**Issue by rmueller83** [WhisperSystems/Signal-Android#6107]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The camera buttons are too small and misaligned

### Steps to reproduce
- Open a conversation
- Click the attach symbol
- Click the camera symbol

### Screenshots

Signal camera screen:
![signal-cam](https://cloud.githubusercontent.com/assets/2698076/22351761/be3e8f2e-e419-11e6-8b77-635e2b1c01b4.jpg)

Standard camera app:
![standard-cam](https://cloud.githubusercontent.com/assets/2698076/22351767/c5358c88-e419-11e6-8ef6-c0ac34afd718.jpg)

### Device info

**Device:** Motorola Moto G (falcon)
**Android version:** 7.1.1 (Lineage OS 14.1)
**Signal version:** 3.28.1

I just updated my phone to Lineage OS , so I am not sure if this is a bug in Signal or in Lineage. With the previous CyanogenMod 14.1 I did not have this bug, but there I also had an older Signal version. The standard camera app and WhatsApp work correctly.

**Comment by nrizzio** [comment]
@rmueller83 Please [send a debug log](https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports#capture-a-debug-log), which will help us figure out what's going on.

IIRC, that camera button triggers the system camera, so there's a good chance that it's a Lineage bug.

**Comment by rmueller83** [comment]
https://gist.github.com/anonymous/1923d2b0f1eb77fcc9207596029502f1

**Comment by moxie0** [comment]
That activity is your system's, not Signal's. The only camera activity that Signal controls is the one where you press the "quick camera" option in the compose field. This looks like a ROM bug.
