### ISSUE TITLE
Strange splitting of messages when sent over SMS to non-Signal receiver

### ISSUE THREAD

**Issue by jonhoo** [WhisperSystems/Signal-Android#6110]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Long messages are being split weirdly when sent from an Android Signal client to a non-Signal iPhone client.

### Steps to reproduce
- Send a single, long SMS from Android Signal client to a non-Signal iPhone client

**Actual result:** Message is split up in non-intuitive places, and sent as multiple separate messages.
**Expected result:** Message should be received as a single, multi-part SMS message.

### Screenshots
![Android Signal sender](https://cloud.githubusercontent.com/assets/176295/22359873/0a7123f8-e419-11e6-8bad-ded61156d5f3.png)
![iOS non-Signal receiver](https://cloud.githubusercontent.com/assets/176295/22359872/0a702d72-e419-11e6-9532-79694a80ee7d.png)

### Device info

**Device:** Nexus 5X (3532671, N4F26I)
**Android version:** 7.1.1
**Signal version:** 3.27.1

### Link to debug log
Unfortunately I did not think to get a debug log dump right after the messages were sent. If I find another recipient that this error occurs with I will post the log then.

**Comment by nribeka** [comment]
If you sent long text message to the same receiver does it coming out as multiple text message too?

**Comment by jonhoo** [comment]
@nribeka I'm not sure I understand the question?

**Comment by nribeka** [comment]
Sorry it wasn't come out very clear. I mean if you send out long text message using original sms app that comes with the phone or hangout, does it come splitted too on the other side? I'm wondering if it's because the recipient's phone (or app) can't merge the text messages or is it a bug on Signal side.

**Comment by jonhoo** [comment]
I'll try that too next chance I get. Though I suspect this would be very well known if multi-part Android to iPhone SMS messages were never merged.

**Comment by moxie0** [comment]
@jonhoo It's a carrier rather than a platform thing. CDMA providers, for instance, don't support multipart (the messages just fragment)

**Comment by jonhoo** [comment]
@moxie0 Ah, I see. That's a shame. Closing as this is not Signal's fault.

**Comment by jonhoo** [comment]
Interestingly, the messages that I got from them were merged correctly...
