### ISSUE TITLE
SMS with malformed headers crashes Signal on startup

### ISSUE THREAD

**Issue by CaiusCosades** [WhisperSystems/Signal-Android#6115]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
My Signal began to crash on startup without a reason! I read the support page and airplane mode did not help. Sent another SMS to my phone for the notification - it showed that I received several anonymous multimedia messages. Pressed "Mark all as read" - that didn't help. 
Now I have to use WhatsApp and default SMS client. Am I going to lose all my messages now? Please fix ASAP.

### Steps to reproduce
- receive an anonymous multimedia message

**Actual result:** Signal starts to crash on startup
**Expected result:** Signal should not crash on startup

### Screenshots
![tmp_20464-screenshot_2017-01-27-10-31-212056042925](https://cloud.githubusercontent.com/assets/25378723/22358098/e83cdd1a-e47f-11e6-991a-e5eb53f01d80.png)
[VIDEO - crash on startup](https://fat.gfycat.com/AmazingMeagerAssassinbug.webm)

### Device info
**Device:** Xperia Z1 Compact
**Android version:** 5.1.1 (CyanogenMod 12.1)
**Signal version:** 3.27.1

### Link to debug log
[logreport.txt](https://github.com/WhisperSystems/Signal-Android/files/736850/logreport.txt)
[logreport_airplane.txt](https://github.com/WhisperSystems/Signal-Android/files/736857/logreport_airplane.txt) - this is with aeroplane mode on

**Comment by Trolldemorted** [comment]
@moxie0, can we just wrap the usage of the [headers](https://github.com/WhisperSystems/Signal-Android/blob/master/src/org/thoughtcrime/securesms/database/MmsDatabase.java#L804) with `if != null`, or does signal rely on the missing fields being filled in the db?
