### ISSUE TITLE
Gifs not loading/unable to view or search gifs

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-Android#6132]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports but unsure if this is a Signal issue vs phone settings/permissions

----------------------------------------

### Bug description
unable to view or search for any gifs using the built in Giphy feature. No matter the input, the message "nothing found" is displayed for both the gif and sticker search.

### Steps to reproduce
- Confirm permissions are enabled for Signal (waiting to confirm if user has 3rd party app limiting connection)
- Open Signal
- Select GIF attachment option

**Actual result:** No images available
**Expected result:** See images

### Screenshots

<img width="220" alt="screen shot 2017-01-31 at 11 32 03 am" src="https://cloud.githubusercontent.com/assets/4898366/22481133/f605d0ce-e7a8-11e6-9aaf-6aa6a79b7726.png">
<img width="219" alt="screen shot 2017-01-31 at 11 31 57 am" src="https://cloud.githubusercontent.com/assets/4898366/22481137/f7c1f8f2-e7a8-11e6-91e4-a20340c3f611.png">

### Device info

**Device:** Galaxy Note II
**Android version:** 4.4.2 **Rooted**
**Signal version:** 3.27.1

### Link to debug log

https://gist.github.com/2aa2aa5371f4dc044cb49a4b9f1fa765

'I/ProxyService( 7191): Request 24 CONNECT api.giphy.com:443 HTTP/1.1
I/adblock.( 7191): false: http://api.giphy.com:443api.giphy.com:443
I/Error   ( 7191): 500 Server Error: java.lang.IllegalArgumentException: http://api.giphy.com:443api.giphy.com:443
I/ProxyService( 7191): unexpected error
W/GiphyProxySelector( 5018): java.io.IOException: Unexpected response code for CONNECT: 500`

**EDIT:** 
log with third party app "AdBlock-free" disabled: 
https://gist.github.com/anonymous/beaf76957a3c59606e1a028d06724816

**Comment by riyapenn** [comment]
2nd user: specifically, gifs will not display when on mobile data
https://gist.github.com/3618fb7a1512b27858a60ee4044f87fc
<img width="241" alt="screen shot 2017-02-16 at 6 51 37 pm" src="https://cloud.githubusercontent.com/assets/4898366/23050751/0e84b8b8-f479-11e6-86e9-aaaaf31b5fe2.png">

**Comment by hroyer** [comment]
I experience the same thing, even with the latest app version.

**Device:** Nexus 5X
**Android v.:** 7.1.2
**Signal v.:** 3.30.4

**Comment by riyapenn** [comment]
I believe this is the result of phone settings / [Google's own VPN limiting the connection](https://support.google.com/nexus/answer/6327199?hl=en).  

@hroyer Can you check your phone settings?
Settings > More (Under Wireless & Networks) > VPN > Wi-Fi Assistant > disable this.

**Comment by hroyer** [comment]
It also happens when I'm on a data connection (LTE), and the Wi-Fi Assistant is disabled on my phone.

**Comment by riyapenn** [comment]
If you've just changed the Wi-Fi Assistant settings, can you restart your phone and see if this continues?  Who is your mobile provider? Please also provide a debug log.

**Comment by hroyer** [comment]
I haven't changed anything related to the Wi-Fi Assistant. I was always disabled.
Here's the debug log: [https://gist.github.com/031f967f9e8f92e8b9d9e8d9bb96827a](https://gist.github.com/031f967f9e8f92e8b9d9e8d9bb96827a)

It works on my home network, but doesn't work on LTE or my work network.
If you need more info, I'll be pleased to provide more! Thanks! :)

**Comment by hroyer** [comment]
I just received an update (4.2.3) and it now works.
I also disabled permissions and re-enabled all of them. Don't know if it's one of these two actions that fixed the issue.

**Comment by blairg23** [comment]
Turning on the WiFi fixed this issue for me.
