### ISSUE TITLE
Screen goes to sleep during video call

### ISSUE THREAD

**Issue by haffenloher** [WhisperSystems/Signal-Android#6141]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Video calls don't prevent the phone from turning off the screen.

### Steps to reproduce

In an API 25 emulator:
- in the emulator's battery settings, set "Charger connection" to "none" and "Battery status" to "Discharging"
- in Android's Display settings, set a short display timeout (e.g. 15 seconds)
- start a video call

**Actual result:** Screen goes dark after a few seconds
**Expected result:** screen should stay on till the bitter end

### Device info
**Device:** AVD
**Android version:** 7.1.1
**Signal version:** 3.29.1

### Link to debug log
https://gist.github.com/anonymous/df33413cafdcebee09e67630e6f7fb9f

**Comment by RiseT** [comment]
I can confirm this hehavior using a physical phone.
