### ISSUE TITLE
Terminating video call from notification doesn't close call UI

### ISSUE THREAD

**Issue by haffenloher** [WhisperSystems/Signal-Android#6143]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Steps to reproduce
- start a video call
- open Android notifications
- tap "End call"

**Actual result:** video freezes, call still says "connected" until I cancel the call again in Signal's UI
**Expected result:** call screen should close

### Alternative steps
- start a video call
- press home button
- open Android notifications
- tap "End call"
- open Signal from the app switcher / "Recents" view

### Device info

**Device:** AVD
**Android version:** 7.1.1 (also happened using a 4.2.2 physical device)
**Signal version:** 3.29.1

### Link to debug log
https://gist.github.com/anonymous/2c798b21261953f2191d23c9374a6005

**Comment by moxie0** [comment]
good catch
