### ISSUE TITLE
Cannot send SMS

### ISSUE THREAD

**Issue by Zeriuno** [WhisperSystems/Signal-Android#6146]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal is unable to send SMS.
System app still can, and Signal can send Signal Messages

### Steps to reproduce
- write a message to a not Signal contact
- SMS is not sent, nor does it raise an error notfication

**Actual result:** The message is not sent
**Expected result:** SMS is sent

### Screenshots

![unsent sms](https://cloud.githubusercontent.com/assets/1645004/22575219/71d529ae-e9b4-11e6-91f8-11ba7038df4d.png)

### Device info
**Device:** TCT ALCATEL ONE TOUCH 997D
**Android version:** 4.1.1
**Signal version:** 3.28.14

### Link to debug log

https://gist.github.com/b8fb9292cd86789935e79445917245df

**Comment by moxie0** [comment]
How did you capture this debug log? It's pretty much empty. Did SMS used to work, or has this always been a problem?  Looks like you might have two SIM cards, one of which doesn't have service, are you sure you've selected the correct one?

**Comment by Zeriuno** [comment]
@moxie0 

* That debug log was captures several hours after trying to send the SMS, through Signal's debug log feature. Since the dots were still dancing, I naively thought Signal was still trying to send the SMS, I guess it wasn't.
Here's another debug log, a minute or two after hitting "Send" for a SMS: https://gist.github.com/anonymous/b435b8edb422402dce628321ba726866
* Yes, SMS used to work. I have had Signal for over a year, and never experienced this.
* Yes, the phone has two SIM cards. I am quite sure the right one is functioning.

These are the circumstances in which this behaviour appeared:
* I was abroad (SIM card in roaming)
* One of the two SIM cards ceased working (it looks like a hardware problem related to the slot)
* #6127

**Comment by moxie0** [comment]
@Zeriuno There's nothing in this debug log either. I'd recommend capturing it immediately after hitting send.

My best guess is that with one of the SIM cards being broken, the system is not reporting to Signal that the phone has SMS service.  You might try enabling "WiFi Calling Compatibility Mode" under Signal Settings -> SMS and MMS.

**Comment by Zeriuno** [comment]
> You might try enabling "WiFi Calling Compatibility Mode" under Signal Settings -> SMS and MMS.

Yes, that fixes it.
@moxie0 Do you wish me to send you another log, captured as soon as possible after hitting send?
Sorry for the two empty ones.

As for the behaviour classification, I would still consider it a bug, since the SIM card selected by the system is the one working.

As usual, thank you.

**Comment by moxie0** [comment]
@Zeriuno Thanks, there's not really anything more we can do. We ask the system "is it possible to currently send an SMS" and it says "no."

**Comment by Zeriuno** [comment]
> Thanks, there's not really anything more we can do.
@moxie0 Perhaps notify that the message can't be delivered? As of now, the user is endlessly led to believe that Signal is still trying to send the SMS.

**Comment by moxie0** [comment]
@Zeriuno There's no way for us to know that. Signal *is* trying to send the message still, but the phone is essentially reporting that the device is in airplane mode, so Signal is waiting it out.
