### ISSUE TITLE
Cannot send Signal messages over Hospital (public?) WiFi probably firewall issue

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-Android#6147]
I have:
- [X] searched open and closed issues for duplicates, but I can not adequately search for the root cause of this issue :( I assume it is a firewall issue but **_just in case_** it is not I have posted here.
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Message sending fails when connected to this particular internet connection

### Steps to reproduce
- Connect to this particular wifi connection
- Send message

**Actual result:** message fails to send
**Expected result:** message sends

### Screenshots

<img width="493" alt="screen shot 2017-02-02 at 8 03 52 pm" src="https://cloud.githubusercontent.com/assets/4898366/22579170/c44b560e-e982-11e6-9c8c-a9e2749a07cb.png">

### Device info

**Device:** Moto G
**Android version:** 6.0.1
**Signal version:** 3.29.1

### Link to debug log

https://gist.github.com/anonymous/a7ba0dbea86cf5e13923d7d835602513

**Comment by moxie0** [comment]
Yep, looks like a firewall thing. The connection is being reset, presumably by a middlebox.

**Comment by dcherian** [comment]
Would more-general domain fronting fix this?
