### ISSUE TITLE
Provide option to stop Signal for Android (and Signal Desktop) from "breaking" new emoji into "constituent" pieces

### ISSUE THREAD

**Issue by jdkruzr** [WhisperSystems/Signal-Android#6151]
I'm on LineageOS for Nexus 6P -- latest build -- and I've found both Signal for Android and Signal Desktop do this despite my phone, my Mac, and my Windows 10 PC all having support for the newest emoji. Most irritating is that you can see the characters are un-split in notifications but when you go to the actual messaging window, they get broken into two -- for example, the "male information desk" character gets split into the female one and a "male gender" symbol. The "male person with laptop" get split into "man" and "computer." Can we fix this?

**Comment by moxie0** [comment]
@jdkruzr You can enable system emoji in the Signal-Android settings if you prefer. As soon as emoji-data [supports the 10.2 emoji](https://github.com/iamcal/emoji-data/issues/69), we will as well.
