### ISSUE TITLE
Cannot run Signal with microG

### ISSUE THREAD

**Issue by Poomex** [WhisperSystems/Signal-Android#6154]
I have just installed Resurrection Remix ROM (7.1.1) on my Xiaomi Redmi Note 3. I then installed all the microG elements (version 0.2.4) and the self-check utility shows all boxes checked (including signature spoofing). 
Signal installs fine and starts, but after giving it my telephone number and clicking "Register" this error is displayed:

> **Update Google Play services**
org.thoughtcrime.securesms.ApplicationContext won't run unless you update Google Play services

And when I click "Update" nothing happens.

**Comment by johanw666** [comment]
I can't find anywhere which version of play services microG reports to be available, but perhaps it's too low? In https://github.com/WhisperSystems/Signal-Android/commit/f310dd60479d746645d7473d7dacbea2a1af5c72 , which is in Signal 3.27, the required version of the play services was increased from 8.1.0 to 9.6.1.

**Comment by Poomex** [comment]
So is there some way to downgrade Signal? Maybe some older .apks?

**Comment by chrihu** [comment]
Update microG to the latest preview release (0.2.4-55).

**Comment by johanw666** [comment]
@Poomex : that's only a limited time solution, because the official Signal binaries expire in 90 days. You'd have to build from source and remove the expiration to prevent that, but risk incompatibility at some point in the future.

**Comment by Poomex** [comment]
@chrihu That worked, thanks!
