### ISSUE TITLE
Prevent webrtc and redphone from simultaneously connecting and sharing audio

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-Android#6156]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Accepting a redphone call while on a webrtc calls, connects both and enables audio for both calls simultaneously 

### Steps to reproduce
- place and connect a webrtc call
- receive a redphone call
- accept redphone call

**Actual result:** Audio is shared with both webrtc call and redphone call; video is still connected to webrtc call
**Expected result:** Only call displayed on Android screen has audio/video permission; either place other call on hold or display "busy" to caller when receiver is already connected to other call 

### Screenshots

N/A

### Device info

**Device:** Moto X
**Android version:** 5.1
**Signal version:** 3.29.1

### Link to debug log

https://gist.github.com/c86609a2156e55c814cb9a031b212bd9

**Comment by ZackTS** [comment]
Hm, could we introduce group calls this way?
