### ISSUE TITLE
Personally-identifiable information (PII) is being included in logcat logs

### ISSUE THREAD

**Issue by manastungare** [WhisperSystems/Signal-Android#6159]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
On inspecting my own device using `adb logcat`, I noticed that Signal is writing sensitive personally-identifiable information to logcat.

```
02-03 16:21:15.603 14609-16502/? W/Directory: Adding active token: +10005550000, REDACTED/+6A
```

Where `+1000555000` is the phone number of one of my contacts. There is one line per contact.

### Steps to reproduce
- Install Signal
- Sign in
- Connect Android device to desktop computer running the Android SDK
- Use `adb shell` to inspect logs.

### Impact

- If a device is rooted, any app running on the device can have access to read sensitive PII.
- If the user chooses to submit a bug report for any other unrelated app, even on a factory device, sensitive PII will be leaked.
- This PII may be uploaded to a phone manufacturer’s servers for crash report analysis, compromising the security of that user’s Signal contact list.

### How to mitigate

The offending `Log.i` should be removed entirely.

If that is not desirable, then some attempt must be made to write only a redacted or hashed version of the contacts' phone numbers.

**Comment by 2-4601** [comment]
This has come up before #4832, #5204, #5570

**Comment by moxie0** [comment]
We need this kind of logging in order to be able to effectively develop the app, particularly given the lack of analytics or integrated crash reporting.  The log is not visible to other apps (since 2012), is not included in system crash reports, and the information is redacted in Signal's integrated debug log submission.
