### ISSUE TITLE
Phone call is not working both sides

### ISSUE THREAD

**Issue by trmendes** [WhisperSystems/Signal-Android#6160]
I have a Samsung Galaxy S4 i9505 running the Cyanogenmod 13.1 and Signal Messenger version 3.28.4.

When I call someone using the phone feature from Signal Messenger I can listen the other person speaking but the person at the other side can't hear myself speaking. (running the call over a very good wifi connection)

Again:
**Device:** Samsung Galaxy S4 i9505
**Android version:** 6.0.1 (Cyanogenmod 13.1)
**Signal version:** 3.28.4 downloaded from Google Play Store

**Comment by 2-4601** [comment]
In the next version 3.29 (in beta now) calls will use webrtc. 3.28.4 is using older code which won't be fixed anymore. When 3.29 is released on the Play Store please test again and if you still experience this issue comment here with debug logs from both devices. Thanks!

**Comment by trmendes** [comment]
It's working now with the new system.

**Comment by trmendes** [comment]
It's working now with the new system.
