### ISSUE TITLE
Phone crashes on attempt to open video

### ISSUE THREAD

**Issue by FeuRenard** [WhisperSystems/Signal-Android#6162]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
My phone reboots when a video is opened repeatedly. This doesn't work with small videos (tested with <1MB) but works reproducibly with larger ones (tested with two 7-8 MB videos).

### Steps to reproduce
- open conversation with video
- tap on video
- tap back button
- tap on video

**Actual result:** MediaPreviewActivity is shown without the video for a moment. Then my phone reboots.
**Expected result:** Video is shown.

### Device info

**Device:** Sony Xperia U
**Android version:** 4.4.4 (CyanogenMod)
**Signal version:** 3.28.4

### Link to debug log
https://gist.github.com/FeuRenard/72126ca6dd8d10628e62993961c497c5

**Comment by moxie0** [comment]
Hmm, anything that causes your phone to reboot is an Android bug (or CM bug in this case). An app shouldn't really be able to do that even if it tried.
