### ISSUE TITLE
Timestamp incorrect on message from some time zones 

### ISSUE THREAD

**Issue by ryannathans** [WhisperSystems/Signal-Android#6163]
When a device in Brisbane, Australia sends messages to a device in Sydney, Australia the timestamp of the message immediately reads as "58 minutes ago" on the receiving device. Running signal version 3.29.1 on Sydney device

**Comment by ryannathans** [comment]
When a device in Perth, Australia sends a message to the same device in Sydney, the timestamp is correct. 

Is this likely a problem with Brisbane or Sydney device?

**Comment by ryannathans** [comment]
I believe Brisbane is the same time zone as Sydney except that Sydney is currently on day light saving time and Brisbane is not. This could be the problem

**Comment by 2-4601** [comment]
Perhaps the other user has manually adjusted the time on that device? See https://github.com/WhisperSystems/Signal-Android/issues/2439#issuecomment-112386748

**Comment by ryannathans** [comment]
@2-4601

Possible, I don't see how it would be fixed other than by maintaining an offset updated regularly with NTP. Will ask them how they set their time

**Comment by ryannathans** [comment]
When the user changed their time to automatic instead of manual, the timestamp was correct. Go ahead and either close this or think of a way to fix it 😉
