### ISSUE TITLE
Onboarding Screen should tell user how to add/recover existing account

### ISSUE THREAD

**Issue by rdnetto** [WhisperSystems/Signal-Android#6174]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When a user reinstalls Signal onto their phone after formatting it, going through the onboarding process creates a new account, instead of restoring the old one.

### Steps to reproduce
- install Signal on phone and setup account
- Link a second device (opt.)
- Format device (or just delete Signal files)
- Re-install Signal, and go through the onboarding screen

**Actual result:** A new account is created, which causes all contacts to get a warning about the magic number having changed. If the user does not realise this has happened and continues to use the linked device as well, repeated warnings may result.
**Expected result:** Either the original account should be restored, or the user warned that the old account will be lost.

This can also be reproduced by moving the SIM card from a old phone to a new one.

### Device info

**Device:** Motorola X Force (XT1580)
**Android version:** 6.0
**Signal version:** 3.28.4

**Comment by 2-4601** [comment]
> **Expected result:** Either the original account should be restored, or the user warned that the old account will be lost.

There's no way to restore the original account if you just formatted your device or uninstalled SIgnal thus obliterating your Signal account. Both operations happen outside Signal and it has no say in the process. Also Signal Desktop doesn't get any information if you format your device or uninstall Signal.

The server could probably at registration time inform the user if that number is already registered with Signal. But that might raise other issues.

**Comment by moxie0** [comment]
There's no real concept of a "new account" vs a "restored account."  It sounds like what you're saying is that you want the re-install to use the old identity key material, but that no longer exists if you deleted it.  It can't be stored on a server, because it has to be secret.  The only place it exists is your device, so if you delete it it's gone.

**Comment by rdnetto** [comment]
> It sounds like what you're saying is that you want the re-install to use the old identity key material, but that no longer exists if you deleted it.

This isn't the case if you have linked devices though (I had several) - I expected it to sync the key from one of them, or at least give me the option to do so, rather than deleting the account they were still using.

I think at the least, a warning that a new account will be created (and that users of existing accounts should import them another way) would be beneficial.
