### ISSUE TITLE
Text push messages takes ~2sek to get trough. Call takes ~10sek to get through

### ISSUE THREAD

**Issue by halb9** [WhisperSystems/Signal-Android#6176]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal Call takes a long time to initiate.
See the video for what I mean. 

### Steps to reproduce
Sending a text message from phone A to phone B. B receives it immediately. 
Right after that I start a call from phone A to phone B. 

**Actual result:** It takes about 10 seconds to go from sonar sound to actual ringing sound. 
**Expected result:** Take as less time as the text push message to initiate the actual call. 

### Video

http://www.xup.in/dl,15777916/out.mov/

### Device info

see logfiles for device info
I am on two different WiFi Networks. And it doesn't matter if the phones are on WiFi or mobile network. 

### Link to debug log

The logs are captured right after the call is terminated. 

Phone A: https://gist.github.com/a6abeeaa62677b82a24506fae09efb09
Phone B: https://gist.github.com/67d46bd2860644af127effd3c50ec3de

**Comment by moxie0** [comment]
Might be slightly faster in 3.29.2, but this is largely the result of the ICE handshake and webrtc's infinite wisdom to use DTLS. We could make the device "ring" sooner, but then if you answered immediately there'd be a delay before you could talk (and there might be problems that prevent the ICE handshake from completing at all).

**Comment by snaggen** [comment]
Is it possible for the calling phone to know the status of the connection, and display a more clear connection state on the callers screen? Like, "trying to establish connection" and silent during the ICE handshake and then "ringing" with the ringing sound.

**Comment by MatejKovacic** [comment]
I have the similar problem. Sometimes it takes about half a minute to start ringing.

Any plans to speed up signalling?
