### ISSUE TITLE
Wearable text reply

### ISSUE THREAD

**Issue by Tristan35** [WhisperSystems/Signal-Android#6178]
Hi !
I'm currently student, I use Silence  daily and I think it should be a great idea if Silence can send pre-programmed text message with my android smartwatch.
We could imagine a special menu in the settings parameters to add pre programmed text.

PS: Sorry for my bad english, it's not my native language. 

Thanks for reply, 
Tristan

**Comment by 2-4601** [comment]
Looks like you opened this in the wrong repository
