### ISSUE TITLE
Disable proximity sensor for video calls

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-Android#6179]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
On a video call, screen turns black (proximity sensor trigger) if phone/sensor is held very close to the face/hand/object

### Steps to reproduce
- Place Signal (audio) webrtc call
- Test proximity sensor, works as expected where screen turns off regardless of landscape or portrait mode
- Toggle video call 
- Test proximity sensor

**Actual result:** Screen turns black, can not view video call
**Expected result:** Screen never turns off for video call unless phone is (manually) locked -- this is if either end has triggered the video track.  (WA video call screen auto locks if on video call and app is not in focus on iOS, have not tested other apps or other platforms)

### Screenshots

N/A

### Device info

**Device:** Moto X
**Android version:** 5.2
**Signal version:** 3.29.1

### Link to debug log
https://gist.github.com/bb8429fa788dc5205ef4f3665f556d8c

**Comment by johanw666** [comment]
Why is this unwanted? Normal calls do this too, at least on the Android devices I've been using.

**Comment by moxie0** [comment]
I agree, this is the intended behavior. I can't think why you'd want the screen to be that close to your face and still be on?

**Comment by RiseT** [comment]
> if phone/sensor is held very close to the face/hand/object

Possibly "hand" or "object" is the actual problem here rather than "face".

**Comment by braaccckkk** [comment]
> Why is this unwanted? Normal calls do this too, at least on the Android devices I've been using.

You don't need the display for normal calls, but you will need it for video calls so it should be active.

**Comment by ruicruzpt** [comment]
I can reproduce this. This should be considered a bug.

Other popular video/audio calling systems like WhatsApp and Skype disable this when video call is active.

**Comment by anarcat** [comment]
I have been very happy to try out Signal's new video feature yesterday, but the most notable usability issue for my friends used to Facetime and Skype is exactly this bug: the screen (and, from their perspective, the camera, as they lost visual feedback) would turn off when they would reach out to the phone. I had to explain what the proximity sensor was, they didn't understand what was going on at all.

Video calls are different than phone calls: you do *not* hold the phone to your ear in video calls like you do in phone calls, therefore there's no reason why the proximity sensor should be working.

**Comment by moxie0** [comment]
What if we disable the proximity sensor only when your video stream is enabled? I'm thinking that you could have your phone up to your ear when the other party enables video, and then you'd still want the proximity sensor to be on.  Would that satisfy folks?

**Comment by brianpgrissom** [comment]
That could work

**Comment by RiseT** [comment]
How does Signal iOS currently behave in that regard?
