### ISSUE TITLE
Cannot delete a "Signal contact" from contacts

### ISSUE THREAD

**Issue by rejhgadellaa** [WhisperSystems/Signal-Android#6182]
I was invited to a group chat with some people I do know and a few I don't. I mistakenly added one of the phone numbers to an existing contact (yes, dumb, I know) but now I can't fix this error. I deleted the number in the Google Contacts app but if I tap "View more fields" it still shows under Signal Contacts and it still shows his name in Signal when it's not him. Is there no way to remove this field once Signal puts it in there??

**Comment by ByteHamster** [comment]
Settings -> accounts 
Remove signal account 
Open signal
Compose message (so you see a contacts list)
Refresh contacts 

You will not lose your messages.

**Comment by rejhgadellaa** [comment]
Thanks I'll have a look.
