### ISSUE TITLE
App crashes on launch if installed to system partition

### ISSUE THREAD

**Issue by gmes78** [WhisperSystems/Signal-Android#6183]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Since version 3.29.0, Signal crashes every time I launch it.

Downgrading to 3.28.4 makes it work again, and allowed me to get the debug log.

From the debug log: `couldn't find "libjingle_peerconnection_so.so"`
So I'm thinking that some library's x86 version is missing from the apk.

Update: It seems to be related to having Signal installed to /system/app.

### Steps to reproduce
- Install Signal to /system/app
- Remove Signal from /data/app (if present)
- Reboot

### Workarounds
Either:
- Extract the `libjingle_peerconnection_so.so` from the apk to the lib/x86 folder where the apk is in.
- Install as user app.

### Device info

**Device:** Asus Zenfone 2
**Android version:** 7.1.1 (RessurectionRemix ROM)
**Signal version:** 3.29.2

### Link to debug log

https://gist.github.com/anonymous/ce07f6fc8097ac9a5f35a85006393a7a

**Comment by moxie0** [comment]
Strange, it is in the aar. I'll try to reproduce in an emulator.

**Comment by gmes78** [comment]
I figured it out. I had Signal installed to /system, and the `libjingle_peerconnection_so.so` library, unlike the others, has to be in the lib/x86/ folder. So either extracting the library manually to /system/app/Signal/lib/x86/ or installing Signal as a user app makes it work again.

I'll now update the issue.

**Comment by moxie0** [comment]
Sounds like you're doing some custom stuff, and it sounds like there might have been a problem during the installation, it's standard for shared libraries to be in lib/arch. I don't think we can support any other behavior.

**Comment by 2-4601** [comment]
same stuff #6213

**Comment by minomoto** [comment]
same issue #6309
