### ISSUE TITLE
Occassional crash when responding through Android N/7 quick reply

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-Android#6185]
I have:
- [X] searched open and closed issues for duplicates; most closely related to https://github.com/WhisperSystems/Signal-Android/issues/4968 and https://github.com/WhisperSystems/Signal-Android/issues/2971
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Crash ~20% of the time when responding through Android N quick reply

### Steps to reproduce
- don't have signal in the foreground 
- be notified of a message 
- pull down to see notifications 
- click reply 
- type a reply 
- click the send icon 

**Actual result:**Message sends
**Expected result:** Signal crashes but the crash notification is not visible. The notification just looks like it is taking a while to send, but it will never send; flick up to collapse the notifications; Now you see the crash notification on top of whatever app you were using

### Screenshots

N/A

### Device info

**Device:** LGE Nexus 5X
**Android version:** 7.1.1
**Signal version:** 3.28.4

### Link to debug log

log 1: https://gist.github.com/48460102b52c1d3dcf51d58e09504773
log 2: https://gist.github.com/0373184adb2020e6b8440f6028881e0e
log 3: https://gist.github.com/739ce632e78e1e8b6345b10f4705decf

**Comment by mammuth** [comment]
@riyapenn was it you that faced the crashes or other users? If so, might you check whether this change solves the problem? 
https://github.com/mammuth/Signal-Android/tree/6185-fix-direct-reply-crash

I only experienced the crash once on my 'production'-device (S5, LineageOS 14), and wasn't able to reproduce it afterward (neither on the S5 nor on a Stock Android 7.1 Nexus4). As a result, I can't assure, whether my change really fixes the crash.
