### ISSUE TITLE
Short authentication string (SAS) word pairs not visible on WebRTC calls

### ISSUE THREAD

**Issue by mmirg** [WhisperSystems/Signal-Android#6186]
I have:
- [x ] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
There are no SAS word pairs visible when placing a call with WebRTC.  This is not intended to be a critique of the crypto design or implementation of ZRTP but rather to reflect that two call recipients without knowledge of cryptography expressed concern that not having the SAS could result in possible interception of the calls.  The reaction was not related to the technical details of the Signal protocol but rather a sudden, unexplained change in a ritual that accompanied previous usage of the service.  At least one call recipient was using the latest iOS beta.  I apologize if this is considered more to be a comment than a bug.

### Steps to reproduce
- Place WebRTC call
- Look for previously existing SAS codes

**Actual result:** SAS codes are not visible and there is no explanation for why they are no longer there.
**Expected result:** Either to see the SAS codes or, in the case that they have been purposefully removed, perhaps some other (transitional) visual indication of call security (particularly vis-a-vis tapping or middle attack interception in lieu of the old SAS word pairs.
### Device info

**Device:** Huawei Nexus 6P
**Android version:** 7.1.1
**Signal version:** 3.29.2

**Comment by nrizzio** [comment]
WebRTC calls are authenticated by your long-term identity key, so an on-screen SAS is no longer necessary. If the identity key changes when a video call is initiated, [the user is informed](https://whispersystems.discoursehosting.net/t/voice-video-beta/760/10?u=nrizzio).
