### ISSUE TITLE
Can't send/recieve messages on WiFi

### ISSUE THREAD

**Issue by GAS85** [WhisperSystems/Signal-Android#6188]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
 
----------------------------------------
 
### Bug description
Messages (also pictures, GIFs, voice notes, etc) is sent to participant are shown as pending to download (white rounded icon), but never downloading till change from WLAN to Cellular network.
On other device media is marked as send and received (if in Cellular). Or pending to send if on wifi
Works in both ways (from device A to B and from B to A).
Both devices using Android 6.0.1.

It seems I should blame my WLAN. But nothing is blocked there.
Could it be that Provider did blocked something? It also strange that placeholders are created (information is partly received), but not messages.
 
### Steps to reproduce
- Device A is in the home WLAN.
- Picture/GIF/Voice Note was sent from B to A.
- B see Medial marked as send.
- A see only message placeholder and spinning circle forever in WLAN.
- A disable WLAN and immediately in Cellular Network got all media files downloaded. 
 
Works in a both ways.
 
**Actual result:** Only message placeholder and spinning circle are shown forever in WLAN.
**Expected result:** Media downloaded, messages recieved.
 
### Screenshots
![screenshot_20170207-213457](https://cloud.githubusercontent.com/assets/6813635/22727932/beed74a0-eddb-11e6-8cdb-eb5c2940cea8.png)
 
 
### Device info
A
**Device:** Huawei Nova
**Android version:** 6.0.1
**Signal version:** 3.28.4
 
B
**Device:** Samsung S III i9305
**Android version:** 6.0.1
**Signal version:** 3.28.4
 
### Link to debug log
https://gist.github.com/anonymous/9360580da4b3d6be89753271757f572d

**Comment by moxie0** [comment]
Looks like an issue with your WLAN. It is trying to connect, but the connection is timing out.

**Comment by GAS85** [comment]
Let me try to test it on weekends again.
I already run tcpdump on Wednesday and send messages, and I could (!) send and receive text messages, but since I touch Media like a GIF it was again everything corrupted and no messages could be send or received. But from the pcap I can not see what goes wrong except the TCP close at some point to gif proxy. But this is ok, since I goes back to Signal messages from the GIF view.
If you have fun, fell free to check this pcapng (I put names of NATed IPs). --> [https://gas85.ddns.net/index.php/s/DRC8oQLiP6ReuhF/download](url)

**Comment by AtlandaGonozal** [comment]
I have exactly the same bug. The difference is only, that most of the time it works perfectly. Then out of nowhere no connection is posible anymore over WiFi. I also discovered that if I start a VPN connection to another server, signal works perfect again. Very strange!

**Comment by Prolex** [comment]
Still the same problem here. Especially at evening here in Germany I can't build up a wifi connection within Signal. All other apps (including WhatApp!) work. So it can't be a problem of my own wifi -router setup. Mobile connection and a VPN connection works fine though. Only Wifi makes the problems.

**Comment by GAS85** [comment]
Funny, but I run test right now and it works as expected. Also in German Network. Only difference is new unrooted phone as B device, but A device is the same. I do not know what happens here.
P.S. Link to pcap you should copy and paste in your browser, otherwise 404.

**Comment by drathier** [comment]
Same problem here since about a week. Cannot send/receive messages over wifi. 3G works fine.

### Device info
Device  : OnePlus A0001 (bacon)
Android : 7.1.2 (5d0cad9112, bacon-userdebug 7.1.2 NJH47B 5d0cad9112 release-keys)
Memory  : 23M (3.39% free, 768M max)
Memclass: 288
OS Host : varun-MS-7923
App     : Signal 4.6.1

### Link to debug log
https://gist.github.com/anonymous/c291f623ad5c13f0fabe5d5646a2c80f

**Comment by moxie0** [comment]
@drathier Looks like something on your network is MITMing your TLS connection so the cert validation is failing. Can you post the certificate that's presented over your wifi network here?

**Comment by drathier** [comment]
How do I see what cert the signal app is seeing? 

This is the cert chrome is seeing for whispersystems.org, on both android and windows, behind the same router (one on wifi, one using cable). [drathier-whispersystems.org-cert.zip](https://github.com/WhisperSystems/Signal-Android/files/1100046/drathier-whispersystems.org-cert.zip) It looks just fine to me.

**Comment by drathier** [comment]
On both 3G and wifi, that is.

**Comment by moxie0** [comment]
textsecure-service.whispersystems.org

**Comment by drathier** [comment]
There we go. Got a cert for *.pr.extole.io over wifi, looks like some link referal site. Thank you for helping me find this, wouldn't have noticed this if it weren't for Signal! Is that the real textsecure cert I'm seeing though? 

![screenshot_20170625-114655](https://user-images.githubusercontent.com/3695812/27515177-4eb7046a-599e-11e7-859c-f7c0fa97d6e0.png)
![screenshot_20170625-115708](https://user-images.githubusercontent.com/3695812/27515178-4ebf5638-599e-11e7-8476-eabf0ab19779.png)
![screenshot_20170625-114701](https://user-images.githubusercontent.com/3695812/27515179-4ec0a966-599e-11e7-8417-48b5e9865b7e.png)
![screenshot_20170625-114750](https://user-images.githubusercontent.com/3695812/27515182-4eca3eae-599e-11e7-84ae-254469bbe92b.png)
![screenshot_20170625-114535](https://user-images.githubusercontent.com/3695812/27515180-4ec795fa-599e-11e7-9541-5e1eac6f59c9.png)
![screenshot_20170625-114806](https://user-images.githubusercontent.com/3695812/27515183-4edb1508-599e-11e7-9024-b4e1f0ce1594.png)
![screenshot_20170625-120034](https://user-images.githubusercontent.com/3695812/27515184-4ee03268-599e-11e7-9f91-f5351685090c.png)
![screenshot_20170625-114626](https://user-images.githubusercontent.com/3695812/27515185-4ee300ec-599e-11e7-9bf2-9af780e4f280.png)
![screenshot_20170625-114812](https://user-images.githubusercontent.com/3695812/27515186-4ee84192-599e-11e7-9fb1-b154b214a8b3.png)

**Comment by drathier** [comment]
I'm getting the same cert on my phone over 3G as on my computer over cable (or at least the sha1 matches for the first few bytes), so I'm guessing the phone is infected.

**Comment by drathier** [comment]
Now I see the correct cert again. Installed new firmware on my router, completely wiped my phone and installed a new kernel and rom.

**Comment by moxie0** [comment]
Cool seems like this is unrelated to Signal so I'm going to close for now. Thanks.

**Comment by joneshank** [comment]
Problem has not been solved as of 12/25/19
I cannot send anything over wifi. It is ONLY happening on Signal. All other messanging apps work

**Comment by joneshank** [comment]
It is also happening today over regular cellular broadband connection

**Comment by Shadoware** [comment]
Im having the same problem. Signal works in my phone using 4G but not wifi. Desktop signal works correctly in the same network, just the Android app version has problems with wifi. All other app works correctly in my phone like whatsapp or Telegram.
