### ISSUE TITLE
Unread notification badges not working on S7 Edge & LG G4

### ISSUE THREAD

**Issue by Blackbird777** [WhisperSystems/Signal-Android#6192]
I have:
- [X ] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Unread notification badges not working on S7 Edge after upgrade to Android 7.0.  I am using the Default Samsung S7 Edge launcher

### Steps to reproduce
- New text message arrives
- New message notification present in top notification area
- New message is seen inside the Signal App
- Unread notification badges not present
- "Notification Allowed" set in Settings->Applications
- Signal set as Default Messaging App in Settings->Applications
**Actual result:** New message count badge does NOT appear
**Expected result:** New message count badge should appear Signal icon

### Device info

**Device:** Samsung S7 Edge Model SM-G935FD, Unlocked, Dual Sim capable, UAE on Cricket Wireless in the US, 
**Android version:** 7.0
**Signal version:** 3.28.4

### Link to debug log
 https://gist.github.com/6a5f5c9910fd869bb086bdc6f3ad2ce0

**Comment by haffenloher** [comment]
Do badges work with the [ShortcutBadger test app](https://github.com/leolin310148/ShortcutBadger#isbadgeworking)?

**Comment by Blackbird777** [comment]
Unfortunately not

⁣
------
Rik Bostic​

**Comment by haffenloher** [comment]
Looks like this is tracked here:
https://github.com/leolin310148/ShortcutBadger/issues/169
At least there's a mention of the Samsung Galaxy S7 Edge.
We'll need to update our version of the library once this is fixed.

**Comment by Blackbird777** [comment]
Badges ARE working with the ShortcutBadger test app

**Comment by haffenloher** [comment]
May be related to https://github.com/leolin310148/ShortcutBadger/commit/ca9e457a6793510a027498d24427282da025b642 which is included in v1.1.12. We're using v1.1.10 at the moment.

**Comment by celtnielsen** [comment]
This is also an issue on Android 6.0 with LG G4 and LG Style phones. Please correct this issue. Thank you

**Comment by riyapenn** [comment]
Count at 2: "change that precipitated this was an upgrade to Android 7.0 (Nougat)" https://gist.github.com/anonymous/2dab8817bc013ed8dc10c8046989151a

**Comment by pinnerup** [comment]
I have the same problem, which arose after upgrading to Android 7. I've also tested the ShortcutBadger app, and that works fine. 

I'm currently running Signal 4.0.1 under Android 7.0 on a Samsung Galaxy S7 Edge (model number SM-G935F).

A debug log taken just now is available here: https://gist.github.com/anonymous/888998427dcdd6e340a7c8cda6f14882

**Comment by McLoo** [comment]
ShortcutBadger got updated a few days ago. Version 1.1.14 fixes (most?) Samsung issues and also updates for the Sony launcher along work a buncho of other changes, since we're still on version 1.1.0 see [here](https://github.com/leolin310148/ShortcutBadger/blob/master/README.md) 

The port for Signal needs to be updated...

**Comment by Blackbird777** [comment]
Unread notification badges appear to be working now on my S7 Edge after upgrade to Signal 4.2.4.  

Great job!

Thank you.

**Comment by McLoo** [comment]
Assuming LG is fixed too...
