### ISSUE TITLE
Can't see who updated a group

### ISSUE THREAD

**Issue by vvug** [WhisperSystems/Signal-Android#6194]
After a group is modified ("updated" in Signal's jargon, see #6193) the other users just see a "Group updated." message if one user was added, or "Group name is now 'newname'.". These messages should show who made the change, for example:

"Masha added Alice the group."
"Masha refreshed the user list." <- Group update received, but with no new members
"Masha renamed to group to 'newname'."

**Comment by rainerzufall** [comment]
There is an open PR which addresses improving the group update behaviour : https://github.com/WhisperSystems/Signal-Android/pull/5416

**Comment by vvug** [comment]
Fixed by https://github.com/WhisperSystems/Signal-Android/commit/3506f2db12a72e43e3ab4d1d7af931ba3786d457.
