### ISSUE TITLE
Listen to voice messages through earpiece instead of loudspeaker

### ISSUE THREAD

**Issue by matt89le** [WhisperSystems/Signal-Android#6195]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When listening to a vocal message, putting the phone near your ear doesn't make anything at all, while I am expecting the proximity sensor to turn off the screen and send the sound to the earpiece instead of the loudspeaker.

### Steps to reproduce
- listen to a vocal message
- darken the proximity sensor
- nothing happens

**Actual result:** nothing happens
**Expected result:** the sound should be sent to the earpiece while the screen should be turned off

### Device info

**Device:** Honor Model 6X (BLN-L21)
**Android version:** 6.0
**Signal version:** 3.28.4

**Comment by p4nci** [comment]
How about an additional button like in the webrtc call screen for manual switch between earpiece and speaker.
Here a mockup
![2017-02-09_22 09 38](https://cloud.githubusercontent.com/assets/16047081/22805361/5c184a92-ef1d-11e6-911a-d04dd3484c47.png)

**Comment by Acromonkey** [comment]
It is implemented perfectly in Telegram! No ear touching the screen makes the speaker play the voice message, and the ear touching the phone makes the earpiece play it.

Right now it is horrible: When I receive a voice message in the library or in the metro, I cannot listen to it because it will in any case be played by the speaker and everybody can hear it.

Only exception: With earplugs it works well.

My phone is a Nexus 5x.

**Comment by moxie0** [comment]
in 4.1.0

**Comment by p4nci** [comment]
@moxie0 switching from speaker to earpiece works, but screen doesn’t turns off (i.e. the screen isn’t locked). I made so an unintended change (i.e. set new value for disappearing massages) with my ear :confused:
imo, screen should be locked if placed to ear

**Comment by geokon-gh** [comment]
Any chance for a manual toggle in some menu?
This features works very inconsistently for me on my phone. I end up hitting buttons with my cheek half the time. 

For instance in Wechat you can set all messages to play "privately" through the earpiece, so you don't need to be so careful about keeping you ear perfectly sandwiched to the light sensor
