### ISSUE TITLE
Rotating device into landscape temporarily changes Signal's language to Android's default

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/Signal-Android#6205]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Rotating device into landscape temporarily changes Signal's language to Android's default

### Steps to reproduce

Example 1:
- **In Signal's settings, set language to one that is not the default on your phone**
- From the conversation list, tap the pencil floating button (contact list & keyboard will open)
- Rotate device to landscape with keyboard open
- Note that the button description right to the input field is displayed in Android's default language

Example 2:
- **In Signal's settings, set language to one that is not the default on your phone**
- In portrait mode, open a conversation
- Open action bar (3-dot) menu in order to check displayed language: It's the one set in Signal
- Rotate device to landscape
- Open 3-dot menu in order to check displayed language: It's the one set in Android
- Rotate back to portrait
- Open 3-dot menu in order to check displayed language: It's *still* the one set in Android

This is true not only for the 3-dot menu, but for all kinds of texts within the UI.
E. g. the desciptions you get when long-pressing a button. Or the recpients list in a group conversation. Or the settings decriptions.
(Note: You have to close an re-open the element after rotating the device to experience the effect).

**Actual result:** Language of many elements changes after rotating into landscape
**Expected result:** Language set in Signal stays no matter what

### Device info

**Device:** LG Nexus 5X
**Android version:** 7.1.1
**Signal version:** 3.29.2

**Comment by FeuRenard** [comment]
Duplicate of #2815

**Comment by RiseT** [comment]
@FeuRenard Oops. That's a pretty old one...
