### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by WithWings4** [WhisperSystems/Signal-Android#6210]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After exchanging secured messages with contacts they appear as 'other' in Google's Default Contact Manager, instead of the actual custom string that the number is set to.

I have contacts organized by client, so the actual contact is the org, then the number is 'so & so's cell' etc.

Normally in Google Contact Manager it displays the custom string underneath the number.

When I go to make a call to the number (now listed as 'other) it will come up as 'so & sos cell', but it makes it problematic since I haven't memorized all of their numbers.

If I go to edit the contact via the Google Contact Manager it is displayed properly, so the information isn't lost. It also displays properly via google.com/contacts

Everyone who isn't on signal for that contact displays the proper 'custom' string; 'so & so's cell'. It is only modified after messages are exchanged. After restarting the phone 1 of the 4 contacts was again displayed properly. I deleted that users conversation via my linked PC while the phone was shutoff. The other 3 were deleted before I shut the phone down, and they display as 'other'.

### Steps to reproduce
-HTC One M8 root using the HTC web method
-Install TWRP 3.0.2-0 for the m8 (flashed via Odin 3.12.5)
-Install open_gapps-arm-7.1-aroma-20161206, using stock selections
-Fully patch Google Apps via Play auto update
-Fully patch everything except Cyanogen beyond the listed version
-Install Next SMS, and make default SMS app
-Install Signal, let it take defaults
-Exchange messages with users via Signal

**Actual result:** After exchanging messages via signal the contact 'custom' string is overwritten by 'other'
**Expected result:** The Contact 'custom' string shouldn't change type to other, or be overwritten for any reason.

### Device info
HTC One M8
Android 7.1
CyanogenMod v14.1-20161202-NIGHTLY-m8
Android Security Patch level: Nov 5th, 2016
Baseband version: 1.23.213311491.05G_20.57.4198.02_F
Kernel version: 3.4.0-g3a88f13 / inky@cyanogenmod #1 / Thu Dec 1 21:01:09 PST 2016
Build date: Thu Dec 1 20:53:49 PST 2016
Build number: cm_m8-userdebug 7.1 NDE63X 336d26b07f test-keys
SELinux status: Enforcing

Signal 3.28.4

### Link to debug log
https://gist.github.com/fcb3ffbec7e1fb6127c519ae887959cb

**Comment by moxie0** [comment]
This sounds a lot like a ROM bug. Signal does add a raw contact associated with the Signal account, but if rebooting the phone occasionally fixes it I'm not sure what Signal can do. 

Looks like you're running a custom ROM too, what makes you think this isn't a rom bug?

**Comment by WithWings4** [comment]
So far it has only flipped the one user, and hasn't changed of the others. It does modify each user as they are contacted via Signal.

It could be a ROM bug, I don't have sufficient knowledge to give you an accurate assumption.

I do have a couple of other devices I can test this weekend to see, some of them are running stock firmware.

**Comment by WithWings4** [comment]
I had forgotten; all of the devices are running Cyanogenmod (for security reasons). None of the tablets have the ability to install signal.

**Comment by WithWings4** [comment]
So I have a workaround; an alternate contact manager. I can't vouch for any of these, but am currently using one called drupe from here:

https://play.google.com/store/apps/details?id=mobi.drupe.app&hl=en

Which displays the contacts properly. I would prefer to use Google's Contact manager as I am sure their security is better.

I intend on having clients donate money to open source organizations for the use of great software. As I feel it is good to have them do. That said I won't be doing that unless bugs like these are fixed.

Thank you for the great software otherwise.
