### ISSUE TITLE
[Feature Request] Add Contact's custom string to Signal app

### ISSUE THREAD

**Issue by WithWings4** [WhisperSystems/Signal-Android#6211]
My contacts are organized by client, and the phone numbers listed as 'so & so's cell'.

Is it possible to add the 'custom' string under the Name of the Contact in Signal? That way I can easily tell who I'm chatting with.

I don't know a better way to organize lots of numbers with Google. It's been rather clunky usually, but this way I can quickly find people.

**Comment by ryolait** [comment]
Same request, with suggestion :

In my contact book, I can give a custom / personnalized label to a telephone number for a contact. For example, when the contact's name is "John & Sandra Smith", I can have 4 phone numbers with different labels : "John cellphone", "Sandra cellphone", "Home" and "Work".

In a Signal conversation, at the top, I have the name of the contact ("John & Sandra Smith") and the phone number I'm writing to under it. However, the phone number does not help me to find if I'm writing to John or to Sandra. It would be better to have the label of the phone number at this place.
