### ISSUE TITLE
Message draft can get lost

### ISSUE THREAD

**Issue by cascheberg** [WhisperSystems/Signal-Android#6212]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
A drafted message can get lost when you (mistakenly) open a conversation that has a drafted message and (therefore) go back to the conversation list immediately.

There is a quite noticeable lag until the message draft is displayed in the text input field. The bug occurs if you leave the conversation before the draft has been loaded.

### Steps to reproduce
- Add a message draft to a conversation
- Open that conversation from conversation list
- Immediately tap back button to go back to conversation list

**Actual result:** Message draft has been deleted
**Expected result:** Message draft should be kept

### Device info

**Device:** Nexus 4
**Android version:** stock Android 5.1.1
**Signal version:** 3.29.2

**Comment by Shenkaa** [comment]
I've tested this issue on several devices (4.4.4 & 6.0.1), also with different Signal versions (3.27.1, 3.28.4 & 3.29.2), and can confirm the bug.
But it only appears if the "Video calling beta" is enabled. If this option is dissabled, the lag is not noticeable or even absent.

**Comment by cascheberg** [comment]
Great catch! The reason for the lag in `ConversationActivity` is the `AsyncTask` in `initializeBetaCalling` blocking the `AsyncTask` in `initializeDraftFromDatabase`.
