### ISSUE TITLE
NoClassDefFoundError: android.graphics.SurfaceTexture

### ISSUE THREAD

**Issue by Bene81** [WhisperSystems/Signal-Android#6220]
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
Since last week I am having signal crash at start up. 
Wiped all data, reinstalled, did not help.

Log error is as following:
W/System.err(16403): java.lang.NoClassDefFoundError: android.graphics.SurfaceTexture
W/System.err(16403): 	at java.lang.Runtime.nativeLoad(Native Method)
W/System.err(16403): 	at java.lang.Runtime.loadLibrary(Runtime.java)
W/System.err(16403): 	at java.lang.System.loadLibrary(System.java)
W/System.err(16403): 	at org.webrtc.PeerConnectionFactory.<clinit>(PeerConnectionFactory.java:21)
W/System.err(16403): 	at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:90)
W/System.err(16403): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java)
...

Full log is attached.

### Steps to reproduce
- Opening Signal
- Tap Signal Icon
- wait for signal to open

**Actual result:** White screen apears for a second then signal exits
**Expected result:** Signal should be opened and display my contacts.

### Screenshots
none possible

### Device info
**Device:** HTC Desire HD / HTC ACE
**Android version:** 2.3.5 (custom ROM Android Revolution HD 9.2)
**Signal version:** 3.29.5 and previous two (beta?) releases

### Link to debug log
can't do, signal preferences are not accessible:

logcat instead:
[logcat.txt](https://github.com/WhisperSystems/Signal-Android/files/770635/logcat.txt)

**Comment by ocram** [comment]
`SurfaceTexture` was introduced in API level 11 and you're on 10

**Comment by moxie0** [comment]
A Gingerbread user! Dang, looks like libwebrtc is 11+. This might mean the end of gingerbread support. =(

**Comment by Bene81** [comment]
Looks like it. Looks like I need to get a phone update. Should have done this for security reasons anyways.

**Comment by johanw666** [comment]
Could there not be a "3.28.4 + security and compatibility patches" version for Gingerbread? There are more apps where Google Play has "depends on device" in the current version field. Gingerbread users will have to do without video calling then, but since that's already only enabled when both sides support it I see no problem here.

**Comment by moxie0** [comment]
I've disabled webrtc in GB for now, but eventually the new calling system will be the default and modern clients will no longer support the old calling system, at which point GB might have to go. From the play store console, it looks like there are very few GB users these days (the number is so low that it's just aggregated into "other" now). 

@Bene81 good on you for hanging on so long!  And thanks for the report.
