### ISSUE TITLE
Messages shuffle on scroll

### ISSUE THREAD

**Issue by tsdmgz** [WhisperSystems/Signal-Android#6223]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Messages change to last messages seen at bottom or top of screen depending on direction while scrolling through message history. I have a secondary phone (Huawei P8lite) that does not appear to exhibit the same problem.

First noticed this issue with Signal 3.28.4

### Steps to reproduce
- Open a thread
- Quickly scroll up or down then flick down to end of conversation

**Actual result:** Messages do not correspond to history
**Expected result:** Messages should be as it were.

### Screenshots
![msg-shuf](https://cloud.githubusercontent.com/assets/9064273/22973385/6c9e3ea4-f3b8-11e6-9f9f-328832b2d803.gif)

### Device info

**Device:** Samsung Galaxy J5 2016 (SM-J510GN)
**Android version:** 6.0.1
**Signal version:** 3.29.6

### Link to debug log
https://gist.github.com/tsdmgz/4f06f5369288a2e3cc8153748efde8db

**Comment by moxie0** [comment]
whoa that's bizarre, do you notice it in all threads? even fairly short ones?

**Comment by WDKevin** [comment]
I also have the exact same issue. It started with the update prior to introducing video calls. It happens, for me, on all threads. It happens on short ones too as long as there are enough messages to scroll a full page or more.

If you keep scrolling it seems to change the messages around more but never goes back to the correct way until you close the thread and open it back up. But if you scroll again it happens again.

I've been meaning to submit this bug and I'm glad to see someone else did and it's not just me.

**Comment by moxie0** [comment]
@WDKevin Thanks that sounds really annoying. @tsdmgz mentions fast scrolling, is it fast scrolling for you as well, or any scrolling?

**Comment by tsdmgz** [comment]
@moxie0
just tried and yes, also happens on threads with less than 100 messages.

@WDKevin
relieved to know it's also not just me. is your phone a samsung, by any chance?

**Comment by Trolldemorted** [comment]
@tsdmgz i saw this happening on a friend's samsung some months ago, i think - at least the last message was just gone after scrolling up and down.

**Comment by WDKevin** [comment]
@moxie0 Yes, it is fast scrolling. It's very annoying, it makes it impossible to read the history of the conversation.

@tsdmgz Yes, it is a Samsung. It's a Note 4.

**Comment by tsdmgz** [comment]
@WDKevin huh. following ours and @Trolldemorted, guess our pattern is all samsungs so far.

**Comment by moxie0** [comment]
@tsdmgz @WDKevin This doesn't reproduce on any of the devices I have. If I were to give you a signed APK, would you have time to test it? There are a lot of changes that could be the culprit, so we might have to go through a few iterations.

**Comment by moxie0** [comment]
(alternately under the very rare possibility that you're building and installing from source yourselves, git-bisect would be really useful)

**Comment by tsdmgz** [comment]
Willing to ~dissect~ bisect and started one from v3.25.0 and 7d1056057. Is there a better starting point or are there any special instructions (aside from backups) or do I just follow BUILDING.md?

**Comment by Trolldemorted** [comment]
Are you sure it was ok on 3.25.0?

I saw the message disappearing several months ago, but it could have been a different issue.

**Comment by tsdmgz** [comment]
Unfortunately, no. I don't even know which version was good. All I remember was I first noticed this problem by around 3.28 or so.

Also, I seem to be having problems building?

~~~
   > Could not resolve all dependencies for configuration ':compile'.
      > Could not find com.android.support:appcompat-v7:25.1.0.
        Searched in the following locations:
            https://repo1.maven.org/maven2/com/android/support/appcompat-v7/25.1.0/appcompat-v7-25.1.0.pom
            https://repo1.maven.org/maven2/com/android/support/appcompat-v7/25.1.0/appcompat-v7-25.1.0.jar
            https://raw.github.com/whispersystems/maven/master/preferencefragment/releases/com/android/support/appcompat-v7/25.1.0/appcompat-v7-25.1.0.pom
            https://raw.github.com/whispersystems/maven/master/preferencefragment/releases/com/android/support/appcompat-v7/25.1.0/appcompat-v7-25.1.0.jar
            https://raw.github.com/whispersystems/maven/master/smil/releases/com/android/support/appcompat-v7/25.1.0/appcompat-v7-25.1.0.pom
            https://raw.github.com/whispersystems/maven/master/smil/releases/com/android/support/appcompat-v7/25.1.0/appcompat-v7-25.1.0.jar
            https://raw.github.com/whispersystems/maven/master/shortcutbadger/releases/com/android/support/appcompat-v7/25.1.0/appcompat-v7-25.1.0.pom
            https://raw.github.com/whispersystems/maven/master/shortcutbadger/releases/com/android/support/appcompat-v7/25.1.0/appcompat-v7-25.1.0.jar
            https://raw.github.com/whispersystems/maven/master/photoview/releases/com/android/support/appcompat-v7/25.1.0/appcompat-v7-25.1.0.pom
            https://raw.github.com/whispersystems/maven/master/photoview/releases/com/android/support/appcompat-v7/25.1.0/appcompat-v7-25.1.0.jar
            https://dl.bintray.com/amulyakhare/maven/com/android/support/appcompat-v7/25.1.0/appcompat-v7-25.1.0.pom
            https://dl.bintray.com/amulyakhare/maven/com/android/support/appcompat-v7/25.1.0/appcompat-v7-25.1.0.jar
            https://jcenter.bintray.com/com/android/support/appcompat-v7/25.1.0/appcompat-v7-25.1.0.pom
            https://jcenter.bintray.com/com/android/support/appcompat-v7/25.1.0/appcompat-v7-25.1.0.jar
            file:/home/gjie/.m2/repository/com/android/support/appcompat-v7/25.1.0/appcompat-v7-25.1.0.pom
            file:/home/gjie/.m2/repository/com/android/support/appcompat-v7/25.1.0/appcompat-v7-25.1.0.jar
        Required by:
            :Signal-Android:unspecified
~~~

and several other files

**Comment by tsdmgz** [comment]
just finished bisecting and it's pointing to 7286fd9b06ec582bfd4ed83dd81a461564806250 as the first bad commit. i've been instaling Signal-Android-debug.apk

debug log: https://gist.github.com/tsdmgz/735a513508df11cfa5ac6ce6bea5e662

**Comment by r-arias** [comment]
I can confirm, I have the same issue on a Fairphone 2 running Android 5.1 and could not reproduce it on a Samsung Galaxy S7. I also seem to be the only one in my social circle that has this problem.

* all threads
* Scrolling slowly does not help for me.

I'm not really an Android developer but in iOS cells from tables (what people at Apple call lists) are reused when scrolling to (I guess) minimize memory allocations. I'm guessing that in Android something similar is done and it seems to fail to update the cells correctly?

**Comment by r-arias** [comment]
Oh, I forgot to add (and can't find an edit button in the mobile version of the github page):

The issue, of course, becomes worse if the keyboard is being displayed, as there is less space. So, when scrolling up, messages are replaced by "already seen" messages from a newer date below earlier.

Not sure if this is helpful. Might be difficult to understand from my explanation. If necessary, I can try to provide screenshots.

**Comment by moxie0** [comment]
@tsdmgz Thank you so much! That's really helpful. I don't totally understand what's wrong with my change, but it does seem like the culprit. I will probably just revert it.

**Comment by moxie0** [comment]
in 3.30.0

**Comment by tsdmgz** [comment]
Tested and working. Thank you @moxie0!

@r-arias
If you can do a backup from Titanium Backup, try testing this out.

**Comment by WDKevin** [comment]
I don't build from source but would have no problem testing, although it seems to have been fixed. I will just wait for the update to hit the play store. Thank you so much to everyone who reported and helped fix this issue!
