### ISSUE TITLE
Crash when receiving call during a Skype call

### ISSUE THREAD

**Issue by t3io** [WhisperSystems/Signal-Android#6229]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashed when an incoming signal call happened during an established Skype call.

### Steps to reproduce (disclaimer: I have not attempted to reproduce this)
- I was on a Skype video call
- suddenly I noticed an incoming Signal call
- next thing I know, Signal has crashed. I do not remember accepting or rejecting the call. I believe signal was still "ringing" when it crashed. 
- the Skype call was unaffected

**Actual result:** Signal crashed
**Expected result:** no crash, but it's not obvious to me what the best next action should be.

### Device info
**Device:** Samsung Galaxy S5 Neo 
**Android version:** 6.0.1
**Signal version:** 3.27.1

### Link to debug log
https://gist.github.com/anonymous/e09bd6939d6baaf5edab9ef32ded972b

**Comment by justin-sleep** [comment]
It looks like your device just ran out of memory.

**Comment by moxie0** [comment]
Out of memory error. That's a pretty old version of Signal! There were some changes in the last few releases to optimize the amount of memory it consumes, so hopefully upgrading will prevent future problems. Thanks for the debug log!
