### ISSUE TITLE
Impossible to establish secure session for a reinstalled peer on 7th new moon or like

### ISSUE THREAD

**Issue by grinapo** [WhisperSystems/Signal-Android#6232]
I have:
- [x] searched open and closed issues for duplicates
- [-] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Feel free to close if you are disturbed by the lack of details. I try.

I have an old peer, last messages were a year ago. Today I have tried to message him and Signal (android) was only offering insecureSMS. The peer have been writing to my _other_ phone so it works. However I was able to verify safety number (for an insecure only session?), but no reset session and like. He wasn't able to message me.

Then I have opened up the chrome web client, and seen the following (old) exchange:
- old messages (ok)
- some old messages which were neither delivered nor received and the web client says "number is not registered"
- a 'secure session reset' old message, with number not registered as well

Then I have tried to send a new message from the web client, and it was successfully delivered. Also, from that point, my phone have changed to secure connection with all the matching menu entries.

### Device info
**Device:** OnePlus One
**Android version:** 6.0.1
**Signal version:** 3.28.4

**Comment by riyapenn** [comment]
Contact support@whispersystems.org for personalized support.

**Comment by grinapo** [comment]
Do I look as someone who *need* support? 😦 It's you, dummy. Your problem, not mine. I tend to realise that you people don't care about fixing your bugs, why the f--- should I waste my time on you reporting them? 
Thanks for the arrogance. Next time read first, reply later.

**Comment by Trolldemorted** [comment]
that was the kind way of saying "we know that our server randomly drops users and not even in a consistent way", i guess. There are many issues about it, e.g. https://github.com/WhisperSystems/Signal-Android/issues/5859, https://github.com/WhisperSystems/Signal-Android/issues/5531 or https://github.com/WhisperSystems/Signal-Android/issues/6049.

**Comment by moxie0** [comment]
This does seem like a legitimate issue to me

**Comment by grinapo** [comment]
@moxie0 it results a state of a contact where it is known [to the other party] **but** stuck in _insecure_ connections, without _any visible means to tell_:
* why is it insecure (while both sides know one another and they have matching safety numbers)
* how to make it secure again.

If I wasn't trying the chrome client (which I hardly ever use) and it wasn't "magically" fixed itself I would have to try to clear app data (=reset everything) or remove and reinstall it, and I am not sure even that would have fixed it (since there may be a problem on your server, I don't know). Since Signal is widely used by non-professionals now they would have pretty hard time to figure out what to do.

And indeed it is similar ('duplicate') of #5531 and #6049 .

**Comment by Trolldemorted** [comment]
@grinapo do any exceptions occur when you open the contact's thread?

**Comment by grinapo** [comment]
@Trolldemorted I cannot readily create a 2 years old chat inactive for more than a year to reproduce the bug, and since I have mentioned that it has been fixed when the web client touched it I cannot tell what internal stuff may have happened back then. I would rather not share my guesses here, many would feel I'm not qualified. :-) Next time I see it I try to extensively logcat it before letting Mrs. Keyboard Macro downcustomering me again.

**Comment by grinapo** [comment]
Seems to have been fixed (GCM sync problem). Yay.
