### ISSUE TITLE
SMS/MMS send&receive not working anymore

### ISSUE THREAD

**Issue by rhetr** [WhisperSystems/Signal-Android#6235]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
As of today I am unable to send or receive SMS/MMS messages. I am unable to make Signal the default SMS/MMS app through both the Signal settings menu and the Android system settings.

#### cannot send sms through conversation
- open signal
- press an sms conversation
- press "ENABLE SIGNAL FOR SMS"
- nothing happens

#### cannot set signal as default through signal settings
- open signal
- press menu
- press settings
- press SMS and MMS
- press SMS disabled
- nothing happens

#### cannot set signal as default through system settings
- press system settings
- press default message app
- signal is not there

**Actual result:** I'm unable to successfully send/receive SMS/MMS or to mark Signal as the default message app
**Expected result:** I should be able to successfully send/receive SMS/MMS and make Signal the default message app

### Device info
**Device:** LG K7
**Android version:** 5.1.1
**Signal version:** 3.29.6

**Comment by 2-4601** [comment]
Could you send some [debug logs](https://support.whispersystems.org/hc/en-us/articles/212535838-How-do-I-send-a-debug-log-)?

**Comment by jeremymasters** [comment]
Here is one for not being able to receive mms on my wife's s7 Verizon stock 6.0.1 https://gist.github.com/9ffc07694cc89fb79efee209d1a93b5a

**Comment by rhetr** [comment]
I reinstalled Signal and it worked fine. I'll reopen if it happens again.
