### ISSUE TITLE
! Connectivity error. Signal was unable to connect to the server.

### ISSUE THREAD

**Issue by exarkun** [WhisperSystems/Signal-Android#6237]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I try to register with Signal on my XT1528 ("Moto E 2nd Generation"), Verizon branded, the process fails with the error:

    Connectivity error.
    Signal was unable to connect to the server

This happens repeatably - 6 or 7 times so far.  I have never used Signal before (on this phone or otherwise).

The failure occurs on the last step after an SMS with a verification code has been received.

### Steps to reproduce
- Install Signal
- Attempt to register

**Actual result:** Registration fails and Signal is unusable.

**Expected result:** Registration completes and Signal is usable.

### Device info
**Device:** Motorola Moto E 2nd Gen XT1528
**Android version:** 5.1
**Signal version:** 3.29.6

**Comment by moxie0** [comment]
Hey @exarkun thanks for the report. I have a feeling it might be a problem with generating a GCM token, are you running stock Android or a custom ROM?

It'd be helpful if we had a debug log to be able to look at what's failing, but you can't get to Signal's built in debug log collection because it's not accessible until after the registration screen. Are you able to use `adb logcat` to capture a log directly?

**Comment by exarkun** [comment]
It's stock Android, I think - at least, it's the Verizon-branded Android that came with the phone.

I've extracted a log with `adb logcat`.  I noticed it contained at least a small amount of private information (my phone number).  I can elide that but I'm worried I might be overlooking something else.  Is there a way I can share it more privately?  Or is there a subset of the logic that's useful that I could more easily audit (eg certain service prefixes)?  Thanks.

**Comment by moxie0** [comment]
@exarkun You can email it to me at moxie+github@whispersystems.org if you're comfortable with that

**Comment by exarkun** [comment]
Thanks.  It's on the way.

**Comment by moxie0** [comment]
Yeah:

```
W/InstanceID/Rpc( 8002): No response android.os.ConditionVariable@38f74b39^M
W/RegistrationService( 8002): java.io.IOException: TIMEOUT^M
W/RegistrationService( 8002):   at com.google.android.gms.iid.zzc.zzb(Unknown Source)^M
W/RegistrationService( 8002):   at com.google.android.gms.iid.zzc.zza(Unknown Source)^M
W/RegistrationService( 8002):   at com.google.android.gms.iid.InstanceID.zzc(Unknown Source)^M
W/RegistrationService( 8002):   at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)^M
W/RegistrationService( 8002):   at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)^M
W/RegistrationService( 8002):   at org.thoughtcrime.securesms.service.RegistrationService.handleCommonRegistration(RegistrationService.java:247)^M
W/RegistrationService( 8002):   at org.thoughtcrime.securesms.service.RegistrationService.handleSmsRegistrationIntent(RegistrationService.java:208)^M
W/RegistrationService( 8002):   at org.thoughtcrime.securesms.service.RegistrationService.access$000(RegistrationService.java:63)^M
W/RegistrationService( 8002):   at org.thoughtcrime.securesms.service.RegistrationService$1.run(RegistrationService.java:95)^M
W/RegistrationService( 8002):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)^M
W/RegistrationService( 8002):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)^M
W/RegistrationService( 8002):   at java.lang.Thread.run(Thread.java:818)^M
```

Looks like something is up with the Play Services install on your device. Have you updated it through the Play store recently? Or are you on a network that would be blocking communication with GCM?

**Comment by exarkun** [comment]
It seems that Play Services auto-updated recently.  The version is apparently 10.2.98.

I don't think my network should be blocking access to GCM.  My attempts have been while the phone is connected to my home network.  I don't know of any particular reason GCM would be blocked from this network - if there's an experiment I can run from another device connected to the same network to test this out, I can try it.

**Comment by exarkun** [comment]
FWIW:

```
$ curl https://gcm-http.googleapis.com/gcm/send > /dev/null && echo $?
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   243    0   243    0     0     54      0 --:--:--  0:00:04 --:--:--    70
0
$
```

**Comment by exarkun** [comment]
This morning I re-read this discussion and it occurred to me that Play Services may just have gotten itself wedged somehow.  So I restarted the phone.  And registration completed successfully. :/

Thanks for the help @moxie0 !

**Comment by moxie0** [comment]
Oh good, some solutions are timeless. Glad it worked out.

**Comment by lpar** [comment]
Just had this issue with my wife after giving her my Nexus 5X and applying a factory reset. On boot it immediately demanded that a Google Play Services update be applied, so we did. However, Signal would fail to contact the server to set up messaging.

Reading this thread, I uninstalled the Play Services update and rebooted, ignoring the errors from all the other Google apps, and Signal was then able to register.

Next I updated Play Services and rebooted again, and now there's a warning saying

> Optimize for missing Play Services
> This device does not support Play Services. Tap to disable system battery optimizations that prevent Signal from retrieving messages while inactive.

Any ideas? I guess it could be a GCM outage. Will the battery optimizations turn on again if Play Services start working again?

**Comment by sigenc** [comment]
Hmmm seems like it did fall back to websocket.

**Comment by realdevnullius** [comment]
Got the same; reboot fixed it :) Rather stock-like Cubot P20.
