### ISSUE TITLE
[Beta call system] Speakers disabled when call is answered

### ISSUE THREAD

**Issue by ruicruzpt** [WhisperSystems/Signal-Android#6238]
### Bug description
If you enable speakers *before* the call begins, when the other person get the call, your speakers will be disabled without any warning or message. 
Other apps (and the old calling system) keeps it enabled if you enable it prior to any call answered.

Can anyone else reproduce this? 

### Steps to reproduce
- enable beta calls on both sides
- make a call and quickly enable the speakers

**Actual result:** When the other person accepts the call, your speakers will be disabled and you need to enable them again.
**Expected result:** Speakers should be enabled.

### Device info
**Device:** Sansumg  S6
**Android version:** 6.x

**Comment by FeuRenard** [comment]
I can reproduce it.

**Comment by FeuRenard** [comment]
Disabling this line solves this issue:
https://github.com/WhisperSystems/Signal-Android/blob/f3e47f7b608a6beb77b6732d676b47c56184248c/src/org/thoughtcrime/securesms/service/WebRtcCallService.java#L696
But I cannot assess which other issues this change would introduce.

**Comment by Shenkaa** [comment]
@FeuRenard I tried the same today and have not noticed any additional/other errors so far. The only think this line does, is to disable the speaker and bluetooth headset. Or am I wrong?

**Comment by FeuRenard** [comment]
> But what I can't understand, the RedPhoneService uses the exact same method and the error doesn't occur there..

RedPhone initializes audio at the beginning of `handleIncomingCall(...)` and `handleOutgoingCall(...)` which calls `AudioUtils.resetConfiguration(this)`. This resets the audio mode to default instead of speaker.
WebRTC initializes audio only in `handleCallConnected(...)`. This causes the audio mode to go to default instead of stay with speaker mode as soon as the connection is established.

**Comment by Shenkaa** [comment]
Ahh. Thanks for the hint, now I see it also.

**Comment by ruicruzpt** [comment]
Is this somehow related with other bug I discover?

- if you have the option enabled to disable screen when you're near the camera (when you "approach" the camera with your face), and have speakers or/and video on, if you go near the front camera, it shuts down the screen. this does not hapen with Skype or WhatsApp (witch I rarely use this days).

If this is related with the same issues, I'll edit my first post. If not, I'll post a new issue.

Thanks!

**Comment by Shenkaa** [comment]
See https://github.com/WhisperSystems/Signal-Android/issues/6179 for this issue.

**Comment by ruicruzpt** [comment]
Thanks @Shenkaa - appreciate your help.

**Comment by moxie0** [comment]
fixed in 3.31.0
