### ISSUE TITLE
Chromium app opened twice --> "A MESSAGE FROM ... WAS NOT RECEIVED"

### ISSUE THREAD

**Issue by Acromonkey** [WhisperSystems/Signal-Android#6240]
I am using Wire as a Chromium app on my Linux Mint PC. When I accidently open the Wire app twice, I can normally chat in the secondly opened chat window, but in the firstly opened chat windows I will see messages like 

"A MESSAGE FROM XXX WAS NOT RECEIVED. (ERROR: 8550)"

You find the detailed error messages in the attached image.

I don't think, that this kind of behavious is intended, because it is very confusing for the user. Especially after I closed the secondly opened chat window, I continued receiving these error messages. They stop appearing when I click on "RESET SESSION". 

![wire](https://cloud.githubusercontent.com/assets/19237773/23041790/8075729c-f496-11e6-9db5-1c428f3527c7.png)

**Comment by sweeper3000** [comment]
Hey, looks like you opened this in the wrong repo. I believe you're looking for @wireapp

**Comment by Acromonkey** [comment]
Ohh, no, you are right! Sorry!!
