### ISSUE TITLE
Echo cancellation stops working when receive email that generates audio notification

### ISSUE THREAD

**Issue by jeffbl** [WhisperSystems/Signal-Android#6248]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
While using the beta video chat, but on an audio-only call, everything is great, but when remote user received an email message that generated an audio notification, suddenly echo cancellation stopped working and there was intolerable echo.

### Steps to reproduce
- enable beta video calling
- make audio-only call, connects fine, audio quality great
- remote phone receives email, I believe in K9 mail

**Actual result:** Echo cancellation fails, and much louder overall audio, for both call participants.
**Expected result:** Echo cancellation continues to work regardless of other system audio

### Device info

**Device:** Nexus 6p, both ends
**Android version:** 7.1.1
**Signal version:** 3.29.6

### Link to debug log

Apologies, failed to get log - will have to reproduce with other party again tomorrow.

**Comment by moxie0** [comment]
This should be fixed in 3.31.0. Please reopen if problems persist w/ that branch.
