### ISSUE TITLE
Gradle failed says:Error:CreateProcess error=2, The system cannot find the file specified

### ISSUE THREAD

**Issue by Asad1234567** [WhisperSystems/Signal-Android#6254]
I have:
- [ ] searched open and closed issues for duplicates
- [ ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by moxie0** [comment]
If you're having problems setting up a build environment, this isn't really the right place. You can try the online forums.

**Comment by SureshItha590** [comment]
Hi Team,
I am try to build the groovy and Java project in my IntelliJ ID for windows but my project got failed with error message: Error:CreateProcess error=2, The system cannot find the file specified Kindly let me know how to fix this issue

**Comment by nrizzio** [comment]
@Sureshltha590 post at https://whispersystems.discoursehosting.net

**Comment by SureshItha590** [comment]
Hi @nrizzio,

I did not find your answer on mentioned above link. Kindly post your answer here. Its very critical. I am unable to run my gradle project in my Intellij IDE. Its giving below error message.
"Gradle 'iris-authoring' project refresh failed
    Error:Error:CreateProcess error=2, The system cannot find the file specified". Kindly post your suggestions here its really very helpful for me.

**Comment by nrizzio** [comment]
[This issue tracker is for Signal issues.](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#not-a-discussion-forum) You're having a build issue, which isn't a Signal issue. You can make a post on the forum I referenced, and someone may be able to help you there.

**Comment by kusal772** [comment]
It is a cloning error in the Singal application. Some android studio versions may give this error. Try fresh reinstalling your android studio.
