### ISSUE TITLE
Battery drain during audio call

### ISSUE THREAD

**Issue by friend7** [WhisperSystems/Signal-Android#6259]
I have:
- [ x] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Battery drain.

### Steps to reproduce
After every audio call. 

**Actual result:** 20 min audio call battery drops about 5%. Back cover of Nexus5X is hot around camera eye. In Signal Battery usage it keeps camera active despite it is audio call only.

### Device info

**Device:** Nexus5X
**Android version:** 7.1.1
**Signal version:** 3.29.6

**Comment by gjallarhorn** [comment]
Are you trying out the new beta call system (WebRTC) or is this just the default call mode?
Also, please update the bug report with a link to your [debug log.](https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports#capture-a-debug-log)

**Comment by friend7** [comment]
Yup, WebRTC beta call system.

I will update bug report with debug log as soon as I make new audio call.

**Comment by sigenc** [comment]
I have the same problem with Nexus 5 (Stock latest updates), Samsung S6 (Android 6), Nexus 6P (noise 3.30.0). it Shows as 40 % battery drain. I have screenshots logs and will provide them later. And yes the camera seems active even if it is only a voice call.

**Comment by friend7** [comment]
My recent audio call log (15min audio, 3℅batt)

https://gist.github.com/d174c9a3b0387f2b6b24cd2d45a6b699

**Comment by friend7** [comment]
I forgot screenshot of signal battery usage after audio call:
https://s17.postimg.org/t78e28dm7/Screenshot_20170223_201128.png

**Comment by moxie0** [comment]
this should be fixed in 3.31.x, please reopen if you continue to have problems with that code
