### ISSUE TITLE
Unread/last seen separator looks clunky and is hardly readable using dark theme

### ISSUE THREAD

**Issue by PiCob** [WhisperSystems/Signal-Android#6265]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The new unread separator looks very clunky (uses much screen space and thus notably reduces the message view "capacity", which is likely to suck on small displays) and has not been adapted to the dark theme.

(Since issues with the dark theme most often go along with new features being introduced, the PR contribution template could perhaps be enhanced to include a test with both themes?)

### Steps to reproduce
- use dark theme
- receive a new message
- open the corresponding conversation

**Actual result:** Unread/last seen separator looks clunky and is hardly readable using dark theme
**Expected result:** Separator is readable und less "heavy" (in terms of size, especially the height)

### Screenshots
![screenshot_20170221-100657](https://cloud.githubusercontent.com/assets/23237468/23158578/fe3d6c52-f81f-11e6-836d-5d5d3bae29b0.png)

### Device info

**Device:** Lenovo Moto G4 Plus
**Android version:** 6.0.1
**Signal version:** 3.30.0

### Link to debug log
(omitted, since unnecessary)

**Comment by moxie0** [comment]
sizing is similar to whatsapp. looks like it should be styled differently for dark theme, but i'm not really sure how to recreate the same effect

**Comment by PiCob** [comment]
To be honest, I didn't look how WA has styled it (since uninstalled a year ago), I just feel it shouldn't be sized that big. Wouldn't it make sense sizing it like the date header to get a more consistent view?

**Comment by cbarnsdale** [comment]
I had actually never used the light theme before, so I just switched to see how this is _supposed_ to look. I actually find it quite unobtrusive in the light theme. If it can be kept really subtle in the dark theme, I think it will work well there too.

**Comment by Shenkaa** [comment]
On the light theme, the "unread messages"-separator looks good and quite similar to WhatsApp as seen on this [picture](https://ixquick-proxy.com/do/spg/show_picture.pl?l=deutsch&rais=1&oiu=http%3A%2F%2F2.bp.blogspot.com%2F-wCllt-uP9Us%2FV3OgLUYfJQI%2FAAAAAAAAFzo%2FcZZw8NtynLsUgzMPbDllZllrgiiypuyewCK4B%2Fs1600%2Fwhatsapp%252Bunread%252Bmessages.png&sp=028af21d8cde87fc57412e2983dc23e1).
The problem is, that last_seen_background.9.png (the grey bar) on a black background looks identical(?) to the bubble's background, that making it clunky.

**Comment by PiCob** [comment]
I agree, it's mainly the background rect that makes it look clunky. What about simply removing it and drawing the separator like the date separator (in terms of colors)? That should do the trick. A minor point would be using a (bigger) rounded rect (like the date headers) instead of an ellipsis for the sake of consistency...

**Comment by PiCob** [comment]
And while we're at it: if the background rect is subject to removal, top and bottom margin should be reduced as well, I think (again, like the date headers)...

**Comment by Shenkaa** [comment]
@PiCob Like that?
Light Theme
![um_light_theme](https://cloud.githubusercontent.com/assets/25299821/23183723/52e5fbe0-f87d-11e6-98a3-76db87d75792.png)
Dark Theme
![um_dark_theme](https://cloud.githubusercontent.com/assets/25299821/23183733/574d1b0a-f87d-11e6-928d-4f804dcc7ba4.png)

**Comment by PiCob** [comment]
Exactly like that... :) Thx!
