### ISSUE TITLE
Feature Request: Emoji only messages should show bigger

### ISSUE THREAD

**Issue by legrk** [WhisperSystems/Signal-Android#6269]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature description
Messages only consisting of emojis should be shown bigger than messages consisting of text only or mixed messages.
Apparently Whatsapp has four sizes for emoji messages. With the number of Emojis size decreases:
- 1 emoji message
- 2 Emojis message
- 3 Emojis message
- 4 or more Emojis or mixed messages

### Screenshots

![](http://www.androidpolice.com/wp-content/uploads/2016/09/nexus2cee_whatsapp-big-emoji-after-2.png)
Source: http://www.androidpolice.com/wp-content/uploads/2016/09/nexus2cee_whatsapp-big-emoji-after-2-217x386.png

**Comment by FeuRenard** [comment]
There is also a request in the community forum:
https://whispersystems.discoursehosting.net/t/jumbomoji-support-like-slack-others/724

**Comment by rainerzufall** [comment]
This issue can be closed as it has been fixed by the PR https://github.com/WhisperSystems/Signal-Android/pull/6531

**Comment by bmintz** [comment]
@rainerzufall it should be kept open, as they don't work anymore in 4.13.2

**Comment by rainerzufall** [comment]
For me it is working since April, when the aforementioned PR was commited. No change in displaying Jumbomoji with 4.13.2.

If it has stopped working for you with the update to 4.13.2 you probably should open a new issue, completely with all the information that is being asked (debug logs, phone specs, etc. // see here for what is needed: https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports)

**Comment by wizardofid** [comment]
Seems that it is no longer working for some emojis. I found the following examples by chance:
:arrow_right:
:bangbang:
:information_source:
@rainerzufall Maybe you could check these emoji with your Signal-instance.

**Comment by rainerzufall** [comment]
All three are working as expected (they get jumbosized) on my phone (Device: Fairphone 2; Android version: 6.0.1) with Signal 4.13.2 beta.

**Comment by FeuRenard** [comment]
This feature request (!) should be closed because the feature is implemented. For bugs in the implementation there should be separate issues like #6758 and #7213.
