### ISSUE TITLE
signal call error: login failed (on blackberry)

### ISSUE THREAD

**Issue by snbl** [WhisperSystems/Signal-Android#6272]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Testing Signal on Blackberry Passport
- I'm not able to initiate a call to another contact on iPhone. Receiving Error message "Login failed!". 
- I'm not able to receive a call. When trying to call from an iPhone it never rings or indicates an incoming call

Tested without success mentioned in other "login failed" github issues
- contacts refreshed 
- un-/re-registering app (via call/sms not working)
- reinstalled from play store

### Steps to reproduce
- Trying to initiate call from chat
- Call window opens - after 1 second receiving "Login failed!"
- Call window closes to message/chat history
- Trying to call from iPhone -> iPhone starts ringing -> nothing happens on Blackberry until iPhone drops call due to timeout

### Device info
**Device:** Blackberry Passport
**Android version:** 4.3
**Signal version:** 3.30.0 (beta program)
**App state:** registered via call (sms does not work), sms/mms settings all disabled, notifications remained unchanged, no passphrase, screen security and safety numbers approval activated, android app settings all allowed (read contacts, modify clipboard, post notification)

### Link to debug log
log without relay
https://gist.github.com/anonymous/132137d173c7ad6aba9f5c1716280568
log with relay activated
https://gist.github.com/anonymous/fac855dab140d5988bd4d2458338405d

Happy to provide any further details or perform some testing!

**Comment by 2-4601** [comment]
related #4563

**Comment by moxie0** [comment]
Sounds like you are you running the non-play-services version?

**Comment by snbl** [comment]
That's correct. Android runtime on Blackberry OS 10 lacks of the play services. Anything I can provide in addition for further investigation?

**Comment by vandenheuvel** [comment]
As described in https://github.com/WhisperSystems/Signal-Android/issues/4563, I'm also running the non-play-services version. Before that version however, I also had the same problem. I used to have the RedPhone in the past, maybe something is wrong with accounts on the server side (in my case).

**Comment by moxie0** [comment]
You can only call people who have enabled "beta calling."  Settings -> Advanced -> Video calling beta. (You don't see that settings, it's on by default for you)

**Comment by sigenc** [comment]
I have the same problem with noise 3.30.0. I noticed that you set webrtc to default when there is no gcm Services. But it doesn't work correctly. I'm testing with:

Ipod Touch (latest updated) (Signal 2.7.1.2) (webrtc enabled)
Nexus 5 (Stock latest updates) (Signal 3.29.6) (webrtc enabled)
Nexus 5 (Stock latest updates) (Signal 3.30.0) (webrtc enabled)
Nexus 6P (Copperhead) (Noise 3.30.0) (webrtc enabled by default)

I can call the Nexus 6P from all devices. But i can't call any of the devices with the Nexus 6P. It Shows the old Redphone UI and says Login failed. 

I will provide you with logs later.

**Comment by vandenheuvel** [comment]
Problems I described in https://github.com/WhisperSystems/Signal-Android/issues/4563 are over now, I can confirm everything to work properly.
