### ISSUE TITLE
Easter Egg: Conversation thread disappears if message trim conversation limit is set to X and conversation thread is empty (i.e. last X messages disappear )

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-Android#6290]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal conversation thread disappears if message trimming is enabled and all line items/messages have been removed or disappeared

### Steps to reproduce
- Set message trimming to X, in this example 2
- Create Signal group or direct conversation
- Edit disappearing message timer
- Send X-1 messages, in this example 1
- Message disappears after timer
- Conversation thread remains because of the “Disappearing message timer” alert
- Send X messages, in this example 2
- Messages disappear after timer (Same result if call entires etc are deleted and group thread is empty, not displayed in log)
- Conversation thread is empty

**Actual result:** Conversation thread deletes/disappears
**Expected result:** Conversation thread remains (issue more so for groups that have not been left)

### Screenshots
N/A

### Device info

**Device:** Motorola Moto X 2nd Gen
**Android version:** 5.1
**Signal version:** 3.29.2 & 3.30.1

### Link to debug log

log from 3.29.2: https://gist.github.com/anonymous/30eef6c52c71529bc5f386633bcbf476
log from 3.30.1: https://gist.github.com/anonymous/a96c2a38314ffe751da11774410f0889

**Comment by haffenloher** [comment]
Duplicate of #6038?

**Comment by riyapenn** [comment]
Sounds like it! Terrible searching on my part. Thanks for the quick find!
