### ISSUE TITLE
Can't send secure messages or set auto-delete

### ISSUE THREAD

**Issue by gethob1** [WhisperSystems/Signal-Android#6294]
I'm using Signal 3.29-6 and am unable to send secure messages or set auto-delete, at least to a recipient using Noise 3.30-2.0; I haven't tested users of other versions.  There is apparently no way to synchronize versions if that is the problem.  Please restore secure messaging and auto-delete.  (Noise doesn't appear to have a place to file bugs.)  Thank you

**Comment by nrizzio** [comment]
If this is a Noise issue then it's out of the control of OWS. OWS doesn't officially endorse third party clients for this reason. You can try the forums located at https://whispersystems.discoursehosting.net.

**Comment by gethob1** [comment]
I couldn't find anything useful in the link, but thanks.  It would sure help if Signal was available in F-Droid because I'm using Copperhead, a security-hardened fork of Android which doesn't allow Google Play Store.  Even though there are concerns putting Signal in F-Droid per that link, I'm unable to receive secure messages and so having that option in F-Droid would make me more secure.  I've been struggling for over a year trying to get an app that works with Signal.  First there was LibreSignal which was discontinued.  Now Noise doesn't work.  It's impractical to compile Signal apk every time it's updated plus I don't know how to do that.  Copperhead forum just points to OWS github, and I'm out of options it seems.  I'd appreciate anything you can do

**Comment by gethob1** [comment]
Actually I can't compile Signal apk-- still requires Google Play Store which I can't install.

**Comment by nrizzio** [comment]
Secure messaging and disappearing messages were certainly not removed from Signal. You'll have to get help from the CopperheadOS people. If they are still telling people to open issues on OWS's repositories for their problems, please tell them to stop doing that.
If you need help building Signal, please go to the community forums per the CONTRIBUTING file. This bug tracker is really not the place for a) help with other people's software, nor b) technical help with setting up your build environment.

**Comment by moxie0** [comment]
Agreed, sorry @gethob1 but we can't support other people's products here.
