### ISSUE TITLE
3.30.2: messages from desktop client sometimes show as unread messages in android app

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#6296]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
My own messages, when sent to another person from my desktop client, show as unread in my android app

### Steps to reproduce
-Have conversation with another person and have a desktop client linked to your android app
-Send messages from your desktop client
-Glance at your android app

**Actual result:** Sometimes when I open my android app, my own messages show up as unread messages
**Expected result:** Anything I send should never considered unread on my end, especially if it's the only message since I sent one from my android app

### Screenshots
Didn't get one in time

### Device info

**Device:** Samsung Galaxy Note 5
**Android version:** 6.0.1
**Signal version:** 3.30.2

**Comment by tge-linee** [comment]
Duplicate of https://github.com/WhisperSystems/Signal-Android/issues/6273

Also: https://github.com/WhisperSystems/Signal-Android/commit/8cd50d1e82a608513afca1abae9f6d95b260a2cb

**Comment by jeremymasters** [comment]
Fixed in 3.30.4.
