### ISSUE TITLE
WebRTC missed call always plays disconnected sound

### ISSUE THREAD

**Issue by cascheberg** [WhisperSystems/Signal-Android#6298]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The sound for disconnected calls is played when an expired incoming call is received (even if device is muted). See `WebRtcCallService.handleIncomingCall()` and `WebRtcCallService.terminate()`.

### Steps to reproduce
- enable WebRTC
- disable wifi & mobile data
- get called by someone using WebRTC
- enable wifi / mobile date

**Actual result:** Notification about missed call is shown. Plays the disconnected sound.
**Expected result:** Should show the notification but not play the disconnected sound.

### Device info
**Signal version:** 3.30.3

**Comment by dcherian** [comment]
Fixed in 3.31.0?
