### ISSUE TITLE
Received pictures list your own number under "Received" if you check the message details

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/Signal-Android#6300]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
For some reason received pictures shows your own number (along with the name of the contact) under the message details.

### Steps to reproduce
1. Open a contact
2. Ask them to send a picture
3. Hold your finger on the picture
4. Press the (i) at the top of the screen
5. Scroll down
6. It should look like this
https://vgy.me/6YQAai.png

**Actual result:** Your own number is listed as the person who sent the picture, along with the person who actually did
**Expected result:** Your number should not be displayed.

### Screenshots
https://vgy.me/6YQAai.png

### Device info
Doesn't seem to matter

**Comment by haffenloher** [comment]
Dupe of #2874

**Comment by Dyras** [comment]
Crap!
