### ISSUE TITLE
Crash after Beta Call

### ISSUE THREAD

**Issue by merkste** [WhisperSystems/Signal-Android#6305]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashed after a beta call. The call used video but only for a brief moment. Afterwards we used audio only.

### Steps to reproduce
This crasher crash happened the second time for me but I cannot trigger it on purpose.

### Device info

**Device:** Motorola Moto G 3rd Gen
**Android version:** 6.0.1
**Signal version:** 3.29.6

### Link to debug log
https://gist.github.com/0976c03d6d514268e469ccdfae6a0167

**Comment by cascheberg** [comment]
```
java.lang.AssertionError: assert
at org.thoughtcrime.securesms.service.WebRtcCallService.handleLocalIceCandidate(WebRtcCallService.java:422)
```

I have seen this during testing as well (Android 5.1.1, Signal 3.30.3). Happened immediately after hanging up a WebRTC call (without video).

**Comment by moxie0** [comment]
i've added additional logging in 3.31.x, please post a new log if it happens again when running that version

**Comment by merkste** [comment]
Unfortunately I had another crash. This time after but answering an incoming call. However, I believe it is related. Log:
https://gist.github.com/anonymous/f6b36e2ff69efadb073def87a8c84a6d
