### ISSUE TITLE
Signal crashes during loading after update 3.29.6 

### ISSUE THREAD

**Issue by minomoto** [WhisperSystems/Signal-Android#6309]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal 3.29.6 3.30.1-4 3.31.4 closes after starting on Asus_T00Q (x86)
(Couldn't load **jingle_peerconnection_so** error) 

### Steps to reproduce
1. Update to 3.29
2. Run the app  
3. Actual result: run error
4. Expected result: running app
5. The same with 3.30.1, 3.30,3, 3.30.4. 

The same issue on arm: #6213 

### Workaround

Downgrade to 3.28 (apk without libjingle_peerconnection_so.so in /lib/x86/)
UPD: Messages dosn`t work anymore on 3.28 due to security reason. Update user firmware (WW_5.4.2-user by ASUS) to solve the issue.

### Device info

**Device:** ASUS_T00Q  (ZenFone 4)
**Android version:** 4.4.2
**Signal version:** 3.29.6

### Debug log

E/AndroidRuntime(18561): FATAL EXCEPTION: main
**E/AndroidRuntime(18561): Process: **org.thoughtcrime.securesms**, PID: 18561**
E/AndroidRuntime(18561): java.lang.UnsatisfiedLinkError: **Couldn't load jingle_peerconnection_so** from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.thoughtcrime.securesms-2.apk", zip file "/data/data/org.thoughtcrime.securesms/code_cache/secondary-dexes/org.thoughtcrime.securesms-2.apk.classes2.zip"],nativeLibraryDirectories=[/data/app-lib/org.thoughtcrime.securesms-2, /vendor/lib, /system/lib, /system/lib/arm]]]: **findLibrary returned null**
E/AndroidRuntime(18561): 	at java.lang.Runtime.loadLibrary(Runtime.java:358)
E/AndroidRuntime(18561): 	at java.lang.System.loadLibrary(System.java:526)
E/AndroidRuntime(18561): 	at org.webrtc.PeerConnectionFactory.<clinit>(PeerConnectionFactory.java:21)
E/AndroidRuntime(18561): 	at org.thoughtcrime.securesms.ApplicationContext.onCreate(ApplicationContext.java:92)
E/AndroidRuntime(18561): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
E/AndroidRuntime(18561): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4400)
E/AndroidRuntime(18561): 	at android.app.ActivityThread.access$1500(ActivityThread.java:138)
E/AndroidRuntime(18561): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296)
E/AndroidRuntime(18561): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(18561): 	at android.os.Looper.loop(Looper.java:149)
E/AndroidRuntime(18561): 	at android.app.ActivityThread.main(ActivityThread.java:5077)
E/AndroidRuntime(18561): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(18561): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(18561): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/AndroidRuntime(18561): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
E/AndroidRuntime(18561): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  862):   Force finishing activity org.thoughtcrime.securesms/.RoutingActivity
E/IMGSRV  (  151): :0: PVRDRMOpen: TP3, ret = 60
E/IMGSRV  (  151): :0: PVRDRMOpen: TP3, ret = 43
D/dalvikvm( 1128): GC_EXPLICIT freed 1864K, 40% free 17437K/28912K, paused 8ms+12ms, total 110ms
W/ActivityManager(  862): Activity pause timeout for ActivityRecord{228c0ad0 u0 org.thoughtcrime.securesms/.RoutingActivity t187 f}
I/WindowManager(  862): computeScreenConfigurationLocked() Enter {1.0 ?mcc?mnc ?locale ?layoutDir ?swdp ?wdp ?hdp ?density ?lsize ?long ?orien ?uimode ?night ?touch ?keyb/?/? ?nav/?}
I/WindowManager(  862): dw=480, dh=854
I/WindowManager(  862): appWidth=480, appHeight=854
I/WindowManager(  862): tempdm=DisplayMetrics{density=1.5, width=480, height=854, scaledDensity=1.5, xdpi=218.185, ydpi=215.66}
I/WindowManager(  862): dm=DisplayMetrics{density=1.5, width=480, height=854, scaledDensity=1.5, xdpi=218.185, ydpi=215.66}, ro.product.device=ASUS_T00Q
I/WindowManager(  862): getConfigDisplayWidth=480, getConfigDisplayHeight=816
D/WindowManager(  862): adjustConfigurationLw, config:{1.0 ?mcc?mnc ?locale ?layoutDir sw320dp w320dp h544dp 240dpi nrml long port ?uimode ?night finger -keyb/v/h -nav/v} mLidState:-1 mHasDockFeature:false mHasKeyboardFeature:false mHasHallSensorFeature:false config.hardKeyboardHidden:2
I/WindowManager(  862): screenWidthDp=320, screenHeightDp=544
I/WindowManager(  862): computeScreenConfigurationLocked() Leave {1.0 ?mcc?mnc ?locale ?layoutDir sw320dp w320dp h544dp 240dpi nrml long port ?uimode ?night finger -keyb/v/h -nav/h}
I/ActivityManager(  862): [TopPkgCurBat]	NowPkgName[com.asus.launcher]	Battery[100]	TimeTick[1488176200313]	OldPkgName[org.thoughtcrime.securesms]
E/IMGSRV  (  151): :0: PVRDRMOpen: TP3, ret = 52
D/BatteryStatsImpl(  862): noteStopWakeLocked system isFromForeground = false
V/ImageWallpaper(  942): onVisibilityChanged: dds = false
E/IMGSRV  (  151): :0: PVRDRMOpen: TP3, ret = 40
E/Sensors (  862): alp setDelay : SENSOR_RATE!!!
E/Sensors (  862): alp setDelay : ms=20 !!!
E/IMGSRV  (  151): :0: PVRDRMOpen: TP3, ret = 54
D/dalvikvm(  862): GC_EXPLICIT freed 1711K, 27% free 32871K/44452K, paused 5ms+15ms, total 252ms
D/BatteryStatsImpl(  862): noteStopWakeLocked system isFromForeground = false
D/BatteryStatsImpl(  862): noteStopWakeLocked com.google.android.gms.persistent isFromForeground = false
D/WifiWatchdogStateMachine(  862): CurrentRSSI:-37
D/ConnectivityService(  862): getPrimaryDataSim returning: 1
D/ConnectivityService(  862): getPrimaryDataSim returning: 1
I/Process (18561): Sending signal. PID: 18561 SIG: 9
D/InputMethodManagerService(  862): --- calledFromForegroundUserOrSystemProcess ? calling uid = 10007 system uid = 1000 calling userId = 0, foreground user id = 0, calling pid = 1062com.android.server.InputMethodManagerService.windowGainedFocus(InputMethodManagerService.java:1887)
V/InputMethodManagerService(  862): windowGainedFocus: android.os.BinderProxy@21d0abf0 controlFlags=#5 softInputMode=#20 windowFlags=#d910100
W/InputMethodManagerService(  862): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@22561210 attribute=null, token = android.os.BinderProxy@223166f8
**I/ActivityManager(  862): Process org.thoughtcrime.securesms (pid 18561) has died.**

**Comment by moxie0** [comment]
Looks like an x86 SoC, which should be fine, since there's an x86 lib in there. Anything weird about this device, aftermarket ROM or anything like that?

**Comment by minomoto** [comment]
@moxie0, thanks a lot for any  clarification! 
I can`t to run Signal the last 2-3 weeks at least 

ASUS_T00Q aka **ZenFone 5** by ASUS  is  pretty widespread smartphone
 I used the device a lot of time. It`s the first run error issue.
And first issue with Signal. Right after the last official update.
Signal worked perfectly before. If the lib lost - what caused it and how to check.  
Just in case - no root access on the dev.

**Comment by 2-4601** [comment]
Is this a different issue from #6213?

**Comment by moxie0** [comment]
Looks to me like it's not finding it: `findLibrary returned null`.  Also it appears to be searching for `jingle_peerconnection_so` instead of `libjingle_peerconnection_so`.

I don't know why, both the library path, file type, and load syntax all look correctly to me, so I think it's a bug in the ROM for that device. I'd probably have to get that device and fool around with it to figure out why.

**Comment by minomoto** [comment]
Its seems the workaround by downgrade no longer works...  From the morning Signal Server rejects connections from old client version 3.28
3.31.4 has the same run error issue with my ROM.

**Comment by p4nci** [comment]
@minomoto probably it's temporary issue. Related https://github.com/WhisperSystems/Signal-Android/issues/6402 ?

**Comment by minomoto** [comment]
Upgrade your official firmware on zenfone manually from sd card to solve the trouble. 
@moxie0 Could you please to close the issue as solved by firmware upgrade (4.4.2->5.4.2).
