### ISSUE TITLE
Crash loop | java.lang.AssertionError: Invalid version

### ISSUE THREAD

**Issue by motatuc** [WhisperSystems/Signal-Android#6312]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
While I was writing a message, several messages came in (media and also text). Suddenly Signal froze, shortly after the phone froze and rebootet. Now I cannot start Signal anymore. It crashes instantly at the start.

### Steps to reproduce
- No idea how to simulate my phones/Signals state
- Start Signal -> Crash

**Actual result:** Signal crashes instantly and does not load
**Expected result:** Signal should work as expected (in this case it should be able to handle the error, whatever error it is actually)

### Device info
**Android version:** LineageOS 14.1
**Signal version:** 30.3.4

###Additional information:
Maybe this is of relevance: I see a lot of websocketconnection in the crash log but actually I am using play services...

### Log:
>--------- beginning of system
02-27 20:36:11.247  1352  1385 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.thoughtcrime.securesms/.RoutingActivity bnds=[28,1035][162,1187] (has extras)} from uid 10028 on display 0
02-27 20:36:11.270  1352  4155 I ActivityManager: Start proc 7172:org.thoughtcrime.securesms/u0a93 for activity org.thoughtcrime.securesms/.RoutingActivity
--------- beginning of main
02-27 20:36:11.319  7172  7172 I art     : Starting a blocking GC AddRemoveAppImageSpace
02-27 20:36:11.352  7172  7172 I MultiDex: VM with version 2.1.0 has multidex support
02-27 20:36:11.352  7172  7172 I MultiDex: install
02-27 20:36:11.352  7172  7172 I MultiDex: VM has multidex support, MultiDex support library is disabled.
02-27 20:36:11.358  7172  7172 W PartProvider: onCreate()
02-27 20:36:11.491  7172  7172 W PersistentAlarmManagerListener: class org.thoughtcrime.securesms.service.RotateSignedPreKeyListener scheduling for: 1488392210706
02-27 20:36:11.494  7172  7172 W PersistentAlarmManagerListener: class org.thoughtcrime.securesms.service.DirectoryRefreshListener scheduling for: 1488232068357
02-27 20:36:11.506  7172  7172 D JVM     : JVM::Initialize@[tid=7172]
02-27 20:36:11.507  7172  7172 D JVM     : JVM::JVM@[tid=7172]
02-27 20:36:11.507  7172  7172 D JVM     : LoadClasses
02-27 20:36:11.507  7172  7172 D JVM     : name: org/webrtc/voiceengine/BuildInfo
02-27 20:36:11.507  7172  7172 D JVM     : name: org/webrtc/voiceengine/WebRtcAudioManager
02-27 20:36:11.508  7172  7172 D JVM     : name: org/webrtc/voiceengine/WebRtcAudioRecord
02-27 20:36:11.508  7172  7172 D JVM     : name: org/webrtc/voiceengine/WebRtcAudioTrack
02-27 20:36:11.582  7172  7172 W PassphraseRequiredActionBarActivity: onCreate(null)
02-27 20:36:11.649  7172  7172 W ExperienceUpgradeActivity: getExperienceUpgrade(225)
02-27 20:36:11.660  7172  7172 W PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
02-27 20:36:11.689  7172  7172 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
02-27 20:36:11.703  7172  7172 W PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
02-27 20:36:11.936  7172  7192 W PhoneNumberFormatter: Got local CC: DE
02-27 20:36:11.946  7172  7192 W TextSecureSessionStore: No existing session information found.
--------- beginning of crash
02-27 20:36:11.981  7172  7192 E AndroidRuntime: FATAL EXCEPTION: JobConsumer-4
02-27 20:36:11.981  7172  7192 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 7172
02-27 20:36:11.981  7172  7192 E AndroidRuntime: java.lang.AssertionError: Invalid version: 795107700
02-27 20:36:11.981  7172  7192 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.storage.TextSecurePreKeyStore.loadSerializedRecord(TextSecurePreKeyStore.java:178)
02-27 20:36:11.981  7172  7192 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.storage.TextSecurePreKeyStore.loadSignedPreKey(TextSecurePreKeyStore.java:66)
02-27 20:36:11.981  7172  7192 E AndroidRuntime: 	at org.thoughtcrime.securesms.crypto.storage.SignalProtocolStoreImpl.loadSignedPreKey(SignalProtocolStoreImpl.java:106)
02-27 20:36:11.981  7172  7192 E AndroidRuntime: 	at org.whispersystems.libsignal.SessionBuilder.processV3(SessionBuilder.java:123)
02-27 20:36:11.981  7172  7192 E AndroidRuntime: 	at org.whispersystems.libsignal.SessionBuilder.process(SessionBuilder.java:108)
02-27 20:36:11.981  7172  7192 E AndroidRuntime: 	at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:172)
02-27 20:36:11.981  7172  7192 E AndroidRuntime: 	at org.whispersystems.libsignal.SessionCipher.decrypt(SessionCipher.java:142)
02-27 20:36:11.981  7172  7192 E AndroidRuntime: 	at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:149)
02-27 20:36:11.981  7172  7192 E AndroidRuntime: 	at org.whispersystems.signalservice.api.crypto.SignalServiceCipher.decrypt(SignalServiceCipher.java:118)
02-27 20:36:11.981  7172  7192 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushDecryptJob.handleMessage(PushDecryptJob.java:150)
02-27 20:36:11.981  7172  7192 E AndroidRuntime: 	at org.thoughtcrime.securesms.jobs.PushDecryptJob.onRun(PushDecryptJob.java:129)
02-27 20:36:11.981  7172  7192 E AndroidRuntime: 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
02-27 20:36:11.981  7172  7192 E AndroidRuntime: 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
02-27 20:36:11.983  1352  1386 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.RoutingActivity
02-27 20:36:12.010  7172  7172 W PassphraseRequiredActionBarActivity: onResume()
02-27 20:36:12.037  1352  4957 I OpenGLRenderer: Initialized EGL, version 1.4
02-27 20:36:12.037  1352  4957 D OpenGLRenderer: Swap behavior 1
02-27 20:36:12.062   273  1326 E NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found
02-27 20:36:12.066  7172  7172 W KeyCachingService: onCreate()
02-27 20:36:12.086  7172  7199 D NetworkSecurityConfig: No Network Security Config specified, using platform default
02-27 20:36:12.095  1352  1396 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{5d2121c u-1 android.net.conn.CONNECTIVITY_CHANGE} to ReceiverList{39d3eee 7172 org.thoughtcrime.securesms/10093/u0 remote:43f469}: process crashing
02-27 20:36:12.132  7172  7172 W service : Broadcasting new secret...
02-27 20:36:12.133  1352  1396 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{99e6e25 u0 org.thoughtcrime.securesms.service.action.NEW_KEY_EVENT} to ReceiverList{24f958d 7172 org.thoughtcrime.securesms/10093/u0 remote:d0b1624}: process crashing
02-27 20:36:12.135  7172  7172 W KeyCachingService: onStartCommand, null
02-27 20:36:12.135  7172  7172 W KeyCachingService: onStartCommand, null
02-27 20:36:12.136  7172  7172 W PassphraseRequiredActionBarActivity: onPause()
02-27 20:36:12.145  7172  7208 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, subscription_id, expires_in, expire_started, transport_type, attachment_id, unique_id, mid, data_size, _data, thumbnail, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS thumbnail, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (read = 0) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, network_failures, 'mms' AS transport_type, unique_id, mid, data_size, _data, thumbnail, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (read = 0) ORDER BY date_received ASC)
02-27 20:36:12.168  1352  4171 I WindowManager: Failed to capture screenshot of Token{41884de ActivityRecord{489dc19 u0 org.thoughtcrime.securesms/.RoutingActivity t4272 f}} appWin=Window{72e6eb7 u0 Starting org.thoughtcrime.securesms} drawState=4
02-27 20:36:12.255  7172  7172 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
02-27 20:36:12.255  7172  7172 W KeyCachingService: Incrementing activity count...
02-27 20:36:12.337  1352  1396 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{ffc7052 u-1 android.net.conn.CONNECTIVITY_CHANGE} to ReceiverList{12488b4 7172 org.thoughtcrime.securesms/10093/u0 remote:b72d187}: process crashing
02-27 20:36:12.339  7172  7210 W MessageRetrievalService: Waiting for websocket state change....
02-27 20:36:12.341  7172  7210 W MessageRetrievalService: Network requirement: true, active activities: 0, push pending: 0, gcm disabled: false
02-27 20:36:12.341  7172  7172 W MessageRetrievalService: Active Count: 1
02-27 20:36:12.343  7172  7210 W MessageRetrievalService: Network requirement: true, active activities: 1, push pending: 0, gcm disabled: false
02-27 20:36:12.344  7172  7210 W MessageRetrievalService: Making websocket connection....
02-27 20:36:12.355  7172  7210 W WebSocketConnection: WSC connect()...
02-27 20:36:12.424  7172  7210 W MessageRetrievalService: Network requirement: true, active activities: 1, push pending: 0, gcm disabled: false
02-27 20:36:12.425  7172  7210 W MessageRetrievalService: Reading message...
02-27 20:36:12.509  7172  7172 W CanonicalAddressDatabase: Hitting DB on query [ID].
02-27 20:36:12.529  7172  7172 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
02-27 20:36:12.529  7172  7172 W KeyCachingService: Decrementing activity count...
02-27 20:36:12.530  7172  7172 W MessageRetrievalService: Active Count: 0
02-27 20:36:12.581  7172  7172 W art     : Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
02-27 20:36:12.707  1352  1476 W WindowManager: Failed looking up window
02-27 20:36:12.707  1352  1476 W WindowManager: java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@5aa51b6 does not exist
02-27 20:36:12.707  1352  1476 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9440)
02-27 20:36:12.707  1352  1476 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9431)
02-27 20:36:12.707  1352  1476 W WindowManager: 	at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2394)
02-27 20:36:12.707  1352  1476 W WindowManager: 	at com.android.server.wm.Session.remove(Session.java:193)
02-27 20:36:12.707  1352  1476 W WindowManager: 	at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3290)
02-27 20:36:12.707  1352  1476 W WindowManager: 	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5923)
02-27 20:36:12.707  1352  1476 W WindowManager: 	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3629)
02-27 20:36:12.707  1352  1476 W WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-27 20:36:12.707  1352  1476 W WindowManager: 	at android.os.Looper.loop(Looper.java:154)
02-27 20:36:12.707  1352  1476 W WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:61)
02-27 20:36:12.707  1352  1476 W WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
02-27 20:36:12.708  7172  7172 W PassphraseRequiredActionBarActivity: onDestroy()
02-27 20:36:12.734  4239  4342 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
02-27 20:36:12.750  7172  7199 W RecipientPreferenceDatabase: Muted until: 0
02-27 20:36:12.758  7172  7199 W RecipientPreferenceDatabase: Muted until: 0
02-27 20:36:12.797  7172  7199 W RecipientPreferenceDatabase: Muted until: 0
02-27 20:36:12.800  7172  7199 W RecipientPreferenceDatabase: Muted until: 0
02-27 20:36:13.100  7172  7211 W WebSocketConnection: onConnected()
02-27 20:36:13.105  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.114  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.123  7172  7210 W SignalServiceEnvelope: Our MAC: 37 xx xx xx xx xx xx xx xx xx 
02-27 20:36:13.123  7172  7210 W SignalServiceEnvelope: Thr MAC: 37 xx xx xx xx xx xx xx xx xx 
02-27 20:36:13.124  7172  7210 W MessageRetrievalService: Retrieved envelope! +491xxxxxxxxxx
02-27 20:36:13.124  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.125  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.125  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.126  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.126  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.127  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.127  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.127  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.128  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.128  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.129  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.129  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.129  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.130  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.130  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.131  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.131  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.132  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.132  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.133  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.133  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.133  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.134  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.141  7172  7210 W PushReceivedJob: Received receipt: (XXXXX, 1488221296961)
02-27 20:36:13.144  7172  7210 W PhoneNumberFormatter: Got local CC: DE
02-27 20:36:13.144  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.145  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.145  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.146  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.146  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.146  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.147  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.147  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.148  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.148  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.149  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.149  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.149  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.150  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.150  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.151  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.151  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.151  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.152  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.152  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.153  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.153  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.153  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.154  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.155  7172  7210 W PhoneNumberFormatter: Got local CC: DE
02-27 20:36:13.157  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.158  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.158  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.159  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.159  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.159  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.160  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.160  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.161  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.161  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.162  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.162  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.163  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.164  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.167  7172  7210 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, subscription_id, expires_in, expire_started, transport_type, attachment_id, unique_id, mid, data_size, _data, thumbnail, ct, cl, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS _data, NULL AS thumbnail, NULL AS ct, NULL AS cl, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (thread_id = 31) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, network_failures, 'mms' AS transport_type, unique_id, mid, data_size, _data, thumbnail, ct, cl, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (thread_id = 31) ORDER BY date_received DESC LIMIT 1)
02-27 20:36:13.172  7172  7210 W PhoneNumberFormatter: Got local CC: DE
02-27 20:36:13.174  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.175  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.175  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.176  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.176  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.177  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.177  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.177  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.178  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.178  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.179  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.179  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.179  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.180  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.180  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.181  7172  7211 W WebSocketConnection: WSC onMessage()
02-27 20:36:13.181  7172  7211 W WebSocketConnection: Message Type: 1
02-27 20:36:13.192  7172  7210 W PhoneNumberFormatter: Got local CC: DE
02-27 20:36:13.193  7172  7210 W EarlyReceiptCache: org.thoughtcrime.securesms.database.EarlyReceiptCache@e2cb028
02-27 20:36:13.193  7172  7210 W EarlyReceiptCache: Early receipt: 1488221296961,+49xxxxxxxxxx
02-27 20:36:13.200  7172  7210 W MessageRetrievalService: Network requirement: true, active activities: 0, push pending: 0, gcm disabled: false
02-27 20:36:13.200  7172  7210 W MessageRetrievalService: Shutting down pipe...
02-27 20:36:13.200  7172  7210 W WebSocketConnection: WSC disconnect()...
02-27 20:36:13.201  7172  7210 W MessageRetrievalService: Looping...
02-27 20:36:13.201  7172  7210 W MessageRetrievalService: Waiting for websocket state change....
02-27 20:36:13.202  7172  7210 W MessageRetrievalService: Network requirement: true, active activities: 0, push pending: 0, gcm disabled: false
02-27 20:36:13.478  7172  7211 W WebSocketConnection: onClosing()!...
02-27 20:36:13.478  7172  7211 W WebSocketConnection: onClose()...
^C

**Comment by johanw666** [comment]
If it barfed on one of the incomming media messages you might fix it by putting your phone in airplane mode, see if Signal runs and then remove the troublesome message.

**Comment by motatuc** [comment]
@johanw666, thanks for the suggestion. That unfortunately does not help. Signal also crashes in airplane mode.

**Comment by johanw666** [comment]
Do you have root on that device? If so, you could try to delete the last records in messages.db with a SqlLite editor, and then to be sure reset the encrypted sessions with the senders of those messages. Safest way would be to make a backup first, making a usable backup unfortunately also requires root at the moment.

**Comment by motatuc** [comment]
I do not have root on that device. But thanks for pointing out a possible solution to get the messages back. They are not really important to me so I'd rather have it fixed in Signals code instead. It seems that this issue is bad and has to be addressed.

**Comment by moxie0** [comment]
Looks like filesystem corruption.  Seems that a ROM bug trigger a phone crash, which messed up your disk.

**Comment by motatuc** [comment]
Hmm. Good question. The rest of the phone seems to behave pretty normal. If this is a problem with the disk then it seems to only affect Signal.

But does that mean there is nothing that can be done to solve the problem on Signals side? Like making Signal able to start anyways regardless of such problems?

If nothing can be done here, I will close the ticket then.

**Comment by motatuc** [comment]
Closing this because most likely the OS itself was the cause.

**Comment by iblech** [comment]
I also had this problem. I can confirm that it was due to data corruption: The files in the directory `files/signed_prekeys` are supposed to contain binary data. However, the file `13444806` contained some ASCII text (the path to some icon, unfortunately I didn't copy the string). Removing that file restored Signal, at the only expense that Signal wasn't able to properly decrypt two new messages from a particular contact.

Tinkering with `messages.db` (like removing the last few records of the `sms` table) did *not* affect the problem in any way.

**Comment by moxie0** [comment]
@iblech Interesting investigation, weird stuff. I've moved storage of all this into sqlcipher, which is in the latest beta. Hopefully that helps.
