### ISSUE TITLE
Unregistering is broken without Play Services

### ISSUE THREAD

**Issue by chrihu** [WhisperSystems/Signal-Android#6314]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
It is not possible to disable "Signal messages and calls" in advanced settings without Google Play Services.

### Steps to reproduce
- Open Signal
- Go to settings > advanced > toggle "Signal messages and calls" off > confirm dialog

**Actual result:** Unregistering fails
**Expected result:** Unregistering should not fail

### Device info

**Device:** LG Nexus 5
**Android version:** 7.1.1
**Signal version:** 3.30.3

### Link to debug log

<pre><code>PushServiceSocket: Push service URL: https://textsecure-service.whispersystems.org
PushServiceSocket: Opening URL: https://textsecure-service.whispersystems.org/v1/accounts/gcm/
AdvancedPreferenceFragment: 
AdvancedPreferenceFragment: org.thoughtcrime.redphone.signaling.UnauthorizedException: Failed to perform GCM operation: 401
AdvancedPreferenceFragment: 	at org.thoughtcrime.redphone.signaling.RedPhoneAccountManager.setGcmId(RedPhoneAccountManager.java:66)
AdvancedPreferenceFragment: 	at org.thoughtcrime.securesms.preferences.AdvancedPreferenceFragment$PushMessagingClickListener$DisablePushMessagesTask.doInBackground(AdvancedPreferenceFragment.java:232)
AdvancedPreferenceFragment: 	at org.thoughtcrime.securesms.preferences.AdvancedPreferenceFragment$PushMessagingClickListener$DisablePushMessagesTask.doInBackground(AdvancedPreferenceFragment.java:191)
AdvancedPreferenceFragment: 	at android.os.AsyncTask$2.call(AsyncTask.java:306)
AdvancedPreferenceFragment: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
AdvancedPreferenceFragment: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:244)
AdvancedPreferenceFragment: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
AdvancedPreferenceFragment: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
AdvancedPreferenceFragment: 	at java.lang.Thread.run(Thread.java:761)
InstanceID/Rpc: Failed to resolve REGISTER intent, falling back
InstanceID/Rpc: Both Google Play Services and legacy GSF package are missing
AdvancedPreferenceFragment: 
AdvancedPreferenceFragment: java.io.IOException: MISSING_INSTANCEID_SERVICE
AdvancedPreferenceFragment: 	at com.google.android.gms.iid.zzc.zza(Unknown Source)
AdvancedPreferenceFragment: 	at com.google.android.gms.iid.zzc.zzb(Unknown Source)
AdvancedPreferenceFragment: 	at com.google.android.gms.iid.zzc.zza(Unknown Source)
AdvancedPreferenceFragment: 	at com.google.android.gms.iid.InstanceID.zzb(Unknown Source)
AdvancedPreferenceFragment: 	at com.google.android.gms.iid.InstanceID.deleteInstanceID(Unknown Source)
AdvancedPreferenceFragment: 	at com.google.android.gms.gcm.GoogleCloudMessaging.unregister(Unknown Source)
AdvancedPreferenceFragment: 	at org.thoughtcrime.securesms.preferences.AdvancedPreferenceFragment$PushMessagingClickListener$DisablePushMessagesTask.doInBackground(AdvancedPreferenceFragment.java:237)
AdvancedPreferenceFragment: 	at org.thoughtcrime.securesms.preferences.AdvancedPreferenceFragment$PushMessagingClickListener$DisablePushMessagesTask.doInBackground(AdvancedPreferenceFragment.java:191)
AdvancedPreferenceFragment: 	at android.os.AsyncTask$2.call(AsyncTask.java:306)
AdvancedPreferenceFragment: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
AdvancedPreferenceFragment: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:244)
AdvancedPreferenceFragment: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
AdvancedPreferenceFragment: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
AdvancedPreferenceFragment: 	at java.lang.Thread.run(Thread.java:761) 
</code></pre>

**Comment by moxie0** [comment]
in 3.31.0
