### ISSUE TITLE
Feature request: Disable heads up notifications

### ISSUE THREAD

**Issue by koenhoeijmakers** [WhisperSystems/Signal-Android#6315]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

As is now it is impossible to disable heads-up notifications, to me, and many others, this isn't all that great as they are pretty obnoxious and they block out other parts of the screen when doing anything else than signal, ofcourse this is my opinion so an option to disable/enable them would be great.

**Comment by skulumani** [comment]
Which popup notifications are you referring to?

1. New message notifications? This can be disabled within the settings already
2. New contact notifications? A banner is shown when a contact in your address book is also on Signal. These can also be turned off in the settings?

**Comment by koenhoeijmakers** [comment]
Ah it seems that i made a mistake and that they're called Heads Up Notifications. [Android Developer Docs](https://developer.android.com/guide/topics/ui/notifiers/notifications.html#Heads-up)

**Comment by haffenloher** [comment]
How do other messaging apps do it? Show incoming calls as heads-up notifications and use normal notifications for messages?

**Comment by moxie0** [comment]
I don't think we have any control over this, we're just setting the notification to CATEGORY_MESSAGE, and Android is deciding to display it the way it is

**Comment by kdmillar** [comment]
It appears that this could be controlled by lowering the priority of the notification from PRIORITY_HIGH to PRIORITY_LOW. It would have to be tested because he docs aren't extremely clear. https://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder.html#setPriority(int)

**Comment by kdmillar** [comment]
The priority of the notifications is set to high:
 setPriority(NotificationCompat.PRIORITY_HIGH);
Creating an option to change the notification priority between PRIORITY_HIGH, PRIORITY_DEFAULT, and PRIORITY_LOW should allow for this functionality.

**Comment by moxie0** [comment]
Is there any other messenger app that does this? My recollection is that the documentation says messenger apps should use PRIORITY_HIGH.

**Comment by kdmillar** [comment]
Yes, Telegram has an option to select notification priority Default, High, or Max.
