### ISSUE TITLE
Feature Request: Let users choose between GCM PUSH and the new WEBSOCKET based notifying service  

### ISSUE THREAD

**Issue by soloclub** [WhisperSystems/Signal-Android#6327]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------
**Feature description**

Most of signal messages I send to my buddies only get delivered( or calls tried notified) when their signal app is opened. This was the case with me until I moved to AOSP  and with the new solution for non play services users, now the messages come in very swiftly even when the app is not in foreground.
All my buddies are on stock rom and I understand there may be issues with play services configuration etc.. But not everyone are geeks and everyone cannot move to AOSP for different reasons and not everyone can or wants to contact support with debug log when there are good alternatives for instant messaging already installed on their phones. 
So if the affected users have ability to choose between type of notifying services (GCM PUSH or the WEBSOCKET one), it would simply overcome the issues of no/sluggish notifications and message delivery.

**Comment by wizardofid** [comment]
Maybe this could be automated. Is there an API or an other possibility to check if a phone has GCM-connection? Then someone could implement an automatic fallback to WebSocket if GCM is missing. This way no additional setting would be necessary and all users with failing Push-notifications would benefit.

**Comment by KarolTrzeszczkowski** [comment]
https://support.whispersystems.org/hc/en-us/articles/218112597-Where-are-my-notifications-

Tell them to try this

**Comment by soloclub** [comment]
@KarolTrzeszczkowski 
Tried those workarounds, few of them like unregistering and registering helped but only temporarily. Once the network connection changed, message notifications were not going through until app is open. 
Sometimes I feel like GCM is sabotaging Signal app's penetration into masses. I wonder how it is working for rest of signal users!

@moxie0 
Kindly consider the feature request or provide with a concrete workaround/fix.

**Comment by tsdmgz** [comment]
Any details on your the phones? Xiaomi, Huawei, and ASUS devices (among others, noticed most with Chinese-based devices) are notorious for killing background apps in the name of battery savers/optimizers.

**Comment by haraldrudell** [comment]
This would be a good feature

It seems like as of Signal 3.31.4, Google Play services needs to be missing or disabled to use Websockets.

Here’s why the Websockets are beneficial:
Since 2015 it is a great idea to be on a Nexus/Pixel Android factory image, because that’s where the security updates are. These have effectively wiped out the cottage industry of custom roms.

Then, on the Google, people with privacy concerns are going to block everything, including Google Cloud Messaging. Therefore, it’s a great idea to not rely on GCM or Play Store or Services Framework. It appears both SMS and Call verification currently requires it for the beta build. The apk can be fished off a less secure rooted Android.

On the page where the phone number is input, there should be an ability to select the non-Google even if Play services are enabled

**Comment by strugee** [comment]
This doesn't seem like a good idea. The right answer is [never more options][options]. If the push-based approach is failing on some ROMs, we should focus on fixing that. As for the use-case for using a Nexus factory image but blocking Google Play Services, I don't buy it. Trying to mitigate something like Google Play Services that is _deeply_ integrated into the operating system is a fool's errand and will only lead to a false sense of security. Plus, trying to do so implies a rooted phone. Now, I have a rooted phone myself. But that does carry with it certain (unideal) security implications.

 [options]: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#development-ideology

**Comment by haraldrudell** [comment]
The app should never have used Google messaging in the first place. It seems that the Google happened because the project or contributors could not make anything else work properly. Anything else implies 24/7 servers and challenging engineering.

Stopping people from doing things is not the answer.

**Comment by haraldrudell** [comment]
As you can see, there are harassing 1-hour-old accounts discrediting targets on the Internet

Those are often from the violent organized crime syndicate “the people behind Zynga” engaged in robberies, burglaries and grand theft auto in San Francisco

There is a need for Signal

**Comment by soloclub** [comment]
At least creating a websocket connection every 30 minutes and checking with server for new messages would help for users with playservices issues.

**Comment by louisabraham** [comment]
Hi, what is the current status of this feature?
