### ISSUE TITLE
Noise Copperhead - Webrtc calls keep failing

### ISSUE THREAD

**Issue by roadkillazpartybird** [WhisperSystems/Signal-Android#6336]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Noise on Copperhead 5X. Attempts to call multiple contacts have failed multiple times. It just keeps 'pinging' for about 2 minutes then it gives up.

Before collecting the debug log i tried about half a dozen times to call another Signal user.

### Steps to reproduce
I'm not sure if it's reproducible, but here's what i did:

- Install Copperhead with Noise.
- Attempt to call a regular Signal user who is using GAPPS.

**Actual result:** Call fails, the 'ringing' never begins.
**Expected result:** Call goes through.

### Device info
**Device:** Nexus 5X
**Android version:** 7.1.1
**Signal version:** 3.30.04 (Noise)

### Link to debug log
https://gist.github.com/anonymous/0b44f0221c8bf8d73e88207d949b8af4

**Comment by moxie0** [comment]
Hey @roadkillazpartybird, sorry but this is a repository for Signal. We can't support other people's products, please contact whoever is responsible for "Noise."
