### ISSUE TITLE
Delete function inserts characters from earlier in the message

### ISSUE THREAD

**Issue by SwartzCr** [WhisperSystems/Signal-Android#6337]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I have entered text into a text message field and then want to delete a typo I press the delete key. At this point signal inserts a previous word from my message, appends it to the location below my cursor and deletes from it. This causes it to take about twice as long to delete any word, as it inserts a word on first delete press.

### Steps to reproduce
- Type a message
- hit delete
- notice that there are extra characters inserted that were not there before delete was pressed.

**Actual result:** A word from previously in the message is now before the cursor. (but with a letter deleted as a result of pressing delete) (the word is also still in its proper place in the message)
**Expected result:** The character before the cursor should be deleted.

### Device info

**Device:** Nexus 5
**Android version:** 6.0.1
**Signal version:** 3.30.4

**Comment by PiCob** [comment]
Something like this happened to me as well, but I guess it was related to the (stock) Android keyboard...

**Comment by McLoo** [comment]
Unless you don't get a previous message draft shown, this is very unlikely Signal's fault... 
Tried the stock  SMS App already?

**Comment by SwartzCr** [comment]
I tried typing in other apps and didn't have the same behavior, I didn't try with hangouts because when you open it it tries to become your default sms app again, so instead I tried gmail and the system input box.

**Comment by haffenloher** [comment]
Could you try using a different keyboard with Signal to see if it makes a difference?

**Comment by SwartzCr** [comment]
The problem mysteriously disappeared over the last few days. It may be that signal updated itself, but I don't remember updating. I'm going to close this as non-reproducible - but it can be re-opened when someone reports a similar thing

**Comment by mfb** [comment]
I've seen this too, usually Signal crashes shortly after it starts happening, and then works fine after I restart.  here's a crashlog: https://gist.github.com/anonymous/28f9b20af3715c2adaabff8cbb4aec57
