### ISSUE TITLE
"In-conversation notifications" setting doesn't really work as intended

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/Signal-Android#6339]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
My mom has a Moto G3 and she often leaves the screen on when she's in a conversation with me while she's watching TV or whatever. The problem is that while the phone always beeps when she gets a new message, the beep is often really quiet/short when the screen is on and she's already in a conversation with me. "In-conversation notifications" is enabled, which is why it beeps at all. However, it seems the message is marked as "read" too quickly, so the beep is interrupted. My mom is old and she just can't hear the beep which means she can't respond right away when I'm texting her at the supermarket or whatever.

### Steps to reproduce
1. Receive a message when your screen is on with the chat open, make sure "In-conversation notifications" is enabled in the settings
2. Most of the time the notification beep is really short, which makes it easy to miss

**Actual result:** The beep is seemingly interrupted
**Expected result:** The beep is fully played, just like you'd expect it to

### Device info
Moto G3
Latest non-beta Signal
Android 6.0.1

### Link to debug log
Don't think this is necessary, but if it is just tell me and I'll post one

**Comment by 2-4601** [comment]
Could not reproduce with Moto G4 Play, 6.0.1, Signal 3.30.0

**Comment by Dyras** [comment]
@2-4601 It doesn't happen 100% of the time. However, it happens often enough that it pisses me off.

**Comment by Dyras** [comment]
So after screwing around with the settings I've deduced this is caused by Moto Display. It also happens for K-9 so I doubt it's a Signal issue.

Never buying another Motorola phone again 😞
