### ISSUE TITLE
Trying to place calls between phones with Signal 3.31.0 -> no ringing

### ISSUE THREAD

**Issue by bl-kl2** [WhisperSystems/Signal-Android#6340]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Both devices have Signal 3.31.0.
Both devices re-registered, synced contacts, rebooted, after 3.31.0 update.
If I try to place a call from the Blackberry, all seems ok, I have the "DIALING" screen and sound,
but the other end (device Alcatel) doesnt ring.
After 20/30 seconds I abort the call on the Blackberry with the red "hangup" button; the other end (Alcatel) gives instantly a missed call notification.
Exactly the same happens when calling the Blackberry from the Alcatel.

### Steps to reproduce
- Call Alcatel from Blackberry, and viceversa.

**Actual result:** Call the other device, the other device doesnt ring.
**Expected result:** Call the other device, the other device rings.

### Device 1 info

**Device:** Blackberry Classic
**Android version:** 4.3
**Signal version:** 3.31.0

### Device 2 info

**Device:** Alcatel Pixi4 5010D
**Android version:** 6.0
**Signal version:** 3.31.0

### Link to debug log

Blackberry calling Alcatel:
http://gist.github.com/05c8bf579c2e551b9cc9619e948f23cf

Alcatel calling Blackberry doesnt give useful info, IMO, in the debug log:
http://gist.github.com/992da1527c45c58d5d0cd25ef4b3f62c

**Comment by moxie0** [comment]
Looks like your Blackberry device isn't generating any ICE candidates. I'm sorry but I don't think we can support non-Android devices like Blackberry.
