### ISSUE TITLE
Chrome Desktop app window will not open consistently for windows 10 

### ISSUE THREAD

**Issue by amazingandrogen** [WhisperSystems/Signal-Android#6341]
Debug logs: 
https://gist.github.com/a2c764a64dcd5c6b0b7cb297554d4c46

**Chrome Version** 56.0.2924.87 (64-bit)
I use multiple user profiles simultaneously to keep work and personal content separate. 
: installed extensions: 
Cisco WebEx Extension 1.0.8
Google Docs 0.9
Google Docs Offline 1.4
Google Sheets 1.1
Google Slides 0.9
LastPass: Free Password Manager 4.1.41
Signal Private Messenger 0.32.1
Tampermonkey 4.2.7

**OS version**: Windows 10 Enterprise Version 1607,  OS build 14393.693

**Behavior**: 
After upgrading from a windows 7 machine to windows 10, Signal has become unreliable. I see the message popup indicating I've gotten a new message, and about 80% of the time when I click the popup, my chrome instance is highlighted, but the signal instance does not appear.  

I've enabled, disabled, removed, re-added, re re re,moved , re re added etc a number of times with no change in behavior. 

Once I have the window open and working, it will continue to work as long as I do not close the window. once I close the window, it's anyone's guess whether it will come back again. 

Sometimes I have the signal icon showing in the control panel open programs list, where I have attempted to bookmark the signal icon so it is easily accessible: If I hover over the icon and I can see the program preview, signal will work as expected. If the icon will not show up, or hovering does not show the program  preview, there is literally nothing I can do to convince the window for signal to show itself. It is obviously running, because I still get the message alerts- but the actual message window can not be accessed. 

I attempted to go to the extension, and use the "create shortcut" option from the extension window. This will very occasionally work, but it's rare. the shortcut mainly gives me a "working" icon, and then does nothing.   

I can also go to the "view in store" and select "launch app" from the chrome store. Again, occasionally this will work, but almost never. mostly it just does nothing. 

I have been paying attention, but I can not find any  consistency for when it will work vs when it will not work. It does not seem more likely to work after a reboot or before, And I believe it has randomly started to work in the middle of a browser session (though I'm not 100% sure).  The only thing that Has changed about my configuration is the OS version, so I'm sure there is something environmental causing this- but I have not been able to narrow down what triggers the behavior. 

One more interesting thing I just discovered: It's more likely to work if I use one chorme profile than another.  when it fails to work, it always highlights the  shortcut to the chrome profile that works less often.  The extension shows as installed on both.   

Perhaps this is a strange side effect of windows 10 + profiles in chrome?

**Comment by FeuRenard** [comment]
Please post this issue in [Signal-Desktop's issue tracker](https://github.com/WhisperSystems/Signal-Desktop/issues).
