### ISSUE TITLE
Please tell user the directory/location of downloaded images/videos

### ISSUE THREAD

**Issue by lathspell** [WhisperSystems/Signal-Android#6349]
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal does not tell where it saves images and videos.
The directories /Pictures and /Movies are no bad choices but as e.g. the camera app only uses /DCIM for both, it's a bit annoying that one has to search.

### Steps to reproduce
save video or image

**Actual result:**
Message just says *"file successfully saved"* but not where.

**Expected result:**
Message says *"Image successfully saved in /Pictures"* (or similar)

### Device info
**Device:** Google Nexus 4
**Android version:** 7.1.1
**Signal version:** 3.30.4

**Comment by haffenloher** [comment]
I'd say this is tracked at #6164 (although that issue currently only mentions the "save all images" operation).
