### ISSUE TITLE
"Group updated." message still very confusing

### ISSUE THREAD

**Issue by vvug** [WhisperSystems/Signal-Android#6350]
We've got some improvements with group-related messages, thanks for that.

Still from time to time I get "Group updated." message in the group conversation. It's very confusing: who updated what? The string name is `GroupUtil_group_updated`, called just two times in `GroupUtil.java`. It should be changed in something more precise, like: "UserX changed the group name from X to Y". (It's just an example, maybe group name changes are already precise, the point is that I don't know what triggers the "Group updated" message!)

**Comment by cascheberg** [comment]
Duplicate of #6194. Also see #5416.

**Comment by vvug** [comment]
Duplicate issue.
