### ISSUE TITLE
Verification SMS and call name or description change critical

### ISSUE THREAD

**Issue by arunhappiest** [WhisperSystems/Signal-Android#6353]
### Bug description
Verification SMS and call name or description change critical

### Steps to reproduce
- using auth screen enter mobile number
- sms sent to  your cell says Your Signal Verification code:
- unable to chnge above signal to my id.

**Actual result:** unable to change signal to any other app name
**Expected result:** I want to rename signal to myapp --in Twilio sms and call for authentica

**Comment by moxie0** [comment]
if you're building your own app, you should be running your own server, which means you can change it to whatever you want

**Comment by arunhappiest** [comment]
Thanks Moxie0, You app is best, however can you provide me tech document how to setup server please? it will be of great help, you can mail me arunhappiest@gmail.com

**Comment by arunhappiest** [comment]
Hi,
please help...
It looks like there is no technical document for server setup, also no
redphone server code available, without these 2 this cannot be open source,
can you kindly help me please  y sharing doc to setup server of my own, his
will help a lot, i need how to setup server and configure in my project.
I WILL keep it confidential and agree with this again.

THANKS,
ARUN.N
