### ISSUE TITLE
Encrypted SMS/MMS without Data Connection

### ISSUE THREAD

**Issue by donfanning** [WhisperSystems/Signal-Android#6354]
[file this under Feature Request]
This would seem like a no-brainer but I guess it needs to be spelled out.  Once two people or a group has a shared key and all further communications are encrypted, if the person needs to turn off data for whatever reasons, they should be able to continue to send and receive *encrypted* texts and MMS.  

The application should be able to understand that a TCP connection is not available and thus either wrap the encrypted message in a MMS envelope or encrypt it into small <160 character blocks and send it via SMS.  Incoming messages should be parsed regularly and decrypted once a proper envelope appears.

There have been times people were caught off guard because they turned off their mobile data/wifi and missed out on important comms.  If the application knew to retry via SMS/MMS, then it wouldn't be an issue unless they had no service whatsoever then it would sit in a queue.  But it should always retry periodically via SMS/MMS until a data connection comes up.

**Comment by FeuRenard** [comment]
Here OWS explains why they dropped encrypted SMS/MMS:
https://whispersystems.org/blog/goodbye-encrypted-sms/

**Comment by donfanning** [comment]
Thanks @FeuRenard.  If support has been removed, then marketing and wording to the effect that it does _not_ encrypt SMS or MMS should be made.   While I understand the motivation of why and technical hurdles, there are solutions to every problem and I don't believe the direction to abandon a communication method that is fundamental to every device on the mobile network is a good strategy.

I will close this issue based on the announcement.
