### ISSUE TITLE
Video shared has no thumbnail

### ISSUE THREAD

**Issue by arunhappiest** [WhisperSystems/Signal-Android#6360]
Video shared has no thumbnail

### Bug description
video shared has no thumbnail
### Steps to reproduce
share a video to friend, difficult to identify as all videos has same icon rather than videos thumbnail pic.

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by moxie0** [comment]
I don't know what Android version you're running, since you left that out of the template, but this should be fixed on N+ devices. Unfortunately Android doesn't support an API that allows us to do that for earlier versions.  Please reopen if still a problem on N.

**Comment by FeuRenard** [comment]
> this should be fixed on N+ devices

It should also be fixed on M devices.
Source: https://github.com/WhisperSystems/Signal-Android/blob/85383054fae2d90eb90f20428062a6463446223d/src/org/thoughtcrime/securesms/database/AttachmentDatabase.java#L565

**Comment by moxie0** [comment]
hah, @FeuRenard is correct as always =)
