### ISSUE TITLE
Emojis in MMS group message are garbled.

### ISSUE THREAD

**Issue by ringw** [WhisperSystems/Signal-Android#6365]
Emojis in MMS show up as garbage characters, it seems like they aren't being interpreted as UTF-8. [Example](http://i.imgur.com/shy3jin.png)

**Comment by nrizzio** [comment]
Please follow the issue template and provide a debug log after receiving garbled MMS.

**Comment by 2-4601** [comment]
Closing in favor of #6374

**Comment by ringw** [comment]
Thanks--I haven't been able to capture a debug log from a message yet, and haven't figured out how to send myself an MMS to repro the issue.
