### ISSUE TITLE
No verification on register

### ISSUE THREAD

**Issue by Skarlett** [WhisperSystems/Signal-Android#6375]
I have:
- [ ] searched open and closed issues for duplicates
- [ ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

### Link to debug log

The register button stays grayed out and will not continue even though the information given is correct, this happens on new installment

**Comment by moxie0** [comment]
should be fixed in the 3.31.x release 3127fda7febc07213c3e7935e8e684b98f6803ab
