### ISSUE TITLE
Issue with recents screenshot

### ISSUE THREAD

**Issue by clviper** [WhisperSystems/Signal-Android#6376]
### Bug description
When using the power button of the device the FLAG_SECURE is ineffective and the screenshot appears with the information. This is actually a bug on Android platform and have been fixed only in versions above 7.x.

My goal with this issue is to understand if there may be implemented a workaround for earlier versions of android like change to a blank fragment during the onPause() or onStop() event.

In the API there is supposedly a function that would allow to generate a custom thumbnail but it's never triggered. I opened a ticket in Google regarding this but so far nobody assigned the ticket (https://code.google.com/p/android/issues/detail?id=235166)

### Steps to reproduce
- Navigate to a particular screen with information
- Press the power button of the device to lock the screen.
- Go to the recents list and confirm that the information is shown on the screenshot

### Screenshots

![screenshot_20170313-161425](https://cloud.githubusercontent.com/assets/4196178/23863867/c799ac08-0808-11e7-95a9-fcaab2a9e7de.png)

### Device info
**Device:** Nexus 5x
**Android version:** 6.0.1
**Signal version:** 3.30.4

**Comment by 2-4601** [comment]
An existing issue for this is here: #3172

**Comment by clviper** [comment]
@2-4601 I saw that existed that particular issue but it was closed just with platform bug. Isn't there a mitigation possible, to help protect users although this is a plataform bug?

**Comment by 2-4601** [comment]
Let's use the existing issue for finding a possible mitigation

**Comment by clviper** [comment]
Agreed @2-4601
