### ISSUE TITLE
Allow auto fallback from Signal message to SMS/MMS

### ISSUE THREAD

**Issue by Lenbok** [WhisperSystems/Signal-Android#6377]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Family uses Signal to communicate but Teenager has limited cellular data (e.g. used up monthly quota on YouTube). Other family members cannot send messages to Teenager in a timely fashion without knowing in advance whether Teenager currently has cellular data available.

### Steps to reproduce
- Attempt to send Signal message to Teenager
- Message is sent fine (one tick)
- Hours later, notice that Teenager has not replied, and message still has only one tick
- Manually send message via long-press SMS

**Actual result:** 
Teenager doesn't actually receive the message until it has been manually been sent via SMS

**Expected result:** 
An app setting should allow automatic fallback to SMS/MMS if the message has not been delivered to the recipient after N minutes. (Signal would ideally need a way to identify when two copies are received, one via SMS/MMS and one via Signal when cellular or Wifi permits the original message to arrive)

For many people, the encrypted nature of Signal messages is less important than a single, reliable messaging app, and these people are nonetheless important for growing the Signal user base.

(BTW, I found some old bugs about fallback if the senders internet is intermittent, but not the receivers)

**Comment by 2-4601** [comment]
This has come up many times before.
Closing as duplicate.
SMS fallback #678, #2847, #3074, #4009, #5001
SMS/Signal default transport mode #2285

**Comment by Lenbok** [comment]
Wow, you'd think this would have been resolved by now then! However:

#678 - Closed with no actual resolution
#2847 - Closed as a dup (i..e no resolution)
#3074 - Closed with no actual resolution
#4009 - Closed saying it's impossible (it's not, I just outlined one useful approach)
#5001 - Closed with an answer that actually just restated the problem (i.e. sender has to manually send again using SMS)

#2285 Does actually look marginally useful, as would the ability to flag particular users as "I always want to use SMS with this user"

**Comment by Trolldemorted** [comment]
@Lenbok are there really mobile data contracts that entirely *stop* the service if the monthly quota is consumed?

**Comment by Lenbok** [comment]
@Trolldemorted Yes, here in NZ it's common on prepay SIMs where you buy data in blocks (or as part of a monthly or weekly data/txt/voice combo, e.g. https://www.skinny.co.nz/pricing/combos/ ), and once the data in your block is gone you need to buy another. The prepay approach is very popular here, particularly with younger folk.

**Comment by moxie0** [comment]
Hey @Lenbok I think we've always considered this a "wontfix."  It would not be an easy change (requires that clients can recall messages in-flight from server), it has some really serious security implications (attacker just needs to DoS your message and they get plaintext), and is not a common case (only affects people with prepaid data plans or in areas where data is intermittent).

Doing something that requires major changes and is a fair amount of work, which would have the effect of reducing security, to solve a problem that is increasingly an edge case... is a tough sell.

**Comment by Trolldemorted** [comment]
I have seen those in stores, but i assumed they were only used by tourists. 9$ for 30mins, unlimited text and 100 MB appear ridiculously high to me - aren't low-end capped contracts a thing in NZ?

In europe you can get some hundred MB for 5€ (+ certain sum of sms/minutes) without impending extra fees. If you exceed your mobile data threshold your connection is throttled, sending/receiving images becomes a pain, but normal signal messages work like a charm.

**Comment by Lenbok** [comment]
@moxie0 I was thinking that security-wise it would always be opt-in that you would only enable for certain contacts, and rather than recalling messages in-flight from the server, potential duplicates would be resolved at the recipient end.  

That being said, maybe a much easier way of addressing the underlying problem of "does my message need to be sent via SMS instead of signal", is to support a "lack-of-delivery notification", where if a message was sent (one tick) but not delivered (two ticks) to the recipient after some timeout, a notification pops up for the sender asking if you want to send via SMS instead? That in conjunction with remembering the last used method for some duration ( #2285 ) would probably sufficiently deal with this frustrating problem.

@Trolldemorted Prepay is really common here, both because kids don't want to be tied in to contracts, and that the prepay deals are much more competitive than on-account since the barrier to switching providers is basically nonexistent. I would assume the situation is similar in Australia too, but haven't had much experience with other countries.

**Comment by moxie0** [comment]
I think "lack-of-delivery notification" is something I would consider much more readily than the auto-fallback.

**Comment by Trolldemorted** [comment]
@Lenbok since these prices are daylight robbery, i think the providers are thinking different:
The barrier to switch is nonexistent, so they crank up the prices because the customer is not bound to you for a longer period.

Are there really no decent cheaper deals in NZ?

**Comment by zacharycohn** [comment]
Strongly agree with [Lenbok's suggestion](https://github.com/WhisperSystems/Signal-Android/issues/6377#issuecomment-286632809) above to add a "notification after N minutes of non-delivery." 

It's a very poor user experience to leave it up to the user to double check to make sure their message was delivered. Especially when many people who haven't used Whatsapp aren't aware what the double check marks mean.

**Comment by cnighswonger** [comment]
It seems a bit less than obvious to me as to why Signal would not fall back to non-secure SMS/MMS when no data is available. The net result is to force users to switch default SMS apps and send the message anyway. After switching apps a few times, it is more convenient to stay with the non-secure app. It seems that at least making this optional would fill a blank for the time being.

It is quite frustrating to send a message and hours later realize it really did not send.
