### ISSUE TITLE
Support "Send location" feature

### ISSUE THREAD

**Issue by D4nte** [WhisperSystems/Signal-Android#638]
Hi,

This app is great and I'd love to replace normal sms and whatsapp with that. The only feature which is missing is the "Send location" feature. I know the first aim is to replace sms but I must say with such feature I could just throw away whatsapp :)

**Comment by mikeazo** [comment]
Looks like they are making progress on this 1a7ab6346f0c0306bfca098698a4a1b3b3edd18f

Not sure how much I like the thought of it though.

**Comment by generalmanager** [comment]
Well as long as it's privacy friendly (no google maps, TLS, etc.) and doesn't just randomly send your location to anyone this is certainly a feature users are looking for. If you don't like it you don't have to use it.

**Comment by turtlekiosk** [comment]
Maybe look at https://github.com/mapzen/LOST/ as a replacement for the closed source FusedLocationProviderApi that's in Google Play Services? I've heard Mapbox is considering/already using it in their raster tile Android SDK and their vector tile Android SDK.

**Comment by sedrubal** [comment]
:+1:

**Comment by ximex** [comment]
Could we change Form Google maps to OpenStreetMap?

**Comment by mcginty** [comment]
closing since it's in 3.9.0
