### ISSUE TITLE
Technical document/details missing for creating own server

### ISSUE THREAD

**Issue by arunhappiest** [WhisperSystems/Signal-Android#6383]
Technical document/details missing for creating own server, I am hobbiest and would like to explore own server rather than depending on others account so that I can fancy by making my own changes. couldnt see how we setup our own server.

one in below didnt help much:
https://github.com/skal1ozz/RedPhoneServer/blob/master/TextSecure-Server_Installation.txt

Thanks,
Arun.N

**Comment by moxie0** [comment]
Hey @arunhappiest this is the Signal android repository. Please do not file issues for other projects, questions, or submissions that do not follow the template.
