### ISSUE TITLE
Updated, now can't send/receive texts

### ISSUE THREAD

**Issue by wolff1066** [WhisperSystems/Signal-Android#6386]
I have:
- [ x] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

Signal was working properly all morning. I updated the app. Immediately I tried to text 3 times, got 3 "failed to send" notifications. A friend tried to text me and I never got it. Reset the secure connection, same result.

**Device:** samsung galaxy s5
**Android version:** 6.0.1
**Signal version:** 3.31.4

https://gist.github.com/c79662f63f943bcde78efddd49f497fb

Sorry if this isn't done right, I've never used github and don't know what I'm doing.

**Comment by moxie0** [comment]
Hey @wolff1066 the log shows that Signal is trying to connect to the service, but that there is a network problem.  So I'd check your network (try switching from wifi to data or vice-versa), reboot your device, put it in/out of airplane mode, etc.

**Comment by wolff1066** [comment]
After rebooting twice and then leaving my wifi it works. I guess it was my phone all along. Thanks. I really appreciate this product.

**Comment by moxie0** [comment]
Cool thanks for the update!
