### ISSUE TITLE
Signal texts keep waiting until attachment gets uploaded and sent. 

### ISSUE THREAD

**Issue by soloclub** [WhisperSystems/Signal-Android#6388]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------
**Bug description**
Newer signal messages typed and sent while attachment being uploaded keep waiting until attachment gets uploaded and sent .

**Steps to reproduce**
- Send an attachment to a contact.
- While attachment is uploading, try texting to same contact.

**Actual result:** Texts keep waiting until attachment gets uploaded and sent.
**Expected result:** Texts should be sent even while attachments are being uploaded.

**Device info**
**Device:** Nexus 5
**Android version:** 7.1.1 (No Gapps)
**Signal version:** 3.31.4

**Comment by moxie0** [comment]
Thanks but this is the intended behavior, we think message ordering is important. Receiving a message that references an image you haven't received yet would be confusing.

**Comment by soloclub** [comment]
Now that it is possible to send big files, I think allowing to text while attachment uploads is important. Particularly if you are on a slow connection and you are uploading some attachment and the other party texts you continuously and you cannot do anything but wait__.

**Comment by scienmind** [comment]
This suggestion does make sense. However, as Moxie mentioned ordering must be properly preserved. 

Some ideas:

Treat attachment internally as two messages: #1 small message - to notify the recipient's​ client; and #2 - the actual attachment.

When #1 received, the receiving end will display a "placeholder" message (with some "delivering" animation, which in turn will be replaced by the actual attachment once the transfer is finished.
(i think it may be reasonable for other media, not just "file attachments")
