### ISSUE TITLE
Storage Access

### ISSUE THREAD

**Issue by soloclub** [WhisperSystems/Signal-Android#6389]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

**Bug description**
Signal is able to access storage even after storage permission is disabled.

 **Steps to reproduce**
- Disable storage permission for Signal in Settings> app> permissions> storage
- Try to send an attachment to any signal contact

**Actual result:** Attachment selection and sending successful.
**Expected result:** Attachment should not be selected since storage permission is disabled. 

### Device info

**Device:** Nexus 5
**Android version:** 7.1.1
**Signal version:** 3.31.4

**Comment by moxie0** [comment]
Signal didn't access external storage, your gallery app did, which then handed the attachment to Signal. You would need to disable the gallery app's access to storage.

**Comment by soloclub** [comment]
@moxie0 Thanks, but this is not the case with other apps. Tried disabling storage permission to gallery, now gallery is not working but signal still is able to access storage(internal storage with UI similar to Settings> storage > explore)
