### ISSUE TITLE
CM 13 Signal Connectivity Error

### ISSUE THREAD

**Issue by meopo** [WhisperSystems/Signal-Android#6397]
### Bug description
I was using Signal SMS App for month until today. I wanted to write a SMS and suddenly i could not send any messages anymore. So i decided to reinstall the app but after reinstalling i could not even register. At the very beginning after you type in your phone number at signal i cannot get through step 1. After a while Signal shows me the message "Connectivity Error".. 
I already deinstalled Signal a couple of times and deleted the cache of every google app. Of course i also deleted the cache of signal but it will not work anymore.
I made two screenshots in Catlog wich i uploaded down below.

Device: Samsung Galaxy S5
Cyanogenmod 13 version:** 6.0.1
Signal version:** 3.31.4

![screenshot_20170315-220849](https://cloud.githubusercontent.com/assets/26444881/23971109/d76d6dca-09cc-11e7-801e-87f9a1743d51.png)

![screenshot_20170315-220907](https://cloud.githubusercontent.com/assets/26444881/23971110/d770832a-09cc-11e7-9974-cdcf51a27b75.png)

**Comment by meopo** [comment]
I have forgotten to ask. Can anybody watch over this and try to help me?

**Comment by moxie0** [comment]
pretty difficult to read those logs from those screenshots, but looks like a network exception to me. i'd recommend checking your network, rebooting your device, toggling from wifi to data, etc.

**Comment by meopo** [comment]
Okay. I tried toggling from data to wifi already. 
I first also thought it could be a network exception but i dont any app on my device wich is capable of doing such network rules. Is there any setting in CM 13 itself?

**Comment by moxie0** [comment]
I'm not sure, you'd have to as CM.  I'm going to close this since it doesn't look like a Signal issue and we don't use GH issues as a support channel, but feel free to ask on the community forums or support@whispersystems.org thanks
