### ISSUE TITLE
Foreground activities taking too much screen estate

### ISSUE THREAD

**Issue by vvug** [WhisperSystems/Signal-Android#6399]
When using Signal without gapps and with a passphrase two foreground activities are shown in the notification area: one for the "Background connection", the other just says "Signal is unlocked", and it's needed to cache the passphrase I guess.

These are taking a lot of screen estate. I'd suggest to join them in a single foreground activity.

**Comment by moxie0** [comment]
Thanks but I don't think we're going to do this, they function pretty independently.  The key caching service notification is marked as the lowest possible priority so you shouldn't usually see it on newer devices.
