### ISSUE TITLE
messages not sending

### ISSUE THREAD

**Issue by BMayneFactual** [WhisperSystems/Signal-Android#6402]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
no messages are being sent through. I'm assuming that this is just a dependency being down, but this seemed like the best way to report such an outage. 

### Steps to reproduce
- send any signal message

### Device info

**Device:** Google Pixel
**Android version:** 7.1.1
**Signal version:** Signal 3.31.4

however, this is affecting the users I'm talking to on iOS and galaxy s5

### Link to debug log

https://gist.github.com/anonymous/982aeb5c264f8844446c303b2e79debb#file-cat-log

**Comment by sidezr** [comment]
I am having the same problem with 3 different phones: Nexus 6, Nexus 6P and Nexus 5x. I uninstalled the app in one of them and now I cannot even register. I get message "Connectivity error" in step 1 of registration. I assume there is a service outage.

**Comment by Penumbra69** [comment]
I am having this issue as well, I can send only unsecured messages. All attempts to send secure messages failed - 2 phones, both having the same problem.  No first checkmark, almost immediate fail.

**Comment by FallenArchangel7** [comment]
I can confirm.  Problems with me and two other people.  None of us can use Signal at the moment.  We are all on Android, and I don't have an iPhone with me to test it.

**Comment by piethon1** [comment]
I'm having the same problem. I suddenly can't send messages (and don't think I can receive any either).  I'm on a Galaxy S6, and my friends (who can't do the same) are on iPhone and Android both.

**Comment by schmeat** [comment]
According to twitter, the down time has started at about an hour ago.

**Comment by crookedstorm** [comment]
Same here, and my wife is having the same issue right next to me suddenly.  Here is my debug log 
https://gist.github.com/395189e775928a58f29ebd7a64b61f99

**Comment by stidf** [comment]
Same issue here. It also effects my chrome web app as well. They report just being disconnected and won't connect. I uninstalled and reinstalled signal on my phone and now I can't even get past the registration page. 

https://gist.github.com/c6ca74e34268c28ae51a925de5b28c48

**Comment by waz452** [comment]
It could just be different devices creating different debug logs ... but having a look at a couple of the gists from above, the two below gists seem to be somewhat different ...  both are from the same device though.  probably just the way im reading it ... 

https://gist.github.com/anonymous/11054c62c0d6950ab94ca09bd07a3baf
https://gist.github.com/anonymous/7a4e1c075c465096a5995b5818f58f85

**Comment by liliakai** [comment]
Thanks everyone. We seem to be experiencing a server outage. No more logs are needed. Stand by for updates.

**Comment by FallenArchangel7** [comment]
@waz452 They are doing two different things.  One is registering, the other is sending a message.
The problem is the same on both. They try to access textsecure-service.whispersystems.org:443 and can't.

**Comment by crookedstorm** [comment]
I did suspect that, but I figured reporting is good. Good luck with the issue!

**Comment by Penumbra69** [comment]
:+1:

**Comment by waz452** [comment]
@liliakai @FallenArchangel7  -- Problem seems to be resolved now ... Messages are working again.

Thanks :)

**Comment by sidezr** [comment]
@waz452 I still can't register here. I keep getting the "Connectivity error" message. I got the confirmation SMS once, but the app got stuck and the error message showed up again.

**Comment by antonius66** [comment]
Getting same errors as well still

**Comment by 1024kbdotcodotnz** [comment]
I can connect, getting the SMS response but that's the end of it - a very quick fail from thrrdç8

**Comment by ironLambda** [comment]
I am still unable to reregister.

**Comment by odiggy** [comment]
Nothing connecting, sending​ or receiving. Uninstalled. Waiting.

**Comment by QantumEntangled** [comment]
Still having issues here, but in the future where should we look to see if there is a known issue?

Also is Signal down globally? Or are all Signal servers domestic US? For some reason I assumed VPNing to another country would utilize foreign servers, thus work. I guess not. Just wondering.

**Comment by kvedder** [comment]
Cannot send messages and tried to register again and cannot do that also. Nexus6P here.

**Comment by piratenpanda** [comment]
Why would you uninstall when the servers are down obviously?

**Comment by odiggy** [comment]
Ummmmmm. Maybe I did that before I along with everyone else knew the servers where down?

It's called due diligence. It's how I ended up here. But thanks for your comment.

Let me know when the servers are up Panda. Seems like you'll know before anyone else, yeah? Yeeeeeeeaah.

**Comment by ironLambda** [comment]
I too uninstalled as a troubleshooting step

**Comment by fat-tire** [comment]
This is yet another reason why federation is a necessity.  A single point of failure (at OWS) for a service this critical is dangerous.  Our threat model has changed and a building in a decentralized fallback is critical.

Just sayin'.

**Comment by odiggy** [comment]
Cuz you're smart^^^

**Comment by 1024kbdotcodotnz** [comment]
Why would you ask such a stupid question?

⁣
www.1024kb.co.nz​

**Comment by kvedder** [comment]
They need to stop relying on freaking Google.

**Comment by PiCob** [comment]
@liliakai: Could you imagine a possibility to let Signal somehow "show" (state) server outages in-app? Or is such a "feature" considered being a security problem?

**Comment by imwally** [comment]
@picob network status is available in the settings. At least on iOS.

**Comment by v6** [comment]
// , Some friends and I are having the same issue. It just caused some inconvenience for us.

**Comment by v6** [comment]
// , Resetting my secure session, updating Signal, and restarting my phone, in various orders, has not availed me.

**Comment by ironLambda** [comment]
@v6  Yeah, its not on your side

**Comment by QantumEntangled** [comment]
I noticed the error I got when trying to send a message didn't have any actual error code. Just "failed".
Maybe add an error code/message that indicates that the problem is communicating with the server.

That way I can at least spend a little less time checking my devices for rootkits & malware. But a centralized notification somewhere saying "Thar be problems. Sit tight" would be much more comforting than a GitHub issue post.

**Comment by v6** [comment]
// , OK. Calls fail too.

**Comment by cmayl0** [comment]
I frantically​ tried everything to fix the issue short of fully resetting my phone just to find out 1) it's down and 2) it's centralized?! There is no notification, no status, nothing at all to indicate that the problem isn't with my network or device. Seems like a huge oversight on an otherwise​ very well done app.

**Comment by sunaurus** [comment]
Does anyone know:
1) how many weak points the signal network has
2) are there plans to change the architecture to remove these weak points?

**Comment by liliakai** [comment]
Please don't start discussions here, as you'll spam everyone who is watching this thread. A better forum for discussion is the discussion forum: https://whispersystems.discoursehosting.net/
