### ISSUE TITLE
Unexpected end of stream on Connection when registering

### ISSUE THREAD

**Issue by sensiblepuffin** [WhisperSystems/Signal-Android#6403]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
When starting Signal fresh and registering device, the registration process hangs on the "Waiting for SMS verification" step and fails, citing a "Connectivity error".

**Actual result:** Registration fails
**Expected result:** I receive a text message and registration continues.

### Device 
Google Pixel XL
Android version: 7.1.1
Signal version: 3.31.4

### Link to debug log
https://gist.github.com/sensiblepuffin/33a2cd03f5e04376b07c3438fe0ebfca

**Comment by FallenArchangel7** [comment]
Probably the same as what's causing this: https://github.com/WhisperSystems/Signal-Android/issues/6402

Signal servers are unresponsive from the looks of it.

**Comment by sensiblepuffin** [comment]
Agreed, I tried again this morning and registration goes through now.
