### ISSUE TITLE
No signal-to-signal messaging

### ISSUE THREAD

**Issue by mrgtreeskier** [WhisperSystems/Signal-Android#6404]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal-to-signal messaging has stopped working about an hour ago, 2300 EST. Confirmed encrypted messages aren't sending or receiving via signal to individuals or groups. Also reset the secure session to test but did not fix.

I can receive regular SMS and data is connected.

### Steps to reproduce
- send encrypted SMS

**Actual result:** 
Signal tries to send and gives a not delivered failure message. Selecting the message for more info and pressing resend does the same thing.

Confirmed on group signal chat as well as to three individual chats.

**Expected result:** 
Encrypted SMS sent.

### Screenshots
None.

### Device info
**Device:** HTC ONE M7
**Android version:** 5.0.2
**Signal version:** 3.31.4

### Link to debug log
https://gist.github.com/4c646467ad228548d290c215eb810efd

**Comment by FallenArchangel7** [comment]
https://github.com/WhisperSystems/Signal-Android/issues/6402
https://github.com/WhisperSystems/Signal-Android/issues/6403
