### ISSUE TITLE
Phone doesn't ring on incoming call in locked state

### ISSUE THREAD

**Issue by tge-linee** [WhisperSystems/Signal-Android#6406]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
As someone else noted in https://whispersystems.discoursehosting.net/t/videocalling-withios-not-possible/876/6 my device sometimes doesn't ring when it is locked. If it is unlocked it allways works. Note that this is a redphone call, as described here: https://github.com/WhisperSystems/Signal-iOS/issues/1858

### Steps to reproduce
- lock the phone
- get a call

**Actual result:** Phone doesn't ring
**Expected result:** Phone should ring

### Device info

**Device:** Nexus 5X
**Android version:** 7.1.1
**Signal version:** 3.31.4

### Link to debug log

https://gist.github.com/dcab3736182311698178202cd0d61cea

I let it ring for about 15 seconds before unlocking the phone

**Comment by mykhi** [comment]
I experience the similar issue - when phone is locked it only rings for about half a second - then for whatever reason it switches to "voice speaker"; so you can't really hear it unless you put phone by the ear. 

Issue doesn't occur when unlocked.

S7 edge@ stock rooted Android 7.0

**Comment by chrihu** [comment]
@mykhi seems to be #6356

**Comment by mykhi** [comment]
@chrihu indeed - thanks, will post there.

**Comment by AboveMyPaygrade** [comment]
I seem to be having the same issue.  Texts will make a notification sound, as expected, but when a call comes in, I miss it entirely.  I got a debug log:  relevant lines are 30 and on, seemingly.  I received a call around 23:15, which I did not hear at all.

https://gist.github.com/anonymous/60df630cfdf1912d5bc2cce5da7d2639

#6356 seems to be different, as I don't recall hearing it through the earpiece.  It's also tagged with [webrtc], and I'm not sure if that's applicable one way or the other.

**Comment by renaudallard** [comment]
Here is a log
https://gist.github.com/anonymous/693a529497b9ee10ffd628732a538d13
