### ISSUE TITLE
Text Message appears 17 days later

### ISSUE THREAD

**Issue by halb9** [WhisperSystems/Signal-Android#6408]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Text Message appears 17 days later. 
This happened a couple of minutes ago. While chatting with a couple of friends via Signal Desktop, I noticed that in the taskbar it said "Signal (1)", implying a new message is there. But somehow it didn't show up. So I took my phone to have another look. Turns out I just received a message from Febr. 28th. 
How? oO
I managed to grab a debug log right after I read the text message on my phone. I am unable to obtain one from the other phone. It is probably useless anyways. 

### Steps to reproduce
- 

**Expected result:** Don't do that ;)

### Screenshots

![signal-2017-03-17-233458](https://cloud.githubusercontent.com/assets/18451020/24065635/91b5f43e-0b64-11e7-955d-8ceda1ff0168.png)

### Device info

**Device:** Samsung Galaxy S5
**Android version:** see log
**Signal version:** see log

### Link to debug log

https://gist.github.com/anonymous/f4d4a3da6e89aa4e7b1d7f4dc682cdb6

**Comment by moxie0** [comment]
Can you try to rephrase your issue? I don't think I understand your description, thanks.

**Comment by notthematrix** [comment]
I noticed some problems when sending text to australia from europe  and vide versa , in autralia it can be one day in the future from our perspective , so can that be the underlining issue?
Because it took very long before I got the messages... and she had my messages....

**Comment by halb9** [comment]
> Can you try to rephrase your issue? I don't think I understand your description, thanks.

I will do my best. 

> I noticed some problems when sending text to australia from europe and vide versa , in autralia it can be one day in the future from our perspective , so can that be the underlining issue?
Because it took very long before I got the messages... and she had my messages....

Pretty sure that's a different issue. 
Because 
1. my contact lives in germany as well. 
2. it would mean a timezone that differs by more than two weeks. 
I'm not astrophysicist, but I belive that is not the case on earth :)

Anyways.. Back to the real problem. 

---------------------------------

I've been using Signal-Android as well as Signal-Desktop without pretty much any major issues for the last couple of weeks. Yesterday the following happened: 

- 22:00: Chatting with multiple friends in Groups as well as direct contacts in Signal-Desktop. No problems. 
- At ~23:30 I noticed my Signal-Desktop Taskbar displayed a new message. 
![01signaltaskbar](https://cloud.githubusercontent.com/assets/18451020/24070338/78abc5a0-0bb3-11e7-9b6e-74ce37a25e9a.png)
But in Signal-Desktop all I can see are my previous chats. No new message. 
I tried to close and reopen the app. But the notification in the taskbar remains. 

- ~23:32: I took my phone to have another look. In Signal-Android the message was displayed as a new unread message. But the timestamp is from the 28th of february. 
- ~23:33: I took the debuglog and screenshot right after that. 

And since my conctact lives in another city and is not very tech-savy I am not really able to provide a debug log for that phone. Sorry. 

---------------------------------

Hope this makes it a bit more clear. Thanks for taking the time!

**Comment by halb9** [comment]
Oh boy. 
It seems like my conctact didn't update the app. Therefore the message for me was not send out. 
For whatever reason he decided to update yesterday. And voila... message went through. 

Sorry for the trouble! 

Maybe it is a good idea to let people know if a message is not send out due to outdated versions. 

Thanks anyways. Have a nice day.
