### ISSUE TITLE
audio calls from android ==> IOS keep using old protocol even after update!

### ISSUE THREAD

**Issue by notthematrix** [WhisperSystems/Signal-Android#6410]
<!-- This is a bug report template. By following the instructions below and filling out the sections with your i

I have:
- [x] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Android client can not detect if new (video) call protocol is active on IOS client...
so initiates the old protocal when calling to updated IOS client.
same problem appears  when making calls to IOS from android ver 4.4.4 and android ver 6.0.1   
IOS to android works fine... (new protocol is used and video is possible)

**Comment by notthematrix** [comment]
### Bug description
Android client can not detect if new (video) call protocol is active on IOS client...
so initiates the old protocal when calling to updated IOS client.
same problem appears  when making calls to IOS from android ver 4.4.4 and android ver 6.0.1   
IOS to android works fine... (new protocol is used and video is possible)

**Comment by moxie0** [comment]
Thanks @notthematrix , there was a bug in the initial Signal iOS that caused some users not to be registered as video capable. There was recently a Signal iOS update to fix that, but if your iOS device is running the absolute latest and it's still not working then can you file this over in the Signal-iOS repo? Thanks!

**Comment by notthematrix** [comment]
Tanx it seems it all updated tonight!! for some reason.
Btw the call quality is asome!
