### ISSUE TITLE
Old icon on "Signal is unlocked" notification (Signal 4.0)

### ISSUE THREAD

**Issue by KarolTrzeszczkowski** [WhisperSystems/Signal-Android#6412]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After latest update changing of Signal icon not all icons were changed. 
### Steps to reproduce
- Update Signal to version 4.0
- Type password to unlock Signal
- Check notifications

**Actual result:** The old icon on "Signal is unlocked" notification i
**Expected result:** There should be new icon

### Screenshots
![s70318-105007](https://cloud.githubusercontent.com/assets/11697819/24071085/a938f6f4-0bca-11e7-9c13-a3e71509201b.jpg)

### Device info

**Device:** Meizu m2 note
**Android version:** Flyme OS
**Signal version:** 4.0

**Comment by johanw666** [comment]
On my device (Sony Z3 compact) I don't see an app icon at all at that notification, only the lock icon. Ins't this something from the Meizu ROM? Does it work the same with other apps that change their icon?

**Comment by KarolTrzeszczkowski** [comment]
I have no idea how to check it. I don't remember any other app changing it's icon and having such a notification.

**Comment by cascheberg** [comment]
I had to restart my phone (Nexus 4, Android 5.1.1) to see the new icon. Did you try that?

**Comment by KarolTrzeszczkowski** [comment]
Yes, restart solves the problem. Icon was probably cached somewhere. So this is not an error. Thanks everybody!
