### ISSUE TITLE
timeout during unregistering without play services

### ISSUE THREAD

**Issue by karyon** [WhisperSystems/Signal-Android#6413]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When un-registering by tapping "signal messages and calls", it says "Error connecting to server".

I have a custom ROM based on cyanogenmod without play services, i installed signal from a backup made with titanium backup (using the "app + data" option). when the backup was made, play service were still installed. i had microG installed temporarily on the new rom, but have removed it in the meantime.

### Device info
Device  : samsung Galaxy Nexus (yakju)
Android : 6.0.1 (a83d380ef9, cm_maguro-userdebug 6.0.1 MOB31K a83d380ef9 test-keys)
Memory  : 22M (0.11% free, 256M max)
Memclass: 96
OS Host : cyanogenmod
App : Signal 4.0.0

### Link to debug log
https://gist.github.com/anonymous/3b43447bb25479a5b5ecef242bc82da7

besides the two exceptions, it also says "gcm disabled: false" which does not make sense to me.

**Comment by karyon** [comment]
my actual issue is that data messages arrive only after i open the app since i have no play services installed. i read somewhere that in order to use websockets, re-registering is necessary, so i wanted to do that.

**Comment by moxie0** [comment]
hey @karyon sorry but titanium backup isn't supported, it'll fuck up a ton of shit in addition to this

**Comment by karyon** [comment]
i exported all messages and re-installed the app. it asked me about missing play service and the battery optimizations and that stuff, and gcm_disabled is now true, so i guess everything is working now. thanks!
