### ISSUE TITLE
Safety number verification status should be stored and presented in UI

### ISSUE THREAD

**Issue by ageis** [WhisperSystems/Signal-Android#6416]
Feature request: if I've verified safety numbers with a contact of mine by scanning QR codes in person, then the fact that we have both verified each other should be presented somewhere in the UI (as a checkmark or something?) until their safety numbers change. There presently seems to be no other way to know that you've already verified with somebody except by memory.

**Comment by mateoeh** [comment]
See #910

**Comment by rainerzufall** [comment]
See also the pending PR https://github.com/WhisperSystems/Signal-Android/pull/6231

**Comment by ageis** [comment]
Thanks for referring me to the extant issues. Closing this.
