### ISSUE TITLE
Missing source code for libwebrtc-android

### ISSUE THREAD

**Issue by vvug** [WhisperSystems/Signal-Android#6420]
I hope this is not a silly question, but I can't find the source code for the libraries included in https://github.com/WhisperSystems/libwebrtc-android. I know that the upstream code comes from

https://chromium.googlesource.com/external/webrtc

but where is, for example, the code where https://github.com/WhisperSystems/libwebrtc-android/commit/e8c3d2f1b8e7e7f2d8cd1f6678905141f100ed22 was applied?

I asked the same question in that repository earlier today, but then the Issue Tracker has been closed without explanation :(

**Comment by moxie0** [comment]
Hey @vvug we don't use this issue tracker for discussion, Q&A, or support.  If you're looking for questions or discussion, the best place is the mailing list or the online forums. If you're looking for support, the best place is support@whispersystems.org.  Thanks!
