### ISSUE TITLE
Google Play Store Screenshots out of Date

### ISSUE THREAD

**Issue by wayloncovil** [WhisperSystems/Signal-Android#6427]
I have:
- [X ] searched open and closed issues for duplicates
- [ X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Google Play Store Screenshots are of TextSecure not Signal

### Steps to reproduce
Go to https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms and view screenshots.

**Actual result:** You see the out of date screenshot of TextSecure
**Expected result:** I would expect to see Screenshots of Signal.

### Device info
Any device.

**Comment by moxie0** [comment]
Thanks, we're aware. I'm going to close this since I don't think we need an issue to track it.
