### ISSUE TITLE
SMS Send Automatically I'm Worried :(

### ISSUE THREAD

**Issue by FaizKhan5** [WhisperSystems/Signal-Android#6430]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Tonight when i was sleeping my father sends me sms and that sms send again to him automatically after 2hours approx when i wake up and check phone same sms sends from me to my father and when i ask about it it shows sms that is in cipher text because my father use feature phone and on my signal app it is in plaintext is my mobile hacked or something else i'm worried :(

### Screenshots
![img_20170323_055737_740](https://cloud.githubusercontent.com/assets/26612909/24227493/3d04fc4e-0f8f-11e7-9a78-fc25fd97fb39.jpg)
![img_20170323_055823_646](https://cloud.githubusercontent.com/assets/26612909/24227494/3d1cdd82-0f8f-11e7-8c52-520bc18984b7.JPG)

### Device info
Device: Qmobile Noir i6 Metal One
Android version: 6.0
Signal version: 4.0.0

**Comment by FaizKhan5** [comment]
@moxie0 Is it Bug ?? My Mobile was not connected to wifi that time and SMS send back to father after approx 2 hour and i have dual SIM Mobile and message sends from one SIM Which have SMS Package That i use mostly

**Comment by Dyras** [comment]
Post a debug log if it happens again

**Comment by FaizKhan5** [comment]
Okay but this is the first time

**Comment by FaizKhan5** [comment]
I never see that issue again
