### ISSUE TITLE
When video enabled, speakerphone is enabled even if headset is on

### ISSUE THREAD

**Issue by FaizKhan5** [WhisperSystems/Signal-Android#6431]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Whenever i on my cam during call loudspeaker also on with it that issue is from 3.31.4 I think and couldnt fix and now in version 4.0.1 also  :(

### Steps to reproduce
When Touch Video Cam Opt Cam On

**Actual result:** 
When Touch Video Cam Opt Speaker Also On With Cam 

**Expected result:**
When Touch Video Cam Opt Cam On Only

### Device info
**Device:** Qmobile Noir i6 Metal One
**Android version:** 6.0
**Signal version:** 4.0.1

### Link to debug log
https;//gist.github.com/60f90810389990a2226ad5a0b9cd3306

**Comment by moxie0** [comment]
Thanks but this is the intended behavior

**Comment by FaizKhan5** [comment]
Why it is intended behavior sometime i forgot to off speaker when using handfree on video call and that is serious issue about privacy

**Comment by rustybird** [comment]
Ah I think @FaizKhan5 may be using a _wired_ headset? There's a bug causing Signal not to treat those the same as bluetooth. Here's [a bugfix](https://github.com/rustybird/Signal-Android/commit/60c21a5a6d73433eb2de2dbe4f3df9aeaf3b96cc), which [I'm not able to submit as a PR](https://whispersystems.discoursehosting.net/t/should-the-contributors-license-agreement-require-personal-info/735/6). Feel free to take it anyway @moxie0.

**Comment by FaizKhan5** [comment]
With or without handfree this issue occurs in so many versions after video call update

**Comment by rustybird** [comment]
@FaizKhan5: Yes, but without a headset it's sensible behavior, not a bug. It doesn't make much sense to transmit video from your front-facing camera while holding the phone (and therefore orienting the camera) towards your ear, which is almost certainly not interesting enough to warrant a live stream. ;)

The bug is that a wired headset doesn't behave the same as a bluetooth headset here.

**Comment by FaizKhan5** [comment]
Thanks but why the bug can't fix for wired headset 😟
