### ISSUE TITLE
Disable touch functionality while listening to a voice note through earpiece

### ISSUE THREAD

**Issue by EmilVogt** [WhisperSystems/Signal-Android#6437]
Thanks for improving the voice note feature. When raising the phone to the ear, voice notes are now played through the earpiece. Maybe it would be good now to also disable the touch functionality of the screen while one is listening to the voice note. Right now it can happen, that the ear is pressing buttons.

**Steps to reproduce:**
- start playback of voice note
- raise phone to ear
- listen to the voice note through the earpiece

**expected result:** during the playback through the earpiece touch functionality of screen is disabled
**actual result:** ear is accidentally pressing buttons on the touch screen

**Comment by jkdf2** [comment]
Agreed. Related to #6195 and 93e7a626bfd81282a4cab8e61aff376609e8ebea
