### ISSUE TITLE
Feature Request: User generated entropy for private key generation

### ISSUE THREAD

**Issue by sigenc** [WhisperSystems/Signal-Android#6440]
Let the user put some extra entropy like threema does for the long-term private key.

**Comment by nrizzio** [comment]
This would heavily mess up the install flow, and it's unnecessary because the app already applies [PRNG entropy fixes](https://github.com/WhisperSystems/Signal-Android/blob/master/src/org/thoughtcrime/securesms/crypto/PRNGFixes.java) at startup.

**Comment by sigenc** [comment]
Threema has the same fix. Even truecrypt used this. The only real entropy is Hardware.

**Comment by moxie0** [comment]
Thanks but we try to stay away from gimmicks
