### ISSUE TITLE
New message notification won't go away

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/Signal-Android#6450]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

I received a message today, and after reading it the "new message" notification stays there, even if I close and re-open Signal. It remains there even when I FC Signal and reopen it. It could be a duplicate of https://github.com/WhisperSystems/Signal-Android/issues/6270 but I'm unsure since I did nothing with the SMS database.

![signal-unread_message](https://cloud.githubusercontent.com/assets/8427572/24367653/b9af5c30-131d-11e7-9974-2aac6695f8fd.jpg)

Looking at the picture I see that the date is also off by one day in the future. The system date is correct.

### Device info

**Device:** Sony Z3 Compact
**Android version:** 6.0.1
**Signal version:** 4.1.0

### Link to debug log

https://gist.github.com/anonymous/0e1901bf5af253c3d7d4909844fa062d

**Comment by moxie0** [comment]
huh i thought there was a PR or a fix or something that based the unread indicator on message received rather than message sent time

**Comment by johanw666** [comment]
On 2nd thought, I might have been playing with the time when I received that message to enter a new level of a game (Criminal Case) that makes you wait (pay to move faster) to enter the next level but falls for the oldest trick in the book. When I move the date 1 day forward the message disappears. So probably user error after all, I'm closing the issue.

**Comment by McLoo** [comment]
Really sorry for the spam, but this made my day:
"I might have been playing with the time" :'-D
