### ISSUE TITLE
[Request] Android Tablets Support Idea

### ISSUE THREAD

**Issue by zero77** [WhisperSystems/Signal-Android#6453]
I know this is a duplicate of #614 but I am unable to post there, and I was wondering if this would be a feasible solution for the problem mentioned there.

Could you look at using the signal desktop repository as a combined android app repository specifically for tablets and other currently non supported devices.

I know this is possible in some circumstances because, DuckieTV (github.com/SchizoDuckie/DuckieTV) also use a single JavaScript repository, but they compile it for multiple OS like Android, Linux, Windows, OSX and a chrome add on. I think they do this with the help of AngularJS.
Thanks

**Comment by Lesik** [comment]
But the Signal app is not written in JavaScript? Also, enabling tablet support would be (theoretically) for the developer as easy as clicking one checkbox. Moxie hasn't replied to the original issue, but I'm quite sure it's not a technical issue but rather a "philosophical" one. It's not a technical limitation but he just doesn't want devices without SIM card to be able to download Signal from Google Play.

**Comment by johanw666** [comment]
Now that one can download an official apk from the website that can't be the only reason. Of course, activating might be more complicated but is still possible even without Titanium Backup hacks.

**Comment by sigenc** [comment]
Why wouldn't he want somebody donwloading Signal without a SIM Card? You can Register Signal with any SIP number.

**Comment by zero77** [comment]
Essentially what I am meaning is to use the signal desktop repository which is coded in JavaScript and maybe with the help of AngularJS compile an apk that can work on android tablets.

Because, another piece of software called DuckieTV (github.com/SchizoDuckie/DuckieTV) do this. They use one git repository for multiple OS like Android, Linux, Windows, OSX and a chrome add on and they just compile it into the necessary file formats like exe, apk, deb, pkg and a chrome add on.

Also, why wouldn't he want somebody downloading and using the Signal apk without a SIM Card?

**Comment by 2-4601** [comment]
Sounds like a topic for https://whispersystems.discoursehosting.net/
