### ISSUE TITLE
Feature Request: Signal as standard phone app

### ISSUE THREAD

**Issue by scroom** [WhisperSystems/Signal-Android#6466]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Description
Would be great if it would be possible to choose Signal as standard phone app (similar to the SMS functionality) -> if a contact one trying to call is using Signal the call would be made via Signal/the Internet and if not the call would be made via the mobile network.

**Comment by 2-4601** [comment]
Closing as duplicate of #6222
