### ISSUE TITLE
Images fail to attach

### ISSUE THREAD

**Issue by schmeat** [WhisperSystems/Signal-Android#6467]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Clicking on an image in the "gifs" page produces a toast error: "Sorry, there was an error setting your attachment"

### Steps to reproduce
- Click paperclip icon in chat
- Press "gif"
- Click on any gif

**Actual result:** Error toast displays, saying image cannot be attached
**Expected result:** Gif is attached in a message

### Screenshots
![signal-2017-03-31-204103](https://cloud.githubusercontent.com/assets/1139817/24573567/b15e1fb6-1652-11e7-890c-1787e51de07c.png)

### Device info
Device  : OnePlus ONEPLUS A3000 (OnePlus3)
Android : 7.1.1 (45, ONEPLUS A3000_28_170324)
Memory  : 48M (10.38% free, 512M max)
Memclass: 256
OS Host : ubuntu-55
App     : Signal 4.2.0

### Link to debug log

https://gist.github.com/anonymous/728e4f23bac0f30a3952db6a6dcfee44

**Comment by sweah82** [comment]
I get the same error message, when I try to add a picture attachement from camera. The quick camera button works.

Device: Samsung S5 mini 
Signal version: 4.2.1

https://gist.github.com/163aada85ab32ce8aa1f88b1a8b1da68

**Comment by Dyras** [comment]
I get the same error message while trying to add a picture from Google Photos.

Moto G4
Latest beta

Will post a debug log later today

**Comment by FeuRenard** [comment]
Can confirm that neither GIFs nor camera attachments work:
https://gist.github.com/c9e6e6a538218718257a583b78f71076

**Comment by aaroecker** [comment]
Gboard gifs also do not work.

Device: Nexus 6p

https://gist.github.com/b3bdf8670209e9cfd4d488c64b23e839

**Comment by PiCob** [comment]
Same here (Moto G4 Plus, Android 7.0 Stock); I've reduced the log to only cover the critical part:

04-02 08:26:10.723 24426 24426 W PassphraseRequiredActionBarActivity: onPause()
04-02 08:26:10.738 24426 24426 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
04-02 08:26:10.738 24426 24426 W KeyCachingService: Decrementing activity count...
04-02 08:26:10.738 24426 24426 W MessageRetrievalService: Active Count: 0
04-02 08:26:10.739 24426 24426 W ConversationActivity: onActivityResult called: 9, -1 , Intent { dat=file:///data/user/0/org.thoughtcrime.securesms/cache/image_manager_disk_cache/be21a13b0bc44dc3cd6142b8ce11e1aa7b6600bbe9e6044951d41c352dc934d6.0 }
04-02 08:26:10.744 24426 24426 W PassphraseRequiredActionBarActivity: onResume()
04-02 08:26:10.750 24426 24426 W ConversationActivity: onResume() Finished: 146190
04-02 08:26:10.768 24426 12913 W MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, subscription_id, expires_in, expire_started, notified, transport_type, attachment_id, unique_id, mid, data_size, file_name, _data, thumbnail, ct, cl, digest, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, notified, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS file_name, NULL AS _data, NULL AS thumbnail, NULL AS ct, NULL AS cl, NULL AS digest, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (read = 0 AND notified = 0) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, notified, network_failures, 'mms' AS transport_type, unique_id, mid, data_size, file_name, _data, thumbnail, ct, cl, digest, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (read = 0 AND notified = 0) ORDER BY date_received ASC)
04-02 08:26:10.785 24426 24426 W ConversationAdapter: Bind time: 3
04-02 08:26:10.789 24426 24426 W ConversationAdapter: Bind time: 2
04-02 08:26:10.791 24426 24426 W ConversationAdapter: Bind time: 1
04-02 08:26:10.794 24426 24426 W ConversationAdapter: Bind time: 2
04-02 08:26:10.797 24426 24426 W ConversationAdapter: Bind time: 1
04-02 08:26:10.806 24426 24426 W KeyCachingService: onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
04-02 08:26:10.806 24426 24426 W KeyCachingService: Incrementing activity count...
04-02 08:26:10.807 24426 24426 W MessageRetrievalService: Active Count: 1
04-02 08:26:10.830 24426 24426 W ConversationAdapter: Bind time: 2
04-02 08:26:10.930 24426 24426 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
04-02 08:26:11.147 24426 24426 W PassphraseRequiredActionBarActivity: onDestroy()

**Comment by Dyras** [comment]
I can't attach pictures at all anymore. However, I can take pictures using the in-app camera
https://gist.github.com/anonymous/9d492b21d053cd5e1db9aaafb7ac93ea
https://gist.github.com/anonymous/1c7d8f95eb5d2a0da1902aa6eb602274
