### ISSUE TITLE
Downloading video keeps spinning forever on Moto G3

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/Signal-Android#6470]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Sometimes when I send a video to my mother's Moto G3, the video either
1. Just sits there spinning
2. Starts loading and then halfway through it goes back to spinning again

I have no idea why this happens, the phone has plenty of free memory and the delete timer is set to 1 day so the chat isn't bloated at all. This has been happening for several months now and it's getting really annoying.

### Steps to reproduce
1. Receive a video (It doesn't happen every time)
2. Wait for it to finish loading...
3. Oh wait! It never does!
4. Restart the device
5. It now works just fine

**Actual result:** Videos get stuck downloading until a restart
**Expected result:** Videos should never get stuck

### Device info
Device  : motorola MotoG3 (osprey_reteu)
Android : 6.0.1 (2, MPIS24.107-55-2-5)
Memory  : 31M (14.53% free, 256M max)
Memclass: 96, low-mem device
OS Host : ilclbld36
App     : Signal 3.30.4

In the most recent debug log below:
App     : Signal 4.1.0

### Link to debug log
https://gist.github.com/anonymous/494993a950189778dc6e6d7f469d1e58
https://gist.github.com/anonymous/0c21e2e84df4dcc8a7a3ecb3af8a34b7

**Comment by 2-4601** [comment]
Could be duplicate of #6004

**Comment by Dyras** [comment]
@2-4601 Not sure, because for me it always works after I restart my device. No mentioning of that anywhere in issue #6004

**Comment by 2-4601** [comment]
The few times I've run into this with pics the issue has sorted itself after a reboot (or after some other undefined period of time).

**Comment by Dyras** [comment]
Guess it's a duplicate then! Sniff sniff..
