### ISSUE TITLE
notifications aren't muted while call is active

### ISSUE THREAD

**Issue by SimJoSt** [WhisperSystems/Signal-Android#6471]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- initate call
- wait until call is active

**Actual result:** notifications still play sounds / aren't muted
**Expected result:** notifications should be muted and not scream in your ear

### Device info

**Device:** Zuk Z1
**Android version:** 5.1.1
**Signal version:** 4.1.0

### Link to debug log

No debug log at the moment, as I do not have the tools and environment to reproduce the bug.
If this is declared abnormal behaviour I will gladly supply it at a later point. If this is normal behaviour I would recommend to change it, like with normal calling.

**Comment by wno-git** [comment]
Seems related to #4318

**Comment by SimJoSt** [comment]
You are right. Thanks.
duplicate of #4318
