### ISSUE TITLE
Lost Signal Messages after Update

### ISSUE THREAD

**Issue by randium** [WhisperSystems/Signal-Android#6472]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
Updated to Signal 4.1.0, had to reauthenticate via SMS.  Once that was complete, it seems that all my Signal history is gone:  Photos, chats, everything.  SMS is still there but I can't find any Signal messages.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

- Impossible to reproduce as I can't reinstall the update and the chats appear to be gone.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

- I should have my freakin' Signal chat history!

### Device info

**Device:** Samsung Galaxy S2 I9100
**Android version:** 4.0.3 
**Signal version:** 4.1.0

### Link to debug log

https;//GIST.GITHUB.COM/56F0921FC61DBDC6FE0B1F443F538180

**Comment by Dyras** [comment]
Someone else already reported this
https://github.com/WhisperSystems/Signal-Android/issues/6441#issuecomment-289297306

**Comment by randium** [comment]
Nope.  Please see my recent comment.  There was a problem with this update
and you're refusing to look at it.
