### ISSUE TITLE
Signal apk download does not match published fingerprint

### ISSUE THREAD

**Issue by mitar** [WhisperSystems/Signal-Android#6478]
I tried downloading the officially published [apk](https://signal.org/android/apk/), but fingerprint does not match. I tried using various browsers and asked a friend to try as well. So I think I am not under an attack.

I downloaded `Signal-website-release-4.1.0.apk` and the SHA256 fingerprint I get is:

```
d7accd1465968607e4df3112c39bfc98eb0674c3a9cb4146a47d935d871e84f6
```

I used `shasum -a 256 Signal-website-release-4.1.0.apk`.

On the website it is written that the fingerprint should be:

```
29:F3:4E:5F:27:F2:11:B4:24:BC:5B:F9:D6:71:62:C0
EA:FB:A2:DA:35:AF:35:C1:64:16:FC:44:62:76:BA:26
```

**Comment by nrizzio** [comment]
To get the fingerprint, use the `keytool` command like so:

```
nicholas@ubuntu:~/Downloads $ keytool -list -printcert -jarfile Signal-website-release-4.1.0.apk 
Signer #1:

Signature:

Owner: CN=Whisper Systems, OU=Research and Development, O=Whisper Systems, L=Pittsburgh, ST=PA, C=US
Issuer: CN=Whisper Systems, OU=Research and Development, O=Whisper Systems, L=Pittsburgh, ST=PA, C=US
Serial number: 4bfbebba
Valid from: Tue May 25 11:24:42 EDT 2010 until: Tue May 16 11:24:42 EDT 2045
Certificate fingerprints:
	 MD5:  D9:0D:B3:64:E3:2F:A3:A7:BD:A4:C2:90:FB:65:E3:10
	 SHA1: 45:98:9D:C9:AD:87:28:C2:AA:9A:82:FA:55:50:3E:34:A8:87:93:74
	 SHA256: 29:F3:4E:5F:27:F2:11:B4:24:BC:5B:F9:D6:71:62:C0:EA:FB:A2:DA:35:AF:35:C1:64:16:FC:44:62:76:BA:26
	 Signature algorithm name: SHA1withRSA
	 Version: 3
```

It would probably be a good idea for Moxie to add a little blurb at the bottom of the page that shows you how to get the fingerprint manually.

**Comment by mitar** [comment]
Oh, I didn't read this well. It is a fingerprint of the signing certificate. Not the apk.
