### ISSUE TITLE
Upgrade path from custom build to offical Signal apk

### ISSUE THREAD

**Issue by mitar** [WhisperSystems/Signal-Android#6483]
I have been using custom builds of Signal apk on my Google-less Android (so I could not use Google Play). I want to switch to [official build](https://signal.org/android/apk/) but it simply upgrading does not work:

```
$ adb install -r Signal-website-release-4.1.0.apk 
[100%] /data/local/tmp/Signal-website-release-4.1.0.apk
	pkg: /data/local/tmp/Signal-website-release-4.1.0.apk
Failure [INSTALL_PARSE_FAILED_INCONSISTENT_CERTIFICATES]
```

It would be great if there would be an easy way to upgrade, or at least a documented way to do it.

**Comment by moxie0** [comment]
There might be some way if you have a rooted device, but by default the Android package manager isn't going to let you install an APK with a different signature over an existing install.

**Comment by carrott** [comment]
You just have to do a backup, uninstall, install the official APK and restore the backup. I expect a backup app will do the file ownership and SELinux dance for you but I hand cranked it without installing a backup app. I wrote the following based on moving from one phone to another, I've slightly re-written what I did to work on one phone hopefully I didn't introduce any bugs:

1. Check Signal is running

        # ps | grep thought
        u0_a82    3206  224   1703088 83144 sys_epoll_ b5ece054 S org.thoughtcrime.securesms
        #

1. Force Stop signal in the Apps list of Settings
1. Check Signal _is not_ running

        # ps | grep thought
        #

1. Make a backup, _note this puts an unencrypted copy of your signal database on your sdcard_

        cd /data/data
        tar -czf /mnt/sdcard/org.thoughtcrime.securesms.tar.gz org.thoughtcrime.securesms


1. Move the existing data directory so uninstalling doesn't delete it. If you're moving phones, you'd skip this step so you don't modify your old phone.

        mv /data/data/org.thoughtcrime.securesms /data/data/org.thoughtcrime.securesms_old

1. Uninstall your custom Signal
1. Install the official Signal APK
1. Check Signal hasn't started (force stop it if it has)

        # ps | grep thought
        #

1. Move the new signal data directory out of the way and put the old one back. If you were moving phones you'd restore your backup here after moving the new directory.

        # mv /data/data/org.thoughtcrime.securesms /data/data/org.thoughtcrime.securesms_new
        # mv /data/data/org.thoughtcrime.securesms_old /data/data/org.thoughtcrime.securesms

1. Check which uid & gid the new Signal has and update old directory. Here, the old signal had u0_a82 and the new signal had u0_a67

        # ls -l /data/data | grep org.thoughtcrime.securesms
        drwxr-x--x 11 u0_a82    u0_a82    4096 2017-05-28 14:16 org.thoughtcrime.securesms
        drwxr-x--x  4 u0_a67    u0_a67    4096 2017-05-28 14:15 org.thoughtcrime.securesms_new
        # chown -R u0_a67:u0_a67 /data/data/org.thoughtcrime.securesms

1. If you're restoring from a naïve tar.gz backup you'll also have to fix up the
SELinux context:

        # ls -Z /data/data | grep org.thoughtcrime.securesms                               
        u:object_r:system_data_file:s0        org.thoughtcrime.securesms
        u:object_r:app_data_file:s0:c512,c768 org.thoughtcrime.securesms_new
        # chcon -R -h u:object_r:app_data_file:s0:c512,c768 /data/data/org.thoughtcrime.securesms

1. Start Signal and check that your messages and keys are present in the new app
