### ISSUE TITLE
Failed Sending Message Behind Wifi/Firewall

### ISSUE THREAD

**Issue by aaroecker** [WhisperSystems/Signal-Android#6486]
Bug description
Data Signal messages fail to send while behind work wifi/firewall.

Attempt to send message fails and returns "failed to deliver message" error.

Device info
**Device:** Huawei Nexus 6P
**Android version:** 7.1.1
**Signal version:** 4.2.2

Link to debug log
https://gist.github.com/anonymous/46bfca09bb1cf6aa2d8dff5ef5f06c4d

**Comment by aaroecker** [comment]
Is there a way to alter the ports used by Signal so that data can be received?  A fallback port?

**Comment by moxie0** [comment]
it's just 443, pretty standard

**Comment by aaroecker** [comment]
Hmmm, I wonder what the hang up is then.
