### ISSUE TITLE
Signal incompatibility with NetGuard

### ISSUE THREAD

**Issue by marshmat** [WhisperSystems/Signal-Android#6487]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal is unable to send or receive messages over an LTE / 3G connection if NetGuard is active simultaneously on the device.
This behaviour persists even if Signal is given full access to both WiFi and cellular connections in NetGuard.
This behaviour is unique to cellular data connections. Signal works properly on WiFi while NetGuard is active.

It is not yet clear whether the problem is in Signal or in NetGuard. If it turns out to be the latter, then a help / faq page saying "NetGuard breaks Signal, there's just no way to make it work, here are alternatives / workarounds" would be a good idea.

Running without NetGuard or a similarly capable alternative is not a workaround, as that would permit other apps to quickly gobble up mobile data (which, in this case, is expensive and in extremely limited supply).

### Steps to reproduce
Debug log attached, generated as follows:
- While an active WiFi connection is present, close and then start Signal.
- Verify that NetGuard is set normally (firewall is on, Signal has full access for both WiFi and cellular modes).
- Move outside the range of the WiFi connection. Device automatically switches to LTE connection.
- Attempt to send a plain text message in Signal.
      **Actual result:** Get a "failed to send message" error.
      **Expected result:** Message is sent, shows 1 checkbox (sent), shortly thereafter shows 2 checkboxes (received).
- Turn off NetGuard entirely.
- Try sending the message again in signal.
      **Actual result:** Message is sent correctly.
      **Expected result:** No change.
- Re-enable NetGuard and move back into WiFi range.
     **Actual result:** Signal works normally.

### Device info
**Device:** LGE Nexus 5 (hammerhead)
**Android version:** 6.0.1
**Signal version:** 4.1.0

### Link to debug log
https://gist.github.com/anonymous/d9a7d59b0737474aec9191101ee182a5

**Comment by moxie0** [comment]
Hey @marshmat I have no idea what netguard is, but we're just making normal network connections. If there's something on your device that's blocking those connections (as this log would indicate), there's nothing we can do.

**Comment by bungabunga** [comment]
netguard is a "firewall" for devicess that are not rooted. it works as a vpn.

**Comment by marshmat** [comment]
So it's probably a Netguard bug, not a Signal bug. Will re-file in their bug tracker.
Good to know.
