### ISSUE TITLE
No names shown for contacts, only numbers

### ISSUE THREAD

**Issue by retsifp** [WhisperSystems/Signal-Android#6494]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
For some days now (also before the latest update), my Signal lost all names of my contacts. I still see the conversations and everything else is working fine, but my contacts only show numbers instead of names. Going to the "pencil" menu and refresh there didn't change anything, it just found some contacts which have Signal now their name is shown correctly, but my old contacts still show only numbers... :/
Clearing the cache of the App didn't change anything, and I didn't change anything with the contacts. And they work in other apps like the phone app.

### Steps to reproduce
- open Signal
- look at recent conversations
**Actual result:** contacts are shown with their numbers
**Expected result:** contacts should have their name

### Device info

**Device:** Fairphone FP2
**Android version:** 6.0.1
**Signal version:** 4.2.4

### Link to debug log
https://gist.github.com/anonymous/7bc47d27f0169aafec27e88ba46f7f89
(Shows A LOT of output, I hope there is some useful information inside... :wink:)

**Comment by moxie0** [comment]
Did you revoke contacts permission?

**Comment by retsifp** [comment]
Yep, I tried to revoke the permission and give it back; didn't change anything. Now it has the permission again.

**Comment by retsifp** [comment]
I found now that the update from 5.1 to 6.0 somehow crashed the contact list. Some of them existed twice, but with the number as name. So this is why Signal showed only numbers.
I deleted all contacts on my sync server and fetched them from a backup, now everything works well again.

Sorry for irritating you! 😉
