### ISSUE TITLE
Thank you for the great work you are doing! 

### ISSUE THREAD

**Issue by kepler2** [WhisperSystems/Signal-Android#6498]

**Comment by janvlug** [comment]
@kepler2 Thanks for sharing your appreciation. I fully agree. Please note that this is an issue tracker. Could you please close this issue to save the developers some work?
The informal community forum at https://whispersystems.discoursehosting.net/ would be a good place to host a 'thank you' topic.

**Comment by kepler2** [comment]
Sure.
