### ISSUE TITLE
New iOS smileys are not shown on Android

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/Signal-Android#6501]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
An update of iOS brought new smileys. If a Signal-iOS users uses these in a Signal conversation with an Android user, the Android app shows only crossed rectangles.

### Steps to reproduce
- Send a message with the new smileys from Signal-iOS to Signal-Android
- Open the message on Android

**Actual result:** The Android screen shows crossed rectangles where there are smileys that are not known to the Android app.
**Expected result:** The app should display the correct smileys.

### Screenshots

iOS screenshot:

![signal-ios-2017-04-06-143545](https://cloud.githubusercontent.com/assets/8427572/24757944/0a93ec2c-1ae1-11e7-9edd-7f6184fc0b4d.jpg)

Android screenshot:

![signal-android_20170406-150149](https://cloud.githubusercontent.com/assets/8427572/24757956/194498e8-1ae1-11e7-8545-5b0d85f54cc5.jpg)

### Device info

**Device 1:** Sony Xperia Z1 Compact
**Android version:** 6.0.1
**Signal version:** 4.2.4

**Device 2:** Apple iPhone 5s
**Android version:** unknown (some 10.x version, can ask if required)
**Signal version:** unknown (can check out later if required)

### Link to debug log
No debug log.

**Comment by johanw666** [comment]
I just did a test with a Sony Z1 Compact device running Android 4.4.4, it will show empty space instead of a crossed-out rectangle for smileys it does not know.

**Comment by 2-4601** [comment]
Emojis need updating which is tracked at #4279.
