### ISSUE TITLE
Switch to noise pipes for transport instead of ssl

### ISSUE THREAD

**Issue by sigenc** [WhisperSystems/Signal-Android#6512]
[https://whispersystems.discoursehosting.net/t/is-signal-use-noiseprotocol-for-transfering-receiving-data/378](url)

**Comment by moxie0** [comment]
Thanks but it's unlikely. I'm going to close because it's not something we need an issue to track.

**Comment by sigenc** [comment]
I know you don't like github as a discussion forum. But it seems nearly impossible to get an answer from you on the forum. I'm sorry for the ignorance. I don't have as much knownledge as you and i don't have as much todo as you. But there is something i noticed in alot of people in the open source community lately. You are all stressed to the point where it seems that you're becoming arrogant and i know it is just the lack of time and no bad behavior. A simple 2 liner why it is unlikely would have been enough to prevent me from writing in this issue again. I'm sorry that i don't come up with the answer myself, maybe if i have your knownledge i would understand your statement. I still hope the security of your users is as important to you as it was when you started this project. 

peace

**Comment by moxie0** [comment]
Yep, I'm really sorry I don't have more time to communicate. I'm the only maintainer for this repository, so unfortunately giving every query the response it deserves would be my full day every day.

I don't think it's possible to express in a 2 liner.  There is a lot of infrastructure for TLS. Every component of our stack, from ELB to nginx to haproxy to jetty is prepared to terminate TLS. Nothing is prepared to terminate Noise. We have a very small team, so we often make leveraged choices, but using Noise as a transport would not allow us to do that. It would prevent us from ever using ELB, Lambda, GAE, EBS, etc and would mean that we'd always have to build our own.

This is, in large part, why TLS is what people use.  So long as GAE, ELB, Lambda, and all the cloud infrastructure providers support TLS and not Noise Pipes, I think we're unlikely to see anyone using Noise Pipes outside of the really big players with really large dedicated infrastructure teams who are already managing their own hardware and services -- and even then probably not so much.
