### ISSUE TITLE
Bug: blocked contact sees message as "delivered" (two check marks)

### ISSUE THREAD

**Issue by itmaciek** [WhisperSystems/Signal-Android#6515]
I have:
- [ ] searched open and closed issues for duplicates
- [ ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Blocked contact sees message as "delivered" (two check marks).

### Steps to reproduce
- Phone A: block contact Phone B
- Phone B: send text to contact Phone A
- Phone B: sees message as "delivered" (two check marks).
- Phone A: not seeing any messages

**Actual result:** Blocked contact sees his messages as delivered
**Expected result:** Messages on Phone B (blocked contact) should have only single check mark. As described on:
https://support.whispersystems.org/hc/en-us/articles/212535538-How-do-I-know-if-a-message-has-been-delivered-

### Device info

**Device:** Nexus 5X
**Android version:** 7.2.1
**Signal version:** 4.2.4

**Comment by nrizzio** [comment]
What's happening here is that the message is delivered but is being immediately discarded client-side. The way it currently stands, there's no indication of being blocked, which I presume is what OWS would like to have.

**Comment by moxie0** [comment]
Yep we went back and forth on this initially, and eventually decided it'd be better if there were no indication to the sender that they're blocked.

**Comment by Levente0xFFFF** [comment]
I think this is a terrible decision. If the sender is able to communicate with you at a later time, you cannot plausible deny that you haven't received the messages. If you say that you have uninstalled Signal this is why you haven't seen what they wrote then they will say that the message has been delivered (double ticks) so you should have seen it.

On the other way, if they would see only 1 tick, you could tell that your Signal install is broken, app crashes all the time, network issues, you have uninstalled the app, etc.

With this decision you have caused that the other party figured out that I have blocked them, which was the opposite of your goals: "it'd be better if there were no indication to the sender that they're blocked."
