### ISSUE TITLE
Error playing video 

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-Android#6518]
I have:
- [X] searched open and closed issues for duplicates, this may be a duplicate of #6263 as logs in this issue also contain `MediaPlayer: error (1, -2147483648)` but that issue is for voice notes only or duplicate of https://github.com/WhisperSystems/Signal-Android/issues/6214 based on title solely (not logs)
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal video messages sent or received do not play but show the error "This video can't be played." Some users can still save the video and play it outside of Signal.

### Steps to reproduce
- send/receive video message to/from another Signal user
- try to play message

**Actual result:** "This video can't be played" alert
**Expected result:** Video plays

### Screenshots
N/A

### Device 1 info

**Device:** Samsung Galaxy S5
**Android version:** 6.0.1
**Signal version:** Signal 4.2.4

### Device 2 info

**Device:** Motorola Moto X Pure
**Android version:** 6.0
**Signal version:** Signal 4.2.4

### Link to debug log

Device 1 log: https://gist.github.com/fd8b475e439a320f3f0db1eda147c882
Device 2 log: https://gist.github.com/d2374f0ba0ebdb1cd23ce38756092ab1
Device 3 log: https://gist.github.com/9bead1cc13f0c982752934f4e0869cf6
EDIT: added logs only

**Comment by notthematrix** [comment]
same problem. also detected in android 6.0 but no logs yet.
https://gist.github.com/anonymous/489dca905e1b38014b8a35df9e95943f#gistcomment-2051253

**Comment by AndrewPy** [comment]
We have the same problem too (with video- and audio files). 
It seems that even some "old" videos in the database (that were playable with older signal versions) now produce this error.

**Comment by notthematrix** [comment]
you can still export then outside signal and then play....  problem started since 4.0.24

**Comment by AndrewPy** [comment]
> you can still export then outside signal and then play.... problem started since 4.0.24

Yes, but that's a bit cumbersome because these files are saved with the suffix ".attach" and you have to find out the correct suffix and rename the files (#6507).

**Comment by notthematrix** [comment]
Its a work around not a solution :) it should be fixed ASAP!

**Comment by gordon-morehouse** [comment]
A useful error message would help. "This video can't be played" conveys precisely zero information to the user as to why. Size limit? Codec problem? Who knows. After trial and error, I believe it can be either - a 6MB (?) limit and/or codecs not handled.

I also can find no documentation anywhere of what codecs are usable with Signal.

**Comment by moxie0** [comment]
Anyone have a sample video that fails?

**Comment by AndrewPy** [comment]
Here is such a mp4-video. But I get no error message - the screen simply remains black.

Device log: https://gist.github.com/b9795b67efedf9c08b6f3c9d40679a76


[clouds2.zip](https://github.com/WhisperSystems/Signal-Android/files/918835/clouds2.zip)

**Comment by notthematrix** [comment]
cant send file needs to be smaller then 10 mb....

**Comment by moxie0** [comment]
Thanks for the sample video. This should be fixed in 4.3.0

**Comment by notthematrix** [comment]
when will new update be availble?
