### ISSUE TITLE
Signal doesn't work over tun0 dev alone.

### ISSUE THREAD

**Issue by Sur3** [WhisperSystems/Signal-Android#6521]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal fails to send or receive messages over tun0 dev via USB.
Conversations has the same issue: https://github.com/siacs/Conversations/issues/2436
Other IM-Clients like Whatsapp or Xabber work fine.

### Steps to reproduce
- disable wifi and gsm internet connections.
- connect via tun0 eg with SimpleRT over USB.
- try to send or receive messages.

**Actual result:** No Message goes in or out.
**Expected result:** Normal sending and receiving of messages.

### Device info
**Device:** Samsung Galaxy S3
**Android version:** 7.1.1
**Signal version:** 4.2.4

### Link to debug log
https://gist.github.com/anonymous/0756a0f23c166b2796dce1cac0b56749

**Comment by Sur3** [comment]
SimpleRT states: "Some apps do not recognize the reverse tethered internet connection due to ConnectivityManager policy."
Probably that information helps to resolve the issue.

**Comment by moxie0** [comment]
@Sur3 That's correct, we wait for ConnectivityManager to report that there is connectivity before attempting to send a message. If you think we should be using different information provided by ConnectivityManager, please let us know.

**Comment by Sur3** [comment]
I pointed out in https://github.com/siacs/Conversations/issues/2436#issuecomment-293768050
that Xabber uses the Applications instance instead of getApplicationContext() (which is used by Signal and Conversations) to get the ConnectivityManager, probably that solves the issue, would have to be tested.

**Comment by Sur3** [comment]
I had a deeper look into the issue and upstream ( https://issuetracker.google.com/issues/37109422 ) reports the issue "wont be fixed" and suggests a downstream solution.. ( https://github.com/vvviperrr/SimpleRT/issues/3#issuecomment-294283202 ) i hope that solution will work therefore i'll close this bug.
