### ISSUE TITLE
No outgoing calls possible, incoming works

### ISSUE THREAD

**Issue by hanswundersam** [WhisperSystems/Signal-Android#6523]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I cannot make any outgoing Signal calls, it just says "calling" forever including the pulsing connection sound. Incoming Signal calls and messaging work just fine.

### Steps to reproduce
- Open Signal app
- Choose contact
- Tap on the call icon and wait....

**Actual result:** The call screen opens and says "calling" ("Kontakt wird angerufen" in German). Pulse sound can be heard but call is never established.
**Expected result:** Call should be established rather quickly.

### Device info

**Device:** LG Nexus 5
**Android version:** 7.1.1 (LineageOS 14.1-20170328-nightly-hammerhead)
**Signal version:** 4.2.5 (without any Google Services installed, Signal downloaded from Play store via Yalp)

### Link to debug log
https://gist.github.com/c7e94477ec08f983873b0f12402672f5

**Comment by hanswundersam** [comment]
I amend my report: sometimes the call can be established. I'm currently trying to find out when that happens and when it doesn't work. Will report back asap.

**Comment by timotk** [comment]
@hanswundersam Is it the same as https://github.com/WhisperSystems/Signal-Android/issues/6447?

**Comment by hanswundersam** [comment]
Thanks for following up on this @timotk. I wasn't able to reproduce this behaviour anymore since it first appeared a few weeks ago. Perhaps it was non-Signal related. So I would consider this report closed.
