### ISSUE TITLE
Videos sent from Moto G4 can't be played without saving them first

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/Signal-Android#6532]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
If I send my friend a video the video gives an error if it's played in the app without saving it first. However, it works just fine if you save it outside the app and open it in the Photos app.

This started happening quite recently, it has always worked before.

### Steps to reproduce
1. Record a video on a Moto G4
2. Try playing it before sending it. It works.
3. Send the video
4. Try playing it in the app
5. It ain't working

**Actual result:** Videos give an error message if you try playing it in the app
**Expected result:** Videos should work just like they always have

### Screenshots
https://nup.pw/BAMir2.png <-- it plays around 5 seconds and then that appears
"The video can't be played"

### Device info
Device  : motorola Moto G (4) (athene)
Android : 7.0 (16, NPJ25.93-14)
Memory  : 53M (9.85% free, 384M max)
Memclass: 192
OS Host : ilclbld26
App     : Signal 4.2.5

### Link to debug log
https://gist.github.com/anonymous/9e7455b84da8c70fc78e34a744e572c9

**Comment by FeuRenard** [comment]
Duplicate of #6518?

**Comment by Dyras** [comment]
*Facepalm*
Will re-open if it's still happening in 4.3.0!
