### ISSUE TITLE
Two issues with the latest translation changes

### ISSUE THREAD

**Issue by bungabunga** [WhisperSystems/Signal-Android#6535]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
There are two issues with the latest change of Signal translations:
- "Contact joined Signal" string in the "Events" chapter is missing from translations,
- In the "Message font size" chapter the word "Normal" has an old translation string, probobly the one also used in "LED pattern". That's not the problem in English language but in Slovenian the word gets transleted to "Normalno", which is ok for "LED pattern" but it's not an ok translation for "Message font size" (it sholud be: "Normalne"). Please add "Normal" as a separate translation for "Message font size".

**Comment by FeuRenard** [comment]
First bullet point is addressed by #6534.

**Comment by RiseT** [comment]
Concerning the second point, what I think you are refering to is not the fact that both cases use the same string identifier (they are not. For LED, *preferences__normal* is used, and for the font *arrays__normal*), but a feature of Transifex called [Translation Memory](https://docs.transifex.com/setup/translation-memory), and in this case [Translation Memory Autofill](https://docs.transifex.com/setup/translation-memory/enabling-autofill).

When a new string is uploaded to Transifex that matches 100% an already existing string, the translation of the new string gets pre-filled with the translation of the existing one. But you can change it afterwards. This is at least what has happened to the German translation with the string "normal".

**Comment by bungabunga** [comment]
Thanks, i changed it. Closing this.
