### ISSUE TITLE
Signal crashes on incoming and outgoing calls

### ISSUE THREAD

**Issue by nicolasmueller** [WhisperSystems/Signal-Android#6537]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashes, when I when there is an incoming SIgnal voice call from an Android device or an outgoing Signal call to an Android device (I didn't test with the iOS version).
For incoming calls, the crash happens immediately when the ringing would normally start. When I restart Signal afterwards, I see that there is a missed call. For outgoing calls, the crash happens immediately, after the call screen is shown, before the ringing starts.

### Steps to reproduce
- Be called on Signal Android by a Signal Android device (no need to pick up or even have the screen active)
- Alternatively, call a Signal Android device.

**Actual result:** Signal crashes immediately.
**Expected result:** Signal should not crash and establish a call.

### Device info

**Device:** Samsung Galaxy S2 (I9100)
**Android version:** 7.1.1. (lineage-os)
**Signal version:** 4.2.5 (self-updating version from the Signal website)

### Link to debug log

https://gist.github.com/anonymous/01b16245e6af6d65659b03bce5975282

**Comment by rustybird** [comment]
This is somehow related to https://github.com/LineageOS/android_frameworks_base/commit/47a42bf706b4eab3bc4243b9abd697703bb36a8e. No idea what is happening here, but building your ROM with `<bool name="config_useWakeLockForFlashlight">false</bool>` will get rid of the crash.

**Comment by ronnystandtke** [comment]
I have the same issue on a Samsung Galaxy S3. Here is the log:
https://gist.github.com/824d621327cbf708da3eeeb9df7fe6ae

**Comment by MJJoker** [comment]
same here with Samsung Galaxy S2, lineageOS 14.1 (latest Nightly) and self compiled Signal (without Google)
https://gist.github.com/anonymous/f5d8b9066a809e2b940f773fffbc8680

it happens since a few version, starting from 4.x.y.
I'm using a google-free phone

**Comment by papjul** [comment]
@MJJoker When you compiled the ROM, did you set `<bool name="config_useWakeLockForFlashlight">false</bool>` as recommended by @rustybird ?

Do we know if Signal can by-pass this issue somehow? It seems regular calls work so…

**Comment by 115ek** [comment]
I've got the same problems with lineageOS 14.1 and a self compiled Signal on a google free device.
AFAIK `<bool name="config_useWakeLockForFlashlight">true</bool>` is needed to use the flashlight with screen turned off (at least on my device...).
I hope the issue can be fixed within Signal - so we don't have to break working lineage features.
Btw: Is there someone with LineageOS and working calls?

**Comment by moxie0** [comment]
I don't think there's anything we can do on the Signal side, looks like a ROM thing.

**Comment by fduhia** [comment]
I wish to contribute a possible fix. The app requires both Phone and Microphone permissions on my device running LineageOS , if the Microphone permission is not provided the app will crash as described.
