### ISSUE TITLE
Regression: Location sharing doesn't work anymore

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/Signal-Android#6543]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
As I don't use that feature that often, I don't know for how long, but location sharing doesn't work anymore. After tapping the location button, I see the map for a couple of frames, but then it disappears.

Note: This is *not* the same as https://github.com/WhisperSystems/Signal-Android/issues/6351, as I'm using stock Android (i. e. with gapps).

### Steps to reproduce
- Open conversation
- Tap on attachment button
- Tap on location button

**Actual result:** Maps visible for a fraction of a second, then disappears
**Expected result:** Map should stay visible and I should be able to send a message containing that map

### Screenshots
N/A

### Device info

**Device:** LG Nexus 5X
**Android version:** 7.1.2
**Signal version:** Current 4.4.0 branch (https://github.com/WhisperSystems/Signal-Android/commit/6d5a43ccb82a6430a32947b008ca85cce707ebbf is the latest commit)

### Link to debug log

None yet. Will post one if this cannot get easily confirmed.

**Comment by FeuRenard** [comment]
Works for me on 4.3.1 Play Store beta, Android 5.1 (stock).

**Comment by johanw666** [comment]
Did you build ypur own version? Then you have to bet your own api key from Google, tie it to your own signing key and replace the one in the manifest file with it. Otherwise you'll see this effect.

**Comment by RiseT** [comment]
> Did you build your own version? Then you have to get your own api key from Google

Oops. Never had heard about that. Thanks & sorry.

**Comment by johanw666** [comment]
See https://developers.google.com/maps/documentation/geocoding/get-api-key
