### ISSUE TITLE
Crash on Android 4.4.X Signal 4.3.1 when viewing Signal > Settings > Notifications/Privacy

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-Android#6544]
I have:
- [X] searched open and closed issues for duplicates, but very easily could have overlooked this crash issue
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Crash when viewing specific settings 

### Steps to reproduce
- Open Signal 
- Go to Menu > Settings > Notifications or Privacy

**Actual result:** crash
**Expected result:** No crash

### Device info

**Device:** Samsung Galaxy S3 and tablet Model MFLogin3T
**Android version:** 4.4.2 and 4.4.4
**Signal version:** 4.3.1

### Link to debug log

User 1: https://gist.github.com/91e770626d5aea949010bbf0fb2c43ae
User 2: https://gist.github.com/dfe18687a0fd0612cf8668993118b357

**Comment by johanw666** [comment]
Confirmed. Signal crashes when I open Settings - notifications  and scroll to the bottom, and when I open and Settings - Privacy.

Debug log: https://gist.github.com/anonymous/60e668c4b0a93a359f0594f2a5c73427

**Comment by mateoeh** [comment]
Regression at 8aab61c

**Comment by FaizKhan5** [comment]
My one friend also that issue when she go to privacy the app crash suddenly

**Comment by FaizKhan5** [comment]
On 4.4.xx
