### ISSUE TITLE
Signal goes into crash loop after messaging contact, receiving message from contact with data connection

### ISSUE THREAD

**Issue by rubin110** [WhisperSystems/Signal-Android#6553]
Signal version 4.3.2
Android 7.1.2
Pixel XL, not rooted
Google Play Service 10.2.98

I had a prior conversation with a contact today. About 20 minutes ago I tried messaging that same contact after leaving my office, Single immediately went into a crash loop and threw the screen allowing me to report feedback (I've reported it a few times with some descriptive text). The crash still happened after I deleted the cache to Signal.

I set the device to airplane mode and reopened Signal. I was able to open the app without a crash. Opening up the conversation with said friend I could see the message I had sent was still in a pending state (3 dots animating). I long held on the message, deleted it, killed the app (app switcher swipe), turned off airplane mode, reopened the app. No crash.

Again I attempted to message my friend, again hit a boot crash. Repeated my airplane mode steps, then went back to Signal while online and tried to send a message to a different contact. That worked fine, no crash, double check marks.

I left it alone. After about 30 minutes said contact tried messaging me again and the app in the background threw the Android crash submit feedback popup box. The airplane mode trick no longer works, nor does clearing cache. Also my session through the Chrome extension is running fine. I can see the last message I received from the friend was "Yeah, k" before any further messages from me or him would cause the app to give up on life.

At this time I was able to logcat the crash in the state that it is in now and attaching thta at the end of this bug report. I am assuming my only option at this point is to clear app data to get out of this bad state.

[bitmoji](https://render.bitstrips.com/v2/cpanel/10217268-133639651_8-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by moxie0** [comment]
Sorry this happened to you. It looks like, somehow, a bit is flipped on disk and the version marker for your session state is corrupt. The airplane mode trick isn't working for you this time around because it's asserting on a *received* message rather than a pending outgoing message.

If you send me an email (moxie+github@whispersystems.org) I can build you a custom APK that you can install which will get you past the assertion and try to reset your session.
