### ISSUE TITLE
Alternative identifier for registration

### ISSUE THREAD

**Issue by Raph33** [WhisperSystems/Signal-Android#6555]
I saw [this thread ](https://github.com/WhisperSystems/Signal-Android/issues/1085) on the topic but it's a few years old. 
Has there been any new attempt to implement an alternative kind of identifier, besides the phone number, for registration? Or is it on the roadmap?

**Comment by nrizzio** [comment]
If it's open, it's still on the roadmap.
In this repository we really don't use issues for discussion, but there is a forum thread [here](https://whispersystems.discoursehosting.net/t/registering-with-an-email-address/919). You can also find more contributing guidelines [here](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md).

**Comment by Raph33** [comment]
Thanks, I'll follow the conversation on the forum then.
