### ISSUE TITLE
message queue stuck, only flushed after media send

### ISSUE THREAD

**Issue by coops** [WhisperSystems/Signal-Android#6557]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Two of my text conversations this afternoon stopped receiving "received" notifications around 1350 PST. Further text messages in those conversations were never marked received, until I sent a picture to each conversation.

### Steps to reproduce
I can't reproduce this any more. I did capture a debug log.

### Device info

**Device:** Google Pixel (sailfish)
**Android version:** 7.1.2 (3766409, N2G47E)
**Signal version:** 4.3.2

### Link to debug log
https://gist.github.com/anonymous/d1e57559b9b18150ae2de0d7fbd5638c
First successful flush picture was sent at 18:00:29, second sent at 18:03:20.

**Comment by nrizzio** [comment]
Probably the same underlying issue as #6556

**Comment by moxie0** [comment]
Yep, should be back to normal now, sorry!

**Comment by coops** [comment]
The issue appears to be recurring.
