### ISSUE TITLE
Can't register without play services / play service error notifications / unreliable delivery

### ISSUE THREAD

**Issue by h278772** [WhisperSystems/Signal-Android#6558]
1. Can't register without google play services.

2. If play services is disabled after registration, the app gives warning notifications "Permanent Signal com...." "Signal was unable to register with google play services" (although the app still works). 

3. Text delivery is sporadic and unreliable.

Do you people even test the app before putting it on the market? Don't publish an app with a big press release saying that it will work without google play services if you haven't even tested it and it, in fact, doesn't work. Pathetic. How is it that Telegram has so many more features, and works so successfully, yet your app doesn't? Incompetent developers.

**Comment by moxie0** [comment]
Hey there @h278772, Signal is designed to work without play services if you don't have them on your device at install time. There is a bug in the play services stub that erroneously reports "disabled" play services as "needing update," and that's already tracked in a separate issue.

(Although, if the idea is that play services are some kind of closed source malware, I'm not sure what the benefit of marking them "disabled" is.)

I don't recall ever publishing a press release, or even an announcement. I do my best here, help is always appreciated.
