### ISSUE TITLE
Play services issue

### ISSUE THREAD

**Issue by h278772** [WhisperSystems/Signal-Android#6559]
First of all, I've never come across another app that won't allow the user to bypass the "update play services" popup by clicking outside the popup, and then work as normal, if indeed the app doesn't REQUIRE play services (but still attempts to use it for something). Signal registration fails completely if play services isn't the latest possible version, even if the user has it disabled. You should allow the user to click outside that popup and proceed without updating/using play services if in fact Signal works without it. That's what most apps do if they don't require play services.

Second, your comment about Signal being designed to work if play services isn't installed on the device at all is completely facetious. ALL android devices have this installed. The only way to get it completely deleted is to root the device, which thanks to google, can only be done by using third-party apps like Kingroot which is made by unknown people in China and introduces a huge security risk. Therefore, it's only feasible to DISABLE play services, google services framework, the play store, and google account manager.

Third, you ask what is the benefit of making play services disabled "if it is some kind of malware." Well, (1) play services constantly phones home to a google domain at 1e100.net. It has complete permissions to your device and, knowing how google is, most likely uploads the user's contacts and files, and may even record audio and video without the user knowing. The mere fact that it has permission to do all of that is a security risk in itself (and opens a backdoor for the government to collude with google to develop spy tools for Android phones). (2) Play services is constantly updating, which I have found can cause major incompatibility issues and brick phones, since google doesn't test the update on every phone in use in the marketplace. Google forces the updates on users, which is unethical and unnecessary if the old version is working.

So, hopefully you can see why play services is a major problem. Basically, google treats peoples' phones as if it belonged to google, controlling what can run on the device, forcing updates, accessing god knows what, and constantly phoning home, as any user with a firewall app can see. They act as if they are only "licensing" the phone to the user, rather than the user actually owning the phone and controlling it. Honestly, I would think any developer working on a privacy/security product like Signal would have grasped this already.

With regards to publishing annoucements, see:

https://news.ycombinator.com/item?id=13691050
https://www.reddit.com/r/Android/comments/5v9evr/signal_can_now_be_used_without_google_play/
http://forums.crackberry.com/blackberry-10-apps-f274/official-signal-app-without-play-services-available-1100790/
https://www.wilderssecurity.com/threads/signal-can-now-be-used-without-google-play-services.392235/
https://opensignal.com/android_app/non-market-download.php

**Comment by h278772** [comment]
By the way, if you still have any doubts about the problems with play services, then read the thousands of complaints about it under the app's reviews section on the play store.

**Comment by h278772** [comment]
Also I would add that I use many other apps with play services DISABLED and they work perfectly... Texting apps (textme, textnow, talku, dingtone), Skype (gives popup to update but clears when you click away), Scruff, Telegram, Instagram, Ghostery, even Google Maps itself works WITHOUT play services and services framework running.

**Comment by moxie0** [comment]
Thanks @h278772 but we don't use GitHub issues for discussion. If you'd like to participate here, please see the [contributor guidelines](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md).

As I mentioned before, there is already an issue (#6381) for what you're reporting. Intentionally opening multiple duplicate issues only means I have less time to get work done.
