### ISSUE TITLE
Missing signal contact

### ISSUE THREAD

**Issue by lielos** [WhisperSystems/Signal-Android#6560]
Hello,

I have 2 contact (iOS and I'm on Android)  install recently signal on his phone but we donsen't see each other. (they number has a +32 zone code and I has a +33 code)

It's my default application not for they.
We see another signal user on contact.
They can call each other with the Signal app.  
We can send text messages (SMS) without any trouble.

If you have some idea we would be grateful.
(sorry for my realy bad english)

**Comment by peterpanondrugs** [comment]
One of you should reregister (or both)
https://support.whispersystems.org/hc/en-us/articles/213190627-How-do-I-unregister-
and then activate again (step 5).

**Comment by lielos** [comment]
It works !!
Thank for your help.

**Comment by peterpanondrugs** [comment]
close this then ;-)
