### ISSUE TITLE
Annoying notification "background connection enabled"

### ISSUE THREAD

**Issue by Tamriel** [WhisperSystems/Signal-Android#6561]
With the websocket version there appears a notification saying "background connection enabled". It can't be dismissed. Please remove that notification, since I know that I am using websockets.

**Comment by moxie0** [comment]
A notification is required in order to run a foreground service, which is necessary to keep the connection alive in the most battery friendly way.

**Comment by Tamriel** [comment]
Do you know how Telegram is doing it without Google?

**Comment by michallepicki** [comment]
Messenger lite doesn't need a notification to work in background without google play services either

**Comment by theBoatman** [comment]
The mailing app K9 can also keep push connections open without a notification. They work reliable and K9 uses far less energy than signal on my phone.

**Comment by NotSoImportant** [comment]
Seems like you can get rid of the notification (at least for a while) with the following trick:
- Slide the notification to the right and open "more settings" (or long press it)
- Click on the "A"
- Put the slider to the top left (all Signal notifications are gone)
- Press on A again (now again other Signal notifications will come in as usual)
Other notifications or even opening the app does not bring the persistant notification back.
This will last until Signal app (for whatever reason) restarts.

**Comment by null-git** [comment]
I don't want to discuss the reason why this notification has to be shown, I'm sure you know what you're doing. But it would be very nice if the icon of the notification could be changed, so that it represents the function of the notification. To just use the same icon as for a new message is very confusing. I find myself checking the notification a few times a day because I think there is a new message.

**Comment by adnion** [comment]
> A notification is required in order to run a foreground service, which is necessary to keep the connection alive in the most battery friendly way.

I tried WhatsApp without play services and it works without any notifications! It's a pity this issue is closed. I invited some friends to use Signal but they complain about this ugly notification.

**Comment by paperdigits** [comment]
Can this be re-examined for Android O? It has much more granular notification settings.

**Comment by tomatosmoothie** [comment]
![Screenshot_20190329-112507_Settings](https://user-images.githubusercontent.com/34439427/55212486-eae24900-5215-11e9-8841-8af869085ade.png)

Found a way that worked for me on Android Pie (LineageOS, no GSF(No Google Installed))
Settings > Apps & Notifications > Signal > Uncheck 'Other' like in the screenshot

**Comment by chrisdane** [comment]
Hi
My OS is Fairphone Open 19.02.1. Is there a way to get rid of the "Background connection enabled" message of Signal? Thanks!

**Comment by Meteor0id** [comment]
It might be a good idea to open a feature request on this topic "keep Signal open in the background without play services and without notification"

**Comment by Nephilimi** [comment]
I got this message today after receiving the message in signal; "This device does not support play services. Tap to disable system battery optimizations that prevent signal from retrieving messages while inactive"

My question is how in the world does my US AT&T samsung S10 not support play push services for this?

This doesn't seem like it should be necessary to have signal always running in the background.

**Comment by zeroedout** [comment]
> I got this message today after receiving the message in signal; "This device does not support play services. Tap to disable system battery optimizations that prevent signal from retrieving messages while inactive"
> 
> My question is how in the world does my US AT&T samsung S10 not support play push services for this?
> 
My Pixel 3a XL as well.

**Comment by paperdigits** [comment]
Did you install signal from the play store or elsewhere? Play store version should support play services. If you grabbed the apk from signal's website, it doesn't.

**Comment by Nephilimi** [comment]
For me I got it from the play store. Apparently the play store version will fall back if play services can't be reached right then. My notification went away after a while.

**Comment by carlin-q-scott** [comment]
Thanks for the clue to fixing this issue for myself. I'm using microG (Google Play Services alternative), and I had to re-install Signal after setting up their alternative to [Google Cloud Messaging](https://github.com/microg/android_packages_apps_GmsCore/wiki/Helpful-Information). They actually mention this problem at that link.

**Comment by landry314** [comment]
> For me I got it from the play store. Apparently the play store version will fall back if play services can't be reached right then. My notification went away after a while.

how long? today signal decided i dont have play services even though i do and it is still using web sockets... no idea how to fix this other than a reinstall... wth?

**Comment by neopostmodern** [comment]
I think that the scenario mentioned [above](https://github.com/signalapp/Signal-Android/issues/6561#issuecomment-576546187) for microG users (but also others, as per [this](https://github.com/signalapp/Signal-Android/issues/6561#issuecomment-739545570) comment) is somewhat common. Will the notification go away by itself at some point without a reinstall? If no, could this be implemented such that Signal re-checks if Google Cloud Messaging has become available once in a while?

**Comment by 015203087630** [comment]
9
Am 06.12.2020 19:49 schrieb "Landry Racoon" <notifications@github.com>:

**Comment by 015203087630** [comment]
Am 19.01.2021 19:11 schrieb "neopostmodern" <notifications@github.com>:

**Comment by Lemmie-Hollatcha** [comment]
Ghost is the man. That's the solution right there! Thank you!!!! Shit was driving me crazy. WHEW

**Comment by user2656** [comment]
> 
> 
> ![Screenshot_20190329-112507_Settings](https://user-images.githubusercontent.com/34439427/55212683-a2775b00-5216-11e9-8ef2-d8682ee839e0.png)
> 
> Found a way that worked for me on Android Pie (LineageOS, no GSF(No Google Installed))
> Settings > Apps & Notifications > Signal > Uncheck 'Other' like in the screenshot

Thanks!

**Comment by user2656** [comment]
Thanks @ghost

**Comment by Penguin-Guru** [comment]
This notification should probably be marked as silent and made small (like some other apps somehow are).
