### ISSUE TITLE
Disclose when installing that metadata is visible

### ISSUE THREAD

**Issue by dandv** [WhisperSystems/Signal-Android#6566]
Pardon me if this had been already discussed, but I only found one relevant issue, #838.

Since TS only supports phone numbers as an identity mechanism, it means the telcos (and hence governments) have all the metadata they need to identify users.

Thy don't even care about the communication contents - see
[Why Metadata Matters | Electronic Frontier Foundation](https://www.eff.org/deeplinks/2013/06/why-metadata-matters) and [Using Metadata to find Paul Revere](http://kieranhealy.org/blog/archives/2013/06/09/using-metadata-to-find-paul-revere/).

Thus TextSecure offers a false sense of security.

I'd love to be proven wrong if perhaps I misunderstood the underlying handshake and transport mechanisms (SMS, GCM).

**Comment by moxie0** [comment]
I'm not sure what you're referring to. If you mean that it's possible to determine someone is a Signal user from their phone number, that's by design and covered in the registration process.

**Comment by dandv** [comment]
I mean that if I Signal about something completely innocuous with an individual (I had no idea was) on a watchlist, I could very well be associated with them as a suspect. In that case, I'd prefer my communication were *not* encrypted, so it would be visible that I'm not talking to the suspicious identity of the individual.

**Comment by moxie0** [comment]
Signal uses phone numbers as identifiers, but Signal traffic is not transmitted over PSTN. The metadata you're referring to is not visible to telcos.  

We don't use GitHub issues for discussion, please contact support@whispersystems.org with questions or see the online forums for discussion.
