### ISSUE TITLE
FOSS gradle build flavor

### ISSUE THREAD

**Issue by AltNico** [WhisperSystems/Signal-Android#6568]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

Since March 13, you can now [download Signal as an `.apk`](https://whispersystems.discoursehosting.net/t/how-to-get-signal-apks-outside-of-the-google-play-store/808/15) from the official website. This is partial done for people who have no Google Play installed on their devices. A part of this group does not have Google Play installed because they don't want to have proprietary software on their device.

Fortunately, you can use Signal without Google's Firebase Cloud Messaging but unfortunately, the proprietary libraries are still included in Signal's build. Some of these are:
```
    compile 'com.google.android.gms:play-services-gcm:9.6.1'
    compile 'com.google.android.gms:play-services-maps:9.6.1'
    compile 'com.google.android.gms:play-services-places:9.6.1'
```

In my eyes it makes sense to add a fully free and open source gradle build flavor to Signal which builds get published on the website instead of the default Google Play release. If this is done, F-Droid can reproduce and distribute the official binaries of Signal by OpenWhisperSystems.

Reference thread in F-Droid's forum: https://forum.f-droid.org/t/signal-discussion-about-google-play-alternative/95

**Comment by moxie0** [comment]
Hey @AltNico, it's already possible to use Signal without Play Services on your device. We also already have a non-Play distribution channel that anyone can use, so we have no plans to distribute Signal through fdroid.
