### ISSUE TITLE
Setting disappearing messages in a group also removes entire group after messages expire

### ISSUE THREAD

**Issue by AboveMyPaygrade** [WhisperSystems/Signal-Android#6569]
I have:
- [ x] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
- [Caveat] Please note, I'm not entirely sure this _is_ a bug, as I could see the utility of this behavior, depending on the use-case.

- When I'm in a group conversation with (in this case) two other users, and I've set the disappearing messages timer to 1 day, if that amount of time passes and no one has sent any messages to the group, not only will the messages disappear (as expected), but the entire group will disappear, no longer showing in the contacts list.

### Steps to reproduce
- Create a messaging group with two other Signal users

- Set disappearing messages timer to _1 day_

- Exchange messages as expected

- Note that your group appears in your contacts list

- Allow all messages to expire, with no messages being sent or received by the group for the duration of the disappearing messages timer

- Note that the created group has disappeared

**Actual result:** Note that the created group has disappeared

**Expected result:** Noting my caveat above, the _expected_ result would normally be that the created group does not disappear without the user manually deleting it.

### Work-arounds

The following work-arounds were found to negate this behavior (assuming you don't want to disable the _disappearing messages_ functionality):

- When first creating the group, prior to setting the _disappearing messages_ timer, send one message to the group, serving to anchor the group in your contacts list.  Once that message has been sent, set the _disappearing messages_ timer, which will automatically delete subsequent messages (excluding the _anchor_).  It is unknown if this will serve to anchor the group with recipients, especially if they manually delete the _anchor_.

- Assuming you're using the desktop client, where the group will not disappear once the timer has expired (but messages will), send a message to the group.  This will serve to recreate the group on the mobile app.  The group will disappear on the mobile app should the timer expire again.

### App State
- Signal messages and calls registered

- SMS/MMS Enabled

- Notifications on

- Passphrase on, Screen security on

- Theme Dark, Language Default

- Message trimming off

- 3rd party app info unknown, other than being Signal registered

### Device info

**Device:** Huawei Nexus 6P
**Android version:** 7.1.2, build N2G47H
**Signal version:** 4.4.0 _beta_

### Link to debug log
Bug(?) was not noticed in a timely fashion, so no debug log was generated.

**Comment by FeuRenard** [comment]
This is a duplicate of #6038.

**Comment by AboveMyPaygrade** [comment]
Ah.  Apologies; I missed it in my initial search of open issues.  Should I reference this issue number in #6038 and close it out?

**Comment by FeuRenard** [comment]
By mentioning #6038 here, this issue (#6569) is automatically listed in the conversation of #6038. So you can simply close this one.

**Comment by AboveMyPaygrade** [comment]
Will do.  Thanks!
