### ISSUE TITLE
No file size limit for arbitrary file types

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#6573]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Just startet sending a 300 MB zip file o_O
This is great, but surely not inteded 

**Actual result:** file can be sent (tough it takes long)
**Expected result:** File size limit at around 100 MB, like for a/v - maybe 50 MB is a good value to start with...

### Screenshots
![grafik](https://cloud.githubusercontent.com/assets/5326916/25354712/599d6f26-2934-11e7-97a4-d4e503995825.png)

**Comment by scienmind** [comment]
> Expected result: File size limit at around 100 MB, like for a/v - maybe 50 MB is a good value to start with...

Wouldn't 100-50 Mb be too low of a limit? 
With videos I run into the limitation quite frequently, very often have to re-encode it to send, and besides, having a secure transfer for big files is a good thing, isn't it?

Of course there might be server load considerations, but if it's not the case, i think higher limits are preferred...

**Comment by adjenks** [comment]
It should be user configurable as to what file size you will receive or send. I am often frustrated by this 100mb limit. I often want to send files between 100 and 200 mb. Ideally my friends and I could exchange whatever we want and not have to split it into chunks. I mean, I'll send it anyways in chunks, so it's not like it's going to reduce traffic coming from me, it's just going to frustrate me.

**Comment by adjenks** [comment]
For those of you who want to split things into chunks, use ZArchiver and archive it into 50mb 7z chunks.
