### ISSUE TITLE
No security warning if arbitrary file attachements opened

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#6574]
I have:
- [x] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
There used to be a security warning when attachements where about to be opened in an external viewer.
There is no such warning when opening a` *.* `file

### Steps to reproduce
- tap a arbitrary file attachement message 
- file opens / app selector opens

**Actual result:** no security warning for opening outside Signal
**Expected result:** show securit warning

**Comment by moxie0** [comment]
Previously we had to do that because we were copying the entire encrypted file into a plaintext file accessible by external applications. We've changed the way it works so that Signal doesn't have to do the plaintext copy anymore.
