### ISSUE TITLE
Document attachement icon recolors (randomly)

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#6575]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Sometimes the paper sheer on the document attach button recolors to green.
Sometimes after closing and opening the attachement selector. Other times only when switch the conversation. Sometimes not at all. Pattern is missing.
(Maybe only when a something is selected/sent)

### Steps to reproduce
- twitch around with the attachment selector

**Actual result:** sheet color turns green
**Expected result:** sheet color shouldn't change

### Screenshots

![grafik](https://cloud.githubusercontent.com/assets/5326916/25355198/19e31258-2936-11e7-83f1-34a01546feeb.png)

### Device info

**Device:** Z5 compact
**Android version:** 6.0.1
**Signal version:** 4.4.0

**Comment by moxie0** [comment]
Does green have a relationship to anything else in the app? Like the contact's color or something?

**Comment by McLoo** [comment]
Oh, indeed. Turns out this happens only for the self send conversation - but still not always. 

It's the color that the contact (me) has set on entering the conversation. Changing the contact color affects the attachment button on reentering.

**Comment by McLoo** [comment]
More detail:
The color from the received file message will be adopted by the attachment button, once a received file in shown in the conversation. Either on load or after scrolling.
