### ISSUE TITLE
Unable to use webrtc libjingle_peerconnection.

### ISSUE THREAD

**Issue by info2shashi** [WhisperSystems/Signal-Android#6578]
I was trying to compile Signal android app along with native android webrtc from https://webrtc.org/native-code/android/

But it didn't work. It seems, webrtc used in Signal implementation is different from what is available on link mentioned above. Is it correct ?
If yes, then is there any repo available for Signal Webrtc ? Thanks.

**Comment by FeuRenard** [comment]
Maybe this: https://github.com/WhisperSystems/libwebrtc-android

**Comment by info2shashi** [comment]
Thanks @FeuRenard  . I looked into this repo, but it doesn't work with latest Signal App codebase. I was getting crash inside its webrtc library. 
Also this repo has version M56-S1, while latest Signal App codebase using M56-S2. I'm not sure, what is difference between these two version.

**Comment by johanw666** [comment]
[quote]Also this repo has version M56-S1, while latest Signal App codebase using M56-S2[/quote]
Actually M57-S2. I believe the difference has to do with which phones are added to the AEC whiteliost, but since the whitelist is replaced by a blacklist I'm not sure how relevant this still is. But I agree the published libwebrtc should be upgraded to the version currently used.

**Comment by info2shashi** [comment]
Thanks @johanw666 for your reply. 
Is there any schedule for updating https://github.com/WhisperSystems/libwebrtc-android repo with latest changes what is being used in Signal ? I believe both repo should be in sync.

**Comment by info2shashi** [comment]
Just one more query on same topic, Is there any public webrtc repo that will generate these Signal Webrtc "libjingle_peerconnection_so.so" file. If yes then i can give it a try to do it by myself.  

Also is there any package name dependency, as I am trying to use this under different package name. thanks.

**Comment by johanw666** [comment]
Well, I can find 2 versions of libjingle_peerconnection in the cache of Android Studio; I the last one should be M57-2. I can host it somewhere if you like but the build setup should download those libraries itself from the servers given in build.gradle.

**Comment by moxie0** [comment]
Hey @info2shashi we try not to use GitHub issues for Q&A. Everything that Signal uses is built and published as a maven artifact, if you have further questions you might hit up the online forums. Thanks.
