### ISSUE TITLE
Release the latest beta as website distribution build

### ISSUE THREAD

**Issue by sigenc** [WhisperSystems/Signal-Android#6580]

**Comment by haffenloher** [comment]
This is not going to happen for the reasons outlined [here](https://whispersystems.discoursehosting.net/t/how-to-get-signal-apks-outside-of-the-google-play-store/808/38?u=haffenloher).

Additionally, considering that OWS doesn't want to actively encourage website installation for security reasons (it kind of brings us back to the failed desktop security model where everyone downloads executables from random websites), I think it wouldn't make sense to publish the most recent version on the website.

If you want to discuss this further, I invite you to do so in the forum thread linked above. Thanks!
