### ISSUE TITLE
Signal sounds and codecs

### ISSUE THREAD

**Issue by MatejKovacic** [WhisperSystems/Signal-Android#6584]
I have:
- [X ] searched open and closed issues for duplicates
- [ X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Actually this is not a bug, just proposal for UX improvement.

Current sounds (sonar sound and ping when call is established/terminated) are by my opinion too aggressive. They contain too much high tones.

My proposal is, to use more soft sounds.

My proposal is also to replace sonar sound with something more similar to ringing... for instance instead of sonar there should be "slow" ringing and when ringing starts, there should be regular ringing (as it is now).

Another proposal is also to measure bandwidth and quality of call. When quality of call starts to get to low, user should get a very soft beep-beep-beep sound, so he/she is alerted there are problems with bandwidth. This should also be visible on the screen.

If connection drops (because of bad connection), it should be re-establisher automatically - user should be alerted of this re-establishing by sound and by screen text.

Anyway, I am also noticing some problems with bandwidth consumption. Are there any plans that when bad network conditions occur, codec automatically "switches" to lower quality? I am not talking about VBR
codecs, just that maybe there should be two codecs used - one for normal bandwidth and another when bandwidth is lower.

**Comment by wizardofid** [comment]
I think it is very important for users that they can clearly distinguish the network-connection-phase from the partner's-phone-is-ringing-phase. Therefore i'd not change something in this area. I'm quite sure there have been issue-reports where users complained the distinction was not clear enough now (and the network-connection needs too long, but that seems to be network dependend).
A sonar sound while searching network connection seems to me really intuitive. I understood it immediately when first using Redphone. And i like the ping which alerts me that now somebody could answer my call.

**Comment by moxie0** [comment]
If you have alternate audio tracks in mind that are appropriately licensed, feel free to propose them in a PR. The encoding we use is already congestion adaptive. I'm going to close this since I don't think we need an issue to track it, hit up the mailing list or the forums if you'd like to discuss it with others.
