### ISSUE TITLE
Jumbomoji doesn't work for all emojis

### ISSUE THREAD

**Issue by tge-linee** [WhisperSystems/Signal-Android#6587]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Jumbomoji doesn't work for newer system-emojis.

### Steps to reproduce
- use newer emoji

**Actual result:** - doesn't get jumboed
**Expected result:** - should be jumbo-jumbo

### Screenshots

![screenshot_20170427-090103](https://cloud.githubusercontent.com/assets/18348129/25472677/a08e09be-2b2c-11e7-8b6f-3a40be2a2470.png)

### Device info

**Device:** Nexus 5X
**Android version:** 7.1.2
**Signal version:** 4.5.0

**Comment by mateoeh** [comment]
Jumbomoji relies on Signal's internal emoji set. This issue, more generally, is about updating Signal's emoji set to Unicode 9.0 (see #6501)

**Comment by rainerzufall** [comment]
According to a comment by moxie in https://github.com/WhisperSystems/Signal-Android/pull/5947 it depends on an update of https://github.com/iamcal/emoji-data. A PR (https://github.com/iamcal/emoji-data/pull/78) for that seems far a long, but is not yet complete. 
also related issue https://github.com/WhisperSystems/Signal-Android/issues/4279

**Comment by tge-linee** [comment]
imo it shouldn't ship as is. It's not only a problem with system emojis, but also if your chat partner is using iOS. The inconsistency is worse than not having Jumbomoji at all.

**Comment by Dyras** [comment]
@tge-linee I don't see what you're complaining about, it's a fun feature and no matter how hard I try I can't think of a scenario where this could create a disasterous misunderstanding. iOS will get this eventually, just wait and relax a bit.

**Comment by tge-linee** [comment]
https://whispersystems.discoursehosting.net/t/discussion-about-jumbomoji/996

**Comment by holopixel** [comment]
I have the same bug although only when I don't use the standard Google keyboard. I have Fleksy and it doesn't work with it. 
everything's fine with the normal Google keyboard.

**Comment by holopixel** [comment]
jumbomojis still don't work for me when using the Fleksy-Keyboard. They work fine with the google standard keyboard.
