### ISSUE TITLE
Sticky list headers misaligned with the avatars

### ISSUE THREAD

**Issue by tge-linee** [WhisperSystems/Signal-Android#6588]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
As described by @moxie0 here https://github.com/WhisperSystems/Signal-Android/pull/6563: The list headers are misaligned.

### Screenshots
![screenshot_20170427-094050](https://cloud.githubusercontent.com/assets/18348129/25473145/96fc5430-2b2e-11e7-9c85-c4741baaae69.png)

### Device info

**Device:** Nexus 5X
**Android version:** 7.1.2
**Signal version:** 4.5.0

**Comment by mateoeh** [comment]
Looks like the wrong commit was merged: c6defe66d08f21798164f51d0128c50c8a605a5d (the updated commit with a fix for this) should have been merged instead of 59a2bf8

**Comment by moxie0** [comment]
@mateoeh Can you submit a PR with the correct commit?

**Comment by mateoeh** [comment]
Sure, I'll get to it later tonight
