### ISSUE TITLE
Preference for message font size doesn't work anymore since version 4.5.0

### ISSUE THREAD

**Issue by sweah82** [WhisperSystems/Signal-Android#6596]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Since version 4.5.0 the preference has no effect any more. I set it to small in version 4.4 and everything worked as expected. After the update to 4.5.0 the font size was back to normal and changing the preference has no effect.

### Steps to reproduce
- start Signal
- enter a conversation (font size is normal)
- change font size to small
- enter conversation (no changes)

**Actual result:** the font size doesn't change
**Expected result:** switch font size from normal to small

### Device info
**Device:** Samsung Galaxy S5 Mini
**Android version:** 6.0.1
**Signal version:** 4.5.0 (beta)

### Link to debug log
https://gist.github.com/8156e4397c146a4ef362786e34e51c0a

**Comment by FeuRenard** [comment]
I can confirm this. But the size of jumbomojis (#6531) changes according to the font preference.
