### ISSUE TITLE
Signal produces smaller Insecure MMS images than the competition

### ISSUE THREAD

**Issue by neheb** [WhisperSystems/Signal-Android#6607]
A recent Signal convert is having issues with his images being overly compressed. He send me three reference images.

### Screenshots
Signal - Secure MMS - 811KB
![signal-2017-04-30-202731](https://cloud.githubusercontent.com/assets/2918873/25571931/4e806570-2dea-11e7-81e9-de35c8149189.jpg)

Signal - Insecure MMS - 75KB
![download_20170430_204159](https://cloud.githubusercontent.com/assets/2918873/25571936/5cbee382-2dea-11e7-92e0-feae1955e3ab.jpg)

Samsung default messenger - 495KB
![download_20170430_204148](https://cloud.githubusercontent.com/assets/2918873/25571941/73736f6c-2dea-11e7-8562-1f5c0e7305fa.jpg)

### Device info
**Device:** Samsung Note 4
**Android version:** 6.0.1
**Signal version:** 4.3.2

### Link to debug log
https://gist.github.com/anonymous/0318dcc4ac285bb53dd3daea4e004df6

**Comment by FeuRenard** [comment]
This could be related to the [MMS size limit in Signal of 280KB](https://github.com/WhisperSystems/Signal-Android/blob/9bf198bb81aa6778b53e5124f2f7700248d675c4/src/org/thoughtcrime/securesms/mms/MmsMediaConstraints.java#L10). The Samsung default messenger clearly is constrained to a higher limit.

#496 asks for the limit to be configurable, which #6025 tried to introduce. But it was rejected to avoid an additional preference. Some discussion on solving this issue also took place on the [community forum](https://whispersystems.discoursehosting.net/t/mms-size-options-best-path/733).

But another questions is why Signal's MMS is so far below its maximum size. Actually #5772 attempted to improve this.

**Comment by johanw666** [comment]
When I see these iamges I think Signal does a great job - the image is still readable, and shrunk. MMS sizes differ per provider - better be on the safe side.

**Comment by neheb** [comment]
When I see those threads I see a 300kB limit. The posted image is much smaller than that. What gives?

Given that this has been an issue for a while, I guess I can't expect it to get fixed anytime soon.

Also, why does Signal think the phone has 512MB of RAM? It has 3GB.

@johanw666 Other pictures that he sent me are really blurry. He considers Signal to be perfect for his needs except for this issue.

**Comment by FeuRenard** [comment]
> When I see those threads I see a 300kB limit. The posted image is much smaller than that. What gives?

This is explained in #5772. Signal tries jpeg quality say 90 and checks whether the file size is below the limit. If this requirement is not fulfilled, it tries a lower quality, and so on. Maybe the step size is too high, so that the file size jumps from 301KB to 75KB between two iterations. Just a guess...

> Also, why does Signal think the phone has 512MB of RAM? It has 3GB.

You probably refer to the header of the debug log. The amount of RAM mentioned there is the memory that Signal is allowed to use.

**Comment by haffenloher** [comment]
> But another questions is why Signal's MMS is so far below its maximum size.

It's not the 280 kB limit which was relevant here (the 75 kB image's quality is 90, which is our maximum), but the max edge of 1024. I think glide doesn't use any kind of interpolation when downscaling (maybe it could, but we're not telling it to?), it just subsamples the image. The original image's longer edge was 2656 pixels wide, so the downscaled image's long edge has 2656/x pixels, where x is the smallest power of 2 necessary to achieve a result below 1024px (see also: https://developer.android.com/reference/android/graphics/BitmapFactory.Options.html#inSampleSize). Here x is 4, which results in an edge length of 664px.

**Comment by jeremymasters** [comment]
Seems like we could at least change that setting for max size to 495kb? Beta might tell us that's crazy, but it seems a fairly safe guess...famous last words

**Comment by neheb** [comment]
I think the main issue is that there's a massive difference in quality between a Secure and Insecure MMS.

To make it clearer,  there's no difference in image size between Secure MMS and Samsung's default messenger.

**Comment by moxie0** [comment]
Like all things MMS, there is no single "maximum file size."  The maximums (size, edge, etc) are all carrier-specific.  It used to be that a pretty common bound was 280kb, so that is what we set it at for all carriers.  Lately it seems as if some carriers have raised that limit.

The "Samsung messenger" has the advantage of being distributed on a device through a carrier, and is probably tuned specifically for that carrier.  What we need to do is determine that maximums for each carrier throughout the world, and store that information along with the APN information that we are currently maintaining for them. It would make a good PR!

**Comment by johanw666** [comment]
> The "Samsung messenger" has the advantage of being distributed on a device through a carrier,

Is it? Devices delivered and adapted by the carrier may be the norm in the US, but in other parts of the world they are not. Does Samsung have such a database included in its messenger with this information for all (most?) carriers? Including those that dropped MMS support completely, like the Dutch branch of T-Mobile.

**Comment by neheb** [comment]
FWIW the phone is a Sprint one that has been unlocked to use AT&T.

**Comment by moxie0** [comment]
This should be fixed in 51d61445915e0a607742a46c60332e015f9559b6. Uses per-carrier size constraints when available.

**Comment by neheb** [comment]
Seems to be a lot better.

I reran the test and found the new maximum on this device to be 1328 either width or height. Now 1328 * 2 is 2656. Is it possible that the size given by the API is halved for some reason? I ask since the width/height of the original image is 2560.
