### ISSUE TITLE
Feature request: Link Signal as app for arbitrary filetyps for sharing via "share menue".

### ISSUE THREAD

**Issue by mawed** [WhisperSystems/Signal-Android#6608]
As it is now possible to send arbitrary files within Signal -> Attachments -> file (Still open issue  #993), it would be even better, if it would be possible to share this files via the "share menue" within other apps.

As far as I know, Signal has to be linked as possible receiverapps for any filetype. 
Sorry if this should be monitored within  #993, but as this is closed, I did not see a chance to connect this request with this issue.

Regards

**Comment by Hanzei** [comment]
Good news: 2b79e13 fixed #933

**Comment by mawed** [comment]
@Hanzei I know (see my first sentence: _As it is now possible to send arbitrary files within Signal _). But it's not yet possible to attach the files via the external share menue.

That's why I opened this request and "linked" it with 933, as it mates, but I can't add this "new" request to the locked (and open) 933.

**Comment by moxie0** [comment]
in 4.6.0
