### ISSUE TITLE
#993 (locked issue) can be closed now

### ISSUE THREAD

**Issue by Wikinaut** [WhisperSystems/Signal-Android#6611]
@moxie0 Thank you for finally implementing #993 with Signal version 4.5.3. You locked the #993 issue some time ago, so that I (who reported it) was unable to close it. 

I want to ask you to close it, and also this issue.

I want to inform you that some people collected a bounty for the implementation of arbitrary-file-attachments. You now can claim the bounty (please see Bountysource page https://www.bountysource.com/issues/1464832-suggestion-allow-arbitrary-file-types-txt-zip-apk-pdf-to-be-sent-as-attachments-not-only-audio-video-media ).

**Comment by moxie0** [comment]
Thanks @Wikinaut, no need for the bounty you can return the funds to the original donors.
