### ISSUE TITLE
Calls, can't hear other side, they can hear me

### ISSUE THREAD

**Issue by patmast3r** [WhisperSystems/Signal-Android#6615]
When having a call with another person via Signal they can hear me, but I can't hear them. We've tried it multiple times, over the span of a month and the issue is always the same. It doesn't matter who initiates the call either. 

### Steps to reproduce
- Call or let someone else call you
- talk

**Actual result:** The person on the other end can hear me perfectly fine but I don't hear anything. It's like they're completely muted (they say they're not)

**Device:** OnePlus One
**Android version:** 6.0.1
**Signal version:** 4.5.3

https://gist.github.com/ada14fc110c4e41798d6ad6367f64365

This is one of the few ways I can talk to this person securely (we're thouhsands of miles apart) so I'd appreciate any help.

**Comment by bowensong** [comment]
I'm experiencing the same problem. Is this duplicate / related to #6432 ?

**Comment by moxie0** [comment]
Seems like the problem might be with your contact's device. What are they running?

**Comment by bowensong** [comment]
@moxie0 In my case, the other party is using a Nexus 5 phone which I know has been resolved (or attempted to resolve) in 4d889a45e25bd1e2298d991a6208f7c86f6eb9fa. I'll write a bit more details in #6432.

**Comment by alecbl** [comment]
Same issue, with at least two other people on xiaomi MTK phones, dif models, running MIUI. (I think a note 3 and a mi4). I'm myself on an idol3 running LineageOS w/ microG. Works with other people.

**Comment by sigenc** [comment]
Hmmm, maybe I'm totally wrong but i think this wasn't an issue all the time with webrtc. Same as #6432. I never had this problem before and i talk alot to a friend with my Nexus 6P and his S6. I think the problem startet last month

**Comment by patmast3r** [comment]
Other side is also running 6.01, I think on an older Samsung. Can't get a hold of them right now. 
For us this issue also started about a month ago. It worked without issues before.

**Comment by patmast3r** [comment]
Has anyone had luck solving this ? Any news ?

**Comment by bowensong** [comment]
@patmast3r For me, this bug has been solved in 4.5.3, the other side was using a Nexus 5. Based on the commits in the repository, I have reason to believe that this is going to be solved for all devices in 4.6.0

**Comment by patmast3r** [comment]
Yep, seems fixed with 4.6.0. Nice !
