### ISSUE TITLE
Requires Google Play!!!

### ISSUE THREAD

**Issue by jsmad** [WhisperSystems/Signal-Android#6616]
For an app that advertises itself for its privacy, I find the requirement for Google Play services quite... alarming.

Maybe you should consider removing this requirement and then we can actually use it.

Thank you.

**Comment by sigenc** [comment]
Official Build without googleplay is here: https://signal.org/android/apk/

You no longer need Google Play. There is a fallback Option, that uses websocket when it is detectet that there is no Play. Please close the issue
