### ISSUE TITLE
Show "new safety number" warning in group for group messages

### ISSUE THREAD

**Issue by paride** [WhisperSystems/Signal-Android#6621]
### Bug description
When a user changes key, the "safety numbers changed, accept?" message appears in a private conversation with the user, even if the message was sent in a group. I observed that people find this confusing, sometimes not realizing that they're missing group messages and then blaming Signal for losing them.

I know that the fact that a message is a "group message" is itself part of the message, and if the message is not trusted this information shouldn't be trusted too. Still I think that in this case the sweet spot between security and usability lies in showing these messages in the group conversation.

Partially related: #5985.

### Steps to reproduce
- Have a group conversation
- One of the users changes key (reinstalls Signal)
- Check where the "safety numbers changed, accept?" warning appears.

**Actual result:** The warning appears in a private conversation with the user.
**Expected result:** The warning appears in the group conversation.

**Device:** Nexus 6
**Android version:** 7.1.1 (stock)
**Signal version:** 4.5.3

**Comment by 2-4601** [comment]
As you noted the group metadata is in the message itself but something is in the road map according to this comment:

https://github.com/WhisperSystems/Signal-Android/issues/4413#issuecomment-154433979
> Unfortunately this is just the way it is for now. We don't know it's a group message until we decrypt it, but we can't decrypt it because of the updated identity. So the way it's supposed to work is that the message shows up in an individual thread, requires your approval, and then moves over to the group thread once we decrypt it.
> 
> **We'll be making some changes in the future that should make this less painful in the common case.**

**Comment by moxie0** [comment]
This should be resolved in 4.7.0
