### ISSUE TITLE
Signal crashes when attempting call

### ISSUE THREAD

**Issue by soloclub** [WhisperSystems/Signal-Android#6624]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

**Bug description**

Signal crashes when attempting call. Was working fine until yesterday.

**Steps to reproduce**

- open signal and call any contact

**Actual result:** Signal crashes
**Expected result:** Should be able to place call.

**Device info**

**Device:** LG Nexus 5
**Android version:** 7.1.2 (No play-services)
**Signal version:** 4.5.3

**Link to debug log**
https://gist.github.com/28da0383f22d4f954666805dbff30c8f

**Comment by moxie0** [comment]
Are you running a custom ROM? Looks like your whole VM is getting killed.

**Comment by soloclub** [comment]
Thanks, Issue resolved after Signal reinstall and a reboot.
