### ISSUE TITLE
Costa Rica and Signal

### ISSUE THREAD

**Issue by trmendes** [WhisperSystems/Signal-Android#6628]
For the last month I couldn't use Signal. I was always getting that message saying that Signal couldn't delivery my message and no message was coming from friends. This started when I arrived Costa Rica for traveling. 

Yesterday I ran Signal over TOR and the problem was gone. But as soon as I leave the TOR network the messages stop leaving my phone.

I have tried to uninstall and install Signal again but it says it can't reach the servers to register if I'm not on TOR...

**Comment by jeremymasters** [comment]
@trmendes Can you include some logs?

**Comment by trmendes** [comment]
@jeremymasters when I try to subimit the log it returns me "network failure" but the network is working.

**Comment by sigenc** [comment]
are you on wifi or mobile data?

**Comment by trmendes** [comment]
Wifi

**Comment by sigenc** [comment]
can you test it with mobile data?

**Comment by sigenc** [comment]
is it happening wih every wifi you connect or are you using always the same

**Comment by trmendes** [comment]
Every wifi network in Costa Rica so far....got here almost a month ago....have been to 5 hostels and 2 times to the airport. I can't test on the mobile network cause I don't have data...

**Comment by sigenc** [comment]
ok. can you edit the first post. Tell us which phone, wich os, wich signal version, gcm or websocket, try to post the log via tor.

**Comment by trmendes** [comment]
Via TOR: https://gist.github.com/9514e7e5aabeba1296facfd3ce7691ba

**Comment by trmendes** [comment]
Don't know how to edit the fist post so here it goes: Samsung S4 i9505 running LineageOS 14.1 20170510 NIGHTLY JFLTEXX. Signal Messenger 4.5.3 from google play

**Comment by sigenc** [comment]
can you please do the follwing. force stop signal. don't start tor. open signal. try to sent a message, try a call and wait 2 min. start tor and let the test message get through. post the log again immediatly after that.

**Comment by trmendes** [comment]
Did it but submitting is nkt working now not even on tor...and I can browse and use others apps that rely on the network. Gonna keep trying it here

**Comment by trmendes** [comment]
https://gist.github.com/7e2724cd0ff819d8f4c21c3c5af3e6e8

**Comment by trmendes** [comment]
Now I'm in Mexico city and I still have the same problem. I can only send/receive messages over TOR. Can't use Signal messeger if I'm not connected to TOR. I'm gonna try to find someone here in mexico to install signal and try it.

**Comment by sigenc** [comment]
sorry mayne. I can't help you with this. But to me it seems it is your client. Ever tried reinstalling the app?

**Comment by trmendes** [comment]
I did it. But when I try to check my phone with an SMS it fails tl connect tl the servers if I'm not on TOR

**Comment by sigenc** [comment]
Is is possible for you   reach any website on this phone without tor?

**Comment by trmendes** [comment]
Yes...I have tor on for Signal Messenger only...all the other apps I use without the tor network..

**Comment by sigenc** [comment]
You said Signal 4.5.3 from google play. Is gcm installed on this phone too?

**Comment by trmendes** [comment]
Yes to both questions... Using Signal from google play together with all the services...

**Comment by jeremymasters** [comment]
Something to do with Lineage + Signal then?

**Comment by sigenc** [comment]
@jeremymasters other people are also using this combination without problems

**Comment by trmendes** [comment]
It seems like it was something with LineageOS. I wiped everything and installed the last version and now Signal is working without TOR.

Thanks for your time and help here :D
