### ISSUE TITLE
Feature request: Answer to specific contact with highlighting and notification

### ISSUE THREAD

**Issue by Tratoschek** [WhisperSystems/Signal-Android#6634]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Description
It would be cool, if Signal provides a function for easy per contact highlighting in group chats, similar to the ones in IRC (with `<contactname>:`), Whatsapp (`@<contactname>`) or Github comments (`@<contactname>`).
In most IRC clients this works with `<tab>`, in Whatsapp a list of users is shown if `@` is entered.

Since the contacts names are not necessarily equal on the different devices, e.g. the phone number can be used internally.

A big advantage of this is, that it enables a personal "ping", so that users can mute the group chat but receive notifications if they are personally messaged (similar to IRC).

### Duplicates
I hope this isn't reported somewhere else or already supported. I have tested with Signal 4.5.2.

**Comment by FeuRenard** [comment]
Duplicate of #5401

**Comment by Tratoschek** [comment]
Ok sorry for the noise.
