### ISSUE TITLE
4.6.0: Some emojis show up more than once

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/Signal-Android#6637]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Some of the emojis appear more than once. Check the picture.

### Steps to reproduce
Open a chat
Click the emoji button
Click the smiley tab
Scroll down
The male face palm and the female shrug show up twice

### Screenshots
![signal-2017-05-13-193241](https://cloud.githubusercontent.com/assets/12563436/26027739/65bb8368-3813-11e7-9992-3dedcb3cd7d7.png)

**Comment by FeuRenard** [comment]
Here is a short note from the original emoji repository: https://github.com/iamcal/emoji-data/issues/86

Problem here is, that there are the following emoji defined:
- [woman-shrugging](https://github.com/iamcal/emoji-data/blob/master/table.htm#L28087)
- [man-shrugging](https://github.com/iamcal/emoji-data/blob/master/table.htm#L28106)
- [shrug](https://github.com/iamcal/emoji-data/blob/master/table.htm#L19746), which is in this case the same as woman-shrugging

**Comment by AlfonsoMuskedunder** [comment]
I just noticed that, in addition to the doubly shrugging woman pictured above, I have quite a long list of duplicate emojis attached at the very bottom of the table:

![screenshot_20170518-170124 1](https://cloud.githubusercontent.com/assets/10466043/26209225/7e630288-3bec-11e7-8878-1374a5650ddd.png)

**Comment by Dyras** [comment]
@AlfonsoMuskedunder I don't see any duplicates in that picture. Could you be more specific?

**Comment by AlfonsoMuskedunder** [comment]
More precisely: All the emojis you see below the umbrella _also_ appear further above, i.e. in their proper slot in the sorting order.
