### ISSUE TITLE
Icon for advanced settings equals that of appearance on Android 4.4.4

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/Signal-Android#6638]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I open settings on an Android 4.4.4 device the icon for "Advanced" equals that of "Appearance". On Android 6.0.1 this is not the case. Now that I look back to the screenshot in issue https://github.com/WhisperSystems/Signal-Android/issues/6601 , this was already so in 4.5.2.

### Screenshots
Android 4.4.4:
![screenshot_signal460-android444](https://cloud.githubusercontent.com/assets/8427572/26029498/9fc32282-3836-11e7-9d7a-fd433572d33f.png)

Android 6.0.1:
![screenshot_signal460-android601](https://cloud.githubusercontent.com/assets/8427572/26029501/a4945182-3836-11e7-8b8d-714a1ef45cdf.png)

### Device info
**Device 1:** Sony Xperia Z1 Compact
**Android version:** 4.4.4
**Signal version:** 4.6.0

**Device 2:** Sony Xperia Z3 Compact
**Android version:** 6.0.1
**Signal version:** 4.6.0

The bug is located in src/org/thoughtcrime/securesms/ApplicationPreferencesActivity.java, line 218:

```java
this.findPreference(PREFERENCE_CATEGORY_ADVANCED).setIcon(appearance);
```
it should be
```java
this.findPreference(PREFERENCE_CATEGORY_ADVANCED).setIcon(advanced);
```

**Comment by nrizzio** [comment]
After looking through this, the reason why this issue is present on Android 4.4.4 but not on 6.0.1 is because the faulty `tintIcons()` method call that places the wrong icon takes place only if the phone is between Honeycomb and Lollipop.

I'll have a PR ready shortly, thanks for the excellently written bug report.
