### ISSUE TITLE
Improve use of space in the message view

### ISSUE THREAD

**Issue by thomkeh** [WhisperSystems/Signal-Android#6641]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
These are small issues but I think they could have some impact on user experience. Here they are (in order of importance):
1. There is too much empty space between messages from the same person. The amount of space is OK for messages from two different people but that space is too much for messages from the same person. I often express my point in several consecutive messages and the spaces are breaking the flow. Right now you could fit about two extra lines between the text of two consecutive messages.
3. Similarly it's not necessary to display the profile picture for every message. In one-on-one chat you actually don't need the pictures at all. But I'm less sure if this is actually an issue.

**Actual result:** a lot of space between messages which interrupts the flow of conversation
**Expected result:** good use of space

**Comment by FeuRenard** [comment]
Duplicates of

1. #964 
2. #6008

**Comment by thomkeh** [comment]
Thanks! I searched in the issues for "space" but didn't find anything.
