### ISSUE TITLE
Screen turns off during video playback

### ISSUE THREAD

**Issue by FeuRenard** [WhisperSystems/Signal-Android#6642]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
During video playback the screen turns off. There should be a wakelock preventing that the screen turns off when a video is playing.

### Steps to reproduce
- set turn off timer in Android settings to a short time (e.g. 15s)
- go to a conversation with a video attachment, that plays longer than the turn off time of the display
- tap this video
- wait as long as your display turn off time is (don't interact with the screen)

**Actual result:** Screen turns off and interrupts video playback.
**Expected result:** Screen stays on during video playback.

### Device info 1

**Device:** Fairphone 2
**Android version:** 6.0.1
**Signal version:** 4.6.0

### Device info 2
**Device:** Sony Xperia U
**Android version:** 4.4.4 (CyanogenMod)
**Signal version:** 4.6.0

**Comment by UserX82** [comment]
Same problem with playing audio.

**Comment by FeuRenard** [comment]
That's tracked in #4424

**Comment by raffthesweetling13** [comment]
I was able to reproduce this issue on Signal 4.8.1 on the Android Studio Emulator: Nexus_6_API_23.

**Comment by raffthesweetling13** [comment]
I was able to find a solution to this issue. Before I do some more testing and submit a pull request, I have a couple questions. 

My solution is to add the `android:keepScreenOn="true"` attribute in the [media_preview_activity.xml](https://github.com/WhisperSystems/Signal-Android/blob/master/res/layout/media_preview_activity.xml#L18) specifically in the `VideoPlayer` section. 

1. Is it too much to keep the screen on anytime the `VideoPlayer` is being used? It is possible to dynamically set and unset the `keepScreenOn` attribute programatically for more fine tuned control.  One situation where this might be useful is if the user hits pause. It might be desirable for the screen to sleep normally when the video is paused.

2. Should the screen remain on while an image is being displayed as well? I would say no, but I figured I would ask. 

Thoughts?

[Documentation for keepScreenOn attribute](https://developer.android.com/training/scheduling/wakelock.html)

**Comment by FeuRenard** [comment]
I think it's better to work with the flags at runtime than in XML.

ExoPlayer offers a listener, which should notify us about hitting pause/play:
https://github.com/google/ExoPlayer/blob/9f814850535afbe5a0123f7fa8fc2875ba2c5015/library/core/src/main/java/com/google/android/exoplayer2/ExoPlayer.java#L153
So you could implement a listener, which sets the flag on play and clears the flag on pause. The ancient MediaPlayer doesn't seem to offer such a listener. To keep your change simple, you could ignore the ancient player unless you find a simple solution.
