### ISSUE TITLE
Support for polls/surveys

### ISSUE THREAD

**Issue by pgerber** [WhisperSystems/Signal-Android#6646]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Description
It would be great to have some basic polling features. Here is a selection of polling options I'd consider useful:

* **Single-choice polls**

  Sample Question:
  * Where should we go for lunch?

  Sample Answers:
    * Italian 
    * Indian
    * Korean
* **Multi-choice polls**

  Sample Question:
    * What days work for you?

  Sample Answers:
    * ✔Monday 10:00, ✔Tuesday 17:30, ✘ Wednesday 10:00
    * ✘ Monday 10:00, ✔Tuesday 17:30, (✔) Wednesday 10:00
* **Agree/disagree with different levels of agreement**

  Sample Question:
    * Is the font to large?

  Sample Answers:
    * Strongly disagree
    * Agree
    * Neutral

* **Preference** (perhaps similar to [Schulze Method](https://en.wikipedia.org/wiki/Schulze_method))

  Sample Question:
    * Should polls be implemented?

  Sample Answers:
     * **1.** Yes, immediately, **2.** Yes, within the next few months, **3.** Not a priority, revisit in 2018, **4.** No
     * **1.** Not a priority, revisit in 2018, **2.** Yes, within the next few months, **3.** Yes, immediately, **4.** No

**Comment by p4nci** [comment]
duplicate of https://github.com/WhisperSystems/Signal-Android/issues/2551

**Comment by manuliner** [comment]
i absolutly aggree with pgerber

# Downsides of doodle and co

-  need to click link ( to be honest everyone is lazy, and if you start a poll with n link over doodle maybe 50% are doing the poll, the other 50% after u asked 100 times to do)
- to check results, u always need to check the link

**Comment by Michael-A-Heuer** [comment]
A basic form of voting is possible already.
Just write a message and use the emoji reactions for vote counting.

For example:
> Should we order Pizza?
> 👍: Yes.
> 👎: No.
> 🤷‍♂️: Maybe.

Yes, they are never final and not anonymous but this is sufficient for most votes taking place in a messenger I guess.

**Comment by udfalkso** [comment]
Should this be reopened?  Is there a better venue for feature requests?

**Comment by greyson-signal** [comment]
We use [the forum](https://community.signalusers.org/) for discussing feature requests

**Comment by ma-karai** [comment]
This should be reopened!
 Its a killer feature and must have

**Comment by Tummetott** [comment]
One thing that holds back many friends of mine to use signal is the absence of proper polls. And the feature to pin a message (like the proper poll) at the top of the conversation!!!! Sure you can react with emojis, but multi choice answers end up in several messages (one per answer + question itself) and later you can’t really refer to that poll with the answer function (because the poll consists of several messages). Please don’t close that feature request. It’s such a useful feature that makes stupid telegram so powerful.

**Comment by CarrollDiehl** [comment]
Upvote for this one. Polls are a hugely convenient feature and should be simple enough to implement.
Don't see, why it's brushed off so quickly.

**Comment by greyson-signal** [comment]
> We use [the forum](https://community.signalusers.org/) for discussing feature requests
