### ISSUE TITLE
null PeerConnection 

### ISSUE THREAD

**Issue by saeedrooyekhat** [WhisperSystems/Signal-Android#6650]
hello,
i use from PeerConnectionWrapper and  compile 'org.whispersystems:webrtc-android:M57-S2' dependency In my project.
when i try for 
```java
this.peerConnection = peerConnectionFactory.createPeerConnection(configuration, constraints, observer);
```
this method returned null . how can i fix it ?

**Comment by nrizzio** [comment]
@saeedrooyekhat this issue tracker is for Signal bugs only. You can post in the forum at https://whispersystems.discoursehosting.net.
