### ISSUE TITLE
Build error -> broken unit test with gradle

### ISSUE THREAD

**Issue by motatuc** [WhisperSystems/Signal-Android#6652]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
It's not possible to build Signal at the moment - it fails with an error.

### Steps to reproduce
- pull the source
- ./gradlew build

**Actual result:** The build process fails
**Expected result:** The build process succeeds

### Build log
org.thoughtcrime.securesms.ConversationAdapterTest > testGetItemIdEquals FAILED
    java.lang.NumberFormatException at ConversationAdapterTest.java:29

23 tests completed, 1 failed
:testPlayDebugUnitTest FAILED

**Comment by johanw666** [comment]
I have no issues building with Android Studio on windows 7, even though I get a lot of errors. Shouldn't this line in build.gradle cope with this?
```
     lintOptions {
        abortOnError false
}
```

**Comment by motatuc** [comment]
Hm, good question.

This line does not seem to help here. Are you able to finish building when using gradle?

**Comment by johanw666** [comment]
I'm building on Windows, but I don't see how that would (or should) make any difference. I am building the playstore release version (with some minor modifications but those have nothing to do with this).

However, I always get an error in ContactSelectionListAdapter.java line 128 that does not break the build and that I can remove by adding a line to the build.gradle lintoptions:
```
     lintOptions {
        abortOnError false
        disable "ResourceType"
    }
```

**Comment by motatuc** [comment]
That line unfortunately does not fix the problem. I am not sure how this can be different for the two of us. But anyways It would be nice if the developers would fix that problem.

**Comment by mitar** [comment]
I have the same issue with current master, building on Mac OS X.

**Comment by Gitju** [comment]
Same with elementary OS.

And 
./gradlew build -x test 
results in a successful build.

**Comment by kale-hagay** [comment]
Same thing here.
