### ISSUE TITLE
Screen turns on, despite still being next to the ear (voice and audio messages)

### ISSUE THREAD

**Issue by michel-zimmer** [WhisperSystems/Signal-Android#6654]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When listening to an audio or voice message ends, the screen turns on and the touchscreen accepts input, despite the phone still being next to the ear, after listening to an audio or voice message. This leads to unwanted calling and other actions, the user never intended to do.

### Steps to reproduce
- Start listening to an audio or voice message.
- Hold the phone next to the ear, so that the screen turns off and input from the touchscreen is ignored.
- Wait for the audio or voice message to end.

**Actual result:** The screen turns back on and input from the touchscreen is no longer ignored.
**Expected result:** The screen stays off and input is ignored, as long as the phone is next to the ear.

### Device info
**Device:** Moto X Play
**Android version:** 6.0.1
**Signal version:** 4.6.0

### Link to debug log
https://gist.github.com/anonymous/d495bc418ede007bf7b5f563f446ea85

**Comment by FeuRenard** [comment]
[`RELEASE_FLAG_WAIT_FOR_NO_PROXIMITY`](https://developer.android.com/reference/android/os/PowerManager.html#RELEASE_FLAG_WAIT_FOR_NO_PROXIMITY) sounds useful for solving this issue.
