### ISSUE TITLE
Reproducible Builds - Dockerfile build from scratch fails

### ISSUE THREAD

**Issue by micressor** [WhisperSystems/Signal-Android#6656]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I am not able to build the Dockerfile for Reproducible Builds from sratch.
Building Signal via image from [docker hub](https://hub.docker.com/r/whispersystems/signal-android/) works fine. 

### Steps to reproduce
According to [Reproducible Builds](https://github.com/WhisperSystems/Signal-Android/wiki/Reproducible-Builds) wiki page.

I also tried:
`git clone https://github.com/WhisperSystems/Signal-Android.git && cd Signal-Android`
`docker build -t signal-android .`

**Actual result:**
```
[...]
Hit http://archive.ubuntu.com trusty/universe i386 Packages
Fetched 30.6 kB in 4s (6695 B/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '2.19-0ubuntu6.7' for 'libc6:i386' was not found
E: Version '4.8.4-2ubuntu1~14.04.1' for 'libstdc++6:i386' was not found
E: Version '8u72-b15-1~trusty1' for 'openjdk-8-jdk' was not found
INFO[0061] The command [/bin/sh -c dpkg --add-architecture i386 &&     apt-get update -y &&     apt-get install -y software-properties-common &&     add-apt-repository -y ppa:openjdk-r/ppa &&     apt-get update -y &&     apt-get install -y libc6:i386=2.19-0ubuntu6.7 libncurses5:i386=5.9+20140118-1ubuntu1 libstdc++6:i386=4.8.4-2ubuntu1~14.04.1 lib32z1=1:1.2.8.dfsg-1ubuntu1 wget openjdk-8-jdk=8u72-b15-1~trusty1 git unzip &&     rm -rf /var/lib/apt/lists/* &&     apt-get autoremove -y &&     apt-get clean] returned a non-zero code: 100

```

**Expected result:** I'd like to build the Signal from scratch including the docker image build environment.

**Comment by micressor** [comment]
I'm sorry for the issue, I saw [that](https://github.com/WhisperSystems/Signal-Android/wiki/Reproducible-Builds#troubleshooting) only now.
> Troubleshooting
> If you cannot get things to work, please do not open an issue or comment on an existing issue at GitHub. Instead, ask for help at https://whispersystems.discoursehosting.net/c/development

**Comment by 2-4601** [comment]
Thanks, feel free to open a topic at the forum!
