### ISSUE TITLE
Feature Request: Storage location

### ISSUE THREAD

**Issue by LoveIsGrief** [WhisperSystems/Signal-Android#6657]
Hi,

Looking at the guidelines, I wasn't able to find how to request features and there are other ones here, so...

# Problem

Devices with small storage and external SD cards have no possibility of using the external SD unless the phone is rooted (sometimes not even then).

# Solution

Add option for user to select where the messages, etc. will be stored. Especially with the possibility to send media, this will come in handy to offload the main storage.

As an added bonus, this is a feature WhatsApp doesn't have and seems to be reluctant to implement so that would be something they don't have.

**Comment by FeuRenard** [comment]
Very similar: #4297

**Comment by LoveIsGrief** [comment]
Thanks @FeuRenard , I'll close this in favor of that one. I hope others will find it too.
