### ISSUE TITLE
How to return from Emoji to normal keyboard?

### ISSUE THREAD

**Issue by charlesmchen** [WhisperSystems/Signal-Android#6662]
I entered emoji mode and couldn't figure out how to return to normal text input.

![exit emoji](https://cloud.githubusercontent.com/assets/625803/26253347/10e659d6-3c81-11e7-955c-af669e426d33.jpg)

**Comment by haffenloher** [comment]
Looks like this is your keyboard's emoji mode, not Signal's own emoji drawer, so there's probably nothing we can do about this.

**Comment by johanw666** [comment]
Does swiping the text row below to the right or left reveal other options than "Emoji, Emoji art, Emoticon"?

**Comment by moxie0** [comment]
Yeah that's your Android device's built-in keyboard, the Signal emoji keyboard still hasn't been activated (smiley face in the compose text)
