### ISSUE TITLE
4.6.0 Outgoing MMS Failed to send / Not delivered

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-Android#6663]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
MMS shows as not delivered on Signal 4.6.0

### Steps to reproduce
- Compose MMS to a contact
- Hit Send

**Actual result:** Not delivered
**Expected result:** delivered

### Device info

**Device:** Galaxy S4
**Android version:** 5.0.1
**Signal version:** 4.6.0
EDIT: **Provider**: Verizon Prepaid

### Link to debug log

Log 1: https://gist.github.com/anonymous/9c439feae61ecd2654531b91a801bb6a
Log 2: (looks like it does not contain MMS sent info) https://gist.github.com/anonymous/562e293246b3ac6c9cd78e8dbedc2378

**Comment by moxie0** [comment]
What carrier? The response is 132, which is `RESPONSE_STATUS_ERROR_SENDING_ADDRESS_UNRESOLVED`... whatever that means. Can they send MMS using the stock MMS app?

**Comment by riyapenn** [comment]
Confirming that it is Verizon Wireless, and checking w.r.t stock MMS app

**Comment by riyapenn** [comment]
For the two logs above, it is Verizon Prepaid wireless and MMS works with the stock app. 

Second user: https://gist.github.com/2748a2d7fc4204295fac12adde8b9743
provider unknown, MMS worked prior to the update to 4.6.0, will add more information here through an update

**Comment by mcbanderson** [comment]
I'm running into the same issue, however in my case messages are only failing to send for group chats. I have same device and carrier as @riyapenn.

Device: Galaxy S4
Android version: 5.0.1
Signal version: 4.6.0
Carrier: Verizon

Log: https://gist.github.com/c8fa7366d6ce238b57eaf6e61e15d952

**Comment by czchmate** [comment]
I can send MMS, but can't receive from others (it might just be with iPhones). This goes for group texts and for multimedia (e.g. photos). MMS between Signal applications works fine.

The in-built default messaging application works as normal.

Did Verizon change their APN settings or something?

Device: Motorola Droid Maxx
Android: 4.4.4
Signal: 4.6.0
Carrier: Verizon

**Comment by martincw2** [comment]
Same issue.  Originally seen on my wife's phone(exactly same as mine) on Saturday(5/20) error receiving MMS picture from AT&T user.  Yesterday she was experiencing issues with group text MMS messages.  Today I encountered issue receiving group text.  I was able to send a picture message to my wife earlier today with both Signal and stock messaging app.  She received both pictures; the one sent with Signal and the one sent via stock messaging app after changing her default to the stock messaging app.

I had a co-worker send me a picture message.  I captured two logs from my phone.  The first was immediately after my phone notified of the message. The second was after the first capture had completed, I opened the conversation and clicked the button to attempt to download the failed MMS message.  

Log 1: [https://gist.github.com/anonymous/4ec3119f018a1e19975ca69d89ba3402](https://gist.github.com/anonymous/4ec3119f018a1e19975ca69d89ba3402)
Log 2: [https://gist.github.com/anonymous/de92b8a89d2aa24b3f44d059ac3dd00b](https://gist.github.com/anonymous/de92b8a89d2aa24b3f44d059ac3dd00b)

Device: HTC One
Android: 5.0.2
Signal: 4.6.0
Provider: Verizon

**Comment by moxie0** [comment]
Hmm, I went and bought a MotoG on a Verizon prepaid plan, and unfortunately MMS works on it. 

I think I have a Galxy S4 somewhere, but it's GSM not CDMA.

I'll have to try to find a CDMA device that doesn't work.

**Comment by jesssssser** [comment]
Having the same issue as @riyapenn

Device: Galaxy Note 3
Android version: 5.0.1
Signal version: 4.6.0
Carrier: Verizon

Failed sending picture to non signal user:
https://gist.github.com/anonymous/85f5ce0687d92244206fb8246981d680

Failed sending group message to non signal users:
https://gist.github.com/anonymous/235187c3c60d5854476382ad130007ec
Screen shot

https://imgur.com/a/n0bFa


Reinstalled app and restarted device with no avail.

**Comment by moxie0** [comment]
Or if anyone having this problem on a verizon device has a rooted phone they can run tcpdump on, that would also help!

**Comment by martincw2** [comment]
What do you need me to do?  My phone is rooted.  It is the HTC One M7 above.  Just log and try to receive a message?

**Comment by moxie0** [comment]
@martincw2 I think you're referring to #6668? Do you also experience failure sending MMS?

**Comment by martincw2** [comment]
Apparently I was.  Sorry.  I had not tested sending MMS picture to a non-signal user until just now and it seems to work fine.  It took longer than I expected, but it shows a check mark indicating that it sent.  The recipient did not reply yet, but he may not be near his phone.  I just created a group with two non-signal users in it and sent a test message.  It seemed to take quite a while too, but the check mark appeared, indicating that it sent.

**Comment by jesssssser** [comment]
https://imgur.com/a/CeZjn

Here are some screenshots​ of the failed outgoing MMS messages (works fine
when communicating with other signal users).



This problem developed roughly a week ago. Until then everything worked
great!

I appreciate your help! Do you guys have a BTC donation address? Should I
reference this incident number??


Thanks again.
