### ISSUE TITLE
Signal crashes when trying to confirm location to be send while map has not loaded

### ISSUE THREAD

**Issue by Rolf558** [WhisperSystems/Signal-Android#6671]
Hi,

Signal 4.6.0 has introduce a confirmation dialogue when sending locations. If I try to confirm a location during bad network conditions (so that Signal fails to load the map) Signal crashes.

![capture _2017-05-22-14-58-38](https://cloud.githubusercontent.com/assets/23729466/26342047/c563b792-3f96-11e7-8040-2f5de3beccf2.png)
![capture _2017-05-22-14-59-01](https://cloud.githubusercontent.com/assets/23729466/26342052/c8960d20-3f96-11e7-9384-124059ae9ef7.png)

**Comment by moxie0** [comment]
Thanks @Rolf558, could you include a debug log and the rest of the issue template?

**Comment by Rolf558** [comment]
@moxie0 please find the link to the cat.log below:
https://gist.github.com/890b42303aef3a8bfd451a8863d40086

Do you mean complete screenshots with "issue template"?
In the first one I have cut the identity. The second one seems to be an Android limitation only making a screen capture of the overlay window.

Btw... tapping very fast (so that there is not enough time for the map to load) it is possible to provoke the crash on normal network conditions too.

**Comment by FeuRenard** [comment]
> Do you mean complete screenshots with "issue template"?

This is meant by "issue template":


I have:
- [ ] searched open and closed issues for duplicates
- [ ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Screenshots



### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

### Link to debug log

**Comment by Rolf558** [comment]
**Bug description**

Signal 4.6.0 has introduce a confirmation dialogue when sending locations. If I try to confirm a location during bad network conditions (so that Signal fails to load the map) Signal crashes.

**Steps to reproduce**

1. Set your mobile device to "flight mode" (just for easier reproduction of the bug)
2. In a chat tap  paper clip button
3. Tap "Location"
4. Tap "Select this location" (Maybe this is not the correct translation because my Google Maps uses German language.)
5. Tap on "Select" (Maybe this is not the correct translation because my Google Maps uses German language.)

Please note:
On bad network conditions or when doing step 5. quickly the crash is also provoked with "flight mode" off. I found this bug first time with "flight mode" off on bad mobile network conditions. I added step 1. with the "flight mode" on just for easy reproduction. 

**Actual result:**

Crash

**Screenshots**

See above.

**Device info**

Device: LG G5 SE
Android version: 7.0
Signal version: 4.6.0
Link to debug log:
https://gist.github.com/890b42303aef3a8bfd451a8863d40086
