### ISSUE TITLE
Feature request: disable "Invite to Signal"

### ISSUE THREAD

**Issue by dmnc-net** [WhisperSystems/Signal-Android#6674]
Duplicate to #4471 and #4436.

In some cases this invitation is not good. I'd like to include Signal to our "corporate standard apps" but I need to disable this feature. We need application which is acting like stock SMS app from the 1st view and without hiding this invitation tooltip we can't use the Signal. Our staff is texting to new recipients almost every time and we can't push our customers to do something.

**Comment by p4nci** [comment]
you mean "Settings -> Chats and media -> Show invitation prompts"

**Comment by dmnc-net** [comment]
... yes, I'm sorry
 :man_facepalming:
