### ISSUE TITLE
Verizon is using an illegal MCC for tests in the APN list

### ISSUE THREAD

**Issue by E3V3A** [WhisperSystems/Signal-Android#6680]
For some reason, someone (Verizon?) has decided to use the MCC for [Lithuania](https://en.wikipedia.org/wiki/Mobile_country_code#Lithuania_-_LT) for its test APN list as found in both lists under `apnlists`, such as in [cyanogenmod.xml](https://github.com/WhisperSystems/Signal-Android/blob/master/apntool/apnlists/cyanogenmod.xml#L376-L383). The available [MCC's for the US](https://en.wikipedia.org/wiki/Mobile_country_code#United_States_of_America_-_US) are: between `310-316`.  In addition the MNC's  `81` and `081` are non-existent, and must have been invented. 

Please remove these lines.

**Comment by haffenloher** [comment]
What exactly is the bug you're trying to solve by having these lines removed? If, as you say, the MNC doesn't exist, they should have no effect anyway.

**Comment by E3V3A** [comment]
IDK what kind of bugs this could cause, since I haven't looked into why this list is here (or how it's used) in the first place. Phones are supplied with their own lists. But surely, a provider from one country, trying to pretend to be from a different country (where they are not even present) is illegal. So if Signal is to continue to proclaim itself as a privacy/security app, I think it should at least conform to the basics. 

Given my previous work with IMSI-catchers, I'm rather curious to the history of those APNs.

**Comment by haffenloher** [comment]
Looks like there is no bug then. The apn db is queried based on the mcc, mnc, and apn fields. A row with a non-existent mnc will never be accessed.

Please close this issue. If you insist on discussing this further, I invite you to do so over at the [community forums](https://whispersystems.discoursehosting.net/). Thanks!

**Comment by E3V3A** [comment]
@haffenloher 
> Please close this issue. If you insist on discussing this further, I invite you

There is nothing to discuss. So, I guess this is exactly the way garbage propagates. If not used, then leave it in. Then eventually someone decide to use the garbage for some other purpose, and suddenly you have a new attack vector. If you want to close the issue without fixing, feel free to do so. I don't agree, so I'll leave it open until then.
