### ISSUE TITLE
Screen Protection is confusing when trying to take a screenshot.

### ISSUE THREAD

**Issue by charlesmchen** [WhisperSystems/Signal-Android#6683]
I wanted to take a screenshot. I held down power+volume and saw and indicator: "screenshot not taken".  I didn't understand if that indicator came from Android or Signal, and I didn't realize that this was because of Signal's screen protection.  

Suggestion: Elaborate "screenshot not taken" message to read "screenshot not taken due to screen protection. This can be disabled in Settings > Privacy.".

**Comment by moxie0** [comment]
Sadly the toast you're seeing is generated by the OS (so we can't edit the copy), and there's no API for us to detect that the user attempted to take a screenshot. Some apps can guess based on a file observer in the screenshot's directory, but in the case where a screenshot fails, no file would be generated. I think the only thing we can do is to disable "screen protection" by default, which iirc there's already an open issue for.
