### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by afaideen** [WhisperSystems/Signal-Android#6688]
Always thrown error here,
 Error:(365, 0) Process 'command 'git'' finished with non-zero exit value 128
<a href="openFile:H:\Google\SignalPrivateMessenger\Signal-Android-master\build.gradle">Open File</a>
![image](https://cloud.githubusercontent.com/assets/12533089/26570006/9aef3612-4540-11e7-9c77-32705d451cb7.png)

**Comment by nrizzio** [comment]
The issue tracker is for bugs, but you can post at https://whispersystems.discoursehosting.net for help with setting up your build environment.

**Comment by afaideen** [comment]
i seek for someone expert to help me how to build it in Android please. I followed exactly the instruction but finding myself keep getting the error above. It's such a hard time.

**Comment by FeuRenard** [comment]
You renamed the project folder to "Signal-Android-master" (from "Signal-Android"). Could this potentially pose a problem?

**Comment by afaideen** [comment]
i didn't renamed anything. Just follow the default setting.

**Comment by moxie0** [comment]
Looks like you either don't have git installed or aren't building this from a git repo.

Thanks for being interested @afaideen but we don't use this issue tracker for Q&A or for help with build environments. You can check out the forums for things like that.
