### ISSUE TITLE
Consistent crash opening large conversation

### ISSUE THREAD

**Issue by charlesmchen** [WhisperSystems/Signal-Android#6696]
This is a conversation with a large number of messages.

https://gist.github.com/anonymous/05623362da945e11ec2076e0516e00ea

**Comment by Trolldemorted** [comment]
duplicate of #6661 and 6660?

**Comment by nrizzio** [comment]
The stack traces are very similar, so I'd wait to see if the next release fixes it.

**Comment by charlesmchen** [comment]
Closing in favor of  #6661
