### ISSUE TITLE
Split long messages to a few messages while you are writing or pasting them

### ISSUE THREAD

**Issue by ghsrcgh** [WhisperSystems/Signal-Android#6699]
Please do like in Telegram messenger: remove a limit for a single message (currently it is a 2000 symbols and very annoying). Just split long messages to a few messages while you are writing them or pasting them (when you try to copy/paste long text to a Telegram, it automatically splits and sends to a few messages).

**Comment by nrizzio** [comment]
Relates to #5146 and #6692

**Comment by FeuRenard** [comment]
Duplicate of #4230
