### ISSUE TITLE
Message received notification is a lie. No way for recipient to reset connection.

### ISSUE THREAD

**Issue by edent** [WhisperSystems/Signal-Android#6703]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

I sent an encrypted message. I see two ticks indicating that it has been delivered. 
![signal1](https://cloud.githubusercontent.com/assets/837136/26759167/7bc61dc6-48ee-11e7-81e0-297983511208.png)

The recipient received the error "Message encrypted for non-existing session"
![signal2](https://cloud.githubusercontent.com/assets/837136/26759169/7bca97a2-48ee-11e7-8084-95770d0b9b78.jpg)

The recipient couldn't send me a message saying there was an error, so tried resetting the secure connection.

That didn't work.

It turns out that the *Sender* has to reset the connection - but there's no indication in the UI that is what is needed.

![signal3](https://cloud.githubusercontent.com/assets/837136/26759168/7bc7bee2-48ee-11e7-9220-cba97d21e542.jpg)

### Steps to reproduce
- Send message
- Get notification of delivery - which is a lie
- Spouse gets annoyed
- Try to work out how Signal has broken itself
- Go through menu options, get frustrated
- Read online help, get more frustrated
- Switch to Telegram which seems to work just fine

**Actual result:** Messages aren't delivered. Notification lies. No information for sender that there is a problem.
**Expected result:** "Hey, looks like the message didn't go through. Click here to reset your connection!"

### Device info

**Device:** Nexus 6
**Android version:** 7
**Signal version:** 4.6.1

**Comment by moxie0** [comment]
Hey @edent, thanks for the report. Sorry that you're having trouble, have you or your contact ever used any kind of tool like Titanium Backup, or are either of your devices rooted? When you say that your contact was "unable to send you a message," what do you mean by that? In what way were they unable?

**Comment by Wikinaut** [comment]
About one week ago, with a usually 100& % reliable contact, I encountered the same problem (for two signal messages, the sender received two check marks for each message, but the receiver got twice "message is encrypted for non-existing session" for each.

As far as I remember, the situation was resolved a day later when I sent a further message, which then was delivered. 

Both smartphones are of type

* HUAWEI P8 Lite
* Android 6.0 (Patch 20170301)

**Comment by moxie0** [comment]
@edent Also is it possible that you changed phone numbers at some point without reinstalling? As in, unregistered and then re-registered with a different number?
