### ISSUE TITLE
Crash after tapping lock screen notification

### ISSUE THREAD

**Issue by FeuRenard** [WhisperSystems/Signal-Android#6706]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashes when entering a conversation via new message notification from lock screen.
It's definitely not the first time that I encountered such a crash.

### Steps to reproduce
I cannot reproduce the crash. But here is what I did:
- Receive a new message while phone is locked
- Turn on the screen
- Double tap the notification
- Enter Android PIN (because the screen is still locked)

**Actual result:** Signal crashes without visibly appearing. There is just a system dialog which offers to send a crash report.
**Expected result:** Signal opens showing the conversation with the new message.

### Device info

**Device:** Fairphone 2
**Android version:** 6.0.1
**Signal version:** 4.6.1

### Link to debug log
https://gist.github.com/anonymous/d2fc6ab17fcbc9b4a9bcf84ae80fa32b

**Comment by cascheberg** [comment]
Debug log looks similar to #6283, which has a pending PR
