### ISSUE TITLE
Call quality degrades into choppy playback when both people talk at the same time

### ISSUE THREAD

**Issue by Nubzori** [WhisperSystems/Signal-Android#6708]
I have:
- [ x] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

When two people talk at the same time (or when talking overlaps eachother) android user's voice quality goes down and voice starts to become choppy. One must wait for another to finish talking otherwise they can't hear clearly.

I've tried Pixel XL into iPhone 5S, Nexus 5X into iPhone 5S. HTC One M8 to Pixel XL. All same results. Only iPhone 6s to 5s works without problems. Using relayed calls from signal servers does not help.

Only the device running android gets choppy, I can always hear the iPhone user fine. Both got choppy when called from android to android. 

### Device info
**Device:** Pixel XL
**Android version:** 7.1.2
**Signal version:** 4.6.0, 4.6.1

**Comment by bl-kl2** [comment]
Same here.
Moreover, often the audio call quality degrades for some seconds.
It always happens.
Verified on 5 Android phones so far.

Android phones referenced by the the below logs, both with Signal 4.6.1:
Sony Xperia X Compact - Nougat 7.0
BlackBerry KEYone - Nougat 7.1.1

If, instead, I use Iphone SE, 6s, 7p, all the Iphones calling each other work flawlessy,
no choppy playback sound while talking, and no sound degradation at all during calls.
Signal version on Iphones: 2.12.2

debug files here:

Sony X Compact:
[https://gist.github.com/fe9f35e303d50902d44df910a665b487](https://gist.github.com/fe9f35e303d50902d44df910a665b487)

BB KEYone:
[https://gist.github.com/44861948bc656b51e5ee1fa6e0cbde8a](https://gist.github.com/44861948bc656b51e5ee1fa6e0cbde8a)

**Comment by moxie0** [comment]
I'm going to consider this a duplicate (same root cause) as #6737 and there's more discussion there.
