### ISSUE TITLE
Unencrypted phone calls ?

### ISSUE THREAD

**Issue by Cr4zyPh1l** [WhisperSystems/Signal-Android#6713]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] contacted https://support.whispersystems.org/

----------------------------------------

### Bug description
I've browse the Android Signal App's source code, and I haven't seen anywhere where phone calls are encrypted. Especially how and with which algorithm.
I suppose that the encryption, if there is one, is used from WebRTC. However, I haven't seen the used algorithm in the Session Description when I was debugging the app.

Accordingly to https://whispersystems.org/blog/signal-video-calls-beta/, the **signaling** of calls are **effectively encrypted** through the Signal protocol. However, in the Session Description, there is **_no encryption_** information to **_encrypt streams_**. Normally, if the Session Description is correctly written (with encryption), there is a "a=crypto:1 AES_128_GCM inline:[Key+Salt] ..." somewhere in it.
Here, this line is missing.

Can you explain me how the streaming encryption is done, with which algorithm and where are lines in source files ?

Sorry for my english.

Have a good day :)
### Steps to reproduce
Not applicable. Work as designed.

### Screenshots
Not useful.

### Device info
Source code issue. No specific device.
Issue on Signal version 4.5.2, 4.5.3 and 4.6.0. Newer and older not checked, but I think it's the same.

### Link to debug log
No log.

**Comment by sigenc** [comment]
webrtc

**Comment by Cr4zyPh1l** [comment]
Ok, because in the source code of WebRTC, there is 4 encrypting algorithms. However, in the Signal's source code, there is anywhere explicit ranking of algorithm. For example use AES_128_GCM instead of AES_CM_128_HMAC_SHA1_32/80.

**Comment by moxie0** [comment]
Thanks for being interested @Cr4zyPh1l but we don't use GitHub for Q&A, discussion, or support: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#issues

Please see the mailing list, online forums, or support center for any of those.
