### ISSUE TITLE
Syncing with other android devices?

### ISSUE THREAD

**Issue by Enigma0** [WhisperSystems/Signal-Android#6714]
Since one can sync the Chrome extension it seems like the infrastructure is already in place.

Is secondary android device syncing coming?

**Comment by NinebitX** [comment]
Duplicate: https://github.com/WhisperSystems/Signal-Android/issues/5102

**Comment by Trolldemorted** [comment]
if you want to test or help: https://github.com/Trolldemorted/Signal-Android/commits/multidevice

**Comment by moxie0** [comment]
Closing as duplicate
