### ISSUE TITLE
Feature request: Option for Data only / SMS only / Both

### ISSUE THREAD

**Issue by LoveIsGrief** [WhisperSystems/Signal-Android#6716]
# What

An option allowing the user to choose how messages should be sent. For encrypted chat all 3 options would be available. For unencrypted chat only SMS would be available.

# Why

A person

 - has ran out of data --> SMS
 - has ran out of free texts --> data
 - doesn't care --> both
 - wants more control
 - has a good package and can use both at any time
 
-------------------------------

I haven't read up on the protocol, but I assume the encryption is end to end and since this once was called TextSecure, encrypted texts should still be possible.

**Comment by haffenloher** [comment]
Hey @LoveIsGrief, this is probably a duplicate of many existing issues :)
You might be interested in
https://whispersystems.org/blog/goodbye-encrypted-sms/
https://support.whispersystems.org/hc/en-us/articles/212535548-How-do-I-send-an-insecure-SMS-

If you want to discuss this further, I think the best place would be the [community forums](https://whispersystems.discoursehosting.net/).

**Comment by LoveIsGrief** [comment]
Thanks for the links @haffenloher . Although I do not necessarily agree with the decision to get rid of encrypted texts, I understand it.

And with that the issue is resolved.

Cheers!
