### ISSUE TITLE
High battery usage, running in the background

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-Android#6717]
I have:
- [X] searched open and closed issues for duplicates, 
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports but I find that the information available may be insufficient :(

----------------------------------------

### Bug description
High battery usage

### Steps to reproduce
- message with contacts
- no particular action in the app
- use other apps, leaving Signal in the background
- check permissions and see alert "designed for an older version of Android"

**Actual result:** Higher than expected battery usage
**Expected result:** less battery usage

### Screenshots

<img width="206" alt="screen shot 2017-06-08 at 10 35 57 am" src="https://user-images.githubusercontent.com/4898366/26942275-4ec449b0-4c36-11e7-9318-a897cfcb041c.png">

### Device info 
**Device:** Galaxy Note 5
**Android version:** 7.0
**Signal version:** 4.6.1
**Provider:** Tmobile

### Link to debug log
 https://gist.github.com/3aa9ee2987039bd32948516f29fd2e96

**Comment by Trolldemorted** [comment]
An awful lot of early receipts.

Iirc receipts are "generated" by the server if the recipient confirms the delivery, maybe it is a server issue?

**Comment by theBoatman** [comment]
I can confirm that signal has a high battery usage (at least on my phone, without gapps), even if I never touch the app and no message is received. The battery usage is usually three times the amount K9 uses, which has a very similar task. (Open push connection, waiting for messages.)

**Comment by Trolldemorted** [comment]
is your log spammed with receipts too?

**Comment by theBoatman** [comment]
Not at the moment. But I have a lot of EOFExceptions, so perhaps there are two seperate problems:
https://gist.github.com/anonymous/216fae3f5f7857c88eee3af101b54c83

**Comment by theBoatman** [comment]
I monitored this over the weekend, and I had still no receipts. So the question is: should I open a new  issue for the EOFExceptions or should all battery usage problems be collected in this issue?

(Another log, but very similar to my last one.)
https://gist.github.com/anonymous/efd6d9b9ae725b831134654ff3250bd2

**Comment by moxie0** [comment]
@riyapenn Is this issue for a user with or without play services?

**Comment by Trolldemorted** [comment]
@theBoatman that looks more like a network issue to me, so i'd suggest you open a seperate issue.

**Comment by riyapenn** [comment]
Closing this issue until further response from the original user.
