### ISSUE TITLE
APK hash doesn't match website

### ISSUE THREAD

**Issue by ghost** [WhisperSystems/Signal-Android#6721]
I'm attempting to verify the download on your official channel: https://whispersystems.org/android/apk/

The sha256 hash of the downloaded APK doesn't match the fingerprint posted on the website `29:F3:4E:5F:27:F2:11:B4:24:BC:5B:F9:D6:71:62:C0 EA:FB:A2:DA:35:AF:35:C1:64:16:FC:44:62:76:BA:26`

The instructions are unclear, does the above hash correspond to a simple hash of the .apk file, or do I need OWS's public key? It's not immediately obvious where to find it.

A better setup would be to host an F-Droid repo so you could push prompt, secure updates to your users using an alternative download channel. Thanks :)

**Comment by haffenloher** [comment]
Hey @lnlllcsq, that's the fingerprint of the signing certificate.
If you want help with verifying the signature, have a look at [this thread in the community forums](https://whispersystems.discoursehosting.net/t/how-to-get-signal-apks-outside-of-the-google-play-store/808/19?u=haffenloher). If you have further questions, feel free to ask them in the forums as well (we try to use Github for issue tracking only, not for discussion). Thanks!

**Comment by lnlllcsq** [comment]
Thank you, that information should really be on the same page as the download.

https://whispersystems.org/android/apk/

**Comment by haffenloher** [comment]
Hey @mrt7, as I wrote above, please keep questions and discussion to the [community forums](https://whispersystems.discoursehosting.net/). I'll be happy to answer your question there!

This issue can be closed.
