### ISSUE TITLE
Unable to send or receive MMS with two Cricket phones

### ISSUE THREAD

**Issue by LvxOne** [WhisperSystems/Signal-Android#6724]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When a non-Signal user sends MMS to either of two phones using Signal Private Messenger with Cricket service, message fails to download. The following error is received:

"Error downloading MMS message, tap to retry"

Tapping to retry also fails.

When attempting to *send* an MMS message to a non-Signal user, the message "Not delivered" is received. Tapping for details shows the message "Failed to send" and tapping "RESEND" also fails to send message.

Each phone's standard messaging app is able to send and receive MMS successfully.

Troubleshooting steps that did not resolve the issue:
- Using data vs Wi-Fi
- Disabling data network and only using Wi-Fi
- Restart phone
- Uninstall / reinstall Signal
- Reset APN information from Cricket
- Enable 'WiFi Calling' compatibility mode

Settings in use
- Receive all SMS & Receive all MMS / SMS Enable (Signal is set as default messaging app)
- SMS deliver reports are disabled
- "Manual MMS settings" are all set to default

### Steps to reproduce
- Receive MMS message (from non-Signal user)
- View message "Error downloading MMS message, tap to retry"
- Tap the MMS button to retry
- Message attempts to download but is never successful

**Actual result:** MMS messages are not received
**Expected result:** MMS messages should be received and downloaded.

### Device info

**Device 1:** HTC One S (HTC VLE_U, from T-Mobile)
**Android version:** 4.1.1
**Signal version:** 4.6.1

**Device 2:** Samsung Galaxy S4 (SGH-M919, from T-Mobile)
**Android version:** 4.4.4
**Signal version:** 4.6.1

### Link to debug log
Device 1:
https://gist.github.com/cffa944e6416c6dafda2b4cffd5122fd

Device 2:
https://gist.github.com/0e39d8b53302fbe3620db2fcfdecea15

**Comment by amavarick** [comment]
What was the solution to this?

**Comment by jamesnuanez** [comment]
@amavarick On one of the subsequent updates it started working again.
