### ISSUE TITLE
Absence of federation

### ISSUE THREAD

**Issue by Lucas-Developer** [WhisperSystems/Signal-Android#6725]
Absence of federation

**Comment by sigenc** [comment]
It no longer depends on gcm
You don't have to give permission for contact discovery
Redphone is gone
federation will only happen if somebody prove moxie wrong > so go ahead

**Comment by Lucas-Developer** [comment]
There is a modified version of Signal, called LibreSignal, that removed the Google dependency that the Signal application has, allowing Signal to run on other devices (Android), such as CopperheadOS, or Jolla phones (with the Android compatibility layer). However, Moxie made it clear that he does not want LibreSignal to use Signal's servers, and that he does not approve of the name. The name is something that can change, not a problem. What is a problem, though, is the fact that he does not want LibreSignal using the Signal servers. Which would be OK, if it allowed LibreSignal to federate between its own servers. This was attempted once (with the Telegram, more than all the others), but then abandoned, why Moxie believes that this will read changes to the application and / or protocol.

The whole problem with your position, however, is that I do not see the point of doing any of these secure messaging things without federation. The internet was built over federation. Multiple email providers and servers, for example, can communicate effortlessly with one another so that I can email someone who has a Gmail address, or a corporate address, etc. effortlessly, And everything works. This works because of federation, because protocols are all open standards, and there are multiple implementations of standards that can cooperate and communicate together. Another example would be the Jabber / XMPP protocol, which also has multiple clients on multiple platforms, which can communicate securely with each other, despite having one Jabber account on one server different from the other.

If we do not federate, if we do not cooperate, what will prevent the internet from becoming a lot of walled gardens again? Is the Internet nothing more than just a platform for choosing certain proprietary silos services? The Signal then is only a silo (partially proprietary) in which your messages are transmitted securely.

**Comment by haffenloher** [comment]
:pray: Please respect the contributing guidelines, this is not a discussion forum. Just use the search engine (everything on these topics has been said multiple times before) or take it to [the forums](https://whispersystems.discoursehosting.net/) if you must.

**Comment by Lucas-Developer** [comment]
Ready

**Comment by Lucas-Developer** [comment]
https://whispersystems.discoursehosting.net/t/absence-of-federation/1106?u=lucas-developer
