### ISSUE TITLE
[Feature request/Suggestion] Clear text input function (quick "delete text" button)

### ISSUE THREAD

**Issue by Wikinaut** [WhisperSystems/Signal-Android#6728]
Quite often when "sharing" a clipboard (text) with the Signal App I noticed that the text is inappropriate or more simply, I decided *not* to send this text.

I have to mark and delete the text.

It would be easier, if the text input has a button(marked with "X" or a delete symbol), so that the text could be quickly deleted by clicking the button or symbol.

**Comment by haffenloher** [comment]
> It would be easier, if the text input has a button(marked with "X" or a delete symbol), so that the text could be quickly deleted by clicking the button or symbol.

That would introduce a new problem, though: people would occasionally tap this button by accident. Not sure if that's worth it, considering that double-tapping a word, pressing "select all" in the action bar, and then deleting the text isn't that much of a hassle.

**Comment by Wikinaut** [comment]
I mean deleting a whole "paste", e.g. several lines of text.

**Comment by FeuRenard** [comment]
This is a duplicate of #6548.

**Comment by Wikinaut** [comment]
Yes!
