### ISSUE TITLE
Disappearing messages still appear on desktop app days later

### ISSUE THREAD

**Issue by samanthablasbalg** [WhisperSystems/Signal-Android#6730]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When using the desktop app, when a person sends me a message, the chat window jumps to a section of disappearing messages from a week ago. The disappearing timer was set to five minutes. The messages disappeared from my phone correctly, but they are still visible on my computer. The messages have also disappeared on the phone and computer of the account that they were sent to.

### Steps to reproduce
Unfortunately, I have never seen this before, so I am not exactly sure of the steps to reproduce it. 
Here are the repro steps from my end that made this happen:
- Send messages from Android (OnePlus 3T phone, Signal v 4.6.1)
- Messages were received on Android (Google Nexus 5 phone)
- Use Signal Desktop a week later on a Mac (macOS Sierra 10.12.5, Chrome 58.0.3029.110)

**Actual result:** Messages that were supposed to disappear are still visible
**Expected result:** Secure messages should disappear from all devices

### Screenshots
In the screenshot you can see the text about turning on and off disappearing messages but also the timestamp showing that the messages occurred last Monday:
<img width="629" alt="screen shot 2017-06-12 at 7 27 14 pm" src="https://user-images.githubusercontent.com/22916128/27059612-74144180-4fa5-11e7-842f-b929b05d8731.png">

### Device info
Computer:
**Device:** Macbook Pro, macOS Sierra 10.12.5, Chrome 58.0.3029.110
**Android version:** 7.1.1
**Signal version:** 4.6.1

### Link to debug log
The desktop app doesn't seem to provide debug logs. I can provide one from my phone, if that will be useful, but the bug doesn't appear on my phone.

**Comment by samanthablasbalg** [comment]
ETA: The messages did go away after restarting Signal on my desktop, but all of the rest of my messages were synced and up to date at that time, so I still think this is an unfortunate bug. I would not have known about it except for the fact that every time the person sent me a message, the window jumped up to the not-disappeared messages. Seems like a security problem to me if messages that people expect to disappear are lingering around.

**Comment by FeuRenard** [comment]
Please post this issue in [Signal-Desktop's issue tracker](https://github.com/WhisperSystems/Signal-Desktop/issues) and close this report.

**Comment by rainerzufall** [comment]
And please add debug logs to your report from your phone as well as from desktop. Here is how you can take a log from desktop: https://support.whispersystems.org/hc/en-us/articles/215188737-How-do-I-submit-a-debug-log-from-the-Desktop-

**Comment by moxie0** [comment]
Thanks for the detailed bug report @samanthablasbalg. This looks like an issue with the desktop client, though. Would you mind [posting it there](https://github.com/WhisperSystems/Signal-Desktop/issues) so the Signal desktop developers can take a look?
