### ISSUE TITLE
Incorrect "Tap for unsecured fallback" prompt

### ISSUE THREAD

**Issue by haffenloher** [WhisperSystems/Signal-Android#6734]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Testing current master @ 59d3e666. Got a message from a contact who has new safety numbers. Replying on my phone fails and offers unsecured fallback ("This message will not be encrypted because the recipient is no longer a Signal user"). The input text field still says "Signal message" and the contact still appears in the list of Signal contacts, even after a contact list refresh.

Sending messages from Desktop to this contact works fine.

### Steps to reproduce
- receive a Signal msg from someone with new safety numbers
- try to reply -> unsecured fallback 
- refresh contacts, try to reply -> same
- reply from desktop (works), try to reply from Signal-Android again -> still getting unsecured fallback prompt

### Device info
**Device:** FP1
**Android version:** 4.2.2
**Signal version:** master at 59d3e666 (edit: still happening at 52311eb8)

### Link to debug log
I think there's an unrelated crash in this log, I'll probably have to open another issue for that one.
https://gist.github.com/anonymous/90fbff8812f10e19f659ad12cf588a3b

**Comment by moxie0** [comment]
I don't see any send attempts in this log?

**Comment by moxie0** [comment]
I've been unable to reproduce this, I think I would need a log with a send attempt in it in order to see what's going on for you.

**Comment by haffenloher** [comment]
Indeed, looks like my log is pretty useless, sorry. It should cover multiple send attempts though... will try to find out what's going on using adb later today.

**Comment by haffenloher** [comment]
On a send attempt, the first call to [`getEncryptedMessage()`](https://github.com/WhisperSystems/libsignal-service-java/blob/54ff4a941d8188ffbce48326918cd4df31bbb61a/java/src/main/java/org/whispersystems/signalservice/api/SignalServiceMessageSender.java#L531) with `deviceId = 1` is successful. `store.containsSession()` is true, so no attempt is made to fetch prekeys.

The second call to [`getEncryptedMessage()`](https://github.com/WhisperSystems/libsignal-service-java/blob/54ff4a941d8188ffbce48326918cd4df31bbb61a/java/src/main/java/org/whispersystems/signalservice/api/SignalServiceMessageSender.java#L531) has `deviceId = 2`. Fetching prekeys fails with a NotFoundException causing an UnregisteredUserException. No idea why these weren't in the log.

Maybe the user used to have a linked desktop device, but doesn't anymore after re-registration? As I said, they still seem to be registered according to desktop and to the contact list (plus they can send messages). I can send you the contact's phone number via mail if needed.
