### ISSUE TITLE
[Group contacts] When adding new contacts, only a part of the secured signal-enabled contacts is shown and selectable

### ISSUE THREAD

**Issue by Wikinaut** [WhisperSystems/Signal-Android#6735]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

**Actual result:** After having created a new group with three contacts, when adding further new contacts, only a fraction of signal-enabled contacts are shown and selectable

### Steps to reproduce
- Provisionally, I stopped and restarted Signal ; and
- generated new index of contacts (Android Contact app)
- the bug is still present

**Expected result:**  I expected the whole contact list of my Signal contacts.

I compared the list (while adding contacts to an existing group) with the list when using to send a Signal message. My observation is:

List (when adding contacts to a group):

* A
* B
* ...
* Z

List (when sending to someone)

* A AnameWithA
* B BnameWithB
* ... (more entries)
* Z (until here, same as above)
* \#
* (space) +telephonenumber
* (space) +telephonenumber
* 1 1and1
* A
* B
* ..
* Z

The second part appears to be the correct full list of contacts.

## Bug
The selection - when selecting contacts to be added to a group - appears to show only the first part ("A"...."Z") of the list.

## Screenshots

n/a

### Device info

**Device:** Huawei P8 Lite
**Android version:** 6.0
**Signal version:** 4.6.1

### Link to debug log

n/a

**Comment by Wikinaut** [comment]
I only can suppose, that this is one of the old Signal problems with inconsistent number formats and/or inconsistent databases.

**Comment by p4nci** [comment]
hope I understood you correctly.
IMO, it's intended behavior and MUST have!
Mixing secured and UNsecured contacts in the same group it's not a good idea.
When you create a group for the first time, you can mix secured and unsecured contacts but this group will be a MMS-Group (warning on the top shows up and explain this). That's why you can add only Signal users to an existing Signal group. Otherwise the group must be converted to an MMS-Group and imo, this is very bad:
a) SECURITY
b) costs for MMS
=> imo, you can always create a new mixed (MMS) group

**Comment by Wikinaut** [comment]
@p4nci 
No. I specify (change) that now in the title. I do mean secured, signal-enabled contacts are missing.

**Comment by Wikinaut** [comment]
(I closed this by mistake, sorry. Reopened now.)

**Comment by p4nci** [comment]
@Wikinaut 
I suppose
1. you have SMS/MMS enabled (Signal Settings -> SMS and MMS is on)
2. in your second list (e.g. when sending to someone) all entries after the first A-Z (e.g. all numbers after #) are not Signal numbers (A-Z letters are gray not blue) 
3. if 1. and 2. then see my comment above

**Comment by Wikinaut** [comment]
@p4nci yes and no.

In the second part of the, yes, the [1-Z] characters are grey, however, many of them are secure(!) signal contacts, for example, my own 2nd, 3rd and 4th smartphones.

**Comment by Wikinaut** [comment]
@p4nci in other words: I have a lot of secure signal contacts which are listed in the second part of the list and which entries follow or have a "grey" character.

**Comment by p4nci** [comment]
@Wikinaut 
a) for bug fixing debug logs are always welcome :wink: 
b) do you use DAVDroid? There are some issues: https://github.com/WhisperSystems/Signal-Android/issues/4338, https://github.com/WhisperSystems/Signal-Android/issues/5079, https://github.com/WhisperSystems/Signal-Android/issues/4803
c) imo, your problem has nothing to do with groups. You can try also this https://github.com/WhisperSystems/Signal-Android/issues/4338#issuecomment-198157982

**Comment by Wikinaut** [comment]
@p4nci Your information

>  Go to Android Settings > Accounts > Signal > Menu > Remove Account > then Resync. Contact support@whispersystems.org for further troubleshooting.

was helpful.
