### ISSUE TITLE
Legal attribution to Google missing

### ISSUE THREAD

**Issue by mueller-ma** [WhisperSystems/Signal-Android#6736]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When reading the readme I cannot find "Google Play and the Google Play logo are trademarks of Google Inc." which is required when using the badge. https://play.google.com/intl/en_us/badges/
Also please set the height to 80.

**Comment by piratenpanda** [comment]
There is already a PR waiting for this https://github.com/WhisperSystems/Signal-Android/pull/6701
