### ISSUE TITLE
Verified indicator for groups

### ISSUE THREAD

**Issue by FeuRenard** [WhisperSystems/Signal-Android#6741]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
A verified indicator is displayed in the action bar of groups, whose members are all marked as verified. I don't know whether this is expected behaviour. If the indicator for groups is expected behaviour, its placement will have to be adjusted (IMHO).

### Steps to reproduce
- Create group
- mark all members as verified
- open group

**Actual result:** Verified indicator is shown on the second line of the action bar.
**Expected result:** Verified indicator is not shown at all (maybe because groups don't have SN?) or the indicator is placed in the same line as the group name.

### Screenshots
![screenshot_20170617-223037](https://user-images.githubusercontent.com/16167751/27256149-3ab71744-53ad-11e7-9486-da0ba6e219e5.png)

### Device info

**Device:** Fairphone 2
**Android version:** 6.0.1
**Signal version:** 4.7.0

**Comment by scienmind** [comment]
I agree with the point regarding indicator placement.

However, regarding the indicator itself -  if **all** members of the group have been verified, it would be reasonable to display an indicator that the group as a whole is "safe and verified", to differentiate it from a "less trusted" group which may have some unverified contact. Manually keeping track of the verification status of all group members is not that trivial.

**Comment by paride** [comment]
It would be great if groups could have a weaker form of verification, valid only within the group, where if A verified B and B verified C, then A considers C as verified. Again, only within the group.

I understand this is not trivial, but I think it's almost impossible to verify all group members for groups containing more than a handful of persons.

**Comment by p4nci** [comment]
@paride this is a kind of web of trust and contrary to [Development Ideology](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#development-ideology):
4. If it's "like PGP," it's wrong. PGP is our guide for what not to do.

**Comment by paride** [comment]
@p4nci I know and I don't think it's "like PGP": there are no signatures to maintain, no keyservers, no user interaction required, in the spirit of Signal. But I understand the complexities... or probably I don't, and that's kind of the point.

**Comment by FeuRenard** [comment]
Since https://github.com/WhisperSystems/Signal-Android/commit/65124fd1f2d459a6e40517bf3f572f68b554a783#diff-212a69ad5972e3fe8a7ee6419400f0b1R105 group member names are displayed in the conversation subtitle. Now the indicator placement looks fine for me:

![screenshot_20171225-222442](https://user-images.githubusercontent.com/16167751/34343145-81cc3796-e9c5-11e7-8b93-733c317ca9d8.png)
