### ISSUE TITLE
Marked verified status messages have sent checkmark

### ISSUE THREAD

**Issue by cascheberg** [WhisperSystems/Signal-Android#6743]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Contact verified status messages have the message sent checkmark displayed in the conversation list.

### Steps to reproduce
- mark a contact as verified
- check conversation list

**Actual result:** Verified message entry has one sent checkmark
**Expected result:** There should be no checkmarks

Same for marked as unverified status messages.

### Device info
**Signal version:** 4.7.0

**Comment by scienmind** [comment]
Related: https://github.com/WhisperSystems/Signal-Android/issues/6741
