### ISSUE TITLE
SMS based safety number verification

### ISSUE THREAD

**Issue by vvug** [WhisperSystems/Signal-Android#6746]
So here is the idea: now that we have persistent identity verification, an SMS based safety number verification can be implemented.

Of course this is not as good as a face-to-face meeting where the numbers are checked, but the only way to perform a MITM is to control both the Signal server and the mobile carrier, in order to manipulate the SMS message exchange. This is very unlikely (remember that the SSL certificate of the server is pinned).

I think that an attack of this kind is less likely than getting the device compromised. In this case encryption is not of any help.

**Comment by moxie0** [comment]
You can "share" and compare with clipboard for SNs, which allows you to do this with any channel you'd like (SMS, email, etc).
