### ISSUE TITLE
Allow for setting a nickname

### ISSUE THREAD

**Issue by vvug** [WhisperSystems/Signal-Android#6752]
Now that the concept of a user profile exists, please add support for setting the user's own nickname, to be shown to other users when they don't have the number in their contact list.

This is mostly useful (I'd say fundamental) in groups.

**Comment by bisam** [comment]
This is coming in the next version. https://github.com/WhisperSystems/Signal-Android/issues/4852#issuecomment-327275832

Guess you can close this issue.

**Comment by vvug** [comment]
In 4.10.0.
