### ISSUE TITLE
Cannot administer groups anymore after re-installing signal, groups are not synced to new device

### ISSUE THREAD

**Issue by mbiebl** [WhisperSystems/Signal-Android#6754]
I've been using an Android phone (Nexus 5) with the latest Signal version.

On this phone I created a group called "Family" where I was the admin: I could change the title, picture and members.

A couple of days ago the Nexus phone died.  As I had an older iPhone 5s, I used the SIM card from the old Nexus phone, installed  the latest Signal version on the iPhone and (re)registered the old mobile number.

None of the groups that I had created on the old Android phone were synced to the iPhone.
When someone posted a new message to the Family, a new group showed up on the iPhone labeled "Unknown group".  The group picture was not set and I can't edit the group anymore.

Was I doing something wrong? How can I make sure the existing groups are properly synced to the new device?

**Comment by mbiebl** [comment]
With properly I mean: All existing groups are synced to the new device, with proper title, picture and I'm still the owner for groups that I created with this mobile number.

**Comment by p4nci** [comment]
@mbiebl before submitting a new issue please search if someone has already opened an issue about the same topic, see [Submitting useful bug reports](https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports)
a) Signal groups don't have admins. Every group member can "change the title, picture and members"
b) this https://github.com/WhisperSystems/Signal-Android/issues/2581#issuecomment-253831947 will probably help solving your problem

**Comment by haffenloher** [comment]
> b) this #2581 (comment) will probably help solving your problem

This should work automatically by now (without any manual steps). If it doesn't, there's probably a bug on the iOS or Android side. (related: https://github.com/WhisperSystems/Signal-iOS/issues/1988#issuecomment-302695174)

> When someone posted a new message to the Family, a new group showed up on the iPhone labeled "Unknown group".

Which client were they using?

**Comment by mbiebl** [comment]
The desktop client (which was bound to an iOS device)

**Comment by mbiebl** [comment]
@haffenloher to be more specific: I used the desktop client. After reinstalling Signal on the iPhone, the desktop client popped up the QR dialog to register the device, which I did. The desktop client still showed the old groups, so I started a conversation in the Family group.
Later I noticed that Signal now showed an "unknown group" (which apparently was the Family group).
After resyncing contacts&groups in the desktop client settings, the group is now also labelled unknown in the desktop client

**Comment by michaelkirk** [comment]
Seems like this doesn't involved your android device, since you stopped using your Android device, to switch to iOS.

I've moved the issue to the iOS repository and can follow up with your there @mbiebl 

https://github.com/WhisperSystems/Signal-iOS/issues/2257

**Comment by p4nci** [comment]
> This should work automatically by now (without any manual steps). If it doesn't, there's probably a bug on the iOS or Android side. (related: WhisperSystems/Signal-iOS#1988 (comment))

well, #2581 (comment) probably works for all clients with or without "group info request"

@mbiebl 
This issue can be closed now :thinking:
