### ISSUE TITLE
Unregistered contact still marked as verified

### ISSUE THREAD

**Issue by cascheberg** [WhisperSystems/Signal-Android#6755]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When a contact, whose safety number was verified, unregisters from Signal, it is still marked as verified.

### Steps to reproduce
- verify safety number of contact A
- contact A unregisters from Signal
- check conversation with contact A: messages are sent as SMS

**Actual result:** Contact is still marked as verified. You can still access "view safety number" in conversation settings.
**Expected result:** Contact is not marked as verified. Option to view safety number is invisible.

### Device info
**Signal version:** 4.7.1

**Comment by FeuRenard** [comment]
If the contact re-registers (same phone, without uninstalling Signal in between) the safety number will stay the same. It will only change with a new installation of Signal. So I think it's okay to consider the contact verified still.

Nevertheless the verified marker is misleading in a conversation where only insecure messaging is possible (after unregistering).
