### ISSUE TITLE
Shutter button is too small/tiny/unusable via "Add attachment"/"Camera"

### ISSUE THREAD

**Issue by jaimet** [WhisperSystems/Signal-Android#6761]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Shutter button (="Shutter release button"?) is too small/tiny/unusable via "Add attachment"/"Camera".

### Steps to reproduce
- Create new message
- Tap menu key, choose "Add attachment", then "Camera"

**Actual result:** The "standard" camera app is opened, but the shutter button (shutter release button) is too small/tiny/unusable (see screenshot below)
**Expected result:** The "standard" camera app should be opened, but the shutter button should be its normal size.

### Screenshots

Here's the actual screenshot:
![actual](https://user-images.githubusercontent.com/8218065/27486295-060a93c0-5828-11e7-886c-1fb6d997cd22.png)

Here's the expected screenshot (this is just me opening the standard camera app):
![expected](https://user-images.githubusercontent.com/8218065/27486330-208d689e-5828-11e7-98ad-691f846ca668.png)

### Device info

**Device:** Samsung Galaxy S2 gt-i9100
**Android version:** 7.1.2 (Lineage build 7th June 2017)
**Signal version:** 4.6.1

### Link to debug log

https://gist.github.com/jaimet/f801d51df116961d59740cc00e7d3576

**Comment by FeuRenard** [comment]
Does this issue only occur with Signal? Did you try using the camera with other apps, too? E.g. the contacts app could also use the standard camera for taking contact pictures.

**Comment by mateoeh** [comment]
Pretty sure this is a LineageOS issue, not Signal

**Comment by piratenpanda** [comment]
Works fine on LineageOS here, latest weekly for the Nexus 6p

**Comment by moxie0** [comment]
That's your ROM's software. We're just firing the intent, don't have any control over what your OS does.
