### ISSUE TITLE
Messages sent from my Android device aren't showing on Signal-Desktop with latest Android beta 4.7.3

### ISSUE THREAD

**Issue by rainerzufall** [WhisperSystems/Signal-Android#6762]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Like recently posted by Dyras in https://github.com/WhisperSystems/Signal-Desktop/issues/1275: Messages sent from my Android device aren't showing on Signal-Desktop with latest Android beta 4.7.3. Messages sent from the Desktop are displayed correctly on my Android device.

### Steps to reproduce
I sent 2 messages to a group conversation: 
           - one message from android to group
           - one message from desktop to group

### Screenshots
Here how it looks:
on Android:
![screenshot_20170625-001202](https://user-images.githubusercontent.com/12666598/27512291-1c9bf308-593c-11e7-9174-c2d086155d39.png)

on Desktop:
![signal desktop](https://user-images.githubusercontent.com/12666598/27512294-2bedd768-593c-11e7-86e5-d8cfc03bd7f6.PNG)

**Note:** 
the missing second checkmark on the Android screenshot is a known bug, where delivery receipts are not cached for group conversations when they arrive before sync message, tracked here: https://github.com/WhisperSystems/Signal-Android/issues/4924 and here: https://github.com/WhisperSystems/Signal-Android/issues/5573. I confirmed the successuful delivery with all group members. 

### Device info
Desktop:
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.109 Safari/537.36 Signal-Desktop/0.41.3
Android:
Device: Fairphone FP2 Android: 6.0.1 Signal 4.7.3 beta

### Link to debug log
Desktop: https://gist.github.com/anonymous/d11acb1f94c6158c415ce4e0ae1a972b
Android: https://gist.github.com/anonymous/43685b4bf3e4aa24e4c1ea6a6962614e

**Comment by moxie0** [comment]
Looks like there's a desktop bug
