### ISSUE TITLE
[Feature Request] Suggestion For Improved Auto Update 

### ISSUE THREAD

**Issue by zero77** [WhisperSystems/Signal-Android#6765]
Can you please implement Phonegap Build (github.com/phonegap-build) to handle updates.
Another git hub project called DuckieTV uses it with their android app, and it has made the update process completely stream line.
For example, upon opening the app Phonegap Build automatically checks for updates, and if found then asks whether to ignore or update and restart, after this there is no additional action required by the user.
Thanks

**Comment by Dyras** [comment]
What's wrong with the Play Store? Or are you talking about non-Play Store installs? If so the time it would take to implement this doesn't really seem worth the effort.

**Comment by moxie0** [comment]
Thanks but if we're using "native" code the user will have to be involved in approving an apk update, which is how our own updater already works
