### ISSUE TITLE
Keyboard Visible Behind Share Menu

### ISSUE THREAD

**Issue by OriginalFannibal** [WhisperSystems/Signal-Android#6766]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The size of the share menu is smaller than the keyboard. I know this depends upon the height chosen for the keyboard but the menu is smaller than the "normal" setting and this makes the keyboard jut out behind the menu when the menu is accessed with the keyboard already open. Is there anyway the menu could scale with the keyboard or could it just be made larger than it is now? Or maybe the keyboard could be minimised/hidden whenever the share menu is accessed?

### Steps to reproduce
- Tap on the text field to pull up the keyboard  
- Tap on the share button to show the share menu  

**Actual result:** The top of the keyboard is visible behind the share menu  
**Expected result:** Keyboard should either be hidden or menu should be larger than keyboard so that the keyboard isn't seen

### Screenshots
Keyboard Open  

![screenshot_20170626-080837](https://user-images.githubusercontent.com/20235646/27522904-0418c3fa-5a19-11e7-91b5-aa26757ae270.png)

Share menu also opened. The black bar between the text field and the menu is what I'm talking about.  

![screenshot_20170626-080828](https://user-images.githubusercontent.com/20235646/27522921-22be1058-5a19-11e7-8a88-de97a74c45a0.png)

### Device info
**Device:** OnePlus One 
**Android version:** 7.1.2
**Signal version:** 4.7.3

**Comment by rainerzufall** [comment]
This issue is a duplicate of https://github.com/WhisperSystems/Signal-Android/issues/4425. 
I personally agree, but unfortunately it was closed as a won't fix with the explanation by moxie:
> I think I'm cool with that, wasn't really intending it to be a keyboard replacement. 

Therefore please close your issue.

**Comment by OriginalFannibal** [comment]
Thanks for pointing that out to me. I only searched for issues regarding the "share" menu. It never crossed my mind to think of it as the "attachment" one.
