### ISSUE TITLE
Support Android 6.0 runtime permissions

### ISSUE THREAD

**Issue by Stanzilla** [WhisperSystems/Signal-Android#6767]
Any chance this could get picked up again? https://github.com/WhisperSystems/Signal-Android/issues/3983

**Comment by nrizzio** [comment]
If it's opened it's tracked and if someone wants to submit a pull request it will be accepted. Please read the contributing guidelines before you open issues.

**Comment by moxie0** [comment]
Closing this as a duplicate issue
