### ISSUE TITLE
On desktop, enabling disappearing messages initially sets 1 day

### ISSUE THREAD

**Issue by GSPP** [WhisperSystems/Signal-Android#6768]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

Repro:

1. On Signal Desktop, open a chat without disappearing messages set
2. Click the 3 dots button and click "Disappearing messages"
3. This sets the timer to 1 day.

This is a problem because if I want 1 week I now have accidentally deleted 6 days of messages (I presume). Even if that is not the case it *looks* like it might be. It's confusing and suggests possible data loss.

Not sure what the best solution is. As a user I'd be happy if clicking the menu item merely made the disappearing messages button visible but set to off. I can then directly set the desired choice.

(Also, can we have a few more choices between 1 day and 1 week and also 1 month?)

### Device info
**Android version:** 7.1
**Windows version:** 7 x64

**Comment by piratenpanda** [comment]
You should report this in the Desktop issue tracker: https://github.com/WhisperSystems/Signal-Desktop

**Comment by GSPP** [comment]
Turns out this was a [duplicate](https://github.com/WhisperSystems/Signal-Desktop/issues/952) anyway.
