### ISSUE TITLE
Remember the last used message mode per contact

### ISSUE THREAD

**Issue by drws** [WhisperSystems/Signal-Android#6771]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
----------------------------------------

I have some people in my contact list that have uninstalled Signal, but didn't do a proper unregistration so my Signal app always defaults to sending them Signal messages, which they never receive. I have to manually select "SMS mode" each time I open the conversation. It would be great if the last used way of contacting a specific contact was remembered by the app.

**Comment by FeuRenard** [comment]
Duplicate of #2285

**Comment by p4nci** [comment]
duplication of https://github.com/WhisperSystems/Signal-Android/issues/2329

**Comment by drws** [comment]
I was actually going to search for "method" but I was "nah, English is not my mother's tongue, no one would call it method". Sorry for the inconvenience and next time I'll check.
