### ISSUE TITLE
Notify if user does not receive mesage in a certain amount of time

### ISSUE THREAD

**Issue by drws** [WhisperSystems/Signal-Android#6772]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
----------------------------------------

When the message is sent, the first tick acknowledges that the message was sent correctly and if there is an error, the notification alerting the user appears after some time. The second tick acknowledges the correct reception of the message and it would be great to have an option to notify the user if message is not received even after some time (a few days for example).

It usually indicates dead phone or battery, that the recepient is no longer available on Signal, wrong recepient, or even some exotic bug in the system, etc. Therefore it would be very practical to have a notification popping up alerting the user that message hasn't been received even after some time. I also suggest this time be adjustable and 1 day as the default setting.

**Comment by p4nci** [comment]
duplication of https://github.com/WhisperSystems/Signal-Android/issues/6390
