### ISSUE TITLE
Receiving a message from a specific contact puts the contact further down in the conversation overview

### ISSUE THREAD

**Issue by EmilVogt** [WhisperSystems/Signal-Android#6773]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Every time I receive a signal message from this specific contact, the conversation with him is put on the 6th postition in my conversation overview even though it is my most recent conversation activity. Problem persists after the contact reinstalled Signal. It works flawless with other contacts.

### Steps to reproduce
- receive a signal message from a specific contact

**Actual result:** The conversation with this contact gets put on 6th position even though it is the most recent activity
**Expected result:** The conversation should be shown at the top of the conversation overview.

### Device info

**Device:** Sony Xperia Z3 Compact
**Android version:** 6.0.1
**Signal version:** 4.6.1

### Link to debug log
https://gist.github.com/anonymous/156b4c598d6f397d589c20697da37120

**Comment by cascheberg** [comment]
Is it possible that the clock/date/timezone on your contacts device is wrong? Threads are sorted by sent time of the most recent message, which is set by the sender.
There is a timespan or date shown for each entry in the conversation list, what do they show?

**Comment by EmilVogt** [comment]
Yes, I forgot about this. The contact changed the clock on his device. Setting the clock back to automatic solved the issue. Thank you very much.
