### ISSUE TITLE
Feature request: Popup warning messages before unverified communication

### ISSUE THREAD

**Issue by davidhedlund** [WhisperSystems/Signal-Android#6778]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
"In July 2016, the Internet Society published a user study that assessed the ability of Signal users to detect and deter man-in-the-middle attacks. The study concluded that 21 out of 28 participants failed to correctly compare public key fingerprints in order to verify the identity of other Signal users, and that the majority of these users still believed they had succeeded while in reality they failed." - https://en.wikipedia.org/wiki/Signal_(software)#Usability

### Steps to reproduce
- Send a message
- Make or receive a phone call

**Actual result:** No warning messages pop-up
**Expected result:** I expect at least an option to make a warning popups before unverified communication is taking place. Another option is to place a extra icon grouped with the phone/lock icon.

### Device info
**Signal version: 4.7.4**

**Comment by moxie0** [comment]
Thanks but I don't think we're going to do this for now

**Comment by davidhedlund** [comment]
@moxie0 I would appreciate if you put "low priority" labels or whatever instead of just closing relevant issues. Now I have to bookmark it.

**Comment by sigenc** [comment]
@davidhedlund

This is a pretty good idea. I too don't understand why moxie0 doesn't label some of the issues as "low priority" instead of closing them. Moxie please consider this.

**Comment by davidhedlund** [comment]
@sigenc Moxie is ignorant.

**Comment by davidhedlund** [comment]
So I don't trust this piece of software. Fuck you Signal.
