### ISSUE TITLE
Signal is censored in my country

### ISSUE THREAD

**Issue by Behizz** [WhisperSystems/Signal-Android#6780]
Hello guys,
I could use signal for about 2 weeks without any problems, but now I cannot use it because the textsecure-service.whispersystems.org is blocked in my country (there is no problem with google).
 Is there any solutions for that?
Thanks

**Comment by johanw666** [comment]
It would help if you said which country that is. If Signal is blocked but google.com is not, the country can be added to the domain fronting list tocircumvent it.

**Comment by Behizz** [comment]
@johanw666 The country is Iran

**Comment by johanw666** [comment]
Ah yes, Iran is a special case because Google does not implement domain fronting from Iran: https://github.com/WhisperSystems/Signal-Android/issues/5992

**Comment by Behizz** [comment]
@johanw666 Thanks for your answer.
So isn't there any solution for this problem?

**Comment by johanw666** [comment]
Not an easy one. You could try connecting through a non-Iranian VPN, or Open Whispersystems could make a domain fronting agreement with another large company that does provide this service for Iranian companies. Akamai or Amazon come to mind.

**Comment by moxie0** [comment]
There would need to be a large popular site in Iran that uses a CDN compatible with domain fronting. As far as I can tell, there aren't any sites like that.
