### ISSUE TITLE
Images shot while a communication is still ongoing are not shown in quick image pane

### ISSUE THREAD

**Issue by piratenpanda** [WhisperSystems/Signal-Android#6783]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
If you take pictures or the picture is still processed in the background (think HDR+) the newer images are not shown when sending images using the image pane above the keyboard. I remember this was reported when this feature was introduced but I didn't find an open bug on that.

### Steps to reproduce
- chat with someone
- take images or take images which are processed in the background an open chat dialog

**Actual result:** 
those newer images are not shown in the quick image pane

**Expected result:** 
those newer images should be shown in the quick image pane without having to leave the chat and enter it again

### Device info

**Device:** Nexus 6p
**Android version:** 7.1.2
**Signal version:** 4.7.4

**Comment by dcherian** [comment]
Should be same underlying cause as #6028

**Comment by piratenpanda** [comment]
Ah thanks, that's what I was looking for. Closing this now
