### ISSUE TITLE
messages not sending in ipv6/ipv4 environment

### ISSUE THREAD

**Issue by icebal** [WhisperSystems/Signal-Android#6793]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

signal on desktop and android do not work when both ipv4 and ipv6 is enabled. Desktop says its disconnected, android just doesnt send messages.

### Steps to reproduce
- use dhcpv6 to enable ipv6
- make sure you have connectivity via ipv6
- try to use signal

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Android shows as message failed
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Either ipv6 support, send via ipv4, or send mms via cell

### Device info

**Device:** Nexus 6p
**Android version:** 7.1.2
**Signal version:** 4.7.4

### Link to debug log

https://gist.github.com/da88de0ddbadef94d85608e482de4bcb

**Comment by moxie0** [comment]
Hey @icebal, that log shows normal message behavior with network data flowing. In any case, Android apps don't really have any control over the circumstances that you're describing. We can make an API call to open a socket, but how it's routed is really up to the OS. If you have an ipv4 tunnel through your ipv6 network it should work, if it's failing I'm afraid there's probably nothing we can do at the app layer.

Many tmobile data networks are now ipv6 only, and Signal seems to work fine in those situations.

**Comment by icebal** [comment]
If it helps, this is project fi. I have seen other issues that tend to happen on fi, figured this is another one.
