### ISSUE TITLE
Q: Will signal switch to GCM automatically?

### ISSUE THREAD

**Issue by Diapolo** [WhisperSystems/Signal-Android#6797]
I installed Signal 4.7.4 from https://signal.org/android/apk on a phone that has no Google services (WebSocket mode). I wonder what will happen, if I install MicroG. Does Signal automatically switch to GCM or does it keep WebSocked mode?

**Comment by moxie0** [comment]
Hey @Diapolo, we don't use issues for Q&A or support:
https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#issue-tracker-is-for-bugs

Please see the forums for discussion, the support center for support. Thanks.
