### ISSUE TITLE
contact that no longer uses signal

### ISSUE THREAD

**Issue by Thetoxicarcade** [WhisperSystems/Signal-Android#6801]
When a contact doesn't use signal anymore, we should have the option to move back to sms. Not having a read receipt for a month is a good indication... but settings would also work in the conversation. 

I get that we don't really want to fix issues like this, but it's kind of a non-starter if you still haven't fixed the problem in a rational way. 

https://github.com/WhisperSystems/Signal-Android/issues/6377

This isn't an error with the software, it's a design error. 

The logs are in the issue tracker 😃

**Comment by Thetoxicarcade** [comment]
Oooo, long press changes the mode.  Where's that in docs?

https://twitter.com/encthenet/status/883535474999951360

**Comment by NinebitX** [comment]
https://support.whispersystems.org/hc/en-us/articles/212535548-How-do-I-send-an-insecure-SMS-
