### ISSUE TITLE
Why no proxy support?

### ISSUE THREAD

**Issue by aurora-potter** [WhisperSystems/Signal-Android#6802]
Without any standard HTTP, SOCKS or obfuscator proxy implementation.
So, how Signal could protect its users?

**Comment by NinebitX** [comment]
Duplicate: https://github.com/WhisperSystems/Signal-Android/issues/1187

If you want to discuss this, you are welcome to start a discussion on the [community forum](https://whispersystems.discoursehosting.net/).

**Comment by aurora-potter** [comment]
IT DOESN'T HAVE TO BE DISCUSSED.

SIGNAL IS NO BETTER THAN DIRECTLY TALKING

YOU'RE USING WebRTC

SIGNAL IS INSECURE

**Comment by NinebitX** [comment]
This is an issue tracker. It's pointless to start a second thread about the same issue: The lack of support for setting a local proxy (SOCKS and maybe http) to use for all data connections of the app. That is why I mentioned that this is a duplicate of https://github.com/WhisperSystems/Signal-Android/issues/1187. It would be helpful for everyone involved if you could close this as a duplicate.

To be clear, I am not part of the Signal developer team. I would love to hear more about your opinions on this topic and why you think Signal is insecure. That is why I said that you are welcome to start a discussion about this on the (unofficial) [community forum](https://whispersystems.discoursehosting.net/).

The way I've understood it, WebRTC is only used for Signal's voice and video calls. They are also end-to-end encrypted [using the Signal Protocol](https://whispersystems.org/blog/signal-video-calls-beta/). You can verify this by comparing [safety numbers](https://support.whispersystems.org/hc/en-us/articles/115000267971) with your contacts. If you want to hide your location from the person you are communicating with, there's a toggle in the settings page that lets you relay all of your voice and video calls through the Signal service. This was explained in the blog post where Open Whisper Systems announced that they had switched over to WebRTC: https://whispersystems.org/blog/signal-video-calls/

**Comment by aurora-potter** [comment]
I don't use Signal for almost the same reason I don't use SMS.

**Comment by Trolldemorted** [comment]
I understand that some users want proxy support for their convenience, but how should that be related to security? The very point of end-to-end encryption is that anyone may intercept your traffic, but is unable to decrypt it.

**Comment by aurora-potter** [comment]
Please discuss in Signal's community forum.

But from my point of view, it doesn't matter the big brothers watch private data of some, but this matters that they don't understand who this data belongs to. pretty different philosophies.

**Comment by herbsmn** [comment]
https://youtu.be/3gJvABEi3wQ?t=59

**Comment by chromer030** [comment]
Hi , please provide in-app proxy support , (HTTPS , SOCKS ) , likely Signal is blocked in countries like Iran.
Thanks you.
