### ISSUE TITLE
Can't run Signal 4.7.4 without google play services

### ISSUE THREAD

**Issue by zen0x90** [WhisperSystems/Signal-Android#6807]
I have:
- [x ] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

I just installed Signal 4.7.4 and I don't have google play services installed. It asks to register with my phone number and I have a popup saying to update Google play services otherwise Signal won't run. I got that popup each time I submit my phone number.

### Steps to reproduce
- uninstall Google play services
- install Signal
- submit your phone number

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

Popup saying Signal won't run without an Google play services updated

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

submit my phone number

### Device info

**Device:** Fairphone 2
**Android version:** 6.0.1
**Signal version:** 4.7.4

### Link to debug log

I can't access to that.

**Comment by moxie0** [comment]
I'm unable to reproduce this. The prompt for an update to play services only happens if you have play services installed.

**Comment by zen0x90** [comment]
I have MicroG and FakeApps installed. Can this be the issue ?

**Comment by zen0x90** [comment]
I uninstall FakeStore and it works !
tchuss
