### ISSUE TITLE
Signal-Android-x86 (VM): Doesn't work with Lan connection

### ISSUE THREAD

**Issue by HenrydV44** [WhisperSystems/Signal-Android#6811]
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

I installed the Signal apk, from the WhisperSystems website (Signal 4.7.4), on Android-X86 in a virtual machine and linked it with the Chromium app, so far so good. Even so the linking process worked pretty fine, it turned out that all the other functionality in Signal-on-Android-x86 isn't working at all (like sending text messages or esp. **calling other signal users**).
That is probably because Android-x86 (in a Virtualbox) uses the LAN interface (NIC) (to connect to the internet) and it seems like the Signal-Android-app expects a WiFi connection instead of a LAN connection. 

Could you please try to find a solution, so that people could use the Signal-Android-App on Android-x86 to call their contacts (of course a solution for the Signal-Chromium-Desktop-App would be preferable ;) )?

### Bug description
Signal is not able to just use an Android LAN connection for sending/receiving messages or making calls 

### Steps to reproduce
- Install Signal apk on Android-x86 just with LAN connection
- Open Siganl app
- send message/call person

### Expected result:
- sending the message

### Device info
**Device:** innotek GmbH VirtualBox (android_x86)
**Android version:** 6.0.1 
**Signal version:** Signal 4.7.4

### Link to debug log
https://gist.github.com/anonymous/1469b2d016896142d3875f7b8f6b6418

![3sfd](https://user-images.githubusercontent.com/30239372/28281432-97e7b9de-6b16-11e7-8aa9-4ba0d1fe6d66.PNG)

**Comment by nrizzio** [comment]
The issue tracker isn't really suited to help you debug this, but feel free to open a topic at https://whispersystems.discoursehosting.net.

**Comment by moxie0** [comment]
Looks to me like requests are failing because they're unauthorized. I suspect you've either registered another client with the same number or done something with the emulator to lose/reset state.
