### ISSUE TITLE
isLowMemory should use getLargeMemoryClass, not getMemoryClass

### ISSUE THREAD

**Issue by dkasak** [WhisperSystems/Signal-Android#6812]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The current [isLowMemory code](https://github.com/WhisperSystems/Signal-Android/blob/master/src/org/thoughtcrime/securesms/util/Util.java#L431) suboptimally uses `getMemoryClass` instead of `getLargeMemoryClass`. Since Signal already sets `android:largeHeap`, the relevant limit is returned by `getLargeMemoryClass`, [as per the Android documentation](https://developer.android.com/reference/android/app/ActivityManager.html#getLargeMemoryClass()). I think this is behind the effect where some devices can easily send higher resolution images over other messaging apps (e.g. Whatsapp) but get a rather low memory class rating in Signal and compress the images too much as a result.

**Comment by moxie0** [comment]
Fixed in 4.9.0
