### ISSUE TITLE
Error Importing Backup, XML parsing error - Android 7+

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-Android#6830]
I have:
- [X] searched open and closed issues for duplicates - similar UIUX as https://github.com/WhisperSystems/Signal-Android/issues/6816 but have checked with user error for the correct file name and directory
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Importing "SignalPlaintextBackup.xml" on a new phone shows an error importing backup. 

### Steps to reproduce
- Take the export from the old phone and move it onto the new phone's root directory (replacing the export on the new phone)
- Import from within Signal and select "SignalPlaintextBackup.xml"

**Actual result:** Receive an error importing backup alert
**Expected result:** import succeeds

### Screenshots
N/A

### Device info

**Device:** OnePlus3
**Android version:** 7.1.1
**Signal version:** 4.8.1

### Link to debug log
 https://gist.github.com/riyapenn/5570c386a8ad95a455c611303ca298df

`07-27 21:48:57.887 21363 12291 W ImportFragment: java.io.IOException: XML Parsing error!`

**Comment by McLoo** [comment]
Well, that redacted part could be interessting
`... (position:START_TAG <sms protocol='0' address='+1 (XXX) XXX-XXXX' contact_name='MANUALLY REDACTED (LPP)'>@97:72 ...`
Any special charaters we do not properly escape in it?

**Comment by riyapenn** [comment]
The X's were actually numbers and 'Manually Redacted' had no special characters.

**Comment by riyapenn** [comment]
Device: Huawei Nexus 6P
Android version: 7.1.1
Signal version: 4.8.1
Log: https://gist.github.com/cfa9f2571ca48bbb81b788ddd6f0449a

Similar logging (no edits)
`... (position:START_TAG <sms protocol='0' address='+*********23' contact_name='null'>@2197:62 in java.io.InputStreamReader@2404ce4) `

**Comment by baztastic** [comment]
I have the same issue, but was able to resolve it.

Contact names with a single quote were not being escaped properly.

Example:
`contact_name="(",)"`
should be:
`contact_name="(&quot;,)"`

Manual find and replace fixed the issue for me.

**Comment by riyapenn** [comment]
Device: Samsung Galaxy S7 Edge
Android version: 7.0
Signal version: 4.8.1
Log:  https://gist.github.com/riyapenn/eff38319d3d32976fab530d593097ff0#file-log-with-redacted-name-and-number-L1568

Similar logging where I've edited the number and displayed name:
`... unterminated entity ref (position:START_TAG <sms protocol='0' address='********53' contact_name='REDACTED (REDACTED THREE WORDS), (REDACTED THREE WORDS)'>@33511:69 in java.io.InputStreamReader@221eb0d) `

This is similar to https://github.com/WhisperSystems/Signal-Android/issues/6198 in title, but closer to this issue #6830 in logging

**Comment by McLoo** [comment]
@riyapenn thanks for the additional logs.
I'm afraid, we produce invalid XML since 381237a3153f5a8d56377d4531525efef9bb58d6. I don't think it makes sense to try skip invalid entires. An "Import successul with errors" is not very helpful.

The export files can be fixed by replacing

- `&`  with` &amp;`
- `<`  with `&lt;`
- `>`  with `&gt;`
- `"`  with `&quot;`
- `'`  with `&apos;`
inside the contact_name attributes

like this: `contact_name="Mom <3"` --> `contact_name="Mom &lt;3"` 

#6861 is fixing the export by escaping contact_name properly

**Comment by riyapenn** [comment]
Would this address issues listed above where contact names as printed in the logs were
- `contact_name='REDACTED (REDACTED THREE WORDS), (REDACTED THREE WORDS)'` [log](https://github.com/WhisperSystems/Signal-Android/issues/6830#issuecomment-320554040)
- `contact_name='null'` [log1](https://gist.github.com/cfa9f2571ca48bbb81b788ddd6f0449a), [log2 (new & edited)](https://gist.github.com/riyapenn/0d068e6d0addfe561eb7b56c40dc13b4)

**Comment by McLoo** [comment]
These 4 are valid ASCII characters. And `null` is a "valid" contact name.
Tried with several UTF characters. There should be no crash. 🤔

What I have noticed while verifying my statement above:
It's not the faulting entry that is shown in the log, but the one before. That means we have no idea what the faulting entry looks like.

Log:
`... unterminated entity ref (position:START_TAG <sms protocol='0' address='***00' contact_name='Test(Ͽ Ͻ 🏳️‍🌈), (🤩 🤨 🏿)'>@33511:69 in java.io.InputStreamReader@221eb0d)`

Backup file:
```
<sms protocol="0" address="+00000" contact_name="(-*,. )M" date="151234598052" readable_date="Tue, date  GMT+00:00" type="2" subject="null" body="Ew" toa="null" sc_toa="null" service_center="null" read="1" status="-1" locked="0" />
<sms protocol="0" address="+00000" contact_name="null" date="151234598052" readable_date="Tue, date GMT+00:00" type="2" subject="null" body="Ew" toa="null" sc_toa="null" service_center="null" read="1" status="-1" locked="0" />
<sms protocol="0" address="+00000" contact_name="Test (Ͽ Ͻ 🏳️‍🌈), (🤩 🤨 🏿)" date="151234598052" readable_date="Tue, date  GMT+00:00" type="2" subject="null" body="Ew" toa="null" sc_toa="null" service_center="null" read="1" status="-1" locked="0" />

<sms protocol="0" address="+00000" contact_name="FAWLTY ENTRY: & **-* M" date="151234598052" readable_date="Tue, date  GMT+00:00" type="1" subject="null" body="Missed call from -* M" toa="null" sc_toa="null" service_center="null" read="1" status="-1" locked="0" />
```

So I'm pretty sure that there will be no more invalid export files, once the escaping is fixed.
