### ISSUE TITLE
Sent time is incorrect

### ISSUE THREAD

**Issue by fdw** [WhisperSystems/Signal-Android#6831]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
If you open the detailed information on a message (both SMS and Signal messages), they show the time they were sent.
On an earlier version of Signal, this worked as expected. With the current version (4.8.1) however, this is no longer possible and all messages and texts show incorrect information. Additionally, I cannot find the setting in the preferences anymore

### Steps to reproduce
- have no network connection for some time
- restore network connection
- receive message that was sent while you were unavailable
- open the message's detailed information

**Actual result:** The message was allegedly sent only seconds prior to the reception (which is wrong)
**Expected result:** The "sent" time should be correct, i.e. when the sender sent the message.

### Device info
**Device:** Oneplus 3
**Android version:** 7.1.2
**Signal version:** 4.8.1

**Comment by Dyras** [comment]
If I had to guess I would guess the other party's clock is off, can you ask him/her/ze to change it?

**Comment by fdw** [comment]
This issue occurred with several people, at least one of which has a correctly synced clock. Thus, it must either be a problem with Signal or with the network provider.

However, I tested it again after your comment, and Signal messages showed the correct time. It seems that only SMS messages are affected.

**Comment by haffenloher** [comment]
> However, I tested it again after your comment, and Signal messages showed the correct time. It seems that only SMS messages are affected.

AFAIK the sent time is known to be unreliable for SMS messages. That's the reason why Signal only shows it in the message details, contrary to Signal messages for which the sent time is used everywhere.

**Comment by fdw** [comment]
> AFAIK the sent time is known to be unreliable for SMS messages.
Thanks, that is good to know. Seems I just thought it was working better previously.

I'll close the issue. Thanks again :)
