### ISSUE TITLE
Receive only part in MMS messages

### ISSUE THREAD

**Issue by deverlex** [WhisperSystems/Signal-Android#6832]
I send a MMS is contain 2 images, but Signal get one image.

Fix it, please!

### Device info
**Device:** Xperia M2, Nokia 5
**Android version:** 5.1 / 7.1.1
**Signal version:** 4.8.1

**Comment by FeuRenard** [comment]
Duplicate of #1300 

Maybe you can see the missing image in the "All images" view.

**Comment by McLoo** [comment]
closing as duplicate
