### ISSUE TITLE
Contact's phone number will not be recognized by TextSecure

### ISSUE THREAD

**Issue by niemalsnever** [WhisperSystems/Signal-Android#684]
I always save my phone numbers in the international format +49 ... (for Germany). I have one contact, where TextSecure will not recognize the + and therefore tries to send messages to an invalid number, which obviously will fail. I had this before the 2.0 update, but there it could be fixed by recreating the thread manually. This fix doesn't work with 2.0+ anymore, which is really annoying because I can't send messages/SMS to that contact.

**Comment by p4nci** [comment]
@niemalsnever is this still an issue for you?

**Comment by niemalsnever** [comment]
No, everything's fine at least since TextSecure on Android also became Signal. Issue can be closed from my point of view.
