### ISSUE TITLE
4.9.0: crash when importing contacts from desktop app

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#6840]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
On a linked desktop app, go into settings and attempt to import contacts. Android app crashes right away. 
https://gist.github.com/506f0a4e0edde03a2d21d37002381230

### Device info

**Device:** Verizon galaxy s8
**Android version:** 7.0 stock
**Signal version:** 4.9.0

**Comment by moxie0** [comment]
thanks!
