### ISSUE TITLE
Crash on Startup after upgrading to 4.9.0

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#6843]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Crash on startup
According to https://github.com/WhisperSystems/Signal-Android/issues/6838#issuecomment-319502054 I opened this new issue.

### Steps to reproduce
- upgrade to 4.9.0
- start up

### Device info

**Device:** Sony X5 compact
**Android version:** 6
**Signal version:** 4.9.0

### Link to debug log
https://gist.github.com/McLoo/241ffd529721775849fb606c0a8c35ad
https://gist.github.com/McLoo/5e1c153bc03721d57c94f2592fd13c01

both logs taken after pressing the OK button from the "has stopped working" message

**Comment by moxie0** [comment]
@McLoo Thanks! It sounds like your device is rooted if you were using TiBackup?

It looks like you have a thread in your thread table with a recipient_id of "-1." It's possible that this is displayed in the app as "Anonymous." Does that sound familiar to you? Do you know what is in that thread or how it came to be?

**Comment by McLoo** [comment]
Correct. The device is rooted.
Found the Anonymous thread among the archived threads.
And it's a weird one: includes 3 different SMS senders. E-Mail provider (alpha address), banking TAN (alpha), Telegram activation codes (alpha). shuffeld like this: bank, bank, telegram, telegram, e-mail, bank, bank.
No idea how that happened.

Delted the Anonymous thread. Updated to 4.9.0-debug5. works :D

Still have the backup, if needed for further investigation.
