### ISSUE TITLE
Crash on startup due to "invalid" email

### ISSUE THREAD

**Issue by jasonsyoung** [WhisperSystems/Signal-Android#6844]
### Bug description
I used my <phone-number>@vtext.com with plaintext as a destination for email notifications.

### Steps to reproduce
Sign up for FedEx text email notifications using your email to phone number functionality from your provider.

**Actual result:** Signal starts fine
**Expected result:** Signal crashes instantly

It seems the NumberUtil class changed recently and I am on the beta.

### Device info
Galaxy S6 Edge 
Android 7.0

### ADB Debug Log
-01 20:10:57.965 13153 13205 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 13153
08-01 20:10:57.965 13153 13205 E AndroidRuntime: java.lang.AssertionError: Not e164: TrackingUpdates@fedex.com
08-01 20:10:57.965 13153 13205 E AndroidRuntime:        at org.thoughtcrime.securesms.database.Address.toPhoneString(Address.java:112)
08-01 20:10:57.965 13153 13205 E AndroidRuntime:        at org.thoughtcrime.securesms.recipients.RecipientProvider.getIndividualRecipientDetails(RecipientProvider.java:136)

**Comment by jasonsyoung** [comment]
I have no way of getting the messages off the phone so I can't uninstall and reinstall

**Comment by p4nci** [comment]
@jasonsyoung are you on latest beta (Signal v4.9.2)?
your issue should normally be fixed with https://github.com/WhisperSystems/Signal-Android/commit/5f9a3b7930070d411ea53fb09e69fadc296a9558 (see also https://github.com/WhisperSystems/Signal-Android/issues/6841)

**Comment by moxie0** [comment]
This should be fixed in 4.9.2.

**Comment by jasonsyoung** [comment]
Totally apologize, updating to 4.9.2 now. Thanks guys!!
