### ISSUE TITLE
Signal gets killed by its own verification SMS [4.9.1 & 4.9.2]

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/Signal-Android#6845]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I haven't experienced this prior to v4.9.1.
Don't know if this is related to the various issues mentioned in https://github.com/WhisperSystems/Signal-Android/issues/6838

### Steps to reproduce
Prerequisite: Installed Signal 4.9.1 or 4.9.2 **with SMS enabled**

1. In Android, go to Settings > Apps > Signal
2. Press "Force Stop"
3. Open "Storage" by pressing it
4. Press "Clear Cache"
5. Press "Clear Data"
6. Leave Android's settings
7. Start Signal (will open up with registration screen like a new installation)
8. Enter your phone number for registration
9. Start registration process by pressing that button
10. Watch Signal crash at the moment the verification SMS should arrive
11. From that point on, whenever you try to open Signal, it instantly crashes
12. (un- and re-installing Signal fixes the situation until you do the steps described above again)

**Important notes:**
- The crash doesn't happen if Signal is not registered as the SMS app
- The verification SMSes are from German phone numbers used by twilio for German registrations

**Actual result:** Crashes
**Expected result:** Doesn't crash
### Screenshots

None.

### Device info

**Device:** Nexus 5X
**Android version:** 7.1.2
**Signal version:** 4.9.1, 4.9.2

### Link to debug log

None.

**Comment by nrizzio** [comment]
Can you provide an example Twilio German phone number, and an adb logcat output?

**Comment by moxie0** [comment]
I would need a debug log in order to help.

**Comment by RiseT** [comment]
That's a copy of Android Studio's "Android Monitor" window, is this enough?

> 08-02 17:44:19.802 6673-6673/? I/art: Late-enabling -Xcheck:jni
08-02 17:44:19.823 6673-6680/? E/art: Failed writing handshake bytes (-1 of 14): Broken pipe
08-02 17:44:19.827 6673-6680/? I/art: Debugger is no longer active
08-02 17:44:19.828 6673-6680/? I/art: Starting a blocking GC Instrumentation
08-02 17:44:20.593 6673-6673/? I/MultiDex: VM with version 2.1.0 has multidex support
08-02 17:44:20.593 6673-6673/? I/MultiDex: install
08-02 17:44:20.593 6673-6673/? I/MultiDex: VM has multidex support, MultiDex support library is disabled.
08-02 17:44:20.602 6673-6673/? W/PartProvider: onCreate()
08-02 17:44:20.663 6673-6701/? W/SmsReceiveJob: onRun()
08-02 17:44:20.721 6673-6673/? W/PersistentAlarmManagerListener: class org.thoughtcrime.securesms.service.RotateSignedPreKeyListener scheduling for: 1501861423459
08-02 17:44:20.727 6673-6673/? W/PersistentAlarmManagerListener: class org.thoughtcrime.securesms.service.DirectoryRefreshListener scheduling for: 1501731823464
08-02 17:44:20.739 6673-6701/? E/AndroidRuntime: FATAL EXCEPTION: JobConsumer-3
                                                 Process: org.thoughtcrime.securesms, PID: 6673
                                                 java.lang.AssertionError: Error type: NOT_A_NUMBER. The string supplied did not seem to be a phone number.
                                                     at org.thoughtcrime.securesms.database.Address$ExternalAddressFormatter.<init>(Address.java:172)
                                                     at org.thoughtcrime.securesms.database.Address.fromExternal(Address.java:71)
                                                     at org.thoughtcrime.securesms.sms.IncomingTextMessage.<init>(IncomingTextMessage.java:48)
                                                     at org.thoughtcrime.securesms.jobs.SmsReceiveJob.assembleMessageFragments(SmsReceiveJob.java:118)
                                                     at org.thoughtcrime.securesms.jobs.SmsReceiveJob.onRun(SmsReceiveJob.java:53)
                                                     at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
                                                     at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
                                                  Caused by: Error type: NOT_A_NUMBER. The string supplied did not seem to be a phone number.
                                                     at com.google.i18n.phonenumbers.PhoneNumberUtil.parseHelper(PhoneNumberUtil.java:2965)
                                                     at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:2847)
                                                     at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:2837)
                                                     at org.thoughtcrime.securesms.database.Address$ExternalAddressFormatter.<init>(Address.java:169)
                                                     at org.thoughtcrime.securesms.database.Address.fromExternal(Address.java:71) 
                                                     at org.thoughtcrime.securesms.sms.IncomingTextMessage.<init>(IncomingTextMessage.java:48) 
                                                     at org.thoughtcrime.securesms.jobs.SmsReceiveJob.assembleMessageFragments(SmsReceiveJob.java:118) 
                                                     at org.thoughtcrime.securesms.jobs.SmsReceiveJob.onRun(SmsReceiveJob.java:53) 
                                                     at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76) 
                                                     at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46) 
08-02 17:44:20.751 6673-6673/? D/JVM: JVM::Initialize@[tid=6673]
08-02 17:44:20.751 6673-6673/? D/JVM: JVM::JVM@[tid=6673]
08-02 17:44:20.751 6673-6673/? D/JVM: LoadClasses
08-02 17:44:20.751 6673-6673/? D/JVM: name: org/webrtc/voiceengine/BuildInfo
08-02 17:44:20.751 6673-6673/? D/JVM: name: org/webrtc/voiceengine/WebRtcAudioManager
08-02 17:44:20.751 6673-6673/? D/JVM: name: org/webrtc/voiceengine/WebRtcAudioRecord
08-02 17:44:20.751 6673-6673/? D/JVM: name: org/webrtc/voiceengine/WebRtcAudioTrack
08-02 17:44:20.829 6673-6673/? W/PassphraseRequiredActionBarActivity: onCreate(null)
08-02 17:44:20.910 6673-6673/org.thoughtcrime.securesms W/ExperienceUpgradeActivity: getExperienceUpgrade(279)
08-02 17:44:20.923 6673-6673/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: routeApplicationState(), state: 4
08-02 17:44:20.959 6673-6673/org.thoughtcrime.securesms W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
08-02 17:44:21.057 6673-6673/org.thoughtcrime.securesms W/KeyCachingService: onCreate()
08-02 17:44:21.058 6673-6698/org.thoughtcrime.securesms W/CreateSignedPreKeyJob: Not yet registered...
08-02 17:44:21.108 6673-6673/org.thoughtcrime.securesms W/service: Broadcasting new secret...
08-02 17:44:21.110 6673-6673/org.thoughtcrime.securesms W/KeyCachingService: onStartCommand, null
08-02 17:44:21.110 6673-6673/org.thoughtcrime.securesms W/KeyCachingService: onStartCommand, null
08-02 17:44:21.126 6673-6723/org.thoughtcrime.securesms W/MmsSmsDatabase: Executing query: SELECT _id, unique_row_id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, subscription_id, expires_in, expire_started, notified, transport_type, attachment_id, unique_id, mid, data_size, file_name, _data, thumbnail, ct, cl, digest, fast_preflight_id, voice_note, cd, name, pending_push FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, 'SMS::' || _id || '::' || date_sent AS unique_row_id, NULL AS attachment_id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, notified, NULL AS network_failures, 'sms' AS transport_type, NULL AS unique_id, NULL AS mid, NULL AS data_size, NULL AS file_name, NULL AS _data, NULL AS thumbnail, NULL AS ct, NULL AS cl, NULL AS digest, NULL AS fast_preflight_id, NULL AS voice_note, NULL AS cd, NULL AS name, NULL AS pending_push FROM sms WHERE (read = 0 AND notified = 0) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, mms._id AS _id, 'MMS::' || mms._id || '::' || date AS unique_row_id, part._id AS attachment_id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, subscription_id, expires_in, expire_started, notified, network_failures, 'mms' AS transport_type, unique_id, mid, data_size, file_name, _data, thumbnail, ct, cl, digest, fast_preflight_id, voice_note, cd, name, pending_push FROM mms LEFT OUTER JOIN part ON part._id =  (SELECT part._id FROM part WHERE part.mid = mms._id LIMIT 1) WHERE (read = 0 AND notified = 0) ORDER BY date_received ASC)
08-02 17:44:21.382 6673-6673/org.thoughtcrime.securesms W/KeyCachingService: onStartCommand, null
08-02 17:44:21.452 6673-6728/org.thoughtcrime.securesms I/Adreno: QUALCOMM build                   : 6818200, Idb2b4cb785
                                                                  Build Date                       : 11/18/16
                                                                  OpenGL ES Shader Compiler Version: XE031.09.00.04
                                                                  Local Branch                     : N25
                                                                  Remote Branch                    : 
                                                                  Remote Branch                    : 
                                                                  Reconstruct Branch               : 
08-02 17:44:21.461 6673-6728/org.thoughtcrime.securesms I/OpenGLRenderer: Initialized EGL, version 1.4
08-02 17:44:21.461 6673-6728/org.thoughtcrime.securesms D/OpenGLRenderer: Swap behavior 1
08-02 17:44:21.518 6673-6673/org.thoughtcrime.securesms W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
08-02 17:44:21.834 6673-6673/org.thoughtcrime.securesms W/PassphraseRequiredActionBarActivity: onDestroy()
08-02 17:44:23.222 6673-6728/org.thoughtcrime.securesms I/Adreno: DequeueBuffer: dequeueBuffer failed
08-02 17:44:23.222 6673-6728/org.thoughtcrime.securesms I/Adreno: DequeueBuffer: dequeueBuffer failed
08-02 17:44:23.222 6673-6728/org.thoughtcrime.securesms I/Adreno: DequeueBuffer: dequeueBuffer failed
08-02 17:44:23.222 6673-6728/org.thoughtcrime.securesms I/Adreno: DequeueBuffer: dequeueBuffer failed
08-02 17:44:23.223 6673-6728/org.thoughtcrime.securesms W/OpenGLRenderer: swapBuffers encountered EGL error 12301 on 0xd0fa7160, halting rendering...

**Comment by RiseT** [comment]
An example for a German twilio number for Signal verification is "01573 5982251" (from Google Messages, exactly as is, no international prefix displayed).

**Comment by moxie0** [comment]
Ah, I see. Your steps make Signal the default SMS app, but remove Signal's knowledge of its own phone number. Thanks!

**Comment by moxie0** [comment]
Hopefully should be resolved, if you could give 4.9.4 a shot I'd appreciate it. Thanks again!

**Comment by RiseT** [comment]
Yep. With 4.9.4, the issue doesn't appear anymore and everything is working as it should. Thanks!

**Comment by zmni** [comment]
Hello, I just got this error on version `4.55.8`. I uninstall builtin sms app and set Signal as the default sms app. It crash when trying to verify registration.

Crash log:
```
03-02 22:51:23.640  5138  5191 E AndroidRuntime: FATAL EXCEPTION: signal-JobRunner-2
03-02 22:51:23.640  5138  5191 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 5138
03-02 22:51:23.640  5138  5191 E AndroidRuntime: org.thoughtcrime.securesms.jobs.SmsReceiveJob$NotReadyException
03-02 22:51:23.640  5138  5191 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.SmsReceiveJob.onRun(SmsReceiveJob.java:75)
03-02 22:51:23.640  5138  5191 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:21)
03-02 22:51:23.640  5138  5191 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:82)
03-02 22:51:23.640  5138  5191 E AndroidRuntime:        at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:46)
```
