### ISSUE TITLE
Move from GCM to FCM

### ISSUE THREAD

**Issue by lehmanju** [WhisperSystems/Signal-Android#6848]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Google has released Firebase Cloud Messaging some time ago and encourages developers to migrate from the original Google Cloud Messaging. According to Google this is the new version of GCM, it is quite likely GCM is going to be deprecated in the future.

### Why migrate …
https://firebase.google.com/support/faq/#gcm-fcm

**Comment by nrizzio** [comment]
Two things:
 - Someone will have to work on removing the analytics functionality from the Firebase libraries before FCM gets put into the app.
 - Signal-Android's dependencies aren't updated until they really have to be.

Based on these two things, I personally doubt Signal will transition to FCM proactively.

**Comment by lehmanju** [comment]
[Here](https://firebase.google.com/support/guides/disable-analytics#disable_analytics_collection_on_android) is explained how to disable analytics

_Sent from my Google Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by moxie0** [comment]
AFAICT it's the exact same thing, only they renamed it and rejiggered the client API some. Neither of the "why migrate" bullet points apply to us.

We typically try not to avoid upgrading play services dependencies unless there's some extremely tangible benefit, since not everyone always has the updated compatible version installed.

**Comment by rubo77** [comment]
Classyshark3xodus now complains since version 0.33.5

**Comment by rubo77** [comment]
why didn't you just  remove the Anayltics dependency like Conversations did?

see https://www.kuketz-blog.de/conversations-entfernung-google-firebase-analytics-tracker/

**Comment by greyson-signal** [comment]
@rubo77  Please see https://github.com/signalapp/Signal-Android/commit/a6564f8f8458fa256e4b68fef65210ee0c30d518

**Comment by rubo77** [comment]
does that commit remove the Anayltics dependency? In which version will it be published?

**Comment by greyson-signal** [comment]
@rubo77  Yes. To be clear, analytics were always disabled. That commit removes the dependency. The commit is in 4.34.x, which is currently in beta.

**Comment by PiCob** [comment]
@rubo77: here's a whole topic dealing with the change: https://community.signalusers.org/t/gcm-will-be-removed-from-google/3888/44

Please let us continue the discussion there (you can login there using your GitHub account), since for Signal, GitHub is preserved for bugs only.

Thanks!
