### ISSUE TITLE
Updating from 4.8 to 4.9.4 truncates the sendername of an sms

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/Signal-Android#6849]
I updated from 4.8.1 to 4.9.4. I had an old sms with sender "4Launch" (a webshop) in the conversation list. After the conversion it shows just "4" in the sender field, which I don't think it should do.

Edit: it also has the value 4 in the address field in table sms. When I change it to 4Launch, FC Signal and reopen it it still shows 4 as sender.

**Comment by moxie0** [comment]
Thanks @johanw666, to clarify, is "4Launch" the name of a contact you have in your address book which corresponds to a phone number, or is someone's actual SMS address "4Launch" (instead of a phone number)?

**Comment by johanw666** [comment]
I don't have this entry in my phonebook, they sent me an sms with this as sender.

**Comment by moxie0** [comment]
Thanks for the update, that commit should fix things for future incoming messages (the migrated thread is not recoverable).

**Comment by johanw666** [comment]
Not even manually? Anyway, I have an old device which I haven't updated yet, I'll see what 4.9.5 makes from it and try to adapt.

**Comment by moxie0** [comment]
Manually? Sure: "UPDATE thread SET recipient_ids = '4Launch' WHERE recipient_ids = '4'"

**Comment by johanw666** [comment]
Thanks, this worked. I changed it in the wrong table, I'll have to study the table structure more thoroughly.
