### ISSUE TITLE
Inconsistent message colors in thread

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/Signal-Android#6851]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When upgrading to 4.9.5 (I didn't check if this also occurred at 4.9.4 but it didn't happen in 4.8.1) I see that messages in this thread have 2 colors. There are preferences set for the contact and the contact is in my phone contacts but under "Lyca Mobile", not "LYCAMOBILE".  In 4.8.1   Lyca Mobile is a phone operator.

### Screenshots
Note: the number for which I received these messages has expired so I don't care  wether pin's are published here.

![signal-inconsitent_colors_20170803-233700](https://user-images.githubusercontent.com/8427572/28945144-8a37a6cc-78a5-11e7-80e5-315228788fe6.jpg)

This is the same conversation (backup restored on another device) in 4.8.1:
![lyca_mobile_2017-08-03-23-46-06](https://user-images.githubusercontent.com/8427572/28945350-65364d1e-78a6-11e7-9483-7e800f9b312b.jpg)

### Device info

**Device:** Sony Xperia Z3 compact
**Android version:** 6.0.1
**Signal version:** 4.9.5

### Link to debug log
None.

**Comment by moxie0** [comment]
Thanks, so you have a device contact called "Lyca Mobile," and the "phone" field in that is set to "LYCAMOBILE?"

**Comment by moxie0** [comment]
Hmm, my device contact app won't even let me enter [a-zA-Z] into the phone field.

**Comment by johanw666** [comment]
> Hmm, my device contact app won't even let me enter [a-zA-Z] into the phone field.

Mine does not allow that as well. However, when I receive such an sms and then make a new contact from Signal, Signal fills the number fields with the name in such cases so I used Signal to hack in such "numbers" in my contacts. Well, I could expect that trick would break sometime. I'll try making a new contact and see if that works.

**Comment by johanw666** [comment]
I added the "number" again to the existing contact and now shows correct again. Do you want to do something with this use case or shall I just close the issue?

**Comment by moxie0** [comment]
Hmm ok thanks I'll chalk this up to the idiosyncrasy of having text in a contact number field
