### ISSUE TITLE
"Signal keeps stopping"

### ISSUE THREAD

**Issue by PC-Admin** [WhisperSystems/Signal-Android#6852]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Running Signal 4.8.1 on CopperheadOS (Android 7.1.2) keeps saying 'Signal has stopped' and 'Signal keeps stopping' forcing me to restart the application.

I can stare at my whole contact list, but when i click on someone to enter the conversation it crashes 100% of the time. I can't do a debug because it keeps crashing during the debug. :S

### Steps to reproduce
- Install CopperheadOS on Nexus 5X
- Install Signal apk
- Try use Signal normally

**Actual result:** Crashes, displays 'Signal has stopped'.
**Expected result:** Should run normally.

### Device info

**Device:** LG Nexus 5X
**Android version:** 7.1.2
**Signal version:** 4.8.1

### Link to debug log

I wish i could. :(

**Comment by McLoo** [comment]
Given the fact, that you can install a OS on your phone, you're able to do some ADB magic to capture the log I assume :)

https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports#debug-logs-with-adb

**Comment by moxie0** [comment]
@PC-Admin Unfortunately I'm not able to help without a debug log. You'll have to provide an adb logcat for us to be able to figure out what's going on for you.

**Comment by piratenpanda** [comment]
there are apps like matlog to capture logs

**Comment by PC-Admin** [comment]
Checked out the logs and this was caused by me disabling chromium. The problems now resolved.

Thanks anyway! :)
