### ISSUE TITLE
Beta crashes receiving mms

### ISSUE THREAD

**Issue by mpb-github** [WhisperSystems/Signal-Android#6853]
I have:
- [ ] searched open and closed issues for duplicates
- [ ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Using the latest beta, upon receiving mms from hikvision security camera, the app immediately closes. Issue persists until the mms is deleted by going into airplane mode.  Mms consists of a high priority notification message with there still images per notification.

### Steps to reproduce
- install latest beta
- receive mms
- observe failure

**Actual result:** App immediately closes and displays a message stating it did with the option to restart. Second dialog comes up saying similar but option is now close the app.
**Expected result:** Display message including pics from security camera

### Device info

**Device:** Google Pixel
**Android version:** 7.1.2
**Signal version:** 4.9.5

### Link to debug log

https://gist.github.com/85fe5da33217f2c0420e5174a493b67f

**Comment by moxie0** [comment]
thanks for the report!
