### ISSUE TITLE
Censorship circumvention for voice calls

### ISSUE THREAD

**Issue by mockitor** [WhisperSystems/Signal-Android#6854]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

Is it possible to use domain fronting when user enables the `Always relay calls` option. 

This feature would increase the anonymity

**Comment by rwasef1830** [comment]
This is needed in Egypt where Signal voice calls are dropped...

**Comment by moxie0** [comment]
There's not really a great way to do this. We can make message traffic "look like" other things, but VoIP traffic pretty much always "looks like" VoIP traffic.

**Comment by mockitor** [comment]
@moxie0 can you enable "Domain fronting" feature for just messaging traffic. Some authorities may detect the people who use the Signal app at some countries, especially non-democratic ones. this limitation may be a serious problem and may result in the lack of Signal popularity in some countries. 

if you want I can provide sample codes or I can make a PR.

**Comment by rwasef1830** [comment]
Messaging traffic I think is already using domain fronting for some countries @mockitor 
I wish it would be enabled for voice calls as well as they are being sabotaged in Egypt.

**Comment by mockitor** [comment]
We cannot use domain fronting for other than Egypt,Omen..etc. There are some countries which allow Signal app but probably observe network traffic (data or message traffic) to detect potential Signal users.  These non-democratic countries may punish users only because they use Signal app
