### ISSUE TITLE
sent sms messages still show pending

### ISSUE THREAD

**Issue by BMayneFactual** [WhisperSystems/Signal-Android#6867]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I send a sms, the three bouncing dots indicate "sending" indefinitely. MMS gets a sent checkmark. I have verified with the recipient that the messages got through. 

### Steps to reproduce
- send sms

**Actual result:** messages show "pending"
**Expected result:** messages show "via sms"

### Screenshots

![unsent2](https://user-images.githubusercontent.com/8355554/29176680-5fbd26d2-7da1-11e7-9937-eab51007bb17.png)
![unsent1](https://user-images.githubusercontent.com/8355554/29176677-5e3f0c1c-7da1-11e7-929c-c738ded760a1.png)

### Device info

**Device:** Google Pixel
**Android version:** 8.0.0 (4187591, OPP4.170623.014)
**Signal version:** Signal 4.9.7

### Link to debug log

https://gist.github.com/anonymous/fd40b948f7dd24781d0f4316f0530260
https://gist.github.com/anonymous/b7599368a85b42dce46d8791b7cb708e

**Comment by moxie0** [comment]
Android has an SMS API where you essentially hand the OS the SMS, and it subsequently fires a callback to let you know whether the SMS was sent, encountered an error, etc. In this case it looks like we're handing the OS the SMS, and it's just... never firing the callback.

I'm inclined to think it's an OS problem. Are you running a custom ROM? What happens when you send an SMS from another SMS app?

**Comment by BMayneFactual** [comment]
Not a custom ROM, but the android 8 beta. 

Something has happened that solved this problem since reporting. Either restarting my phone or resetting the default sms app (to messages for my test and then back to signal). 

The old messages I sent last night (in the screenshot) still indicate "pending", but new messages to the same person now go through. 

Please feel free to close this if it's not worth investigating.

**Comment by moxie0** [comment]
Thanks for the update
