### ISSUE TITLE
Database upgrade fails and wipes all conversations

### ISSUE THREAD

**Issue by eaon** [WhisperSystems/Signal-Android#6868]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Updated Signal to 4.9.8 via Google Play Store. Upon launching Signal again, it attempted to upgrade the database, but immediately crashed. Launching Signal then made it clear that all the conversations/groups (~4GB I believe) etc. are gone, the app also takes up a mere 100MB of space now.

### Device info
**Device:** Motorola Moto X Play (XT1562)
**Android version:** 6.0.1
**Signal version:** 4.9.8

### Link to debug log
https://gist.github.com/anonymous/98c8da9909bb76ab597b6d06c086f50e

**Comment by moxie0** [comment]
Sorry this happened to you, a crash simply rolls back the transaction, so something else went wrong. We've seen Android's sqlite implementations lose data before. The original crash isn't in the log, so unfortunately there's no action we can take. I'm going to close this until someone can reproduce it. Sorry again.
