### ISSUE TITLE
text security - how deletion is secure ? 

### ISSUE THREAD

**Issue by MyraBaba** [WhisperSystems/Signal-Android#6876]
I dont know where to put this question correctly , sorry for if its mistakenly wrong place.

There is devices that gather all WhatsApp history messages  even they are deleted. They can extract all data from your phone even its assumed deleted .

I dont know the mechanism of the message delete / disappearing . Is this devices can read the memeory or SD card as a raw and extract the messages/files that send by signal and after that deleted/disappeared  ?

Thx

**Comment by moxie0** [comment]
Hey @MyraBaba, please don't delete the issue template when submitting issues. We don't use GitHub for discussion or Q&A, please see the support center or the community forums for that.
