### ISSUE TITLE
Unable to view the call iconon Signal App on iphone

### ISSUE THREAD

**Issue by was6ah** [WhisperSystems/Signal-Android#6878]
I'm new to Signal app.. and unable to find the phone icon that allows me to make phone calls..

Can someone help
Please?

Thank u in advance

**Comment by rainerzufall** [comment]
Please be aware that github is used as bug tracker and not as support forum. Therefore please close this issue and refer to their [support page](https://support.whispersystems.org/hc/en-us). If you can't find the answer on their support page, then try it at [community forum]( https://whispersystems.discoursehosting.net/).

ps. The answer to your question can be found here https://support.whispersystems.org/hc/en-us/articles/115002977308
