### ISSUE TITLE
App permanently stops sending & receiving messages or calls

### ISSUE THREAD

**Issue by DarkCoridor** [WhisperSystems/Signal-Android#6880]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

Signal suddenly stops sending and receiving new messages or calls in the Android app only while Desktop app keeps working fine. No incoming messages are displayed.

### Steps to reproduce
- Install Noise app and register with a phone number
- Link with the Desktop application
- Use OpenVPN (prolly irrelevant)
- Use Signal app as expected for days to weeks

**Actual result:** Outgoing text messages hang in non-sending state with three animated bouncy dots `...` indefinitely. Restarting phone, switching networks, nothing seems to help. The only thing I can do to fix the issue is to reinstall the app completely.

**Expected result:** App should function as normally.

### Device info

**Device:** HTC Nexus 9
**Android version:** ASOP 7.1.1
**Signal version:** Noise 4.9.8-0

### Link to debug log

https://gist.github.com/anonymous/51cd2d91e6864be3dcbea605c080f6fb

IIUC, the log seems to show the app is downloading new messages.

**Comment by nrizzio** [comment]
Per https://github.com/WhisperSystems/Signal-Android/issues/6336#issuecomment-284975110, Noise isn't supported here.

**Comment by DarkCoridor** [comment]
As I understand it, since 1669731329bcc32c84e33035a67a2fc22444c24b was merged, this is not "other people's products" unless simply making a build is considered as such. In which case, I will install https://whispersystems.org/android/apk/ and see if I encounter this again.

**Comment by moxie0** [comment]
Sorry you're having problems, but you would need to get support from the Noise developers for their app, we can only offer support for Signal.

**Comment by DarkCoridor** [comment]
Hi @moxie0  me again here. After a couple months of using the APK from your website- I encountered the same bug twice. The first time Signal recovered a few hours later. The second time it did not recover after 24+ hrs. Here is the log https://gist.github.com/anonymous/184be5550a1ec8593298cc1eda8a6068
