### ISSUE TITLE
signal doesn't actually stop when I exit it

### ISSUE THREAD

**Issue by lethargosapatheia** [WhisperSystems/Signal-Android#6889]
Hi,

I'm using Signal Desktop on macOS Sierra. Whenever I exit Signal and Chrome is still running, Signal actually doesn't exit. Which I find rather annoying. When someone sends messages, I always get notified. I don't understand why the app doesn't actually shut down. It really annoying and I think it's a matter of security, in my opinion, if I think if direct physical access/people peeking over your shoulder.
No that I think about it, runs nontheless whenever I simply start Chrome. So I can't use Chrome without actually using Signal.

**Comment by nrizzio** [comment]
You've opened this issue in the wrong repository, but I can tell you that this is intended behavior. If you're curious why, I suggest you open a thread at https://whispersystems.discoursehosting.net, as issues are used for bugs and not for discussions.

**Comment by moxie0** [comment]
Closing this issue since it seems unrelated to Signal-Android
