### ISSUE TITLE
Crash on opening

### ISSUE THREAD

**Issue by xpete** [WhisperSystems/Signal-Android#6891]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
App crash when i try to open it.

### Steps to reproduce
- try to open it

**Actual result:** 
Show "Updating Database" and then crashes

**Expected result:**
Should open

### Device info

**Device:** Xaomi MI6
**Android version:** 7.1.1
**Signal version:** 4.9.9

### debug log
java.lang.AssertionError: Error type: NOT_A_NUMBER. The phone number supplied was null.
	at org.thoughtcrime.securesms.database.DatabaseFactory$NumberMigrator.<init>(DatabaseFactory.java:1315)
	at org.thoughtcrime.securesms.database.DatabaseFactory$DatabaseHelper.onUpgrade(DatabaseFactory.java:908)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
	at org.thoughtcrime.securesms.database.SmsDatabase.getExpirationStartedMessages(SmsDatabase.java:654)
	at org.thoughtcrime.securesms.service.ExpiringMessageManager$LoadTask.run(ExpiringMessageManager.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: Error type: NOT_A_NUMBER. The phone number supplied was null.
	at com.google.i18n.phonenumbers.PhoneNumberUtil.parseHelper(PhoneNumberUtil.java:2954)
	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:2847)
	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:2837)
	at org.thoughtcrime.securesms.database.DatabaseFactory$NumberMigrator.<init>(DatabaseFactory.java:1312)
	... 8 more

**Comment by moxie0** [comment]
Thanks @xpete, could you include the debug log instead of just this stack trace?

**Comment by moxie0** [comment]
Also, is it possible that you're using Signal without having registered? Like, just as an insecure SMS app?

**Comment by xpete** [comment]
The 1st time i got the error It was the 2nd time I tried to open the app... The first time I didn't had the SIM card on the phone yet so I didn't configured anything and was before the update to version 4.9.9.
I'am not using Signal because I can't open it.
I think you only need to add some validation to the database update code. Should be an easy fix.
I added the debug log I got from ADB but i don't think it adds much information.

### Debug 
08-29 01:13:03.701  3380  3380 I MultiDex: VM with version 2.1.0 has multidex support
08-29 01:13:03.701  3380  3380 I MultiDex: install
08-29 01:13:03.701  3380  3380 I MultiDex: VM has multidex support, MultiDex support library is disabled.
08-29 01:13:03.707  3380  3380 W PartProvider: onCreate()
08-29 01:13:03.745  3380  3380 W PersistentAlarmManagerListener: class org.thoughtcrime.securesms.service.RotateSignedPreKeyListener scheduling for: 1504138383745
08-29 01:13:03.747  3380  3380 W PersistentAlarmManagerListener: class org.thoughtcrime.securesms.service.DirectoryRefreshListener scheduling for: 1504008783747
08-29 01:13:03.761  3380  3417 I SQLiteConnectionPool: The connection pool for /data/user/0/org.thoughtcrime.securesms/databases/messages.db has been closed but there are still 1 connections in use.  They will be closed as they are released back to the pool.
08-29 01:13:03.766  3380  3417 E AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
08-29 01:13:03.766  3380  3417 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 3380
08-29 01:13:03.766  3380  3417 E AndroidRuntime: java.lang.AssertionError: Error type: NOT_A_NUMBER. The phone number supplied was null.
08-29 01:13:03.766  3380  3417 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DatabaseFactory$NumberMigrator.<init>(DatabaseFactory.java:1315)
08-29 01:13:03.766  3380  3417 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DatabaseFactory$DatabaseHelper.onUpgrade(DatabaseFactory.java:908)
08-29 01:13:03.766  3380  3417 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
08-29 01:13:03.766  3380  3417 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
08-29 01:13:03.766  3380  3417 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SmsDatabase.getExpirationStartedMessages(SmsDatabase.java:654)
08-29 01:13:03.766  3380  3417 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.ExpiringMessageManager$LoadTask.run(ExpiringMessageManager.java:57)
08-29 01:13:03.766  3380  3417 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-29 01:13:03.766  3380  3417 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-29 01:13:03.766  3380  3417 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
08-29 01:13:03.766  3380  3417 E AndroidRuntime: Caused by: Error type: NOT_A_NUMBER. The phone number supplied was null.
08-29 01:13:03.766  3380  3417 E AndroidRuntime: 	at com.google.i18n.phonenumbers.PhoneNumberUtil.parseHelper(PhoneNumberUtil.java:2954)
08-29 01:13:03.766  3380  3417 E AndroidRuntime: 	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:2847)
08-29 01:13:03.766  3380  3417 E AndroidRuntime: 	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:2837)
08-29 01:13:03.766  3380  3417 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DatabaseFactory$NumberMigrator.<init>(DatabaseFactory.java:1312)
08-29 01:13:03.766  3380  3417 E AndroidRuntime: 	... 8 more
08-29 01:13:03.766  3083  3234 I WtEventController: Receive am_crash event for pid: 3380
08-29 01:13:03.767  2586  2613 I octvm_klo: klo lock
08-29 01:13:03.768  1521 19387 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.RoutingActivity

**Comment by moxie0** [comment]
Before you did the update, when you were able to open Signal, were you using it exclusively as an insecure SMS/MMS app or were you registered for the Signal service?

The "validation" that is missing is *your* registered phone number totally missing, which would suggest that you had never registered?

**Comment by xpete** [comment]
I wasn't using the Signal app. I got this error the first time I tried to open the app after i got the SIM on the phone. Yes, I never registered. That's what i was trying to say in the previous comment.

**Comment by moxie0** [comment]
I see, just reinstall and you should be good then

**Comment by xpete** [comment]
I know I can I clean the app data and it will work. but that is just a work around. I would be better to add an validation or threat the exception.

**Comment by rtye** [comment]
Sounds a bit arrogant asking people who have not registered yet to loose all their existing conversations and reinstall just because you forgot to test your app properly. You do not even give them a choice.

Why should any of us trust your app when you show such ignorance and expect us to forgive such a data loss like the one you suggest.

Years of conversations are now lost because of this. Not the best way to build trust among your users...

**Comment by moxie0** [comment]
@rtye This issue is describing a problem someone had when they had *never used Signal*. My understanding is that they installed the app, never used it in any capacity because they didn't have a SIM in their device, got the update shortly after, and then tried to start using it.

**Comment by xpete** [comment]
@moxie0 is right. I didn't lost any important data but it won't hurt to add a validation.

**Comment by rtye** [comment]
Yes the description is correct. It's just that the consequences of this bug also affect those of us who has kept on using the app since it was called textsecure and had that fantastic SMS transport.

@xpete were just lucky to have nothing of value to loose from a reset. He could just as easily have used it for years, and now lost all conversation history.

The rest of us who did not register before this update and has a database full of conversations, images and more are now effectively locked out of the app and our data.

We cannot reset without loosing all our data. And we cannot register either since the app crashes during init.

Why have an option to use the app without registering, when you clearly does not intend to support it. 

The response to just close this bug as if it was no big deal made me just angry.
Most user does not know how to attach a debugger and google the error as I did. Had I been an ordinary user I would never have known what struck me.

This bug is a show stopper and should be fixed asap.
