### ISSUE TITLE
(Possible security issue) Whilst de-registering foreign number in UAE messages, are sent/received

### ISSUE THREAD

**Issue by OH-BUGGER** [WhisperSystems/Signal-Android#6893]
### Bug description
While registered with Signal on a foreign number, and visiting UAE, Signal does not work so whilst de-registration of foreign number, messages that were not being sent/received are suddenly sent/received in that time window. **_Is there a possible vulnerability just during that time frame?_**

### Steps to reproduce
- Use a SIM card from a foreign country where Signal is not blocked or censored and register and use it in that country.
- Go to UAE and use Signal (messages will not be sent)
- Send a few messages and instantly go to next step
- Try de-registering (it will give an error of "error connecting to server")
- Previously sent messages will be delivered whilst the de-registration is happening 
- Messages will not be sent anymore afterwards and de-registration won't happen.
- Messages sent from outside UAE are also not delivered normally, but are received whilst the UAE user is de-registering.

**Actual result:** So messages are not being sent/received at all.... but then when trying to de-register the messages are sent/received. The main problem here is that during de-registration all messages are sent/received. 

**Expected result:** Not sure what I expect, but if Signal is blocked then messages shouldn't go through at all. So maybe it is a security issue, or perhaps there is another way to circumvent censorship?

### Screenshots
Sorry no screenshots as the explanation is self-sufficient (hopefully).

### Device info

**Device:** Samsung Galaxy S7
**Android version:** 7.0
**Signal version:** 4.8.1

### Link to debug log
https://gist.github.com/b53230b3764cb08ad97ff102088700db

**Comment by OH-BUGGER** [comment]
Update!

Removing and re-installing Signal worked to register the UAE number... and thus I assume that de-registration didn't work due to the censorship.

**BUT wait there is more:**

Is there a vulnerability in the system whilst de-registration?

**Comment by moxie0** [comment]
It's a known issue that foreign numbers don't work in censored countries. We're only supporting detection by country code for now, but are looking into ways to support other numbers. Think there's already an open issue for this.
