### ISSUE TITLE
Android 8 crash when opening the attachment drawer a second time

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-Android#6894]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Crash on Android Oreo after attempting to attach or attaching a picture directly from the message thread.  Typically crashes on second tap of the attachment icon.

### Steps to reproduce
- Open a conversation
- Tap the attachment icon
- Close the attachment drawer
- Tap the attachment icon a second time

**Actual result:** Attachment drawer is partially displayed & Signal crashes
**Expected result:** Display drawer & not crash

### Screenshots

<img width="187" alt="screen shot 2017-08-25 at 11 06 31 am" src="https://user-images.githubusercontent.com/4898366/29727711-ec2c5a04-8989-11e7-9245-ba35fd2710b9.png">

### Device info

**Device:** LGE Nexus 5X
**Android version:** 8.0.0
**Signal version:** 4.9.9

### Link to debug log

https://gist.github.com/472ca31f484bc4e908b5beb5e950ce15

**Comment by moxie0** [comment]
Is this an official build or an aftermarket ROM update? The crash is a segfault in OS code.

**Comment by riyapenn** [comment]
Official build for Android 8.0.0.  Prior to this, the device was running official Android O betas. All updates have been done OTA.

**Comment by RiseT** [comment]
For another debug log, see #6907

**Comment by moxie0** [comment]
This really looks like an Android 8 bug to me. I can't think of anything we could do that should cause a segfault in the renderer. Maybe there's something we can do to work around it, but I still don't have Android 8 on a physical device.

**Comment by RiseT** [comment]
Could temporarily (until the Android bug is fixed) omitting that drawer animation help? At least optically, it looks like the issue arises during that animation.

Is there a simple parameter in the code that I can change in order the set the drawer animation to "no animation" in order to test this?

**Comment by Le1b1** [comment]
Here is mine: https://gist.github.com/adb8f2787a71f842d4d8d00253eca92c

The number of taps on the icon to crash Signal differs between 1 - 3.

**Comment by Le1b1** [comment]
I don't know why, but if I turn the 'energy safer' on in system settings, Signal doesn't crash anymore.

**Comment by RiseT** [comment]
> I don't know why, but if I turn the 'energy safer' on in system settings, Signal doesn't crash anymore.

Confirmed.

**Comment by veeti** [comment]
It's unfortunate visually, but removing elevation on attachment_type_selector resolves this on Nexus 5X.

**Comment by RiseT** [comment]
Has this been fixed (...by https://github.com/WhisperSystems/Signal-Android/commit/74779adc3436542ef2a9b1a89fc45f645720dc31 perhaps)? I'm currently unable to reproduce this in v4.10.11.

**Comment by riyapenn** [comment]
This is still occurring but less frequently on 4.10.12 for the original report. 
Log: https://gist.github.com/a24d2a8f37ea97371f822b40104f4f70

**Comment by igor2x** [comment]
I also have this problem on LG Nexus 5X using Android 8 and Signal 4.10.12. It is interesting that crash does not happen every time I tap on attachment icon. First time tap on attachment does not crashes it.  It is required to tap 2 times (and cancel between), sometimes more.

When problem appears it appears when attachments are only half screen displayed:
![1](https://user-images.githubusercontent.com/10895030/31187816-4d70a14e-a933-11e7-9c6a-c0f0056424cc.png)

Crash window:
![2](https://user-images.githubusercontent.com/10895030/31187947-aef8d1fc-a933-11e7-9abe-9eb28da241e3.png)

I clicked on "Send feedback" and made print screens of screen:
![3](https://user-images.githubusercontent.com/10895030/31187971-c899934e-a933-11e7-9192-5d719d4dc614.png)

![4](https://user-images.githubusercontent.com/10895030/31187976-cc82a0a4-a933-11e7-9d88-4ee64176e27e.png)
![5](https://user-images.githubusercontent.com/10895030/31187980-d046fab4-a933-11e7-94c6-869f1fd85ab7.png)
![6](https://user-images.githubusercontent.com/10895030/31187992-d37764bc-a933-11e7-83da-9edd43ea16d4.png)
![7](https://user-images.githubusercontent.com/10895030/31187996-d64759b8-a933-11e7-8261-0bed9ea5144b.png)
![8](https://user-images.githubusercontent.com/10895030/31187999-da1a1350-a933-11e7-8d57-a9def18a58eb.png)
![9](https://user-images.githubusercontent.com/10895030/31188006-de7ac32c-a933-11e7-9d1a-7401a8322b9a.png)
![10](https://user-images.githubusercontent.com/10895030/31188010-e19e9128-a933-11e7-9e65-ad45d02b7ec8.png)

But what it is interesting it looks like only attachment component crashes and Signal works normally. Actually when crash appears and I tap on "Close app" only this question dialog closes, but Signal main window (as seen on second image) gets displayed, but Signal is working fine. It may be that Signal itself does not crashes, but only some Android file attachment component or something.

**Comment by florianprischl** [comment]
I can confirm this issue. I have tried it several times now and it already happens on the first tap of the attachment button.

**Steps to reproduce**
1. Open conversation
2. Tap attachment icon
5. Actual result: Attachment drawer partially displayed, Signal crashes
6. Expected result: Display drawer, do not crash

**Screenshots (scaled down to 225x400 px)**
![2017-10-06 22 21 59x400](https://user-images.githubusercontent.com/9057669/31297991-72ad0e28-aae8-11e7-8216-3c9720675a9a.png)
![2017-10-06 22 22 02x400](https://user-images.githubusercontent.com/9057669/31297996-744f46ba-aae8-11e7-8d2e-15aafca10017.png)


**Device info**
**Device:** LGE Nexus 5X
**Android version:** 8.0.0, patch level 5 September 2017, build OPR4.170623.006 (I flashed 8, it's not an OTA from Android 7)
**Signal version:** 4.10.12

**Debug log**
https://gist.github.com/anonymous/346ab604f29d7ebab22a14ed8bb3eb77

**Comment by RiseT** [comment]
Mh. My device is a Nexus 5X with Android 8.0.0 & patch level 10/2017 (same for 09/2017) as well, but the issue seems fixed for me. Strange.

**Comment by florianprischl** [comment]
Update: The crash does not occur if the attachment button is tapped while the cursor is in the message input field, i.e. when the keyboard (in my case, Gboard by Google) is open. See the following screenshots:

![screenshot_20171008-214946](https://user-images.githubusercontent.com/9057669/31320394-0fbef7a8-ac74-11e7-8f58-27eebb1d0e23.png) ![screenshot_20171008-215006](https://user-images.githubusercontent.com/9057669/31320395-0fbf2f8e-ac74-11e7-88c8-fb1a28f4f7e6.png)

**Comment by claptopus** [comment]
Same issue. Pixel XL on 8.0. If you tap attach when the keyboard is open it will crash back to the messages window. If you tap attach without the keyboard open it works normally.

**Comment by florianprischl** [comment]
The issue no longer appears for me.
**Device info**
**Device**: LGE Nexus 5X
**Android version**: 8.1.0, patch level 5 December 2017, official build OPM1.171019.011
**Signal version**: 4.13.6
