### ISSUE TITLE
Using Signal standalone with MicroG in it's default state (gcm off) fails to register

### ISSUE THREAD

**Issue by ilikenwf** [WhisperSystems/Signal-Android#6895]
### Bug description
When using microg in it's default configuration (having cloud messaging/gcm disabled) Signal still tries to register and send/receive messages via gcm. Freezing the microg framework allows websockets to be used instead, as gsf is no longer detected.

I use the standalone apk release from the website, and would greatly appreciate it if an option to toggle the use of gcm could be exposed somewhere in the standalone apk releases. Alternatively, Signal could test to see if gcm is functional or not before registration and upon startup, and fall back to websockets with the standard notice in the event a system issue is present, or the user is opting to use websockets on purpose.

As an aside, if I unfreeze the microg framework now, will Signal continue using websockets instead? I have no idea.

### Steps to reproduce
- Procure phone running microg with gcm/cloud messaging disabled
- Try to register with Signal (fail)
- Freeze the microg framework applications
- Kill and restart Signal, register
- Success (via websockets)

**Comment by moxie0** [comment]
The only way to test for the presence of GCM is to make the framework call that we're making, which MicroG is apparently returning true for. You can re-enable MicroG after registration and Signal will not attempt to use GCM.

**Comment by ilikenwf** [comment]
Good to know, I may need to file a report with MicroG then as one currently
is unable to do any sort of blacklisting until after an application has
registered with GCM.

Of course, I didn't realize until recently that the protocol only wakes the
devices via GCM, and that messages get passed around through the Whisper
servers, so Google at best gets some metadata.

Thanks for all you do! I've enjoyed your work since the early days of
sslstrip, back before wifi pinepples were even called pineapples...the
yasager routers, back then, was the name if I recall.

On Sun, Aug 27, 2017 at 8:12 PM, Moxie Marlinspike <notifications@github.com

**Comment by eighthave** [comment]
I'm also having this problem using v4.14.10.  I am running Signal on the [Lineage+MicroG ROM](https://lineage.microg.org), e.g. MicroG's custom build of LineageOS with MicroG built in.  I also have WhatsApp on this device, which has been working fine, so this makes me think it is not necessarily a problem in MicroG.

Without changing any settings or registering with Google, Signal fails to register.  When I click the Register button, I immediately get a toast saying "Unable to connect to service. Please check network connection and try again.".  It then waits forever with the spinner where the button was.  In this configuration, WhatsApp just worked.

I then added a Google account to MicroG and enabled GCM.  Now Signal was able to register.  WhatsApp immediately put up the push notification permission prompt and works with it enabled.
