### ISSUE TITLE
Crash when trying to open the attachment menu (Android 8.0.0)

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/Signal-Android#6907]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I've just had strange behavior resulting in a crash when trying to open the attachment menu (button with paper clip). The animation opening the menu area got stuck somewhere in the middle and resulted in a crash a couple of seconds later. I've had this 2 times in a row now.

### Steps to reproduce
- Open conversation
- Tap on paper clip button

**Actual result:** Opening animation isn't completed, crash
**Expected result:** Open the attachment menu without crashing

### Screenshots

None

### Device info

**Device:** Nexus 5X
**Android version:** 8.0.0
**Signal version:** 4.9.9

### Link to debug log
https://gist.github.com/anonymous/55715ded01ef69d58579a638f0cbf20d

**Comment by McLoo** [comment]
looks like #6894 to me

**Comment by RiseT** [comment]
Damn it. Either GitHub's search feature is suboptimal, or I'm too dumb to use it ... Thanx 😄
