### ISSUE TITLE
Attached image from camera leaves plaintext copy

### ISSUE THREAD

**Issue by arikb** [WhisperSystems/Signal-Android#6909]
I have:
- [x] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description

When attaching an image directly from the camera, a plaintext copy of the image is saved to the folder `/storage/emulated/0/Android/data/org.thoughcrime.securesms/files`

### Steps to reproduce

- Go into any Signal conversation
- Leave the message empty
- Press the blue paperclip button (this does not happen when you press the quick camera button)
- Press the green "Camera" button
- Take a picture
- Press the tick or similar button in the camera app to accept the picture
- No need to continue editing, captioning or sending the image, the file has already been created and is never removed. Even deleting the draft doesn't delete the file.

**Actual result:**

- A file with a `jpg` extension is created in the folder `/storage/emulated/0/Android/data/org.thoughcrime.securesms/files` - the file name is made of the digits of what appears to be `ctime` of the time the file was created.
- The file persists throughout the life of the app and never deleted, even when the image in the conversation is deleted or the entire conversation is deleted.
- Clearing Signal's storage from the app info applet does delete all files in that folder.

**Expected result:**

- Ideally, No plaintext image file would be created anywhere within the phone's file system
- Alternatively, the file will be deleted as soon as practicable after it has been encrypted and stored in Signal's database

### Device info
**Device:** Tested on OnePlus 2 and Samsung Galaxy S7
**Android version:** Tested under OxygenOS Stock 3.6.0 for Oneplus 2 and Cyanogen 14.1 NIGHTLY for S7
**Signal version:** 4.9.9 and, based on the pictures left on my device, multiple previous versions

**Comment by 0xbb** [comment]
I experience the same behavior on my device. 
### Device info
**Device:** Moto G4 (athene)
**Android version:** Android 7.12 (lineage-14.1-20170911-nightly-athene)
**Signal version:** 4.99 and some versions before.

Side node: I use OpenCamera as the default camera app.

**Comment by mlsxlist** [comment]
I see the same issue independent of the camera app.

Device : samsung SM-N910F (cm_trltexx)
Android : 5.1.1
OS Host : cyanogenmod
App : Signal 4.11.5

**Comment by FeuRenard** [comment]
I can reproduce this.

Device: Fairphone 2
Android: 6.0.1 stock
Signal 4.11.5

Further information:
https://whispersystems.discoursehosting.net/t/etiquette-of-promoting-an-issue-in-the-repository/1342/10
