### ISSUE TITLE
Signal messages aren't received by SMS after switching phones but keeping number, and not in installing signal

### ISSUE THREAD

**Issue by Shaderboy** [WhisperSystems/Signal-Android#6912]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

Messages sent from signal don't come through to SMS on new phone without signal. The new phone shares the number of an old phone that had signal. My guess is that the number is still registered in the server since signal was never uninstalled from the old phone, so the server tries to route to the app for that number, even though the new phone doesn't have it. Installing signal on the new phone makes new messages come through without trouble.

### Steps to reproduce
- buy new phone with new sim card 
- transfer number to new phone
- don't uninstall signal from old phone
- don't install signal on new phone

**Actual result:** new phone doesn't get messages sent from signal
**Expected result:** new phone should get messages from signal in default SMS app

### Device info

**Device:** iPhone 6s (new phone), Galaxy S6 (old phone)

**Comment by FeuRenard** [comment]
You should unregister the number you don't want to use Signal with any longer. Learn how to do this here:
https://support.signal.org/hc/en-us/articles/214160088-How-do-I-unregister-or-delete-my-account-

**Comment by moxie0** [comment]
If you physically remove a SIM from a phone and put it in another, there's no way for us to know that you've done so. We process GCM feedback for uninstalls on existing devices, but there's nothing more than we can do beyond eventually timing out your account after inactivity (which eventually happens).

**Comment by codenamezjames** [comment]
Sorry to dig up an old thread, but there should be a way to set a user as SMS/MMS only.

I had an issue with one of my friends. She uninstalled signal without telling me and then all my messages failed and I couldn't explain to her she had to unregister. 

A much needed feature would be to allow me to set my default sending mode per conversation

**Comment by FeuRenard** [comment]
This is tracked by #2285.
