### ISSUE TITLE
Signal 4.10.2 crashes when opening SMS on Android Oreo

### ISSUE THREAD

**Issue by lndbrg** [WhisperSystems/Signal-Android#6924]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When clicking any SMS conversation in Signal on Android Oreo the application crashes (have not tried all of them, but many of them). Haven't tried a Signal conversation.

I had deleted an old SMS thread with 1 message before upgrading to Android Oreo and the latest beta (don't know which Signal version I used when I deleted the convo)

### Steps to reproduce
- Open signal
- Enter password
- Press any SMS convo

**Actual result:** Application crashes
**Expected result:** I should enter the SMS convo and read SMS

### Device info

**Device:** Google Pixel
**Android version:** 8.0.0
**Signal version:** 4.10.2

### Link to debug log
https://gist.github.com/anonymous/4686dc9de22af979aea80e37d170b872

**Comment by dcherian** [comment]
Another log: https://gist.github.com/anonymous/e0a2645dc1577419950831611f8d08b7

This time on Android 7.0

**Comment by moxie0** [comment]
Are these SMS conversations that you've sent messages to in the past, or unidirectional conversations where you've only received messages?

Also, are these threads that you have a contact for, or messages from numbers that aren't in your address book?

**Comment by dcherian** [comment]
1. Yes.

2. I have a contact for these conversations.

**Comment by lndbrg** [comment]
Unnamed contacts I can verify that it crashes on unidirectional and bidirectional.

Named contacts I also believe it crashes on both (both not sure of the history on all of them)

A named contact with only one incoming MMS do not crash.

A named contact with bi-directional communication of SMS and MMS crashes

I don't have any problems opening a group signal convo.

**Comment by lndbrg** [comment]
Get a crash with a similar stack trace when trying to search too:
https://gist.github.com/anonymous/3f0260e62d85b3b65197cc0c6d27fa52
