### ISSUE TITLE
Group MMS threading bug - 4.10.2

### ISSUE THREAD

**Issue by dcherian** [WhisperSystems/Signal-Android#6925]
### Bug description
After updating to Signal 4.10.2, incoming messages sent to an MMS group are not threaded with previous messages from group.

1. The message was received while I was going through the profile onboarding. Don't think this is relevant.
2. The new group created has my number in there (in conversation title and under group members). The old group does not present my number anywhere. I think this is the bug.

### Steps to reproduce
- Receive MMS message

**Actual result:** Messages are in new thread
**Expected result:** Old thread should be continued.

### Device info

**Device:** Moto G4 Play
**Android version:** 7.0.0
**Signal version:** 4.10.2

### Link to debug log
Not sure if needed.

**Comment by moxie0** [comment]
Good find, I fixed the migration, but sadly it won't help you since you've already run the migration.

**Comment by dcherian** [comment]
hmmm I received an MMS that got attached to the wrong thread (which was the most recent MMS thread).

the only common member I'm both got was me.

also MMS group names now show my number first which is not useful at all.

**Comment by moxie0** [comment]
@dcherian Yes unfortunately since you've already been through the migration all of your MMS threads are going to get split into new threads. Would you mind opening a new issue for the problem with your phone number being displayed first?

**Comment by dcherian** [comment]
I wasn't clear enough.

1. My phone is being displayed first in Group A, which is the group that went through the migration and had the trouble initially reported. So this observation might not hold after the fixes you applied.

2. After upgrading to 4.10.3, I received a message in Group B that got threaded in Group A (the most recently used MMS group). The only common member is me. That seems like a bug.

**Comment by moxie0** [comment]
I don't understand what you're describing, can you try rephrasing with an example?

**Comment by dcherian** [comment]
I have Group A, which is the new MMS group created by the migration in 4.10.2.

I sent a message in an unrelated Group B. The reply to this message, was threaded with messages in Group A, not Group B. The only common member to both MMS groups is me. 

I've sent out a message in Group C, to see if I can reproduce but no one has responded yet :(

**Comment by moxie0** [comment]
5173921ce091d5dbe68e6d56f571f8137b6106c7 should hopefully address this

**Comment by mrgtreeskier** [comment]
@moxie0

Similar issue. I created a new MMS group. When I get a response, signal creates another MMS group with all members and my number now listed. Now I have two groups with the same members but one with my number listed first.

Pixel XL
Android 8.0.0
Signal 4.10.8

Log: https://gist.github.com/b656bc7f51c42e706751fac8aa83075c

**Comment by moxie0** [comment]
@mrgtreeskier You created the group with Signal 4.10.8?

**Comment by mrgtreeskier** [comment]
@moxie0 correct

**Comment by dcherian** [comment]
same issue as @mrgtreeskier on 4.10.10.

reply MMS messages get threaded separately to my initial outgoing message.

 In my case, my number is added to the **end** of the title in the Conversation List screen, but listed first under Group Members

**Comment by dcherian** [comment]
the group might've been created on 4.10.9, not 4.10.10. I can't remember when I updated
