### ISSUE TITLE
Crash after taking profile picture

### ISSUE THREAD

**Issue by FeuRenard** [WhisperSystems/Signal-Android#6926]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Choose to take your profile picture using the camera. It will crash after confirming this picture in the camera intent.

### Steps to reproduce
- Go to settings
- choose profile entry at the top
- tap the picture
- choose to use the camera
- take a picture
- confirm the picture (still in the intent, maybe depends on used camera app)

**Actual result:** Signal crashes
**Expected result:** Picture is set as profile picture

### Device info 1

**Device:** Sony Xperia U
**Android version:** 4.4.4
**Signal version:** 4.10.2

### Device info 2

**Device:** AVD Nexus 5X
**Android version:** 7.1.1
**Signal version:** 4.10.2

### Link to debug log
https://gist.github.com/anonymous/d53c84c37d84a4520991ef8ebe64fd39

**Comment by moxie0** [comment]
I can't reproduce this, it looks like your camera app isn't returning a result intent (NPE). Are you using something non-standard for taking the photo?

**Comment by FeuRenard** [comment]
- com.android.camera2 on 4.4.4 (CyanogenMod)
- OpenCamera on 6.0
- preinstalled "Camera" on 7.1.1 emulator

It's reproducible for me on these three devices.

Do we really need a result? Why does `captureFile` exist then?

**Comment by moxie0** [comment]
You're right! hopefully that works

**Comment by FeuRenard** [comment]
works fine on 4.4.4 and 7.1.1 👍 
will test OpenCamera/6.0 as soon as the change arrives in beta channel.

**Comment by rainerzufall** [comment]
With Signal 4.10.3 it now works on Android 6 and Open camera!

**Comment by FeuRenard** [comment]
Works fine with OpenCamera, too.
