### ISSUE TITLE
Messages w/attachment sent on desktop disappear from mobile

### ISSUE THREAD

**Issue by arikb** [WhisperSystems/Signal-Android#6928]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

- Issue copied over from [Closed Desktop issue 1424](https://github.com/WhisperSystems/Signal-Desktop/issues/1424) as requested by @scottnonnenberg

### Bug description

Under the following conditions, messages disappear in an untimely fashion from Signal Android:

1. The message is sent from Signal Desktop (Electron); and
2. The message has an attachment or is a voice message; and
3. The message is sent in a conversation that has the "Disappearing Messages" feature turned on

### Steps to reproduce
- Have Signal Android and Signal Desktop (Electron) linked
- Enter a conversation on Signal Desktop
- Turn on "Disappearing Messages" if not already on (set the time to 1 day)
- Send a message with an attachment - or - send a voice message
- Wait for the message to be sent successfully, reach the recipient successfully (two "tick marks")
- Watch the same conversation on Signal Android

**Actual result:**

- The messages are synchronised to Signal Android
- After around 1-2 minutes, the messages with the attachments disappear from Signal Android

- Unreproducible: Sometimes the message doesn't show up at all on Signal Android. This happened to me yesterday pretty consistently with voice messages but I can't reproduce that today. I suspect that they might show up and disappear too fast for me to see. Today they behave like other messages with attachments.

(the messages do not disappear from Signal Desktop nor do they disappear from the recipient's device)

**Expected result:**

- The messages are synchronised to Signal Android and stay there for the duration specified in the "Disappearing messages" menu
- The messages disappear simultaneously from both Signal Desktop and Signal Android when the period specified for "Disappearing messages" has elapsed.

### Screenshots

Desktop:
![signal-desktop-1](https://user-images.githubusercontent.com/1229613/29997387-eaba116e-9011-11e7-9059-c7906d3baf0a.png)
![signal-desktop-2](https://user-images.githubusercontent.com/1229613/29997388-eef386d4-9011-11e7-8ea2-bf2e8a802c28.png)

Mobile:
![signal-android-1](https://user-images.githubusercontent.com/1229613/29997368-8ab10520-9011-11e7-9a46-58f2e039c86d.png)
![signal-android-2](https://user-images.githubusercontent.com/1229613/29997370-8fd6efe2-9011-11e7-944f-ca593560d310.png)

### Platform info

**Operating System**: Ubuntu GNU/Linux 16.04.3 LTS (xaniel) x86_64
**Browser**: N/A (Electron)
**Signal version:** signal-desktop 1.0.22       amd64

**Operating System**: Android 7.1.2, LineageOS version 14.1-20170824-NIGHTLY-oneplus2
**Device**: Oneplus 2
**Signal version:** Signal 4.9.9

### Link to debug log

[Signal Desktop](https://gist.github.com/80b6257811b7775b8e04c00ebe9fce1b)
[Signal Android](https://gist.github.com/e5caede11b46aebe281adfa98e2316d8)

**Comment by Dyras** [comment]
[Signal Desktop Electron debug log](https://gist.github.com/anonymous/ceae18854c24edce218cbb0c44d1f311)
[Signal Android debug log](https://gist.github.com/anonymous/6f102fba3c9f7fb26803ca88535c3fc9)

**Comment by arikb** [comment]
Issue still reproducible on Signal Android 4.11.5 and Signal Desktop 1.0.31

**Comment by scottnonnenberg** [comment]
Okay, I was just able to repro this with Android 4.11.5 and the latest Desktop. Will soon be trying with iOS.

**Comment by scottnonnenberg** [comment]
Does not happen on iOS.

**Comment by Dyras** [comment]
Ordinarily I wouldn't write this but @moxie0 are you working on fixing this? For me this is by far the most annoying issue in Signal as of today. It makes attachments useless in some cases and frankly it's pulling the app down from "Best app I've ever used" to "Unreliably annoying".

If you want a log or something just poke me and I'll bombard you with them. If you want to make a fund to track this issue down I'll happily chip in with some dough to whomever helps you fix it.
