### ISSUE TITLE
Cannot choose to send SMS, button switches back to blue immediately

### ISSUE THREAD

**Issue by FeuRenard** [WhisperSystems/Signal-Android#6929]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After choosing to send an SMS instead of Signal message, the message type switches back immediately to a Signal message.

### Steps to reproduce
- open a Signal conversation
- long-tap send button
- choose unsecured SMS

**Actual result:** Send button switches to gray shortly and then immediately back to Signal blue
**Expected result:** Send button switches to gray, stays gray and I can send a SMS

### Device info

**Device:** Fairphone 2
**Android version:** 6.0
**Signal version:** 4.10.2

### Link to debug log

`09-06 23:21:17.906 1366-1409/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 2025411 , only wrote 2025360
09-06 23:21:17.923 1551-1833/system_process W/InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@d8698e6 attribute=null, token = android.os.BinderProxy@b16999d
09-06 23:21:17.933 3923-3923/org.thoughtcrime.securesms W/ConversationActivity: updateInviteReminder(false)
09-06 23:21:17.934 3923-3923/org.thoughtcrime.securesms W/ConversationActivity: updateDefaultSubscriptionId(-1)
09-06 23:21:17.969 3923-3923/org.thoughtcrime.securesms W/ConversationActivity: updateInviteReminder(false)
09-06 23:21:17.969 3923-3923/org.thoughtcrime.securesms W/ConversationActivity: updateDefaultSubscriptionId(-1)`

**Comment by mrgtreeskier** [comment]
Same issue here. Android 8.0.0, Signal 4.10.3

Log: https://gist.github.com/5cf4e2c530b55e16bc097c8d99712be6

**Comment by mrgtreeskier** [comment]
@moxie0

**Comment by moxie0** [comment]
update to 4.10.4

**Comment by pietervdvn** [comment]
**I opened an issue too. I'm duplicating my information here and will close #6950 **



I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

My contact uses signal, but does not have mobile internet. Thus, sometimes I like to send her an insecure SMS. After switching to the beta builds (4.10.3), selecting 'insecure SMS' does not work as the button switches back to 'signal message'  

### Steps to reproduce
- Open a conversation to a signal contact
- Tap & hold the 'send button' to reveal the sending options
- Select 'insecure SMS'

**Actual result:** The 'send' button still is blue and says 'signal message', signal messages are send when the message is sent
**Expected result:** The 'send' button should be gray and say 'insecure SMS'

### Screenshots


![out](https://user-images.githubusercontent.com/1466478/30250633-2b4ee0a6-9652-11e7-820c-eeba8aaca83d.gif)

(Video is cropped to hide phone number)

### Device info

**Device:** Samsung Galaxy S5; LineageOS; Rooted
**Android version:** 7.1.1
**Signal version:** 4.10.3

### Link to debug log
https://gist.github.com/84d93117b44d7da0857d396229833cf8

**Comment by dcherian** [comment]
@pietervdvn this is fixed. Upgrade your version of Signal.

**Comment by pietervdvn** [comment]
Great! Note to self: update before filing a bug report...

**Comment by pietervdvn** [comment]
Can confirm: is fixed for me
