### ISSUE TITLE
Crash when opening SMS chat (group SMS chats and Signal chats open fine)

### ISSUE THREAD

**Issue by bidrohi** [WhisperSystems/Signal-Android#6931]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Happening after update to 4.10.2. When you try to open a SMS chat it crashes. Group chats open fine. Signal chats open fine.

Signal is used as the SMS app on my phone. Group messages are all SMS recipients. 

### Steps to reproduce
- Go to conversation list
- Open conversations that are known to be SMS

**Actual result:** App crashes and restarts
**Expected result:** Conversation opens

### Screenshots
None

### Device info
**Device:** OnePlus 3
**Android version:** 7.1.1
**Signal version:** 4.10.2

### Link to debug log
https://gist.github.com/anonymous/087663a7543a59f27f4dd4cb4da3bb32

**Comment by moxie0** [comment]
Duplicate #6924
