### ISSUE TITLE
Mms:group list does not match /include all those whose messages are in the group

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#6938]
- [ x] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Received mms message from user who was not listed in the group list at the top. 

### Steps to reproduce
- new install of 4.10.3
- first received mms from one person to a group but when I tap the little group icon, that person /number is not listed but the person's name is listed in the message. This person is in my phone contacts but not in Google contacts.

**Actual result:** see above
**Expected result:** mms would correctly last all those in the conversation in the group icon menu. 

### Screenshots
Didn't get one as it's not my phone 

### Device info
**Device:** Samsung galaxy s7
**Android version:** 7.0
**Signal version:** 4.10.3

### Link to debug log
https://gist.github.com/b800dea4f2d92c581a9c28c72442a23d

**Comment by mrgtreeskier** [comment]
Seconded. I think there is a group MMS bug with the new version.

Device: Pixel XL
Android version: 8.0.0
Signal version: 4.10.3

Log: https://gist.github.com/8e74ed3dfa602ab0e6a22f334952e3c2

**Comment by jeremymasters** [comment]
The same user had all mms conversations merging into one. That could get pretty embarrassing, lol

**Comment by moxie0** [comment]
That should fix it, but anyone who's already gone through the migration has MMS threads that are pretty messed up. =(
