### ISSUE TITLE
Disappearing disappearing messages timer info

### ISSUE THREAD

**Issue by sir-brickalot** [WhisperSystems/Signal-Android#6940]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature request description:
I would love to see an option (or default behaviour) for status info about setting timers for disappearing messages to vanish from a conversation as well.  
*Reason:* If one has the need for using disappearing messages it seems very likely this person does not want anyone to know that there was any exchange of communication at the time.

**Actual result:** If I switch between different timer settings, all of them get listed in the conversation. So if anyone is eavesdropping on my conversation, it might be suspicious to see that information and that could lead to questioning.
**Expected result:** After a 'hidden' conversation disappered, the info about it should disappear as well.

### Device info
All devices, all Signal versions up till now.

**Comment by FeuRenard** [comment]
This was discussed from [this comment](https://github.com/WhisperSystems/Signal-Android/pull/5628#issuecomment-241919892) onwards.

**Comment by sir-brickalot** [comment]
> This was discussed from this comment onwards.  

Thank you. I read the comments and disagree that it 
> "[Just didn't feel quite right](https://github.com/WhisperSystems/Signal-Android/pull/5628#issuecomment-242592764)" (moxie0)

to autodelete, but I overlooked the option to manually delete these messages and think it is an okay workaround.  
**Big but**: Manual deletion of the timer messages is not possible on the Desktop version and deletion in the Android version don't get synchronized over to the Desktop version. So there is no workaround for the workaround either. Is that a know bug?

**Comment by moxie0** [comment]
I think we're going to leave this as-is for now, but feel free to open an issue on the desktop tracker for manual deletion of timer updates if you'd like
