### ISSUE TITLE
Can't switch to send unencrypted message

### ISSUE THREAD

**Issue by WDKevin** [WhisperSystems/Signal-Android#6943]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
A contact that used to have Signal and no longer does will no longer let me switch from encrypted to unencrypted message

### Steps to reproduce
- Have a message open with a contact that used to have signal but no longer does
- Hold down the send button to switch from encrypted message to unencrypted message

**Actual result:** It quickly selects the grey send button and switches back to the blue (encrypted) send button.
**Expected result:** In the past it always just selected the grey send button and let me send the message unencrypted

### Device info

**Device:** Samsung Galaxy Note 4
**Android version:** 6.0.1
**Signal version:** 4.10.3

### Link to debug log
https://gist.github.com/a6e6e652217b3e306d9b26e3749b8e53

### Additional Note
This would ultimately be solved if there was a way to unlink a contact who had signal and was sync'd but no longer uses it. Currently when a user stops using signal, I can't tell unless I send a message and notice there is only 1 checkmark instead of 2. This has been a bug since I started using Signal years ago though.

**Comment by jeremymasters** [comment]
I believe 4.10.5 fixes this in https://github.com/WhisperSystems/Signal-Android/commit/6455c66a0b4bd7dee683ea9b12d733290849c892

**Comment by FaizKhan5** [comment]
Yes 4.10.5 fix this. Issue
