### ISSUE TITLE
"Learn more" web link from "Verify safety number" results in 404 error

### ISSUE THREAD

**Issue by igor2x** [WhisperSystems/Signal-Android#6945]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I click on link "Learn more" in "Verify safety number" I see address whispersystems.org redirects to signal.org and reports 404. It looks like http server redirect for this particular link is not working properly.

### Steps to reproduce
- Start Signal.
- From main Signal window click on pencil button.
- List of contacts is displayed. Click on one of Signal user.
- From top-right menu select "Conversation settings".
- Select "View safety number".
- At the bottom tab on link "Learn more".

**Actual result:**
Now problem appears. In address bar there is https://whispersystems.org/redirect/safety-numbers that redirects to https://signal.org/redirect/safety-numbers but this page displays "404" with text "Something is amiss! You might try browsing for what you wanted." Clicking on link "browsing for what you wanted" displays https://moxie.org web page.

**Expected result:**
Instead o 404 actual help should be displayed.

**My humble suggestion:**
- Quick fix: fix the http server redirect (this will fix help links in currently installed Signal versions)
- Long term fix: replace all of the whispersystems.org links to signal.org in Signal app (the same in iOS and desktop version) to remove chance of redirect problems.

**Comment by vvug** [comment]
Better solution: stop linking and embed the relevant information in the app.
The same goes for the 'who can see this' link in the profile settings page.

**Comment by moxie0** [comment]
Fixed, thanks
