### ISSUE TITLE
Mms from contact comes in as separate conversation from sms from same contact 

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#6947]
I have:
- [ x] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
While sending sms with contact, they sent me an mms gif. It started a new group thread with just myself and this contact. 

### Steps to reproduce
- send sms to user. They reply with sms
- they send mms gif

**Actual result:** starts a new group thread with same user 
**Expected result:** mms comes in to same conversation as sms

### Device info
**Device:** Samsung galaxy s8
**Android version:** 7.0
**Signal version:** 4.10.6

### Link to debug log
https://gist.github.com/anonymous/fc43c5fd79ffdee7d7aa150e9f506abe

**Comment by thinkbrown** [comment]
I've experienced the same exact issue under Signal 4.10.6 on a Huawei Mate 9, running Android 7.0. 

Debug log: https://gist.github.com/anonymous/158c98387075ec0aa69521a135543263

**Comment by mrgtreeskier** [comment]
Have same issue.

Pixel XL
Android 8.0.0
Signal 4.10.6

Log: https://gist.github.com/d1f25a710fbe4432cc19d6684bdbb54d
