### ISSUE TITLE
4.9.9 repeatedly crashing, cannot start app any more

### ISSUE THREAD

**Issue by sstefan** [WhisperSystems/Signal-Android#6948]
I have:
- [ X ] searched open and closed issues for duplicates
- [ X ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
----------------------------------------

### Bug description
Signal 4.9.9 does not start properly anymore, crashes immediately.
Similarities with #6850, but different log message.

Unsure if that has started just suddenly or after a recent update from Play store.

### Steps to reproduce
- starting Signal app via icon
**Actual result:** popup appears stating that app has been closed ("Signal wird wiederholt beendet" on second try)
**Expected result:** App starts correctly to e.g. show contact list.

### Screenshots
![screencap](https://user-images.githubusercontent.com/951607/30249440-0393e12a-963d-11e7-8adf-5c62da132bd3.png)

### Device info
**Device:** Samsung Galaxy S6 (SM-G920F)
**Android version:** 7.0
**Signal version:** 4.9.9

Device is not rooted; I'd be very interested in a way to fix the problem without data loss, but any hint on how to get it running at all again is highly appreciated as well!

### Link to debug log
[adb_logcat_signal_4.9.9_crash.txt](https://github.com/WhisperSystems/Signal-Android/files/1290553/adb_logcat_signal_4.9.9_crash.txt)

**Comment by Dyras** [comment]
Does it work if you join the beta and install the beta updates?

**Comment by sstefan** [comment]
Still doesn't fully start (crashes) with 4.10.7 from beta. Same with flight mode activated (and Wifi off).

Here's the relevant part of logcat's output for this version:
09-11 19:05:43.469  9189  9189 W PartProvider: onCreate()
09-11 19:05:43.522  9189  9189 W PersistentAlarmManagerListener: class org.thoughtcrime.securesms.service.RotateSignedPreKeyListener scheduling for: 1505208433821
09-11 19:05:43.522  3651  6420 D SamsungAlarmManager: Cancel Alarm calling from uid:10310 pid :9189 / op:PendingIntent{df3be60: PendingIntentRecord{3097f19 org.thoughtcrime.securesms broadcastIntent}}
09-11 19:05:43.527  3651  5035 D SamsungAlarmManager: setInexact Intent (T:0/F:0/AC:false) 20170912T112713 - CU:10310/CP:9189
09-11 19:05:43.528  9189  9189 W PersistentAlarmManagerListener: class org.thoughtcrime.securesms.service.DirectoryRefreshListener scheduling for: 1505161272027
09-11 19:05:43.528  3651  3666 D SamsungAlarmManager: Cancel Alarm calling from uid:10310 pid :9189 / op:PendingIntent{61aebde: PendingIntentRecord{90841bf org.thoughtcrime.securesms broadcastIntent}}
09-11 19:05:43.531  3651  3859 D SamsungAlarmManager: setInexact Intent (T:0/F:0/AC:false) 20170911T222112 - CU:10310/CP:9189
09-11 19:05:43.547  9189  9189 D JVM     : JVM::Initialize@[tid=9189]
09-11 19:05:43.547  9189  9189 D JVM     : JVM::JVM@[tid=9189]
09-11 19:05:43.547  9189  9189 D JVM     : LoadClasses
09-11 19:05:43.547  9189  9189 D JVM     : name: org/webrtc/voiceengine/BuildInfo
09-11 19:05:43.547  9189  9189 D JVM     : name: org/webrtc/voiceengine/WebRtcAudioManager
09-11 19:05:43.547  9189  9189 D JVM     : name: org/webrtc/voiceengine/WebRtcAudioRecord
09-11 19:05:43.547  9189  9189 D JVM     : name: org/webrtc/voiceengine/WebRtcAudioTrack
09-11 19:05:43.570  9189  9189 W PassphraseRequiredActionBarActivity: onCreate(null)
09-11 19:05:43.627  9189  9189 W ExperienceUpgradeActivity: getExperienceUpgrade(268)
09-11 19:05:43.628  9189  9189 W PassphraseRequiredActionBarActivity: routeApplicationState(), state: 5
09-11 19:05:43.653  9189  9189 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
09-11 19:05:43.684  9189  9224 I SQLiteConnectionPool: The connection pool for +data+user+0+org_thoughtcrime_securesms+databases+messages_db has been closed but there are still 1 connections in use.  They will be closed as they are released back to the pool.
09-11 19:05:43.691  9189  9224 E AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
09-11 19:05:43.691  9189  9224 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 9189
09-11 19:05:43.691  9189  9224 E AndroidRuntime: java.lang.AssertionError: Unable to resolve: 28
09-11 19:05:43.691  9189  9224 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.DatabaseFactory$DatabaseHelper.onUpgrade(DatabaseFactory.java:965)
09-11 19:05:43.691  9189  9224 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
09-11 19:05:43.691  9189  9224 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
09-11 19:05:43.691  9189  9224 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SmsDatabase.getExpirationStartedMessages(SmsDatabase.java:655)
09-11 19:05:43.691  9189  9224 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.ExpiringMessageManager$LoadTask.run(ExpiringMessageManager.java:57)
09-11 19:05:43.691  9189  9224 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-11 19:05:43.691  9189  9224 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-11 19:05:43.691  9189  9224 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:762)
09-11 19:05:43.726  9189  9189 W KeyCachingService: onCreate()
09-11 19:05:43.762  9189  9189 W service : Broadcasting new secret...
09-11 19:05:43.767  3651  3669 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{f256752 u0 org.thoughtcrime.securesms.service.action.NEW_KEY_EVENT to ReceiverList{23200c7 9189 org.thoughtcrime.securesms/10310/u0 remote:2b7a206}: process crashing
09-11 19:05:43.767  9189  9189 W KeyCachingService: onStartCommand, null
09-11 19:05:43.806  9189  9189 W ExperienceUpgradeActivity: getExperienceUpgrade(268)
09-11 19:05:43.892  9189  9189 D ViewRootImpl@4909bab[ExperienceUpgradeActivity]: ThreadedRenderer.create() translucent=false
09-11 19:05:43.895  9189  9189 D InputTransport: Input channel constructed: fd=62
09-11 19:05:43.896  9189  9189 D ViewRootImpl@4909bab[ExperienceUpgradeActivity]: setView = DecorView@2429208[ExperienceUpgradeActivity] touchMode=true
09-11 19:05:43.904  9189  9189 D ViewRootImpl@4909bab[ExperienceUpgradeActivity]: dispatchAttachedToWindow
09-11 19:05:43.953  9189  9189 D ViewRootImpl@4909bab[ExperienceUpgradeActivity]: Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,0][1440,2560] result=0x7 surface={isValid=true -903493632} surfaceGenerationChanged=true
09-11 19:05:43.953  9189  9189 D ViewRootImpl@4909bab[ExperienceUpgradeActivity]: mHardwareRenderer.initialize() mSurface={isValid=true -903493632} hwInitialized=true
09-11 19:05:43.995  9189  9295 D libEGL  : loaded /vendor/lib/egl/libGLES_mali.so
09-11 19:05:44.024  9189  9295 I OpenGLRenderer: Initialized EGL, version 1.4
09-11 19:05:44.024  9189  9295 D OpenGLRenderer: Swap behavior 1
09-11 19:05:44.034  9189  9295 D mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1440x2560]-format:1
09-11 19:05:44.105  9189  9189 D ViewRootImpl@4909bab[ExperienceUpgradeActivity]: MSG_RESIZED_REPORT: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
09-11 19:05:44.145  9189  9189 W PassphraseRequiredActionBarActivity: onDestroy()
09-11 19:05:44.145  9189  9189 D Graph   : removeVertex() : insertDummyVertex, because there is no ancestor.
09-11 19:05:45.627  3651  6418 E ActivityManager: Found activity ActivityRecord{b56a9b7d0 u0 org.thoughtcrime.securesms/.ExperienceUpgradeActivity t2874 f} in proc activity list using null instead of expected ProcessRecord{1f8dac 9189:org.thoughtcrime.securesms/u0a310}
09-11 19:05:45.629  9189  9189 D ViewRootImpl@4909bab[ExperienceUpgradeActivity]: mHardwareRenderer.destroy()#1
09-11 19:05:45.630  9189  9189 D ViewRootImpl@4909bab[ExperienceUpgradeActivity]: Relayout returned: oldFrame=[0,0][1440,2560] newFrame=[0,0][0,0] result=0x0 surface={isValid=false 0} surfaceGenerationChanged=true
09-11 19:05:45.638  3651  6418 I ActivityManager: Killing 9189:org.thoughtcrime.securesms/u0a310 (adj 199): crash
09-11 19:05:45.638  3651  6418 D ActivityManager: cleanUpApplicationRecord -- 9189

**Comment by moxie0** [comment]
Somehow, your client has an identity key which references a canonical ID that doesn't exist. That should never be possible, and represents a "constraints violation" that there is no straightforward way to resolve. Looking at the crash log stats, somehow this client is the only client in the world (so far) to encounter this condition. We could manually edit the database to fix the constraint problem, but without root that's not possible. I'll keep thinking about how to proceed.

**Comment by moxie0** [comment]
@sstefan If you're still in this state, I think I can send you a custom APK that will resolve the conflict.

**Comment by sstefan** [comment]
@moxie0: Yes, I am. - your offer sounds great, thanks in advance!

**Comment by moxie0** [comment]
@sstefan Give this a shot: https://mega.nz/#!w8cXCRAJ!IdySG3_3G5c8uZf1rU1w7HASFDYCNix1oowzCD61OtY

**Comment by sstefan** [comment]
@moxie0: Thanks. Unfortunately that didn't work, as I already was on version 4.10.7 (version number 294), and I didn't succeed in downgrading the app using e.g. 
    adb install -r -d Signal-debug-sstefan.apk
not even after a 
    adb shell pm uninstall -k org.thoughtcrime.securesms

**Comment by sstefan** [comment]
Never mind, I'll reinstall, although it's a pity to loose the saved conversations and photos.

It would be great to really be able to do a complete backup (including configuration/keys) in some future version.

**Comment by Kieranlp** [comment]
I encountered the same problem.
Is it still no fix for this bug ?

**Comment by greyson-signal** [comment]
@Kieranlp Are you sure you have this exact problem and not some other crash? Please open a new ticket, fill out the template, and include a debug log. Thanks!
