### ISSUE TITLE
Send-button switches back to 'Signal' when 'Insecure SMS' is selected for signal contacts

### ISSUE THREAD

**Issue by pietervdvn** [WhisperSystems/Signal-Android#6950]
** DUPLICATE - information here was copied to #6929 **

I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

My contact uses signal, but does not have mobile internet. Thus, sometimes I like to send her an insecure SMS. After switching to the beta builds (4.10.3), selecting 'insecure SMS' does not work as the button switches back to 'signal message'  

### Steps to reproduce
- Open a conversation to a signal contact
- Tap & hold the 'send button' to reveal the sending options
- Select 'insecure SMS'

**Actual result:** The 'send' button still is blue and says 'signal message', signal messages are send when the message is sent
**Expected result:** The 'send' button should be gray and say 'insecure SMS'

### Screenshots

![out](https://user-images.githubusercontent.com/1466478/30250633-2b4ee0a6-9652-11e7-820c-eeba8aaca83d.gif)

(Video is cropped to hide phone number)

### Device info

**Device:** Samsung Galaxy S5; LineageOS; Rooted
**Android version:** 7.1.1
**Signal version:** 4.10.3

### Link to debug log
https://gist.github.com/84d93117b44d7da0857d396229833cf8

**Comment by FeuRenard** [comment]
This is a duplicate of #6929.

**Comment by pietervdvn** [comment]
Indeed. I'm closing this one, I copied all this information over!
