### ISSUE TITLE
Refresh contact list: Progress indicator circling, circling & circling

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/Signal-Android#6957]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Since a) Signal v4.9 or v4.10 **OR** (not sure) b) since installing Android 8.0.0, the progress indicator circles pretty long when refreshing the contact list. I don't even know if the contact list is refreshed successfully or not.

### Steps to reproduce
- Go to contact list
- Pull screen downwards, i. e. refresh contact list

**Actual result:** Progress indicator circling for at least a minute (if it stops at all)
**Expected result:**  Contact list refreshes within a couple of seconds

### Screenshots

None

### Device info

**Device:** Nexus 5X
**Android version:** 8.0.0
**Signal version:** 4.10.8

### Link to debug log

Anything in there? Did it refresh successfully?
https://gist.github.com/anonymous/21e701288e39b07d1e9ce74f5b026103

**Comment by jeremymasters** [comment]
I also experience this with the additional issue of bad sort order of contacts after refresh.

**Comment by RiseT** [comment]
> with the additional issue of bad sort order of contacts after refresh.

I have this as well. My guess is that the bad sort order is a variation of https://github.com/WhisperSystems/Signal-Android/issues/6488

**Comment by RiseT** [comment]
This seems fixed for me. I'll re-open if anybody is still experiencing this.
