### ISSUE TITLE
Read Confirmations

### ISSUE THREAD

**Issue by ax3l** [WhisperSystems/Signal-Android#6959]
I have:
- [x] searched open and closed issues for duplicates and only buried in #838 seems to be the topic in a comment
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature request description

Is it currently impossible to disable the sent of read confirmations?

Read confirmations can potentially be intrusive to private life and several aspects regarding stalking. It would be great if one could disable sending read confirmations via the settings.

### Steps to reproduce
- send a message
- check the read confirmation (double tick)

**Actual result:** Always sent.
**Expected result:** Allow to disable the confirmation to protect my privacy.

### Device info

**Device:** all
**Android version:** 7.1.1
**Signal version:** 4.9.9

**Comment by rainerzufall** [comment]
There are currently no read confirmations in Signal! 
see: https://support.signal.org/hc/en-us/articles/212535538-How-do-I-know-if-a-message-has-been-delivered-

> One check mark in your message bubble indicates that your Signal message has been sent to our servers or your insecure SMS was sent to your provider. 

> Two check marks in your message bubble indicate that the Signal message or insecure SMS has been delivered to your contact's device. This does not indicate the message was read. Your contact will only get this message if their phone is online. 

Therefore, please close this issue.

**Comment by ax3l** [comment]
All right, thanks for the info! :)
