### ISSUE TITLE
Sometimes Signal Not Working For Sending Anything

### ISSUE THREAD

**Issue by FaizKhan5** [WhisperSystems/Signal-Android#6967]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

Bug description
Sometimes i open signal, Friend profile picture in conversation not showing and also no blue button of signal nor call padlock on top it seems like signal communication not working and also cant delete anything when you delete something in that condition its loading and cant delete. 
After Restart Phone It Works Fine.  

Device info
Device: Qmobile Noir i6 Metal ONE
Android version: 6.0
Signal version: 4.10.11

https://gist.github.com/anonymous/c6b7d40b11e5856a475a113d0e9b82c9#file-cat-log-L185

**Comment by rainerzufall** [comment]
please attach a debug log to your report (taken directly after you have experienced such a situation), without it there is almost no chance that the devs can help you.
Here you can find how this is done: https://support.signal.org/hc/en-us/articles/212535838-How-do-I-send-a-debug-log-from-Signal-Android-

**Comment by FaizKhan5** [comment]
@moxie0 check debug log :)

**Comment by maxxer** [comment]
I'm having similar issue. Sometimes after going back to Signal I just see *Send unsecure SMS*, but I've not enabled Signal to handle SMSes! Also anything written in it get lost, it's not sent anywhere. As stated in one of the linked issues, forcing close of Signal and reopening restores functionality.

**Comment by maxxer** [comment]
Some time ago I had the *Unsecure SMS* issue. I captured [this debug log](https://gist.github.com/5ff9b9f0bead7923bcbc2629b1590290). Apparently there was poor connectivity at the moment. Later on I tried again and I was able to use Signal messages.

What is quite annoying is that you can still send a message that way, but that won't get deliver, and also will get lost when you close the chat! While the chat is open the message is in *sending*, when you close and come back to the chat the message is disappeared

**Comment by FaizKhan5** [comment]
@moxie0 My problem is solved now i notice from a long time and i facing no issue so if you want to close issue then close this but i don't know anyone has still that issue :)
