### ISSUE TITLE
4.10.x no Signal contacts in system Share dialog

### ISSUE THREAD

**Issue by dcherian** [WhisperSystems/Signal-Android#6968]
The system "share" dialog used to show signal contacts as options, saving the user from having to choose signal and then pick a contact.

After the upgrade to 4.10.x, this had not been possible. On my phone the share dialog now only shows WhatsApp contacts as options, no Signal contacts.

Moto G4 Play
Android 7.0
Signal 4.10.9

To reproduce, attempt to share something from any app.

Can anyone else confirm this behaviour?

**Comment by johanw666** [comment]
When I press share on a picture I see a list of applications including Signal. Sharing it to Signal opens Signal, when I select a conversation the file is included.
