### ISSUE TITLE
Signal sent a lot of SMS messages without any reason (repeated the same message to same person)

### ISSUE THREAD

**Issue by gaborgulyas** [WhisperSystems/Signal-Android#6975]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Today I was trying to send a regular SMS message via signal app. It was not successful (maybe because the signal of the network was weak and sometimes disappeared), and all the sudden Signal started to repeatedly send the message in a crazy speed. My phone asked if I still want to allow that, but even when pressing deny the question came back. As this rendered my phone useless, I made a restart. The problem came back after the restart. I switched back to the default SMS app, and this has not happened since. (The problem never appeared either before.)

### Steps to reproduce
I have no clue. Never happened before and since. See my description for details.

**Actual result:** N/A
**Expected result:** N/A

### Screenshots
N/A

### Device info
**Device:** [willing to disclose privately]
**Android version:** [willing to disclose privately]
**Signal version:** 4.9.9

### Link to debug log
Didn't capture. Next time I'll do!

**Comment by gaborgulyas** [comment]
Could be important: the messages sent out by signal got delivered multiple tens of times to the recipient.

**Comment by FeuRenard** [comment]
Sounds very similar to #5997

**Comment by gaborgulyas** [comment]
Indeed. Thanks for noting, I didn't find that one!
