### ISSUE TITLE
4.9.9 repeatedly crashing, cannot open signal

### ISSUE THREAD

**Issue by Fine-Tune** [WhisperSystems/Signal-Android#6980]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After updating to Signal 4.9.9 I can not open signal anymore without crash.
About 5 minutes before I updated to 4.9.9 I received a message from DHL (shipping company) without any issue opening signal and/or reading the message. After the update I could no longer open it. I have tried to manually delete these messages from the database but didn't find a tool to do so. The line number that keep showing up in cat-log, crash-log & stack trace is Line number 3140.

### Steps to reproduce
- Every time I open Signal.

**Actual result:** "Unfortunately, Signal has stopped"
The solutions provide through email support didn't work either. (Airplane mode, clear cache etc.)

### Device info

**Device:**Samsung Galaxy S5 Neo (SM-G903F)
**Android version:** s5neollte: 6.0.1
**Signal version:** 4.9.9 (updated to 4.10.11 by now)

Phone is rooted

### Link to debug log

[alogcat.2017-09-19-11-10-05+0200.txt](https://github.com/WhisperSystems/Signal-Android/files/1321384/alogcat.2017-09-19-11-10-05.0200.txt)

**Comment by moxie0** [comment]
Doesn't look like there's anything in this log, you have to capture it immediately after the crash.

**Comment by Fine-Tune** [comment]
I did capture it after the crash though.

Would these screenshot files help?
![screenshot_20170912-182322](https://user-images.githubusercontent.com/32166876/30748074-6e76ea98-9faf-11e7-974c-cf966f883930.png)
![screenshot_20170922-144627](https://user-images.githubusercontent.com/32166876/30748075-6e793cd0-9faf-11e7-85e6-05e8a6870529.png)
![screenshot_20170922-144632](https://user-images.githubusercontent.com/32166876/30748076-6ea06670-9faf-11e7-9dd9-591e6b5c0d85.png)

and txt. (for some reason it doesn't allow me to upload it.)

Process: org.thoughtcrime.securesms
Flags: 0x38d83e44
Package: org.thoughtcrime.securesms v297 (4.10.11)
Build: samsung/s5neoltexx/s5neolte:6.0.1/MMB29K/G903FXXU1BQC1:user/release-keys

java.lang.AssertionError: Error type: NOT_A_NUMBER. The phone number supplied was null.
	at org.thoughtcrime.securesms.database.DatabaseFactory$NumberMigrator.<init>(DatabaseFactory.java:1427)
	at org.thoughtcrime.securesms.database.DatabaseFactory$DatabaseHelper.onUpgrade(DatabaseFactory.java:903)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
	at org.thoughtcrime.securesms.database.SmsDatabase.getExpirationStartedMessages(SmsDatabase.java:655)
	at org.thoughtcrime.securesms.service.ExpiringMessageManager$LoadTask.run(ExpiringMessageManager.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: Error type: NOT_A_NUMBER. The phone number supplied was null.
	at com.google.i18n.phonenumbers.PhoneNumberUtil.parseHelper(PhoneNumberUtil.java:3140)
	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:3032)
	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:3022)
	at org.thoughtcrime.securesms.database.DatabaseFactory$NumberMigrator.<init>(DatabaseFactory.java:1424)
	... 8 more

**Comment by moxie0** [comment]
Somehow Signal doesn't know what your number is. Is it possible that you're using Signal without having registered somehow?

**Comment by Fine-Tune** [comment]
That's correct yes, Ive been using the app like that since it was released without any issues until 4.9.9

**Comment by moxie0** [comment]
How did you get past the registration screen without registering?

**Comment by Fine-Tune** [comment]
Honestly I don't know, it's been a couple years since I installed Signal, most likely I did register or there was a register later option, just guessing.

**Comment by moxie0** [comment]
You're the second person to find themselves in this situation. The other person who posted here had been using Signal since it was an encrypted SMS app and then decided not to register when it started using the data channel instead.

For two years you've been using Signal with a big banner at the top that says "Enable Signal messages and calls?"  Is there a reason you have been using Signal this way? There is no security value to sending unencrypted SMS messages via Signal.

**Comment by Fine-Tune** [comment]
As far as I'm aware I haven't been bothered with a banner, maybe that's because I'm using X-privacy as well. I do understand there is no extra security value in using signal as a regular sms app, but since none of my contacts use the app in the secure way I supposed it didn't matter. For now I'm just looking for a solution to get the access back to my messages, been trying to downgrade without luck and uninstall/reinstall will delete my messages. I do have a database backup and a backup from the securesms folder though, so I guess I could put this folder back once I reinstalled the app.

**Comment by Fine-Tune** [comment]
Solved with Titanium Backup
