### ISSUE TITLE
Ability to choose preferred SIM for SMS on a per-contact basis (dual SIM)

### ISSUE THREAD

**Issue by novoid** [WhisperSystems/Signal-Android#6984]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

When using a dual SIM Android phone, un-encrypted text messages (SMS) are sent from the primary SIM card even when all received text messages from this contact were received by the secondary SIM.

### Steps to reproduce

SIM1 is the primary SIM with the data connection.

SIM2 is the secondary SIM without data connection. _In my case, Signal was registered using the number of SIM2. However, sending/receiving encrypted messages via SIM1 only works flawlessly, thanks!_

- open existing conversation of a contact which does not use Signal (yet)
  - this contact does only know my SIM2 number and thus, the whole conversation so far was written to and sent by my SIM2
- send an un-encrypted text message without manually switching the send-button to SIM2; SIM1 is always selected and used by default

**Actual result:** 

- the contact gets my message from my SIM1 phone number which she did not recognize
- my text message gets misinterpreted as spam which results in a failed conversation

**Expected result:** 

- my text message gets sent via SIM2 (as before) and my contact recognizes my number

IMHO, this can be accomplished in two ways:

1. Signal asks me once (per un-encrypted conversation) which SIM I want to use for this contact
    - This can be modified in the conversation settings
2. Signal analyses the conversation so far and if (a) every or (b) the most recent ones or (c) the previous message was sent from SIM2, use SIM2 as long as I manually don't switch the SIM for this conversation.

I'd go with 2. (c) because it seems to be the most intuitive solution without additional UI elements for switching default SIM in the conversation settings.

### Device info

**Device:** OnePlus 5
**Android version:** 7.1.1
**Signal version:** 4.9.9

**Comment by FeuRenard** [comment]
Just for reference, [here](https://github.com/WhisperSystems/Signal-Android/issues/5266#issuecomment-280821696) is written how the current implementation is intended to work:

> 1. If you receive an SMS for someone on a SIM, the default for that conversation will update to that SIM, unless you're actively in the conversation and have explicitly selected a different SIM manually.
> 
> 2. The Android N API will give me access to the "preferred SMS SIM" system setting, so if you're on Android N new conversations use that

So if I understand Moxie's intention in (1) correctly, dual SIM handling should already behave as you desire (except that it analyses incoming SMS).

Did you receive any SMS in this conversation via Signal (or were they all imported)?

**Comment by novoid** [comment]
Both. I imported the messages from my old phone via backup/restore. However, the issue appeared after I received a new message.

So:

1. import of message backup from old phone
    - conversation was with SIM2 (which was only SIM in old phone)
2. receiving of new un-encrypted text message to SIM2
3. my answer (un-encrypted text message) was sent from SIM1 (the default data SIM if this matters)

**Comment by novoid** [comment]
It seems to be the case that my issue was a migration issue.

After having defined default SIMs for each conversation, Signal is re-using this choice.

Sorry for the fuzz.
