### ISSUE TITLE
[Feature Request] Swipe left/right to next media item within conversation

### ISSUE THREAD

**Issue by vitobcn** [WhisperSystems/Signal-Android#6994]
On other messaging apps, the typical behavior within a conversation that includes multiple media files such as images, is to allow swiping left/right to the previous/next one.
If multiple images are shared in a conversation, that makes it much easier to go through them all without leaving fullscreen.
In Signal if, let's say, 5 images are shared in a row, you need to open them individually, then go back, open the next one and repeat until done.

**Comment by FeuRenard** [comment]
This is a duplicate of #2355.

**Comment by vitobcn** [comment]
Apologies, I wasn't able to find #2355 before posting.
I will close this one.
