### ISSUE TITLE
Changes are not saved when editing pictures with the brush tool

### ISSUE THREAD

**Issue by justin-** [WhisperSystems/Signal-Android#6998]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Changes are not saved after editing a picture

### Steps to reproduce
- Take a picture or attach an existing picture inside of a conversation but don't send it
- Tap the edit icon on the preview thumbnail
- Use the brush tool to draw on the picture, then tap the checkmark at the top left to confirm changes. Do not use any of the other tools
- The edits will not be present

**Actual result:** The picture is unchanged
**Expected result:** The picture reflects the edits made by the user

### Device info
**Device:** Google Pixel
**Android version:** 8.0.0
**Signal version:** 4.10.12

**Comment by FeuRenard** [comment]
I can **not** reproduce this.

### Device info

**Device:** Fairphone 2
**Android version:** 6.0.1
**Signal version:** 4.10.12

**Comment by ahtmatrix** [comment]
I can reproduce this

Turning disappearing messages on or off gives the same result

Device info
Device: Nexus 6P
Android version: 8.0
Signal version: 4.10.12
