### ISSUE TITLE
Show message text at direct reply with privacy option of only showing the name of sender

### ISSUE THREAD

**Issue by hlorenz** [WhisperSystems/Signal-Android#6999]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I enabled the option "Show name only" in "Notifications". When I receive a message, the text "New message" is shown in my notifications (which is intended), but when I want to reply directly in the notification, it should show the message that I received (but still shows the "New message" text). How can I answer if I don't know what the message was.
This worked on my old phone with Android 4.2.2, but does not with my new one with Android 7.

### Steps to reproduce
- In options: Notifications > Show > Name only
- Close Signal
- Receive new message
- Try to reply directly from your notifications

**Actual result:** When I use direct reply within the notifications, "New message" is shown
**Expected result:** When I hit direct reply within the notifications, the message text should be shown

### Screenshots

![screenshot_20170928-140050](https://user-images.githubusercontent.com/12643214/30965572-1d6325b2-a456-11e7-9ed6-e87e64a11baf.png)

### Device info

**Device:** OnePlus 5
**Android version:** 7.1.1
**Signal version:** 4.10.12

**Comment by moxie0** [comment]
Sorry there's no way to do this that I know of on Android.
