### ISSUE TITLE
Limited video size?

### ISSUE THREAD

**Issue by jedie** [WhisperSystems/Signal-Android#700]
Seems that sending video files are limited in size... Don't know if it's pixel size or file size?!?

IMHO there should be exist no size limit.

**Comment by joelthelion** [comment]
Any updates on this? I'd really like to be able to use TextSecure! But 300kB videos is a steep limitation...

**Comment by mad-de** [comment]
280 kb as well for Audio files. That's a major usability flaw there...

**Comment by volcano99** [comment]
what is the current video size limit?

**Comment by rmueller83** [comment]
https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/mms/PushMediaConstraints.java#L25 references to https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/mms/MmsMediaConstraints.java#L5 where we have a limit of 280kb for videos. Presumably it is sufficient to change that first line.

**Comment by agrajaghh** [comment]
@rmueller83 I don't think its that easy since MMS are still supported and don't work with bigger files...

**Comment by rmueller83** [comment]
@agrajaghh This is why the change should take place in PushMediaConstraints.java while MmsMediaConstraints.java should stay as it is.

**Comment by agrajaghh** [comment]
oops, didn't look carefully enough...

**Comment by rmueller83** [comment]
@agrajaghh As you seem to have a working build environment, could you please test this by replacing PushMediaConstrains.java line 25 with `return 10 * MB;` ?
The whole infrastructure seems to be ready for this since I can successfully send larger videos from Signal (iOS) to TextSecure (Android) and watch them there.

**Comment by agrajaghh** [comment]
@rmueller83 thats not working, Slide is thowing a MediaTooLargeException for MMS and Push:
https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/mms/Slide.java#L113

But I guess @mcginty is going to increase the limit anyway, when he has the time ;)

**Comment by rmueller83** [comment]
@agrajaghh Okay, thanks for your efforts anyway!

**Comment by mcginty** [comment]
It's just a matter of limiting auto-downloads of large files depending on the network you're on before we increase the size.

**Comment by 2-4601** [comment]
Closing: resolved by 551274f167db2905714b0b76abc97394a2e221f6
