### ISSUE TITLE
4.10.12 crash after sending message in a group

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-Android#7000]
I have:
- [X] searched open and closed issues for duplicates, same as/related to https://github.com/WhisperSystems/Signal-Android/issues/6989?
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Crash that occurred after sending a message to a group. 

### Steps to reproduce
- send message in a group

**Actual result:** crash
**Expected result:** No crash

### Screenshots
 N/A

### Device info

**Device:** Google Pixel
**Android version:** 8.0.0
**Signal version:**4.10.12

### Link to debug log
 https://gist.github.com/anonymous/e79fe9926b1c9be1b0a5a746b333a20d

**Comment by moxie0** [comment]
duplicate #6894
