### ISSUE TITLE
option to use old group chat ui

### ISSUE THREAD

**Issue by cgag** [WhisperSystems/Signal-Android#7001]
I can't emphasize enough how much I don't want to see peoples profile pictures, or read their names on every single message they send (!?).  Is there an option to just have their names be their first initial and not show them on the message?

Is there an option to just have their names be their first initial and not show them on the message? Could such a thing be added?

**Comment by moxie0** [comment]
They were always shown before, just outside the bubble, so people would get confused whether it referred to the bubble above or the bubble below.

**Comment by mueller-ma** [comment]
Might it be possible to have an option to hide names in group chats? Color and picture is often enough to know the person.
