### ISSUE TITLE
Signal user marked as non-signal user in conversation for 10-15 seconds

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#7002]
I have:
- [x ] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Once in awhile, I am in a conversation with a signal user and for about 10-15 seconds, the blue circle with airplane changes to gray and the text changes to "send unsecure sms message".  I don't really have particular steps to repro this with, but it _seems_ to happen if I'm chatting with a signal user and during that, another contact I've invited to use signal installs it and messages me.

### Steps to reproduce
see above

**Actual result:** Signal contacts appearing as non-signal contacts sometimes in-conversation with them
**Expected result:** Signal contacts always show as signal contacts in-conversation unless they've uninstalled the app, etc.

### Device info
**Device:** Samsung Galaxy S8
**Android version:** 7.0
**Signal version:** 4.10.12

**Comment by jeremymasters** [comment]
https://gist.github.com/a23186555fa2e94fcf3c1a45698aac51
Current signal user last two digits are 76, new user was 91

**Comment by FaizKhan5** [comment]
duplicate #6967

**Comment by jeremymasters** [comment]
There is overlap but I think I have more anecdotal evidence as well as more specific timing information.

**Comment by benmayne** [comment]
same thing for me today. 

https://gist.github.com/anonymous/df59abe130de535c22ef86c5fdb67e89

![screenshot_20171022-120727](https://user-images.githubusercontent.com/3374110/31866197-bf8264ba-b730-11e7-8483-efe40fc7816f.png)
