### ISSUE TITLE
After Changing Profile Pictures Takes Too Much Time To Show Other People

### ISSUE THREAD

**Issue by FaizKhan5** [WhisperSystems/Signal-Android#7004]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

Bug description
Everytime when i change my profile picture it takes too much time to show on other people phones like 1hr/2hrs/6hrs/12hrs in contact badges but immediately shows on call screen

Actual result: Takes too much time to show people in contact badge but only shows on when someone call me then they see my new picture
Expected result: Immediately show to others in contact badge after changing picture 

Device info
Device: Qmobile Noir i6 Metal ONE
Android version: 6.0
Signal version: 4.10.12

Link to debug log

**Comment by cascheberg** [comment]
Other people will see your new profile after you sent them a message.

When you update your profile, a new profile key is generated, which is required to decrypt the profile. The profile key is part of every outgoing message. So when contacts receive a message from you, they will see that your profile key has changed and will update your profile from the server.

I think currently there is no mechanism to automatically distribute new profile keys to contacts.

**Comment by moxie0** [comment]
A new key shouldn't be generated, so it's just a matter of the other clients polling the endpoint to determine if something has changed. I think the first question is what platform the "other" people (who don't see your profile photo change) are on?

**Comment by FaizKhan5** [comment]
Android To Android

**Comment by mawed** [comment]
@moxie0 does this include, deleting a contact from address book won't stop sharing profile updates (as the contact has the key already)?

**Comment by FaizKhan5** [comment]
I notice that now this problem is solved and profile pics shows on the other side instantly :+1:
