### ISSUE TITLE
Crash when registering on new device and viewing group chats

### ISSUE THREAD

**Issue by hughdavenport** [WhisperSystems/Signal-Android#7005]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

My old phone broke, and I got lent one by a friend, Samsung S3 (model GT-I9300), running CyanogenMod (11.0-InstallerXNPQ32P) with android 4.4.4 which is old but they asked me not to reflash it as it had some tools that were hard to set up and worked which they didn't want breaking.

The google play framework was out of date, so couldn't install via the play store, instead getting the apk from https://signal.org/android/apk/ and installing it. I have swapped sims from old phone, and started up signal, registered and sent test message to my friend which worked, they could send one back and that worked. Later I asked someone from a group chat I was in to send a message to the group, and it came through, but now everytime I open the app it crashes with the stack trace shown below. I get notifications fine, but whenever I go into the app it crashes.

I cleared data and reinstalled the apk and it still does this repeatably.

It also has xposed framework on it, but I couldn't see how to disable that so unsure if it is interfering.

I'm just wondering whether this would be an issue with:
- signal
- old cyanogen
- old gapps
- xposed

Attached the logs below, let me know if you need more than that.

### Steps to reproduce
- Have a group chat on one phone
- Register a new device running outdated software?
- Receive a group chat message

**Actual result:** Crash
**Expected result:** Signal works as normal, can view group chat messages, no crash.

### Device info

**Device:** Samsung S3 (model GT-I9300)
**Android version:** 4.4.4
**Signal version:** 4.10.12

### Link to debug log
```
E/AndroidRuntime( 5212): FATAL EXCEPTION: JobConsumer-0
E/AndroidRuntime( 5212): Process: org.thoughtcrime.securesms, PID: 5212
E/AndroidRuntime( 5212): java.lang.IllegalStateException: Cannot set request property after connection is made
E/AndroidRuntime( 5212):        at com.android.okhttp.internal.http.HttpURLConnectionImpl.setRequestProperty(HttpURLConnectionImpl.java:508)
E/AndroidRuntime( 5212):        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.setRequestProperty(HttpsURLConnectionImpl.java:294)
E/AndroidRuntime( 5212):        at org.whispersystems.signalservice.internal.push.PushServiceSocket.downloadAttachment(PushServiceSocket.java:468)
E/AndroidRuntime( 5212):        at org.whispersystems.signalservice.internal.push.PushServiceSocket.retrieveAttachment(PushServiceSocket.java:372)
E/AndroidRuntime( 5212):        at org.whispersystems.signalservice.api.SignalServiceMessageReceiver.retrieveAttachment(SignalServiceMessageReceiver.java:119)
E/AndroidRuntime( 5212):        at org.whispersystems.signalservice.api.SignalServiceMessageReceiver.retrieveAttachment(SignalServiceMessageReceiver.java:88)
E/AndroidRuntime( 5212):        at org.thoughtcrime.securesms.jobs.AvatarDownloadJob.onRun(AvatarDownloadJob.java:85)
E/AndroidRuntime( 5212):        at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
E/AndroidRuntime( 5212):        at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
E/AndroidRuntime( 5212):        at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)

```

**Comment by moxie0** [comment]
That code is unchanged since February of 2015. I can't really offer support as long as shit like Xposed is running, if you get it running stock Android and something is still wrong I can look more closely.

**Comment by hughdavenport** [comment]
Fair enough, I'll just grab a cheap new phone for now. If it is still an issue then I'll reopen this
