### ISSUE TITLE
when using video call only working rear facing camera ...not working front camera although both camera working in whatsapp and FB messenger..

### ISSUE THREAD

**Issue by negi17** [WhisperSystems/Signal-Android#7008]
when using video call only working rear facing camera ...not working front camera although both camera working in whatsapp and FB messenger......even not showing switch option of front and rear facing camera...please help suggest

I have:
- [ ] searched open and closed issues for duplicates
- [ ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by moxie0** [comment]
There is already an issue open for this (#6279). Please do intentionally open duplicate issues over and over again, it only means I have less time to do the work you're requesting.
