### ISSUE TITLE
Zoom / magnify group pictures

### ISSUE THREAD

**Issue by jondo** [WhisperSystems/Signal-Android#7009]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

Like in WhatsApp, it should be possible to click on a group picture to see a magnified version of it.

**Signal version:** 4.10.12

**Comment by exploide** [comment]
I wouldn't restrict this to group pictures ;)

**Comment by FeuRenard** [comment]
This is a duplicate of #5496.

**Comment by jondo** [comment]
Yes.
