### ISSUE TITLE
Where can I get protobuf file for SignalServiceProtos.java ?

### ISSUE THREAD

**Issue by thegamblerrises** [WhisperSystems/Signal-Android#7015]
### Bug description
I am trying to alter some values in server side code, for that to work effectively, I have to change values in SignalServiceProtos.java class, I can't find any .proto file related to the same.

Please let me know. Thanks

**Comment by moxie0** [comment]
We don't use this issue tracker for Q&A or discussion:
https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#not-a-discussion-forum

Please do not post here without following the issue template and reading the contributing guidelines.
