### ISSUE TITLE
4.10.12: android client only showing one checkmark when messages are sent from desktop and show two there

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#7019]
I have:
- [x ] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Messages from my desktop client to a group are not showing the second check mark, even though the desktop app shows them both.

### Steps to reproduce
- Have a group (mine is myself and two others)
- Message from desktop client

**Actual result:** Two checkmarks in desktop client, only one in android app
**Expected result:** Check marks for sent and received should match on both desktop and android clients

### Screenshots
Desktop Client ( newest non-electron)
![image](https://user-images.githubusercontent.com/4967949/31139943-51fd5972-a830-11e7-8e0d-3e49acc43696.png)

Android 4.10.12:
![screenshot_20171003-114831](https://user-images.githubusercontent.com/4967949/31140183-eadb428a-a830-11e7-897c-bb19a836bf32.jpg)

### Device info

**Device:** Samsung Galaxy S8
**Android version:** 7.0 stock
**Signal version:** 4.10.12

### Link to debug log
Android Client:
https://gist.github.com/db36befa18426f262a2b3394dd5f5d2d

Desktop Client:
https://gist.github.com/bb63e53f03aa199e445789b69e52d562

**Comment by moxie0** [comment]
Thanks, this is fixed in 4.11.0
