### ISSUE TITLE
Wrong color for "Shared Media" in conversation preferences

### ISSUE THREAD

**Issue by mammuth** [WhisperSystems/Signal-Android#7024]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The heading of the shared media section in the conversation preferences is not styled correctly in the dark theme.

### Steps to reproduce
- open conversation preferences in dark theme

**Actual result:** 
"Shared Media" heading is black

**Expected result:** 
Heading should be styled the same as the other sections.

### Screenshots

![screenshot](https://i.imgur.com/gTapN2Q.png)

### Device info

**Device:** Galaxy S5
**Android version:** 7.1, LineageOS 14
**Signal version:** 4.11.0

### Link to debug log

Probably not relevant for this UI-only issue.

**Comment by FeuRenard** [comment]
The color is wrong for light theme, too. The blue is lighter than the other headings. And it doesn't seem to be printed bold like the other headings.

**Comment by RiseT** [comment]
May I add that on the screenshot above, the titles "Chat settings" and "Privacy" have the wrong color as well (should be blue, not cyan).

**Comment by FeuRenard** [comment]
@RiseT I didn't test it again, but I think this would be solved by #5412.

**Comment by RiseT** [comment]
@FeuRenard Uh, right. I tend to forget that PR of yours again and again since it has been unmerged for so long... 😄
