### ISSUE TITLE
Avatar in conversation view should be tappable

### ISSUE THREAD

**Issue by cascheberg** [WhisperSystems/Signal-Android#7025]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I want to tap the conversation header to open the new conversation settings screen which also shows the enlarged avatar. I can tap the contact / group name, but not the avatar itself, which is unexpected.

### Steps to reproduce
- open a conversation
- tap the avatar in the conversation header

**Actual result:** Nothings happens.
**Expected result:** Should open the conversation settings screen.

Also note that in the old conversation screen one could tap the avatar on the left of each message bubble (which has been removed) to see that users full contacts info to e.g. start a normal (non-Signal) phone call. This quick access option is not available anymore anywhere.

### Device info
**Android version:** 5.1.1 & AVD 7.1.1
**Signal version:** 4.11.0

**Comment by p4nci** [comment]
I suggest also increasing the tap area for the back arrow (near avatar). I hard to find the right area.

**Comment by moxie0** [comment]
Hah, these two requests are pretty much at odds with each-other.  The reason the avatar icon isn't tap enabled right now is because it's so close to the back arrow that I thought people would more often accidentally open the conversation settings when they meant to go back.

**Comment by skulumani** [comment]
This might be a good opportunity/motivation to implement swipe gestures to move between threads or back to the main conversation screen? 

Swipe to get back to conversation: #584, #3759

It seems like it'll require a large change, based on #3759 discussion. 

Related to swipe gestures for other interactions: #6625, #4749, #2355, #1651

**Comment by p4nci** [comment]
@moxie0 
> The reason the avatar icon isn't tap enabled right now is because it's so close to the back arrow

Well, personally I expected that the avatar is/was tappable and probably for this reason I was too careful when I tried to hit the back button just to avoid opening the conversation settings.
> Hah, these two requests are pretty much at odds with each-other.

:thinking: a few months ago there was a PR (https://github.com/WhisperSystems/Signal-Android/pull/6585/) about this. You can compare the "Before" and "After" pictures. Imo, the gap between back button and avatar can be increased from 15dp to 25dp `android:layout_marginRight="15dp"`?
OR
a desktop client like: centered avatar at bottom
https://user-images.githubusercontent.com/1229613/29997387-eaba116e-9011-11e7-9059-c7906d3baf0a.png

**Comment by mammuth** [comment]
> I thought people would more often accidentally open the conversation settings when they meant to go back.


Btw, on WhatsApp a click on the avatar is indeed a back action to the conversation list.

**Comment by cascheberg** [comment]
> Well, personally I expected that the avatar is/was tappable and probably for this reason I was too careful when I tried to hit the back button just to avoid opening the conversation settings.

I agree, it's not really helpful for usability to make something not tap enabled while it still looks like it is.

I like the screenshot in PR #6585 that @p4nci mentioned. The avatar is a bit smaller in diameter and the margin is a bit bigger. Below is a screenshot of the current layout.

![conversation](https://user-images.githubusercontent.com/3845150/31190572-c1761238-a93b-11e7-9d04-fda30dc447a1.png)

**Comment by p4nci** [comment]
@mammuth I never used WhatsApp, so I can't check if still is the case, but according to the [screenshots from playstore](https://lh3.googleusercontent.com/foFmwvVGIwWWXJIukN7png18lFjFgbw3K7BqIm8G-jsFgSTVtkCa-dDkFApUzbvzIvbe=h900):

![wp](https://user-images.githubusercontent.com/16047081/31195777-a98624fa-a94b-11e7-9ba4-ee801a5a949d.png)
the avatar is grouped with back arrow and NOT with the contact / group name (check/see left and right avtar margin).
IMO, this is very strange UI decision, but at least the avatar is tappable.
