### ISSUE TITLE
Show first-letter-avatar in recipient preferences

### ISSUE THREAD

**Issue by FeuRenard** [WhisperSystems/Signal-Android#7028]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The avatar for contacts in my address book without any picture changes from first-letter-avatar to some default avatar when I switch from/to recipient preferences.
Maybe this is related to #7022.

### Steps to reproduce
- select a conversation with a user that has no profile picture and is in my contacts with a name
- tap the conversation header

**Actual result:** In RecipientPreferenceActivity the first-letter-avatar is replaced by "some person" avatar.
**Expected result:** RecipientPreferenceActivity shows the first-letter-avatar.

### Screenshots
![screenshot_20171003-212405](https://user-images.githubusercontent.com/16167751/31144685-c02211da-a881-11e7-98f1-41bc6cb73393.png)

### Device info

**Device:** Fairphone 2
**Android version:** 6.0.1
**Signal version:** 4.11.0

**Comment by moxie0** [comment]
Hmm, this is intentional. A big "F" right there would look pretty weird, right?

**Comment by FeuRenard** [comment]
It just feels inconsistent switching between conversation and recipient preferences.

**Comment by moxie0** [comment]
How do you think it should work instead?

**Comment by FeuRenard** [comment]
It got better with 4.11.1 I think. Now the slightly more modern default person is used:
![screenshot_20171004-103604](https://user-images.githubusercontent.com/16167751/31167281-da824bce-a8f1-11e7-8897-d1a586371650.png)

I looked in the Android 6 contacts app. There a list of contacts is shown with first-letter-avatars. Clicking on an entry shows this:
![screenshot_20171004-103705](https://user-images.githubusercontent.com/16167751/31167340-0b08f572-a8f2-11e7-818a-696c9aa67fc2.png)
Maybe we could mimic this look: contact color as background and white icon on top.

Final remark: Note the gap between contact picture and conversation settings (in screenshot "Unterhaltungseinstellungen"). The conversation has no shared media. So this segment is missing and conversation settings segment is first. It should spare the top margin in this case.

**Comment by rainerzufall** [comment]
please also note, that there now 3 different visualisations for a group avatar:

white on grey in conversations overview:
![screenshot_20171004-112908](https://user-images.githubusercontent.com/12666598/31169843-4c8455e8-a8fa-11e7-9734-01b936632e62.png)


grey on white in group conversation:
![screenshot_20171004-112912](https://user-images.githubusercontent.com/12666598/31169763-06430b10-a8fa-11e7-9c6f-47246ea7a73d.png)


grey on grey in group conversation settings:
![screenshot_20171004-112918](https://user-images.githubusercontent.com/12666598/31169785-197ccf72-a8fa-11e7-8ee5-51a0f89e7465.png)
