### ISSUE TITLE
Make "Shared media" string translatable

### ISSUE THREAD

**Issue by FeuRenard** [WhisperSystems/Signal-Android#7030]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
https://github.com/WhisperSystems/Signal-Android/blob/master/res/layout/recipient_preference_activity.xml#L78
`"Shared media"` is hard coded.

**Comment by moxie0** [comment]
b3147aad55ec4b5f91442b6cdb3ef7535af2ed4b
