### ISSUE TITLE
"Read Receipts" feature not clear

### ISSUE THREAD

**Issue by vvug** [WhisperSystems/Signal-Android#7033]
This is an usability issue: the read receipts feature is not clear. What should I expect? A triple tick mark then the recipient read the message? A change in color in the tick marks? Or will the second tick mark appear only if the message has been read (so if I disable read receipts, I won't know if a message has been delivered)?

How can I tell if a contact disabled the read receipts, or if s/he actually didn't read my messages?

**Comment by moxie0** [comment]
Please don't delete the issue template. If this is a question, please see the online forums. If these are rhetorical questions, thanks for the feedback but I'm going to close this since we don't need an issue to track it.

**Comment by landry314** [comment]
> How can I tell if a contact disabled the read receipts, or if s/he actually didn't read my messages?

This is a really good point. If the recipient had read receipts on then turned them off then the sender would think they havent read something when they have. I guess this is a feature though, that the user can hide their presence from people?

It is the same way in Whatsapp and has always feel awkward. Did he receive my message or is he one of those people who disabled read receipts?

Maybe there could be a way to see if the user has read receipts on, an icon or something in their profile...
