### ISSUE TITLE
4.11 introduced different scroll behaviours in conversation settings 

### ISSUE THREAD

**Issue by rainerzufall** [WhisperSystems/Signal-Android#7042]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
with the new conversation settings layout different scroll behaviours are introduced, depending from where in the display you start the scrolling as well as a difference between group and 1on1 conversation settings now exists. details in the steps to reproduce below:

### steps to reproduce:
**1on1 conversation:**
- go into a 1on1 conversation with shared media
-  try to scroll within the "shared media" image rail. Only a part of the screen is scrolled. the profile picture does not fade out and the "shared media" image rail gets hidden behind the profile picture.
- when starting to scroll from within "chat settings" the whole screen is scrolled and the profile picture fades away as expected.

---> expected behaviour: that scrolling behaves consistent. when starting to scroll within the "shared media" image rail the whole screen should be scrolled and the profile picture should fade away.

**group conversation:**
- go into a group conversation with shared media
- try to scroll within the "shared media" image rail - it does not work / scroll.
- try to scroll from the "chat settings" field scrolling works.

---> expected behaviour: scrolling is also possible when starting to scroll within the "shared media" image rail

### Device info
**Device:** Fairphone 2
**Android version:** 6.0.1
**Signal version:** 4.11.1

**Comment by moxie0** [comment]
Looks like an Android coordinatedlayout bug.
