### ISSUE TITLE
Tap on image preview causes crash

### ISSUE THREAD

**Issue by strobelm** [WhisperSystems/Signal-Android#7050]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After inserting a picture into a conversation, and not sending it, a tap on the image preview crashes signal.

### Steps to reproduce
- open a conversation
- insert a image
- tap on the picture

**Actual result:** Signal crashes
**Expected result:** the image should be shown 

### Screenshots
![screen1](https://user-images.githubusercontent.com/14185442/31239422-50e7eaa6-a9fd-11e7-80f9-505726cd316c.jpg)
![screen2](https://user-images.githubusercontent.com/14185442/31239421-50cf74e4-a9fd-11e7-80a6-bf71f08f9f43.jpg)

### Device info
**Device:** Google Nexus 6p
**Android version:** 7.1.2 (LineageOS 14.1)
**Signal version:** 4.11.2

### Link to debug log
https://gist.github.com/strobelm/87f51aa16158a7f53d6f22160b09315a

**Comment by TimesEnemy** [comment]
I am able to reproduce this.

To reproduce:
- Click paperclip icon to add attachment
- Select an image (I just picked an image already visible in this menu.)
- "Signal has stopped" error appeared.  Options were Open app again, or Send feedback.  The feedback goes to Google.

Debug Log: 
https://gist.github.com/anonymous/f7a8a9def4a43fed75fa4811cdfb5cb0

Device: Google Pixel XL
Android Version: 8.0.0
Signal Version: 4.11.2

**Comment by merkste** [comment]
I have experienced a similar issue. I sent a video from Signal Desktop to some contact. But on my mobile phone I neither can see the preview image nor can I play the video. However, Signal does not crash. Could this be related or should I open a separate issue?
Signal Version: 4.10.12
Crash Log: https://gist.github.com/anonymous/6901a6838a3a2579d42d0d2638d4bb76

**Comment by FeuRenard** [comment]
It's unrelated to this issue. You should open a separate issue, as long it is not already reported. Please use the search function to determine this first.
