### ISSUE TITLE
4.11.2: unread indicator aligns below text input box

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#7054]
I have:
- [ x] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Unread indicator is below text input for messages

### Steps to reproduce
- someone sends you a message
- open signal
- tap thread with new message

**Actual result:** can't see the new messages. Pull up and the unread indicator and all new messages are revealed.
**Expected result:** the unread indicator is aligned so that it is both visible and is scrolled no farther upward than the top and no farther downward than to reveal itself and all new messages. 

### Screenshots
Will add next time

### Device info
**Device:** Samsung galaxy s8
**Android version:** 7.0
**Signal version:** 4.11.2

### Link to debug log
Will capture next time.

**Comment by jeremymasters** [comment]
Can't nail down exact repeatability though

**Comment by jeremymasters** [comment]
https://gist.github.com/ee5921e756f8aa4e67fb2993a3ba3075

**Comment by moxie0** [comment]
Can't reproduce. Please include steps to reproduce.

**Comment by jeremymasters** [comment]
Almost every single conversation I had yesterday had this going on.  Not sure if it's when I read the message, then use the home key to leave the app. I almost never get the expected behavior, I have to pull up on the conversation to even see the unread indicator.

**Comment by merge** [comment]
jup. same here. The unread marker is basically reversed. Instead of being at the top (or not yet, if too few messages are unread), it is below the bottom.

**Comment by moxie0** [comment]
Could someone include specific steps to reproduce?

**Comment by jeremymasters** [comment]
1. have ongoing conversation with someone
2. tap home button to make signal go away
3. friend sends signal message
4. turn phone screen on
5. pull down notification shade
6. tap signal message notif
7. conversation is opened, but new messages are not shown...need to scroll to see the unread indicator as well as new messages

**Comment by moxie0** [comment]
@jeremymasters Hmm, doesn't seem to reproduce for me. If it's easily reproducible for you, could you try doing a git bisect to determine which commit introduced this behavior?

**Comment by jeremymasters** [comment]
I would, but I can't do code-y things right now.  I went from 4.10.12 (not happening) directly to 4.11.2 (happening) which, I guess is not as helpful as bisect and build.

**Comment by moxie0** [comment]
@jeremymasters Ok thanks.

Can anyone else who can reproduce this do git bisect?
