### ISSUE TITLE
When tapping on Notification sound in Conversation Settings Signal crash

### ISSUE THREAD

**Issue by lcouturier** [WhisperSystems/Signal-Android#7055]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I am in a conversation, I go to the Conversation Settings and then I tap on Notification Sound Signal crash.

### Device info

**Device:** Motorola G 3
**Android version:** 6.0.1
**Signal version:** 4.11.2

**Comment by moxie0** [comment]
Can you include a debug log taken after a crash?

**Comment by lcouturier** [comment]
https://gist.github.com/acd044799c38cae0f20811dee219c11e

**Comment by Dyras** [comment]
@moxie0 This happens for me as well on both my G3 and my G4. 

https://gist.github.com/anonymous/32867492142900c94f40c3283e71f210
https://gist.github.com/anonymous/53f429558198ca982fea9413937c92b7
