### ISSUE TITLE
Signal crashes when clicking on profile without picture in conversation

### ISSUE THREAD

**Issue by elya5** [WhisperSystems/Signal-Android#7056]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Clicking on the profile picture in the top bar of a conversation causes a crash if there isn't a profile picture available.

### Steps to reproduce
- Go to conversation with a person without a profile picture
- Click on picture in the top bar

**Actual result:** Profile (without the picture) should be shown
**Expected result:** Signal crashes immediately

### Device info

**Android version:** 4.2.2
**Signal version:** 4.11.2

**Comment by rainerzufall** [comment]
Please post a debug log to your report, without it the developers won't be able to solve your issue. Here is how you do that: https://support.signal.org/hc/en-us/articles/212535838-How-do-I-send-a-debug-log-from-Signal-Android-

**Comment by elya5** [comment]
This is the link to the debug log: https://gist.github.com/anonymous/312af092046c3b28e16fb8044c69df1d

**Comment by moxie0** [comment]
Looks like a Jellybean compat problem
