### ISSUE TITLE
Overall Privacy-Compromise Created by Profile Feature

### ISSUE THREAD

**Issue by turningdragon** [WhisperSystems/Signal-Android#7064]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

Not really sure how to report this. I deem that it belongs here since it is not a support request, and is an issue with Signal. But it it is considerably more general than other bug reports.

I have read all of the issue tickets reporting issues with the new profile feature, and all of them identify issues with the way the feature was implemented. None of them speak to the addition of this feature itself as problematic.

I use Signal because it is still the project with the most diligent commitment to smartphone messaging privacy. I have until now had high confidence that Signal development decisions would be smart and levelheaded, and would not compromise my privacy. The addition of the profile feature has shaken that confidence.

The [announcement of the Profile feature in Beta](https://signal.org/blog/signal-profiles-beta/), which I've only now had a chance to read, claims "All of this is possible without sacrificing the privacy and security that you have come to expect from Signal." This is not true.

Half of my contacts know me by one name, half by another. It is imperative that there is no crossover between these identities. Furthermore, the gmail account my Android phone is registered under is a third identity. Disclosing that identity to some Signal contacts would represent a catastrophic privacy breach, which could even, hypothetically, endanger my life.

Up until now, there has been no cause for concern in using Signal, as enforcing the segregation of these identities has presented no issues. Signal's design decisions have never presented any threat to this segregation, because the presumption has always been in favour of privacy.

The "set up your profile" wizard which announced itself after the update prepopulated the name field with the name associated with my Google account. It would have been very easy to have accidentally accepted this as my profile name. As per the Signal blogpost, this name would then have been visible to all contacts saved in my phone. This decision thoughtlessly left me a single mistake away from a catastrophic privacy breach.

The "Do It Later" option was minuscule and dangerously close in the UI to the very large "Accept" button. It was initially not visible to me, so it looked as if I was being forced to choose a unitary identity for a Signal instance where I was managing multiple identities. When I did spot it, after a reinstall, several attempts to press it on my large smartphone screen were unsuccessful. It took multiple attempts. 

Before I discovered the "Do it later" option, my compromise attempt to save an empty profile returned an error message. I also discovered, after temporarily choosing a privacy-preserving pseudonymous profile name (which would nevertheless appear highly incongruous to several of my contacts) that [it is not possible to delete an identity once chosen](https://github.com/WhisperSystems/Signal-Android/issues/6960). There is no option to do so, and if you try to save an empty profile it gives you an error. So I had to reinstall the app to delete my profile. And when you do not set up a profile,[ the app harrasses you with persistent notifications](https://github.com/WhisperSystems/Signal-Android/issues/6927) to do so during group conversations, as if the decision not to is assumed to be a temporary one by the Signal devs.

There are several bug reports which suggests mitigations for some of these different problems (although not all of them - e.g. I have seen no mention of the prepopulation of the name field as a concern). Fixing each of these problems would indeed have reduced the severity of the threat to privacy represented by the introduction of the feature. (I also imagine there are people who believe that simply adding support for multiple profiles would solve the issue, but in my opinion this would drastically sophisticate the task of managing identities, and result in accidental breaches.)

But fixing each of those issues would not address what seems to me the major issue: that this issue was so thoughtlessly introduced at all. Yes, it is clear that - to preserve my privacy - Signal devs decided it would be unwise to just automatically create a profile for me based on the name associated with my Gmail account. Instead I was given a dialogue with the name prepopulated. But this in itself was dangerous, and the fact that I was subjected to even this danger with apparently no consideration of how it could affect people with multiple identities leaves me with little confidence that similar or worse breaches might be thoughtlessly created in the future, in order to introduce some convenience feature which is secondary to the goal of a truly private messaging application. Using Signal is now fraught with inherent risk, and I am no longer confident that Signal devs have my privacy as their priority.

For me - a Signal user whose privacy is paramount - this profile feature is not a feature but a bug. The utility added to the app by the profile feature, eliminating unknown phone numbers in group conversations, seems to address an edge case at best. It does not enhance the privacy of the user - its only effect on user privacy is to make privacy compromise more likely. I cannot see how its addition necessitates the attendant complexification of the task of staying private while using the app. And the reasoning behind its introduction, in a dev team with a commitment to privacy, is entirely opaque to me. 

I submit this issue as a Signal user who values privacy, and who has experienced a privacy scare because of Signal development decisions - something which I am sure should be of concern to a privacy-oriented project. It is considerably longer than a typical bug report, because it speaks to a broader issue. If this issue can be taken on and used to improve matters, that is to the good. 

If it is simply the case that Signal is reprioritising, or that it does not intend to cater to users like me with harder privacy requirements than the average (but privacy-conscious) user, that is sad to me, but I accept it. But it also suggests to me that it is misleading to call it Signal Private Messenger, and to entice users with more stringent needs into a potentially risky situation.

**Comment by Lesik** [comment]
While your specific use case (several identities tied to one phone number) might not be too common, it is definitely a valid request to be able to use Signal without setting a name or profile picture. I'm fine with these features being added – after all, some people see Signal as a WhatsApp clone and thus expect similar features – but it **needs** to stay optional (and by optional I mean no banners constantly reminding you to add your name). I don't see how disclosing your name (or any identifying string of text) is compatible with a "privacy"-oriented messenger like Signal.

**Comment by moxie0** [comment]
Please do not file issues without following the issue template. If you'd like to share your thoughts or invite discussion, please use the online forums for that.
