### ISSUE TITLE
Conversation back arrow closes keyboard instead of going back

### ISSUE THREAD

**Issue by mammuth** [WhisperSystems/Signal-Android#7065]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Pressing the back button in the action bar while the keyboard is open, just closes the keyboard but you need a second press on the back button to get back to the conversation list. 

I've got the feeling that this behaviour was introduced recently.

### Steps to reproduce
- Open conversation
- Click on text area to bring the keyboard up, write a lovely message, let the keyboard open
- Hit the back arrow in the action bar

**Actual result:** 
Keyboard closes, but we stay in the conversation

**Expected result:**
Keyboard closes and we get back to the conversation list.

### Device info

**Device:** Galaxy S5
**Android version:** 7.1 LineageOS
**Signal version:** 4.11.2

### Link to debug log

https://gist.github.com/53bfaaa5f6510107228dedc6dea286ba

**Comment by FeuRenard** [comment]
This was probably introduced here:
https://github.com/WhisperSystems/Signal-Android/commit/65124fd1f2d459a6e40517bf3f572f68b554a783#diff-8b6badc7254f2d75634d87a85bc9cd31R1213

**Comment by Dyras** [comment]
It has been this way for as long as I can remember and there is *no way* this was introduced just a month ago.

Also please don't change it, I really like it the way it is now 🐱

**Comment by mammuth** [comment]
@Dyras well I think the current behaviour is just not how it should be. 
The back arrow in the action bar is for navigating to the parent view, not dismissing anything in the current view.
