### ISSUE TITLE
Safety number still marked verified after contact reregisters

### ISSUE THREAD

**Issue by pgerber** [WhisperSystems/Signal-Android#7072]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
If a contact's safety number is marked as verified and that contact reregisters, the new safety number is marked as verified.

### Steps to reproduce
- mark contact's safety number as verified
- contact reregisters with Signal (via Settings →Advanced →Signal messages and calls)
- new safety number is marked as verified

**Actual result:** New safety number is marked verified without asking the user.
**Expected result:** User is asked to verify new safety number.

### Device info

**Device:** Blackphone 2
**Android version:** 6.0.1
**Signal version:** 4.11.2

### Link to debug log
[log](https://gist.github.com/anonymous/de34d026d41031898e282cf68a62dac0)

**Comment by FeuRenard** [comment]
https://support.signal.org/hc/en-us/articles/115000267971-What-is-a-safety-number-and-why-do-I-see-that-it-changed-

Safety numbers don't change when someone just deregisters and registers again. However, it changes with a new installation.
