### ISSUE TITLE
Use inset dividers in conversations screen

### ISSUE THREAD

**Issue by lokesh-krishna** [WhisperSystems/Signal-Android#7074]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature Request  
Add inset dividers to the conversations view in order to improve/enhance the user experience.

### Detailed Description
The conversations view presently uses no dividers at all.  
Full-bleed dividers are pretty visually overwhelming in large numbers. Inset dividers are subtle and offer better distinction than what is offered presently. It is also something that is recommended in the [Material Design Guidelines](https://material.io/guidelines/components/dividers.html#).

While there are representations of how this would look in the guidelines, here is how this looks in WhatsApp.

![screenshot_20171009-091937](https://user-images.githubusercontent.com/20235646/31324866-9743d086-aca6-11e7-8d26-135a88f97df6.png)
  
Thank you for reading :)

**Comment by p4nci** [comment]
@lokesh-krishna I have already suggested exactly this:
https://github.com/WhisperSystems/Signal-Android/pull/4710#issuecomment-161116701

**Comment by lokesh-krishna** [comment]
You indeed did. But it doesn't seem to have gotten any response there. Let's see what people have to say about it here. Also, I'm suggesting the use of inset dividers while you'd suggested full-bleed dividers. Inset dividers are more in line with Material Design guidelines.

**Comment by p4nci** [comment]
@moxie0 thanks for implementing this, but in devices with high density the divider is almost invisible
