### ISSUE TITLE
Listening to audio recordings on Galaxy S7 only possible with the hands-free speaker

### ISSUE THREAD

**Issue by drws** [WhisperSystems/Signal-Android#7075]
### Bug description
Whenever a voice message is played on a Samsung Galaxy S7 (G930F), it is only possible to hear it with the "strong" speaker that is used for hands-free calling. If the phone is put to the ear to hear it on the regular voice speaker, the phone simply mutes the big one and nothing is heard from the regular one.

### Steps to reproduce
- get or record a voice message
- press the button to play the voice message
- put your phone to the ear

Actual result: silence
Expected result: non-silence

### Device info
**Device:** Samsung Galaxy S7 G930F
**Android version:** 7.0
**Signal version:** 4.10.12

### Link to debug log
I saw this on a friend's phone, sorry about the log. If it is truly necessary here, I'll get one.

Also, can somebody confirm?

**Comment by Lesik** [comment]
This bug is mentioned in #6455, with some people confirming it (+1s and comments).

**Comment by drws** [comment]
Then this is redundant.
