### ISSUE TITLE
Outgoing text messages unsuccessful, only incoming messages-- outgoing works with stock text application only.

### ISSUE THREAD

**Issue by RublezNPence** [WhisperSystems/Signal-Android#7087]
I have:
- [ x] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

Only able to receive messages in Signal using a Samsung Note 3 on the Freedom Network (formerly Wind) in Toronto, Ontario Canada. Outgoing message attempts are all unsuccessful with resend all also unsuccessful. Switching to the stock messaging app results in successful outgoing messages. Connectivity with Wifi vs network does not vary the outcome, even with other signal users.

### Steps to reproduce
- trying to send message in Signal
- Unsuccessful
- Resend unsuccessful 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Only incoming messages work, all attempts for outgoing unsuccessful unless switching to stock Note 3 messaging app as default where outgoing messaging is functional.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Outgoing messaging should function regardless of application preference, since network connectivity isn't the issue

### Screenshots

![image](https://user-images.githubusercontent.com/32741113/31501959-ae7281d6-af39-11e7-9ba2-f11b6fe4c702.png)
![image](https://user-images.githubusercontent.com/32741113/31501980-bfc089f6-af39-11e7-8e0a-3f6e1ff6441d.png)

### Device info

**Device:** Samsung Note 3 SM-N900W8
**Android version:** 5.0 Kernel version 3.4.0-4348112
**Signal version:** 4.8.1

### Link to debug log

https://gist.github.com/caff7d867d942ba1312704e64825f7a2

**Comment by moxie0** [comment]
You're running a version that's 27 releases old. There should be a big banner at the top of the conversation list activity that says "This version of Signal has expired, tap to update." Once you update you'll be able to send messages again.
