### ISSUE TITLE
Voice calls do not ring

### ISSUE THREAD

**Issue by jdrissel** [WhisperSystems/Signal-Android#7090]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Place a voice call from another device. Rings for a long time, but no notification appears until after the ringing stops. Then you get a missed call notification. This may be the same root cause as a similar bug on the iOS side: https://github.com/WhisperSystems/Signal-iOS/issues/1628

### Steps to reproduce the issue
- send a voice call from another device.

**Actual result:** Nothing happens until the ringing stops. Then you get a missed call notification.
**Expected result:** notification of in-comming call and ringing.

### Screenshots

**Device:** Manufacturer Model XVI Samsung SN-M950U
**Android version:** 7.1.1
**Signal version:** 4.11.3

### Link to debug log

I suspect this may be at least partially a server side problem because the same thing happens on Android.

Here are the debug logs, call placed from iphone7 to a note 8.  The iPhone got a pastekit error10001 when I tried to get a log. Here is the Android log: https://gist.github.com/c7136cb8d99a20cd7aa3964923a2cc85

Here are the logs for a call from the Note 8 to the iPhone 6.  Again the iPhone failed to submit a log.
https://gist.github.com/668577b3e0ff5a0be87c8a9af8b81436

**Comment by moxie0** [comment]
The Android device never seems to find any ice candidates. Is it on a network that blocks voip?

**Comment by jdrissel** [comment]
I do not think so. It happens both of my wifi (spectrum cable for internet
access) and on Sprint and on my internet at work (provided by Aethernet),
which is supposed to be unfiltered.

**Comment by jdrissel** [comment]
I found the problem. Your hint about blocking lead me to try disabling my
ad blocker, blockade origin.  I will submit a bug with the developer.
Strange though, this did not start when in installed blockade, so it must
be a recent update.

**Comment by jdrissel** [comment]
Issue was caused by ad blocking software, blockade origin.  Not a signal problem.
