### ISSUE TITLE
New MMS group chat thread created with exact same users as another

### ISSUE THREAD

**Issue by tgp1994** [WhisperSystems/Signal-Android#7091]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I've had an MMS group chat thread going with me and two other people for several months now. Just this morning, one of the contacts send a message to this group. Signal created a new thread for this group chat, even though the recipients specified are the same. I have noticed that they're in a slightly different order, however. For example; the older thread is Person 1, Person 2, and Person 3. The new thread shows that the recipients are Person 1, Person 3, and Person 2. Perhaps Signal thinks this justifies creating a new thread? IMO this should still go in the old thread.

### Steps to reproduce
- Create a group MMS, send
- Create another group MMS to the same people, but with them in a slightly different order

**Actual result:** Two threads are created for the same people.
**Expected result:** The old thread is continued.

### Screenshots
![screenshot_20171012-162207](https://user-images.githubusercontent.com/842942/31523841-cff14924-af6a-11e7-8c95-b5f8cbb66d0d.png)

### Device info

**Device:** HTC One M8, S. Team ROM
**Android version:** 6.0.1
**Signal version:** 4.10.12

### Link to debug log
N/A, thread was created too long ago.

**Comment by jeremymasters** [comment]
Isn't that the same behavior as other messaging clients?

**Comment by tgp1994** [comment]
Oh, is it? I don't think I've ever noticed it before. Then again, maybe I've never had a contact send me a continued group MMS with the contacts out of order before... Signal could be the first app to fix this! :)

**Comment by wesdawg** [comment]
I experienced a similar issue after starting a new mms thread with 2 contacts. The first response started a new separate thread with the difference being my own number was added as a member. I expect Signal to filter my number and show all replies in the same starting thread.

@jeremymasters that is not the default behaviour for the SMS messaging apps I have used
