### ISSUE TITLE
Change action bar color in MediaOverviewActivity

### ISSUE THREAD

**Issue by FeuRenard** [WhisperSystems/Signal-Android#7098]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The color of action bar and tabs in MediaOverviewActivity is white. There is no other action bar in Signal which is white afaik. It should either

- be black as before or as in MediaPreviewActivity
- be blue/black according to theme
- have the contact color like conversations or recipient preferences

### Steps to reproduce
- open Signal
- choose a conversation
- open context menu
- go to "All media"

**Actual result:** Action bar and tabs are white.
**Expected result:** Action bar and tabs have a color I know from somewhere else in the app. E.g. black, blue or the contact color.

### Device info
**Device:** Fairphone 2
**Android version:** 6.0.1
**Signal version:** 4.11.3

**Comment by moxie0** [comment]
Thanks but this was intentional
