### ISSUE TITLE
Add option to block/disable user avatars

### ISSUE THREAD

**Issue by IGBC** [WhisperSystems/Signal-Android#7105]
I mainly use signal for anonymous faceless communication with people I don't know or want to know. 

I don't want to see the picture the chose for themselves when I add them to my contacts. A bubble with a letter and color will do just fine. 

Please add an option to fully disable contact avatars from the app and stop downloading them from the servers.

Thanks.

**Comment by williamSaintB** [comment]
Yes addd

**Comment by moxie0** [comment]
Thanks but we're not going to do that
