### ISSUE TITLE
Read receipt in desktop app

### ISSUE THREAD

**Issue by Metal-Frog** [WhisperSystems/Signal-Android#7109]
Please add read receipt functionality to the desktop app.

**Comment by piratenpanda** [comment]
You should post this in the proper bug tracker: https://github.com/WhisperSystems/Signal-Desktop and also don't delete the template please.

I guess though, that the electron version of the desktop client already supports this.

**Comment by Metal-Frog** [comment]
Sorry, for posting at wrong place
