### ISSUE TITLE
Not working in dual sim phone - cannot send SMS on second SIM card

### ISSUE THREAD

**Issue by fastalan** [WhisperSystems/Signal-Android#7119]
Please read comments on Issue #555. In short, Signal does not allow me to send SMS text messages on my second SIM card. In my case, the first SIM card is disabled. All original issues of this nature seem to be closed with no resolution. Please advise.

**Comment by equaeghe** [comment]
Did you try long press on the send button to bring up the sim selection menu?

**Comment by fastalan** [comment]
Thanks that worked.
