### ISSUE TITLE
Recurring Blank "Select SIM card" Popup When No SIM Is In Phone

### ISSUE THREAD

**Issue by ded5r** [WhisperSystems/Signal-Android#7120]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Using a phone without a SIM card. Using Signal only through WiFi. Signal seems to be recognizing there is no SIM card, as if it has lost contact with the SIM or it is a dual-SIM phone (it is not). So every time a contact's message page is opened, an empty popup asks to "Select SIM card" and there is none to select. This doesn't make Signal very user-friendly since you have to hit outside the popup before reading or sending a message. And this happens over and over again every time you click on a contact's name to send a message or see what was sent.

### Steps to reproduce
- Take out phone's SIM card.
- While SIM card is out of phone, try to send a message to a contact.

**Actual result:** "Select SIM card" popup will be there every time.

**Expected result:** "Select SIM card" popup will not be there every time. That Signal doesn't need a SIM card to be present, since non-SIM phone numbers can also be used to register with Signal.

### Screenshots

![signal_screenshot](https://user-images.githubusercontent.com/27523404/31873280-acdbdc48-b7b1-11e7-83a8-b164c7e492cb.jpg)

### Device info

**Device:** Nexus 5
**Android version:** 7.1.2
**Signal version:** 4.10.12

**Comment by johanw666** [comment]
Did you select Signal as standard sms app? I can not reproduce this, with Signal default sms app or not.

**Comment by sigenc** [comment]
me neither

**Comment by ded5r** [comment]
@johanw666 Yes, Signal is the default SMS app. And in fact when clicking on a non-Signal contact the problem is worse because the popup does not go away. Hitting outside the white box of the popup just makes it reappear and cannot get rid of it, unlike a Signal contact where is does go away.

But since you mentioned it, just made Signal **not** the default SMS app and then the problem went away. No popups. Another curious thing, in order to change it, went into the Signal settings were it says  'Touch to change your default SMS app'. When that is clicked though, it goes to the 'Wireless & networks' settings of the phone, instead of the 'Configure apps' setting where it can be changed. So it seems some connection in the settings has been severed? Nonetheless, had to go to the setting directly to change it and not from hitting the button within Signal to get there.

And for additional information, if it matters at all, the phone has LineageOS 14.1 on it.

Also, if a SIM is placed in the phone, Signal **can** work as the default messaging app. It is only when the phone recognizes there is no SIM card--when it shows the grey icon of a SIM card with a slash through it in the status bar--that the popup appears in Signal, when it is the default SMS app.

As a temporary solution for now, since there is no SIM, will of course be not using Signal as the default SMS app, but would definitely rather Signal be the default app if this issue can be solved.

**Comment by ded5r** [comment]
Do to unrelated issues, Signal had to be reinstalled on the phone. It now works without issue. The above "Select SIM card" popup no longer occurs in any instance. Don't know why or what fixed the issue.
