### ISSUE TITLE
Your version of Signal has expired!

### ISSUE THREAD

**Issue by Aravinthu** [WhisperSystems/Signal-Android#7121]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I have downloaded the Source from GitHub and did built, after installed the Signal, i'm getting this message, Please refer the Screenshot, i'm getting Expired message after installed.

### Steps to reproduce
- https://github.com/WhisperSystems/Signal-Android/wiki/How-to-build-Signal-from-the-sources
- i have followed the steps
- did built using Android Studio without any error

**Actual result:** Please refer the Screenshot.
**Expected result:** It should be working like when we download from Play Store.

### Screenshots
![whatsapp image 2017-10-23 at 9 25 25 pm](https://user-images.githubusercontent.com/7602795/31891357-bbf9fa70-b838-11e7-8c9c-450d184026dc.jpeg)

### Device info
**Device:** samsung SM-A720F
**Android version:** 7.0
**Signal version:** 4.11.5

### Link to debug log
https://gist.github.com/anonymous/fa4821b5e70dcb2af5dee185419dfb7a#file-cat-log

**Comment by moxie0** [comment]
Sorry but we can't really support non-production releases here, you might try the forums. Thanks!

**Comment by Aravinthu** [comment]
Thanks for your quick reply.

**Comment by Shubham-Mollatech** [comment]
@aravinthu  Did you found the solution for above???
