### ISSUE TITLE
Voice calls blocked in Egypt

### ISSUE THREAD

**Issue by alispeedmail** [WhisperSystems/Signal-Android#7126]
i can now confirm that signal's calls protocol is now censored blocked in egypt all over all networks and isps , and the text chat still works perfectly.
telegram , whatsapp calls blocked also 
facebook messenger the only app still works both voice calls and text

**Comment by alispeedmail** [comment]
https://www.reddit.com/r/Egypt/comments/6jf27j/voice_call_apps_that_work_in_egypt/

**Comment by moxie0** [comment]
Thanks, unfortunately there's not really a way for us to do censorship circumvention with voice calls.
