### ISSUE TITLE
Message "failed to send" to previously added contact after phone OS re-installed

### ISSUE THREAD

**Issue by ticktockhouse** [WhisperSystems/Signal-Android#7128]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Message "failed to send" to previously added contact after phone OS re-installed

### Steps to reproduce
- Add contact and successfully send messages
- Re-install phone OS
- Install Signal
- Re-add user

**Actual result:** Can receive messages from contact, get "Failed to send" when attempting to re-send messages. Attempted "Reset secure session" and  "View safety number" for contact, all fail
**Expected result:** Should be able to send message to previous contact after the above steps.

### Device info
**Device:** Oneplus One
**Android version:** Android 7.1.2 (Lineage OS 14.1-20171016-NIGHTLY-bacon)
**Signal version:** 4.11.5

### Link to debug log
https://gist.github.com/b011de4bdf730cc2db5e8910e3c5df41

**Comment by moxie0** [comment]
Looks like a rate limit. Please reopen with a new log if still a problem.
