### ISSUE TITLE
Don't spam every single one of my contacts on Signal with a notification when I install the app

### ISSUE THREAD

**Issue by casey** [WhisperSystems/Signal-Android#7130]
How do you possibly think that this is acceptable behavior? I had no chance to stop it or opt out.

I don't want to use Signal for everything.
I don't want some of my contacts to know I am using Signal.

Even though they are unencrypted, I prefer email, SMS, and POTS calls over your proprietary walled garden.

Stop. Please.

You can't stoop to this level, even if everyone else is doing so.

**Comment by casey** [comment]
Oh hey, check it out, someone else things this is shitty behavior:

https://www.jwz.org/blog/2017/03/signal-leaks-your-phone-number-to-everyone-in-your-contacts/

**Comment by FaizKhan5** [comment]
You can turn off this notification from settings

**Comment by casey** [comment]
Unfortunately this doesn't help the issue. I don't care about the notifications that *I* get, I care about the notifications that *my contacts* get.

**Comment by moxie0** [comment]
@casey, I understand that you're frustrated, but it's not helpful to show up here, having never contributed anything before, ignoring all the contribution guidelines, with the attitude that we must be idiots.

This has been discussed at length. I and many people here have thought about it at length, and I'm sure that if you want to discuss it without the attitude or name calling, you might find that it's a much more complex issue than you initially assume. It is nearly impossible to deliver the experience you're asking for.  However, we don't use this issue tracker for discussion.  Please check out the online forums for that.
