### ISSUE TITLE
Read Receipts Blue Color Ugly in Dark Theme

### ISSUE THREAD

**Issue by landry314** [WhisperSystems/Signal-Android#7131]
The blue read receipts checkmarks clash with the dark theme. You have gray, gray, gray then blue. Gray and blue just don't match.

I suggest red instead, everyone knows red and gray/dark/black match. If you chose blue to match the color of signal, I understand, but then... it just doesn't work, it stands out with all the gray and feels weird.

Can the color change with the theme?

Does anyone agree with me?

To reduce comments, use the thumbs up to agree!

**Comment by sigenc** [comment]
Yes 100%

**Comment by p4nci** [comment]
duplicate of https://github.com/WhisperSystems/Signal-Android/issues/7112

BTW @sigenc and @kourbou please use reaction emojis to express support

**Comment by landry314** [comment]
Sorry for the duplicate. I searched for "Read Receipts" so the issue with "Read Receipt" in the title didn't come up. They are called read receipts! :-p'
