### ISSUE TITLE
Service down. Can't send messages. 

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#7136]
https://gist.github.com/252c9d4153311664399774b37ddb8a54

**Comment by schmeat** [comment]
Yup. Looks like an outage to me. I have several contacts that can't send either.

**Comment by apraetor** [comment]
Ok good, not just me.

**Comment by aionic** [comment]
Same issue here Android Oreo, and win 10 (chrome dev branch)

**Comment by whikloj** [comment]
Same, here is my log.
https://gist.github.com/anonymous/da5a8e8c97b0a5a9131081bd2196f66e

**Comment by bowensong** [comment]
I have the same problem here, Signal 4.11.5 on Android and on desktop. Cannot send messages and not receiving any new messages. Started at around 18:18 GMT.

**Comment by agiz10** [comment]
Same here. Any info please?

**Comment by SultanJilani621616** [comment]
ditto, been messaging around and no dice.
occasionally a message will get through after ~half an hour ish but still says it didn't send.

**Comment by interprop** [comment]
Same here, lost connectivity

**Comment by bowensong** [comment]
The service has recovered for me.

**Comment by JustPassingByHere** [comment]
Can confirm. I'm able to send messages again now.

Can anyone chime in on what caused the service to go down?

**Comment by erickrawczyk** [comment]
I can send messages on android but still can't use signal desktop

**Comment by apraetor** [comment]
@JustPassingByHere Better talk to management ;) The logs show EOF exceptions being thrown, but that could be caused by the server not responding to a new connection request, or sending back corrupted data, or..

**Comment by nanashiz3r0** [comment]
I just got this app last week.  How often do the servers/service go down?

**Comment by dkasak** [comment]
@nanashiz3r0 This is the first time I've experienced this in several years of Signal usage.

**Comment by Trolldemorted** [comment]
Last time was the 17th of march this year, so it is a rather rare occurrence.

**Comment by nanashiz3r0** [comment]
Thank you for your responses, I'm trying to implement this at work and I don't want/need any issues. lol

**Comment by schmeat** [comment]
It appears to be back up for me.

**Comment by erickrawczyk** [comment]
Service is confirmed up again, [here's the official twitter statement](https://twitter.com/whispersystems/status/923992983417917440)

I think this is closable @moxie0

**Comment by jlund** [comment]
Thanks!
