### ISSUE TITLE
Chrome Extension does not get past loading screen

### ISSUE THREAD

**Issue by samabenie1** [WhisperSystems/Signal-Android#7143]
I have:
- [x] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] reinstalled both chrome and the signal extension. Reinstalling the extension works for some time, but the issue will re-present itself after a few weeks.

Happens on multiple devices. I have also tried multiple versions of Chrome.

----------------------------------------

### Bug description
Chrome Extension does not open

### Steps to reproduce
- Go to windows search bar
- Type "signal"
- open signal

**Actual result:** Permanent loading screen
**Expected result:** Load my texts

### Screenshots
![image](https://user-images.githubusercontent.com/33236336/32196153-bbfc6d1e-bd8d-11e7-9002-5d36fc3d8553.png)

### Device info
**Chrome Version: 61.0.3163.100
**Signal version:** 0.44.0

### Link to debug log
Can't really do that...

**Comment by FeuRenard** [comment]
Please use that issue tracker:
https://github.com/WhisperSystems/Signal-Desktop/issues

**Comment by nrizzio** [comment]
...and close out this issue.
