### ISSUE TITLE
Export / Backup / Migration of Signal chats to keep all shared Media as well 

### ISSUE THREAD

**Issue by breznak** [WhisperSystems/Signal-Android#7146]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I want to backup / migrate all of my signal conversations to a new device. There exists Export/Improt for plaintext msgs, I want to export the media shared in conversations (both mine and other side's) as well, this includes primarily photos/videos/files (if others, like gifs, etc. can be exported as well, it'd be a bonus) 

### Steps to reproduce
- try to export your conversation thread

### Device info
**Signal version:** latest from app store

**Comment by FeuRenard** [comment]
Duplicate of #1619

**Comment by breznak** [comment]
Maybe more duplicate of #7097 
Closing here.
