### ISSUE TITLE
Support for Librem 5 HW phones (no GPlay) with PureOS (deb), or compatibility with Matrix/riot protocol

### ISSUE THREAD

**Issue by breznak** [WhisperSystems/Signal-Android#7148]
The privacy & security focused mobile HW has just been founded: 
https://puri.sm/shop/librem-5/ 

As these projects share common ideology, it would be nice if Signal were natively ported to the PureOS platform on release day. 

* ETA availability for customers on 1/2019
* `PureOS` (already available), based on Debian, definitely withOUT GPlay services

Alternative to a native port would be a compatibility with their intended IM: `Matrix` using `riot` protocol (i think the compatibility would be a better approach, but not sure if it's feasible?)

**Comment by moxie0** [comment]
I'm not sure what PureOS is, but if it's a skinned version of Android that meets the Android CTS, then Signal should work.

**Comment by breznak** [comment]
It's definetely not a skinned version of android, it's a debian based distro that will run the phones.

**Comment by christianfl** [comment]
It is just a Debian based distro which will be adapted to work on small screens (smartphones). So the new Signal-Desktop Electron application should work. In my opinion the only question is whether the desktop application will support the standalone mode one time. Will it maybe?

**Comment by s72785** [comment]
nicest would be a gateway to matrix as this one already enables us to use irc and xmpp, so more people can communicate.
