### ISSUE TITLE
After Update to 4.12.0 emojis not showing correctly

### ISSUE THREAD

**Issue by FaizKhan5** [WhisperSystems/Signal-Android#7157]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

Bug description
After updating to 4.12.0 emojis are totally broken in messages and drawer 

### Screenshots
#5973 this issue last comment for screenshot

### Device info
**Device:** Qmobile i6 Metal One
**Android version:** 6.0
**Signal version:** 4.12.0

**Comment by moxie0** [comment]
Duplicate #5973

**Comment by FaizKhan5** [comment]
But please fix this issue ASAP

**Comment by moxie0** [comment]
@FaizKhan5 Please read the contributing guidelines before posting again in this tracker: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#issues
