### ISSUE TITLE
[Feature Request] Make Signal availiable for users in China. 

### ISSUE THREAD

**Issue by MichaelJendryke** [WhisperSystems/Signal-Android#7159]
Over here we do not have access to the Google Play Store and other AppStores do not provide the Signal App. Is there an alternative way to download the apk file so we can also enjoy encrypted conversations?

The App is available on the Apple AppStore in China, so I guess the software itself is not banned. 

Thanks

**Comment by FeuRenard** [comment]
You should try this:
https://signal.org/android/apk/

For future questions please use the [community forum](https://whispersystems.discoursehosting.net/) instead. This issue tracker should be used [exlusively for bugs and feature requests](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#issue-tracker-is-for-bugs).

**Comment by MichaelJendryke** [comment]
Needed a VPN but it works, Thanks!
