### ISSUE TITLE
Messages in Egypt fails to send occasionally then succeeds after retrying more than one time 

### ISSUE THREAD

**Issue by icarus-1** [WhisperSystems/Signal-Android#7164]
### Bug description
Messages in Egypt fails to send occasionally then succeeds after retrying more than one time .

### Steps to reproduce
- send a message.
- mostly it fails in the first time.
- retry sending more than one time then it succeeds.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Redmi Note 4
**Android version:** 7.0.0
**Signal version:** 4.11.5

### Link to debug log
https://gist.github.com/anonymous/6d338dbacc269ec74050004f0af9d540

**Comment by moxie0** [comment]
Should be fixed in 4.12.3
