### ISSUE TITLE
Feature discussion: Blockchain verified conversations

### ISSUE THREAD

**Issue by vangorra** [WhisperSystems/Signal-Android#7169]
This discussion really applies to the entire Signal stack, but it had to put someplace. Also, I'm not entirely sure signal doesn't already have something like this.

Signal does a great job at client e2e encryption. People mostly seem excited about it's ability to prevent people from listening in on conversations. Aside from encryption GPG also gives us verification that the message originated from a specific individual. I'm curious, what is that verification was taken one step further?

What if a blockchain (of sorts) was kept for each conversation? This way, we enforce the order in which messages were sent and most importantly that message b came directly after message a. Deletion or insertion of messages after the fact would not be possible. Such an implementation would ensure a conversation remains the same between all parties involved and that no individual could inject or remove parts of conversations without the other parties involved noticing.

An example of something like this is how git handles commits. Each commit contains a hash of the current commit (and diff) and the hash of the previous commit. A simple program can then run against the commits to verify the repo is in good order.

In Signal's case, a central authority would be necessary. So the hash chain would probably need to exist on the server. The clients can sync against the hash chain and verify their local conversations match the server's. 

Thoughts?

**Comment by nrizzio** [comment]
This issue tracker is not a discussion forum: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#not-a-discussion-forum

However, you can open a thread at the community forum: https://whispersystems.discoursehosting.net

**Comment by vangorra** [comment]
Okay. I posted it on the discussion forum.
