### ISSUE TITLE
[Feature request] Know when someone is typing/last seen online

### ISSUE THREAD

**Issue by trymeouteh** [WhisperSystems/Signal-Android#7181]
A minor cool feature would be to see when someone is typing in the conversation weather it is a group chat or a one-on-one chat.  And to know when someone was viewing the conversation last. This way you know weather they are taking awhile to reply since they are typing a long reply or they are away.

**Comment by johanw666** [comment]
The server does not store this information. This has been asked for before, like in https://github.com/WhisperSystems/Signal-Android/issues/5051 . A will not implement feature.

**Comment by haffenloher** [comment]
Not sure about last seen, but typing indicators are being tracked at #1121. Please search for duplicates and don't delete the issue template when opening new issues.

**Comment by moxie0** [comment]
Duplicate #1121
