### ISSUE TITLE
[Feature request] Send Recieve Read Group Chat Options

### ISSUE THREAD

**Issue by trymeouteh** [WhisperSystems/Signal-Android#7182]
A handy feature to have is to be able to choose in your settings when it comes to group chat Send Recieve Read Receipts weather you get a checkmark when one person in the group has Recieved/Read it or if you get a checkmark when all the people on the group have Recieved/Read it.

**Comment by PiCob** [comment]
This has been discussed in the forum: https://whispersystems.discoursehosting.net/t/read-receipts-using-group-chat-behaviour-is-this-expected-or-bug/1340

I'd also prefer it the other way around, but I don't think a setting will be provided, since "the answer is never more options"...

**Comment by moxie0** [comment]
Thanks but we're not going to do this. The latter behavior makes sense in systems where all users always send group read receipts (ie whatsapp), but not systems where individual users can opt out of sending group read receipts (ie signal), and the answer is never more options.
