### ISSUE TITLE
[Feature request] Video Call Transparent UI

### ISSUE THREAD

**Issue by trymeouteh** [WhisperSystems/Signal-Android#7184]
I find the UI of the Video calls on Andriod (And maybe the same on iOS) to take up a lot of room. My only suggestion is to make the buttons and menus transparent so you can see through them and if some people like it the way it is have add an option in the settings for transparent buttons and menus so everyone can choose what they prefer.

**Comment by moxie0** [comment]
Thanks but we're not going to do this. Please try to follow the issue template when posting issues here, and please consider reading the contributing guidelines. Thanks!
