### ISSUE TITLE
Messages not delivered over wifi

### ISSUE THREAD

**Issue by amrod** [WhisperSystems/Signal-Android#7186]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Messages fail to send over wifi.

### Steps to reproduce
- Connect to wifi at home
- Send a message to another Signal user
- Get "Not delivered - Tap for details" error. When tapping for details the error message is: "Some issues need your attention."

**Actual result:** Message not sent.
**Expected result:** Message sent.

### Screenshots
n/a

### Device info
**Device:** OnePlus 3
**Android version:** 7.1.1
**Signal version:** 4.11.5

### Link to debug log
https://gist.github.com/anonymous/891bac2b8b2c2f42197b22cbbd9e4082

**Comment by haffenloher** [comment]
`java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

The SSL certificate presented to the app is wrong. Apparently something (e.g. a captive portal) is intercepting your SSL connection.

**Comment by moxie0** [comment]
Yep, looks like a captive portal or some other mitm.
