### ISSUE TITLE
[Feature Request] Remove users from Signal Groups.

### ISSUE THREAD

**Issue by samabenie** [WhisperSystems/Signal-Android#7187]
**Bug description**

I have a signal group chat, but I am unable to remove users.

**Steps to reproduce**

View list of users in signal group. no options to add or remove.

**Actual result**: No options to edit group members
**Expected result**: Provide options to add/remove group members.

**Comment by jeremymasters** [comment]
subset of https://github.com/WhisperSystems/Signal-Android/issues/7150

**Comment by nrizzio** [comment]
I would say it's pretty clearly a duplicate.
Please read the contribution guidelines, follow the template, and search for duplicates before opening an issue.

**Comment by moxie0** [comment]
Closing as duplicate
