### ISSUE TITLE
Friend doesn't receive messages after deleting Signal

### ISSUE THREAD

**Issue by mckaz** [WhisperSystems/Signal-Android#7188]
I have:
- [ X ] searched open and closed issues for duplicates
- [ X ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When a friend who has Signal uninstalls the app, but does not delete their account, and I continue to send them messages through Signal, they will not receive the messages. This has now happened with multiple friends of mine. The fix is to have them reinstall the app, delete their account, then uninstall again. But it causes great confusion and it is particularly challenging for people who aren't tech-savvy. It seems there should be a way for Signal to send to a user's default messaging app in the case that they don't have Signal installed on their phone.

**Comment by jeremymasters** [comment]
This is a duplicate several times over.  Also see https://signal.org/signal/unregister/ if you don't want to re-install just to unregister.

**Comment by moxie0** [comment]
Closing as duplicate
