### ISSUE TITLE
Show message content in notifications only when phone unlocked

### ISSUE THREAD

**Issue by unhammer** [WhisperSystems/Signal-Android#7190]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

If I set notifications to hide message contents, then I can't even see message content in notifications when the screen is unlocked. 

If I set to show message contents, I see the message contents also when the screen is locked.

**Feature request**: I'd like the possibility to have message contents in notifications if and only if the screen is unlocked.

### Device info

**Device:** Samsung S4 Active / GT-I9295
**Android version:** 5.0.1
**Signal version:** 4.12.3

**Comment by micressor** [comment]
@unhammer Have a look at signal's `settings -> notifications` menu. There is an option for that.

**Comment by unhammer** [comment]
@micressor The settings are

**Show**
- [ ] Name and message
- [ ] Just name
- [ ] No name nor message

There is no option that I can see for 

- [ ] Name and message when screen unlocked, just name when screen locked.

I have tried both "Name and message" and "Just name", and neither do what I want.

**Comment by haffenloher** [comment]
Isn't there an Android setting to "hide sensitive notification content on the lock screen" (or similar)? I think I saw that option on someone's phone some time ago. Not sure if it's there with Android 5.

**Comment by jeremymasters** [comment]
@unhammer This is probably a topic that would be better to ask in the [forums](https://whispersystems.discoursehosting.net/) first so the devs can dev.

**Comment by unhammer** [comment]
> Isn't there an Android setting to "hide sensitive notification content on the lock screen" (or similar)? I think I saw that option on someone's phone some time ago. Not sure if it's there with Android 5.

You're right, there is! Thanks, I'll close this then – it seems it's already solved on the OS-level :-)
