### ISSUE TITLE
[feature request] ability to relay SMS to Signal Desktop

### ISSUE THREAD

**Issue by alex** [WhisperSystems/Signal-Android#7193]
If you use Signal for Android as an SMS client, you have to look at your phone to read the SMS, even if you have a Signal Desktop paired with the Android.

It'd be great if there was a way to configure Signal for Android to automatically proxy SMS messages to/from Signal Desktop. I'm told iMessages does this as well.

**Comment by nrizzio** [comment]
This feature has been rejected in the past multiple times, although I am on my phone so I cannot find the exact duplicate.

**Comment by alex** [comment]
Doh. I only searched open issues.

**Comment by FeuRenard** [comment]
E.g. here is a statement: https://twitter.com/whispersystems/status/900867109730766848

**Comment by moxie0** [comment]
Yeah, thanks for the suggestion but we've decided not to do this. The desktop client doesn't depend on the phone being on, but this would, and it would greatly complicate the user experience.

**Comment by jbwinters** [comment]
While not a must-have (from my perspective), it's a highly desirable nice-to-have. I believe Apple's iMessage has provided this functionality for a long time (never been an iphone user so not positive). As of a week ago, Android Messages does something similar. I understand the systems involved on their ends are very different, but there may be other solutions: an optional proxy disabled by default and slathered in warnings, auto-syncing with the OS standard SMS apps, or even a basic plugin API so we can make our own would be wonderful.
