### ISSUE TITLE
Signal crashes on image forward

### ISSUE THREAD

**Issue by lazlolazlolazlo** [WhisperSystems/Signal-Android#7195]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Forwarding image crashes Signal

### Steps to reproduce
- select image in thread
- click the forward button
- Signal crashes

**Actual result:** Clicking forward image button crashes Signal
**Expected result:** Clicking forward image button displays contact list

### Screenshots
![signal-2017-11-16-115511](https://user-images.githubusercontent.com/601905/32887783-5e12d536-cac5-11e7-8adf-9ab0c1b50705.jpg)
![signal-2017-11-16-115536](https://user-images.githubusercontent.com/601905/32887800-6a30c102-cac5-11e7-869b-45300b6833ed.jpg)

### Device info

**Device:** Wilefox Spark +
**Android version:** 7.0
**Signal version:** 4.13.0

### Link to debug log

https://gist.github.com/8b593a3dd4a1c96df47c274b088f7086

**Comment by FeuRenard** [comment]
I can reproduce what you described, but there are more affected actions:

- Sharing from another app via Signal
- sharing text from inside a conversation

**Comment by schmeat** [comment]
Crashes for me too when I try and use androids share menu

https://gist.github.com/3893e494c9cc87ea02e2f05770d55481

**Comment by i7u** [comment]
I loudly protest. I had two juicy crash logs to offer and you've gone ahead and fixed the issue already?! How inconsiderate :-)
