### ISSUE TITLE
Signal Crashes When Receive Calls

### ISSUE THREAD

**Issue by FaizKhan5** [WhisperSystems/Signal-Android#7199]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

Bug description
When I Receive Calls From Anyone Signal Is Force Stopped.

Steps to reproduce
- When I Receive Someone Calls Signal Stopped Again And Again
- Not On Getting Incoming Calls But Only When I Swipe To Receive Call
- Signal Force Stopped Messages Shows And Call Disconnect 

Actual result: When Swipe To Receive Call Signal Crashes And Call Disconnect
Expected result: Swipe To Receive Call And Call Starts Without Any Issue

Device info
Device: Qmobile Noir i6 Metal One
Android version: 6.0
Signal version: 4.13.0

Link to debug log
https://gist.github.com/ed791e91111521f555e01eaf94619a5e

**Comment by benefaktorix** [comment]
I have the same issue. Signal version 4.13.1 has not fixed the problem. 
Device: BlackBerry PRIV 
OS: MM 6.0.1 
Debug log just after the crash when trying to answer a call: https://gist.github.com/df224d98c75ae091a759339ffa38cbe1

**Comment by KarolTrzeszczkowski** [comment]
The same here
Device  : Meizu M2 Note (lineage_m2note)
Android : 7.1.2 Lineage OS
Signal 4.13.1
https://gist.github.com/anonymous/656c53969dcb5fdf0d914c67ed064d94

**Comment by warblend** [comment]
Same for me. Some further information:

- On the caller's phone the status is "Ringing" after Signal crashes on the phone that is receiving the call. 
- Answering a call is still possible through the notification, if one opens the drawer. 
- Crash happens exactly when the middle circle (the one which is swipped) is touched, not when one starts swiping. 

Device: Lg K420n
Android: 6.0
Signal: 4.13.1

**Comment by MikkoMajuri** [comment]
Same issue with me.

Here's the log:
https://gist.github.com/anonymous/aa6252c8dd4c8757f5fb011c020c988f

**Comment by cegg1** [comment]
Exactly the same issue. The call rings and Signal crashes when you try to answer the call. 

Caller: Nexus 4 stock ROM
Receiver: Nexus 5 stock ROM
Signal 4.13.1

D WebRtcCallService: java.lang.IllegalArgumentException: 
Bad argument for key "onComplete" with value class org.thoughtcrime.securesms.components.multiwaveview.MultiWaveView$AnimationsWrapper$4
--------- beginning of crash
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: org.thoughtcrime.securesms, 
E AndroidRuntime: java.lang.IllegalArgumentException: Bad argument for key "onComplete" with value class org.thoughtcrime.securesms.components.multiwaveview.MultiWaveView$AnimationsWrapper$4

Debug log:
https://gist.github.com/68a91d60c6bba95a1284b878f1e957e4

**Comment by i7u** [comment]
Another one with caller on ios and receiver in beta android channel: https://gist.github.com/anonymous/0e177cc2045263bdc7ac0289652c247f

**Comment by ruicruzpt** [comment]
Any update on this?

Same problem here.

**Comment by zero77** [comment]
Same problem hear, should I also post a log or is there enough.
Android version: 6.0
Device: LG G3

**Comment by johanw666** [comment]
A mee too here: receiver Sony Z3 compact, Android 6.0.1. Caller is an iPhone 5s.

Link to debug log: https://gist.github.com/anonymous/84ea15d124790b2031f020e62b4ca821

The same exception as above:
```
11-19 17:03:14.831 30259 30259 E AndroidRuntime: FATAL EXCEPTION: main
11-19 17:03:14.831 30259 30259 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 30259
11-19 17:03:14.831 30259 30259 E AndroidRuntime: java.lang.IllegalArgumentException: Bad argument for key "onComplete" with value class org.thoughtcrime.securesms.components.multiwaveview.MultiWaveView$AnimationsWrapper$4
11-19 17:03:14.831 30259 30259 E AndroidRuntime: 	at org.thoughtcrime.securesms.components.multiwaveview.Tweener.to(Tweener.java:93)
11-19 17:03:14.831 30259 30259 E AndroidRuntime: 	at org.thoughtcrime.securesms.components.multiwaveview.MultiWaveView.showTargets(MultiWaveView.java:515)
11-19 17:03:14.831 30259 30259 E AndroidRuntime: 	at org.thoughtcrime.securesms.components.multiwaveview.MultiWaveView.switchToState(MultiWaveView.java:291)
11-19 17:03:14.831 30259 30259 E AndroidRuntime: 	at org.thoughtcrime.securesms.components.multiwaveview.MultiWaveView.trySwitchToFirstTouchState(MultiWaveView.java:833)
11-19 17:03:14.831 30259 30259 E AndroidRuntime: 	at org.thoughtcrime.securesms.components.multiwaveview.MultiWaveView.handleDown(MultiWaveView.java:702)
11-19 17:03:14.831 30259 30259 E AndroidRuntime: 	at org.thoughtcrime.securesms.components.multiwaveview.MultiWaveView.onTouchEvent(MultiWaveView.java:671)
11-19 17:03:14.831 30259 30259 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:9377)
```

**Comment by FaizKhan5** [comment]
@moxie0 Now my device is Huawei Mate 10 Lite

**Comment by FaizKhan5** [comment]
And same problem on that too

**Comment by itmaciek** [comment]
Same problem with calls, exact same exception.
Signal 4.13.1
Android 8.1.0

**Comment by moxie0** [comment]
Thanks for being beta testers everyone

**Comment by FaizKhan5** [comment]
@moxie0 Welcome 😊
