### ISSUE TITLE
In new share, recent chats groups have their string identifier instead of number

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#7201]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
In the new share from another app, single contacts look fine but for a group it shows the string identifier for the group where the number for an individual contact would go if it was a 1x1 chat. 

### Steps to reproduce
- have a signal group you've chatted with recently
- go to another app to share back to Signal
- signal pops up recent chats

**Actual result:** 1x1 chats show contact number but groups show string identifier
**Expected result:** group chats would show nothing or maybe "3 members"

**Comment by Dyras** [comment]
Yup same here on my Moto G4 with Android 7.0.1
![screenshot_20171117-172140](https://user-images.githubusercontent.com/12563436/32957618-87aca550-cbbc-11e7-9ef7-3fed6d91e743.png)
