### ISSUE TITLE
Fix User Interface Issues

### ISSUE THREAD

**Issue by FaizKhan5** [WhisperSystems/Signal-Android#7204]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------
Bug description
Please Fix UI Issues which i saw from severals months but issues remain exist and no one post this. 

Screenshots
Fix Camera And Mic Icon Placement With Emojis Icon
![img_20171117_063440_291](https://user-images.githubusercontent.com/26612909/32962671-209be83e-cbef-11e7-98e7-de34d63dd685.JPG)

Too Much Space Between Back Arrow And Contact Badge Even 5 5 characters First Last Name Not Showing Full And Shows Dots Because Of Not Fitting In Area, Please Fix
![img_20171117_063556_288](https://user-images.githubusercontent.com/26612909/32962702-4ab9aa2a-cbef-11e7-998a-8307d1f879fb.JPG)

Again Please Fix This
![img_20171117_064258_303](https://user-images.githubusercontent.com/26612909/32962834-b6110642-cbef-11e7-836e-33db63442f50.JPG)

Device info
Device: Qmobile Noir i6 Metal One
Android version: 6.0
Signal version: 4.13.1

Link to debug log

**Comment by moxie0** [comment]
Looks like your device has a very low quality display (mdpi?). I'm unable to reproduce the first screenshot, the second is not going to change, and I don't have any idea what you're referring to in the third screenshot.

**Comment by FaizKhan5** [comment]
@moxie0 Framework Resource Selection Is Normal HDPI 480x854
Why Second Picture Problem Not Fixing ?
In Third Picture When You Skip Lines Emoji Button Remain On Bottom But Camera And Mic Button On Top Not Looking Correctly I Think Emoji Button Is Also On Top Like Mic And Camera Button

**Comment by bme13** [comment]
I don't have issue 1 and 2 however the third one is indeed a bit strange. This happens if you only type enters in the textbox. As soon as I start entering text the camera and mic button disappear. To me the intended behavior seems to be that once the textbox is not empty the camera and mic button disappear however enters seems to be the exception to this. Not sure if this is meant to be.

**Comment by FaizKhan5** [comment]
Thanks

**Comment by FaizKhan5** [comment]
@moxie0 i notice same thing on new huawei mate 10 lite as in first image camera and mic button is little up from line as compare to emoji button please fix.

**Comment by FaizKhan5** [comment]
May be i feel like that but please check in graph lines
