### ISSUE TITLE
Unable to change profile picture

### ISSUE THREAD

**Issue by LeeWilson** [WhisperSystems/Signal-Android#7205]
### Bug description
Unable to change profile picture via a set file (also attempted via camera) 
After initially setting up a profile picture successfully, it is not possible to change the profile picture to a different image. It is possible to clear the profile picture completely, however any other image that is selected results in the first still being displayed. I have confirmed with a friend, they also get this experience. 

### Steps to reproduce
- Go to settings. 
- Click on profile picture (takes you to profile area)
- Click again on profile picture ot edit it. 
- Click on files 
- Select an image
- Click done
- Image does not change

**Actual result:** 
Image does not change
**Expected result:** 
Image should be replaced by the one selected
### Device info
Google Pixel
**Android version:** 8.0.0
**Signal version:** 4.12.3

### Link to debug log
Https://gist.github.com/1b10e48420773e8d97dbf4df75433c8c

**Comment by moxie0** [comment]
This is fixed in 4.13.x
