### ISSUE TITLE
Will there be option to edit or delete messages?

### ISSUE THREAD

**Issue by alvosec** [WhisperSystems/Signal-Android#7207]
We are wondering if there will be _edit_ or _delete_ option for messages for individual or group chat? Let's consider scenario where someone posted something private accidentally, what can be a solution for that, this is just on example which may be more related to the privacy of user.

**Comment by moxie0** [comment]
@alvosec Please review the contributing guidelines before posting here again: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md

We don't use the issue tracker for Q&A.
