### ISSUE TITLE
Messages send after a received SMS should not default to Signal message replies

### ISSUE THREAD

**Issue by ahirschberg** [WhisperSystems/Signal-Android#7209]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When Signal is used as an SMS client, it is frustrating for the user and the recipient of messages in which the recipient has Signal installed but is still using SMS. Many of my contacts have signal installed but still use SMS separately, or use iPhones where they cannot use signal for SMS.

When a Signal contact sends me an SMS message, the Signal default is to respond via a Signal message, which is confusing for the other party and inconvenient for the user, who has to remember to change the mode to SMS. This discourages users from using Signal as their SMS client.

### Steps to reproduce
Receive an SMS from a phone number registered with Signal.

**Actual result:** The user responds with a Signal message, which may appear differently on the recipient's device and cause confusion.
**Expected result:** The Signal app should either match the sender's mode of communication (perhaps with a warning about encryption) OR remember the user's preference for that contact across restarts of the app.

### Screenshots
Friend sends an SMS. I reply in Signal without realizing, then re-reply via SMS.
![screenshot_20171120-104348](https://user-images.githubusercontent.com/5578698/33027455-25a5d1c0-cde1-11e7-99a0-7d9c755fd195.jpg)

Friend sends an SMS. I remember to change the send-mode to SMS, but after an app restart the app is back to the default of sending Signal messages.
![screenshot_20171120-104455](https://user-images.githubusercontent.com/5578698/33027546-5f55d76c-cde1-11e7-8d9c-fed032f0abab.jpg)

### Device info

**Device:** Samsung Galaxy S7 Edge
**Android version:** 7.0
**Signal version:** 4.12.3

**Comment by johanw666** [comment]
I believe the idea is to send as much messages via a secure channel, especially after the support for encrypted sms was dropped. So if the number supports Signal messages Signal tries not to send an sms by default.

This default is good for people who do not have an unlimited sms bundle, which is the case on many places. And it encourages to send as much encrypted messages as possible. After all, the other side has Signal installed so sms is only to be used when we can expect the other side has no data connection. Then they might see a part of a message thread in a separate app, is this really a big issue?

**Comment by 2-4601** [comment]
> **Expected result:** The Signal app should either match the sender's mode of communication (perhaps with a warning about encryption)

I think this has been discussed before however I can't remember if there's a specific issue for this...

> OR remember the user's preference for that contact across restarts of the app.

...but there is for this: https://github.com/WhisperSystems/Signal-Android/issues/2285

**Comment by nicholasfoden** [comment]
Perhaps an option to delete the users keys from the app could help with the security issue with default behaviour. If the contact re-installed signal, after the new key exchange Secure would then be the default.

**Comment by moxie0** [comment]
Thanks but we're not going to do this. We explicitly want Signal to upgrade a conversation to encrypted communication whenever possible.

**Comment by stin7** [comment]
Could we consider UX changes to notify users that there is a mismatch?

Perhaps a toast with something along the lines of: "You replied to an insecure SMS with a secure Signal message. If the recipient is no longer using Signal, they may not receive that message. If you want to send an insecure SMS, long-press the send button to change the delivery method." (I acknowledge that's a really long toast and would need to be trimmed)

Or, just a highlighting of the unlocked and locked padlocks to show they aren't on the "same channel"

(All that said, I think #7210 is a better solution, despite adding more options. There is a set of contacts that try signal and leave without de-registering, and then after that the issue referenced here is a permanent annoyance for the user still using Signal, every time they are contacted by someone from that group.)

**Comment by nicholasfoden** [comment]
I totally agree with upgrading to an encrypted conversation whenever possible, but how conversations are handled when that isn't possible is what is broken. Perhaps a UX change could help highlight it, but IMO something needs to change.

**Comment by mwmalick** [comment]
My mother got a new phone, had not installed signal yet, and was sending me SMS messages. I did not realize my return messages were not getting through to her because they were automatically sent as signal messages. I understand wanting to always promote encrypted conversation whenever possible, but it shouldn't be at the expense of possibly losing messages. I missed a funeral because of this default behavior.

**Comment by tristandl** [comment]
Yes it's a big issue. As an iPhone user I'm going to delete my signal account over it because I rarely use it but I started missing replies from contacts with android phones.

**Comment by mkay581** [comment]
Yeah I was surprised to see this behavior by default. It's very confusing. I've stopped using Signal because of this.

**Comment by maym86** [comment]
This is still a problem. A new contact sends me a message via text and reply goes to signal without notifying me that it isn't actually getting received because the texter doesn't have signal installed. Please have an option to allow the default reply to be via the method a message was received.
