### ISSUE TITLE
Unable to answer incoming call due to decline button overlays accept button

### ISSUE THREAD

**Issue by halb9** [WhisperSystems/Signal-Android#7211]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The decline button is overlapping the accept button for incoming calls. Not impossible but very challenging to swipe up. (see Screenshot)

### Steps to reproduce
Best thing for me to reproduce is to restart my phone. At first I thought this would only occur when the incoming call is the first after a fresh start. But that didn't turn out to be true. 
All I can say for now is sometimes it happens, sometimes it doesn't. 

**Actual result:** Decline button is in front of the accept button which makes it nearly impossible to answer calls. 
**Expected result:** Do the intended thing ;)

### Screenshots
![signal-2017-11-20-190545](https://user-images.githubusercontent.com/18451020/33034823-f8562388-ce20-11e7-8f3a-004e285180ea.png)

### Device info

see logs

### Link to debug log

https://gist.github.com/anonymous/a009a315cfa32d5e837482f6a0e2bd73
Different phone but same behavior: https://gist.github.com/5d1ac370ee1029b0a2cb2d758aea8d7f

**Comment by moxie0** [comment]
I am unable to reproduce this

**Comment by halb9** [comment]
I just tried it with a friend. I called him. He had exactly the same problem. 
Screenshot is from his phone. 
Phone is a OnePlus5 with OxygenOS. 
Debug Log: https://gist.github.com/cdb8eccbe0b6f79262ce0760e34579b7
