### ISSUE TITLE
Emoji appearance altered after update

### ISSUE THREAD

**Issue by FeuRenard** [WhisperSystems/Signal-Android#7212]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Some emoji in the recent emoji list were changed to the Android ones after update to 4.13.2. They also changed in the messages. But I don't find Android styled emoji in any category.

### Steps to reproduce
- update to 4.13.2

**Actual result:** Some emoji change their appearance to the Android style.
**Expected result:** Emoji don't change their appearance.

### Screenshots
![screenshot_20171121-002554 01](https://user-images.githubusercontent.com/16167751/33047050-0f1cf370-ce54-11e7-937d-ac5b0535412d.png)
See "walking", ":)", ":(" and "<3".

### Device info

**Device:** Fairphone 2
**Android version:** 6.0.1
**Signal version:** 4.13.3

**Comment by rainerzufall** [comment]
Can not reproduce on the same device (Device: Fairphone 2 // Android version: 6.0.1 // Signal version: 4.13.3)

**Comment by dcherian** [comment]
Same issue here with :( 

on motog4 Android 7.0 signal 4.13.2

**Comment by moxie0** [comment]
Hmm, damn. I think the deal is that "walking" is actually three different emoji: man-walking, woman-walking, and walking. The latter is the same glyph as man-walking, and is marked as "obsoleted" by man-walking, however it is a unique character.

In the past all three were in there, which resulted in duplicate glphys in the picker (two men walking, one woman walking). I removed all the "obsoleted" glyphs to eliminate the duplicates, but now that means there's no glphy to render in situations where they *are* used.

**Comment by moxie0** [comment]
@FeuRenard Do you have root on that device? It'd be helpful if you could send me the value of the pref_recent_emoji2 shared pref.

**Comment by FeuRenard** [comment]
I don't have root on this device. But the issue is fixed for me with 4.13.4.
