### ISSUE TITLE
Couple issues with answering screen for signal calls

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#7214]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug descriptions
New call answering button is far enough down that it's a little tight for declining calls. 
The text for describing what to do is a bit hard to read for a person with no profile picture.
Declined calls show as unread missed calls in the conversation. 

### Device info

**Device:** galaxy s8
**Android version:** 7.0
**Signal version:** 4.13.3

**Comment by moxie0** [comment]
Unless the third item is a regression (I don't think it is?), I'm cool with the first two since it's the same as the default dialer.
