### ISSUE TITLE
Signal crashes on opening (4.13.4)

### ISSUE THREAD

**Issue by anarchogeek** [WhisperSystems/Signal-Android#7219]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I tap on Signal logo, Signal seems to open for halo a second then closes. No error, no toast. Also my contacts told me that they sent messages, but I had no notifications. I am on Signal Beta (4.13.4). I reinstalled yesterday (Nov 24) because I bought a new phone (oneplus 5t). It worked with no issues for 24h. I tried to clean cache and to reboot phone.

### Steps to reproduce
- tap signal icon

**Actual result:** Very brief flash (half a second) of the animation of app opening. Then back to home screen.
**Expected result:** Signal opens and I receive my message.

### Screenshots
If necessary I can upload a screen recording.

### Device info

**Device:** Oneplus 5t (8gb ram)
**Android version:** 7.1.1
**Signal version:** 4.13.4

### Link to debug log

I can't open app. Is there another way to get error log?

**Comment by moxie0** [comment]
adb logcat

**Comment by anarchogeek** [comment]
Thanks for the answer. I tried to remove non-related strings but I don't know if succeeded.

`11-25 19:53:34.147 27968 27984 W JobConsumer: java.lang.NullPointerException: Attempt to invoke interface method 'int org.whispersystems.libsignal.ecc.ECPublicKey.getType()' on a null object reference
11-25 19:53:34.147 27968 27984 W JobConsumer:   at org.whispersystems.libsignal.ecc.Curve.calculateAgreement(Curve.java:60)
11-25 19:53:34.147 27968 27984 W JobConsumer:   at org.thoughtcrime.securesms.crypto.AsymmetricMasterCipher.encryptBytes(AsymmetricMasterCipher.java:68)
11-25 19:53:34.147 27968 27984 W JobConsumer:   at org.thoughtcrime.securesms.crypto.AsymmetricMasterCipher.encryptBody(AsymmetricMasterCipher.java:102)
11-25 19:53:34.147 27968 27984 W JobConsumer:   at org.thoughtcrime.securesms.database.EncryptingSmsDatabase.getAsymmetricEncryptedBody(EncryptingSmsDatabase.java:54)
11-25 19:53:34.147 27968 27984 W JobConsumer:   at org.thoughtcrime.securesms.database.EncryptingSmsDatabase.insertMessageInbox(EncryptingSmsDatabase.java:107)
11-25 19:53:34.147 27968 27984 W JobConsumer:   at org.thoughtcrime.securesms.database.EncryptingSmsDatabase.insertMessageInbox(EncryptingSmsDatabase.java:88)
11-25 19:53:34.147 27968 27984 W JobConsumer:   at org.thoughtcrime.securesms.jobs.SmsReceiveJob.storeMessage(SmsReceiveJob.java:104)
11-25 19:53:34.147 27968 27984 W JobConsumer:   at org.thoughtcrime.securesms.jobs.SmsReceiveJob.onRun(SmsReceiveJob.java:63)
11-25 19:53:34.147 27968 27984 W JobConsumer:   at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
11-25 19:53:34.147 27968 27984 W JobConsumer:   at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
11-25 19:53:34.147 27968 27984 E AndroidRuntime: FATAL EXCEPTION: JobConsumer-0
11-25 19:53:34.147 27968 27984 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 27968
11-25 19:53:34.147 27968 27984 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'int org.whispersystems.libsignal.ecc.ECPublicKey.getType()' on a null object reference
11-25 19:53:34.147 27968 27984 E AndroidRuntime:        at org.whispersystems.libsignal.ecc.Curve.calculateAgreement(Curve.java:60)
11-25 19:53:34.147 27968 27984 E AndroidRuntime:        at org.thoughtcrime.securesms.crypto.AsymmetricMasterCipher.encryptBytes(AsymmetricMasterCipher.java:68)
11-25 19:53:34.147 27968 27984 E AndroidRuntime:        at org.thoughtcrime.securesms.crypto.AsymmetricMasterCipher.encryptBody(AsymmetricMasterCipher.java:102)
11-25 19:53:34.147 27968 27984 E AndroidRuntime:        at org.thoughtcrime.securesms.database.EncryptingSmsDatabase.getAsymmetricEncryptedBody(EncryptingSmsDatabase.java:54)
11-25 19:53:34.147 27968 27984 E AndroidRuntime:        at org.thoughtcrime.securesms.database.EncryptingSmsDatabase.insertMessageInbox(EncryptingSmsDatabase.java:107)
11-25 19:53:34.147 27968 27984 E AndroidRuntime:        at org.thoughtcrime.securesms.database.EncryptingSmsDatabase.insertMessageInbox(EncryptingSmsDatabase.java:88)
11-25 19:53:34.147 27968 27984 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.SmsReceiveJob.storeMessage(SmsReceiveJob.java:104)
11-25 19:53:34.147 27968 27984 E AndroidRuntime:        at org.thoughtcrime.securesms.jobs.SmsReceiveJob.onRun(SmsReceiveJob.java:63)
11-25 19:53:34.147 27968 27984 E AndroidRuntime:        at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
11-25 19:53:34.147 27968 27984 E AndroidRuntime:        at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
11-25 19:53:34.147 27968 27984 D AppTracker: App Event: crash
11-25 19:53:34.149  1405  3526 W ActivityManager:   Force finishing activity org.thoughtcrime.securesms/.PassphrasePromptActivity
11-25 19:53:34.158  1405  1443 D RestartProcessManager: Duration is too short, ignore : 143 in org.thoughtcrime.securesms
11-25 19:53:34.161 27968 27984 I Process : Sending signal. PID: 27968 SIG: 9
11-25 19:53:34.168  1405 28000 D DropBoxManagerService: file :: /data/system/dropbox/data_app_crash@2017-11-25-19_53_34_154.txt
11-25 19:53:34.174  1405  2031 W InputDispatcher: channel '8d7f27c org.thoughtcrime.securesms/org.thoughtcrime.securesms.PassphrasePromptActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
11-25 19:53:34.174  1405  2031 E InputDispatcher: channel '8d7f27c org.thoughtcrime.securesms/org.thoughtcrime.securesms.PassphrasePromptActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
11-25 19:53:34.182  1405  3525 D GraphicsStats: Buffer count: 22
11-25 19:53:34.182  1405  9965 I WindowManager: WIN DEATH: Window{8d7f27c u0 org.thoughtcrime.securesms/org.thoughtcrime.securesms.PassphrasePromptActivity}
11-25 19:53:34.182  1405  9965 W InputDispatcher: Attempted to unregister already unregistered input channel '8d7f27c org.thoughtcrime.securesms/org.thoughtcrime.securesms.PassphrasePromptActivity (server)'
11-25 19:53:34.182  1405  6122 D EmbryoManager: prepare org.thoughtcrime.securesms user 0
11-25 19:53:34.182  1405  6122 I ActivityManager: Process org.thoughtcrime.securesms (pid 27968) has died
11-25 19:53:34.182  1405  6122 D ActivityManager: cleanUpApplicationRecord -- 27968`

**Comment by moxie0** [comment]
I'm not sure what you did to reinstall or what's going on with your device, but it looks like the key/value store we use on disk got deleted and your asymmetric storage keys are gone. Sorry that happened to you, but there's nothing to do but reinstall. If you haven't done anything abnormal, it could be an indication of a problem with your disk.

**Comment by anarchogeek** [comment]
I reinstalled (via Play Store, as the first time) and everything works again. I must say that after rebooting I removed cache of the app, I don't know where the key is stored. Error appeared to be the same after removing the cache but maybe I just deleted the key. As I'm on the beta I felt obligated to report the error.
