### ISSUE TITLE
improve display of "read receipt"

### ISSUE THREAD

**Issue by simhnna** [WhisperSystems/Signal-Android#7221]
Currently the colors used to distinguish delivered from read messages are so similar, that it's rather hard to distinguish. Also blue is not the best color for color blind people.

Ideally I guess the icon itself should change a little, at least use another color. For me personnaly a more prominent blue would solve the issue.

Currently mobile so please excuse me if it has been filed before...

**Comment by nrizzio** [comment]
This is a duplicate of #7137.

**Comment by simhnna** [comment]
Actually #7112 but thank you for stating that.

Closing in favor of #7112
