### ISSUE TITLE
Crash when editing group members

### ISSUE THREAD

**Issue by i7u** [WhisperSystems/Signal-Android#7225]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Crashed as soon as I added a new member to an existing group

### Steps to reproduce
- Edit group members
- add a contact with their new phone number

Note: the contact had just left the group as he reinstalled Signal because they got a new SIM (new phone number).

**Actual result:** App crashed. On relaunch I can see that the new contract was successfully added. 
**Expected result:** No crash.

### Device info
**Device:** Samsung S5 neo
**Android version:** 6.0.1
**Signal version:** 4.13.5

### Link to debug log

https://gist.github.com/4e80c0d41a6a9c2ef1ced0727123ea69

**Comment by lcouturier** [comment]
Same thing when you want tout save any modifications on the groupe.

**Comment by moxie0** [comment]
There's no crash in that debug log. You need to capture it immediately after the crash.

**Comment by halb9** [comment]
I noticed it when changing the group avatar. Crashes everytime. Funny thing is, it crashes even if the change is made on the other device. 
As you can see in the screenshots, the avatar change is not fully recognized. 

![signal-2017-11-27-180653](https://user-images.githubusercontent.com/18451020/33279471-8b9900a0-d396-11e7-8ada-38e37f0f0f53.png)
![signal-2017-11-27-180705](https://user-images.githubusercontent.com/18451020/33279477-90ac9d5e-d396-11e7-8597-ca5578808939.png)
![signal-2017-11-27-180710](https://user-images.githubusercontent.com/18451020/33279481-93f08020-d396-11e7-8c72-e7e420a3ad5d.png)


Logs are from three different phones. 

https://gist.github.com/536d5534bcc5e8a839eb36a88d0f0f35
https://gist.github.com/6b9ef8d8d91a3ab3833e60439d11af26
https://gist.github.com/357a09ddb0d51efe9b175486bc7f3705

Thanks!

**Comment by lcouturier** [comment]
https://gist.github.com/5c8672f8fcbc4db2fe5abf3479321f24

**Comment by i7u** [comment]
@moxie0 how odd. Capturing the debug log was the first thing I did as soon I relaunched the app.
