### ISSUE TITLE
Can't send messages to people who stopped using Signal

### ISSUE THREAD

**Issue by The-Sushi** [WhisperSystems/Signal-Android#7228]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Attempting to send a message to someone who deleted the app causes the message to never get received.  Signal seems to be trying to send the message to the other Signal app, which has been deleted, so they never get it.  The app should have an option to switch to SMS/MMS, or should send it as SMS/MMS if the user has been offline for a long period of time, or if the message was not received after a long period of time

### Steps to reproduce
- Download Signal on two phones
- Begin an encrypted messaging session, and send some messages
- Delete the app on one phone
- Attempt to send a message using the Signal app to that phone

**Actual result:** The message is never received, and there is no option to switch to SMS/MMS
**Expected result:** There should be an option to switch to SMS/MMS, or it should resend as SMS/MMS if the user was offline for a long period of time, or if messages aren't received for a long period of time.

### Device info

**Device:** Xiaomi Mi A1
**Android version:** Nougat
**Signal version:** Unknown (not near my phone right now)

**Comment by moxie0** [comment]
Long-press the send button for an SMS option. Please try searching for duplicate issues before opening a new one, thanks!
