### ISSUE TITLE
[4.14.0] Some groups get default group avatar after upgrade.

### ISSUE THREAD

**Issue by bme13** [WhisperSystems/Signal-Android#7235]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After the upgrade to 4.14.0 two of my groups lost their custom avatar. They now have the default group avatar. This does not happen to all groups though. Although this is not a major issue to me I did create the attached logfile just after the upgrade. Hope this can help to get the upgrade as smooth as possible. 

### Steps to reproduce
- unable to do so.

**Actual result:** After the upgrade two groups lost their avatar.
**Expected result:** All groups should keep their avatar after the upgrade.

### Device info

**Device:** Samsung SM-G900F
**Android version:** 6.0.1
**Signal version:** 4.14.0

### Link to debug log

https://gist.github.com/anonymous/2127738b954266ae83a67eb60fcb2dc8

**Comment by FeuRenard** [comment]
Happened for my only group, too.

https://gist.github.com/e09a2d5c44a7de28b38f87a74e3723a0

**Comment by bme13** [comment]
Just having a thought about why some groups keep their avatar and some don't I think that for the groups that lost their custom avatar I was the one that set the avatar. For the groups that still have the custom avatar some other group member set the avatar.

**Comment by FeuRenard** [comment]
This guess would apply to my case. I was the one who set the avatar which got lost after upgrade.

**Comment by kpuljek** [comment]
I have a lot of group chats with the same people, and the only groups that lost avatars are the ones containing a certain person. I've set avatars for a lot of these, so it wasn't because I set them.
