### ISSUE TITLE
4.14: Crash when trying to take a picture in the app

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/Signal-Android#7237]
Long story short:

1. Tap attachment button
2. Tap Camera
3. Crash!

Moto G4
Android 7.0
Memclass: 192

https://gist.github.com/anonymous/fb27c304b4bda41516394cd99e2f1e47

**Comment by johanw666** [comment]
I can not reproduce this on a Sony Z3 compact with stock Android 6.0.1.

**Comment by halb9** [comment]
![signal-2017-12-01-171605](https://user-images.githubusercontent.com/18451020/33491837-588647ac-d6b3-11e7-9ed7-da9a4b628a37.png)

https://gist.github.com/cf53b52b108d456435bc13d869d4ddd7

**Comment by moxie0** [comment]
Looks like same root cause as #7234 (but separate instance of it), N targetSdk thing.
