### ISSUE TITLE
Please provide an option to remove the inane "Inbox zeeeerrro" content

### ISSUE THREAD

**Issue by Neurogami** [WhisperSystems/Signal-Android#7238]
When all messages have been read, a screen now appears that says "Inbox zeeerrro"[sic] followed by a picture from a children's book that looks like a shoe box with a face, and then the text "Zip, Zilch. ... You're all caught up!" 

Why?

Perhaps it's there by mistake.  What might seem seems cute the first few times can grow stale fast.

Please provide a way to just see a short, simple indication that there are no new messages.  

Perhaps "There are no new messages."

With the link for seeing archived messages.

**Comment by moxie0** [comment]
Thanks but we're not going to do this. In the future please don't delete the issue template.

**Comment by Neurogami** [comment]
I did not see how to submit this as a feature request, hence the deletion of the bug/issue template (since it's not a bug per se, just poor UI design).
