### ISSUE TITLE
crash when showing/opening SMS

### ISSUE THREAD

**Issue by pgerber** [WhisperSystems/Signal-Android#7239]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashes when showing an SMS.

### Steps to reproduce
I've observed a crash in these three scenarios:

a)
* receive an SMS
* click on notification to open it

b)
* open conversation list
* click on a contact with whom you communicate insecurely

c)
* open conversation list
* pick a contact with whom you communicate securely
* scroll up until you hit an insecure message

**Actual result:** Signal crashes
**Expected result:** no crash

### Device info

**Device:** Blackphone 2
**Android version:** 6.0.1
**Signal version:** 4.14.1

### Link to debug log
N/A (send a report instead)

**Comment by moxie0** [comment]
Thanks for being a beta tester @pgerber but I can't (ever) do anything without a debug log.

**Comment by FeuRenard** [comment]
https://gist.github.com/6e68f280c42dd82f578ba53c7a0c6ccc

Happens on selecting some (not all) sms only conversations. SMS are not enabled atm. Log should include 1-3 of these crashes.

Signal 4.14.0
Android 6.0.1

**Comment by moxie0** [comment]
Are these dual sim phones?

**Comment by pgerber** [comment]
@moxie, no single sim here.

Looks like phone permission (`READ_PHONE_STATE`) is needed to be enabled to read SMS. I disabled that permission yesterday because I assumed that just used for calls which I'm not using anyway. Now that Signal has the permission back, it works again.

[full log](https://gist.github.com/anonymous/a3edb4efb6bb19b066a7a691f6f87696)

**Comment by FeuRenard** [comment]
Mine is a dual sim phone, but I am only using one slot since I bought the phone.
