### ISSUE TITLE
Can't share from another app to group chat if not one of the 5 most recent conversations

### ISSUE THREAD

**Issue by rubin110** [WhisperSystems/Signal-Android#7240]
Pretty sure this is a dupe but I'm too tired to share and to annoyed that it's now difficult to share to my Bitmoji only group chat. 

With a recent update (4.13.6), there's now a new list of conversations that shows up when you're sharing content from another app. With the old behavior you got a list of conversations in order of last received/sent. In the new version you first get your to five last received/sent conversations, then a list of all your contacts.

If you would like to share this content with a group that isn't in your top 5, it will now show up in that following contacts list. You'll have to go and send a message to the group separately so that it then shows up in that list. 

Again I'm half asleep and slightly intoxicated. My apologies if this is a duplicate.

**Comment by FeuRenard** [comment]
Duplicate of #7202

**Comment by rubin110** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/8d70afe2-8030-4735-b895-076a9a91f1eb-4c3ce6ec-5f47-4c4a-acb3-bf1c6de44b2f-v1.png?transparent=1&palette=1&width=246)
