### ISSUE TITLE
[Regression in 4.13.6] New unread messages are no longer marked with bold font

### ISSUE THREAD

**Issue by Wikinaut** [WhisperSystems/Signal-Android#7241]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Unread messages were marked in bold in all previous versions.
This nice feature stopped (apparently) with version 4.13.6.

### Device info
**Device:** HUAWEI P8 LITE 2017
**Android version:** 7.0 (Secruriy patch level 20171005)
**Signal version:** 4.13.6

**Comment by p4nci** [comment]
I don't know if this was intended or not, but sometime is very hard to find unreaded threads.

imo, the blue marked unread indicator is lost in the big blue signal ocean:
![screenshot_unread-1](https://user-images.githubusercontent.com/16047081/33525649-503f0a20-d834-11e7-9267-935500520c73.png)

a) IMO, as proposed here in this issue: mark in bold all unreaded threads, is the simplest and best solution

b) make the unread indicator more visible (i.e. use another color):
![screenshot_unread-2](https://user-images.githubusercontent.com/16047081/33525672-d4089f2e-d834-11e7-8762-d0de808502f7.png)

c) move the unread indicator to avatars:
![screenshot_unread-3](https://user-images.githubusercontent.com/16047081/33525689-165a0660-d835-11e7-98c4-826ff23a44ff.png)

**Comment by moxie0** [comment]
This was intentional. Eventually we'll support bold text, in which case using bold to indicate something else won't make sense.

**Comment by Wikinaut** [comment]
@p4nci @moxie0 Solution c) above - move the indicator to the avatar - would be an improvement, I like very much.

In addition, I suggest to change the **background** of new unread messages to gray colour.

Should a new issue be filed for these suggestions?

**Comment by p4nci** [comment]
> Eventually we'll support bold text, in which case using bold to indicate something else won't make sense.

well, searching for unread threads (conversation) when you receive new messages is more common then a bold text in the first line of the message (and imo, it's only a preview of the message).

At least a **contact name in bold**, could be a big UI step forward:
1) (partially) restore the look & feel, 
2) don't conflict with possible bold text in the message
