### ISSUE TITLE
Fix back sign layer in All Images Section

### ISSUE THREAD

**Issue by FaizKhan5** [WhisperSystems/Signal-Android#7242]
have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Please fix back arrow sign layer in Conversation All Images Section it shows white dash full above media and documents. 

**Actual result:** big white dash above media and documents labels in All images Section 
**Expected result : back sign with All images Label like in previous versions 

### Device info
**Device:** huawei mate 10 lite
**Android version:** 7.0
**Signal version:** 4.14.1

**Comment by FeuRenard** [comment]
![screenshot_20171203-115923](https://user-images.githubusercontent.com/16167751/33524674-80a63106-d821-11e7-9ba9-1d5984ae20cb.png)

You mean this?

**Comment by FaizKhan5** [comment]
Yes

**Comment by FaizKhan5** [comment]
In Dark Theme Shows White Dash And You Post Image It Shows Black Dash.
