### ISSUE TITLE
[4.14.1] Signal crashes when trying to send sms without sms permissions.

### ISSUE THREAD

**Issue by bme13** [WhisperSystems/Signal-Android#7246]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I try to send an sms with the sms permissions disabled, Signal crashes. I'm not having sms enabled in Signal however by long pressing the paperclip icon in a conversation I can send an sms. Since 4.14 would support permissions I thought, let's disable the sms permissions for Signal and send an sms by long pressing the paperclip. As a result I got the message "Signal stopped" and it cannot be started again. I first had to enable the sms permissions before I was able to start Signal again.

### Steps to reproduce
- Disable sms permissions for Signal
- In a conversation long press the paperclip so you can send an unsecured sms
- Send unsecured sms message

**Actual result:** Signal crashes
**Expected result:** After selecting unsecured sms in a conversation I would expect Signal to request the sms permission and after excepting it I would be able to send an sms or if I denied it sms would not be possible.

### Device info

**Device:** Samsung SM-G900F
**Android version:** 6.0.1
**Signal version:** 4.14.1

### Link to debug log

logcat output:
12-04 13:44:28.219 14129 14144 W JobConsumer: java.lang.SecurityException: Sending SMS message: uid 10210 does not have android.permission.SEND_SMS.
12-04 13:44:28.219 14129 14144 W JobConsumer:   at android.os.Parcel.readException(Parcel.java:1620)
12-04 13:44:28.219 14129 14144 W JobConsumer:   at android.os.Parcel.readException(Parcel.java:1573)
12-04 13:44:28.219 14129 14144 W JobConsumer:   at com.android.internal.telephony.ISms$Stub$Proxy.sendTextForSubscriber(ISms.java:1577)
12-04 13:44:28.219 14129 14144 W JobConsumer:   at android.telephony.SmsManager.sendTextMessageInternal(SmsManager.java:380)
12-04 13:44:28.219 14129 14144 W JobConsumer:   at android.telephony.SmsManager.sendTextMessage(SmsManager.java:333)
12-04 13:44:28.219 14129 14144 W JobConsumer:   at android.telephony.SmsManager.sendMultipartTextMessageInternal(SmsManager.java:592)
12-04 13:44:28.219 14129 14144 W JobConsumer:   at android.telephony.SmsManager.sendMultipartTextMessage(SmsManager.java:544)
12-04 13:44:28.219 14129 14144 W JobConsumer:   at org.thoughtcrime.securesms.jobs.SmsSendJob.deliver(SmsSendJob.java:105)
12-04 13:44:28.219 14129 14144 W JobConsumer:   at org.thoughtcrime.securesms.jobs.SmsSendJob.onSend(SmsSendJob.java:52)
12-04 13:44:28.219 14129 14144 W JobConsumer:   at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:39)
12-04 13:44:28.219 14129 14144 W JobConsumer:   at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
12-04 13:44:28.219 14129 14144 W JobConsumer:   at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
12-04 13:44:28.219 14129 14144 W JobConsumer:   at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
12-04 13:44:28.219 14129 14144 E AndroidRuntime: FATAL EXCEPTION: JobConsumer-0

**Comment by moxie0** [comment]
Please always post a full debug log. Thanks for being a beta tester!

**Comment by bme13** [comment]
https://gist.github.com/anonymous/9b555e799a38f4220b10505ab1352b9e
Note that before I was able to create this debug log I first had to enable the sms permission again since otherwise Signal did not start.
