### ISSUE TITLE
signal keeps asking me to restart for update

### ISSUE THREAD

**Issue by lethargosapatheia** [WhisperSystems/Signal-Android#7248]
Today signal has asked me 6-7 times to restart in order to apply an update. It seems that nothing is happening, actually. I'm using the independent signal program on mac os high sierra.

Any ideas what's going on?

**Comment by jeremymasters** [comment]
If it's the desktop version you're talking about, you need to file the bug over [there](https://github.com/WhisperSystems/Signal-Desktop/issues)

**Comment by lethargosapatheia** [comment]
Sorry, I didn't pay attention. Thanks for the link.
