### ISSUE TITLE
Android app no longer able to send, link devices, or even deregister; only receives messages after reboot

### ISSUE THREAD

**Issue by keithzg** [WhisperSystems/Signal-Android#7249]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Android app is unable to send messages, open the "link devices" option in settings, or even deregister. Messages are received upon a reboot. Chrome app on desktop continues to work fine.

### Steps I took
 - Earlier today, everything was fine, and I was chatting away happily via my Android device. 
 - I then chatted a bit via the app on my desktop. Walked away from my computer and opened up the Android app again and tried to send a message, but it failed. Attempted to retry, and it failed again.
 - Went back to my computer, and sent a message via the desktop. It was received fine. Got a reply as well. Everything seemed fine from the desktop perspective, but none of the messages were received on my phone.
 - Attempted to open the "linked devices" list and I get a "Network connection failed" error dialog.
 - Attempted to deregister the device, as per https://support.signal.org/hc/en-us/articles/216948747-What-do-I-do-if-I-see-Network-connection-failed-,  and I get "Error connecting to server!" popping up in the middle-bottom of the screen briefly.
 - Rebooted phone, opened Signal, and the intervening messages all were delivered. Repeated above steps and no messages arrived on my phone and none could be sent.

**Actual result:** The Android app only receives messages after a reboot, and cannot send messages, manage linked devices, or deregister.
**Expected result:** The Android app should be able to send and receive messages normally, open and manage the list of linked devices, and deregister if desired.

**Note:** I'm "still" using the Chrome app on this desktop, having never migrated because the standalone app's GTK usage doesn't play well with my KDE theme or DPI settings. I do have the standalone app installed on another desktop PC (which is how I became aware of the GTK-related problems), and the Chrome app configured on a ChromeOS laptop (which obviously couldn't run the standalone app even if I wanted to there), but I haven't had a chance yet to see if they are also still working.

### Device info

**Device:** Google Pixel XL (marlin)
**Android version:** 8.0.0
**Signal version:** 4.13.6 (from Play Store)

### Link to debug log
https://gist.github.com/anonymous/fc26f282c52288f71392732eb86410f4

**Comment by keithzg** [comment]
Just rebooted again, and this time I did *not* receive the message backlog. Attempted again to send a message, which again failed. Second debug log created immediately after this: https://gist.github.com/bd59bcffe19fca231defb9c84be42f3f

**Comment by keithzg** [comment]
Well now that's interesting, disconnected from wifi and now it's working fine. Looking at the debug logs, is it too paranoid to think that the router might have been compromised and trying to MITM somehow? There doesn't seem to be anything wrong with other SSL connections via browsers on my phone, but I guess if one is being paranoid it wouldn't be a bad plan to only try and intercept certain traffic . . .

**Comment by moxie0** [comment]
Something on your network is modifying the TLS certificate. Could be a captive portal or anything else.

**Comment by johanw666** [comment]
Maybe a virus scanner that does a man in the middle attack on encrypted connections to scan them?

**Comment by keithzg** [comment]
> Maybe a virus scanner that does a man in the middle attack on encrypted connections to scan them?
Maybe? Certainly nothing like that is _supposed_ to be installed with the Tomato firmware (this is in fact a router I have nominal control over, at my work; it's an ASUS RT-N66U running Tomato that I've now taken offline for the time being), and it's intriguing that other SSL traffic at least doesn't _appear_ to be affected---certainly Chrome on Android wasn't giving me any complaints. This same router worked fine until recently, so something changed somewhere.
