### ISSUE TITLE
Add an option to hide "A new version of Signal..."

### ISSUE THREAD

**Issue by tezeb** [WhisperSystems/Signal-Android#7250]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After recent problem with new version of Signal (#7171), I had to downgrade. Since then I had a permanent notification of pending update, which was quite inconvenient, as on locked screen it looks exactly the same as a new message. It would be great if there will be a way to disable update notification.

Regarding the self-updates notification I wonder about what has changed since #127, where @moxie0  commented that distributing apk only through Play:

> does not encourage the average user to tick "allow 3rd party APKs" in Android settings.

and now Signal updates requires exactly that?

### Steps to reproduce
- Install older version of Signal
- View the update notification
- Lock screen(with option to hide notification contents)

**Comment by moxie0** [comment]
Your problem (#7171) is with a bug in CM, not Signal.  We're not going to remove the pending update notification, and if you're asking for the ability to install Signal outside of Play but not enable third party APKs, that's not possible.

**Comment by tezeb** [comment]
I do know what my problem with Signal update is - that's why I linked to it in my comment, but thank you for pointing it out anyway.
I also have another problem(with so called UX), that's why I created this issue. What I ask for is an option to hide pending update notification(ie. so it pops out once per release and user can hide it). Alternatively update notification looks might be changed, so that it differs from a new message notification. Having both look the same is super annoying when you have to unlock phone each time just to recall that there is a pending update of Signal. Even more so, when you are not able to update for some reason(lack of internet or a bug in newer version).

Regarding the third party APKs, I am not asking for whatever you understood and sorry if my comment was not clear enough. I am asking why Signal has changed it's delivery model? It used to be delivered via Play, but now with "self-update" feature it requires user to allow for installation of third party APKs. You, @moxie0, were exactly against this behaviour(aka. "allow 3rd party APKs") in #127, but now it is Signal's default. It is inconsistent, so I would like to get the reasoning?

To be clear(because maybe it happens only on my phone?) when I click Signal update notification it asks me to allow 3rd party APKs installation, which is teaching users bad habits. I also do understand that it's impossible to do self-updates without this option, which brings back the question:
Why have Signal team added self-update feature instead of using Play-market, which was such a great solution back then?

**Comment by Trolldemorted** [comment]
Sideloading signal's apk is not signal's default.

It is only supposed to happen on systems that have no gapps installed, because on those the playstore is not there and signal has to update itself.

**Comment by moxie0** [comment]
It sounds like you installed an APK off the website, so you're running a non-play version of the app. There is a huge warning urging you not to do that and to install through the play store instead.

**Comment by tezeb** [comment]
Thanks for you patience and explanation - it's my mistake. I was always installing from Play market, but as I had to downgrade I did it via adb. As the downgrade was to newer version than I had previously I thought that those notifications are a new feature.

**Comment by johanw666** [comment]
These notifications arise only from the Website version, so if you download a Playstore version apk from a site like apkmirror you should not have those notifications.
