### ISSUE TITLE
Intrusive & confusing notifications on Android 8.1 without Google Play Services

### ISSUE THREAD

**Issue by milesmcc** [WhisperSystems/Signal-Android#7255]
I have:
- [X] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
On devices without Google Play Services, Signal creates a notification to inform the user that a background connection has been established to the Signal servers. On earlier versions of Android (pre 8.1), this notification was present but low priority, and therefore did not have an icon in the status bar and did not show up on the lock screen. It only was visible in the expanded notification drawer.

On Android 8.1, however, the background connection notification is visible in both the status bar and the lock screen notification view. Furthermore, it uses the same icon as incoming Signal messages, creating the effect that a message notification is always present and causing user confusion. (See annotated screenshots.)

### Steps to reproduce
- run Signal on a device running Android 8.1 without Google Play Services
- look at the lock screen or status bar

**Actual result:** background connection notification is shown in the status bar and lock screen.
**Expected result:** background connection notification should only be shown in the notification drawer, and the Signal icon should not be present, per previous versions.

### Screenshots
Standard usage of the device, without any dismissable message notifications. (The icon in the status bar is from the background connection notification.)
![screenshot_20171207-232132](https://user-images.githubusercontent.com/3037552/33751266-be67a59a-dba7-11e7-9d08-d03c1f44aad3.png)

Standard usage of the device, with an undismissed notification. Note how two Signal icons are present in the status bar, one from the message and the other from the background connection notification.
![screenshot_20171207-232226](https://user-images.githubusercontent.com/3037552/33751284-dc1cc318-dba7-11e7-9193-91216ddc5194.png)

The expanded notification drawer.
![screenshot_20171207-232236](https://user-images.githubusercontent.com/3037552/33751300-045ed41a-dba8-11e7-8eb1-4998c09aee97.png)

_(Irrelevant sections of screenshots removed for privacy.)_

### Device info
**Device:** Google Pixel
**Android version:** 8.1.0 (without Google Play Services; running CopperheadOS, like raw AOSP)
**Signal version:** 4.13.6

**Comment by moxie0** [comment]
I don't think there's anything we can do about this. Android is going to make it more and more difficult to accomplish what you want, I expect the end game will be making background connections entirely impossible.

**Comment by bungabunga** [comment]
@milesmcc try this app and see if it help you: 
https://play.google.com/store/apps/details?id=com.iboalali.sysnotifsnooze

**Comment by milesmcc** [comment]
@moxie0 would it be possible to change the background connection notification _icon_ to something different, so that message notifications can be easily distinguished?

(I suppose this assault by Google on background processes is yet another way for them to kill the usefulness of AOSP w/out Google Play Services...)

**Comment by sigenc** [comment]
I had the same problem. Just go to settings > notifications > Show System > Turn off "Apps consuming battery"

**Comment by milesmcc** [comment]
@sigenc this fix removes the 'Apps using battery' notification, but I don't think it affects the 'Signal / Background connection enabled' notification. Perhaps I'm misunderstanding?

**Comment by pushcx** [comment]
@sigenc @milesmcc Correct, unfortunately. It turns off Android's notification but leaves the one from Signal. There are no notification control apps like @bungabunga available in F-Droid, so that's not an option without Google Play Services, either.
