### ISSUE TITLE
Cannot Start App

### ISSUE THREAD

**Issue by Adrianteri** [WhisperSystems/Signal-Android#7256]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

I don't have any log for this crash ...

Android Version - 5.1.1
Signal Version - 4.14.3

**Comment by moxie0** [comment]
Hey @Adrianteri sorry you're having problems, but I can't do anything without a debug log.

**Comment by Adrianteri** [comment]
Thanks ....
