### ISSUE TITLE
Pictures sent from Nokia 5 get heavily scaled down (13MP -> 3MP)

### ISSUE THREAD

**Issue by fncnt** [WhisperSystems/Signal-Android#7263]
I have:
- [x] searched open and closed issues for duplicates (searched for "compression", "regression", "nokia 5" and "resolution")
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I have 2 contacts using a Nokia 5 by HMD Global. When they send me full resolution (13 MP) pictures made with their smartphones, I receive scaled down pictures (approximately 3 MP). Other contacts (using iPhones with 12MP-Cameras) can send pictures that I receive just as they were shot in terms of resolution.
All pictures were sent via data (not MMS).
Let me know if there's additional information that I forgot to include. Thanks!

### Steps to reproduce
- find contacts using a Nokia 5
- Make them send you a 13MP-picture made with their smartphone (i.e. their camera app)
- Make them capture and send the debug log
- receive picture and save to device
- check the details of the received picture.

**Actual result:** The received picture has a resolution of approximately 3 MP
**Expected result:** The received picture shouldn't have been scaled down that much. Ideally, it would have the same resolution as it was shot.

### Screenshots

Sender's side:
![Resolution and size of the picture that got sent.](https://user-images.githubusercontent.com/7197813/33827389-7ce2e350-de68-11e7-9bdc-b388f7a48efb.png)
Receiver's side:
![Resolution and size of the picture that I received.](https://user-images.githubusercontent.com/7197813/33827439-a1b59e16-de68-11e7-8816-5c66103be267.png)

### Device info

Sending Device:
**Device:** HMD Global TA-1053 (TA-1053_00WW)
**Android version:** 7.1.2 (00WW_3_72A, 00WW_3_72A)
**Signal version:** 4.13.6

Receiving Device:
**Device:** motorola MotoE2 (4G-LTE) (surnia_retde)
**Android version:** 6.0 (3, MPI24.65-39-4)
**Signal version:** 4.13.6

It appears that the issue is still present on Signal 4.14.4. I'm willing to provide more recent debug logs if necessary.

### Link to debug log
Contact 1:
https://gist.github.com/anonymous/11a015c6447ad754149f2b1609a6a6f4
Contact 2:
https://gist.github.com/anonymous/67939cb7e210fcfee7843d609b242368

**Comment by johanw666** [comment]
That's a feature, not a bug. Sent pictures should be even smaller IMO, more like the compression WhatsApp uses, and just as with WA send them as documents if you don't want any compression.

**Comment by fncnt** [comment]
@johanw666 Yeah, I understand that. It's just that 12MP or 8MP pictures from other contacts don't get scaled down at all. Basically, I was wondering why those 13MP pictures got scaled down to 3 MP.
I figured that could have been a regression...

**Comment by Dyras** [comment]
I like the way Telegram handles this. When you try to send a picture it asks you if you want to compress it or not. When I sit at home on my WiFi I really don't mind 20 megabyte pictures but on 3G that's a no-no. Maybe an option in the settings would be the best way of handling it?

Compress images [X]
* Only compress images on 3G [X]

**Comment by fncnt** [comment]
I don't think this should become a discussion about the way Signal handles compression. There have been enough issues covering that topic.

If the reduction from 13 MP to 3 MP is intended in contrary to uncompressed 12 MP pictures from other contacts, that's fine. It's just not what I have expected. In that case, I'll close the issue.

**Comment by johanw666** [comment]
@Dyras I don't care about wifi or 3/4G, my wifi is usually worse than 3/4G anyway, but about storage space.

**Comment by FaizKhan5** [comment]
No its not a intended behavior cause there is no option of compression in signal.

**Comment by johanw666** [comment]
No option does not mean it is not intended. The compression code is there, compression has even been reduced in the past so it's certainly intended.

**Comment by FaizKhan5** [comment]
Then I think there should be an option for that.

**Comment by fncnt** [comment]
Just received a picture from contact 2. He's still using `4.13.6` (I'm on `4.14.8` now) but the picture only got scaled down to 8.3 MP this time. So I'm closing this issue.
