### ISSUE TITLE
[Feature Request] Using Signal offline.

### ISSUE THREAD

**Issue by JetBitz01** [WhisperSystems/Signal-Android#7264]
Signal offers an offline SMS service, however, when the recipient has a Signal account, I can only send encrypted messages through a WiFi network. It would be preferable if I can still send offline even if there is no encryption. Probably adding a warning might help. This is an issue as Signal will replace the current SMS app to be the default one.

**Comment by moxie0** [comment]
Signal can send neither SMS nor Signal messages if there is no network connection. If there is a cell service connection but no data, Signal can send SMS. If you're asking for Signal to automatically fall back to unencrypted SMS when there is no data connection but there is a cell service connection, we're not going to do that. If I've misunderstood your request please feel free to reopen. In the future please try not to delete the issue template, thanks!

**Comment by JetBitz01** [comment]
Hi, why is this so as it is cumbersome to have to change to another SMS app if I am not connected to any WiFi network

**Comment by mawed** [comment]
Long-pressing the arrow allows to send SMS.

**Comment by JetBitz01** [comment]
@mawed Thanks very much
