### ISSUE TITLE
Change notifications' sound in general settings is useless.

### ISSUE THREAD

**Issue by freeroot** [WhisperSystems/Signal-Android#7265]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When you change notifications' sound in general settings, it doesn't change notifications' sound in contacts' settings. So you must change sound for each contacts which is very long and boring. In other terms, general setting for notifications' sound works only for new contact, not for contact already there.

### Steps to reproduce
- change notifications' sound in general settings
- no notifications' sound is changed

**Actual result:**
Change notifications' sound in general settings is useless.
**Expected result:**
Change notifications' sound in general settings is usefull : 
· Either overwriting automatically each contacts' setting
· Either overwriting each contacts' setting after asking user
· Either overwriting contacts' setting of contacts selected by user during asking user
· Something else

### Device info

**Device:** Samsung A5 2017
**Android version:** 7.0
**Signal version:** 4.14.4

**Comment by moxie0** [comment]
Can you post steps to reproduce? I just tried:

1) Installing Signal
2) Receiving a message from Alice. Heard the default notification sound.
3) Changing the notification sound in Settings.
4) Receiving a second message from Alice. Heard the new notification sound.

**Comment by freeroot** [comment]
1. Changing the notification sound in Alice Settings.
2. Receiving a message from Alice. Heard the new notification sound.
3. Changing the notification sound in General Settings.
4. Receiving a second message from Alice. Don't heard the new notification sound, still the notification sound of Alice settings.

I looks like good because Alice specific settings are keeped but general settings is become useless. When you have many contacts to manage, it's a shame.

**Comment by moxie0** [comment]
That sounds like the intended behavior. If you set a custom sound for a contact, that's the sound that's used. It would only be a lot of work to manage across many contacts if you set a custom sound across many contacts, in which case presumably you want to hear custom sounds for each of those contacts.
