### ISSUE TITLE
Notification default sound is call default sound of android

### ISSUE THREAD

**Issue by freeroot** [WhisperSystems/Signal-Android#7266]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
In settings or contact settings, notification sound set to default will play call sound of android, neither notification sound of android nor notification sound of signal. I think that someone call me every time I receive a sms/mms.

### Steps to reproduce
1. Open settings
2. Set notification sound to default
OR
1. Open contact settings
2. Set notification sound to default

**Actual result:** When default is selected for notification, play call sound of android for sms/mms.
**Expected result:** When default is selected for notification, play notification sound of android or signal for sms/mms.

### Screenshots

**Contact settings**
![screenshot_20171212-130324](https://user-images.githubusercontent.com/20989929/33884012-56516e74-df3e-11e7-8eb2-33942b9cf35a.png)
**Signal settings**
![screenshot_20171212-130343](https://user-images.githubusercontent.com/20989929/33884013-581eae06-df3e-11e7-94ef-350528e8ffae.png)
**Android sound settings**
![screenshot_20171212-130354](https://user-images.githubusercontent.com/20989929/33884017-59c6a498-df3e-11e7-8d94-d0d7f49bede1.png)
**Android notification sound settings**
![screenshot_20171212-130359](https://user-images.githubusercontent.com/20989929/33884019-5cfebdd0-df3e-11e7-8d00-bdb920b09ee8.png)

### Device info

**Device:** Samsung A5 2017
**Android version:** 7.0
**Signal version:** 4.14.4

**Comment by moxie0** [comment]
I'm unable to reproduce this, we're using the system notification picker so this sounds like an OS issue.

**Comment by freeroot** [comment]
Ok, thanks for you answers.

**Comment by freeroot** [comment]
Fixed by 4acedd2a4b962e2fa84bb8848c88b84350a762c7
