### ISSUE TITLE
FR: Integrated keyboard input (Google Keyboard spying?)

### ISSUE THREAD

**Issue by ThoughtPhotography** [WhisperSystems/Signal-Android#7277]
This may sound (and even be) overly paranoid, but the most advanced encryption in the world is meaningless if using an input method like Google Keyboard, with system-wide microphone access and other permissions.

Tonight I had Signal open while watching a discussion on vegetarianism and magically I had a msg populated with "I would die I was sick of being hungry I was sick of beans and rice".

I DID NOT write this, or ever discuss this topic with the contact.

Perhaps it's just a random coincidence, but it sounds quite a bit like the endless reports alleging Facebook listening in and serving ads based on ambient audio. Regardless if it's a real security concern, it could be a potential one,.

A few ideas:
1) Have the option for Signal to use it's own built in keyboard, similar to those meant to circumvent keyloggers.

2) There are apps like Microphone Block and Camera Block for Android which disable the microphone and camera on a system wide basis.

Replicating this functionality in Signal for a "Get Smart: Super Paranoia Cone of Silence Mode" would be a great addition for those that trust Signal/OWS, but maybe not Google Keyboard/Android.

This still obviously isn't a 100% guarantee, but could help shift the balance  from ubiquitous surveillance to highly targeted surveillance (where it should be, and all we can realistically hope for)...

**Comment by milesmcc** [comment]
`[Tinfoil](https://en.wikipedia.org/wiki/Tin_foil_hat) mode` — sounds like a great idea.

I wonder if this is a conversation more appropriate for the [community forum](https://whispersystems.discoursehosting.net/) to discuss?

**Comment by moxie0** [comment]
You're free to use whatever keyboard you'd like with Signal, but we don't have any control over the OS.
