### ISSUE TITLE
Android 7.1.2 without g-apps problem call

### ISSUE THREAD

**Issue by MarkTomson** [WhisperSystems/Signal-Android#7282]
I use android 7.1.2 without google apps and I'm having big problems using signal calls. Every time I try to make a call with another person with a signal, the call starts and shortly after the call drops and says a lost call. I do not understand how to solve.
Maybe with micro-g?

**Comment by haffenloher** [comment]
Please don't delete the issue template and always include a debug log when opening an issue.

**Comment by moxie0** [comment]
Closing for lack of information
