### ISSUE TITLE
Cannot receive images

### ISSUE THREAD

**Issue by coopchange** [WhisperSystems/Signal-Android#7286]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Cannot receive image. Signal is set as my primary messaging app. Received the image (twice) from a contact who used Signal on iOS. Have received images from this person before

### Steps to reproduce
- have someone send me an image via Signal (on iOS) [_did this twice_]
- click on the download image button ("[download-symbol]  Image")

**Actual result:** The loading wheel begins to spin but then disappears, leaving the rounded rectangle button (the dark green field within the received-text-field) blank
**Expected result:** Image should appear.

I've received images from this person before, but I can't correlate this change in behavior to any change with the phone or their phone.

### Screenshots
Signal won't let me take a screenshot

### Device info

**Device:** HTC HTC6535LVW (HTCOneM9vzw)
**Android version:** 7.0 (947620.11, NRD90M release-keys)
**Signal version:** 4.13.6

### Link to debug log
https://gist.github.com/c304923ba40cc8c6f5301bbd2564d168

**Comment by moxie0** [comment]
Your contact is running a version of Signal that's more than 6 months out of date. Once they update everything should work fine.
