### ISSUE TITLE
For over-the-shoulder secrecy, manual option to move conversations to bottom

### ISSUE THREAD

**Issue by nitrocode** [WhisperSystems/Signal-Android#7289]
For over-the-shoulder secrecy

* manual option to move conversations to bottom (including when a new message arrives)
* or hide conversations for a specific time

**Comment by moxie0** [comment]
Thanks but we're not going to do this. In the future please try not to delete the issue template, thanks!

**Comment by nitrocode** [comment]
@moxie0 any reason to not implement this? no time?

would you accept a PR?

Also the template seemed specific for bugs and not really for requests... but I can re-add it.
