### ISSUE TITLE
Crash! Cannot open signal when internet is connected

### ISSUE THREAD

**Issue by las2mile** [WhisperSystems/Signal-Android#7290]
I have:
- [x] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Crashes while opening signal when internet is connected.
Can open signal in airplane mode but crashes when opening conversation.

### Steps to reproduce.
- Send any signal message to any contact
- before the message is sent, cellular network is lost
- signal keeps trying to send the message
- killed signal app
- network is back
- opened signal and crash

**Actual result:**  Crash
**Expected result:** Signal should work fine

### Device info

**Device:** LG nexus 5
**Android version:** 7.1.2 ( no play services)
**Signal version:** 4.14.8

### Link to debug log
https://gist.github.com/e6ad1a93264564b87ef6e5f666c41585

Note: Debug log taken after deleting the top conversation by opening signal keeping phone in airplane mode.

**Comment by moxie0** [comment]
Looks like a segfault, so probably a custom ROM issue.
