### ISSUE TITLE
No notification without pull

### ISSUE THREAD

**Issue by Lu7sodaa** [WhisperSystems/Signal-Android#7295]
I have:
- [ ] searched open and closed issues for duplicates
- [ ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Since the update of Android. I don't receive any more notifications (apart from pull), and I can't send sms from the app. 

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Huawei P8Lite2017
**Android version:** 7.0
**Signal version:** 4.13.6

**Comment by moxie0** [comment]
Sorry @Lu7sodaa , but "it doesn't work" isn't enough for us to diagnose or fix a problem. We would need more information, along with steps to reproduce. You might try checking out the support center for related content, thanks!
