### ISSUE TITLE
Using without GMS

### ISSUE THREAD

**Issue by stemy2** [WhisperSystems/Signal-Android#7296]
Hello,

One of my friends have some technical problems with Google Play Services, so he can't register his phone number in the Signal app without having an error message from the Google Services. Personnaly, i use signal with a custom rom without GMS, and strangely, i didn't have problems to register (but i didn't tried the voip service with anybody).

So it would be cool if you be cool if you develop a version wich would work without GMS for privacy- aware users.

Thanks

P.s.: To describe briefly my fried's problem, the recovery code that google sends to him never works and is always considered as incorrect, and i don't know why.

**Comment by moxie0** [comment]
This is represented by existing issues, please try not to delete the issue template in the future and check for duplicates. Thanks!
