### ISSUE TITLE
After update Signal does not display contacts names

### ISSUE THREAD

**Issue by tezeb** [WhisperSystems/Signal-Android#7298]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
After updating from Signal 4.11.5 to 4.14.10, when opened, Signal did not displayed contact names in the messages view(nor in single message view). Instead it displays numbers and all in gray. Signal groups(and colors set in Signal) are kept with name.

### Steps to reproduce
- Update Signal
- Open Signal
- Wait for DB to be updated
- Even after reboot or app restart messages are displayed with number instead of name

**Actual result:** Numbers are displayed instead of names
**Expected result:** Names as in contact list shall be visible.

### Workaround
After clicking "new message"(round blue icon with pen) and waiting few minutes(it seems way too long for loading ~100 contacts), the contacts list gets populated(the view seems to get updated only when scrolling). I might have also "pulled down" the list, which seems to refresh it from contacts. Going back to messages view shows contacts properly.

### Device info
**Android version:** 5.1.1
**Signal version:** 14.4.10

**Comment by moxie0** [comment]
Can't do anything without a debug log. Please reopen when you have one.

**Comment by tezeb** [comment]
https://gist.github.com/361ecb6eb324ff6f070f6456468ae067

I hope it contains all relevent information.

**Comment by m-schaub** [comment]
Another debug log. Same issue.
https://gist.github.com/100a115a8d379cc2c4af004b3d2eb7b1

Workaround did not work for me.
