### ISSUE TITLE
Disable (or at least add an option to disable) separation of Signal vs non-Signal users in Contacts list

### ISSUE THREAD

**Issue by tezeb** [WhisperSystems/Signal-Android#7299]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When creating new message and looking for the contact, user has to search first in alphabetically sorted list of Signal-using contacts and then in alphabetically sorted list of non-Signal-using contacts to find a non-Signal-using recipient. Assuming you don't know if your recipient is using Signal(why should one even care) it adds unnecessary overhead for searching.
When using Signal as default SMS app, this results in clunky UX.

### Steps to reproduce
- press round blue icon with pen
- contacts are sorted by those using Signal and those not using it

**Actual result:** Contacts are separated into Signal and non-Signal.
**Expected result:** Contacts are sorted alphabetically only(or there is an option to enable this).

### Device info
**Android version:** 5.1.1
**Signal version:** 14.4.10

**Comment by moxie0** [comment]
Thanks but we're not going to do this.

**Comment by tezeb** [comment]
May I ask what is the reason behind this?
I may be oldschool but it seems unintuitive to force users to scroll through two alphabets.
Will pull-request with such feature be approved?
