### ISSUE TITLE
Standalone apk updates lack behind google play updates

### ISSUE THREAD

**Issue by hasufell** [WhisperSystems/Signal-Android#7306]
Latest standalone apk is [4.13.7](https://signal.org/android/apk/) which is a ~month old. Is there a problem with the release workflow?

**Comment by moxie0** [comment]
This is intentional. Please don't delete the issue template when opening issues in the future, thanks.

**Comment by T-vK** [comment]
What is the reason for this?

**Comment by hasufell** [comment]
@T-vK don't delete the issue template...
