### ISSUE TITLE
Incoming call button jumping up and down rapidly when Animator duration scale is set to off in Android developer options on the phone

### ISSUE THREAD

**Issue by eggsgent** [WhisperSystems/Signal-Android#7318]
[output_20180104_220335_cut (Encoded).zip](https://github.com/WhisperSystems/Signal-Android/files/1604728/output_20180104_220335_cut.Encoded.zip)
I have:
- [ y] searched open and closed issues for duplicates
- [ n] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Incoming call button jumping rapidly up and down, very hard to accept the call

### Steps to reproduce
- Set Animator duration scale to off in Android developer options in phone settings
- Receive an incoming voice call from a contact
- Inspect phone screen, check that the answer call button can be dragged up

**Actual result:** 
Incoming call button jumping rapidly up and down, very hard to accept the call

**Expected result:** 
The button to either slowly move up and down or stay put and show an arrow up to invite to a drag up movement to answer the call

### Device info
**Device:** Samsung G930F
**Android version:** 7.0
**Signal version:** 4.14.10 (issue started to appear in regular release channel, so switched to beta)

### Link to debug log
https://gist.github.com/anonymous/82edd086e0a385af56e2028ac4f3a77a

**Comment by moxie0** [comment]
You'll have to qualify what you mean by "rapid." It currently moves at the same rate as the default Android dial screen, but it's possible that there's an OS bug on your device. A video would be helpful.

**Comment by eggsgent** [comment]
I've reset the app on my device without change. Same app version does not show this error on two other Samsung G930F units with the same software version. I'll provide a video.

**Comment by eggsgent** [comment]
Also checked that it is not related to text & icon size set on the device nor related to the launcher being used. I'll check if the disabled animations in Dev settings might be relevant. Otherwise I'm out of ideas at the moment.

**Comment by eggsgent** [comment]
Found the issue trigger:

1. On the phone, go to Settings > Developer options and set the Animator duration scale to off
2. Receive incoming voice call in Signal

Actual result: jumping Answer button

**Comment by nrizzio** [comment]
I'm pretty sure that's literally what the setting is intended to do - to cause the duration of animations to be zero. I don't think that's a bug in Signal, everything appears to be working as intended.

**Comment by eggsgent** [comment]
I disagree, Signal UI should be able to handle the case where user turns UI animations off, all my other messaging apps handle this gracefully: Hangouts, Whatsapp, phone dialer app etc.

**Comment by moxie0** [comment]
Hah, no if you tweak the *developer* options to short-circuit animation durations, we're not going to deal with working around that. Those options are hidden, and designed for developers to be able to debug their animations.

**Comment by eggsgent** [comment]
So because a bug appears in a corner case, it's an instant wontfix? I'm disappointed. 
It is not about working around turned off animations, it is about handing this use case in a proper manner.

**Comment by moxie0** [comment]
If this disappoints you, prepare yourself for a very long life of disappointment. This is not a "use case," if it works in other apps I guarantee it's an accident.

**Comment by eggsgent** [comment]
There is nothing wrong with disappointment. Ignorant and arrogant devs usually disappoint me, because I keep having hope and care about the human made products I work with and use. 

The use case is a device where animations are turned off globally. Any app should be able to present a coherent UI without animations.

**Comment by WajdiMuh** [comment]
U could use hidden sdk api and set duration scale to 1 or u can use reflect
Like this
Get duration scale from the global settings.

float durationScale = Settings.Global.getFloat(context.getContentResolver(),
                        Settings.Global.ANIMATOR_DURATION_SCALE, 0);

// If global duration scale is not 1 (default), try to override it
// for the current application.
if (durationScale != 1) {
  try {
    ValueAnimator.class.getMethod("setDurationScale", float.class).invoke(null, 1f);
    durationScale = 1f;
  } catch (Throwable t) {
    // It means something bad happened, and animations are still
    // altered by the global settings. You should warn the user and
    // exit application.
  }
}
