### ISSUE TITLE
Out-of-date prekeys

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/Signal-Android#7319]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
This issue contains various examples for badly encrypted messages which are per @scottnonnenberg most likely caused by a Signal Android bug that produces out-of-date prekeys.

For the full discussion including Scott's comments, see here:
https://github.com/WhisperSystems/Signal-Desktop/issues/1930

**Example 1:**

One of those cases is decribed in [issue 7154](https://github.com/WhisperSystems/Signal-Android/issues/7154), and as "luck" has it, I've just experienced this again a couple of minutes ago.

My Android device and Signal Desktop had been successfully linked for several months now, but as I switched to a newly set up installation of Windows, I had to install Sigal Desktop again and re-link it to my phone.

So what I've done is

1. Installed Signal Desktop v1.1 on Windows
2. Deleted the the old link (from the prior Windows installation) from Signal Android
3. Went through the linking procedure on Signal Desktop & Signal Android (scanning QR code, etc)

And bam - I've received 2 badly encrypted messages from my own phone number on Signal Android. As expected, Signal Desktop didn't sync anything. It looks finished, but there are no contacts available.

I haven't done so yet, but I know from experience that I can remedy this situation by resetting the secure session with my own phone number. [I later did, and resetting the secure fixed the problem]

**Example 2:**

I have a friend with whom I've successfully communicated via Signal Android & Desktop (me) & iOS (him) for many months. But a week or so ago, I've installed and configured Signal Desktop (v1.1) on his notebook for the very first time. At first, all seemed well.

But from that very point in time on, I suddenly only received badly encrypted messages from him. Namely I received only badly encrypted messages from him independently from the device he was using. I've received badly encrypted messages from him when he used his newly installed Signal Desktop, and I've received badly encrypted messages from him when he was using Signal iOS (which used to work without problems before linking it to Signal Desktop).

Interestingly, this only happened when he communicated with me, but not when he communicated with other contacts.

Again, I've had to reset the secure session with him AND send him a message afterwards (only resetting didn't do the trick) in order to fix it.

So I've definitely had my share of issues that could only be fixed by resetting the secure session. I've had this happen on completely different devices and addtionally, I've done clean installs of Signal on a fairly regular basis, so it's not some fucked up installation. ~~My guess is that Signal Desktop is somehow bugged in that regard.~~

*Update 2018-01-03*

**Example 3:**

A contact of mine installed & set up Signal Android for the very first time (in her life) and directly after that sent me a message (also her very first Signal message to anyone ever). I've received that message as badly encrypted on Signal Android, **but it is readable on Signal Desktop**. See debug log for example 3.

### Steps to reproduce
See above

### Screenshots
N/A

### Device info

**Device:** LG Nexus 5X
**Android version:** 8.1.0
**Signal version:** 4.14.10

### Link to debug log

Logs for example 1:

Signal Android:
https://gist.github.com/anonymous/b0edc4bdb4251c36cd7e2bc63c3c60c9

Signal Desktop:
https://gist.github.com/8c8cc81e6231576136388a63dcf984f2

Logs for example 3:

Signal Android:
https://gist.github.com/anonymous/c5c5b688503ea54cd7555dcc73438f9f

**Comment by moxie0** [comment]
@RiseT Looks to me like the messages desktop is sending are malformed, do you happen to have root on your device? Also would you be willing to email me your phone number at moxie+github@whispersystems.org?

**Comment by RiseT** [comment]
@moxie0 No root on my current phone, but I can email you my phone number. So does the latter make sense without root?

**Comment by moxie0** [comment]
Thanks, looks like the prekey id the desktop instance used is fairly behind. Let's make the desktop issue the canonical issue for this.
