### ISSUE TITLE
disappearing messages with 1 Month

### ISSUE THREAD

**Issue by derDieDasJojo** [WhisperSystems/Signal-Android#7324]
Disappearing Messages are great. But sometimes information is relevant for more than a Week but
should still disappear after a while. It would be great to also have the possibility to configure
disappearing messages to stay 1 Month

**Comment by Dyras** [comment]
Adding more times was up before, but it seems Moxie doesn't want to do it: https://github.com/WhisperSystems/Signal-Android/pull/6814#issuecomment-327033465

**Comment by moxie0** [comment]
Please don't delete the issue template in the future.
