### ISSUE TITLE
Media preview: screen gets stuck between two images (incomplete slide change)

### ISSUE THREAD

**Issue by PiCob** [WhisperSystems/Signal-Android#7332]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When using the new swipe gesture to switch between media (especially when doing this quickly over and over), the slide change sometimes "stops"/ends between two images (see screenshot below)

### Steps to reproduce
- open media preview gallery
- swipe left/right several times (quickly)

**Actual result:** Change to previous/next media isn't performed completely (at least it looks like that), part of the former image is still visible
**Expected result:** Previous media is hidden and next one is shown completely

### Screenshot:
![screenshot_20180110-043652](https://user-images.githubusercontent.com/23237468/34754819-762aba78-f5c0-11e7-9a4c-108fc5a77469.png)

### Device info
**Device:** Lenovo Moto G 4 Plus (other devices as well)
**Android version:** 7.0 (Android 4.4 as well)
**Signal version:** 4.15.0

### Link to debug log
https://gist.github.com/1894e25757c4a7ee701b8d34082f7aa0

**Comment by moxie0** [comment]
We're just using a standard ViewPager, so I think that's an Android bug =(

**Comment by RiseT** [comment]
Confirmed for Android 8.1 (Nexus 5X)

**Comment by RiseT** [comment]
@moxie0 Just FYI - this issue still exists after switching to the HackyViewPager in the latest Signal build.
