### ISSUE TITLE
Can't change image from Gallery 

### ISSUE THREAD

**Issue by wile-coyote** [WhisperSystems/Signal-Android#7334]
I have:
- [X ] searched open and closed issues for duplicates
- [ X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I can change my image in Signal using the Camera, but can't use images from the Gallery.
The APP got full privileges 
### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug
-open Signal
-select options
-click on the image
-click on the image again
-click of Gallery
-select directoy
-select image
-select area of the image
-select DONE

**Actual result:** Old Image remains, new image was not updated
**Expected result:** New image should replace the old images

### Device info

**Samsung Galaxy 7 SM-G930F:** Manufacturer Model XVI
**Android version:** 7.0.0
**Signal version:** 4.14.10

### Link to debug log

https://gist.github.com/anonymous/73ac425094de8ed8b47840587fc838a0

**Comment by gabrielsimoes** [comment]
Does it work if you remove the profile picture before adding a new one?

**Comment by wile-coyote** [comment]
yea, now it works, thanks

**Comment by moxie0** [comment]
From the log, it looks like we can't handle the image format you're trying to use. What format is it?

**Comment by wile-coyote** [comment]
Move to a new image solved the issue, thanks for your support!!!
A proper error message might be a good idea to add.
