### ISSUE TITLE
crash while swiping in media preview

### ISSUE THREAD

**Issue by pgerber** [WhisperSystems/Signal-Android#7335]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I was looking through some pictures and when I swiped to the next picture Signal crashed.

### Steps to reproduce
I've not managed to reproduce the crash.

### Device info

**Device:** Blackphone 2
**Android version:** 6.0.1
**Signal version:** 4.15.0

### Link to debug log
[full log](https://gist.github.com/anonymous/3d49feba26e427187acaada2918aa467)

```
01-10 21:37:27.530  5347 20832 E AndroidRuntime: FATAL EXCEPTION: main
01-10 21:37:27.530  5347 20832 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 20832
01-10 21:37:27.530  5347 20832 E AndroidRuntime: java.lang.IllegalArgumentException: pointerIndex out of range
01-10 21:37:27.530  5347 20832 E AndroidRuntime: 	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
01-10 21:37:27.530  5347 20832 E AndroidRuntime: 	at android.view.MotionEvent.getX(MotionEvent.java:2089)
01-10 21:37:27.530  5347 20832 E AndroidRuntime: 	at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2066)
```

**Comment by moxie0** [comment]
That stack trace doesn't have any of our code in it. I see you're running blackphone's platform, sadly it looks like a ROM bug.
