### ISSUE TITLE
Signal crashing on launch

### ISSUE THREAD

**Issue by jcassano** [WhisperSystems/Signal-Android#7339]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description

Signal crashes immediately after I enter my password in the app. Sometimes there is a lag of a few seconds before it crashes. Seems to have started after update.

Secondarily: After the Android crashed app dialog pops up, if I don't press anything, I am able to access push notifications to read messages that way. But I'm unable to reply or scroll in the notifications.

I'm unsure if this is the same as the other "crash at startup" bug from last month: https://github.com/WhisperSystems/Signal-Android/issues/7262

### Steps to reproduce
- Launch app
- Enter password

**Actual result:** Signal crashes
**Expected result:** Signal doesn't crash

### Screenshots
![screenshot_2018-01-12-16-44-37](https://user-images.githubusercontent.com/569357/34896640-85b65d04-f7b8-11e7-8ca5-30ba7efba929.jpg)

Screenshot shows the secondary behavior of being able to access notifications even after Signal has "crashed"

### Device info

**Device:** Asus Zenfone 2
**Android version:** 5.0
**Signal version:** 4.14.10

### Link to debug log
https://gist.github.com/anonymous/a4a39659521dfc12aa3e79088f21c893

Note that because Signal crashes, I am only able to get the debug log after launching Signal again and before I enter my password, initiating the bug. So I am unsure if this contains the buggy behavior from what would have been a prior Signal "session."

**Comment by jcassano** [comment]
Uninstalling and reinstalling Signal fixed this issue. However, I lost my entire message history as a result.

**Comment by johanw666** [comment]
Looks like an issue with the T-Mobile wap configuration to me. Starting the app in airplane mode might have allowed you to save your message history.

**Comment by moxie0** [comment]
It looks like you manually configured your MMSC, but included some illegal characters as a prefix to the URL. Perhaps a copy and paste error?
