### ISSUE TITLE
Profile photo can't be chaged or deleted in Huawei phone.

### ISSUE THREAD

**Issue by Edu4rdSHL** [WhisperSystems/Signal-Android#7340]
I have:
- [ x] searched open and closed issues for duplicates
- [ x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal shows/hide quickly a blank screen when you tried to change/delete the profile photo and it does not allow to do it.

### Steps to reproduce
- Launch the signal app.
- Go to Parameters -> Tap on the profile photo
- Try to change or delete it.

**Actual result:** Signal show/hide quickly a blank screen and does not allow to change delete the profile photo.
**Expected result:** Signal show the options for upload/delete profile photo.

### Screenshots
Can't take screenshots, the event is quick.

### Device info
Device  : HUAWEI HUAWEI VNS-L53 (VNS-L53)
Android : 7.0 (C69B320, VNS-L53C69B320)
Memory  : 24M (0.58% free, 512M max)
Memclass: 192
OS Host : SIA1000073864
App : Signal 4.15.0 or 4.14.10

### Link to debug log
https://gist.github.com/anonymous/b3b000dcbac12e2dcecccf2bf9656236 <- Seems that signal is not debugging the app too.

**Comment by moxie0** [comment]
Unfortunately we can't do anything without a debug log. If you're not familiar with adb logcat, please contact support for help getting a debug log. Thanks!
