### ISSUE TITLE
Signal crashes when submitting debug log

### ISSUE THREAD

**Issue by genodeftest** [WhisperSystems/Signal-Android#7341]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Every time I try to submit a debug log, Signal crashes.

### Steps to reproduce
1. open Signal
2. open "Settings" from vertical dots menu
3. open "Advanced"
4. open "Submit debug log"
5. press "Submit" button

**Actual result:**
I get the "Uploading logs" popup for a few seconds. Then Android tells me "Signal has stopped".

**Expected result:**
Upload just fine.

### Screenshots
not necessary, bug is trivial

### Device info
**Device:** Nokia (HMD Global Oy) 5, TA-1053
**Android version:** 7.1.2
**Signal version:** 4.14.10

### Link to debug log
Could not be created (see steps above). I manually uploaded it: [Debug log](https://github.com/WhisperSystems/Signal-Android/files/1629734/Editor.txt)

**Comment by genodeftest** [comment]
After uninstalling updates to WebView (which I previously installed using [Yalp](https://f-droid.org/packages/com.github.yeriomin.yalpstore/)), the issue is gone. Same is true for the original issue I wanted to report.

Feel free to close this bug report.

**Comment by johanw666** [comment]
When using Yalp, make sure you use the correct Google Services Framework ID, otherwise you might end up downloading app versions for a different Android version.

**Comment by jeremymasters** [comment]
@genodeftest since you created it, I believe you can also close it.

**Comment by genodeftest** [comment]
@johanw666 : Thank you very much for this useful hint! You probably saved me a few hours of finding out why multiple applications crash.
