### ISSUE TITLE
Could not send and receive any message

### ISSUE THREAD

**Issue by OgreTransporter** [WhisperSystems/Signal-Android#7342]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I have a problem with the signal. I can no longer send and receive messages. If friends send me messages they will be marked as sent and read, but no message arrives. When I try to call someone, they only get the message "Bad encrypted message". If I break the connection attempt, a second message "Bad encrypted message" is sent.

### Steps to reproduce
1. Send a message to certain contacts
- The messages are not marked as "sent"
- There is no error message
- The messages are never sent
2. Contact send a message to me
- I've never received a message
- Marked as "send" and "read" on the other device
3. Reset encryption on both devices and try steps 1 and 2 again
- Same result
4. Try to establish a call (Signal) to a contact
- Dialing and waiting on my device
- "Bad encrypted message" on other device
5. Stop calling
- "Bad encrypted message" on other device
6. Calling me via Signal from an other device
- Nothing happened on my device
- Calling and waiting on the other device

### Device info
**Device:** Archos 70 Xenon Color
**Android version:** 5.1
**Signal version:** 4.14.10

### Link to debug log
https://gist.github.com/OgreTransporter/a3486b9e4fb6536e71f5b8c3ec3f5af4

**Comment by moxie0** [comment]
Thanks for the report, but this debug log is empty and we're not able to do anything without one. Please reopen if you're able to capture one, thanks!
