### ISSUE TITLE
Image is not supported and was deleted. Android Samsung S7

### ISSUE THREAD

**Issue by sethgilchrist** [WhisperSystems/Signal-Android#7343]
### Bug description
I have received two messages this week that have read:
"The image file *** is not supported and was deleted." when a contact sent me an MMS. In one case it was a jpg, in the other it was a png. In the case of the jpg it was a direct message to me from the person's phone, in the case of the png it was a group message.  I believe both other parties are using iMessage on iPhones.

### Steps to reproduce
Others who send me messages have no issues. For example, my wife will use both Signal and Textra and I receive her MMSs.

**Actual result:** Get a message that a media file was not supported, and never get the media.
**Expected result:** I expect to get the image delivered and shown in-line with the other messages

### Device info

Device: Samsung S7
Android version: 7.0
Signal version: 4.14.10

### Link to debug log
https://gist.github.com/49ff7e0af07f9ce40af1dd8b7d2b7b84
The latest manifestation was a message received at 12:29:58.

**Comment by moxie0** [comment]
It looks to me like that message was injected by your carrier, not by Signal.
