### ISSUE TITLE
Message doesn’t arrive

### ISSUE THREAD

**Issue by leonardoporpora** [WhisperSystems/Signal-Android#7348]
I have a problem I do not receive messages in a group that I have created. I send the message from the iOS phone and it sends it but it never delivers. And if I try to write from the android the message I get an error where is written that something went wrong and I have to rettey but nothing happen.

**Comment by jeremymasters** [comment]
@leonardoporpora You're going to need to include some error logs.  That template that was there when you opened this was supposed to be filled out.
