### ISSUE TITLE
Mock number for SMS verification for developers

### ISSUE THREAD

**Issue by Radu-Raicea** [WhisperSystems/Signal-Android#7349]
Is there a way to get past the SMS verification screen when building it with Android Studio? (for development purposes)

**Comment by nrizzio** [comment]
This is an issue tracker and not a forum. The appropriate place to ask questions is https://whispersystems.discoursehosting.net.

**Comment by shelbaz** [comment]
Thats a very valid issue IMO. I would like the answer to that question too.
