### ISSUE TITLE
Right swipe to latest picture in media overview is inconsistent

### ISSUE THREAD

**Issue by halb9** [WhisperSystems/Signal-Android#7354]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When you are in your regular phone media gallery the latest pictures are on top. 
And if you swipe trough them there is a 'newest is left - oldest is right' "rule". 

In a signal conversation (or any messenger I suppose) the newest files are on the bottom of your chat history. If you receive multiple messages and you enlarge one of them it make sense to scroll to the right to get the latest picture. 

However if you are in the media overview section for specific chat sessions the latest picture are again at the top. Just like in the regular phone gallery. However this time to get to the latest pictures you have to swipe right. And left to get to the oldest ones. 

I think this is inconsistent and should be reversed to match the experience from the regular phone gallery. 

### Screenshots

will provide if needed. 

### Device info

shouldn't matter for this issue

### Link to debug log

shouldn't matter for this issue

Thanks in advance!
Have a nice day!

**Comment by rainerzufall** [comment]
**illustration of the inconsitency:**

Pictures sent in the order: `1` (oldest), `2`, `3` (newest)

### 1. when looking at the pictures in the media rail:

![screenshot_20180122-135223](https://user-images.githubusercontent.com/12666598/35222177-419d98f4-ff7d-11e7-87b7-da8cec4299ec.png)

- now when you click on the second oldest picture (`2`) you would think that:
`3` is on the left and 
`1` is on the right. 

- BUT: when you swipe to the left you get  `1`
and when you swipe to the right you get `3`. Exactly the opposite what you have seen in the media rail.




### 2. when clicking within the conversation

![screenshot_20180122-135548](https://user-images.githubusercontent.com/12666598/35222234-83c5e858-ff7d-11e7-85ca-0780a7bf3e51.png)

- clicking on the second (`2`) picture and you would think that:
`1` is on the left and 
`3` is on the right. And that is also what you get when you swipe left (`1`) and right (`3`)

**Comment by halb9** [comment]
With 4.15.3 your change reversed the media order in ViewPager. Looks good. 
Unfortunately it reversed the order within a conversation as well where newest files are now left and the older ones are on the right. 

Is this intendet?

**Comment by moxie0** [comment]
"reversed the order within a conversation" - I don't know what you mean by this

**Comment by pgerber** [comment]
I believe what @halb9 noticed is that when you click on a picture in a conversation you have to swipe right to see newer pictures but when you click on a picture in *All media* you have to swipe left.

**Comment by halb9** [comment]
Maybe it is a bit easier to understand with pictures. I'll try my best. 

---------------------------------------------------------------

![phonegallery](https://user-images.githubusercontent.com/18451020/35297656-95ab77d6-0077-11e8-923e-2f6306e25da0.png)

This is your normal phone media gallery. Newest files are on top. Oldest files are on the bottom. If you tap on 5 it fills up the whole screen. Now you swipe from left to right to see 4. Or you swipe from right to left to see 6. 
This is what I mean when I say "Newest is left, oldest is right". 

---------------------------------------------------------------

![signal gallery](https://user-images.githubusercontent.com/18451020/35297683-ae3e4940-0077-11e8-978b-aa77e0b19cda.png)

This is signals media ViewPager. The section where 'all the stuff you ever sent' is nicely displayed. 

In 4.15.2 although newest files are on top and oldest are on the bottom, you had to swipe from right to left to see the newest pictures. Which gave it a "newest is right, oldest is left" feel. 
This is what I meant when I said it is inconsistent to the phone gallery. 

Thankfully this changed with 4.15.3! 

Which brings me the to the conversation. 

---------------------------------------------------------------

![conversation](https://user-images.githubusercontent.com/18451020/35297753-e4026e12-0077-11e8-9f5f-0e4bd4c5eb0d.png)

Contrary to both gallerys, in a conversation newest or latest files are not on top, but on the bottom. 
So when I tap on 2 and it fills up the screen I expect 1 to be on the right. Meaning a swipe from right to left. 
And exactly that changed with the recent update to 4.15.3 
It should be: Newest is right, oldest is left.
It is atm: Newest is left, oldest is right. 

Does this make it a bit more clear? ;)

PS: Just a stupid thought. But how about right-to-left languages? Maybe this applies to them in exactly the opposite way.

**Comment by moxie0** [comment]
Oh I see, you want *different* swiping behavior depending on where the user entered from. Hmm.

**Comment by halb9** [comment]
> you want different swiping behavior

I wouldn't necessarily say that **I** want it. It just feels counterintuitive to me. 

> depending on where the user entered from

I don't know what that means.

**Comment by halb9** [comment]
4.15.5 looks good to me. 

Thank you!

**Comment by FeuRenard** [comment]
I don't like the inconsistency introduced by 14644077e7d8b09061b11b87daaa44d151ba5705. Just see the following use case:

### Steps to reproduce
- open a conversation
- tap on an image
- now images on the right are more recent
- tap on "All media" in the action bar
- tap on any image

**Actual result:** Now images on the left are more recent.
**Expected result:** Like before: images on the right are more recent.

I get the point that gallery apps tend to have left images more recent while e.g. WhatsApp has right images more recent (Wire & Threema have more recent images on the left, like the gallery apps). We should not mix these two behaviours. I don't want to argue for any direction, but please decide for one and use it all of the time. I am inclined to the directions of the media rail.

**Comment by p4nci** [comment]
imo, this is like squaring the circle. There is always an use case where swiping is inconsistent/confusing.
before https://github.com/signalapp/Signal-Android/commit/14644077e7d8b09061b11b87daaa44d151ba5705 using "tap on image from conversation" it was bizarre (imho), especially if you have 2 or more pictures in the row. Now we have the problem described by @FeuRenard . This can probably be resolved if taping on "all media" keeps current direction for recent pictures.

Another (imo more problematic) use case:
https://github.com/signalapp/Signal-Android/commit/95ebae5d5f39e4a8391cd3e26cce2f823f2204de in combination with https://github.com/signalapp/Signal-Android/commit/14644077e7d8b09061b11b87daaa44d151ba5705 (see also https://github.com/signalapp/Signal-Android/issues/7329): if you lock the screen and then resume e.g. after 5min, you will probably forget the entry point (tap on image from conversation OR media overview section) and now you have to guess where are the most recent pictures (left or rigght).

**Comment by moxie0** [comment]
I agree that there's probably not a perfect solution here, but I kind of like the contextual swipe direction as a first shot. Maybe that won't work out, or maybe we'll need to include something in the UI that clarifies swipe direction.
