### ISSUE TITLE
Feature Request: Only one notification for multiple messages received at once + Timestamps

### ISSUE THREAD

**Issue by shaaati** [WhisperSystems/Signal-Android#778]
After being offline (flight mode / no internet connection) my device rings/vibrates multiple times, depending on how many messages have been sent by others in the meantime.
Being in a quite active group my device vibrated for about 30 seconds this morning.

I can see the point of being notified that not only one but multiple messages have been received but this should be reworked to a less annoying way (e.g., ring twice for multiple messages).

Additionally, all messages that get then received are displayed with their receiving time.
I would prefer having them displayed with the sending time, which can also be seen by looking in the message details.
Maybe a menu entry to switch between both options would be a good idea because I can imagine people who like it the way it is handled now.

**Comment by mawed** [comment]
I just wanted to create a feature request for some similiar situation.
For when in a group some other people are writing really intense, then the amount of vibrations is really disturbing. So a limit of notifications in an amount of time would be nice.

For example, 3 vibrations in 5 minutes. 
So if 4+ messages come in in 5 minutes (and I leave my phone wihout reading the signal messages), there should only be 3 vibrations.
After the 5 minutes (or if I read the messages) the counter restarts.

Maybe this is to special, maybe not.

**Comment by 2-4601** [comment]
Closing first part in favor of #3165.
Second part duplicate #597.
