### ISSUE TITLE
Optional vibrate when phone is in connected call state.

### ISSUE THREAD

**Issue by ponso** [WhisperSystems/Signal-Android#79]
the vibrate received text notification comes on while phone is in use;  this can be annoying to the other end especially on speaker phone.

Maybe you can look into turning this off?

phone used - Droid2G

**Comment by patcon** [comment]
Just tested this with stock dialer and TextSecure 2.7.0-B1. (fwiw stock dialer was configured with sip, but shouldn't matter)

Texting my phone when not on call vibrated. Texting it when on outgoing call with stock dialer resulted in no vibrate whether on headset or speaker.

I think this can be closed.
