### ISSUE TITLE
Feature request: Mute Group (or any user)

### ISSUE THREAD

**Issue by mbrochh** [WhisperSystems/Signal-Android#801]
Sometimes friends in a group are discussing something I'm not interested in and my phone would go nuts vibrating and ringing all the time. A "Mute for X minutes/hours" feature would be awesome.

**Comment by manhole11** [comment]
Please! This shouldn't be hard to implement and my friends can be very talkative sometimes ^^"
Also, they want this to switch from WA to TS

**Comment by grandchild** [comment]
+1

**Comment by shaaati** [comment]
+1
