### ISSUE TITLE
Display shorter fingerprint, enable sharing of fingerprint

### ISSUE THREAD

**Issue by felixgr** [WhisperSystems/Signal-Android#817]
To enable faster sharing of the fingerprint, let the user copy the fingerprint and send it over a secure channel (inform the user that the channel needs to be secure).

Also, don't display the hex of the fingerprint but rather something the user can easily read out:
- base58-encoding
- poetry-encoding

**Comment by vks** [comment]
Another alternative is what Peerio is doing: Graphical avatars generated from the public key. (Like the automatically generated github avatar, but bigger.)

**Comment by 2-4601** [comment]
In 3.20.0
