### ISSUE TITLE
Speed up message sending 

### ISSUE THREAD

**Issue by vascorppor** [WhisperSystems/Signal-Android#981]
Sending a message seems to include a ssl handshake with the ts server. This expensive operation is problematic in areas with limited coverage or overloaded cells (such as in a demonstration or today's carnival). It can take minutes for a message to be sent. Receiving (via gcm) is much faster. 

Can we speed this up? Maybe keep the socket open for a while? Use some faster re-negotiation? Or do some crypto magic instead of ssl? :-)

**Comment by x12x** [comment]
I'm having this problem too. This is hardly bearable on slowish connections (like on a not-so-fast public wifi). If you quickly send something like 10-20 messages, it takes several seconds to send them all. On whatsapp, it sends all of them in about one second.

**Comment by nrizzio** [comment]
As of ec5ac44cd36907653b03c4cecbb9a82c9fdb0b66, messages are sent and received over a single WebSocket connection. Should this be closed?
