### ISSUE TITLE
Contact List: Show sent indicator & unread message count

### ISSUE THREAD

**Issue by vascorppor** [WhisperSystems/Signal-Android#991]
An idea for better overview of your conversations: The conversation list view (i.e. the one that shows when you open TS) should show:
* the count of unread messages in a conversation
* an indication whether the last message I sent has been acknowledged by the server

**Comment by 2-4601** [comment]
Conversation list has message status indicators now per 7c95adc7e61e8157a686caa19ac8b6c8cf593eae
Message counts are explored more thoroughly in this issue #1198. Closing this in favour of that.
